### ISSUE TITLE
Can't download from FTP server

### ISSUE THREAD

**Issue by Hackmodford** [SDWebImage/SDWebImage#110]
I've just updated my code to the latest version.
However when I try loading an image this is what I get

-[NSURLResponse statusCode]: unrecognized selector sent to instance 0xead06d0
2012-04-29 11:00:35.765 MA Mobile[40457:15b03] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSURLResponse statusCode]: unrecognized selector sent to instance 0xead06d0'
**\* First throw call stack:

This is what I'm using to set the image in a custom cell

[self.customImageView setImageWithURL:[NSURL URLWithString:[NSString stringWithFormat:@"ftp://%@:%@@%@/%@.jpg", [[NSUserDefaults standardUserDefaults] stringForKey:@"ftpusername"],[[NSUserDefaults standardUserDefaults] stringForKey:@"ftppassword"],[[NSUserDefaults standardUserDefaults] stringForKey:@"imagePath"],autoID]] placeholderImage:nil];

**Comment by danipralea** [comment]
can you please let us know how did you actually managed to display an image from ftp ? 
Thanks

**Comment by mythodeia** [comment]
@danipralea unless the image url is a public url you can access without logging in then as far as i know you cannot connect to an FTP server with this library, yet!
