### ISSUE TITLE
'SDWebImage/UImageView+WebCache.h' file not found when archive

### ISSUE THREAD

**Issue by ShumiGmail** [SDWebImage/SDWebImage#132]
The project works fine on simulator but i got the error when i archive project.
I have tried many ways such as:

set these on Header Search Paths - 
”$(TARGET_BUILD_DIR)/usr/local/lib/include”
”$(OBJROOT)/UninstalledProducts/include”

And also set this on User Header Search Paths -
$(BUILT_PRODUCTS_DIR)/../../Headers

However xocde still tell me 'SDWebImage/UImageView+WebCache.h' file not found

**Comment by HotWordland** [comment]
http://stackoverflow.com/questions/10714600/cdvplugin-h-file-not-found-in-cordova-as-component-cleaver 
I solved the issue is add "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" to the Header search Path

**Comment by m-irfan** [comment]
GOTO this file **UIImageView+UIActivityIndicatorForSDWebImage.h**
Change these two lines
```
#import "UIImageView+WebCache.h"
#import "SDImageCache.h"
```

to 

```
#import <SDWebImage/UIImageView+WebCache.h>
#import <SDWebImage/SDImageCache.h>
```

thats it

recompile code and error gone gone

Best Regards,
Happy Coding

**Comment by AVINASHKAUL** [comment]
I faced the same issue when I was using **react-native-fast-Image in React-native app**, My app is a hybrid app with some components written in Objective-c and swift.
react-native-fast-image is wrapper on top of SDWebImage. So I had to add following **$(SRCROOT)/../node_modules/react-native-fast-image/ios/Vendor/SDWebImage (recursive)** to target's **Header Search Paths**.
