### ISSUE TITLE
Load images taking too long or not loading

### ISSUE THREAD

**Issue by manoelfranklin** [SDWebImage/SDWebImage#138]
Hi! Im using SDWebImage to load and cache imagens on a uitableview...

When the uittableview load, all cells appears with the placeholder images there... The real images take too long (more than 40 seconds) to load and in some cases do not load. All images are average 300kb and are stored on an Akamai CDN (Cloud files, rackspace cloud)

Also If i have 20 rows, about 3 o 4 images loads properly but others images do not load... 

Also, the network activity indicator quick disappears and images stop loading

doing more tests, it seems that when the cell appears on the screen, the image loading is triggered but the image after loaded do not draw on the cell... When the cell go out of the screen and come back, it seems that the cell get the image from the cache and show it correctly... Is there anything I have to turn on to auto redraw the cell after the image is loaded or something like this?

The code is justs:
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
  
  // Nome / Identificador da Celula para Reunitilizar Celulas.
  static NSString *CellIdentifier = @"BuscaAmigo";
  
  // Cria celula nova usando o identificador acima.
  BuscaAmigo *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier];
  
  if(cell == nil) {
      cell = [[[NSBundle mainBundle] loadNibNamed:@"BuscaAmigo" owner:nil options:nil] objectAtIndex:0];
  }
  
  NSMutableDictionary *dict = [[NSMutableDictionary alloc] init];
  dict = [buscarArray objectAtIndex:indexPath.row];
  
  [cell.uiivFoto setImageWithURL:[NSURL URLWithString:[dict objectForKey:@"fotoUsuario"]]
                 placeholderImage:[UIImage imageNamed:@"no_user.png"]];  
  cell.IdUsuario = [dict objectForKey:@"idUsuario"];
  cell.uilNome.text = [dict objectForKey:@"nomeUsuario"];
  cell.uilEmail.text = [dict objectForKey:@"emailUsuario"];
  cell.seguindo = [dict objectForKey:@"seguindo"];
  
  dict = nil;
  
  return cell;

}

**Comment by bickram** [comment]
same problem with the collection view .
Why does it takes time to load image from the cache in uicollectionview cell.

**Comment by mythodeia** [comment]
@bickram can you replicate the issue on the demo project?
