### ISSUE TITLE
load local files..

### ISSUE THREAD

**Issue by samiibnauf** [SDWebImage/SDWebImage#153]
Hi ..
I have more than 100 UIButton created view a loop .. I'd like to set images for them from LOCAL application bundle .. i used : 

```
    [btn setImageWithURL:[NSURL URLWithString:@"img.png"]
               placeholderImage:[UIImage imageNamed:@"placeholder.png"]];
```

with no success .. so what is the correct way to do that ..

**Comment by rintoandrews90** [comment]
could you please any methods for loading images from Document Directory

**Comment by bpoplauschi** [comment]
We don't have support for loading images at certain paths. But a way to work around that is to load the image from whatever directory (in this case `Documents`) using for instance `UIImage imageWithContentsOfFile`, and then directly store it into our system using `SDImageCache storeImage`. After that, you will be able to use it as if it was downloaded.

**Comment by bpoplauschi** [comment]
@SerhiiMatvieiev Indeed the image would be stored twice. And cache gets cleared (see the `SDImageCacheConfig` settings. I was offering a workaround, as the requested feature does not exist and I don't see it being implemented.
