### ISSUE TITLE
modifying the picture load request to add headers

### ISSUE THREAD

**Issue by nogece** [SDWebImage/SDWebImage#166]
Hi there,

as far as I can see, SDWebimage does not allow to modify the http-request used for getting images. The start method of SDWebimageDownloader just creates the request and there is no way to do things like adding headers. But there are many good reasons why you could want to add http-request-header, for example:
- the image is loaded from amazon aws S3 and you need an authentication header because the images are private
- any other custom or standards-based http-authentication schemes
- cookies
- the image is not static but generated by a rest or webservice that reacts on certain custom headers
- ...I think there are more.

Is there a proper way to add headers to the NSURLRequest before it get's scheduled? Or do I have to overwrite the SDWebImageDownloader?

thanx
No Gece

**Comment by itsSaad** [comment]
Although this was closed without any reason. But i think this feature request is still valid and needed.

**Comment by abraxascorner** [comment]
I have tried this, but it doesn't work
```objective-c
SDWebImageDownloader *manager = [SDWebImageManager sharedManager].imageDownloader;
[manager setValue:[NSString stringWithFormat:@"Basic %@",authValue] forHTTPHeaderField:@"Authorization"];
```
Is there any solution to do basic authorization with SDWebImage lib?

**Comment by judepereira** [comment]
That worked for me :)

**Comment by farzadshbfn** [comment]
@nogece would you share your approach with `URLProtocol`?
