### ISSUE TITLE
Resize, scale and crop images before caching

### ISSUE THREAD

**Issue by sukhrobkhakimov** [SDWebImage/SDWebImage#170]
How can I resize, scale and crop image coming from url before caching it. I tried to achieve this with the following code.

[cell.profilePicture setImageWithURL:[NSURL URLWithString:[rowData objectForKey:@"pictureUrl"]] placeholderImage:nil];
    cell.profilePicture.image = [self imageByScalingAndCroppingForSize:CGSizeMake(cell.profilePicture.frame.size.width, cell.profilePicture.frame.size.height) image:cell.profilePicture.image];

This produced a strange result. First, it shows a not resized/scaled/cropped version. But, when I scroll down and then go back, it shows a resized/scaled/cropped version. I know that this code first caches images and resizes/scales/crops them. But, I could not come up with a better solution. I think there should be something that enables to do downloading images so as to resize/scale/crop and caching independently. Any ideas?

Thank you.

**Comment by mayqiyue** [comment]
Your solution is not very good! Because you crop the image in the main thread which would block the main thread. You should use this method:
- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL;

in SDWebImageManagerDelegate

**Comment by mayqiyue** [comment]
Your solution is not very good! Because you crop the image in the main thread which would block the main thread. You should use this method:
- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL;

in SDWebImageManagerDelegate

**Comment by mayqiyue** [comment]
Your solution is not very good! Because you crop the image in the main thread which would block the main thread. You should use this method:
- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL;

in SDWebImageManagerDelegate

**Comment by mayqiyue** [comment]
Your solution is not very good! Because you crop the image in the main thread which would block the main thread. You should use this method:
- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL;

in SDWebImageManagerDelegate

**Comment by mayqiyue** [comment]
Your solution is not very good! Because you crop the image in the main thread which would block the main thread. You should use this method:
- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL;

in SDWebImageManagerDelegate

**Comment by Sukhrob** [comment]
Thanks for your reply @mayqiyue. I will try out :).
