### ISSUE TITLE
New Framework distribution - -[UIImageView setImageWithURL:placeholderImage:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by AndyJordan** [SDWebImage/SDWebImage#197]
I've just downloaded the new version with the new framework installation. This certainly simplifies the installation of SDWebImage for me.

But I am getting:
-[UIImageView setImageWithURL:placeholderImage:]: unrecognized selector sent to instance

When I try to use in - (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath

My file is a subclass of UITableViewController and includes:
# import <SDWebImage/UIImageView+WebCache.h>

Any ideas?
Thanks,
Andy

**Comment by priya-vr** [comment]
Guys, My issue is "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIButton sd_setImageWithURL:forState:placeholderImage:]: unrecognized selector sent to instance 0x7f9853d55f50".How can i solve this?

**Comment by mythodeia** [comment]
@priya-vr is ```UIButton+WebCache.h``` & ```UIButton+WebCache.m``` included in your project

**Comment by priya-vr** [comment]
still issue exist,shows the error "[UIButton sd_cancelImageLoadOperationWithKey:]: unrecognized selector sent to instance 0x7f80b061c5c0".?

**Comment by mythodeia** [comment]
are these files included too? ```UIView+WebCacheOperation.h & UIView+WebCacheOperation.m```
if not please make sure you have read the installation notes [here](https://github.com/rs/SDWebImage#installation)

**Comment by priya-vr** [comment]
issue is solved by adding UIView+WebCacheOperation.h & UIView+WebCacheOperation.m.,
Thanks

**Comment by imran411** [comment]
Have you install cocoapods for this project
If no then please intall.

**Comment by RajaSaravanan** [comment]
I installed through cocoapods, for me also its crashing.
