### ISSUE TITLE
SDWebImageOptions enum

### ISSUE THREAD

**Issue by daproject85** [SDWebImage/SDWebImage#215]
Im sorry if this isn't the right place for this... not sure if  there is a way to ask the dev questions. Can someone please tell me what is the purpose of this enum and is the point of the left shit operators please...

**Comment by leoleong** [comment]
Hi Olivier, i'm wondering whether could i use some of the options together? In my case, i want use both of .RetryFailed and .CacheMemoryOnly. Thank u~

**Comment by bpoplauschi** [comment]
You should be able to use the bitwise OR operator: `.RetryFailed | .CacheMemoryOnly`
