### ISSUE TITLE
No visible interface for SDWebImageManager

### ISSUE THREAD

**Issue by modusCell** [SDWebImage/SDWebImage#225]
hi guys, i am using almost all functions however having problem about SDWebImageManager. 

when i try to use the block 

```
    [manager downloadWithURL:imageURL delegate:(id)self options:0
                     success:^(UIImage *image, BOOL cached)
    {

    }
                     failure:nil];
```

getting the error message which you can see below. 

No visible @interface for 'SDWebImageManager' declares the selector 'downloadWithURL:options:progress:completed:'

i am on 10.8.

any idea would welcome. 
thanks.

**Comment by gokalpcaymaz** [comment]
I am getting same error for this. above solution was not worked for me. do you have any suggestion?

**Comment by bpoplauschi** [comment]
Depending on which version of SDWebImage you are using, check the docs and examples for that version. Version 4.0 has renamed `SDWebImageManager.downloadImageWithURL` to `loadImageWithURL`.
