### ISSUE TITLE
Memory problem that caused the crash

### ISSUE THREAD

**Issue by lzylzy1991** [SDWebImage/SDWebImage#2252]
Info | Value
-|-
Platform Name | ios
Platform Version | 11.2
SDWebImage Version | 4.3.0
Integration Method | cocoapods 
Xcode Version | Xcode 9.2
Repro rate | all the time

HI，friend
**UICollectionView  Load more than twenty webp animations
Memory problem that caused the crash**

**Comment by dreampiggy** [comment]
Could you please provide more detail information about the memory warning. 

For example, what size of Animated WebP images are you loading ? 
Did you try disable `shouldDecompressImages` when loading images ?
When did the memory warning notification fired, means does this fired during decoding or the cell reusing and rendering ?

**Comment by lzylzy1991** [comment]
<img width="507" alt="b2b45a70bcbcbfeed9a98e90655128bb" src="https://user-images.githubusercontent.com/14507003/37442894-bac19f7e-27d6-11e8-8695-79d91639604f.png">

Occupies memory close to 100M。
When you continue to slide the UICollectionView will crash

**Comment by PrakashMaharjan** [comment]
Hi @lzylzy1991, 

I also got this issue while loading 150 - 200 images from URL in collection view and scrolling.
Not sure exactly but till now, did not got this issue in real device, while i tested.. but issue often occurs is simulator...
I am still testing.. Can you share your findings till now? Would be helpful..

**Comment by shaktiprakash099** [comment]
i am also having this issues, while collection view  reloading or i am scrolling it crossed 400 Mb and app got crashed [
![screen shot 2018-03-20 at 7 13 33 pm](https://user-images.githubusercontent.com/31213820/37706572-02a8b850-2d26-11e8-9525-2df3d3d7529e.png)
](url)

**Comment by dreampiggy** [comment]
@lzylzy1991 @PrakashMaharjan @shaktiprakash099 Are all of you using Animated WebP in collection view ? But it seems that during 4.2.x -> 4.3.x there is no change on `SDWebImageWebPCoder`. Could you please provide a demo that can trigger this OOM issue

**Comment by PrakashMaharjan** [comment]
HI @dreampiggy, I am not using animated WebP, but its just normal images from url.
The images are about 150 - 200. While loading on collection view and then scrolling in collection view, it crashes. I often got this issue in iOS simulator but have not encountered in real device, when i checked. I feel its the memory issue as mentioned by @shaktiprakash099 and @lzylzy1991

**Comment by mythodeia** [comment]
@PrakashMaharjan how big are the images in terms of size and resolution?

**Comment by shaktiprakash099** [comment]
@mythodeia  my images are 250 to  300 Kb ,the problem is that when the images are completely downloaded the memory impact drastically getting changed from 45 to 400 Mb ,in simulator it not happening as its using MAC memory but in real device its getting crashed ,i have also tried to use 
cache clear ,but  nothing happened .i am very close to my app lunch

**Comment by mythodeia** [comment]
@shaktiprakash099 and whats the resolution of those images? is it lower that 1000x....

**Comment by mythodeia** [comment]
@lzylzy1991 the webp image you posted is a bit moret than 1MB in size. if you have 200 images of this size then the memory will surely rise

**Comment by shaktiprakash099** [comment]
@mythodeia  yes its 125* 125

**Comment by shaktiprakash099** [comment]
@lzylzy1991  did you find any solution for this

**Comment by PadmaPreethi** [comment]
I'm also facing the same issue , memory grows till 1 GB and crashes. But it does not throws memory warning. Instead the log shows "Terminated due to memory error" . I tried disabling shoudCacheInMemory, and the memory usage drastically reduced to 100 MB.

**Comment by PrakashMaharjan** [comment]
Hi @mythodeia ,
they are thumbnail images and are just about 40 - 50 KB  and 300 X 408.
I have JSON array that returns around 150 - 200 thumbnail images that is meant to shown in UICollectionview. But while loading and scrolling often it crashes.

**Comment by randarnold** [comment]
I suggest that you spend some time with Instruments and find out exactly where your problem lies. If you can identify that the issue lies with SDWebImage code and not your code, then propose a fix.

**Comment by shaktiprakash099** [comment]
@PadmaPreethi  where did you write shoudCacheInMemory ,in Viewdidapper or in collection view delegates methods could you please share your code snippet which reduces to 100 mb i am still having 450 Mb memor impact @randarnold  hey i checked with instruments also the reason of high memory impact is SDwebimage

**Comment by PadmaPreethi** [comment]
<img width="916" alt="decompressing disabled" src="https://user-images.githubusercontent.com/13163772/37754222-99f9db58-2dc6-11e8-8bcf-30621446ab9b.png">
I tried disabling decompressing , but the image consumption is still the same just that now it shows in Image_IO_Jpeg_Data (Instead of raster data) .Refer above image.

<img width="918" alt="decompress enabled and caching disabled" src="https://user-images.githubusercontent.com/13163772/37754260-c93cbebc-2dc6-11e8-8f47-63027b36961f.png">
I tried enabling decompression and disabled in memory cache. Memory usage reduced a lot and is always around 200 MB. But when i scroll fast, image views goes blank and loads again (which is expected as in memory cache is disabled). 

When i disabled both decompression and in memory caching, memory consumption even reduced to 100 MB (But again performance lags).

**Comment by PadmaPreethi** [comment]
@shaktiprakash099 : I added it in AppDelegate didFinishLaunchWithOptions.

**Comment by shaktiprakash099** [comment]
@PadmaPreethi  ,here is my App delegate application did finish lunching 
 

     func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: 
         [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
         SDWebImageManager.shared().imageCache?.deleteOldFiles(completionBlock: nil)
         SDImageCache.shared().clearMemory()
         SDImageCache.shared().clearDisk()
         URLCache.shared.removeAllCachedResponses()
         return true
      }
 have you added any thing extra

**Comment by PadmaPreethi** [comment]
@shaktiprakash099 : You just need to set decompression to false,
    [[[SDImageCache sharedImageCache] config] setShouldDecompressImages:NO];
   [[SDWebImageDownloader sharedDownloader] setShouldDecompressImages:NO];

But remember , if you set this to false, the decompression will be done by the UIKit in main thread which will cause a drop in FPS. it's a trade off between memory and performance. Choose according to your need.

**Comment by shaktiprakash099** [comment]
@PadmaPreethi  ,letting performance down its not a good idea ,at the same time i am unable to reduce  memory impact ,what to do ??

**Comment by PadmaPreethi** [comment]
@dreampiggy : Please take a look at the allocations screen shot and let us know if there is any workaround for this.

**Comment by PadmaPreethi** [comment]
Adding a screen shot when Decompression is enabled.

<img width="1413" alt="screen shot 2018-03-22 at 4 37 15 pm" src="https://user-images.githubusercontent.com/13163772/37767260-8573bc34-2def-11e8-9299-76262d6687aa.png">

**Comment by randarnold** [comment]
So your allocations go up and up. You need to look at why. What are the retain counts? Who owns those allocations? Do you have any retain cycles? What is the life cycle of your objects? Any leaks?

You can call methods to dump objects when you get a memory warning, but if those objects still have a positive retain count they will not go away.

You are working in a constrained environment, you have to understand the constraints and work within them. It can be a long hard process to track down memory issues, but the tools available today it much easier. Try figuring all that out without instruments! (I have, thankfully I don't have to do that anymore).

**Comment by PadmaPreethi** [comment]
@randarnold : Verified leaks as well. There is no major leak. Maximum leak is around 600KB thorugh out app usage. My question is why is Raster data or the image jpeg is not getting released from memory during memory warnings.  WIll setting totalCostLimit to SD cache helps ?

**Comment by randarnold** [comment]
Try looking at the retain history of the objects. In normal use, the count goes up and then down to zero when it is released. There is probably a strong reference in there someplace that should be weak or another object that is holding a strong reference that in itself is not being released.

Is your code objective-c? Are you referencing self within any blocks?

**Comment by dreampiggy** [comment]
@PadmaPreethi  Hi. Could you please try to downgrade to the 4.3.0 version. Which I guess that #2228 may related to the memory warning behavior from 4.3.0 -> 4.3.3 all PRs. 

And all of you, could you please provide any demo to simulate this use case about OOM. Or could you please set a break point on the memory warning, then try using Xcode's [Memory Graph Debugger](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/special_debugging_workflows.html) to check who retain the `UIImage` instance ?

**Comment by PadmaPreethi** [comment]
@dreampiggy : Tried downgrading to 4.3.0 , But still the raster data takes up lot of memory. I checked the references of UIIMage object through visual debugger. References seems to be fine (Nothing is retaining it) Also, when i noticed the size of raster data for each uiimage, it's size is between 3-5 MB. That's huge !!

**Comment by dreampiggy** [comment]
@PadmaPreethi Hi, could you please check that whether these `UIImage` instance is still alive and retained by `SDImageCache`, or more specific, in `NSCache` or `SDMemoryCache` (from 4.3.2) ?

And here is a little more description about what `CG raster data`. The `CG raster data` is just the rendered data represent `UIImage`, which can be directlly displayed without any extra cost in `UIImageView`. The opposite one is the normal `UIImage` which just directlly from the Image/IO or method like `-[UIImage imageWithData:]`, which is in `undecompressed` format and must be copied by Core Animation before the `UIImageView` actual rendering it. (You may see some `CA::Render::copy_image` method call, which is what it need to transform the original data to CG raster data)

When you enable `showDecompress` options in `SDImageCache`, `SDWebImageDownloader`, we will try to do this stuff just in background queue to avoid this `copy` happened on main queue to reduce frame rate. However, this may consume more memory. It's a trade-off. If you do not want this behavior or your memory is limit, you can try to disable it.

**Comment by PadmaPreethi** [comment]
@dreampiggy : Yes, i get that point. So SDWebImage  decompression part taking up MB's of data for each image is expected ? If i disable decompression, then it will affect FPS . Is there a better way to handle this situation ?

**Comment by PadmaPreethi** [comment]
@dreampiggy : Sorry if i'm missing something. I have a question. Will SDWbImage retains the raster data as well ? I'm not sure when will the raster data gets deallocated from memory.

**Comment by dreampiggy** [comment]
That `CG raster data` is kept in `UIImage`, acutlly `CGImage`'s internal data, See your visual debugger's screenshot...If Core Animation render you `UIImage` on a `UIImageView`, it automatically create that data and it kept alive...

**Comment by PadmaPreethi** [comment]
Snapshot of rater data ...

<img width="1397" alt="screen shot 2018-03-24 at 7 12 30 pm" src="https://user-images.githubusercontent.com/13163772/37864601-63bcb524-2f97-11e8-8082-37f36bdc35fd.png">

**Comment by PadmaPreethi** [comment]
And check this, so SDWebImage cache maintains the image in cache. That also keeps the raster data in memory. 

<img width="1437" alt="screen shot 2018-03-24 at 7 15 34 pm" src="https://user-images.githubusercontent.com/13163772/37864640-c917b676-2f97-11e8-8c34-dc5feb371cf8.png">

**Comment by dreampiggy** [comment]
@PadmaPreethi All these screenshot in visual debugger are designed behavior if you enable `shouldDecompressImage`. But since we add a memory warning action to clear the memory cache, normally this should not cause crash. 

If you want to limit the memory cost, you can consider these solution.

+ Disable `shouldDecompressImage`
+ Try using `SDWebImageScaleDownLargeImages`, or do your own by using `imageManager:transformDownloadedImage: withURL:`
+ Limit the `maxMemoryCost` and `maxMemoryCountLimit`
+ Consider let your server response the small pixel image or non-alpha image, because the memory data is only related to resolution and channels.
+ Maybe you can only disable memory cache using `shouldCacheImagesInMemory` if you want to render too many images at the same time.

**Comment by dreampiggy** [comment]
Wait...Are you using animated images ? If so, maybe we should talk this from the beginning..

**Comment by PadmaPreethi** [comment]
Nope, we don't use animated images.

**Comment by PadmaPreethi** [comment]
@dreampiggy : Just a thought , will you be able to provide support for adding delegate to the memory cache to get notification when it evicts objects(which NSCache already provides) ? Will be useful to debug when we set some certain parameters like maxMemoryCountLimit or maxMemoryCost.

Currently i have set maxMemoryCountLimit and it seems to be better than before.

**Comment by dreampiggy** [comment]
@PadmaPreethi This can be accomplish by 5.x using the custom memory cache in #2195 . We seems does not consider to add support to 4.x because this may cause some API-changes.

However, I understand your use case, currently just directly access the internal memory cache property and set a delegate :)

```objective-c
    SDImageCache *imageCache;
    NSCache *memCache = [imageCache valueForKey:@"memCache"];
    if (![memCache isKindOfClass:[NSCache class]]) {
        return;
    }
    memCache.delegate = self;
```

**Comment by PadmaPreethi** [comment]
@dreampiggy : Thanks !

**Comment by wucanqi** [comment]
same issue

**Comment by PadmaPreethi** [comment]
@dreampiggy : valueForKey:@"memCache" always returns nil.

**Comment by dipkasyap** [comment]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          | ios 
 Platform Version         |11.0 
 SDWebImage Version    |4.0
 Integration Method      |cocoapods
 Xcode Version            |Xcode 9 
 Repro rate              | all the time (100%) 
 Repro with our demo prj |NA
 Demo project link       | NA

### Issue Description and Step

Loading image normally with SDSebImage on UITableview Cell 

![screen shot 2018-06-27 at 4 36 48 pm](https://user-images.githubusercontent.com/12591229/41969918-b9454d22-7a28-11e8-9ef1-cb13671f45d3.png)

**Comment by bpoplauschi** [comment]
@dreampiggy do you think that the 5.0 release will provide a workaround for this issue? I can't keep up with this conversation :)

**Comment by zhongwuzw** [comment]
Related to some architecture issues, users provide some good comments for us to find issues.

**Comment by nvduc2910** [comment]
I got the same issue. 

Look like when I am loading many WebP at the time then it will be crashed without raised memory warning. Because I see sometimes the memory was taken about 200mb but It crashed immediately without memory warning.

Could you please check this issue?

**Comment by dreampiggy** [comment]
> the memory was taken about 200mb 

This is the In-App process memory, if the other process like Render server process, occupy many memory, the Jetsam is still be triggered and your App get killed.

You can using Xcode, to check the `Free Memory` in memory footprint tabs, but not only about `App Process`.

You can also using Instruments, which have a `Allocation` template, to check all the memory footprint used by your App. When your app is terminated, you can check all persistent object which occupy the large memory.

**Comment by nvduc2910** [comment]
![img_3943](https://user-images.githubusercontent.com/12984583/53744956-adb5c000-3ed0-11e9-85de-853535de51d1.PNG)

Thank for your reply, I will check.

At the time I must load about ten webp. I think it's really large and take huge memory then it will be crashed without raise memory warning. this is bad so any solution, please

**Comment by Baolv** [comment]
I got same issue. When i try load about 10->20 WebP at the same time, my app crashed and show this message: "Message from debugger: Terminated due to memory issue". Although memory just 70mb 
Btw: I test on iphone 6 and I config on Appdelagate like this:
```
SDImageCache.shared().maxMemoryCost = 1024 * 1024 * 120
        SDImageCache.shared().config.shouldDecompressImages = false
        SDWebImageDownloader.shared().shouldDecompressImages = false
        SDImageCache.shared().config.diskCacheReadingOptions = NSData.ReadingOptions.mappedIfSafe
```

**Comment by nvduc2910** [comment]
<img width="898" alt="screen shot 2019-03-05 at 5 28 01 pm" src="https://user-images.githubusercontent.com/12984583/53799215-798fdd00-3f6c-11e9-95c0-322fc9eebab8.png">
Could you take a look this screen?

**Comment by dreampiggy** [comment]
> <img width="898" alt="screen shot 2019-03-05 at 5 28 01 pm" src="https://user-images.githubusercontent.com/12984583/53799215-798fdd00-3f6c-11e9-95c0-322fc9eebab8.png">
> Could you take a look this screen?

This is a designed behavior.

You must loading Animated WebP. And maybe your animated webp resolution is too large (260MB, assume RGBA8888, the pixel count is 68,157,440, nearly like a 8255x8255 pixels). It’s really not recommaned to load such an image. It’s better to let your inage server to do a thumb and scale before loading.

For that CGBitmapContext RAM usage. The animated webp, must keeping a canvas the same size as plaeceholder (in iOS, it’s the CGContext) to draw frames, it’s WebP standard. Maybe there are no better way to avoid this.

**Comment by dreampiggy** [comment]
Actually, I’ve done one feature, to support the **Thumb Decoding**, which means even the original image is 100000x100000 pixels, the decoder can decode a scaled pixel width. It’s supported by the Image IO(Apple built-in, JPEG/PNG/HEIF only) and WebP(using libwebp). See #2560

However, many other decoder can not support this, and it need some more APIs in 5.0, I don’t know whether it’s suitable or not to add to our milestone.

I can create one MR later to let you have a try.

**Comment by nvduc2910** [comment]
> > <img alt="screen shot 2019-03-05 at 5 28 01 pm" width="898" src="https://user-images.githubusercontent.com/12984583/53799215-798fdd00-3f6c-11e9-95c0-322fc9eebab8.png">
> > Could you take a look this screen?
> 
> This is a designed behavior.
> 
> You must loading Animated WebP. And maybe your animated webp resolution is too large (260MB, assume RGBA8888, the pixel count is 68,157,440, nearly like a 8255x8255 pixels). It’s really not recommaned to load such an image. It’s better to let your inage server to do a thumb and scale before loading.
> 
> For that CGBitmapContext RAM usage. The animated webp, must keeping a canvas the same size as plaeceholder (in iOS, it’s the CGContext) to draw frames, it’s WebP standard. Maybe there are no better way to avoid this.


All Webp I am loading always less 2MB. but the behavior is loading many webp at the time ( about 15 - 20 webp) . The UI like this screen. 

An example webp: https://storage.googleapis.com/myscoop/scoops/webp/5d5o3jqjsmkshry3ilkcew_320.webp

![image](https://user-images.githubusercontent.com/12984583/53850937-7db10e80-3fef-11e9-8a4d-311c2709c39e.png)

Even I loaded on iphone xs but it's still crash. 

Please check.

**Comment by nvduc2910** [comment]
> > the memory was taken about 200mb
> 
> This is the App Process memory. If the other process like Render server process, occupy too much memory, the Jetsam is still be triggered and your App get killed.
> 
> And, the memory warning is always dispatched on the main queue, so if you're alloacting large memory in the global queue outside the main queue, your app may already been killed before you receive memory warning... 😥
> 
> You can using Xcode, to check the `Free Memory` in memory footprint tabs, but not only about `App Process`.
> 
> You can also using Instruments, which have a `Allocation` template, to check all the memory footprint used by your App. When your app is terminated, you can check all persistent object which occupy the large memory.

![image](https://user-images.githubusercontent.com/12984583/53854347-ba830280-3ffb-11e9-8d95-02ff01415f01.png)

I follow by your instruction and got crashed. then I see that.

**Comment by dreampiggy** [comment]
@nvduc2910 The size of WebP files does not count anything. Maybe you're not famaliar with What is Image Bitmap (The array contains pixels, which is used for Low-level API and Hardware to render), and what is Compressed Image Format( Like JPEG/PNG/WebP). You can have a check in https://en.wikipedia.org/wiki/Image_file_formats and https://en.wikipedia.org/wiki/Bitmap

A image bitmap memory usage = bytes per pixel * pixel count, it does not related to what the compressed image format (WebP or something) size. So if you're using image with alpha (4 channels), the bytes usage = 4 * pixel count, only related to the resolution.

Could you please have a check or show me some of your images to load ? I remember the `SDImageCache` have a limit for bitmap image cached in memory, if the limit is hitted, the image should be purged to free up memory.

**Comment by nvduc2910** [comment]
I think the problem here is the memory consume suddenly so it crashed without raise memory warning because I already set limit cache but it still crashes.

**Comment by nvduc2910** [comment]
https://storage.googleapis.com/myscoop/scoops/webp/zztnkorims5k6fexsw7q_320.webp
https://storage.googleapis.com/myscoop/scoops/webp/w9yihxxutqsrjzp6drbtfw_320.webp
https://storage.googleapis.com/myscoop/scoops/webp/stcis6rctzcjafckbtfng_320.webp
https://storage.googleapis.com/myscoop/scoops/webp/mtu1mtm0otu3ms44mjg5oty_320.webp
https://storage.googleapis.com/myscoop/scoops/webp/5d5o3jqjsmkshry3ilkcew_320.webp

I share you some webp that I am loading in my application. some link like that about 15-20 webp load at the time will be crashed. 

Please check.

**Comment by WXXXXH** [comment]
swift 4.0 ios 12 Xcode 10.3  
Message from debugger: Terminated due to memory issue
IGlist is pic list
![1568102041312](https://user-images.githubusercontent.com/35984644/64594940-8ee63800-d3e3-11e9-8462-b2c36d9e76da.jpg)

**Comment by ankit0812** [comment]
Has anybody found a solution to this yet?

**Comment by ZUCheema** [comment]
@ankit0812 , I just faced the same issue in showing around 500 images on collection view. 
I manually stored images in Documents Directory with their paths in CoreData and loaded images from remote only if they don't existing in local storage, i.e my own disk cache. 

Now if I load images with SDWebImage either from localUrl or remoteUrl, the memory is taken up-to 1.16 Gb which huge. 

So I tested to assign local images directly if with `cell.tempImageView.image = UIImage(data: try! Data(contentsOf: url))` and remoteImage with SDWebImage with option `fromLoaderOnly`(then I cached images to documents in completion handler). Now memory is reduced to around 400Mb when some images were new and some were cached and further reduced to around 100Mb when most images are loaded locally, i.e without SDWebImage. 

So, I think the issue is purely with SDWebImage loader and this can be a good workaround.

**Comment by dreampiggy** [comment]
Using SDWebImage without cache is simple (but maybe sometime useful) way...That `fromLoaderOnly` and `fromCacheOnly` actually designed for another cases.

But anyway if you can provide a more re-producable demo for us to investigate, it's better
