### ISSUE TITLE
cachedFileNameForKey crash 

### ISSUE THREAD

**Issue by tjcsr** [SDWebImage/SDWebImage#2350]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 11.0
 SDWebImage Version      | e.g. 4.3.3
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 9
 Repro rate              | e.g. sometimes x%
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/5518856/41142367-fcda09de-6b27-11e8-9699-957f78045606.png">

**Comment by dreampiggy** [comment]
Seems like a thread-safe issue, or the memory issue (that `memmove` call failed). Check it later

**Comment by tjcsr** [comment]
@dreampiggy Whether to find a solution？

**Comment by bpoplauschi** [comment]
@tjcsr thanks for your interest in our project. I kindly ask that you fill in the info in the issue template (table above). Also, can you provide a stack trace for the crash? Does it crash constantly? Can you reproduce it in a small demo project?

**Comment by bpoplauschi** [comment]
Closing due to lack of response and more info. Please reopen if it's still an issue.

**Comment by kyleYang** [comment]
I meet this problem.
The fabric crash log is that!




0 | libsystem_malloc.dylib | szone_free + 2944
1 | libsystem_malloc.dylib | szone_free + 1744
2 | CoreFoundation | CFRelease + 1088
3 | CoreFoundation | _CFStringCreateWithFormatAndArgumentsAux2 + 268
4 | Foundation | -[NSPlaceholderString initWithFormat:locale:arguments:] + 168
5 | Foundation | +[NSString stringWithFormat:] + 68
6 | SDWebImage | SDImageCache.m line 186-[SDImageCache cachedFileNameForKey:]
7 | SDWebImage | SDImageCache.m line 167-[SDImageCache cachePathForKey:inPath:]
8 | SDWebImage | SDImageCache.m line 172-[SDImageCache defaultCachePathForKey:]
9 | SDWebImage | SDImageCache.m line 337-[SDImageCache diskImageDataBySearchingAllPathsForKey:]
10 | SDWebImage | SDImageCache.m line 370-[SDImageCache diskImageForKey:]
11 | SDWebImage | SDImageCache.m line 412__42-[SDImageCache queryDiskCacheForKey:done:]_block_invoke
12 | libdispatch.dylib |  

and the line 186
    NSString *filename = [NSString stringWithFormat:@"%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%@",
                          r[0], r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9], r[10],
                          r[11], r[12], r[13], r[14], r[15], [[key pathExtension] isEqualToString:@""] ? @"" : [NSString stringWithFormat:@".%@", [key pathExtension]]];

**Comment by zhongwuzw** [comment]
@kyleYang Can you give an integrated crash log which contains all related information?
