### ISSUE TITLE
SDImageCache not clearing

### ISSUE THREAD

**Issue by JaapManenschijn** [SDWebImage/SDWebImage#250]
With the latest version of SDWebImage, calling something like:
[[SDImageCache sharedImageCache] clearMemory] does not actually clear your image cache.

This has been keeping me busy for a bit, as I wanted to force my program to always load the image from the web and not get it from cache. 
I came to a point where I used [[SDImageCache sharedImageCache] queryDiskCacheForKey: done:] ,after clearing the cache first, and it would not find anything. 
Then on the next line i'd use [imageView setImageWithURL: placeholderImage: completed:], which you'd expect to load the image from the web, as the image wasn't found previously. 
However, it'd still show the old image from the memory (wtf?).

I started browsing through the code and came up to the following:
Both SDImageCache and SDWebImageManager (used for downloading the image) have are singletons, as in they have a static sharedImageCache (or sharedManager) to get an instance of the class.
In the implementation of both classes, a new imageCache is created. So instead of having one imageCache across the classes, there's actually two imageCaches.

Clearing the cache through [[SDImageCache sharedImageCache] clearMemory] does clear a cache. But it's not the cache you'd want cleared.

I resolved my problem by changing the implementation of SDWebImageManager slightly.
I changed the init method a bit. I replaced the line:
_imageCache = SDImageCache.new;

with the following:
_imageCache = [SDImageCache sharedImagecache];

This way you'll have the same imageCache across both classes.
I don't know if this is the way it is supposed to be, but it made sense (atleast for my case).

**Comment by sawijaya** [comment]
after i using custom disk cache path, the method clearDisk() not working for clear disk cache.
here is my code

let caches: [AnyObject]? = BOPreferences.sharedInstance.caches.allCaches()
if let caches = caches {
for(_, value) in caches.enumerate() {
var cache: [String: AnyObject] = value as! [String: AnyObject]
let namespace: String = cache["namespace"] as! String
let directory: String = cache["diskCacheDirectory"] as! String
let sdImageCache: SDImageCache = SDImageCache(namespace: namespace, diskCacheDirectory: directory) // => custom disk patch cache
sdImageCache.clearDisk() // ===> after call this not working (my cache file still on there)
}
}

why it's not working for clearDisk()?

**Comment by handiansom** [comment]
I got a problem with  my memory. I am using the SDWebimage with ProgressView. Is there a way to clear the cached memory? disk and ram?

**Comment by bpoplauschi** [comment]
@handiansom you can use `[[SDWebImageManager sharedManager].imageCache clearMemory]` or `[[SDWebImageManager sharedManager].imageCache clearDisk]`

**Comment by handiansom** [comment]
@bpoplauschi   Thank you so much for your answer. It really helped me reduce memory usage.

**Comment by AmeerChand** [comment]
on Logout Method....
SDImageCache.sharedImageCache().clearMemory()
        SDImageCache.sharedImageCache().cleanDisk()
        SDImageCache.sharedImageCache().clearDisk()

**Comment by EndLess728** [comment]
> on Logout Method....
> SDImageCache.sharedImageCache().clearMemory()
> SDImageCache.sharedImageCache().cleanDisk()
> SDImageCache.sharedImageCache().clearDisk()
> after login i switched off the internet.
> on Scrolling The TableView i am Still getting Images. Why?
> while there is no internet Connection.

same thing is happening is with me , when i logout from the app and login again into the app using other user credentials it still shows old user image for a while and then it shows the image of the logged in user

**Comment by criistii-toptal** [comment]
One of my customers complains about a similar issue. He is getting images from a different session when he switches accounts.

> SDImageCache.shared.clearDisk {
>                 SDImageCache.shared.clearMemory()
>                 // other sign-out logic
>             }
