### ISSUE TITLE
Use FaceAware cause Memory to Large

### ISSUE THREAD

**Issue by CocoaML** [SDWebImage/SDWebImage#2502]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0
 SDWebImage Version      | 4.2.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9
 Repro rate              | 100%
 Repro with our demo prj | NO
 Demo project link       | I will try to create a Project later.

### Issue Description and Steps

I use the Third-party libraries   
> FaceAware  ( https://github.com/BeauNouvelle/FaceAware )

when the ImageView set image Completed,  I Use FaceAware to deal with ImageView like The Code: 

```objc
[self sd_setImageWithURL:[NSURL URLWithString:url]
        placeholderImage:nil
                 options:SDWebImageScaleDownLargeImages
               completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
    weakself.focusOnFaces = YES;
    weakself.debugFaceAware = YES;
}];
```

When I scroll TableView, The memory growth too large,   Maybe it cause A circular reference Or Something not destruction, How can I release the  Memory? 

Thanks !

**Comment by bpoplauschi** [comment]
@CocoaML thanks for reporting back to us.
First of all, I have re-added the issue template info you have removed from the issue description. We need you to fill in the info in this table to we can better understand the conditions of your issue.
Secondly, you are using another 3rd party code, so I think the best thing to do is just use Xcode profiler to see what is causing the memory grow.
One idea is to disable the FaceAware code and see if the issue still reproduces.
I see you have set `SDWebImageScaleDownLargeImages`. If you are dealing with large images, that might cause the memory growth.
You can also try disabling the decompression and see if that takes care of the mem issue
```objc
[[SDWebImageDownloader sharedDownloader] setShouldDecompressImages:NO];
[[[SDImageCache sharedImageCache] config] setShouldDecompressImages:NO];
```

**Comment by CocoaML** [comment]
> ### New Issue Checklist
> * [x]  I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
> * [x]  I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
> * [x]  I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
> 
> ### Issue Info
> Info	Value
> Platform Name	 iOS
> Platform Version	11.0
> SDWebImage Version	. 4.2.0
> Integration Method	 cocoapods 
> Xcode Version	 Xcode 9
> Repro rate	e.g. all the time (100%) 
> Repro with our demo prj	 does it happen with our demo project? NO.
> Demo project link	I will try to create a Project later.
> ### Issue Description and Steps

> I use the Third-party libraries
> 
> > FaceAware  ( https://github.com/BeauNouvelle/FaceAware )
> 
> when the ImageView set image Completed, I Use FaceAware to deal with ImageView like The Code:
> 
> ```objc
> [self sd_setImageWithURL:[NSURL URLWithString:url]
>         placeholderImage:nil
>                  options:SDWebImageScaleDownLargeImages
>                completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
>     weakself.focusOnFaces = YES;
>     weakself.debugFaceAware = YES;
> }];
> ```
> 
> When I scroll TableView, The memory growth too large, Maybe it cause A circular reference Or Something not destruction, How can I release the Memory?

@bpoplauschi Thanks for your quick reply. And I  I have added the issue info.  I set local Image and enable  FaceAware code, The memory is Fine, but when I use SDWebImage to load net Image, the memory is growing.  and I try to set the code.

`[[SDWebImageDownloader sharedDownloader] setShouldDecompressImages:NO];

[[[SDImageCache sharedImageCache] config] setShouldDecompressImages:NO];`

but it does not work. and I think what cause A circular reference Or Something not destruction.

Thanks for your quick reply.

**Comment by CocoaML** [comment]
> @CocoaML what do you mean by
> 
> > I try to set the code. but it does not work.
> 
> What doesn't work? Doesn't compile? Doesn't run? The issue still happens with this code?

Sorry , I mean I use the code: 
 [[SDWebImageDownloader sharedDownloader] setShouldDecompressImages:NO];
[[[SDImageCache sharedImageCache] config] setShouldDecompressImages:NO];
and the memory also grows , not reduce my memory issue.

**Comment by dreampiggy** [comment]
@CocoaML Hi.

Your demo code does not contains any retain cycle (Only if you retain the `self` in the compltionBlock, it will cause a short-term (until load finish) retain cycle). I guess it may because of the `FaceAware` code that open too much of bitmap context to detect the faces (I don't check their source code, you can have a try).


The best way to view your memory usage, firstlly try Xcode `Memory Graph Debugger`. You can see each alive object's retain chain. There may be a ❕mark in the object which is in retain cycle.

![image](https://user-images.githubusercontent.com/6919743/46939126-132b2080-d098-11e8-9acb-7b1c210a9f05.png)

For more advanced debug, you need Instruments and using `Leak` scheme to check the status.

![image](https://user-images.githubusercontent.com/6919743/46939155-2ccc6800-d098-11e8-9b47-ea1802a8c993.png)

**Comment by CocoaML** [comment]
> @CocoaML Hi.
Thanks, Now I have a try.

**Comment by CocoaML** [comment]
> @dreampiggy  Hi.

Thanks, Now I have a try.

**Comment by CocoaML** [comment]
@dreampiggy @bpoplauschi Hi.
About The memory issue, I did a demo, link is Here,   

https://github.com/CocoaML/SDWebImageAndFaceAwareDemo 
The memory report shows memory used so high.

What can do to reduce memory ?

**Comment by zhongwuzw** [comment]
@CocoaML, I'll try to find the issue, but I need some extra informations, refer to your issue template, the issue only appear in `iOS11`? Which device can reproduce? Simulator can reproduce? How to define large memory? 300M? 1G?

I just run the demo you post on simulator `iOS12` and memory works fine.
