### ISSUE TITLE
addOperation:` 可能会导致死锁？

### ISSUE THREAD

**Issue by zhongguoming** [SDWebImage/SDWebImage#2521]
// `addOperation:` does not synchronously execute the `operation.completionBlock` so this will not cause deadlock.

这个注释怎么解释？

**Comment by kinarob** [comment]
@zhongguoming Thank you very much for your interest in our framework, I highly recommend that you look at apple's [documentation](https://developer.apple.com/documentation/foundation/nsoperationqueue), which explains it very clearly!

**Comment by bpoplauschi** [comment]
Can we close the issue?

**Comment by dreampiggy** [comment]
You mean this line ? https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/SDWebImageDownloader.m#L307

Just as the comment shows, we use a GCD semaphore `disaptch_semaphore_wait` at the beginning of that function call, and we also use `disaptch_semaphore_wait` inside the `operation.compltionBlock`.

If Apple call your `operation.compltionBlock` after you call `NSOperationQueue.addOperatation` in synchronously, what will happen ?  There may be two serail call to `disaptch_semaphore_wait`, and so that the semaphore count will +2. But each of them waiting for another to release the lock. This cause a dead lock.

If Apple does not call it synchronously, the first semaphore (from the `SDWebImagDownloader`) will be released. And then the `NSOperation.completionBlock`'s semaphore can balance it as well. No dead lock occur.

**Comment by zhongguoming** [comment]
yes, this is line.i try to understand deadlock occur. but ignor the disaptch_semaphore_wait.
Thank you!







------------------ 原始邮件 ------------------
发件人: "DreamPiggy"<notifications@github.com>;
发送时间: 2018年10月31日(星期三) 下午5:21
收件人: "SDWebImage/SDWebImage"<SDWebImage@noreply.github.com>;
抄送: "崔志伟"<2213139162@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [SDWebImage/SDWebImage] addOperation:` 可能会导致死锁？ (#2521)




You mean this line ? https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/SDWebImageDownloader.m#L307
 
Just as the comment shows, we use a GCD semaphore disaptch_semaphore_wait at the beginning of that function call, and we also use disaptch_semaphore_wait inside the operation.compltionBlock.
 
If Apple call your operation.compltionBlock after you call NSOperationQueue.addOperatation in synchronously, what will happen ?  There may be two serail call to disaptch_semaphore_wait, and so that the semaphore count will +2. But each of them waiting for another to release the lock. This cause a dead lock.
 
If Apple does not call it synchronously, the first semaphore (from the SDWebImagDownloader) will be released. And then the NSOperation.completionBlock's semaphore can balance it as well. No dead lock occur.

**Comment by zhongguoming** [comment]
the semaphore count will reduce  after call disaptch_semaphore_wait ,i disagree ' so that the semaphore count will +2'. i think the semaphore count will -1.






------------------ 原始邮件 ------------------
发件人: "DreamPiggy"<notifications@github.com>;
发送时间: 2018年10月31日(星期三) 下午5:21
收件人: "SDWebImage/SDWebImage"<SDWebImage@noreply.github.com>;
抄送: "崔志伟"<2213139162@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [SDWebImage/SDWebImage] addOperation:` 可能会导致死锁？ (#2521)




You mean this line ? https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/SDWebImageDownloader.m#L307
 
Just as the comment shows, we use a GCD semaphore disaptch_semaphore_wait at the beginning of that function call, and we also use disaptch_semaphore_wait inside the operation.compltionBlock.
 
If Apple call your operation.compltionBlock after you call NSOperationQueue.addOperatation in synchronously, what will happen ?  There may be two serail call to disaptch_semaphore_wait, and so that the semaphore count will +2. But each of them waiting for another to release the lock. This cause a dead lock.
 
If Apple does not call it synchronously, the first semaphore (from the SDWebImagDownloader) will be released. And then the NSOperation.completionBlock's semaphore can balance it as well. No dead lock occur.

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/47781481-bc307700-dd38-11e8-97a5-20640544067c.png)

**Comment by zhongguoming** [comment]
please say detail about the result of the semphore count






------------------ 原始邮件 ------------------
发件人: "DreamPiggy"<notifications@github.com>;
发送时间: 2018年10月31日(星期三) 晚上6:14
收件人: "SDWebImage/SDWebImage"<SDWebImage@noreply.github.com>;
抄送: "崔志伟"<2213139162@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [SDWebImage/SDWebImage] addOperation:` 可能会导致死锁？ (#2521)

**Comment by dreampiggy** [comment]
...Just simplify the problem. That code just like this if `Apple call your completionBlock synchronously when operation is already empy`. And thanks, they do not because they will always dispatch to queue to execute the completionBlock (typically another queue, but can be the same queue running for opearation).

```
int main(int argc, char *argv[]) {
	@autoreleasepool {
		dispatch_semaphore_t lock = dispatch_semaphore_create(1);
		
		__auto_type completionBlock = ^{
			dispatch_semaphore_wait(lock, DISPATCH_TIME_FOREVER);
			printf("operation finish");
			dispatch_semaphore_signal(lock);
		};
		
		dispatch_semaphore_wait(lock, DISPATCH_TIME_FOREVER);
		printf("add opeartion");
		completionBlock();
		dispatch_semaphore_signal(lock);
		
		printf("here"); // never go here
	}
}
```

**Comment by zhongguoming** [comment]
addOperation()添加不管是同步操作还以异步操作，queue都会有单独的线程去异步执行。所以感觉死锁应该不会发生。
我写了一个operation的子类，直接重写main()方法，然后添加到queue里，发现它仍然不会同步执行operation。所以猜测，在调用addOperatation之后,不会同步调用operaion。


------------------ 原始邮件 ------------------
发件人: "DreamPiggy"<notifications@github.com>;
发送时间: 2018年10月31日(星期三) 下午5:21
收件人: "SDWebImage/SDWebImage"<SDWebImage@noreply.github.com>;
抄送: "崔志伟"<2213139162@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [SDWebImage/SDWebImage] addOperation:` 可能会导致死锁？ (#2521)




You mean this line ? https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/SDWebImageDownloader.m#L307
 
Just as the comment shows, we use a GCD semaphore disaptch_semaphore_wait at the beginning of that function call, and we also use disaptch_semaphore_wait inside the operation.compltionBlock.
 
If Apple call your operation.compltionBlock after you call NSOperationQueue.addOperatation in synchronously, what will happen ?  There may be two serail call to disaptch_semaphore_wait, and so that the semaphore count will +2. But each of them waiting for another to release the lock. This cause a dead lock.
 
If Apple does not call it synchronously, the first semaphore (from the SDWebImagDownloader) will be released. And then the NSOperation.completionBlock's semaphore can balance it as well. No dead lock occur.
