### ISSUE TITLE
What happens when disk memory is full.

### ISSUE THREAD

**Issue by MagLiC** [SDWebImage/SDWebImage#2526]
What happens when I keep writing to disk when the memory is full.
It will release cache? 
it will crash?

**Comment by dreampiggy** [comment]
> What happens when I keep writing to disk when the memory is full.

If you are writing disk cache using method like `-[SDImageCache storeImage:forKey:completion:`, you should note the documentation shows that this will also store the image into memory as well.

In 4.x, we have no built-in method to **store disk cache only**. You can only use some hack way like using the internal method `_storeImageDataToDisk:`. In 5.x, we introduce the `SDImageCache` protocol, which allows you to **store disk cache only** using `storeImage:imageData:forKey:cacheType:completion:` with `SDImageCacheTypeDisk`.

**Comment by bpoplauschi** [comment]
I think @MagLiC is referring to the disk, not the memory cache. 
See #2366 - I think that is the error you get when disk is full.

**Comment by dreampiggy** [comment]
That `memory  is full` seems a misunderstanding of this issue.
