### ISSUE TITLE
Image Desaturation feature 

### ISSUE THREAD

**Issue by sureshcapternal** [SDWebImage/SDWebImage#2544]
Platform Name : ios
 Xcode Version : 10  
 Repro rate : new request

Need image desaturation with memory efficient way in library itself.

**Comment by dreampiggy** [comment]
It's a 5.x feature, [Image Transformer](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#image-transformer-50).

You can use any [Core Image Filter](https://developer.apple.com/documentation/coreimage) or even your own custom implementation for image processing since it's a protocol.

**Comment by sureshcapternal** [comment]
Hello,
Thank for quick reply, I had implemented it using CIImage and its working
as expected. What i thought is, Our library should support some image
processing like aplying some filters. But you are righ SDWebImagd is not an
image processing library. Thanks for correction, keep giving us such great
support. Thanks once again.
