### ISSUE TITLE
libsystem_platform.dylib | _platform_memmove + 96

### ISSUE THREAD

**Issue by fishycx** [SDWebImage/SDWebImage#2545]
Info | Value
-- | --
Platform Name | ios
Platform Version | 10.x~12.x
SDWebImage Version | 4.4.2
Integration Method | cocoapods
Xcode Version | Xcode 9.4.1
Repro rate

There's a lot of crash information about GIF graphs. Here's the information captured by buggly：

0 libsystem_platform.dylib | _platform_memmove + 96
-- | --
1 ImageIO | GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 3192
2 ImageIO | GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 3192
3 ImageIO | GIFReadPlugin::CopyImageBlockSetProc(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*)+ 124
4 ImageIO | IIOImageProviderInfo::copyImageBlockSetWithOptions(CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 496
5 ImageIO | IIOImageProviderInfo::CopyImageBlockSetWithOptions(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 356
6 QuartzCore | CA::Render::(anonymous namespace)::create_image_from_image_provider(CGImage*, CGImageProvider*, CGColorSpace*, unsigned int) + 524
7 QuartzCore | CA::Render::create_image(CGImage*, CGColorSpace*, unsigned int, double) + 772
8 QuartzCore | CA::Render::copy_image(CGImage*, CGColorSpace*, unsigned int, double, double) + 500
9 QuartzCore | CA::Render::prepare_image(CGImage*, CGColorSpace*, unsigned int, double) + 16
10 QuartzCore | CA::Layer::prepare_commit(CA::Transaction*) + 292
11 QuartzCore | CA::Context::commit_transaction(CA::Transaction*) + 264
12 QuartzCore | CA::Transaction::commit() + 512
13 QuartzCore | CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long)+ 616
14 IOKit | IODispatchCalloutFromCFMessage + 372
15 CoreFoundation | ___CFMachPortPerform + 180
16 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
17 CoreFoundation | ___CFRunLoopDoSource1 + 436
18 CoreFoundation | ___CFRunLoopRun + 1840
19 CoreFoundation | CFRunLoopRunSpecific + 444
20 GraphicsServices | GSEventRunModal + 180
21 UIKit | -[UIApplication _run] + 684
22 UIKit | UIApplicationMain + 208
23 MamHao | 0x00000001000ec000 + 8310660
24 libdyld.dylib | _start + 4

**Comment by mythodeia** [comment]
@fishycx can you please conform to the [ISSUE_TEMPLATE](https://github.com/SDWebImage/SDWebImage/blob/master/.github/ISSUE_TEMPLATE.md) on this project?

**Comment by zhongwuzw** [comment]
@fishycx And if this is a crash, please also upload the entire crash log.

**Comment by fishycx** [comment]
Info | Value
-- | --
Platform Name | ios
Platform Version | 10.x~12.x
SDWebImage Version | 4.4.2
Integration Method | cocoapods
Xcode Version | Xcode 9.4.1
Repro rate

more Details:

0 libsystem_platform.dylib | _platform_memmove + 96
-- | --
1 ImageIO | GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 3192
2 ImageIO | GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 3192
3 ImageIO | GIFReadPlugin::CopyImageBlockSetProc(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*)+ 124
4 ImageIO | IIOImageProviderInfo::copyImageBlockSetWithOptions(CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 496
5 ImageIO | IIOImageProviderInfo::CopyImageBlockSetWithOptions(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 356
6 QuartzCore | CA::Render::(anonymous namespace)::create_image_from_image_provider(CGImage*, CGImageProvider*, CGColorSpace*, unsigned int) + 524
7 QuartzCore | CA::Render::create_image(CGImage*, CGColorSpace*, unsigned int, double) + 772
8 QuartzCore | CA::Render::copy_image(CGImage*, CGColorSpace*, unsigned int, double, double) + 500
9 QuartzCore | CA::Render::prepare_image(CGImage*, CGColorSpace*, unsigned int, double) + 16
10 QuartzCore | CA::Layer::prepare_commit(CA::Transaction*) + 292
11 QuartzCore | CA::Context::commit_transaction(CA::Transaction*) + 264
12 QuartzCore | CA::Transaction::commit() + 512
13 QuartzCore | CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long)+ 616
14 IOKit | IODispatchCalloutFromCFMessage + 372
15 CoreFoundation | ___CFMachPortPerform + 180
16 CoreFoundation | _CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION + 56
17 CoreFoundation | ___CFRunLoopDoSource1 + 436
18 CoreFoundation | ___CFRunLoopRun + 1840
19 CoreFoundation | CFRunLoopRunSpecific + 444
20 GraphicsServices | GSEventRunModal + 180
21 UIKit | -[UIApplication _run] + 684
22 UIKit | UIApplicationMain + 208
23 MamHao | 0x00000001000ec000 + 8310660
24 libdyld.dylib | _start + 4

**Comment by fishycx** [comment]
There are many crash records about FLAnimatedImage



0 libsystem_platform.dylib | _platform_memmove + 80
-- | --
1 ImageIO | GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 3244
2 ImageIO | GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 3244
3 ImageIO | GIFReadPlugin::CopyImageBlockSetProc(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*)+ 124
4 ImageIO | IIOImageProviderInfo::copyImageBlockSetWithOptions(CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 496
5 ImageIO | IIOImageProviderInfo::CopyImageBlockSetWithOptions(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 356
6 CoreGraphics | _img_blocks_create + 260
7 CoreGraphics | _img_data_lock + 1896
8 CoreGraphics | CGSImageDataLock + 152
9 CoreGraphics | _ripc_AcquireImage + 712
10 CoreGraphics | _ripc_DrawImage + 676
11 CoreGraphics | CGContextDrawImageWithOptions + 636
12 FLAnimatedImage | +[FLAnimatedImage predrawnImageFromImage:] + 328
13 FLAnimatedImage | -[FLAnimatedImage imageAtIndex:] + 148
14 FLAnimatedImage | __42-[FLAnimatedImage addFrameIndexesToCache:]_block_invoke_3 + 132
15 Foundation | ___NSIndexSetEnumerate + 824
16 FLAnimatedImage | __42-[FLAnimatedImage addFrameIndexesToCache:]_block_invoke_2 + 136
17 libdispatch.dylib | __dispatch_call_block_and_release + 24
18 libdispatch.dylib | __dispatch_client_callout + 16
19 libdispatch.dylib | __dispatch_queue_serial_drain + 928
20 libdispatch.dylib | __dispatch_queue_invoke + 652
21 libdispatch.dylib | __dispatch_queue_override_invoke + 360
22 libdispatch.dylib | __dispatch_root_queue_drain + 572
23 libdispatch.dylib | __dispatch_worker_thread3 + 124
24 libsystem_pthread.dylib | _pthread_wqthread + 128

**Comment by zhongwuzw** [comment]
@fishycx Please provide `Exception Type` like below:

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0
```

**Comment by zhongwuzw** [comment]
@fishycx I still request you to upload entire log just like [this](https://github.com/zhongwuzw/WebBrowser/blob/master/logs/crash/Done/DOMError.crash).

From the limited log, the crash is race condition, `CGContextDrawImage` is not thread safe for the same `image source`, `predrawnImageFromImage` is called on a `serial queue`, so you use a `tableView` or `collectionView`?I need some informations.

**Comment by fishycx** [comment]
yes, i use a tableView to show pictures， and I use third-party software (buggly) to record this crash log, and I can't provide complete crash information.

**Comment by zhongwuzw** [comment]
@fishycx :ok_hand: got it, but `Exception Type` `Exception Subtype`.. also cannot provided?  because this is the key to show wether is `EXC_BAD_ACCESS` or other reason.

```
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
```

**Comment by fishycx** [comment]
SEGV_ACCERR

**Comment by zhongwuzw** [comment]
Investigate!

**Comment by fishycx** [comment]
When I turned off the predrawing（self.sd_predrawingEnabled = NO）, the problem was no longer reported.

**Comment by zhongwuzw** [comment]
@fishycx Thanks for your information! 👍 We'll try to fix it.

**Comment by zhongwuzw** [comment]
Keep.
