### ISSUE TITLE
HEIC file format issue

### ISSUE THREAD

**Issue by visionsIT** [SDWebImage/SDWebImage#2546]
Thanks for creating this library I am using this lib. since five years its great.

Now I am getting issue for .heic image format file, SDWebImage not load images for .heic format . I am used SDWebImageHEICCoder , its load file successfully but build issue while archive due to bitcode enable yes. if  disable bitcode than its working fine.

Can you please check this.

**Comment by dreampiggy** [comment]
Thanks for your report and I know the reason.

But, please goto https://github.com/SDWebImage/SDWebImageHEIFCoder and fire the issue here. Since it's related to that decoder plugin, not the Core SDWebImage framework.

**Comment by dreampiggy** [comment]
I've moved your issue here: https://github.com/SDWebImage/SDWebImageHEIFCoder/issues/2

**Comment by dreampiggy** [comment]
Fixed by SDWebImageHEIFCoder new release.

**Comment by visionsIT** [comment]
Thanks
