### ISSUE TITLE
Memory Issues Problem

### ISSUE THREAD

**Issue by CapricornRJ** [SDWebImage/SDWebImage#2557]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        | 10.2
 SDWebImage Version      | 4.4.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.4.1
 Repro rate              | sometimes

### Issue Description and Steps

0 libsystem_platform.dylib | _platform_memmove + 96
-- | --
1 ImageIO | GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 3192
2 ImageIO | GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 3192
3 ImageIO | GIFReadPlugin::CopyImageBlockSetProc(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 124
4 ImageIO | IIOImageProviderInfo::copyImageBlockSetWithOptions(CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 496
5 ImageIO | IIOImageProviderInfo::CopyImageBlockSetWithOptions(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 356
6 CoreGraphics | _img_blocks_create + 260
7 CoreGraphics | _img_data_lock + 1868
8 CoreGraphics | CGSImageDataLock + 176
9 CoreGraphics | _ripc_AcquireImage + 712
10 CoreGraphics | _ripc_DrawImage + 676
11 CoreGraphics | CGContextDrawImageWithOptions + 636
12 FLAnimatedImage | +[FLAnimatedImage predrawnImageFromImage:] + 328
13 FLAnimatedImage | -[FLAnimatedImage imageAtIndex:] + 148
14 FLAnimatedImage | __42-[FLAnimatedImage addFrameIndexesToCache:]_block_invoke_3 + 132
15 Foundation | ___NSIndexSetEnumerate + 824
16 FLAnimatedImage | __42-[FLAnimatedImage addFrameIndexesToCache:]_block_invoke_2 + 136
17 libdispatch.dylib | __dispatch_call_block_and_release + 24
18 libdispatch.dylib | __dispatch_client_callout + 16
19 libdispatch.dylib | __dispatch_queue_serial_drain + 928
20 libdispatch.dylib | __dispatch_queue_invoke + 652
21 libdispatch.dylib | __dispatch_queue_override_invoke + 360
22 libdispatch.dylib | __dispatch_root_queue_drain + 572
23 libdispatch.dylib | __dispatch_worker_thread3 + 124
24 libsystem_pthread.dylib | _pthread_wqthread + 1288

**Comment by dreampiggy** [comment]
What about trying disable the predraw feature of `FLAnimatedImage` ? And you can also use their `optimalFrameCacheSize`.

```objective-c
FLAnimatedImageView *imageView;
imageView.sd_predrawingEnabled = NO;
imageView.sd_optimalFrameCacheSize = 1; // equals to `FLAnimatedImageFrameCacheSizeLowMemory`, means  "The minimum frame cache size; this will produce frames on-demand."
```

**Comment by CapricornRJ** [comment]
I found that the crash situation happened on iOS 10.x. Is this accidental?
