### ISSUE TITLE
kernel EXC_RESOURCE exceeded mem limit: ActiveHard 2048 MB (fatal)

### ISSUE THREAD

**Issue by cdunkel** [SDWebImage/SDWebImage#2560]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS (iPhone XS Max only)
 Platform Version        | 12.1
 SDWebImage Version      | 4.4.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.1
 Repro rate              | all the time (100%), only observed on the iPhone XS Max
 Repro with our demo prj | No demo project at this time, but can create one later if necessary.
 Demo project link       | No demo project at this time, but can create one later if necessary.

### Issue Description and Steps

A portion of our application downloads and displays a list of companies, including their logos. The company information and logo links can be provided by our customers. Our application also prefetches all of the image assets whenever data is downloaded from our server so the app will still be able to display images in the event the user loses their internet connection.

Our prefetch code looks like:
```
SDWebImagePrefetcher *prefetcher = [SDWebImagePrefetcher sharedImagePrefetcher];
prefetcher.options = prefetcher.options | SDWebImageRetryFailed;
[prefetcher prefetchURLs:[urlSet allObjects]];
```
Where `urlSet` is an array of image URLs as NSStrings.

Very occasionally we will have a customer try to use a logo or other image that is very large. For example, [this logo](https://downloads.intercomcdn.com/i/o/84945728/de61766feaad914e56d597a7/Chess+Dynamics+Logo+%28Pantone%29+Outlined+Large+%281%29.png) which is 37627 × 7644. **WARNING: Before clicking on the link, the image will slow down your browser significantly.**

Testing the application on an iPod Touch running iOS 10 and an iPhone X running iOS 12 we're experiencing no issues aside from a slight slowdown and the logo not appearing (the app logs that it can't allocate the required memory), which is fine. However, when running on the iPhone XS Max the app crashes immediately. This has also only been observed when running on the physical device - the simulator seems to work exactly as the iPod Touch and iPhone X do. The issue has been duplicated on two different iPhone XS Max devices.

**Comment by cdunkel** [comment]
@dreampiggy we are implementing controls on our server to prevent images like this from being uploaded.

My intent in posting this wasn't so much that I expect SDWebImage to be able to display such things - I don't - but that I found it odd that on the other platforms tested (iPod Touch and iPhone X) the system was able to handle the memory allocation rejection without the app being killed by the kernel, while on the iPhone XS Max it wasn't. I thought perhaps that there was some case that the XS Max is hitting that hadn't come up before with other devices that SDWebImage might be able to handle by failing gracefully.

So, just to be clear, I posted this here because I was getting different behavior on different devices and wanted to bring it to the attention of the developers. I'm not expecting SDWebImage to be able to display the image I referenced in my example.

**Comment by zhongwuzw** [comment]
@cdunkel I didn't have a `iPhone XS Max`, so I can't try to see the situations of memory allocation. Would you try to use `SDWebImageScaleDownLargeImages` option to load this? it also crashed?

**Comment by dreampiggy** [comment]
😕 iPhone XS Max actually the physical RAM is 4GB. So theoretically it can decode this large image without OOM (unless your phone is under heavy memory pressure)...Maybe I need an iPhone XS Max test device to check back.

**Comment by cdunkel** [comment]
@zhongwuzw, I did try the `SDWebImageScaleDownLargeImages` option when trying to address this issue, but I still got the crash 😞 . The only thing I didn't try was the option to *not* decompress images on download, but I figured in this case it would just move the problem to when the image is being displayed.

@dreampiggy, yeah, I found this to be a very frustrating crash to duplicate, since it was only by random luck that one of my co-workers has an XS Max that he tested on. The crash did not show up in the simulator, but I assume that's because the simulator has access to the resources of the machine on which its running. I wish Xcode had a way to simulate a specific memory load condition (e.g. 5% RAM available, etc).

**Comment by dreampiggy** [comment]
I brought a iPhone XS Max from our QA for testing. I can reproduce this issue. Which means:

For iPhone X/iPhone 8 (iOS 12.1), when viewing this image and cause allocation failed, Image IO && CoreGraphics framework log the issue, and return a nil CGImage, we finally mark this deciding failed.

```
SDWebImage iOS Demo(2662,0x16f6d3000) malloc: can't allocate region
*** mach_vm_map(size=1150517248) failed (error code=3)
SDWebImage iOS Demo(2662,0x16f6d3000) malloc: *** set a breakpoint in malloc_error_break to debug
2018-12-14 11:30:55.979711+0800 SDWebImage iOS Demo[2662:389406] [Unknown process name] CGSImageDataLock: Cannot allocate memory
```

However, when running on iPhone XS Max (12.1), these system framework does not log anything when allocate failed. Instead, then just trigger a OOM process without any other useful information.

```
Message from debugger: Terminated due to memory issue
```

And the device console contains useless log only.

```
default	11:26:21.813409 +0800	SDWebImage iOS Demo	Received memory warning.
default	11:26:22.027039 +0800	kernel	EXC_RESOURCE -> SDWebImage iOS Demo[2661] exceeded mem limit: ActiveHard 2048 MB (fatal)
default	11:26:22.028253 +0800	kernel	137820.072 memorystatus: killing_specific_process pid 2661 [SDWebImage iOS Demo] (per-process-limit 10) - memorystatus_available_pages: 37808
default	11:26:22.040183 +0800	assertiond	[SDWebImage iOS :2661] Setting jetsam priority to 3 [0x100]
error	11:26:22.040616 +0800	assertiond	[SDWebImage iOS :2661] SyscallError: setpriority(PRIO_DARWIN_ROLE, 2661, 3): No such process
error	11:26:22.041489 +0800	SpringBoard	HW kbd: Failed to set (null) as keyboard focus
default	11:26:22.042390 +0800	backboardd	Connection removed: IOHIDEventSystemConnection uuid:3C5C64B4-9BB0-4F84-883C-27750D7A16CC pid:2661 
```

Maybe this is because the new system management for those iPhone XS/XS Max/XR (arm64e) devices. I'll try to investigate these issue. 

And I can provide you a demo on how to use thumb decoding (which means, decoding only thumb pixels without allocation failed, but not firstly generate full pixels and then scale down, which does not help for this issue)

**Comment by dreampiggy** [comment]
@cdunkel You can using Image IO (for PNG/JPEG, etc, Apple's supported format) for thumb decoding, I test it locally on the iPhone XS Max, it works. The sample code looks like this. You can create a subclass of `SDWebImageIOCoder` and override those one instead.

```objectivec
- (UIImage *)decodedImageWithData:(NSData *)data {
    if (!data) {
        return nil;
    }
    
    CGImageSourceRef source = CGImageSourceCreateWithData((__bridge CFDataRef)data, nil);
    if (!source) {
        return nil;
    }
    NSDictionary *properties = (__bridge_transfer NSDictionary *)CGImageSourceCopyPropertiesAtIndex(source, 0, nil);
    NSUInteger pixelWidth = [properties[(__bridge NSString *)kCGImagePropertyPixelWidth] unsignedIntegerValue];
    NSUInteger pixelHeight = [properties[(__bridge NSString *)kCGImagePropertyPixelHeight] unsignedIntegerValue];
    NSUInteger exifOrientation = [properties[(__bridge NSString *)kCGImagePropertyOrientation] unsignedIntegerValue];
    if (!exifOrientation) {
        exifOrientation = 1;
    }
    UIImageOrientation imageOrientation = [SDWebImageCoderHelper imageOrientationFromEXIFOrientation:exifOrientation];
    NSUInteger maxPixelSize = 4000; // This should be a option value from the caller method
    
    CGImageRef imageRef;
    if (pixelWidth > maxPixelSize || pixelHeight > maxPixelSize) {
        // Using thumb decoding
        NSDictionary *options = @{(__bridge NSString *)kCGImageSourceCreateThumbnailFromImageIfAbsent : @(YES), (__bridge NSString *)kCGImageSourceThumbnailMaxPixelSize : @(maxPixelSize)};
        imageRef = CGImageSourceCreateThumbnailAtIndex(source, 0, (__bridge CFDictionaryRef)options);
    } else {
        imageRef = CGImageSourceCreateImageAtIndex(source, 0, nil);
    }
    
    UIImage *image = [[UIImage alloc] initWithCGImage:imageRef scale:1 orientation:imageOrientation];
    CGImageRelease(imageRef);
    CFRelease(source);
    image.sd_imageFormat = [NSData sd_imageFormatForImageData:data];
    
    return image;
}
```

However, I need to consider it whether it's suitable to put this case on 4.x. Because now our decoder does not support a extra options to pass from the top-level API to the bottom. Maybe if we have to do, we can put it on a property of `SDWebImageIOCoder` shared instance.

On 5.x, I'll make this a optional value through decoding option, to allow customization of max limit pixel count during decoding. This can solve some issue.

**Comment by zhongwuzw** [comment]
@dreampiggy Just curious, what if disable decompress and let `UIKit` to decompress? on iPhoneXS Max still consume greater than 2G and crash?

**Comment by dreampiggy** [comment]
@zhongwuzw Once you call `malloc` to allocate 2GB memory on iPhone XS Max (not apply for iPhone X), the OOM detector start to jetsam and kill.

Whether you move the bitmap buffer to CA render server (when draw a bitmap context, leave `decompressImage` on) or keep the bitmap buffer on App process does not help. They just check whether total memory is used. So to fix this case, you have to avoid allocatation large buffer than the limit. Allocate a large buffer to decode then scale down does not help anything.

**Comment by zhongwuzw** [comment]
@dreampiggy Emm, I mean wether this image's decompress consumes memory greater than 2G , because 37627 × 7644 x 4 = 1.1G, I tested it on simulator and iPhone6+, they all indicate the memory consume is about 1.1G.

**Comment by dreampiggy** [comment]
@zhongwuzw I know the size of bitmap buffer. The system consume memory as well. Such as the Wired Memory is not purgeable. So the sum over 2GB and trigger a jetsam.

I list my test result when running on iPhone XS Max. You can also have a try for this case.

**Comment by cdunkel** [comment]
@dreampiggy and @zhongwuzw, thank you both for your help with this issue. For now we are going to implement some safeguards and checks to make sure that our customers don't upload images that are too large. However, if you do implement a fix I'll be happy to test on my end as well.

**Comment by dreampiggy** [comment]
I have a idea, that to introduce solution based on the above discussion. We can let the decoder, to just allocate and produce a thumb image during decoding. (Before the image transformer).

For Apple's built-in image format, like PNG/JPEG/GIF/TIFF, we can use [CGImageSourceCreateThumbnailAtIndex](https://developer.apple.com/documentation/imageio/1465099-cgimagesourcecreatethumbnailatin?language=objc)

For coder plugins, we can use each of their codec's method, like WebP format with libwebp: [WebPDecoderOptions.use_scaling](https://github.com/webmproject/libwebp/blob/master/src/webp/decode.h#L455)

See PR:

**Comment by dreampiggy** [comment]
Should be solved by using the thumbnail decoding. See #2922
