### ISSUE TITLE
FLAnimatedImageView+WebCache category is not running when there is multiple target.

### ISSUE THREAD

**Issue by SwordJason** [SDWebImage/SDWebImage#2564]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |   ios
 Platform Version        | 12.0
 SDWebImage Version      | 4.4.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10
 Repro rate              | all the time (100%) 
 Repro with our demo prj | does it happen with our demo project?
 Demo project link       | I have described the configuration under Issue Description

### Issue Description and Steps

I create this issue just want to post a solution for people who is run into the same issue & didn't found out why.

Configuration:
1. Project with multiple target(My.app, MyExt.extension)
2. PodFile only put "pod 'SDWebImage/GIF' " under target 'My'

The issue is that I couldn't access(visible/running) to the category of FLAnimatedImageView+WebCache at any point. Even the file is already inside the project & could be imported.
You will see a static image and the UIImageView+WebCache category method is called instead of FLAnimatedImageView+WebCache.

Solution:
1. PodFile need to put "pod 'SDWebImage/GIF' " under both target 'My' and 'MyExt' to fix this issue.
2. Pod install
3. Solved.

**Comment by dreampiggy** [comment]
This is a issue of usage of CocoaPods, actually, but not what a Pod framework can do.

For multiple target project, you must use the both GIF subspec for each target. If you use one target with subspec 1, another with subspec 2, CocoaPods allow this usage and will generate two different framework (static libaray) with two xcconfig. It’s a designed behavior of CocoaPods.

A better solution, if you write Podfile (instead of some Podfile automatic pre-generator), you can define a ruby function called shared pods.

```
def shared_pods
  pod 'SDWebImage/GIF'
end

target 'App'
  shared_pods
  pod 'KVOController'
end

target 'Extension'
  shared_pods
end
```

**Comment by dreampiggy** [comment]
Seems this is a usage issue. I think the answer above works for the this case. @SwordJason any extra issue ?
