### ISSUE TITLE
Crash by EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by musicode** [SDWebImage/SDWebImage#2567]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 11.0  12.0
 SDWebImage Version      | 4.4.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9
 Repro rate              | 50%
 Repro with our demo prj | 
 Demo project link       |  

### Issue Description and Steps

![image](https://user-images.githubusercontent.com/2732303/50463870-ffba0100-09c8-11e9-9221-49b0ba44d24c.png)

I dont know why crash at this line all the time. Maybe imageView is dead, but what can i do to avoid the crash.

**Comment by zhongwuzw** [comment]
@musicode Can you provide a demo project to reproduce? From your screenshot, system goes to forwarding process, this seems very strange.
