### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tebriz159** [SDWebImage/SDWebImage#2579]
Hi, I'm a logo designer and I can make a new free logo for your project. Do you want a new logo?

**Comment by bpoplauschi** [comment]
@tebriz159 thanks for you kind offer. Feel free to create a logo (note we have 2 versions of the logo):
- the small version used as organizatio logo: 
https://avatars1.githubusercontent.com/u/33113626?s=200&v=4
- the larger version used as project logo: https://github.com/SDWebImage/SDWebImage/raw/master/SDWebImage_logo.png

Lets us know if you have any ideas for a new logo, it might be better than the one we have.

**Comment by tebriz159** [comment]
@bpoplauschi I designed 2 logo and I used similar colors that you used on current design. If you like it I will send you all files to use it.

![sdwilt1](https://user-images.githubusercontent.com/31902754/52576007-23e46c80-2dd4-11e9-9fd3-3ab6e0d0e5c3.png)
![sdwilt2](https://user-images.githubusercontent.com/31902754/52576013-2646c680-2dd4-11e9-85df-28863f7e3fb6.png)

Which variation and colors do you want?

**Comment by zhongwuzw** [comment]
Interesting!

**Comment by bpoplauschi** [comment]
@tebriz159 I like the 1st one more. I think we should keep it smaller and avoid duplicating the "SD" part. Can we just use a more readable font for "SD" and keep it inside the semi-square (I assumed the first 2 letters are SD written in a custom font)? That way the "WebImage" text will follow and the whole logo is shorter.

**Comment by tebriz159** [comment]
@bpoplauschi I've made some variations as I understand. If you like one of these designs, which variation and colors do you want?

![sdwipr02](https://user-images.githubusercontent.com/31902754/53044887-187eea00-3441-11e9-8de7-47c2722746b5.png)

![sdwipr01](https://user-images.githubusercontent.com/31902754/53044929-2c2a5080-3441-11e9-9fe9-2a3ecc525dc7.png)

**Comment by bpoplauschi** [comment]
@tebriz159 sorry for the late response. Those look very nice IMO.
My personal preference is for the 4th in the 1st column.
![Screen Shot 2019-03-17 at 8 49 57 PM](https://user-images.githubusercontent.com/154913/54496288-477c6480-48f6-11e9-8082-223625de027e.png)


@SDWebImage/collaborators other opinions?

**Comment by dreampiggy** [comment]
I prefer the white background one (The black one seems a little deep in color from my mind).

I think the second and forth one are both good in the left side. 👍

**Comment by zhongwuzw** [comment]
I like firth and second in the 1st column.

**Comment by tebriz159** [comment]
All files here for 4th variation: https://drive.google.com/open?id=1f8DQujotWZloDnKfXg4Ah7g4AmFkeriZ

**Comment by bpoplauschi** [comment]
Great @tebriz159, really appreciate this contribution.
I think it would be ideal to release the new logo with the 5.0 release :)

**Comment by bpoplauschi** [comment]
I've updated the 2 logos on the 5.x branch: https://github.com/SDWebImage/SDWebImage/tree/5.x
When we release the 5.0 version, I will also update the Organization logo.

**Comment by bpoplauschi** [comment]
@tebriz159 can you please update the small logo icon to be in a square format? that is what GitHub needs and I can't install GIMP or similar on my current machine

**Comment by tebriz159** [comment]
@bpoplauschi Sure, I will update

**Comment by tebriz159** [comment]
Sorry for delay, all updated file are here https://drive.google.com/open?id=1350SoxHL4SCFgUYUO1A2kUCVOs0UoWvn

**Comment by bpoplauschi** [comment]
Again, many thanks @tebriz159 - I have updated the organization logo (with the one provided) and added it to the repo. We can close this issue now.

Very good job everyone, especially @tebriz159 :)
