### ISSUE TITLE
Possible improvements for  large image scaling

### ISSUE THREAD

**Issue by xiangwangfeng** [SDWebImage/SDWebImage#2583]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        | 11.0
 SDWebImage Version      | 4.2.0
 Integration Method      |  cocoapods 
 Xcode Version           |  Xcode 10

### Issue Description and Steps

SDWebImage offers a great feature of scaling large image automatically avoid memory issues. However, some possible improvements could be added for more easy use.
1.offer the custom configuration for kDestImageSizeMB and  kSourceImageTileSizeMB, users can config their own values depends on their user case.
2.width/height of image could be added to consideration when scale large image (also offer a custom configuration?). For example, a picture size of 100 * 20000 may only takes about 8MB memory (less than 60MB),but it results in a UIView/UIImageView render error (nothing show except a white background) because the value of height is too big.

**Comment by dreampiggy** [comment]
The second question is that bitmap context draw issue. The CGContext draw result a error. I'll try to investigate later.
