### ISSUE TITLE
How to cancel a webimage's load

### ISSUE THREAD

**Issue by jiutianhuanpei** [SDWebImage/SDWebImage#2594]
First I use `sd_setImageWithUrl:` method to set a webimage for imageview ,but the webimage is too big and return is slow, in that time I reset a local image for the imageview , and then I don't wanna the webimage, what should I do to unload the webimage ?

**Comment by kinarob** [comment]
See if this method can help you ？

**Comment by kinarob** [comment]
```Objc
- (void)sd_cancelCurrentImageLoad;
```

**Comment by jiutianhuanpei** [comment]
ok，thank you very much
