### ISSUE TITLE
CF_RETURNS_* issues when naming Core Foundation functions

### ISSUE THREAD

**Issue by zhongwuzw** [SDWebImage/SDWebImage#2598]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 SDWebImage Version      | 5.x`

### Issue Description and Steps

```
// Marks functions which return a CF type that needs to be released by the caller but whose names are not consistent with CoreFoundation naming rules. The recommended fix to this is to rename the functions, but this macro can be used to let the clang static analyzer know of any exceptions that cannot be fixed.
// This macro is ONLY to be used in exceptional circumstances, not to annotate functions which conform to the CoreFoundation naming rules.
#ifndef CF_RETURNS_RETAINED
#if __has_feature(attribute_cf_returns_retained)
#define CF_RETURNS_RETAINED __attribute__((cf_returns_retained))
#else
#define CF_RETURNS_RETAINED
#endif
#endif

// Marks functions which return a CF type that may need to be retained by the caller but whose names are not consistent with CoreFoundation naming rules. The recommended fix to this is to rename the functions, but this macro can be used to let the clang static analyzer know of any exceptions that cannot be fixed. 
// This macro is ONLY to be used in exceptional circumstances, not to annotate functions which conform to the CoreFoundation naming rules.
#ifndef CF_RETURNS_NOT_RETAINED
#if __has_feature(attribute_cf_returns_not_retained)
#define CF_RETURNS_NOT_RETAINED __attribute__((cf_returns_not_retained))
#else
#define CF_RETURNS_NOT_RETAINED
#endif
#endif
```

`CF_RETURNS_RETAINED` and `CF_RETURNS_NOT_RETAINED` can only used in **_exceptional circumstances_**, which is to say, if function name conforms the naming rules, we should not annotate it. But currently, we don't conform this rule, like :

`+ (CGColorSpaceRef _Nonnull)colorSpaceGetDeviceRGB CF_RETURNS_NOT_RETAINED;`
`+ (CGImageRef _Nullable)CGImageCreateDecoded:(_Nonnull CGImageRef)cgImage CF_RETURNS_RETAINED;`
and so on.....

From the git log, seems it try to optimize `Swift` Unmanaged type.

Two options we can solve issues:
1. Remove all `CF_RETURNS_*` annotate if it already satisfy naming rules. Let `Unmanaged` type exist.
2. Remove all `CF_RETURNS_*` annotate if it already satisfy naming rules. Refactor `SDImageCoderHelper`, make all class methods to be `C` functions, use `CF_IMPLICIT_BRIDGING_ENABLED` to fix swift `Unmanaged` type issues.

**Comment by dreampiggy** [comment]
Objective-C method return any CF data type, does not follow CF rules. You must annotation it with either `CF_RETURNS_RETAINED` (caller call `CFRelease`) or `CF_RETURNS_NOT_RETAINED` (caller don't need call `CFRelease`).

**Comment by dreampiggy** [comment]
See all the Objective-C API with CF data type inside all the Apple's framework, like `UIImage.CGImage`.

![image](https://user-images.githubusercontent.com/6919743/51510972-5b49a400-1e3a-11e9-88ea-f3664521684b.png)

**Comment by zhongwuzw** [comment]
@dreampiggy Oh, it's true, I always think compiler can do memory management the same as `C` function based on method return type, unfortunately clang don't do it, the reason is compiler may  cannot figure out returned `C` type.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/5061845/51512822-e169e880-1e42-11e9-89ed-90df42a15855.png">


<img width="979" alt="image" src="https://user-images.githubusercontent.com/5061845/51512753-94861200-1e42-11e9-87b1-f048241555e4.png">
