### ISSUE TITLE
Cached png images not transparent

### ISSUE THREAD

**Issue by project707** [SDWebImage/SDWebImage#26]
I'm not sure if this is only an issue with my particular app, but it really seems like if I clear the cached images the following happens:
1. they never load on the build that clears the cache
2. on the next build they load with alpha transparency
3. once they are cached, they load with white background where they were once transparent

For some background I am using the setImageWithURL method with a UITableView as follows:

[cell.imageView setImageWithURL:[NSURL URLWithString:theImagePath]
                       placeholderImage:[UIImage imageNamed:@"placeholder.png"]]; 

Has anybody else experienced this?

**Comment by rokridi** [comment]
I have the same issue. When image is loaded from disk, it comes with a white background. Have this issue been solved ?

**Comment by bpoplauschi** [comment]
This should work fine. Can you provide a demo project with this issue isolated?

**Comment by rokridi** [comment]
Sorry for the late reply. I will provide a separate demo project as soon as possible.

**Comment by rokridi** [comment]
Here is the link to a simple demo project : https://www.dropbox.com/s/q975vpdokstct1o/SDTransparencyIssue.zip?dl=0 . I have an issue with a .jpg image. The issue is that the image has a white background when loaded from the disk cache.

**Comment by rokridi** [comment]
The issue is related to .jpg images.

**Comment by mythodeia** [comment]
@rokridi try [this](https://dl.dropboxusercontent.com/u/34562882/SDTransparencyIssue.zip)
it is working now

**Comment by rokridi** [comment]
@mythodeia Thank you very much
