### ISSUE TITLE
sd_imageData(as: _, compressionQuality: _) does not work

### ISSUE THREAD

**Issue by bizibizi** [SDWebImage/SDWebImage#2600]
the size of Data which returns this method is always the same.

I was trying with every format. Bug is with every one

    pod 'SDWebImage', :git => 'https://github.com/SDWebImage/SDWebImage.git', :branch => '5.x'

**Comment by bizibizi** [comment]
@dreampiggy , hm, strange, i am checking the size of data, received after "sd_imageData(as: _, compressionQuality: _)" and it's always the same...


let byteCount = data.count
        let bcf = ByteCountFormatter()
        bcf.allowedUnits = [.useMB] // optional: restricts the units to MB only
        bcf.countStyle = .file
        var str = bcf.string(fromByteCount: Int64(byteCount))
        if str == "0 MB" {
            str = "0,1 MB"
        }
        return str

I will check it with real files

**Comment by dreampiggy** [comment]
OK....I understand the issue. It's should describe like that `sd_imageData(as: _, compressionQuality: _) does not work for compressionQuality arg. The output is always the same`

And after I check the code, it's a obvious bug that trigger this. And not only the `compressionQuality`, the `firstFrameOnly` arg is get effected as well. I'll create a MR to fix that as soon as possible.
