### ISSUE TITLE
the version 4.4.4 can't build success

### ISSUE THREAD

**Issue by applejian** [SDWebImage/SDWebImage#2601]
4.4.4 version has DEFINES_MODULE  in podspec file cause xcode error : unable to execute command: Segmentation fault: 11

**Comment by applejian** [comment]
fix step
post_install do |installer|
       installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            config.build_settings['DEFINES_MODULE'] = 'NO' #SDWebImage 4.4.4
        end
    end
end

**Comment by dreampiggy** [comment]
Please provide the information by using our issue template, instead of remove them.


And, what Xcode && CocoaPods version did you use ? It's a Xcode standard build settings.

**Comment by winfredzen** [comment]
I have the same issue.
When I change sdwebimage version to 4.4.2 , everything is ok

**Comment by dreampiggy** [comment]
@winfredzen Could you provide the information about the environment ? Like Xcode version && CocoaPods version, iOS firmware version, a demo project is better. Because our demo project can works and my third-party project can also build success.

**Comment by dreampiggy** [comment]
@zhongwuzw Maybe that `DEFINES_MODULE` contains some related issue, could you please have a check ?

And, I think, even if we don't specify `DEFINES_MODULE` in the podspec, Swift user who want to use Objective-C framework, can just using the `:modular_headers => true` in their Podfile. It's more configuratale.

```ruby
pod 'SDWebImage', '~> 4.4.4', :modular_headers => true
```

**Comment by applejian** [comment]
Xcode 10.1
cocoapods 1.5.3
not use 'use_frameworks!'

**Comment by dreampiggy** [comment]
> xcode error : unable to execute command: Segmentation fault: 11

Could you please have a screenshot or the full build log (including all messages of that line in Xcode build ouput) ?

**Comment by applejian** [comment]
![wechatimg1](https://user-images.githubusercontent.com/3965066/51828548-c3aaf080-2326-11e9-8f97-f44660e58c8b.jpeg)
[clang_2019-01-28-174938-3_skyme.crash.zip](https://github.com/SDWebImage/SDWebImage/files/2802391/clang_2019-01-28-174938-3_skyme.crash.zip)

**Comment by zhongwuzw** [comment]
I'll investigate this issue, @applejian any issue when execute `pod update`? Can you provide the `Podfile` example?

The first glimpse from the screenshot I can't find any relationship the cause is from `DEFINES_MODULE`.

**Comment by kinarob** [comment]
@zhongwuzw `pod 'SDWebImage', '~> 5.0.0-beta4'`, This is pod code I execute, I meet the same issues.

**Comment by applejian** [comment]
Maybe itundefineds another problem.
 4.4.4 version not build success
@zhongwuzw

**Comment by kinarob** [comment]
@applejian Is it in your pch file had import `SDWebImage`?

**Comment by applejian** [comment]
No

**Comment by dreampiggy** [comment]
@applejian Check again. You can use the preprocess function from the Xcode. Create a new temp Objective-C files (For example, `ViewController.h && ViewController.m`), then do the following step to check:

![image](https://user-images.githubusercontent.com/6919743/51882436-d6223a00-23b9-11e9-8f5a-aff96d9d0bb3.png)

![image 2](https://user-images.githubusercontent.com/6919743/51882441-d91d2a80-23b9-11e9-9339-576bac21941b.png)

Search the preprocessed files with `SDWebImage`, if you found one, you must have a implict import of SDWebImage in your prefix header.

**Comment by zhongwuzw** [comment]
Quote from [ZipArchive](https://github.com/ZipArchive/ZipArchive/issues/473)

> OK, confirmed to be related to this issue: CocoaPods/CocoaPods#7584
Some advices:
Solution A: pod 'SDWebImage', :modular_headers => false
Solution B: you disable "Precompile Bridging Header" AND you use Xcode 10+ to keep autocompletion working
Solution C: you don't import SDWebImage in Precompiled Headers (*.pch), you do it header by header
Solution D, from [nsparks](https://github.com/CocoaPods/CocoaPods/issues/7584#issuecomment-392203614) post, we add a swift file to the sources, as that may workaround the CocoaPods bug
Solution E, we wait for a CocoaPods fix on this, but it can take years
Solution F: you don't use modules (so, use_frameworks in Podfile)
Solution G, we remove DEFINES_MODULE from podspec, but then many users wishing the benefits of static libs/modules will have to customize their Podfile manually.
I don't guaranty at all that everything works: these are just ideas of resolution.

**Comment by applejian** [comment]
@dreampiggy 
@zhongwuzw

Solution by rollback to 4.4.3 
but in new tmp project the issue not appear

**Comment by dreampiggy** [comment]
@applejian The 4.4.5 version is released. Which revert that `DEFINES_MODULE`. You can have a try again by upgrading your Podfile.
