### ISSUE TITLE
SDWebImageContext dose not work in SDWebImageDownloader！

### ISSUE THREAD

**Issue by pei625569** [SDWebImage/SDWebImage#2603]
I want to know why do not callback in block of  'SDWebImageCacheSerializer' !

`

    SDWebImageCacheSerializer* seri = [[SDWebImageCacheSerializer alloc]initWithBlock:^NSData * _Nullable(UIImage * _Nonnull image, NSData * _Nullable data, NSURL * _Nullable imag{    
        return [self imageDataWith:image originalData:data imageURL:imageURL];
    }];
    SDWebImageContext* context = @{SDWebImageContextCacheSerializer:seri};
    [_downloader downloadImageWithURL:url options:SDWebImageDownloaderContinueInBackground context:context progress:nil completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, BOOL finished) {
        NSLog(@"inside finished image size = %@, dataSize = %.5lf kB",[NSValue valueWithCGSize:image.size], image.sd_imageData.length / 1024.0);
    }];
`

**Comment by dreampiggy** [comment]
@pei625569 Hi. Could you please provide the information in the issue template ? Such at least we need to know what version of SDWebImage, the platform version, Xcode version, to help us investiagte the issue.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / macos / tvos / watchos
 Platform Version        | e.g. 11.0 / 10.13.0 / 11.0 / 4.0
 SDWebImage Version      | e.g. 4.2.0 / 4.1.0
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 9 / Xcode 8
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

**Comment by dreampiggy** [comment]
@pei625569 Wait. You are using the `SDWebImageCacheSerializer` in `SDWebImageDownloader` ? It's wrong usage. The downloader does not do anything related to cacehe. And the documentation also point this property or context option is applied for `SDWebImageManager`. You can use like this.

```objective-c
SDWebImageContext* context = @{SDWebImageContextCacheSerializer:seri};
[SDWebImageManager.sharedManager loadImageWithURL:imageURL options:SDWebImageContinueInBackground context:context progress:nil completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, SDImageCacheType cacheType, BOOL finished, NSURL * _Nullable imageURL) {
    NSLog(@"inside finished image size = %@, dataSize = %.5lf kB",[NSValue valueWithCGSize:image.size], image.sd_imageData.length / 1024.0);
}];
```

Please check your usage again. And see the documentation comment there.

**Comment by dreampiggy** [comment]
Here is the documentation about [cacheSerializer](https://github.com/SDWebImage/SDWebImage/blob/5.x/SDWebImage/SDWebImageManager.h#L131-L149)
