### ISSUE TITLE
can't load webp

### ISSUE THREAD

**Issue by luangaolei** [SDWebImage/SDWebImage#2605]
### New Issue Checklist

* [√ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [√ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [√ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name            ios 
 Platform Version        10.3.2 
 SDWebImage Version      4.4.3
 Integration Method      cocoapods
 Xcode Version           Xcode 10.1

### Issue Description and Steps

 hi, After pod 'SDWebImage/WebP', WebP is still not loaded in the project. Is there any additional configuration required?

Error Domain=MWSDWebImageErrorDomain Code=0 "Downloaded image has 0 pixels" UserInfo={NSLocalizedDescription=Downloaded image has 0 pixels}

SDWebImage (4.4.3)
Libwebp (0.6.1)

**Comment by dreampiggy** [comment]
@luangaolei Could you also print a debug breakpoint at `-[SDWebImageCodersManager decodedImageWithData:]`. And print out the `self.coders` property (using `po self.coders` via lldb) ? It's an array contains all your coder plugin. It must have that `SDWebImageWebPCoder` inside. If not, maybe the bug is appear.

**Comment by dreampiggy** [comment]
I can not reproduce this issue locally. Are you sure you're using SDWebImage via the 3 standard way ?

Or, did you use something like preprocess macro override. The `SD_WEBP` macro is used to add the `SDWebImageWebPCoder` into the coder plugin manager during init method. If you face some issue, you can manually add that coder instead.

```objective-c
[SDWebImageCodersManager.sharedInstance addCoder:SDWebImageWebPCoder.sharedCoder]
```

**Comment by luangaolei** [comment]
嗯使用的是CocoaPods
好的,我先使用你提供的方法手动添加coder尝试一下

**Comment by luangaolei** [comment]
yeah,I found setting **SD_WEBP=1** in **build setting->preprocessor Macros**


> -[UIView(MWWebCache) 
sd_internalSetImageWithURL:placeholderImage:options:operationKey:setImageBlock:progress:completed:]
What does this method do? Is it in SDWebImage?There is also the MWSDWebImageErrorDomain returned by error.

**Comment by dreampiggy** [comment]
It this issue been solved ? I think it's that you're using something not our framework (Like a wrapper or a modified version). So maybe we can not help for that.

**Comment by luangaolei** [comment]
@dreampiggy hi, I found that the problem was caused by the UIView(MWWebCache) method imported from other libraries in the project. The problem was solved after deleting that library. Thank you for your help.

**Comment by dreampiggy** [comment]
OK...

Actually, if someone who want to `embbed` SDWebImage 4.x with WebP subspecs, they must inherit the preprocess macro `SD_WEBP`. In 5.0, this does not needed because the WebP is another standalone repo without any preprocess macro hack.
