### ISSUE TITLE
Can't load image

### ISSUE THREAD

**Issue by keynsianets** [SDWebImage/SDWebImage#2613]
### New Issue Checklist

* [+ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ +] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [+ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 11.0
 SDWebImage Version      | 4.4.4
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 10
 Repro rate              | all the time (100%)

### Issue Description and Steps
Can't load image with url: https://d2bnh4l4ivgux0.cloudfront.net/outfits/bfe8cf33-8b2f-4678-9a7a-81b6ecf477bd.png 
In MappleBeacon and browser this image loads successfully.

**Comment by mythodeia** [comment]
@keynsianets can you try the url you provided in the demo project? does it load there?

**Comment by dreampiggy** [comment]
Can not reproduce...Are you sure it's not the server issue or net work issue ? The image downloaded, is a normal PNG image, and the connection use HTTP/2.


![image](https://user-images.githubusercontent.com/6919743/52116296-c588f280-264b-11e9-93c1-c272a983f044.png)

**Comment by keynsianets** [comment]
How can i set HTTP/2 connection? It's not internet or server issue - this image loads successfully in browsers or with using other libraries. I will make test project in several minutes. 

> Can not reproduce...Are you sure it's not the server issue or network issue ? The image downloaded, is a normal PNG image, and the connection use HTTP/2.
> 
> ![image](https://user-images.githubusercontent.com/6919743/52116296-c588f280-264b-11e9-93c1-c272a983f044.png)

Can you show code, that you use for download this image? Maybe i am doing something wrong?

**Comment by keynsianets** [comment]
https://www.dropbox.com/s/dknfhxvuyksye4j/SDWebImageTest.zip?dl=0  - test project. 
I get an error: 
"2019-02-01 12:16:23.788275+0200 SDWebImageTest[9807:99077] Task <3683275B-1CD7-4520-B70A-ED08D16A8D36>.<1> load failed with error Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x6000024d7630 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3683275B-1CD7-4520-B70A-ED08D16A8D36>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <3683275B-1CD7-4520-B70A-ED08D16A8D36>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://d2bnh4l4ivgux0.cloudfront.net/outfits/bfe8cf33-8b2f-4678-9a7a-81b6ecf477bd.png, NSErrorFailingURLKey=https://d2bnh4l4ivgux0.cloudfront.net/outfits/bfe8cf33-8b2f-4678-9a7a-81b6ecf477bd.png, _kCFStreamErrorDomainKey=4} [-1001]
Optional(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x6000024d7630 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3683275B-1CD7-4520-B70A-ED08D16A8D36>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <3683275B-1CD7-4520-B70A-ED08D16A8D36>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://d2bnh4l4ivgux0.cloudfront.net/outfits/bfe8cf33-8b2f-4678-9a7a-81b6ecf477bd.png, NSErrorFailingURLKey=https://d2bnh4l4ivgux0.cloudfront.net/outfits/bfe8cf33-8b2f-4678-9a7a-81b6ecf477bd.png, _kCFStreamErrorDomainKey=4}) "my error""

**Comment by dreampiggy** [comment]
Just use `sd_setImageWithURL:`


> The requwst timed out.

Already show that it’s a network connect issue. Not about image decoding, not about loading logic inside SDWebImage.

**Comment by dreampiggy** [comment]
Maybe your image server provide, check something about HTTP header. Copy all your HTTP header from the browser (such like Chrome. Grab that in Network debugger tab). Then have a try again.

**Comment by mythodeia** [comment]
@dreampiggy @keynsianets using the demo he provided i cannot load the image too. 
the code is:
```
        let url = URL(string: "https://d2bnh4l4ivgux0.cloudfront.net/outfits/bfe8cf33-8b2f-4678-9a7a-81b6ecf477bd.png")
        imageView.sd_setImage(with: url) { (image, error, cacheType, url) in
            if error != nil {
                debugPrint(error, "my error")
            }
        }
```

**Comment by keynsianets** [comment]
I don't think it's problem with headers - this image only one from several thousand on this server, that doesn't load. I try to load this image directly with swift (test project - https://www.dropbox.com/s/1ecu4ytq83t9ukx/SDWebImageTest%202.zip?dl=0) and it works. Image load very long, but has loaded successfully.

**Comment by kostyleteam** [comment]
Have same issue with your code.

**Comment by zhongwuzw** [comment]
@keynsianets I used you project 
https://www.dropbox.com/s/dknfhxvuyksye4j/SDWebImageTest.zip?dl=0, but it works, can you check again?

**Comment by Insofan** [comment]
@kostyleteam @keynsianets I used the test project encountered this error.
```
2019-03-16 00:55:29.860806+0800 SDWebImageTest[5516:324854] Task <1AD0CB64-E7E8-4156-B7D2-BA148E9CECFC>.<1> finished with error - code: -1001
....some logs
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://d2bnh4l4ivgux0.cloudfront.net/outfits/bfe8cf33-8b2f-4678-9a7a-81b6ecf477bd.png, NSErrorFailingURLKey=https://d2bnh4l4ivgux0.cloudfront.net/outfits/bfe8cf33-8b2f-4678-9a7a-81b6ecf477bd.png, _kCFStreamErrorDomainKey=4}) "my error"
```
I think this caused by sd's default downloadTimeout is 15 seconds. The url takes a long time even on my chrome. Just set the downloadTimeout longer like sub code
```
        let  manager =  SDWebImageManager.shared()
        manager.imageDownloader?.downloadTimeout = 60.0
        let url = URL(string: "https://d2bnh4l4ivgux0.cloudfront.net/outfits/bfe8cf33-8b2f-4678-9a7a-81b6ecf477bd.png")
        imageView.sd_setImage(with: url) { (image, error, cacheType, url) in
            if error != nil {
                debugPrint(error, "my error")
            }
        }
```

**Comment by pramodApptech** [comment]
let imageURL = URL(string: "https://www.dropbox.com/s/fmdyhk5kc6f2hta/Prem_Chopda_8827904764_1672651676_pexels-raydar-341970.jpg?dl=1")!
         cell.imageView.sd_imageIndicator = SDWebImageActivityIndicator.gray
         cell.imageView.sd_setImage(with: imageURL, placeholderImage: UIImage(named: "water_mark"))
         not show image in imageView, Please check and share your feedback
