### ISSUE TITLE
How to cancel a webimage's load in swift 4

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [SDWebImage/SDWebImage#2614]
I have a tabbar and each tabbar item (UIViewController) a tableview consist from image in each row, and when I navigate to another tabbarItem, before images compeletly loaded, app crashes.

**Comment by mythodeia** [comment]
can you please conform to the [ISSUE_TEMPLATE](https://github.com/SDWebImage/SDWebImage/blob/master/.github/ISSUE_TEMPLATE.md) on this project?
which version are you using?

**Comment by dreampiggy** [comment]
I don’t know something that about that `App Crashes`. But if you want to cancel current imageView load, you can simply call

```swift
imageView.sd_cancelCurrentLoad()
```

**Comment by abdallahnh** [comment]
Hi,
when i used  `imageView.sd_cancelCurrentImageLoad()` the completion block still calling any help?

**Comment by dreampiggy** [comment]
It's a designed behavior. If you cancel the image load, you will receive a completion callback with error, which error code is `NSURLErrorCancelled`
