### ISSUE TITLE
Canceled download handler

### ISSUE THREAD

**Issue by aledefra** [SDWebImage/SDWebImage#2615]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12
 Language        | Swift
 SDWebImage Version      | 5.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.1
 Repro rate              | all the time (100%)

### Issue Description and Steps

I have an app that shows the pages from a online news service.
I have two buttons, page up and page down, that trigger two function that change the page number and download the image of the page with `imageView.sd_setImage(with: url, completed: { (image, error, cacheType, imageURL) in ... })`, and in the completion block I have `self.queue.leave()` (queue is `DispatchGroup()`).
It all works fine, but if the user touches the "page up" button again before the completion of the download, the completion block never gets triggered, the DispatchGroup never gets over and so the application stops working.
Does something like "operation cancel handler" exist?
Thanks for help

**Comment by dreampiggy** [comment]
You can try to use KVO on the operation’s 'isCancelled' property. But to say, it’s not a good idea.

Any reason cause you to write code like this ? If you just need to synchronizly download (as well as cache) the image from net, use `SDWebImageManager loadImageWithURL:`. It’s more suitable for this use case compared to the View Catatory methods.

**Comment by Softy101** [comment]
Well done!
