### ISSUE TITLE
Download image using SDWebImage, error -999

### ISSUE THREAD

**Issue by kbabulrao** [SDWebImage/SDWebImage#2616]
I am unable to download the image in Objective c Using SDWebImage 4.4.5 version.,  I tried the following , nothing worked.

Try 1:

    [self.thumbnailImageView sd_setImageWithURL:[NSURL URLWithString:thumbnailURLString] completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
}];

Try 2:

    [self.thumbnailImageView sd_setImageWithURL:[NSURL URLWithString:thumbnailURLString] placeholderImage:nil options:SDWebImageRefreshCached completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) { if(image != nil){
                self.thumbnailImageView.image = image;                
            } else {
                NSLog(@"Photo Not Available, fetch");
                [self.thumbnailImageView sd_setImageWithURL:[NSURL URLWithString:thumbnailURLString] placeholderImage:nil options:SDWebImageRefreshCached completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                    if(image != nil) { NSLog(@"Lo Res Image Loaded by %ld from '%@'", (long)cacheType, imageURL);
                        self.thumbnailImageView.image = image;
                        
                    } else {
                        self.thumbnailImageView.image = nil;
                        
                    } }];
                
            } }];

Try 3:

    [[SDWebImageDownloader sharedDownloader] downloadImageWithURL:[NSURL URLWithString:thumbnailURLString] options:SDWebImageDownloaderUseNSURLCache progress:nil completed:^(UIImage *image, NSData *data, NSError *error, BOOL finished) {
                
                
            }];

Try 4:

    SDWebImageManager *manager = [SDWebImageManager sharedManager];
            
            [manager loadImageWithURL:[NSURL URLWithString:thumbnailURLString] options:SDWebImageDelayPlaceholder progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL) {
            } completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, SDImageCacheType cacheType, BOOL finished, NSURL * _Nullable imageURL) {
                
            }];

Try 5:

    SDWebImageDownloader *manager = [SDWebImageManager sharedManager].imageDownloader;
            [manager setValue:@"application/vnd.learning.events.v1+json" forHTTPHeaderField:@"Accept"];
            [manager setValue:@"en-US" forHTTPHeaderField:@"Accept-Language"];
            [manager setValue:@"application/json; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
            //[manager setValue:savedEmail forHTTPHeaderField:@"Email"];
            [manager setValue:savedToken forHTTPHeaderField:@"Authorization"];
            [manager downloadImageWithURL:[NSURL URLWithString:thumbnailURLString] options:SDWebImageDownloaderHighPriority progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL) {
            } completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, BOOL finished) {
                self.thumbnailImageView.image = image;
            }];

In all the above cases, getting the following error:

    

> Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://prodServer.azurewebsites.net/api/BAImage?ActionFlagId=97&id=615, NSErrorFailingURLKey=https://prodServer.azurewebsites.net/api/BAImage?ActionFlagId=97&id=615, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <92586538-B07D-46FB-8694-3B29AA3F0CB4>.<7>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <92586538-B07D-46FB-8694-3B29AA3F0CB4>.<7>, NSLocalizedDescription=cancelled}

 Earlier, we used v3.5.4 version used, able to download the image with the following code. It's working good.

    [self.thumbnailImageView setImageWithURL:[NSURL URLWithString:thumbnailURLString]
                                placeholderImage:nil
                                       completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType) {
                                           if (image != nil){
                                               self.thumbnailImageView.image = [self imageResizingToAspetRatio:image];

                                           }
                                       }];

Kindly let me know if did any mistake, or any suggestions.

**Comment by dreampiggy** [comment]
Could you please. use Charles to capature the different HTTP Header for request compared with these two different version of SD. I think that your image server provider, filter something because of HTTP Header(such as User-Agent or something, we add a default UA recentlly)

**Comment by dreampiggy** [comment]
You can run Charles, send network request, then see all the information for the HTTP request and response. It’s better to export (right click on that request) that Charles report (a .chls file) and upload for me to investigate.

**Comment by dreampiggy** [comment]
Version below 3.8 using NSURLConnection, which it’s a legacy network framework for iOS URL Loading system. The we use URLSession. However, there are also some little different between these. For example, URLSession does not use URLProtocol by default (you need to config one) compared to URLConnection. So if yout app have custom URLProtocol, you shoukd have a check.

**Comment by kbabulrao** [comment]
When I tried to see the response on "Charles Proxy" I am able to see some response if I give “https://www.charlesproxy.com/“.  Please find the attached image for the response…
![sample url](https://user-images.githubusercontent.com/5792888/52475989-45223e80-2bc3-11e9-9e23-de6ce161be99.png)


When I give the actual image url on "Charles Proxy", I didn't see any data when we click on ‘Execute’. We tried with giving authorization parameters and tried without adding any parameters.
![image url](https://user-images.githubusercontent.com/5792888/52476010-53705a80-2bc3-11e9-935f-e63361414e42.png)

**Comment by zhongwuzw** [comment]
@kbabulrao Hey, the domain you provided is reachable?

**Comment by SuperCup** [comment]
Hello, I have encountered the same problem, I would like to ask you how to solve this problem in the end.

**Comment by kbabulrao** [comment]
I am facing the issue. Didn't solved the issue still.

Tried to download the image using post man.

The same image URL is working on SDWebImage v3.5.4 after i upgraded to SDWebImage v4.4.5, it is  not lodging the image.

Is there any configurations am i missing? Installed pod 'SDWebImage/WebP' also, added SD_WEBP=1 in Build settings -> Preprocessor macros.

> Error:  Error Domain=SDWebImageErrorDomain Code=0 "Downloaded image has 0 pixels" UserInfo={NSLocalizedDescription=Downloaded image has 0 pixels}

![image_loading_issue](https://user-images.githubusercontent.com/5792888/53563348-c85b0280-3b79-11e9-8f53-3ab5fb70d705.png)


This is the actual url, i am trying to download 
Image URL:
http://devprimewebapp.azurewebsites.net/api/CTImage?ActionFlagId=20&id=864

Authorization:
Email: kkk1@ler.com ,
Token: 21F222BF-BE3D-436F-847F-1F7B4A8A106F

**Comment by kbabulrao** [comment]
> @kbabulrao Hey, the domain you provided is reachable?

Please check this
Image URL:
http://devprimewebapp.azurewebsites.net/api/CTImage?ActionFlagId=20&id=864

Authorization:
Email: [kkk1@ler.com](mailto:kkk1@ler.com) ,
Token: 21F222BF-BE3D-436F-847F-1F7B4A8A106F

**Comment by kbabulrao** [comment]
it's working, Added to convert the response image in "SDWebImageDownloaderOperation.m" Once i got the response, converted to image and assigned to the same.

Added the following code in "- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error"

NSDictionary *responseObject = [NSJSONSerialization JSONObjectWithData:self.imageData
                                                                       options:0
                                                                         error:nil];
        if (![[responseObject objectForKey:@"Value"] isEqual:[NSNull null]] &&
            [responseObject objectForKey:@"Value"]) {
            self.imageData  = [[NSData alloc] initWithBase64EncodedString:[responseObject objectForKey:@"Value"] options:0];
            
        }

**Comment by Objectivist-angular13677** [comment]
Here’s an answer to consider https://lnkr.fun/43583ff
