### ISSUE TITLE
'UIImage+MemoryCacheCost.h' file not found

### ISSUE THREAD

**Issue by ramprasadios** [SDWebImage/SDWebImage#2617]
I am using SDWebImage in the iOS app, I am using the cocoapod version with version ~4.0.

**Comment by dreampiggy** [comment]
I don’t know the reason why cause this file not found. It’s new file introduced in v4.4.3. And it’s always works in CocoaPod’s install. Maybe you can try to clear your pod cache ?

`pod cache clean SDWebImage`

**Comment by introin** [comment]
same error with me, did manaul linking in ios. 
@ramprasadios have you been able to find workaround?
