### ISSUE TITLE
5.0.0版本取缓存，必现崩溃

### ISSUE THREAD

**Issue by GengJian** [SDWebImage/SDWebImage#2632]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 9.0~12.1.4
 SDWebImage Version      | 5.0.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9 / Xcode 10
 Repro rate              | all the time (100%)

### Issue Description and Steps

SDWebImage SDDiskCacheFileNameForKey
![Uploading 1901551851903_.pic_hd.jpg…]()

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by kinarob** [comment]
@GengJian  Can you get rid of the crash step description more? Or the crash log, or your usage of SDWebImage, or the URL of the image. Thanks!

**Comment by dreampiggy** [comment]
It this reproducable ? Maybe we have to fix it before final release.

Your uploaded image seems down, could you please re-upload your screenshot ?

And, the image url is necessary for us to investigate the issue.

**Comment by GengJian** [comment]
![261551969357_ pic_hd](https://user-images.githubusercontent.com/13254245/53964037-75f58500-4129-11e9-967e-360e5744b708.jpg)

**Comment by GengJian** [comment]
> @GengJian You mean there's a problem with this method：
> 
> `NSString * _Nonnull SDDiskCacheFileNameForKey(NSString * _Nullable key)`
> 
> Could you provide the URL of your picture?

在5.0.0版本上必现，然后我们回滚到了4.4.5版本就没有crash了。

**Comment by GengJian** [comment]
> It this reproducable ? Maybe we have to fix it before final release.
> 
> Your uploaded image seems down, could you please re-upload your screenshot ?
> 
> And, the image url is necessary for us to investigate the issue.

在5.0.0版本上必现，然后我们回滚到了4.4.5版本就没有crash了。
图片地址当时没有存，我尝试去找一下

**Comment by dreampiggy** [comment]
@GengJian Any update ?

The code of calculating file name from cacheKey, it's **exact the same**.
4.4.6: https://github.com/SDWebImage/SDWebImage/blob/4.4.6/SDWebImage/SDImageCache.m#L245-L260
5.0.0-beta5: https://github.com/SDWebImage/SDWebImage/blob/5.0.0-beta5/SDWebImage/SDDiskCache.m#L273-L288

So maybe this issue is not caused by the calculating algorithm. I guess maybe that the cacheKey appear in 5.0 is different from 4.4.6. Could you please show me some of the image url (if you're using a custom `SDWebImageCacheKeyFilter`, please provide the code)

**Comment by GengJian** [comment]
@dreampiggy  我们暂时没有尝试更新pod库，而且没有自定义SDWebImageCacheKeyFilter，至于图片链接，再下次遇到时我会留意。

**Comment by Insofan** [comment]
@GengJian Hi, I'm refactoring some part of SD's cache codes. Could you provide a URL or a demo to reproduce this issue.

**Comment by dreampiggy** [comment]
Hi. SDWebImage 5.0.0 is official released. Could you have a try as well ? See: https://github.com/SDWebImage/SDWebImage/releases/tag/5.0.0
