### ISSUE TITLE
could not download the Vendor directory

### ISSUE THREAD

**Issue by Calvin-Shen** [SDWebImage/SDWebImage#2640]
When I downloaded the project from github, then I build it in my Xcode,raise the error "Build input file cannot be found ,/Users/xxxxx/xxxxx/SDWebImage/Vendors/libwebp/src/dsp/yuv_sse2.c". 
I found that the Verdor directory's two subDirectories are empty.

**Comment by kinarob** [comment]
Since submodule(`libwebp` and `FLAnimatedImage`) was used in project, 
You should use this way：

`git clone --recurse https://github.com/SDWebImage/SDWebImage.git`

**Comment by Calvin-Shen** [comment]
@kinarob thanks a lot! it works,但是为什么通过github上面那个clone and donwlond按钮，就在下载不了libwebp 和 FLAnimatedImage呢?非得必须用命令行
