### ISSUE TITLE
Replace weak-strong dance with @weakify @strongify

### ISSUE THREAD

**Issue by zhongwuzw** [SDWebImage/SDWebImage#2643]
Currently, we have many weak-strong dances to break retain cycle. But the code looks not good, we can borrow some macros to simplify code style, like [@weakify](https://github.com/jspahrsummers/libextobjc/blob/4296d9f115fcbf56bca2583e21cfa83740bf131a/extobjc/EXTScope.h#L45) from `libextobjc`.

https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/FLAnimatedImage/FLAnimatedImageView%2BWebCache.m#L173-L188

I think this is a `Good first issue`, anyone who wants to contribute can take a stab about this.

Related https://github.com/SDWebImage/SDWebImage/pull/2642#issuecomment-473493328.

**Comment by Insofan** [comment]
> Currently, we have many weak-strong dances to break retain cycle. But the code looks not good, we can borrow some macros to simplify code style, like [@weakify](https://github.com/jspahrsummers/libextobjc/blob/4296d9f115fcbf56bca2583e21cfa83740bf131a/extobjc/EXTScope.h#L45) from `libextobjc`.
> 
> https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/FLAnimatedImage/FLAnimatedImageView%2BWebCache.m#L173-L188
> 
> I think this is a `Good first issue`, anyone who wants to contribute can take a stab about this.
> 
> Related [#2642 (comment)](https://github.com/SDWebImage/SDWebImage/pull/2642#issuecomment-473493328).

I'll do my best for this part, recently I'm reading the source code.

**Comment by Insofan** [comment]
@zhongwuzw @dreampiggy There're massive dummy code. Should add tests for these retain cycle codes? I thought it's just repeat labor. And I wanna commit codes by directories order(there're 7 directories and I have read three of them). Do you have any advise for this issue.

**Comment by zhongwuzw** [comment]
@Insofan Go for it if you can help us to do code clean.

**Comment by dreampiggy** [comment]
Seems this is already done via #2647 . So close now.
