### ISSUE TITLE
SDWebImage crash when decode webp

### ISSUE THREAD

**Issue by xuvw** [SDWebImage/SDWebImage#2644]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          |  iOS
 Platform Version         |  12.5
 SDWebImage Version       |  4.4.5
 Integration Method       |  cocoapods
 Xcode Version           |   Xcode 10.1
 Repro rate               |  sometimes 3%

### Issue Description and Steps

when restart app from background ,scroll tableview, then crash at VP8TransformWHT(dc, dst);  line:532  file:vp8_dec.c  version:0.6.1  thank you!

**Comment by dreampiggy** [comment]
I found you're using SDWebImage 4.4.5 with WebP, is this issue related to #2621 ? Did you try the 4.4.6 version ?

**Comment by xuvw** [comment]
> I found you're using SDWebImage 4.4.5 with WebP, is this issue related to #2621 ? Did you try the 4.4.6 version ?

I've tried 4.4.6 but still crash

**Comment by dreampiggy** [comment]
Is there any WebP image url for testing ? Could you set a exception break point and find the image url (or if your break point have only image data, using lldb to write the image data to temp folder and upload here)

We need to investigate whether this is a bug of libwebp, or the use code of SDWebImage.

**Comment by xuvw** [comment]
> @xuvw Is there any WebP image url for testing ? Could you set a exception break point and find the image url (or if your break point have only image data, using lldb to write the image data to temp folder and upload here)
> 
> ```
> expr [imageData writeToFile:"/tmp/1.webp" atomically:YES];
> ```
> We need to investigate whether this is a bug of libwebp, or the use code of SDWebImage.

this is crash screen short:https://github.com/xuvw/SDWebImageCrash/blob/master/10_36_37__03_19_2019.jpg

**Comment by dreampiggy** [comment]
I means, which the detail WebP image cause this crash ? I've no idea how to reproduce this feature. So please at least, show me the WebP image url, or you can upload the WebP image to the comment here.

You can grab the image url from the stack trace using lldb, or output the WebP image data to your computer's directory using the lldb command.

**Comment by zhongwuzw** [comment]
Please provide like `Exception Type`, error code and related crash infos.
