### ISSUE TITLE
SDWebImage crash HTTPProtocol::shouldAttemptOriginLoad

### ISSUE THREAD

**Issue by mariohahn** [SDWebImage/SDWebImage#2649]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | tvOS
 Platform Version        | 12.1.2
 SDWebImage Version      | 4.4.6
 Integration Method      | cocoapods
 Xcode Version           | 10.1
 Repro rate              | sometimes 3 %
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

<img width="295" alt="Bildschirmfoto 2019-03-22 um 12 19 25" src="https://user-images.githubusercontent.com/915933/54819769-37b9a300-4c9d-11e9-8eee-d0c60318474a.png">

**Comment by zhongwuzw** [comment]
@mariohahn I think it's a bug from `CFNetwork`. Seems no more things we can do.

**Comment by aelam** [comment]
Please see this . https://forums.developer.apple.com/thread/110493
