### ISSUE TITLE
UICollectionViewCell  has a high probability that only the placeholder can be displayed.

### ISSUE THREAD

**Issue by gdxud2016** [SDWebImage/SDWebImage#2653]
@JKjiangnan Do you use `UITableView` or `UICollectionView`? because cell or `imageView` would be reused, so if we get a cell from reuse queue and set a new image url, we would cancel the download task of previous image, so these cancellation logs would be appear, do you faced any issue besides these annoying logs?

_Originally posted by @zhongwuzw in https://github.com/SDWebImage/SDWebImage/issues/2492#issuecomment-423953152_

**Comment by gdxud2016** [comment]
Hi,I add an imageview to the UICollectionviewCell and then used SDWebimage to download the image, but when I click the cell to change the url of the imageview and reloadData, the image of the imageview has a high probability that only the placeholder can be displayed.Can you tell me why?
error log:
Task <B8B5317A-D845-4FF3-85AE-0ADD61FDFFA5>.<13> HTTP load failed (error code: -999 [1:89])

**Comment by Insofan** [comment]
Could you provide a demo to reproduce this issue.

**Comment by nice2m** [comment]
I involved the issue too,request for a gif formated file,SDAnimatedImageView+WebCache.m - (void)sd_setImageWithURL:(nullable NSURL *)url placeholderImage:(nullable UIImage *)placeholder;

**Comment by gdxud2016** [comment]
This may be a network problem, but not sure, when the network speed is good, the chance of occurrence is relatively small.
