### ISSUE TITLE
I want to refactor SDWebImage disk cache, so want to discuss with maintainers.

### ISSUE THREAD

**Issue by Insofan** [SDWebImage/SDWebImage#2662]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |ios / macos / tvos / watchos
 Platform Version        |1.0 / 10.13.0 / 11.0 / 4.0
 SDWebImage Version      | All
 Integration Method      |  cocoapods
 Xcode Version           |Xcode 10
 Demo project link       | 
### Issue Description and Steps
I have done a pre version LRU strategy memory cache, it's designed by adapter pattern, it only change one property in SDImageCacheConfig class, I think if it through the unit test and benchmark, maybe it can merge into 5.0 version branch, see [issue #2655](https://github.com/SDWebImage/SDWebImage/issues/2655#issuecomment-478219816).

Currently sd disk cache logic removeExpiredData based on NSFileManager, we can provide a disk cache option in SDImageCacheConfig class(also memory cache option), let user to choose disk cache strategy. I have read several iOS platform cache frameworks. I think the best solution is implementation LRU(or other algorithms) disk cache is based on a database, there're two options,  first is the [YYCache](https://github.com/ibireme/YYCache) based on sqlite3, second is the [levelDb](https://github.com/google/leveldb), level db is a thread safe key value database, but levelDb will implementation with cpp. I hope to get your suggestions.

**Comment by dreampiggy** [comment]
> maybe it can merge into 5.0 version branch

5.0.0 is now feature-freezed. We'll release 5.0.0 major version tomorrow (After we fix the current PR issue). This PR can be ready for 5.1.0, since this does not break API.

If your PR, contains another dependency other than the system library, consider using the plugin in 5.0. Which means we can make this cache implementations as a optional choice for user, like [SDWebImageYYPlugin](https://github.com/SDWebImage/SDWebImageYYPlugin). The SDWebImge/Core should not have any external dependency actually...

**Comment by dreampiggy** [comment]
I'll have a review after 5.0.0 released. So place have a wait...Thanks.

**Comment by Insofan** [comment]
> I'll have a review after 5.0.0 released. So place have a wait...Thanks.

Ok I'll close this issue.
