### ISSUE TITLE
Download failed on iOS12.1.4

### ISSUE THREAD

**Issue by lilongCoder** [SDWebImage/SDWebImage#2665]
Failed to download on iOS12.1.4 system, good in iOS12.2 and iOS12.1.2, error log as follows:

Task <65415ED6-AD2D-4581-BABC-88513D70A81E>.<1> load failed with error Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=60, NSUnderlyingError=0x281a7cc90 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=60, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <65415ED6-AD2D-4581-BABC-88513D70A81E>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <65415ED6-AD2D-4581-BABC-88513D70A81E>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://118.31.36.78:6700/b/FileUpload/SF/79e4a792-6a77-4bea-bbe3-c56332ebddc8.png, NSErrorFailingURLKey=http://118.31.36.78:6700/b/FileUpload/SF/79e4a792-6a77-4bea-bbe3-c56332ebddc8.png, _kCFStreamErrorDomainKey=1} [-1001]

**Comment by Insofan** [comment]
Please fill the Issue Checklist, provide more information about this.

**Comment by lilongCoder** [comment]
Download failed on iOS12.1.4

* [ *] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [* ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [* ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        |  12.1.4
 SDWebImage Version      |  4.4.6
 Integration Method      |   cocoapods 
 Xcode Version           |  Xcode 10
 Repro rate              |  all the time 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | http://118.31.36.78:6700/b/FileUpload/SF/79e4a792-6a77-4bea-bbe3-c56332ebddc8.png

**Comment by Insofan** [comment]
Actually I even couldn't open this url on my chrome.Have you check this url is available. And maybe this issue as same as [# 2613](https://github.com/SDWebImage/SDWebImage/issues/2613)

**Comment by lilongCoder** [comment]
Thank you very much. My problem has been solved. This url is the address of Intranet.
