### ISSUE TITLE
UIImageView+WebCache should check its disk cache prior to setting the placeholder image

### ISSUE THREAD

**Issue by markkrenek** [SDWebImage/SDWebImage#267]
The way all the setImageWithURL: methods are implemented, they will temporarily display the placeholder image even if the image is in the disk cache. This leads to an undesirable flash onscreen. This is noticeable after the memory cache gets cleared, which happens each time you switch out to another app. When you come back to the app and cause things to be refreshed, your images are not in memory, the placeholder gets displayed, and then shortly after that, the disk cache version gets displayed. If setImageWithURL: checked the disk cache first, this could be avoided.

**Comment by skensell** [comment]
You can now solve this flashing issue with the SDWebImageDelayPlaceholder option.
