### ISSUE TITLE
Problems after the last update

### ISSUE THREAD

**Issue by UtkuDalmaz** [SDWebImage/SDWebImage#2672]
After the latest update, I am having these problems

<img width="897" alt="Screen Shot 2019-04-02 at 18 15 54" src="https://user-images.githubusercontent.com/2130592/55414429-c539a480-5573-11e9-8b6e-aa943848a991.png">

<img width="864" alt="Screen Shot 2019-04-02 at 18 15 35" src="https://user-images.githubusercontent.com/2130592/55414446-cc60b280-5573-11e9-82cb-366273d30ba4.png">

**Comment by Insofan** [comment]
If your project under XCode 10.2. try update cocoapod version then pod install sd again.Relation pr [#2652](https://github.com/SDWebImage/SDWebImage/pull/2652)

**Comment by UtkuDalmaz** [comment]
> If your project under XCode 10.2. try update cocoapod version then pod install sd again.Relation pr [#2652](https://github.com/SDWebImage/SDWebImage/pull/2652)

It is 10.2

**Comment by Insofan** [comment]
> > If your project under XCode 10.2. try update cocoapod version then pod install sd again.Relation pr [#2652](https://github.com/SDWebImage/SDWebImage/pull/2652)
> 
> It is 10.2

Update your pod to latest version then cd your project pod install, if your project still not work then checkout an other branch then go back pod install/update, replay this operation, it bug cause by cocopod.We'll fix it when pod 1.7.1 release.

**Comment by dreampiggy** [comment]
@UtkuDalmaz We've released SDWebImage 5.0.0 today. And this contains API-breaking because of major version upgrade.

Maybe you don't specify the sematic version like this in Podfile. So after the `pod update` you get the 5.0.0 version.

```
pod 'SDWebImage', `~> 4.4`
```

To migrate from the 4.x version to 5.0 version, please have a check at [5.0-Migration-Guide](https://github.com/SDWebImage/SDWebImage/wiki/5.0-Migration-guide). It contains the API changes from previous version, and some useful information about the replacement.

**Comment by Insofan** [comment]
> > If your project under XCode 10.2. try update cocoapod version then pod install sd again.Relation pr [#2652](https://github.com/SDWebImage/SDWebImage/pull/2652)
> 
> It is 10.2
Sorry I  didn't check your picture carefully. I thought it is a bulid failure. Dream piggy's advice may help you.

**Comment by dreampiggy** [comment]
For your screenshot detail cases, the migration can be like this:

1. `shouldDecompressImage` is now a image options `avoidDecodeImage` in `sd_setImage(with:)`, so you need update to provide this option. If you have large codebase, it's better to create your own extension and pass this as a default value.

2. Now, SDWebImage support custom downloader and custom cache, so the `SDWebImage.imageCache` is a protocol, the same as `SDWebImage.imageLoader`.

At this case, if you don't want to use any custom downloader or cache, please just using this code instead.

```swift
SDWebImageDownloader.shared.downloadImage(with: URL(string: resimlink))
SDImageCache.shared.storeImage(toMemory: image, forKey: key)
```

**Comment by UtkuDalmaz** [comment]
> For your screenshot detail cases, the migration can be like this:
> 
> 1. `shouldDecompressImage` is now a image options `avoidDecodeImage` in `sd_setImage(with:)`. It allows you to control which image URL need avoid pre-drawing and background decoding, which are not.
> 
> So you need update to use this option to disable the pre-drawing feature. If you have large codebase and want to disable it for all image requests, it's better to create your own convenient extension method, and pass this as a default value.
> 
> 1. Now, SDWebImage support custom downloader and custom cache, so the `SDWebImage.imageCache` is a protocol, the same as `SDWebImage.imageLoader`. They are not instance type.
> 
> At this case, if you don't want to use any custom downloader or cache, please just using this code instead.
> 
> ```swift
> SDWebImageDownloader.shared.downloadImage(with: URL(string: resimlink))
> SDImageCache.shared.storeImage(toMemory: image, forKey: key)
> ```
> 
> Or you can check the class to ensure usage
> 
> ```swift
> if let downloader = SDWebImage.imageLoader as? SDWebImageDownloader {
>    // blabla
> }
> ```

I fixed the second one by using `SDWebImageManager.shared.imageLoader.requestImage`

I wasn't able to fix the first one. Can you show me an example?

**Comment by dreampiggy** [comment]
@UtkuDalmaz For what your use case, there are many ways.

## I want to disable pre-drawing and background decoding globally

It's better to create a convenient category instead.

```swift
extension UIImageView {
    func my_setImage(with url: URL, placeholderImage: UIImage? = nil, options: SDWebImageOptions = [], context: [SDWebImageContextOption : Any]? = nil, progress: SDImageLoaderProgressBlock? = nil, completed: SDExternalCompletionBlock? = nil) -> Void {
        var options = options
        options.insert(.avoidDecodeImage) // shouldDecompress = false 
        self.sd_setImage(with: url, placeholderImage: placeholderImage, options: options, context: context, progress: progress, completed: completed)
    }
}
``
Then change all the codebase to using this instead. It's a good idea for large codebase.

## I want to only disable some large images's background decoding, keeping enable for small images to increate frame rate.

Just decide which of image request should use, which should not. And provide `avoidDecodeImage` for large images.

```swift
imageView.sd_setImage(with: url, placeholderImage: placeholderImage, options: [.avoidDecodeImage], context: context, progress: progress, completed: completed)
```

**Comment by UtkuDalmaz** [comment]
Thanks
All fixed now
