### ISSUE TITLE
Unexpected '@' in program

### ISSUE THREAD

**Issue by Grayson2019** [SDWebImage/SDWebImage#2680]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.1
 SDWebImage Version      | 5.0.0
 Integration Method      | manually
 Xcode Version           | Xcode10

### Issue Description and Steps

I'm a beginner to iOS development. When I build it, the ```@weakify(self)``` and the ```@strongify(self)``` are warned with **"Unexpected '@' in program"**. I don't know how to fix it.

**Comment by Insofan** [comment]
Please read [Installation Guide](https://github.com/SDWebImage/SDWebImage/wiki/Installation-Guide). I suggest you install SD 5.0 with [cocoapod](https://guides.cocoapods.org/using/getting-started.html). If you want to know weaify && strongify marcros, this file [SDInternalMacros.h](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Private/SDInternalMacros.h) may help you. 

## The main steps of pod install SD 5.0

Notice: **The following are the main steps, you may need to a little adjust**

1. ##### Install cocoapod

```
sudo gem install -n /usr/local/bin cocoapods
```

2. ##### Cd to your project

```
cd /your-project-path/
```

3. ##### Init cocoapod

```
pod init
```

4. ##### Add Sd to your pod file

```
// first step: edit Podfile
vim Podfile
// second step: add sub line to your pod file, just like the Installation Guide
 pod 'SDWebImage', '~> 5.0'
```

5. ##### Install SD

```
pod install
```

6. Open your project **workspace** then run it

   Your project should build successfuly.

**Comment by Grayson2019** [comment]
> Please provide more infomation about XCode version and your cocoapod version. If you integrate Sd manually. I suggest you install SD 5.0 with [cocoapod](https://guides.cocoapods.org/using/getting-started.html). Please read [Installation Guide](https://github.com/SDWebImage/SDWebImage/wiki/Installation-Guide). If you want to know weaify && strongify marcros, this file [SDInternalMacros.h](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Private/SDInternalMacros.h) may help you.
> 
> ## The main steps of pod install SD 5.0
> Notice: **The following are the main steps, you may need to a little adjust on your device**
> 
> 1. ##### Install cocoapod
> 
> ```
> sudo gem install -n /usr/local/bin cocoapods
> ```
> 1. ##### Cd to your project
> 
> ```
> cd /your-project-path/
> ```
> 1. ##### Init your project to a workspace  with pod
> 
> ```
> pod init
> ```
> 1. ##### Add Sd to your pod file
> 
> ```
> // first step: edit Podfile
> vim Podfile
> // second step: add sub line to your pod file, just like the Installation Guide
>  pod 'SDWebImage', '~> 5.0'
> ```
> 1. ##### Install SD
> 
> ```
> pod install
> ```
> 1. Open your project **workspace** then run it
>    Your project should build successfuly.

**Comment by Grayson2019** [comment]
> Please provide more infomation about XCode version and your cocoapod version. If you integrate Sd manually. I suggest you install SD 5.0 with [cocoapod](https://guides.cocoapods.org/using/getting-started.html). Please read [Installation Guide](https://github.com/SDWebImage/SDWebImage/wiki/Installation-Guide). If you want to know weaify && strongify marcros, this file [SDInternalMacros.h](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Private/SDInternalMacros.h) may help you.
> 
> ## The main steps of pod install SD 5.0
> Notice: **The following are the main steps, you may need to a little adjust on your device**
> 
> 1. ##### Install cocoapod
> 
> ```
> sudo gem install -n /usr/local/bin cocoapods
> ```
> 1. ##### Cd to your project
> 
> ```
> cd /your-project-path/
> ```
> 1. ##### Init your project to a workspace  with pod
> 
> ```
> pod init
> ```
> 1. ##### Add Sd to your pod file
> 
> ```
> // first step: edit Podfile
> vim Podfile
> // second step: add sub line to your pod file, just like the Installation Guide
>  pod 'SDWebImage', '~> 5.0'
> ```
> 1. ##### Install SD
> 
> ```
> pod install
> ```
> 1. Open your project **workspace** then run it
>    Your project should build successfuly.

Alright, I'll have a try.

**Comment by Grayson2019** [comment]
> > Please provide more infomation about XCode version and your cocoapod version. If you integrate Sd manually. I suggest you install SD 5.0 with [cocoapod](https://guides.cocoapods.org/using/getting-started.html). Please read [Installation Guide](https://github.com/SDWebImage/SDWebImage/wiki/Installation-Guide). If you want to know weaify && strongify marcros, this file [SDInternalMacros.h](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Private/SDInternalMacros.h) may help you.
> > ## The main steps of pod install SD 5.0
> > Notice: **The following are the main steps, you may need to a little adjust on your device**
> > 
> > 1. ##### Install cocoapod
> > 
> > ```
> > sudo gem install -n /usr/local/bin cocoapods
> > ```
> > 
> > 1. ##### Cd to your project
> > 
> > ```
> > cd /your-project-path/
> > ```
> > 
> > 1. ##### Init your project to a workspace  with pod
> > 
> > ```
> > pod init
> > ```
> > 
> > 1. ##### Add Sd to your pod file
> > 
> > ```
> > // first step: edit Podfile
> > vim Podfile
> > // second step: add sub line to your pod file, just like the Installation Guide
> >  pod 'SDWebImage', '~> 5.0'
> > ```
> > 
> > 1. ##### Install SD
> > 
> > ```
> > pod install
> > ```
> > 
> > 1. Open your project **workspace** then run it
> >    Your project should build successfuly.
> 
> Alright, I'll have a try.

Thank you very much.
