### ISSUE TITLE
[SDImageCache cachePathForKey:]: unrecognized selector

### ISSUE THREAD

**Issue by brightsider** [SDWebImage/SDWebImage#2684]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.2
 SDWebImage Version      | 5.0.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.2
 Repro rate              | all time

### Issue Description and Steps

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SDImageCache cachePathForKey:]: unrecognized selector sent to instance 0x6000023594c0'

```
let cache = SDImageCache.shared
let path = cache.cachePath(forKey: key)!
```

**Comment by Insofan** [comment]
@brightsider Please provide more information to reproduce this issue. I have try follow code.
```
  let cache = SDImageCache.shared
 //Only the arg is a nil object and unwrapping it encounter a fatal error.But I haven't encounter your message receiver error.
  let path = cache.cachePath(forKey: nil)!
  print(path as Any)
```
It seems unrecognized SDDiskCache's method [reference link](https://github.com/SDWebImage/SDWebImage/blob/767a6643f87d3ca9e90c5746aded35ccf2555b94/SDWebImage/SDDiskCache.m#L201-L204) .

**Comment by dreampiggy** [comment]
@brightsider Really strange issue.

Are you sure just this demo code cause the crash ?

```swift
let key = "test"
let cache = SDImageCache.shared
let path = cache.cachePath(forKey: key)!
print(path)
```

![image](https://user-images.githubusercontent.com/6919743/55771248-d6296f00-5ab9-11e9-9963-f205f4da78b3.png)


I try and no any crash happened. So could you please provide more information about it ? Such as the full code sample, or your environment (Swift version ?).

And also, did you using a [Custom Cache](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-cache-50) feature ? If you specify a badly written cache implementation, maybe this cause some potential issue.

**Comment by brightsider** [comment]
Sorry, it's an issue of CocoaPods. Full clean of project help with crash.
