### ISSUE TITLE
No visible @interface for 'SDImageCache' declares the selector 'defaultCachePathForKey:'

### ISSUE THREAD

**Issue by Lidalu** [SDWebImage/SDWebImage#2686]
When I update SDWebImage to 5.0.0, I can't find the method named 'defaultCachePathForKey:', In 5.0.0 version, It named 'cachePathForKey:'.
Can you not change the method name? It has affected our app several times. Please!!!

**Comment by dreampiggy** [comment]
Please see the [5.0 miguration guide](https://github.com/SDWebImage/SDWebImage/wiki/5.0-Migration-guide) first. It already provide the detail information for this.

+ cachePathForKey:inPath: removed, use cachePathForKey: with NSString's path API instead.
+ defaultCachePathForKey: removed, use cachePathForKey: instead

**Comment by dreampiggy** [comment]
If you want to know the reason to change this API. See https://github.com/SDWebImage/SDWebImage/pull/2276
