### ISSUE TITLE
No known class method for selector 'sd_imageWithWebPData:'

### ISSUE THREAD

**Issue by FrankiezZZ** [SDWebImage/SDWebImage#2687]
hi, i am having a problem.
i depend 'SDWebImage/WebP' in my podA
and i depend 'SDWebImage/GIF' in podB which depend by podA.
like this
![image](https://user-images.githubusercontent.com/12370297/55850613-9fba2580-5b87-11e9-8fa4-1b2862717218.png)
when i use -sd_imageWithWebPData: in WebP ,i have this problem 'No known class method for selector 'sd_imageWithWebPData:' ' 
thank u!

**Comment by dreampiggy** [comment]
Seems you're using SDWebImage 4.x as a upstream dependency.

SDWebImage's WebP subspec, using the predefined macro for WebP specify code compile. If you dependency the Pod, check that you have also inherit the `SD_WEBP` macro.

See 4.4.6's [podspec](https://github.com/SDWebImage/SDWebImage/blob/4.4.6/SDWebImage.podspec#L53-L56)

```
    webp.xcconfig = { 
      'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) SD_WEBP=1',
      'USER_HEADER_SEARCH_PATHS' => '$(inherited) $(SRCROOT)/libwebp/src'
    }
```

**Comment by FrankiezZZ** [comment]
@dreampiggy thank you, your blog help me a lot👍
