### ISSUE TITLE
Azure pipeline + CI/CD

### ISSUE THREAD

**Issue by Shamshuddinshaik777** [SDWebImage/SDWebImage#2688]
Hi Team,

I am using Framework for one of my project. It is really very helpful. We have started doing Build automation using Azure pipeline. But I am receiving the following error while archiving the build in Azure pipeline.

Could you please help me on resolving this issue. Please let me know if you need more info.

The following build commands failed:
	CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/Objects-normal/armv7/NSButton+WebCache.o SDWebImage/SDWebImage/NSButton+WebCache.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Thanks,
Shaik

**Comment by kinarob** [comment]
What version of SDWebImage are you currently using? Have you tried `Clean` before you use Azure pipeline?

**Comment by Shamshuddinshaik777** [comment]
HI kinarob,

pod 'SDWebImage', '~> 5.0'

And in Azure Pipeline (azure-pipelines.yml)
- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'clean build analyze archive'

**Comment by zhongwuzw** [comment]
@Shamshuddinshaik777 Recommend to read Azure [Docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/xcode?view=azure-devops).

**Comment by Shamshuddinshaik777** [comment]
Hi zhongwuzw,

I am following the same [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/xcode?view=azure-devops). I am able to build for other pods except SDWebImage.

**Comment by dreampiggy** [comment]
> The following build commands failed:
CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/Objects-normal/armv7/NSButton+WebCache.o SDWebImage/SDWebImage/NSButton+WebCache.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

This build log seems missing the detail of compile failed reason. Could you please using `xcodebuild --verbose` to log the detail output ?

**Comment by Shamshuddinshaik777** [comment]
Hi 

Updated with log

NSData+ImageContentType.m

CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/Objects-normal/armv7/NSData+ImageContentType.o SDWebImage/SDWebImage/NSData+ImageContentType.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

    cd /Users/vsts/agent/2.149.2/work/1/s/ProjectName_iOS/Pods
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode_9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode_9.4.1.app/Contents/Developer/usr/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/vsts/bin:/Users/vsts/.yarn/bin:/usr/local/go/bin:/Users/vsts/Library/Android/sdk/tools:/Users/vsts/Library/Android/sdk/platform-tools:/Users/vsts/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vsts/.azcopy"

    /Applications/Xcode_9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=SDWebImage -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_RELEASE=1 -DCOCOAPODS=1 -DNS_BLOCK_ASSERTIONS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode_9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wunguarded-availability -fembed-bitcode -iquote /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/SDWebImage-generated-files.hmap -I/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/SDWebImage-own-target-headers.hmap -I/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/SDWebImage-all-non-framework-target-headers.hmap -ivfsoverlay /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/all-product-headers.yaml -iquote /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/SDWebImage-project-headers.hmap -I/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/BuildProductsPath/Release-iphoneos/SDWebImage/include -I/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/DerivedSources/armv7 -I/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/DerivedSources -F/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/BuildProductsPath/Release-iphoneos/SDWebImage -include /Users/vsts/agent/2.149.2/work/1/s/ProjectName_iOS/Pods/Target\ Support\ Files/SDWebImage/SDWebImage-prefix.pch -MMD -MT dependencies -MF /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/Objects-normal/armv7/NSData+ImageContentType.d --serialize-diagnostics /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/Objects-normal/armv7/NSData+ImageContentType.dia -c /Users/vsts/agent/2.149.2/work/1/s/ProjectName_iOS/Pods/SDWebImage/SDWebImage/NSData+ImageContentType.m -o /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/Objects-normal/armv7/NSData+ImageContentType.o
<built-in>:1:10: fatal error: '/Users/vsts/agent/2.149.2/work/1/s/ProjectName_iOS/Pods/Target Support Files/SDWebImage/SDWebImage-prefix.pch' file not found
#include "/Users/vsts/agent/2.149.2/work/1/s/ProjectName_iOS/Pods/Target Support Files/SDWebImage/SDWebImage-prefix.pch"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

NSButton+WebCache.m

CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/Objects-normal/armv7/NSButton+WebCache.o SDWebImage/SDWebImage/NSButton+WebCache.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/vsts/agent/2.149.2/work/1/s/ProjectName/Pods
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode_9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode_9.4.1.app/Contents/Developer/usr/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/vsts/bin:/Users/vsts/.yarn/bin:/usr/local/go/bin:/Users/vsts/Library/Android/sdk/tools:/Users/vsts/Library/Android/sdk/platform-tools:/Users/vsts/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vsts/.azcopy"
    /Applications/Xcode_9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=SDWebImage -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_RELEASE=1 -DCOCOAPODS=1 -DNS_BLOCK_ASSERTIONS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode_9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wunguarded-availability -fembed-bitcode -iquote /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/SDWebImage-generated-files.hmap -I/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/SDWebImage-own-target-headers.hmap -I/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/SDWebImage-all-non-framework-target-headers.hmap -ivfsoverlay /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/all-product-headers.yaml -iquote /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/SDWebImage-project-headers.hmap -I/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/BuildProductsPath/Release-iphoneos/SDWebImage/include -I/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/DerivedSources/armv7 -I/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/DerivedSources -F/Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/BuildProductsPath/Release-iphoneos/SDWebImage -include /Users/vsts/agent/2.149.2/work/1/s/ProjectName/Pods/Target\ Support\ Files/SDWebImage/SDWebImage-prefix.pch -MMD -MT dependencies -MF /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/Objects-normal/armv7/NSButton+WebCache.d --serialize-diagnostics /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/Objects-normal/armv7/NSButton+WebCache.dia -c /Users/vsts/agent/2.149.2/work/1/s/ProjectName/Pods/SDWebImage/SDWebImage/NSButton+WebCache.m -o /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-chcqbmyfggvewyheagjlagpdtjbt/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/SDWebImage.build/Objects-normal/armv7/NSButton+WebCache.o
<built-in>:1:10: fatal error: '/Users/vsts/agent/2.149.2/work/1/s/ProjectName/Pods/Target Support Files/SDWebImage/SDWebImage-prefix.pch' file not found
#include "/Users/vsts/agent/2.149.2/work/1/s/ProjectName/Pods/Target Support Files/SDWebImage/SDWebImage-prefix.pch"

**Comment by dreampiggy** [comment]
It seems you're using CocoaPods. (Please fill the issue template, again :))

And please check your CocoaPods version.

It looks like something wrong with your prefix header files. It's written in Podspec standard syntax, and should be created. Or it's a CocoaPods's bug, need something to check

You can check Pod install generated project again, or using `pod install --verbose` to see what happend.

See the podspec here : [Podspec](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage.podspec#L34)
