### ISSUE TITLE
How To Fetch Cached Image?

### ISSUE THREAD

**Issue by LionWY** [SDWebImage/SDWebImage#2694]
Should I use `[[SDImageCache sharedImageCache] imageFromCacheForKey:cacheKey]` to get the cached image?

**Comment by dreampiggy** [comment]
In short, it's OK. But it may become compilicated if you're using Custom Cache feature of SDWebImage 5.0.

+ For memory cache (sync):

```objectivec
[SDImageCache.sharedImageCache imageFromMemoryCacheForKey:key];
```

+ For disk cache (sync):

```objectivec
[SDImageCache.sharedImageCache imageFromDiskCacheForKey:key];
```

+ For both memory / disk cache (sync):

```objectivec
[SDImageCache.sharedImageCache imageFromCacheForKey:key];
```

+ For async version of `SDImageCache`

```objectivec
[SDImageCache.sharedImageCache queryCacheOperationForKey:key done:^{ // ... }];
```

+ For asynv version of Custom Cache (Also you can use it on `SDImageCache`)

```objectivec
id<SDImageCache> cache;
[cache queryImageForKey:key options:0 context:nil completion:^{ // ... }];
```
