### ISSUE TITLE
Option/Completed - Swift 

### ISSUE THREAD

**Issue by badfranco** [SDWebImage/SDWebImage#2696]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide] (https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md) **Kinds not really** 
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/) **Yes**
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        | 12.1
 SDWebImage Version      | 5.0.0
 Integration Method      | cocoapods 
 Xcode Version           | .Xcode 10 
## Issue Description and Steps

Hello i have more of a question that any type of issues, bc i am using swift not objective and i am quite a noob to coding i don't really understand some of the code. I would like a simple explanation if possible. 

here is my code:
`let imageback = UIImage(named: "whiteCategoryImage.png")
        cell.categoryImage.sd_setImage(with: urla, placeholderImage: imageback, options: [.progressiveLoad], completed: nil)` 

i wanna understand how to handle `completed:` currently i have `nil` is this good enough? or do i have to look for an error ?

Also what's the best `option:` i can use? can the placeholder be displayed as the image loads in the background ?

Thank you for the help and support in advanced...

**Comment by dreampiggy** [comment]
> i wanna understand how to handle completed: currently i have nil is this good enough? or do i have to look for an error ?

If you need some specify logic after one image load finished, such as logger, extra view rendering, etc. You may provide a closure for completion block.

If you don't care about it, just ignore it.

> Also what's the best option: i can use? can the placeholder be displayed as the image loads in the background ?

If you need to display a placeholder during loading, you just pass the image in `placeholderImage` arg. No extra options is needed.

And, you can check our [documentation](https://sdwebimage.github.io/Enums/SDWebImageOptions.html), it describe the detail behaviors for each option and context arg. It's for different users' use case. I can not say that there is a `Best` one to choose. But typicaly, the default option (empty actually) is the thing we think most people will use.

**Comment by badfranco** [comment]
Thank you! i've removed the both options & completed
