### ISSUE TITLE
[Question] Replicate Prefetching images into memory (SDWebImageCacheMemoryOnly) in v5?

### ISSUE THREAD

**Issue by IljaDaderko** [SDWebImage/SDWebImage#2698]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.0
 SDWebImage Version      | 5.0.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10
 Repro rate              | 100%
 Repro with our demo prj | Likely yes
 Demo project link       | -

### Issue Description and Steps

While using SDWebImage v4 it was possible to set options to cache images in memory only via

```objc
SDWebImagePrefetcher.sharedImagePrefetcher.options = SDWebImageCacheMemoryOnly;
```

This no longer seems to be an option with v5, hence this question. By default it seems that cached images are coming from disc. (Some images appear on screen with delay, which I previously solved by prefetching them in memory).

I saw in migration guide that v5 now splits disc and memory cache, but I am not able to figure out how to tell prefetcher to store images in memory only.

**Comment by IljaDaderko** [comment]
Closing in favour of https://stackoverflow.com/questions/55749720/replicate-prefetching-images-into-memory-sdwebimagecachememoryonly-in-v5

**Comment by dreampiggy** [comment]
There is a context option called `storeCacheType`, the value type is `SDImageCacheType`. See the documentation about it.

```objectivec
/**
 A SDImageCacheType raw value which specify the cache type when the image has just been downloaded and will be stored to the cache. Specify `SDImageCacheTypeNone` to disable cache storage; `SDImageCacheTypeDisk` to store in disk cache only; `SDImageCacheTypeMemory` to store in memory only. And `SDImageCacheTypeAll` to store in both memory cache and disk cache.
 If not provide or the value is invalid, we will use `SDImageCacheTypeAll`. (NSNumber)
 */
FOUNDATION_EXPORT SDWebImageContextOption _Nonnull const SDWebImageContextStoreCacheType;
```

So. You just need to control your prefetcher, to use the `.memoryOnly` enum for this store cache type control.


```objectivec
SDWebImagePrefetcher.sharedImagePrefetcher.context = @{SDWebImageContextStoreCacheType : @(SDImageCacheTypeMemory)};
```
