### ISSUE TITLE
Feature Request: store both transformed image and original image to cache, and allows for later query

### ISSUE THREAD

**Issue by dreampiggy** [SDWebImage/SDWebImage#2700]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | ios 12.0
 SDWebImage Version      | 5.0.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10
 Repro rate              | all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

SDWebImage 5.0 provide a feature called transformer, which allow you to do image processing after decoding, apply somehting like scale, rotation, rounded corners, which is useful for some Apps's rendering and display of images.

However, currently, when using transformer, I can only store the transformed image into cache. The original full resolution image is dropped. So next time, if I need the same URL of image, to apply a different image processing style, or want to show the full images, I have to re-download it again.

This is a common usage, in the master-detail based Apps, or Apps contains a list for images, and the detail pages contains the images. The list page images have a small scale or rounded corners transformer, but the detail pages does not.

**Comment by dreampiggy** [comment]
This issue, can be solved by PR #2590 . See the PR for more detail about the solution

**Comment by rhkrthdud7** [comment]
@dreampiggy hello I am currently looking for this feature does anybody know when this feature will be available or are there any plans so far? thanks

**Comment by dreampiggy** [comment]
@kinarob Anytime to review that #2590 and #2591 ?

I think the #2591 and succesfully solve this feature request.

**Comment by dreampiggy** [comment]
Closed because of #2590 is merged.
#2591 is closed without merge, because current it contains some issue. Maybe need further feedback to decide whether to implements or not.

**Comment by rhkrthdud7** [comment]
@dreampiggy Thanks! I will be waiting for the next update!
