### ISSUE TITLE
Feature request: Allows the UIButton to check and set different state for current `progress` and `transition`

### ISSUE THREAD

**Issue by dreampiggy** [SDWebImage/SDWebImage#2701]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Feature Description

SDWebImage's `UIView+WebCache`, provide some properties, like

+ sd_imageURL
+ sd_imageProgress
+ sd_imageTransition

It works great for normal UIImageView, which have one single image to be query and load.

However, things become more complicated when using these properties on `UIButton`, because UIButton have different state, each state can represent a different image query pipelilne. See the already exist API:

```
- (void)sd_setImageWithURL:(nullable NSURL *)url
                  forState:(UIControlState)state NS_REFINED_FOR_SWIFT;
```

So, actually, these properties, which tied to single image request, should also have a correspond API for different UIButton state. Like the following:

+ sd_imageURLForState:     **Already Done**
+ sd_imageProgressForState:
+ sd_imageTransitionForState:

### Similar use case
The same thing, can also apply for the `UIImageView+HighlightedWebCache`, which should have the coorespond APIs like the following:

+ sd_highlightedImageURL
+ sd_highlightedImageProgress
+ sd_highlightedImageTransition

Note: The Indicator feature, is not under consideration for this case, because from all the usage, the indicator on `UIButton` is not a good idea. And it's a UIView's subview, it's not designed to dynamically removed and re-add base on state.

**Comment by Insofan** [comment]
> The same thing, can also apply for the `UIImageView+HighlightedWebCache`, which should have the coorespond APIs like the following:
> 
> * sd_highlightedImageURL
> * sd_highlightedImageProgress
> * sd_highlightedImageTransition

I dont understand this part, high light image already have progress and transition? 

```
    SDAnimatedImageView *image = [SDAnimatedImageView new];
    [image setHighlighted: true];
    [image sd_setHighlightedImageWithURL:[NSURL URLWithString:str]];
    image.sd_imageTransition = SDWebImageTransition.flipFromTopTransition;
```

**Comment by dreampiggy** [comment]
@cntrump Hi. I see you have some use case for this State-like View API. Which means, a `UIView` have multiple image and their responding state, like URL, progress, indicator, transaction at the same time.

Could you explain your detail use case, to help me to solve this issue, with a more general, extensible solution ?

**Comment by dreampiggy** [comment]
I wonder, if the user who want to call `UIView+WebCache` methods, are all advanced users, we can treat this `UIView+WebCache` as a building block API for developer who want to make their own class with SDWebImage category.

For example, if this is true, I'll provide some powerful API (but hard to use for simple one line code) for this. This is my first design draft.

**Comment by dreampiggy** [comment]
```objective-c
/**
 A loading storage keeping all of the related property, associated to single image request
 */
@interface SDWebImageLoadStorage

// Description is same as current property
@property (nonatomic, strong, readonly, nullable) NSURL *imageURL;
@property (nonatomic, strong, null_resettable) NSProgress *imageProgress;
@property (nonatomic, strong, nullable) SDWebImageTransition *imageTransition;
@property (nonatomic, strong, nullable) id<SDWebImageIndicator> imageIndicator;

@end


@interface UIView (WebCache)

/**
 Return the loading storage for specify operation key.
 */
- (nullable SDWebImageLoadStorage *)sd_imageLoadStorageForKey:(nullable NSString *)key
/**
 Specify a desired loading storage for opeartion key
 */
- (void)sd_setImageLoadStorage:(nullable SDWebImageLoadStorage *)storage forKey:(nullable NSString *)key;

@end
```

**Comment by dreampiggy** [comment]
Usage code for cases when I want to observe different state's loading progress on UIButton:

```objective-c
- (void)testUIButton {
    NSURL *url;
    NSURL *disabledUrl;
    
    // Normal
    SDWebImageLoadStorage *storage = [SDWebImageLoadStorage new];
    UIButton *button = [UIButton new];
    UIControlState state = UIControlStateNormal;
    NSString *key = [UIButton sd_imageOperationKeyForState:state];
    [button sd_setImageLoadStorage:storage forKey:key];
    
    [self.KVOController observe:storage.imageProgress keyPath:NSStringFromSelector(@selector(fractionCompleted)) options:NSKeyValueObservingOptionNew block:^(id  _Nullable observer, id  _Nonnull object, NSDictionary<NSString *,id> * _Nonnull change) {
        // ....
    }];
    [button sd_setImageWithURL:url forState:state];
    
    // Disabled
    state = UIControlStateDisabled;
    key = [UIButton sd_imageOperationKeyForState:state];
    SDWebImageLoadStorage *disabledStorage = [SDWebImageLoadStorage new];
    [button sd_setImageLoadStorage:disabledStorage forKey:key];
    
    [self.KVOController observe:disabledStorage.imageProgress keyPath:NSStringFromSelector(@selector(fractionCompleted)) options:NSKeyValueObservingOptionNew block:^(id  _Nullable observer, id  _Nonnull object, NSDictionary<NSString *,id> * _Nonnull change) {
        // ....
    }];
    [button sd_setImageWithURL:disabledUrl forState:state];
}
```

**Comment by dreampiggy** [comment]
Usage code for cases when I want to set different transaction animation for normal image and highlighted image on UIImageView:

```
- (void)testUIImageView {
    NSURL *url;
    NSURL *highlightedUrl;
    
    // image
    UIImageView *imageView = [UIImageView new];
    SDWebImageLoadStorage *storage = [SDWebImageLoadStorage new];
    storage.imageTransition = SDWebImageTransition.fadeTransition;
    NSString *key = [UIImageView sd_imageOperationKey]; // actually is nil, or `NSStringFromClass`
    [imageView sd_setImageLoadStorage:storage forKey:key];
    [imageView sd_setImageWithURL:url];
    
    // highlighted image
    key = [UIImageView sd_highlightedImageOperationKey];
    SDWebImageLoadStorage *backgroundStorage = [SDWebImageLoadStorage new];
    backgroundStorage.imageTransition = SDWebImageTransition.flipFromTopTransition;
    [imageView sd_setHighlightedImageWithURL:highlightedUrl];
}
```

**Comment by dreampiggy** [comment]
For convience API on `UIButton+WebCache.h`, we can create one like this


```
@interface UIButton (WebCache)
/**
 Get the image progress for a control state.
 */
- (nullable NSProgress *)sd_imageProgressForState:(UIControlState)state;
/**
 Get the background image progress for a control state.
 */
- (nullable NSProgress *)sd_backgroundImageProgressForState:(UIControlState)state;
@end

@implementation UIButton (WebCache)

- (NSProgress *)sd_imageProgressForState:(UIControlState)state {
    NSString *key = [UIButton sd_imageOperationKeyForState:state];
    SDWebImageLoadStorage *storage = [self sd_imageLoadStorageForKey:key];
    return storage.imageProgress;
}

- (NSProgress *)sd_backgroundImageProgressForState:(UIControlState)state {
    NSString *key = [UIButton sd_backgroundImageOperationKeyForState:state];
    SDWebImageLoadStorage *storage = [self sd_imageLoadStorageForKey:key];
    return storage.imageProgress;
}

@end
```

**Comment by dreampiggy** [comment]
Fix in future
