### ISSUE TITLE
Is there something wrong with SDCGContextTransformFromOrientation?

### ISSUE THREAD

**Issue by freespinach** [SDWebImage/SDWebImage#2703]
I couldn't get the expected value when I tested the function named SDCGContextTransformFromOrientation.

I modified this function as below.

static inline CGAffineTransform SDCGContextTransformFromOrientation(CGImagePropertyOrientation orientation, CGSize size) {

    CGAffineTransform transform = CGAffineTransformIdentity;
    switch (orientation) {
        case kCGImagePropertyOrientationUp:
            break;
        case kCGImagePropertyOrientationUpMirrored:
            transform = CGAffineTransformScale(transform, -1, 1);
            break;
        case kCGImagePropertyOrientationDown:
            transform = CGAffineTransformRotate(transform, M_PI);
            break;
        case kCGImagePropertyOrientationDownMirrored:
            transform = CGAffineTransformScale(transform, 1, -1);
            break;
        case kCGImagePropertyOrientationLeftMirrored:
            transform = CGAffineTransformRotate(transform, -M_PI_2);
            transform = CGAffineTransformScale(transform, -1, 1);
            break;
        case kCGImagePropertyOrientationRight:
            transform = CGAffineTransformRotate(transform, M_PI_2);
            break;
        case kCGImagePropertyOrientationRightMirrored:
            transform = CGAffineTransformScale(transform, -1, 1);
            transform = CGAffineTransformRotate(transform, -M_PI_2);
            break;
        case kCGImagePropertyOrientationLeft:
            transform = CGAffineTransformRotate(transform, -M_PI_2);
            break;
    }
    
    return transform;
}

**Comment by dreampiggy** [comment]
@freespinach Hi. This inline method is internally used by SDWebImage's image processing code. Could you please describe your problem ?

+ Does this implementaion, cause any bug related to SDWebImage?
+ Do you want to use this implmentation in another project ?

**Comment by dreampiggy** [comment]
This method is used for `CGImageRef`, which rotate a CGImage by respect the specify EXIF orientation, is not designed to rotate anything other than CGImage (CGContext, for example). And it need to extra calculation before calling this. See: [SDImageCoderHelper.m](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/SDImageCoderHelper.m#L253-L271)

**Comment by dreampiggy** [comment]
@freespinach See the latest code. If you need to rotate the CGImageRef as well. Which fix the bug of wrong width/height aspect ratio.
