### ISSUE TITLE
Does SDWebImage support download and cache encrypted image/video?

### ISSUE THREAD

**Issue by dungeonsnd** [SDWebImage/SDWebImage#2712]
I wanna use the SDWebImage in downloading and caching encrypted images and videos. 
Is there any place to write my own decryption code?
Thanks.

**Comment by dreampiggy** [comment]
Wiki is your friend, please check it in detail.

Depends on your detail use case, you can use any following method for this.

+ [Custom Download Operation](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-download-operation-40), subclass and override the URLSessionDelegate method for data, then do decrypted and call super.
+ [Custom Image Coder](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-coder-420), provide a decoder which firstly decrypt the data and then call the original coders manager.
+ [Custom Image Loader](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-loader-50), implements your own network stack, data provider for the compressed image data like JPEG, which don't limit on where the data from (maybe local, maybe FTP/WebDav/iCloud/ThirdParty SDK...)

**Comment by dreampiggy** [comment]
If you want, you can even try to load small video format into Animated Image form. But since Video Player is far more performent than image render solution, optimized for 60 FPS render with large resolution and audio, I suggest you should use the correct tools to do the suitable things.

**Comment by dungeonsnd** [comment]
I'll try your methods.
Thanks again.
