### ISSUE TITLE
dyld: Symbol not found - 

### ISSUE THREAD

**Issue by timbms** [SDWebImage/SDWebImage#2717]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        | 12.0 
 SDWebImage Version      |  5.0.0 
 Integration Method      | cocoapods 
 Xcode Version           |  Xcode 10 
 Repro rate              | all the time (100%) 
 Repro with our demo prj | Not tested
 Demo project link       | No demo 

### Issue Description and Steps

Debugger hangs with dyld: Symbol not found - when trying to use requestModifier
```
let requestModifier = SDWebImageDownloaderRequestModifier { (request) -> URLRequest? in
            let authStr = "\(self.openHABUsername):\(self.openHABPassword)"
            let authData: Data? = authStr.data(using: .ascii)
            let authValue = "Basic \(authData?.base64EncodedString(options: []) ?? "")"
            var r = request
            r.setValue(authValue, forHTTPHeaderField: "Authorization")
            return r
        }
SDWebImageDownloader.shared.requestModifier = requestModifier

```

I resolved the issue by changing the import statement in Podfile from 
```
pod 'SDWebImage', '~> 5.0'
```
to
```
pod 'SDWebImage', '~> 5.0' , :modular_headers => true
```

**Comment by dreampiggy** [comment]
> pod 'SDWebImage', '~> 5.0'

Did you means, you use SDWebImage as dynamic framework, with `use_frameworks!` enabled ?

I try this dynamic framework scenario, it works well for debugger. Maybe you need to cleanup the CocoaPods && Xcode cache ?

![image](https://user-images.githubusercontent.com/6919743/57351572-fe79bb80-7194-11e9-9f03-988fe26e4802.png)
