### ISSUE TITLE
How I can custom image download accept

### ISSUE THREAD

**Issue by Ryan0520** [SDWebImage/SDWebImage#2721]
How do I customize the request header for the image download to the `accept` property? Since some files uploaded to our server image did not specify a suffix name, the image could not be downloaded if Accept is set to `image/*`, and the server reported 406 errors. If Accept is set to `*/*`, the image can be downloaded normally. I saw the source code `accept` is set to`image/*`. Can I customize this parameter?

**Comment by kinarob** [comment]
See if this can help you：
```
[imageDownloader setValue:@"yourValue" forHTTPHeaderField:@"Accept"];
```

**Comment by Ryan0520** [comment]
thanks, it work

**Comment by dreampiggy** [comment]
And, if you want a per-image-request level config for HTTP headers, consider using the [Request Modifier](https://github.com/SDWebImage/SDWebImage/wiki/How-to-use#use-request-modifier-50) (4.x called Headers Filter)
