### ISSUE TITLE
这张图如何用SD无法加载会变成黑色

### ISSUE THREAD

**Issue by YellBinn** [SDWebImage/SDWebImage#2726]
所有SD的版本
图片地址：http://ptest.xgbuy.cc/201706/20170628100753_9406.png
谷歌浏览器显示正常
SD加载显示失败 plus iOS12会成功 其他大部分都是失败

**Comment by KeymonWong** [comment]
可以哇，6s ios 12 真机，是不是 你姿势不对

**Comment by KeymonWong** [comment]
> 所有SD的版本
> 图片地址：http://ptest.xgbuy.cc/201706/20170628100753_9406.png
> 谷歌浏览器显示正常
> SD加载显示失败 plus iOS12会成功 其他大部分都是失败

可以哇，6s ios 12 真机，是不是 你姿势不对

**Comment by YellBinn** [comment]
旧系统都不行啊 你再试试？iOS9 iOS10 都不行

**Comment by YellBinn** [comment]
貌似是系统的问题 旧版的系统都无法渲染
旧版系统的微信，QQ 各种都显示不了
这边有方法吗？
