### ISSUE TITLE
SDAnimatedImageView 崩溃

### ISSUE THREAD

**Issue by z624821876** [SDWebImage/SDWebImage#2727]
SDAnimatedImageView 如果使用 `- (instancetype)initWithImage:(UIImage *)image` 初始化会导致程序崩溃
因为内部调用了父类的`- (instancetype)initWithImage:(UIImage *)image` 初始化方法，然后会触发`- (void)setImage:(UIImage *)image`方法，跳过了`- (void)commonInit`方法的初始化，导致`self.lock`为空，然后引起了崩溃

**Comment by dreampiggy** [comment]
Reproducible. Need a rapid fix for this.

**Comment by dreampiggy** [comment]
You can curretly, use the `-[SDAnimatedImageView init]` and then call `-[SDAnimatedImageView setImage:]` for the same logic to avoid this. Will be fixed in v5.0.3

**Comment by z624821876** [comment]
OK

**Comment by dreampiggy** [comment]
@z624821876 [v5.0.3](https://github.com/SDWebImage/SDWebImage/releases/tag/5.0.3) is released. You can try to upgrade for this issue.
