### ISSUE TITLE
Crash when using 'in memory cache' from swift

### ISSUE THREAD

**Issue by phoney** [SDWebImage/SDWebImage#2731]
version 5.0.3, iOS 12, Xcode 10.2

The following code in my iOS swift project crashes every time

     imageView.sd_setImage(with: url, placeholderImage: nil, options: [.refreshCached], context: [.storeCacheType: SDImageCacheType.memory])

If I replace SDImageCachetype.memory with the number 2 then it doesn't crash.

The crash is on line 294 in SDWebImageManager.m, callStoreCacheProcessForOperation:

        storeCacheType = [context[SDWebImageContextStoreCacheType] integerValue];

When I print the context dictionary it says
(lldb) po context
{
    storeCacheType = "__C.SDImageCacheType";
}
It should say

(lldb) po context
{
    storeCacheType = 2;
}

Also, the type SDWebImageContext isn't available in swift, which may be part of the problem.

2019-05-16 19:07:39.402220-0400 MyApp [67205:1475869] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__SwiftValue integerValue]: unrecognized selector sent to instance 0x600000261ad0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001101036fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010f00aac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000110121ab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000110108443 ___forwarding___ + 1443
	4   CoreFoundation                      0x000000011010a238 _CF_forwarding_prep_0 + 120
	5   SDWebImage                          0x000000010ec23102 -[SDWebImageManager callStoreCacheProcessForOperation:url:options:context:downloadedImage:downloadedData:finished:progress:completed:] + 482
	6   SDWebImage                          0x000000010ec22ca2 __125-[SDWebImageManager callDownloadProcessForOperation:url:options:context:cachedImage:cachedData:cacheType:progress:completed:]_block_invoke + 1298
	7   SDWebImage                          0x000000010ec1e888 __88-[SDWebImageDownloaderOperation callCompletionBlocksWithImage:imageData:error:finished:]_block_invoke.221 + 376
	8   libdispatch.dylib                   0x000000011233bd7f _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x000000011233cdb5 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000011234a080 _dispatch_main_queue_callback_4CF + 1540
	11  CoreFoundation                      0x000000011006a8a9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	12  CoreFoundation                      0x0000000110064f56 __CFRunLoopRun + 2310
	13  CoreFoundation                      0x0000000110064302 CFRunLoopRunSpecific + 626
	14  GraphicsServices                    0x00000001156a22fe GSEventRunModal + 65
	15  UIKitCore                           0x0000000118d16ba2 UIApplicationMain + 140
	16  RehabTracker DEV                    0x000000010ade3cfb main + 75
	17  libdyld.dylib                       0x00000001123b1541 start + 1
	18  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by kinarob** [comment]
@phoney How about use like this?
```
[.storeCacheType: SDImageCacheType.memory.rawValue]
```

**Comment by dreampiggy** [comment]
Similar issue like https://github.com/SDWebImage/SDWebImage/pull/2261#issuecomment-379223946

For Swift value, because the `SDWebImageContext` is declared as `[SDWebImageContextOption : Any]`, so the enum type with raw value does not automatically bridged to Objective-C.

The automatically bridge only works if we declare like `[SDWebImageContextOption : Int]`, but since the context option should hold any value. We can not do that.


Try using `imageView.sd_setImage(with: url, placeholderImage: nil, context: [.storeCacheType : SDImageCacheType.memory.rawValue])`. I can ensure this works.

**Comment by phoney** [comment]
Using .rawValue does work. I guess I'll use that.

Thanks.
