### ISSUE TITLE
carthage build error

### ISSUE THREAD

**Issue by tomatobin** [SDWebImage/SDWebImage#2733]
Skipped building SDWebImage due to the error:
Dependency "SDWebImage" has no shared framework schemes for any of the platforms: iOS

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           ios
 SDWebImage Version     5.0.3
 Integration Method      carthage 
 Xcode Version          Xcode 10 /

**Comment by dreampiggy** [comment]
Carthage version ? I can build it on local and our Travis-CI pipeline.
