### ISSUE TITLE
Feature Request: Supports UIKit for macOS

### ISSUE THREAD

**Issue by dreampiggy** [SDWebImage/SDWebImage#2743]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x]  I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | macOS (UIKit)
 Platform Version        | 10.15.0
 SDWebImage Version      | 5.0.5
 Integration Method      | all
 Xcode Version           | Xcode 11

### Issue Description and Steps

See the documentation: [Creating a Mac Version of Your iPad App](https://developer.apple.com/documentation/uikit/creating_a_mac_version_of_your_ipad_app)

Seems there are a new macro to detect the UIKit for macOS. `TARGET_OS_UIKITFORMAC`. We can use this to the `SD_UIKIT` and fix for platform detection.

Maybe this also need CocoaPods support . But at least, we can support Carthage user first.

**Comment by kinarob** [comment]
Interesting!

**Comment by rjchatfield** [comment]
MD5 is not supported on macOS. I believe it’s still used for hashing URLs to file paths.

**Comment by fishandphil** [comment]
+1

**Comment by dreampiggy** [comment]
Current Status:

+ Build SDWebImage on UIKit for macOS (Catalyst): works with little Xcode build settings changes
+ Run SDWebImage iOS Demo on macOS: Works, but need workaround for UIKit's bug behavior on macOS. See more later
+ Update test case on UIKit for macOS: TODO
+ Update the XCFramework build script of UIKit for macOS: TODO


<img width="1158" alt="Screenshot1" src="https://user-images.githubusercontent.com/6919743/62865961-5bf84800-bd42-11e9-8184-815ab3352825.png">

![WechatIMG82](https://user-images.githubusercontent.com/6919743/62865953-57cc2a80-bd42-11e9-9f67-f4e115cb54f1.jpeg)

**Comment by dreampiggy** [comment]
Current working branch: [project_uikit_macos](https://github.com/dreampiggy/SDWebImage/tree/project_uikit_macos)

**Comment by dreampiggy** [comment]
Catalyst for macOS is supported !

Both the Carthage/SwiftPM, and even CocoaPods (It need you to tweak the code sign issue), support the UIKit for macOS.

You can also use the `SDWebImage XCFramework` build scheme, to build the XCFramework contains all the 8 platforms into one on Xcode 11:

+ iOS
+ iOS Simulator
+ tvOS
+ tvOS Simulator
+ watchOS
+ watchOS Simulator
+ macOS
+ macOS Catalyst
