### ISSUE TITLE
SDWebImage/SDWebImage/SDWebImageDownloader 2.m:50:17: Method definition for 'downloadImageWithURL:completed:' not found

### ISSUE THREAD

**Issue by aynakora** [SDWebImage/SDWebImage#2748]
/Pods/SDWebImage/SDWebImage/SDWebImageDownloader 2.m:50:17: Method definition for 'downloadImageWithURL:completed:' not found

[1]  @implementation SDWebImageDownloader    <--- Method definition for 'downloadImageWithURL:completed:' not found

[2]  - (nullable SDWebImageDownloadToken *)downloadImageWithURL:(nullable NSURL *)url   <------- Method 'downloadImageWithURL:completed:' declared here

                                                 completed:(nullable SDWebImageDownloaderCompletedBlock)completedBlock;

**Comment by dreampiggy** [comment]
What version, please provide the issue template.

**Comment by dreampiggy** [comment]
Do you mean the `-[SDWebImageDownloader downloadImageWithURL:completed:` ?

https://github.com/SDWebImage/SDWebImage/blob/4.4.7/SDWebImage/SDWebImageDownloader.h#L227
https://github.com/SDWebImage/SDWebImage/blob/4.4.7/SDWebImage/SDWebImageDownloader.m#L278-L281

This is a convience method from v4.4.7 or v5.0. And I check it can be built succesfully. Please check your local environment again (Pod cache clean, Xcode clean build). If you still have the problem, you can reply here.
