### ISSUE TITLE
CocoaPods trunk still shows 5.0.4

### ISSUE THREAD

**Issue by deszip** [SDWebImage/SDWebImage#2750]
`pod search SDWebImage` still shows v5.0.4.
Probably you didn't push new podspec to the trunk, or smth wrong with their trunk cache.

**Comment by dreampiggy** [comment]
https://github.com/CocoaPods/Specs/blob/master/Specs/1/1/7/SDWebImage/5.0.6/SDWebImage.podspec.json

Try `pod repo update` and `pod cache clean SDWebImage` ?

**Comment by dreampiggy** [comment]
-> SDWebImage (5.0.6)
   Asynchronous image downloader with cache support with an UIImageView category.
   pod 'SDWebImage', '~> 5.0.6'
   - Homepage: https://github.com/SDWebImage/SDWebImage
   - Source:   https://github.com/SDWebImage/SDWebImage.git
   - Versions: 5.0.6, 5.0.5, 5.0.4, 5.0.3, 5.0.2, 5.0.1, 5.0.0, 5.0.0-beta6, 5.0.0-beta5, 5.0.0-beta4, 5.0.0-beta3,
   5.0.0-beta2, 5.0.0-beta, 4.4.7, 4.4.6, 4.4.5, 4.4.4, 4.4.3, 4.4.2, 4.4.1, 4.4.0, 4.3.3, 4.3.2, 4.3.1, 4.3.0, 4.2.3,
   4.2.2, 4.2.1, 4.2.0, 4.1.2, 4.1.1, 4.1.0, 4.0.0, 4.0.0-beta2, 4.0.0-beta, 3.8.3, 3.8.2, 3.8.1, 3.8.0, 3.7.6, 3.7.5,
   3.7.4, 3.7.3, 3.7.2, 3.7.1, 3.7.0, 3.6, 3.5.4, 3.5.2, 3.5.1, 3.5, 3.4, 3.3, 3.2, 3.1, 3.0, 2.7.4, 2.7, 2.6, 2.5, 2.4
   [master repo]
   - Subspecs:
     - SDWebImage/Core (5.0.6)
     - SDWebImage/MapKit (5.0.6)


I can search the SDWebImage 5.0.6. Maybe it's your enrionment issue. Please check it again.

**Comment by 4dmoonlight** [comment]
5.0.6 in cocoapods loss the SDWebImageContextOriginalStoreCacheType

**Comment by dreampiggy** [comment]
> SDWebImageContextOriginalStoreCacheType

Sorry, this is the new feature in 5.1.0, I'll release today and update all documentation or readme.
