### ISSUE TITLE
Support for "Swift Package Manager"

### ISSUE THREAD

**Issue by OkiRules** [SDWebImage/SDWebImage#2751]
Is support for Xcode 11's "Swift Package Manager" coming?

Thanks

**Comment by dreampiggy** [comment]
This is just the same as the current SwiftPM ? Maybe we can do this soon.

**Comment by OkiRules** [comment]
Yes it is the same thing.

**Comment by dreampiggy** [comment]
This the #2756 is merged. This issue can be closed now. Available in 5.1.0.

**Comment by pavm035** [comment]
@dreampiggy  It seems that xcode unable to find 5.1.0 tag, does it exists? when i looked in github also it does not exist

**Comment by dreampiggy** [comment]
@pavm035 Will be released before Friday. Wait for some small pending MR.

**Comment by pavm035** [comment]
@dreampiggy  Thank you so much

**Comment by dreampiggy** [comment]
@pavm035 [5.1.0 version](https://github.com/SDWebImage/SDWebImage/releases/tag/5.1.0) is released. You can use the version dependency of SDWebImage using SwiftPM. See more in [wiki](https://github.com/SDWebImage/SDWebImage/wiki/Installation-Guide#installation-with-swift-package-manager-xcode-11)

**Comment by pavm035** [comment]
@dreampiggy Thank you so much for your great support, however i discovered later some of other frameworks(pods) depends on SDWebImage via cocoapod and my app depends directly on this, so if we add it as spm will it not have two copies of SDWebImage? or any other suggestions?

**Comment by dreampiggy** [comment]
The pacakage manager is aim to “manage the dependency”. So, if one framework is depended by others, others must upgrade to provide their own SwiftPM support.

This just like CocoaPods and Carthage. SwiftPM looks like another CocoaPods (since it use a DSL to declare source files, but not Carthage which use Xcode project)

Currently, you have to push other framework to support it. If those frameworks are maintained by SDWebImage orgnazation such as Coders. We will release a version later with SwiftPM support.

**Comment by pavm035** [comment]
@dreampiggy Thanks for clarifying yes we have some internal pods which does depend on sdwebimage but right now the would not support SPM due to SPM does not support resource fils for unit testing so until they become available we need to wait

**Comment by dreampiggy** [comment]
@pavm035 It's a little suck that SwiftPM does not support the resource files.

I can try some experiment to see whether it's possible to hack to use like this:

1. A framework use SwiftPM
2. B framework dependeny A, but use Carthage / CocoaPods
3. B use some tricky way, to `link the library` of A. Which may be something about Xcode's build settings of B target

**Comment by pavm035** [comment]
@dreampiggy I was thinking same but not able to make it

**Comment by bmunge** [comment]
SPM now supports resources in Xcode 12/Swift 5.3 toolchain.
