### ISSUE TITLE
Non-public API usage

### ISSUE THREAD

**Issue by andreyoshev** [SDWebImage/SDWebImage#2752]
### New Issue Checklist

* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | watchos
 Platform Version        | 5.0
 SDWebImage Version      | 5.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10
 Repro rate              | all the time (100%)

### Issue Description and Steps

Since the release of watchOS 6 beta, I am receiving an invalid binary message every time I upload my app with the following description:

> ITMS-90338: Non-public API usage - The app contains or inherits from non-public classes in APPNAME: WKInterfaceDevice . If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

It appears that the official docs no longer reference iOS as a supported platform for WKInterfaceDevice.

**Comment by dreampiggy** [comment]
Don't upload ipa using using beta SDK. And this [WKInterfaceDevice](https://developer.apple.com/documentation/watchkit/wkinterfacedevice?language=objc) is still the valid API.

**Comment by andreyoshev** [comment]
@dreampiggy I use Xcode 10.2.1 :) 

<img width="938" alt="Screenshot 2019-06-17 at 17 58 09" src="https://user-images.githubusercontent.com/17673010/59606007-860a0100-9129-11e9-810f-4a6b8172b516.png">

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/59610130-53710000-914b-11e9-98d5-0511dfc43046.png)

Whatever the reason. The API is guranteed to be exist and been public, using Xcode 10. And before the day of WWDC 2019. So we have the good reason to use that.

If you think it's a bug, maybe we can fire Radar or require technical report for this. I don't think there are something we can do for this...
