### ISSUE TITLE
Frequently crashes in version 5.X

### ISSUE THREAD

**Issue by d553296416** [SDWebImage/SDWebImage#2755]
### New Issue Checklist

* [✅] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [✅] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [✅ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        |  12.1
 SDWebImage Version      |  5.0.6
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 10
 Repro rate              | sometimes  
 Repro with our demo prj |  Haven't tried
 Demo project link       |  N/A

### Issue Description and Steps
#5.x版本经常崩溃在这里

<img width="789" alt="image" src="https://user-images.githubusercontent.com/7206557/59347010-30f37700-8d46-11e9-8218-5227294f69b8.png">
<img width="673" alt="image" src="https://user-images.githubusercontent.com/7206557/59347065-51233600-8d46-11e9-9e1d-e2191d339955.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/7206557/59347112-6c8e4100-8d46-11e9-87f2-115d47a9d7f0.png">

**Comment by kinarob** [comment]
Hi @d553296416 ,  Had you use `sd_imageProgress`  for KVO ?  If done, Would you mind describe something that you use `sd_imageProgress`  for KVO ？

**Comment by dreampiggy** [comment]
KVO will triiger your observer in the modification thread, which means there may be some thread safe issue if you're not careful.

Try to follow the ]Wiki's demo usage code](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#image-progress-430), using KVOController and always using `dispatch_main_async` to ensure your UI code exec on main queue.

**Comment by d553296416** [comment]
but I'm not use sd_imageProgress for KVO...

**Comment by d553296416** [comment]
Should sd_setImageWithURL be used in kvo should also use dispatch_main_async to ensure security?

**Comment by dreampiggy** [comment]
This feature is introduced from v4.3.0, and does not change any logic from v4.3.0~v5.0.6. So maybe it's not related to something special on 5.0

Is there any crash log from your crash collect service such as Fabric ? I want to see if these crash happend on some specify iOS frimware or not.

And actually, we can change the behavior , to disable the autogenerate `sd_imageProgress` instance in v5.1.0. If you don't use KVO, we don't create `sd_imageProgress` instance to avoid extra cost.

**Comment by d553296416** [comment]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/7206557/59411161-322baf00-8ded-11e9-8c09-1d26b2797396.png">
这是一些其他的崩溃信息

**Comment by d553296416** [comment]
<img width="876" alt="image" src="https://user-images.githubusercontent.com/7206557/59411492-f6451980-8ded-11e9-9d44-c80c0c0725b2.png">

**Comment by d553296416** [comment]
不知道和webp 解码有没有关系

**Comment by dreampiggy** [comment]
@d553296416 Please symbolicate the crash stack...Giving the address frame seems can not find the reason.

Actually, I want to knwo : If this crash specify on some iOS firmware like iOS 11, iOS 12, and whether it's related to special iOS hardare such like iPhone XS, to find whether it's a Apple SDK bug or something like thread-safe issue on SD.

But since SDWebImage, all the touch to that `sd_imageProgress` happended on main queue (from manager callback), it's strange that there are somethinig can happend.

**Comment by kinarob** [comment]
@d553296416  Maybe like this:


![1560476441139](https://user-images.githubusercontent.com/29303030/59477613-93ed2700-8e88-11e9-9a15-0d3abc2eb489.jpg)

**Comment by d553296416** [comment]
![image](https://user-images.githubusercontent.com/7206557/59662922-85807180-91e0-11e9-9d05-36f637a055fd.png)
是这个嘛。
