### ISSUE TITLE
[Usage] synchronously check if url(s) exist in memory cache

### ISSUE THREAD

**Issue by IljaDaderko** [SDWebImage/SDWebImage#2757]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.0
 SDWebImage Version      | 5.0.6
 Integration Method      |  cocoapods
 Xcode Version           | Xcode 10
 Repro rate              | -
 Repro with our demo prj | -
 Demo project link       | -

### Issue Description and Steps

Using SDWebImage v5 what is the least costly method to check if array of urls exists in memory cache in a synchronous?

While looking through documentation closest thing I found for this use case is [cacheKeyForUrl](https://sdwebimage.github.io/Classes/SDWebImageManager.html#/c:objc(cs)SDWebImageManager(im)cacheKeyForURL:) that I believe can be used in a loop to check each url in the array individually and if one of them does not return a key, we can assume that full array is not in the cache. 

However, what if I only want to check memory, without hitting disk cache?

Perhaps I am missing something, a helper to check if link(s) are in memory?

**Comment by dreampiggy** [comment]
@IljaDaderko If you're careful, there are a new series of method in`SDImageCache` protocol method.
[containsImageForKey:cacheType:completion](https://sdwebimage.github.io/Protocols/SDImageCache.html#/c:objc(pl)SDImageCache(im)containsImageForKey:cacheType:completion:)

And also, there is the exisiting method in `SDImageCache` class, the [imageFromMemoryCacheForKey:](https://sdwebimage.github.io/Classes/SDImageCache.html#/c:objc(cs)SDImageCache(im)imageFromMemoryCacheForKey:). Because for now, the memory cache only contains the image instace. So actually, the `check` is equal to the cost of `query memory`, they're the same design like `NSDictionary.objectForKey:`.

You can use the demo code to check 

```objectivec
NSArray<NSString *> *keys;
[keys enumerateObjectsUsingBlock:^(id  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
    BOOL isInMemoryCache = ([cache imageFromMemoryCacheForKey:key] != nil);
}];
```

**Comment by dreampiggy** [comment]
`cacheKeyForUrl` is in the manager method. It's used to grab the generated cache key for URL during load. Because not always the `URL.absoluteString == cacheKey`.

We supports the pCache Key Filter](https://github.com/SDWebImage/SDWebImage/wiki/How-to-use#using-cache-key-filter) to provide a cutsom key, to help user to provide the high-level fucntion, like CDN lookup (for example, differnt URL www.1.foo.com/1.jpg, www.2.foo.com/1.jpg is 2 CDN image url, they can match to same cache key).

**Comment by IljaDaderko** [comment]
Assuming I don't initially know they key for the url (for example I get array of urls from API response) and want to check if all of them are in cache.

I will need to run a loop that combines `cacheKeyForUrl` and `imageFromMemoryCacheForKey` for example?

1. Get the key
2. Check if it is in memmory

**Comment by IljaDaderko** [comment]
This far this is my attempt (it's within react-native scope hence `RTC` and `resolve / reject`)

```objc
RCT_EXPORT_METHOD(checkCache
                  : (NSArray<NSURL *> *)urls resolver
                  : (RCTPromiseResolveBlock)resolve rejecter
                  : (RCTPromiseRejectBlock)reject) {
  __block BOOL cacheExists = YES;

  @try {
    [urls enumerateObjectsUsingBlock:^(NSURL *_Nonnull obj, NSUInteger idx, BOOL *_Nonnull stop) {
      NSString *key = nil;
      key = [[SDWebImageManager sharedManager] cacheKeyForURL:obj];

      if (key != nil) {
        [[SDImageCache sharedImageCache]
            containsImageForKey:key
                      cacheType:SDImageCacheTypeMemory
                     completion:^(SDImageCacheType containsCacheType) {
                       if (containsCacheType != SDImageCacheTypeMemory) {
                         cacheExists = NO;
                         *stop = YES;
                       }
                     }];
      } else {
        *stop = YES;
      }
    }];
    resolve(@{@"cacheExists" : @(cacheExists)});
  } @catch (NSError *error) {
    reject(@"ASQImage:unknown_error", @"chechCache method failed", error);
  }
}
```

Did I grasp this concept correctly?

**Comment by dreampiggy** [comment]
`[SDImageCache sharedImageCache]`. If you desired to only use `SDImageCache` but not other custom cache implementation. You can directly use the `imageFromMemoryCacheForKey:` API. This don't need a block.

Just for-in loop to call this.

But actually, I don't think this is a good React Native Bridge. Consider the user-side of your bridge API.

I can provide a list of url, but you give me a bool value represent the existing. What to do if I receive a `false` ? I didn't now which cache is missing, which are hit.

A better design of this API, should return a hash object. Like this:

```
[{
   key: "www.foobar.com/1.jpg",
   exist: false
},
{
   key: "www.foobar.com/2.jpg",
   exist: true
},
]
```

Which may be better. Or if you don't care the bridge callback performance (I remember the React Native briding need JavaScriptCore in another thread), you can receive just one URL and callback whether it exists.

**Comment by IljaDaderko** [comment]
Ah, I didn't realise url is the key, thought it was something custom. This makes sense. In terms of the bridge perfromance, it's just an async function on js side and within ObjC we only return it one time after the loop (not on every loop run).

I will indeed implement approach that returns array of keys and exist flags like you suggested 👍 Thank you for explaing all of this!
