### ISSUE TITLE
Memory error in Xcode 11 Analyzer

### ISSUE THREAD

**Issue by Idomo** [SDWebImage/SDWebImage#2759]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 SDWebImage Version      | 5.0.6 & 4.4.7 & 4.4.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11
 Repro rate              | all the time (100%)

### Issue Description and Steps

When running Product > Analyze (Shift + Cmd + B), this error is showen:
![image](https://user-images.githubusercontent.com/26777129/59569488-d8e4a980-9092-11e9-86d2-1b5946b69cd7.png)

**Comment by dreampiggy** [comment]
`Error` ?

**Comment by Idomo** [comment]
@dreampiggy Yes, you can see “memory error” in the attached image.
I’m actually thinking it might be the reason for getting `SIGBART` error in my app that makes it to crash.

**Comment by dreampiggy** [comment]
@Idomo `addEntriesFromDictionary:` This API, can works even if you pass nil. It will creat an empty dictionary instead.

Though this API nullability mark as nonnull, this is the behavior from iOS 4.0~iOS 13.0 Beta.

We can fix this by using a little check code, which may be better. But this `might be the reason for getting SIGABRT error in my app that crashing it` can not happend now.

**Comment by Idomo** [comment]
@dreampiggy Thanks for the explanation :)
Closing here.

**Comment by Idomo** [comment]
@dreampiggy Hi, I've just noticed that there is a new warning for the library:
![image](https://user-images.githubusercontent.com/26777129/59606373-9f0ab600-9119-11e9-9999-11707385720b.png)

Guess this one is pretty important.

**Comment by dreampiggy** [comment]
@Idomo What about the latest release here ? Or using the search function you can see the #2744.

https://github.com/SDWebImage/SDWebImage/releases

**Comment by Idomo** [comment]
@dreampiggy Oh, I’ve actually seen this release, but thought you’ve missed this one (forgot that I’ve tried to use older version to test something).
Thanks!

**Comment by Idomo** [comment]
Hi @dreampiggy, after upgrading to the latest release, I got those warnings:
![image](https://user-images.githubusercontent.com/26777129/59916493-fa91b800-9427-11e9-8314-dc5927cbc0fd.png)

**Comment by dreampiggy** [comment]
4.x version ?

These warning, is the CocoaPods or Carthage ?

And to say, we're not have enough time to maintain the old version. If you have time, please upgrade to v5.x version

**Comment by Idomo** [comment]
@dreampiggy 5.0, Cocoapods

**Comment by dreampiggy** [comment]
@Idomo 5.0 does not have `SDWebImageGIFCoder`. It does only have `SDImageGIFCoder`.

So, try to clean your local cache totally.

```
pod cache clean SDWebImage
rm -rf Pods // Your project's Pods folder
```

**Comment by Idomo** [comment]
@dreampiggy Seems like it solved the issue, thanks!
