### ISSUE TITLE
iOS3 Failed to load webp image

### ISSUE THREAD

**Issue by JohnnyHooo** [SDWebImage/SDWebImage#2765]
Error Domain=SDWebImageErrorDomain Code=2001 "(null)" UserInfo={SDWebImageErrorDownloadStatusCodeKey=405}

**Comment by dreampiggy** [comment]
I use a iOS 13 device and using Xcode 11 to run simulator. Does not face anything. I suggest you to use the latest SDWebImage version and try again ?

And, for issue report, please fill and provide the issue template, or we may not help for this...
