### ISSUE TITLE
[Question] Prevent clearing memory cache when app goes into background

### ISSUE THREAD

**Issue by IljaDaderko** [SDWebImage/SDWebImage#2769]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.0
 SDWebImage Version      | 5.0.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10
 Repro rate              | -
 Repro with our demo prj | -
 Demo project link       | -

### Issue Description and Steps

I implemented following method (react-native) to check if array of URL's is present in memory cache

```objc
RCT_EXPORT_METHOD(checkCache
                  : (NSArray<NSURL *> *)urls resolver
                  : (RCTPromiseResolveBlock)resolve rejecter
                  : (RCTPromiseRejectBlock)reject) {
  __block BOOL cacheExists = YES;

  @try {
    [urls enumerateObjectsUsingBlock:^(NSURL *_Nonnull obj, NSUInteger idx, BOOL *_Nonnull stop) {
      NSString *key = nil;
      key = [[SDWebImageManager sharedManager] cacheKeyForURL:obj];

      if (key != nil) {
        [[SDImageCache sharedImageCache]
            containsImageForKey:key
                      cacheType:SDImageCacheTypeMemory
                     completion:^(SDImageCacheType containsCacheType) {
                       if (containsCacheType != SDImageCacheTypeMemory) {
                         cacheExists = NO;
                         *stop = YES;
                       }
                     }];
      } else {
        *stop = YES;
      }
    }];
    resolve(@{@"cacheExists" : @(cacheExists)});
  } @catch (NSError *error) {
    reject(@"ASQImage:unknown_error", @"chechCache method failed", error);
  }
}
```
While within the app it works as I expected it and I can check efficiently if urls are stored in memory cache.

However when my app goes into background even for short time like 5s and without me doing any other operations, once I come back and check cache again it seems like it was cleared.

I wanted to clarify if this is expected behaviour or if there is a way to prevent it from happening? I doubt iOS is clearing these images from cache so quickly?

For additional context, this is how I save images initially (only via prefetch method)

```objc
RCT_EXPORT_METHOD(prefetch
                  : (NSArray<NSURL *> *)urls resolver
                  : (RCTPromiseResolveBlock)resolve rejecter
                  : (RCTPromiseRejectBlock)reject) {
  @try {
    [[SDWebImagePrefetcher sharedImagePrefetcher]
        prefetchURLs:urls
            progress:nil
           completed:^(NSUInteger noOfFinishedUrls, NSUInteger noOfSkippedUrls) {
             NSNumber *finished = [NSNumber numberWithLong:noOfFinishedUrls];
             NSNumber *skipped = [NSNumber numberWithLong:noOfSkippedUrls];
             resolve(@{@"finished" : finished, @"skipped" : skipped});
           }];
  } @catch (NSError *error) {
    reject(@"ASQImage:unknown_error", @"prefetch method failed", error);
  }
}
```

And these are my only tweaked settings for SDWebImage

```objc
[SDImageCodersManager.sharedManager addCoder:[SDImageWebPCoder sharedCoder]];
SDWebImagePrefetcher.sharedImagePrefetcher.context = @{SDWebImageContextStoreCacheType : @(SDImageCacheTypeMemory)};
```

**Comment by dreampiggy** [comment]
@IljaDaderko Current SDWebImage's logic, have a expire data. But this apply for disk cache only.

See: [shouldRemoveExpiredDataWhenEnterBackground](https://sdwebimage.github.io/Classes/SDImageCacheConfig.html#/c:objc(cs)SDImageCacheConfig(py)shouldRemoveExpiredDataWhenEnterBackground) option.

And the implementation is here: [SDImageCache.m](https://github.com/SDWebImage/SDWebImage/blob/5.0.6/SDWebImage/SDImageCache.m#L529-L538). You can see we did only trigger a disk cache clean.

However, from your description, I guess maybe you're running too much of images in keeping in memory cache, and when entering the background, UIKit will send you a `UIApplicationDidReceiveMemoryWarning` notification.

We have special check for this memory warning notification, to clear the memory cache totally. See [SDMemoryCache.m](https://github.com/SDWebImage/SDWebImage/blob/5.0.6/SDWebImage/SDMemoryCache.m#L73-L76).

If you have time, could you please provide more information, or try to run debug on your environment and see what happend ?

**Comment by IljaDaderko** [comment]
I'm caching relatively big number of images (around 60), but their total in memory cost is roughly 18mb, I don't think this would trigger `UIApplicationDidReceiveMemoryWarning` unless it considers 60 separate images as a big memory usage?

I can test if that notification is received (I believe I just need to add `didReceiveMemoryWarningNotification` to my app delegate?)

**Comment by dreampiggy** [comment]
> but their total in memory cost is roughly 18mb

If you don't realize the bitmap image memory usage, please check [WWDC](https://developer.apple.com/videos/play/wwdc2018/219/) and wikipedia
It does not related to anything about your original compressed format data, whatever JPEG/PNG/WebP, etc.
The fomula is

```
RAM = pixel count (width * height * scale * scale) * bytesPerPixel (4 for RGBA 32bit)
```

So if you display one 2000*2000 pixel image, it will cost 15MB RAM.

> I can test if that notification is received (I believe I just need to add didReceiveMemoryWarningNotification to my app delegate and log something out?)

You'd better test this, to see what make your App receive memory warning.

**Comment by IljaDaderko** [comment]
I implemented it in my app delegate
```objc
-(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
  NSLog(@"MEMORY WARNING");
}
```

When I move my app into the background and open another app like safari for example, I don't see this log in my console, however when I go back into to the app and check cache it seems like it was deleted.

During this whole process I also left memory profiler open to see if memory is de-allocated while I was doing this operation, but it seems like everything is more or less consistent (variance in jumps and lows is me navigating around different screens)

<img width="851" alt="Screenshot 2019-06-25 at 14 58 09" src="https://user-images.githubusercontent.com/3154053/60100523-2a0f3000-975a-11e9-887c-bd6ef8f4cb60.png">

Memory usage also seems fine to where it should not receive a warning (this is in react-native's dev mode, in prod it is around 80 - 90ish mb).

Is there any other check I should perform to see why my `checkCache` method returns `NO` when app goes to background, but works fine while it is active?

**Comment by IljaDaderko** [comment]
I also just simplified my `checkCache` method to use `imageFromMemoryCacheForKey:key` method, but result is the same

```objc
RCT_EXPORT_METHOD(checkCache
                  : (NSArray<NSURL *> *)urls resolver
                  : (RCTPromiseResolveBlock)resolve rejecter
                  : (RCTPromiseRejectBlock)reject) {
  __block BOOL cacheExists = YES;

  @try {
    [urls enumerateObjectsUsingBlock:^(NSURL *_Nonnull url, NSUInteger idx, BOOL *_Nonnull stop) {
      NSString *key = url.absoluteString;
      cacheExists = ([[SDImageCache sharedImageCache] imageFromMemoryCacheForKey:key] != nil);

      if (!cacheExists) {
        *stop = YES;
      }
    }];
    resolve(@{@"cacheExists" : @(cacheExists)});
  } @catch (NSError *error) {
    reject(@"ASQImage:unknown_error", @"chechCache method failed", error);
  }
}
```

**Comment by dreampiggy** [comment]
@IljaDaderko I test the code for current 5.0.6 again. In iPhone X device (iOS 12.2), it will not clean any memory cache when entering the background. Only do this when memory warning.

So, there must be something other cases cause you see the memory cache check failed. Could you plaees, write a full demo, to trigger this issue ?

For example, if you're using React Native, write a simple React Native with your bridge, then try to run it on real device to invesigate the issue.

If we can not reproduce this issue, actually, I can not provide more better help or fix for this. So please spend a little time for providing such as demo.

**Comment by IljaDaderko** [comment]
I've been playing with this for last few days, and came to a conclusion that it must be a memory warning, I can persist some images (surprisingly small amount however in terms of pixels size). So will close the issue. I'm still not sure why I don't see memory warning log when I test this however, I will try with a real device as soon as I have access to one.

If I find anything new or interesting I'll come back here.

Thank you for the time and tips you left here to help me better understand the issue.
