### ISSUE TITLE
Sometimes animated images render erroneous transparent pixels

### ISSUE THREAD

**Issue by krze** [SDWebImage/SDWebImage#2776]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS 
 Platform Version        | 12
 SDWebImage Version      | 5.0.6
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.2
 Repro rate              | 5%
 Repro with our demo prj | n/a
 Demo project link       | n/a

### Issue Description and Steps
Occasionally, some `SDAnimatedImage`s play back with frames that contain missing pixels. These pixels, which should be filled, are instead completely transparent (alpha 100%). This is a clip of the bug observed in our app. The bug is the out-of-place white pixels that appear in one frame:
![ezgif-5-ac3fa74c49fc](https://user-images.githubusercontent.com/10662717/60359083-f4f71d80-99a5-11e9-8f26-49b05bc055eb.gif)

I can tell these pixels are transparent because they will be filled with whatever color the background view is behind the `SDAnimatedImageView`

Unfortunately I do not have reproduction steps. It tends to happen if >1 animated images are being downloaded/rendered at a time. I've only ever seen it happen with WebP's, but I can't be sure it only affects WebP's because it's hard to purposefully cause this bug to happen while debugging.

This seems to affect the image while it's in the memory cache. We have a tap-to-lightbox feature that uses the in-memory image from the cache by fetching it with the key (rather than copying the existing SDAnimatedImage instance). An image that has a frame with missing pixels will show this bug until it's cleared from the in-memory cache and then re-loaded from disk.

This started happening when we updated to SDWebImage 5.0.6 from 4.x

**Comment by dreampiggy** [comment]
Is this WebP images ? Previous there is a bug in SDWebImageWebPcoder 2.1.0 and been fixed.

**Comment by dreampiggy** [comment]
Provide a demo url, or write a demo to let us re-produce this issue.

**Comment by dreampiggy** [comment]
I read again and I found you mentioned WebP...So I just close this issue ?

Another tips: for any extension coder plugin, please submit the issue report in their own repo, but not SDWebImage core repo , to make us easy to find and organize the responsibility to fix.

**Comment by huangboju** [comment]
I faced with the similar problem

**Comment by dreampiggy** [comment]
@huangboju WebP only ? Did you try https://github.com/SDWebImage/SDWebImageWebPCoder/pull/14 and version >= 0.2.1

**Comment by krze** [comment]
I'm using SDWebImageWebPCoder 0.23

**Comment by dreampiggy** [comment]
> I can tell these pixels are transparent because they will be filled with whatever color the background view is behind the SDAnimatedImageView

Please provide the demo WebP. I'll test it on browser.

And we should detect whether this is bug of deocidng part of `SDWebImgaeWebPCoder`, or render logic on `SDAnimatedImageView`. From your description that `. I've only ever seen it happen with WebP's` it's mostly something about WebP anmation decoding.

**Comment by huangboju** [comment]
This is my bug
![xiAo-Ju 2019-07-07 16 40 21 2019-07-10 16_41_13](https://user-images.githubusercontent.com/14818224/60954646-eb6c9e80-a331-11e9-9df5-fe0b864d2023.gif)


You can use those data have a test
http://sns-img-anim-up.xhscdn.com/lv0_ahVgutPDk7f3TcHLIDmjLIrh_gif_w320?imageView2/0/format/webp
http://sns-img-anim-up.xhscdn.com/ltbQN77Dd7kkSr9R4ij_DmqaAZv0_gif_w320?imageView2/0/format/webp
http://sns-img-anim-up.xhscdn.com/lkIECQFVzODA25qlH0kUY2IX_WqN_gif_w320?imageView2/0/format/webp
http://sns-img-anim-up.xhscdn.com/lpSWIQp66rvLKpT-DSw5Qs59BT8c_gif_w568?imageView2/0/format/webp

**Comment by dreampiggy** [comment]
For this : http://sns-img-anim-up.xhscdn.com/lpSWIQp66rvLKpT-DSw5Qs59BT8c_gif_w568?imageView2/0/format/webp

I test on our demo. It shows correctly without any issue.

There must be something about your code config or version.

So, the best way to reproduce this issue, it's to provide a full demo which can trigger this issue.

You should use 

+ SDWebImage version 5.0.6, or master branch
+ SDWebImageWebPCoder 0.2.3, or master branch

to detect whether this issue exist.


Screen record:
[屏幕录制 2019-07-10 下午7.38.25.mov.zip](https://github.com/SDWebImage/SDWebImage/files/3377234/2019-07-10.7.38.25.mov.zip)

**Comment by dreampiggy** [comment]
I think this issue has already been solved by SDWebImageWebPCoder v0.2.0+. If you think this is not fixed, reopen this issue.
