### ISSUE TITLE
Include of non-modular header inside framework module 'SDWebImage':

### ISSUE THREAD

**Issue by TOMZACH** [SDWebImage/SDWebImage#2777]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name         |   ios
 Platform Version     |    12.3.1
 SDWebImage Version   |    5.0.6
 Integration Method   |   cocoapods 
 Xcode Version       |     Xcode 10.2.1 

### Issue Description and Steps
After creating the podfile using “use_frameworks!” and installing pod SDWebImage cleaning and building the project I receive the error 
`Include` of non-modular header inside framework module 'SDWebImage'

I’ve been using SDWebImage on the same project for months without any issue. I’ve tried setting allow non-modular headers to yes in the build settings and installing with non-modular pods but still the issue continues.

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

1) create Podfile

  use_frameworks!
	pod 'SDWebImage’
end

2) Install Pods
3)Clean Build Folder
4) Build Project

**Comment by dreampiggy** [comment]
Duplicated for #
