### ISSUE TITLE
How to get image from disk with swift 5.0

### ISSUE THREAD

**Issue by MrZhou1990** [SDWebImage/SDWebImage#2787]

**Comment by dreampiggy** [comment]
https://github.com/SDWebImage/SDWebImage/wiki/5.0-Migration-guide


https://sdwebimage.github.io/Classes/SDImageCache.html#/c:objc(cs)SDImageCache(im)queryCacheOperationForKey:done:

https://sdwebimage.github.io/Classes/SDImageCache.html#/c:objc(cs)SDImageCache(im)imageFromDiskCacheForKey:

**Comment by MrZhou1990** [comment]
感谢
