### ISSUE TITLE
sd_imageTransition with AutoLayout bug

### ISSUE THREAD

**Issue by 4dmoonlight** [SDWebImage/SDWebImage#2788]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.2
 SDWebImage Version      | 5.0.6
 Integration Method      | cocoapods
 Xcode Version           | 10.2.1
 Repro rate              | all the time (100%)
 Repro with our demo prj | happen with demo
 Demo project link       | no

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

`    self.imageView.sd_imageTransition = SDWebImageTransition.fadeTransition;
    [self.imageView sd_setImageWithURL:self.imageURL placeholderImage:nil options:SDWebImageAvoidDecodeImage completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
        NSLog(@"self.imageView:%@",self.imageView.image);
    }];
`
if using autolayout, the above code will cause the 'self.imageView.image = nil' in completed block

**Comment by dreampiggy** [comment]
> if using autolayout, the above code will cause the 'self.imageView.image = nil' in completed block

It's not a guranteed that your completion is called back with

```
self.imageView = image from block arg 1
```

It's only guranteed that 

```
The block arg of `image` is from download or cache
```

The transition is a animation, which means, the completion block is always called back when download finished, but not `After the animation finished`
