### ISSUE TITLE
[Question] Check if URL array already cached or needs download

### ISSUE THREAD

**Issue by CraftizLtd** [SDWebImage/SDWebImage#2794]
* [ ✅] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ✅] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ✅] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

We are using the amazing `SDWebImage` lib as our app caching mechanism.
Our app has many image assets on a server. When the user opens the app we'll start pre-fetching all the remote assets and cache them locally.
When a user taps on specific content and going into the detail view, before showing him the assets, we want to make sure they are cached locally, and if not request them from the server. Only after the downloaded images, we'll be cached we will show the user the detail screen. Two questions for this section:

- What is the correct way to verify if `URL` is already cached on device?

- For the assets which are not cached locally, Is it possible to bulk-download/cache those `URLs`? Is there a way to have one completion block for the bulk `URL` download request? Can we increase those `URLs` requests to **higher priority**?

Here is a visual demo for the flow we are trying to achieve:
https://imgur.com/HMbhiJi

We tried using:

`let isCached = SDImageCache.shared.diskImageDataExists(withKey: urlString)`
But it always returns false even if assets are cached...
We also tried to use `DispatchGroup` like this:

  ```
let dispatchGroup = DispatchGroup()
       
for imageUrl in imageUrls {
 dispatchGroup.enter()
           
SDWebImageManager.shared.loadImage(with: imageUrl, options: .highPriority,progress: nil) { (image, data, error, cacheType, isFinished, imageUrl) in          
     guard let image = image else {
             dispatchGroup.leave()
             return
         }
      dispatchGroup.leave()
     }
 }
    
dispatchGroup.notify(queue: .main) {
        print("downloaded & cached all assets")
 }
```

Which should download & cache (or return immediately if the image is already cached). Seems to work, BUT when we are going into the detail view, and using the same URLs using the `UIImageView` extensions:

`UIImageView().sd_setImage(with: <URL>, completed: nil)`

You can clearly see that the image is being redownloaded again, altho we use the SAME URL for the image, as we did in `loadImage` function above.

Is this happen on intention? Intuitively I thought that if it's cache image for a given URL, for later user I'd be able to use the same URL to load the image from cache.

**Comment by dreampiggy** [comment]
Cache include memory cache and disk cache. So you need to check both of them.

+ Disk Cache Exisit (no decoding or disk query):
https://sdwebimage.github.io/Classes/SDImageCache.html#/c:objc(cs)SDImageCache(im)diskImageExistsWithKey:completion:
+ Memory Cache Exist (no decoding or disk query):
https://sdwebimage.github.io/Classes/SDImageCache.html#/c:objc(cs)SDImageCache(im)imageFromMemoryCacheForKey:

But actually, I don't think your use case is normal case (especially that `if image is not in cache, I don't let user jump into the dtetail page`. Why not just let them in and automatically download if not cache ?)

**Comment by dreampiggy** [comment]
And, using `Dispatch Group` on SDWebImageManager is not recommaned, until this PR is merged #2702 . Because it's not gurantee in some rare case the `completionBlock` is callback. So your `Dispatch Leave` code may not been called and this will cause a runtime exception from Apple's dispatch logic.

**Comment by dreampiggy** [comment]
+  Can we increase those URLs requests to higher priority?

See Wiki page. You may need:

+ https://sdwebimage.github.io/Enums/SDWebImageOptions.html#/c:@E@SDWebImageOptions@SDWebImageHighPriority

**Comment by CraftizLtd** [comment]
Hey @dreampiggy , thank you for responding. 

- Cache include memory cache and disk cache. So you need to check both of them.

What about using `SDWebImageManager.shared.cacheKey(for: <URL?>)`, can I assume that if it returns nil (no key), for this given URL there is no image both on-disk cache and on RAM cache?

- Why not just let them in and automatically download if not cache ?)

We thought about it a lot actually in terms of product and UX. In our opinion, it's better to show the user that a fetch-process is occurring, instead of pushing him into the detail view, and just randomly showing him fetched assets. In this scenario, he can't know when there are no more assets to fetch, using the Modal-Fetching-Vc, he gets a clear state of what's going on within the app.

- And, using Dispatch Group on SDWebImageManager is not recommended, until this PR is merged #2702 

Interesting. Let's assume we know what URLs needs remote fetch. What would you recommend doing to fetch all of them, and get a completion once they are done? (So we can push the user into the detail view, with the assets already cached)?

- See Wiki page. You may need:

Thank you, used that!

Looking forward,
Again, thank you for this great lib! 🙏

**Comment by dreampiggy** [comment]
> SDWebImageManager.shared.cacheKey(for: <URL?>)

This API, just do a calculation of the input URL and cache key, it does not represent any cache exists about disk or memory. Just a MD5 hash by default. So you can not use this for your propose.

> What would you recommend doing to fetch all of them, and get a completion once they are done
Use [SDWebImagePrefetcher](https://sdwebimage.github.io/Classes/SDWebImagePrefetcher.html#/c:objc(cs)SDWebImagePrefetcher(im)prefetchURLs:progress:completed:). This do the nearlly same as SDWebImageManager. But with a URL list and a token represent this list's loading status. When all the list been either cached or downloaded, you'll receive the completion block.

**Comment by CraftizLtd** [comment]
Awesome! @dreampiggy , Thank you for your help. I tried the following:

```
let highPriorityPrefetcher = SDWebImagePrefetcher()
highPriorityPrefetcher.maxConcurrentPrefetchCount = 4

 highPriorityPrefetcher.prefetchURLs(assetsUrls, progress: { (expectedSize, receivedSize) in
    let progress = CGFloat(expectedSize) / CGFloat(expectedSize)
   print("progress at \(progress)")
}) { (finishedCount, skippedCount) in
   print("finished \(finishedCount)")
   print("skipped \(skippedCount)")
   if skippedCount == 0 {
        print("All assets cached, proceed to detail")
   }
}
```
But nothing happens, I placed breakpoints in both closures, and it's no printing anything no the debugger called. I verified that the URL does exist and responsive.
Any ideas what could be the issue?

**Comment by CraftizLtd** [comment]
Hopefully, If I understood your guidance correctly this will be correct. Here is my thesis:

-  `func isUrlCached(url: URL)` - First, if I understand correctly, calling `cacheKey` shouldn't return nil right? It's simple "cold" conversation from `URL` to `String-Key`? Meaning that when I'll call `PrefetchUrls` or `sd_setImage`, under the hood it'll treat the URL cache-key the same? 

- Also, another point - The reason why I'm not checking also within the RAM cache (`imageFromMemoryCache`), is because I assume that if it's in the Disk Cache and I'm using `sd_setImage`, it'll 100% load the image **(Is this correct?)**. As before I'm going to the Detail screen it's not mandatory that the image will be on the RAM.

- If all URLs are cached, we can safely go straight to the detail screen. The advantage here is that `isUrlCached` is synchronous. Should `isUrlCached` cause a delay or it's immediate?

-  Workaround for high priority requests - I couldn't find a way to increase the  `prefetchURLs` URL priority, so Instead before prefetching the needed uncached-URLs I'm canceling all previous prefetches (`cancelPrefetching`). **Is this correct, or there is a better way?**

Hopefully, you'll approve this. I hope this piece of code could help the rest of the community.
Thank you so much @dreampiggy !

Code:

```
func isUrlCached(url: URL) -> Bool {
guard let cacheKey = SDWebImageManager.shared.cacheKey(for: url)  else { // shouldn't happen in theory?
  return false
}
            
let isCachedOnDisk = SDImageCache.shared.diskImageDataExists(withKey: cacheKey)
return isCachedOnDisk
}
        
let uncachedUrls = assetsUrls.filter { isUrlCached(url: $0) == false }

if uncachedUrls.count == 0 {
   print("Moved to screen with sync")
     proccedToDetailScreen() // All URL cached
     return
 }
        
// ELSE

// Cancel all previous prefetching, workaround for high priority requests?
SDWebImagePrefetcher.shared.cancelPrefetching()
        
// Fetch uncachedu URLs
SDWebImagePrefetcher.shared.prefetchURLs(uncachedUrls, progress: nil) { (finishedCount, skippedCount) in
    if skippedCount == 0 { // everything Cached
           proccedToDetailScreen()
    }
}
```

**Comment by dreampiggy** [comment]
1. Yes. If input arg is no-nill, actually the function return non-nil. But remember SDWebImage's cache system is cutomizable, if you write your own disk cache implementation, you can have your logic. The built-in cache just using MD5, no magic behind code. See here: [SDDiskCache.m](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/SDDiskCache.m#L272-L289)

2. Yes. But query disk cache, and then decode the image data, callback async with your data. All this steps may take 0.1~0.5s (dependends on your iOS device hardware, or concurrent query count). It's ok if you don't care about this.

3. All my previous comment show what's API is sync, what's is async. I can list them again here. But actually, read the docuementation again, so we don't need to repeat again and again.

+ diskImageDataExistsWithKey: Sync
+ imageFromMemoryCacheForKey: Sync
+ imageFromCacheForKey: Sync

4. See docuemntation. You can set the `option` property. Using `.highPriority` is what you need.

**Comment by dreampiggy** [comment]
For prefetcher, you can just create a new instance for your `High priority` usage. It's a normal object which you can create each for each your customization usage.

**Comment by CraftizLtd** [comment]
Awesome. Looks like it's working as expected :) Thank you again. 🙏🙏🙏
