### ISSUE TITLE
Module map file SDWebImage.modulemap not found

### ISSUE THREAD

**Issue by ChristianMoler** [SDWebImage/SDWebImage#2803]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        | 12.0 / 13.0
 SDWebImage Version      | 5.1.0 
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11 / Xcode 10

### Issue Description and Steps

After update to version 5.1.0 can't build project. get error 
<unknown>:0: error: module map file '/Users/user/Code/project/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
mixed obj-c & swift project. 
5.0.6 work fine

**Comment by dreampiggy** [comment]
> Users/user/Code/project/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap

The modulemap is not in this directory, it's in `SDWebImage/WebImage/SDWebImage.modulemap`

Run 

```
pod cache clean SDWebImage
(choose All)
rm -rf Pods
pod install
```

to re-install your CocoaPods's cache of SDWebImage

**Comment by ChristianMoler** [comment]
I'm tried this but didn't help. Downgraded to 5.0.6

**Comment by dreampiggy** [comment]
@ChristianMoler I think it's a bug of CocoaPods ? We does not use any custom modulemap now, the modulemap should be generated by CocoaPods. 

The moduelmap path is not `Pods/Headers/Private'. It's always in `Pods/Target Support Files/SDWebImage/SDWebImage.modulemap`.

You can try to check your local environment. You can check demo like [SDWebImageProgressiveJPEGDemo](https://github.com/SDWebImage/SDWebImageProgressiveJPEGDemo) here does not cause any issue.

**Comment by dreampiggy** [comment]
If you still have issue, you can try to `grep` your total project directory, to find where the `Pods/Headers/Private/SDWebImage.modulemap` this string was referenced.

**Comment by dreampiggy** [comment]
Still not re-produacble. I use a demo that can successfuly find the modulemap when using CocoaPods `use_frameworks!`.

**Comment by ChristianMoler** [comment]
@dreampiggy it's mixed project. Maybe the problem is with the bridge?

**Comment by ChristianMoler** [comment]
> <unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
<unknown>:0: error: module map file '/Users/chris/Code/ok-market-ios/Pods/Headers/Private/SDWebImage/SDWebImage.modulemap' not found
25 errors generated.
<unknown>:0: error: failed to emit precompiled header '/Users/chris/Library/Developer/Xcode/DerivedData/okey-dpnrrlmizyhdayfwsveissmlnkvk/Build/Intermediates.noindex/PrecompiledHeaders/okey-Bridging-Header-swift_J00QSPKQJQW8-clang_PPGN4MIQTV0Y.pch' for bridging header '/Users/chris/Code/ok-market-ios/okey/Infrastructure/okey-Bridging-Header.h'

**Comment by dreampiggy** [comment]
SDK or App ? You can provide more context, more background and usage from you. A reproducable demo is better, so that I can check this issue. If I can not reproduce this issue, I can not provide any help fix :(

**Comment by ArchLL** [comment]
I also encountered this problem。Update from 5.0.1 to 5.9.3.

**Comment by ArchLL** [comment]
I also encountered this problem when I update from 5.0.1 to 5.9.3. @dreampiggy 

I found that after using ʻuse_modular_headers!` in Podfile, `SDWebImage.modulemap` is not generated in `Pods/Headers/Private`. But this file is generated in `Pods/Headers/Public`. 

I think it might be a bug. I tried it many times, and there are no problems with other three-party libraries.

**Comment by dreampiggy** [comment]
Try 

```
pod cache clean SDWebImage -all
rm -rf Pods
pod update
```

To see.

SDWebImage history use `podspec.module_map_file = 'WebImage/SDWebImage.modulemap', but already been reverted. Which will cause issues when using in `use_frameworks!`
