### ISSUE TITLE
crash when load big size Gif

### ISSUE THREAD

**Issue by x1911** [SDWebImage/SDWebImage#2811]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          |  iOS
 Platform Version        | 10.0.0 / 11.2.5
 SDWebImage Version      | 5.1.0 
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.3
 Repro rate              |  100% 

### Issue Description and Steps

if i try to open this GIF image

http://wx1.sinaimg.cn/large/9846815ely1g5wk9dfopog206o03q4r1.gif

it crash the app, it works fine in smulator, but not in real device

all the soluction in wiki i have tried, options: [.lowPriority, .avoidDecodeImage] still crash

any new idear or solution for big size gif file?

Thank you very much

**Comment by dreampiggy** [comment]
Using `SDDAnimatedImageView` for large frame and pixels animated image. The `UIImageView` must always keep all the frame buffer in RAM, which means, if one frame use 500KB (sound small ?), 1000 frame will use 500MB in your RAM.

**Comment by dreampiggy** [comment]
Read more here: [Wiki - Animated Image](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50)

**Comment by x1911** [comment]
thans for the reply,
im using SDAnimatedImageView now, 
it works fine almost all the time,
my code like this, and already put the options

`    
func ZImgWithProgressAndCallback(_ url : String,   
        completion:@escaping (UIImage?) ->Void) {

        self.sd_imageIndicator = SDWebImageProgressIndicator.bar 
        
        self.sd_setImage(with: imageURL, placeholderImage: nil,
            options: [.lowPriority, .avoidDecodeImage]
           
            
        ) { (image, error, cacheType, _) in
            
            
            guard let img = image else{
                ZAlertInfo("image not exist", dismissTime: 2)
                completion(nil)
                return
            }
            
            completion(img)
        }
`

maybe another performace options should add?

**Comment by dreampiggy** [comment]
This `avoidDecodeImage` does no any effect when using `SDAnimatedImage`. It's only options effect the `UIImageView` and `UIAnimatedImage` from UIKit. Which does not do a force decode (which means, UIKit default will do lazy load, which decode the image during Core Animation render, this is on the main queue and main effect frame rate).

It's about the force decode logic. If you don't understand and want to know what's the meaning. See my blog (Chinese only): [DreamPiggy's blog](https://dreampiggy.com/2019/01/18/%E4%B8%BB%E6%B5%81%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD%E5%BA%93%E6%89%80%E4%BD%BF%E7%94%A8%E7%9A%84%E9%A2%84%E8%A7%A3%E7%A0%81%E7%A9%B6%E7%AB%9F%E5%B9%B2%E4%BA%86%E4%BB%80%E4%B9%88/)

**Comment by dreampiggy** [comment]
If you think all the SDWebImage Extension should always bring the `SDAnimatedImage` and other custom class implementation into account. Please leave the comment and use case here, we may consider to add this in the 5.2.0 or later release.

**Comment by x1911** [comment]
in my opinion that may be a good way to aviod the waste of large memory size
maybe developer can better handle by itself to choose which way save those memory
anyways the point is how reduce the crash as many as it can
