### ISSUE TITLE
Support iOS 13 

### ISSUE THREAD

**Issue by pengshengsongcode** [SDWebImage/SDWebImage#2816]
Sometimes the network image does not load, is the SDK required to be upgraded separately?

system version：iOS 13，iOS 13.1

iPhone XS

**Comment by dreampiggy** [comment]
Did you use the latest version ? See: https://github.com/SDWebImage/SDWebImage/releases/tag/5.1.0

And please provide the issue template information for us, like your SDK version, iOS version, SDWebImage version, a re-producable demo is strongly recommended.

**Comment by pengshengsongcode** [comment]
so sorry,I forget it

pod 'SDWebImage', '5.0.6'
pod 'SDWebImageWebPCoder', '0.2.3'

system version：iOS 13，iOS 13.1
iPhone XS
Xcode version：Version 11.0 beta 6 
mac version：10.15 Beta

use in Objective-C

**Comment by pengshengsongcode** [comment]
Did 5.0.6-5.1.0 have code support iOS 13？

**Comment by dreampiggy** [comment]
SDWebImage supports iOS 13 beta. I think your issue about the `Sometimes the network image does not load` is not related to iOS 13. But something your network or server.

Try to use Networking Debug Tool like [Charles](https://www.charlesproxy.com), to capture the HTTP response, and to see what's wrong of this. The decoding part shoudl works as expected.
