### ISSUE TITLE
error in 32-bit device

### ISSUE THREAD

**Issue by plguyim** [SDWebImage/SDWebImage#2817]
when i use 32-bit device or simulator.
options |= SDWebImageScaleDownLargeImages;
BOOL shouldScaleDown = options & SDWebImageScaleDownLargeImages;
The shouldScaleDown always return NO.

**Comment by kinarobin** [comment]
@plguyim Thanks.  Fix with #2819 .

**Comment by dreampiggy** [comment]
@plguyim [5.1.1] patch version released. Please try to upgrade and have a try :)
