### ISSUE TITLE
Save GIF Image ，but it's not animated in os album。

### ISSUE THREAD

**Issue by YueLiXing** [SDWebImage/SDWebImage#2821]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.3.1
 SDWebImage Version      | 5.1.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11 / Xcode 10.3
 Repro rate              | all the time (100%)
 Demo project link       | https://github.com/YueLiXing/SDWebImageTestSaveGif

### Issue Description and Steps

download gif 
http://p5.gexing.com/GSF/biaoqing/20180813/20/4ghr1gkvwhu4e1hhofwi85ywd.jpg@!big.jpg  。
but the image is not animated any more. [demo](https://github.com/YueLiXing/SDWebImageTestSaveGif)

**Comment by dreampiggy** [comment]
PhotosKit API: [creationRequestForAssetFromImage:](https://developer.apple.com/documentation/photokit/phassetchangerequest/1624060-creationrequestforassetfromimage?language=objc)

It does not support any animation.

Instead, you must using the data API: [creationRequestForAssetFromImageAtFileURL:](https://developer.apple.com/documentation/photokit/phassetchangerequest/1624059-creationrequestforassetfromimage).

You can firstly using the encoding API by SDWebImage, save the data buffer to file system, and then use this API to save GIF.

```objective-c
UIImage *image; // This is the `UIAnimatedImage`, which has `images` properties. (you can also use `sd_isAnimated` property)
// For SDAnimatedImage, you can just grab the `animatedImageData` instead of encoding, which is the original GIF data
NSString *fileURL;
NSData *gifData = [image sd_imageDataAsFormat:SDImageFormatGIF];
[gifData writeToURL:fileURL atomically:YES];
PHAssetChangeRequest *request = [creationRequestForAssetFromImageAtFileURL:fileURL];
```

This is the API designed by Apple, we can not provide any further help if you don't use it correctly.

**Comment by dreampiggy** [comment]
I saw your demo using a `SDAnimatedImage`. So just use the following code.

```objective-c
- (void)saveImage:(UIImage<SDAnimatedImage> *)image {
    [PHPhotoLibrary requestAuthorization:^(PHAuthorizationStatus status) {
        if (PHAuthorizationStatusDenied == status || PHAuthorizationStatusAuthorized == status) {
            __block NSString * assetID = nil;
            NSError * error = nil;
            NSData *gifData = [image animatedImageData];
            NSURL *fileURL = [NSURL fileURLWithPath:@"/tmp/a.gif"];
            [gifData writeToURL:fileURL atomically:YES];
            [[PHPhotoLibrary sharedPhotoLibrary] performChangesAndWait:^{
                assetID = [PHAssetChangeRequest creationRequestForAssetFromImageAtFileURL:fileURL].placeholderForCreatedAsset.localIdentifier;
            } error:&error];
            if (error) {
                NSLog(@"%@", error);
                return;
            } else {
                NSLog(@"save success");
            }
        }
    }];
}
```

**Comment by YueLiXing** [comment]
@dreampiggy Thank You !

**Comment by YueLiXing** [comment]
Emmm，I found another bug.. [The demo](https://github.com/YueLiXing/SDWebImageTestSaveGif) has been updated.
![image](https://user-images.githubusercontent.com/9456800/64093270-477bfe00-cd8a-11e9-823f-c3837dc6de56.png)
@dreampiggy

**Comment by dreampiggy** [comment]
What's bug ?

SDAnimatedImage is different from UIAnimatedImage.

Our all the category, without the **Explicit Declaration in Public Docuementation**,  does not provide the compatibility for `SDAnimatedImage`.

You shoudl always check the `@protocol` to use.

**Comment by YueLiXing** [comment]
ok... in my project, there has more than one type image,so i have to this.
还是多谢帅哥指教了。不过我还是觉得子类的新方法和父类的扩展。。应该保持某种关系。。。算了。。[那就这样吧](https://music.163.com/#/song?id=351271&autoplay=true&market=baiduhd)

```
NSData * tempData = nil;
if ([image respondsToSelector:@selector(animatedImageData)]) {
    tempData = [image animatedImageData];
} else {
    tempData = [image sd_imageDataAsFormat:[image sd_imageFormat]];
}
[tempData writeToFile:filePath atomically:YES];
```

**Comment by dreampiggy** [comment]
@YueLiXing See:

> This design is because some property, can not works as you expected (or cause misunderstanding) for the same thing. For example, the encoding. SDAnimatedImage should not re-encoding, you just need to grab the animatedImageData. However, UIAnimatedImage does not have any compressed image format, you need the encoding API. These two can not bridge a common layer without the performance cost.

If you think there is another good idea **Keep the abstract without the performance cost** for this desgin, you can provide a design discusssion in another issue. But this is the current design for SDWebImage 5.1.0...
