### ISSUE TITLE
Cache size and expiration

### ISSUE THREAD

**Issue by jpintor14** [SDWebImage/SDWebImage#2822]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.0 
 SDWebImage Version      | 5.1
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 10.3

### Issue Description and Steps

Are there any limitation about time and size of the default cache?
Where I can find these values?

Thanks a lot in advance.

**Comment by dreampiggy** [comment]
API documentation and the headers' comment show the default value for cache size and expieration.

See: https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDImageCacheConfig.h#L91

**Comment by jpintor14** [comment]
Just what i was looking for, thanks a lot!
