### ISSUE TITLE
Error Domain=SDWebImageErrorDomain Code=1001 "Image data is nil"

### ISSUE THREAD

**Issue by mafangchao** [SDWebImage/SDWebImage#2824]
the imageUrl is 'https://www.cyzone.cn/upload/2019/0902/b0085277de84f5a27b9b54196160bc97.png' 

the code is :
UIImageView *view = [[UIImageView alloc] init];
    [self.view addSubview:view];
    view.frame = CGRectMake(100, 200, 200, 200);
    [view sd_setImageWithURL:[NSURL URLWithString:@"https://www.cyzone.cn/upload/2019/0902/b0085277de84f5a27b9b54196160bc97.png"] completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        NSLog(@"%@",error);
    }];
the error is :
Error Domain=SDWebImageErrorDomain Code=1001 "Image data is nil" UserInfo={NSLocalizedDescription=Image data is nil}

**Comment by dreampiggy** [comment]
This may be some server issue. You can check your HTTP request and response using some network debugger tools like Charles.

**Comment by mafangchao** [comment]
it can load this image with SDWebImage earlier version, and this image url can be used normally on the Safari.

**Comment by mafangchao** [comment]
I found this error "SDWebImageDownloader.m"  line 90 :  - (instancetype)initWithConfig: 
Because you set "User-Agent"  ,cancel is ok 。

**Comment by dreampiggy** [comment]
@mafangchao I don't know what this "earlier version" is. Is the 4.x version ? Or 5.0.x version ?

I remember that 5.1.0 change the default HTTP header. And 4.4.3 change to add the User-Agent filed. All of them are listed in the changelog. You can also check the release page.

https://github.com/SDWebImage/SDWebImage/blob/master/CHANGELOG.md

**Comment by mafangchao** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/15926944/64219354-bb87e480-cef7-11e9-87cd-5d62f3869cca.png">
this version maybe 4.3.0 ,I not sure, I see that "SDWebImageDownloader.m" , This version does not have User-Agent .

**Comment by dreampiggy** [comment]
If you have custom HTTP header, you can change it by using the [SDWebImageDownloader setValue:forHTTPHeaderField:](https://sdwebimage.github.io/Classes/SDWebImageDownloader.html#/c:objc(cs)SDWebImageDownloader(im)setValue:forHTTPHeaderField:)

Any extra question ?

**Comment by mafangchao** [comment]
I got it, thx
