### ISSUE TITLE
Downloader will become serialable on some casee

### ISSUE THREAD

**Issue by crossyoureye** [SDWebImage/SDWebImage#2826]
If the operationQueue is FILO and the number of operation are more then maxConcurrentDownloads，then the downloader will be serialable。

My config is below:

`SDWebImageDownloaderConfig *config = [[SDWebImageDownloaderConfig alloc] init]; 

config.maxConcurrentDownloads = 2; 

config.executionOrder = SDWebImageDownloaderFIFOExecutionOrder; 

SDWebImageDownloader *downLoader = [[SDWebImageDownloader alloc] initWithConfig:config];`

**Comment by dreampiggy** [comment]
Please fill the issue template, or provide the detail information about your use case.

**Comment by crossyoureye** [comment]
If the operationQueue is FILO and the number of operation are more then maxConcurrentDownloads，then the downloader will be serialable。

My config is below:

` SDWebImageDownloaderConfig *config = [[SDWebImageDownloaderConfig alloc] init];
    config.maxConcurrentDownloads = 2;
    config.executionOrder = SDWebImageDownloaderFIFOExecutionOrder;
    SDWebImageDownloader *downLoader = [[SDWebImageDownloader alloc] initWithConfig:config];`

**Comment by dreampiggy** [comment]
We don't have `FILO`, we have only `SDWebImageDownloaderLIFOExecutionOrder` and `SDWebImageDownloaderFIFOExecutionOrder`. Check you code ?

And, if you specify the order`LIFO`, there have no gurantee for the concurrency... Seems current code does not have a and robust complicated dispatch system. This code in changed in 5.3.1 because of #2823 #2852.

Maybe there need a `if self.maxConcurrentOperationCount == 1` check ? Or can we re-write a dispatch system from the scratch (Don't rely on the NSOperation) to solve this problem ?

**Comment by dreampiggy** [comment]
Actually, I can not reproduce this in our Test Cases.

We have a special test case here `test15DownloaderLIFOExecutionOrder`. Which submit the operation in order like this:

// Input order: 1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7 (wait for 7 started and immediately) -> 8 -> 9 -> 10 -> 11 -> 12 -> 13 -> 14
// Expected result: 1 (first one has no dependency) -> 7 -> 14 -> 13 -> 12 -> 11 -> 10 -> 9 -> 8 -> 6 -> 5 -> 4 -> 3 -> 2

If I change the maxConcurrentDownloads to 1, this test passed, the order is `1 -> 7 -> 14 -> 13 -> 12 -> 11 -> 10 -> 9 -> 8 -> 6 -> 5 -> 4 -> 3 -> 2`

![image](https://user-images.githubusercontent.com/6919743/67073370-8985c580-f1b9-11e9-854b-c1d5d62b34dd.png)

If I change the maxConcurrentDownloads to 10 (What you expcted), the order is not that, and also in concurrent, the callback rate is not in average at all (I think, you run that test case by yourself is better)

![image](https://user-images.githubusercontent.com/6919743/67073422-a1f5e000-f1b9-11e9-9629-4f57deed9155.png)

**Comment by dreampiggy** [comment]
I've also add a Log to print the URLSession start and stop notification in this test:

```objective-c
    [[NSNotificationCenter defaultCenter] addObserverForName:SDWebImageDownloadStartNotification object:nil queue:nil usingBlock:^(NSNotification * _Nonnull note) {
        SDWebImageDownloaderOperation *operation = note.object;
        NSURL *url = operation.request.URL;
        NSString *path = url.lastPathComponent;
        printf("URL %s started\n", [path cStringUsingEncoding:NSUTF8StringEncoding]);
    }];
    [[NSNotificationCenter defaultCenter] addObserverForName:SDWebImageDownloadStopNotification object:nil queue:nil usingBlock:^(NSNotification * _Nonnull note) {
        SDWebImageDownloaderOperation *operation = note.object;
        NSURL *url = operation.request.URL;
        NSString *path = url.lastPathComponent;
        printf("URL %s stoped\n", [path cStringUsingEncoding:NSUTF8StringEncoding]);
    }];
```

See the running result, this is not `Serialable`. It's still concurrent. Maybe NSOerationQueue already handle the case then `maxConcurrentOperationCount != 1` and have complicated dependency ?

![image](https://user-images.githubusercontent.com/6919743/67074179-26952e00-f1bb-11e9-882f-0d21f4f816df.png)
