### ISSUE TITLE
Load image from url without extension swift 4.1

### ISSUE THREAD

**Issue by CNOJAME** [SDWebImage/SDWebImage#2828]
How to load image from url without image extension in swift 4.1 ?
Example: https://drive.google.com/open?id=xxxxxxxx

**Comment by dreampiggy** [comment]
[SDWebImageManager. loadImage](https://sdwebimage.github.io/Classes/SDWebImageManager.html#/c:objc(cs)SDWebImageManager(im)loadImageWithURL:options:progress:completed:)
