### ISSUE TITLE
Feature Request: Add support for variable frame delays in GIF

### ISSUE THREAD

**Issue by fightveryexplosion** [SDWebImage/SDWebImage#2836]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Feature Request

Currently, SDAnimatedImage uses (as far as I can see at least) the same frame delay for all the frames in a GIF animation.
I use a lot of GIFs in my project, sometimes with varying frame delays in the same GIF animation. For example, most frames have a 1 second delay, while the last frame might have a 5 second delay for emphasis. Or I might use a couple of 0.2 second delays to make a fade animation inside the GIF, etc.

FLAnimatedImage handled this beautifully by getting the frame delay of each frame and showing it for as long, but SDAnimatedImage seems to not have this feature yet.

I would love to see this implemented in SDAnimatedImage, since I look forward to switching over to the new 5.0.0 version for my project!

**Comment by dreampiggy** [comment]
> Currently, SDAnimatedImage uses (as far as I can see at least) the same frame delay for all the frames in a GIF animation.

This is not true. We use the same standard frame duration as browser do. You can guess what does this method do: [SDImageCoderHelper.h](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDImageCoderHelper.h#L18-L26)

> FLAnimatedImage handled this beautifully by getting the frame delay of each frame and showing it for as long, but SDAnimatedImage seems to not have this feature yet.

SDAnimatedImage do what FLAnimatedImage do less, with more feature powered and more Animated Image Format do.

**Comment by dreampiggy** [comment]
> I would love to see this implemented in SDAnimatedImage, since I look forward to switching over to the new 5.0.0 version for my project!

All the source code is open source. You can learn and see [Wiki](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50) for explaination how it works. It just works as other animated image solution (like YYImage) with bettwe MacOS support, better handle of customization.

**Comment by dreampiggy** [comment]
Since this is already implmeneted from the day one in 5.0.0, I'll close this issue. If you have some other question, you can reopen it again or check the wiki first.
