### ISSUE TITLE
Setting a bundled image on a SDAnimatedImageView

### ISSUE THREAD

**Issue by ddaddy** [SDWebImage/SDWebImage#2839]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.4
 SDWebImage Version      | 5.1.1
 Integration Method      | carthage
 Xcode Version           | Xcode 10
 Repro rate              | all the time (100%)

### Issue Description and Steps

Sometimes I have a situation were I need to load a simple `UIImage` from my app bundle.
There doesn't seem to be an sd method to simply `setImage`. When using the standard `UIImageView` `-setImage:` method it doesn't remove the `UIActivityIndicator` from the view.

I set the image views sd state in `viewDidLoad:`, so if I simply remove the `UIActivityIndicator` from the image view when required, i'm not sure it'll be available to sd later on.

What's the preferred method to simply set a `UIImage` to a `SDAnimatedImageView` and have the sd classes know an image has been loaded?

**Comment by dreampiggy** [comment]
using `sd_imageIndicator` setter with a nil value will remove the indicator. See the documentation

**Comment by dreampiggy** [comment]
Actually...This seems a useless convient method, if we add `sd_setImageWithName:inBundle:`. Because it does not get any benefit from our cache system, loader system, control options, or even decoding part(its decoded by UIKit). If there are available features for you to do the same thing, we recommend that instead(for this is the image indicator, there are already API to controls it)

**Comment by dreampiggy** [comment]
And one tips: `SDAnimatedImage` works for bundle image(not in asset catalog). This is the limit by Apple and we could not do this using Public APIs. And there are no ways to add any Animated Image Format to assets catalog (such as GIF). UIKit always treat it as the static format. So pay attention to this.

**Comment by ddaddy** [comment]
Thanks for the reply. I'm actually using static images, but `SDAnimatedImageView` was the only `UIImageView` subclass I could find o I assumed that was the one to use (And also used in the demo).

I'll have a go with setting `sd_imageIndicator = nil;`.

Sorry for wasting your time, the documentation is huge and I did read through what I could.

**Comment by ddaddy** [comment]
Oh one case I thought of for having a simple `setImage:` method, is it would perform the `sd_imageTransition` when set. Handy for when you have a tableView that mixes images from the web and local.
