### ISSUE TITLE
Configuration for large images - documentation obsolete. 

### ISSUE THREAD

**Issue by fredbombadil** [SDWebImage/SDWebImage#2840]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.0 / 11.0
 SDWebImage Version      | 5.1.1 
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.3
 Repro rate              | all the time (100%)

### Issue Description and Steps

In the documentation, the Common Problems section includes one entitled: 

> Configuration for large images (avoid high memory usage)

And for which 
`SDImageCache.shared().config.shouldDecompressImages = false
SDWebImageDownloader.shared().shouldDecompressImages = false
 `
No longer works. The migration guide (https://sdwebimage.github.io/sdwebimage-50-migration-guide.html) mentions that `SDImageCacheConfig` 

> `shouldDecompressImages` removed. Use `SDImageCacheAvoidDecodeImage` in cache options instead

and for `SDWebImageDownloader` now uses 

> `shouldDecompressImages` removed. Use `SDWebImageDownloaderAvoidDecodeImage` in downloader options instead

But I've tried and failed to get this implemented.

**Comment by dreampiggy** [comment]
Duplicated to #2837 . There are already 5 issues about the same thing.

If you need, I can update a FAQ for this. But remember, this is a trade-off to disable the force decode feature. It will impact your frame rate, with less memory usage (but it's still under control)

### For single image request 

If you want to disable the force decode feature for individual image request, use `SDImageCacheAvoidDecodeImage`:

```objective-c
[sd_setImageWithURL:url1 placeholderImage:nil options:SDImageCacheAvoidDecodeImage];
```

### For central control

If you want to have a global control for this, use [Options Processor]() for this option.

```objectivec
 SDWebImageManager.sharedManager.optionsProcessor = [SDWebImageOptionsProcessor optionsProcessorWithBlock:^SDWebImageOptionsResult * _Nullable(NSURL * _Nullable url, SDWebImageOptions options, SDWebImageContext * _Nullable context) {
     // Global disable force decode feature
     options |= SDWebImageAvoidDecodeImage;
 
     return [[SDWebImageOptionsResult alloc] initWithOptions:options context:context];
 }];
[sd_setImageWithURL:url1];
```

**Comment by fredbombadil** [comment]
This is on old solution I think, because it doesn't work.  `.sharedManager` has changed to `.shared` and this returns error 

> Use of unresolved identifier 'optionsProcessorWithBlock'

**Comment by dreampiggy** [comment]
@fredbombadil This is Objective-C code, not Swift. The API is `sharedManager`. It's easy for you to translate and use Swift code.
And the `optionsProcessorWithBlock` is always the Public API of [options processor](https://sdwebimage.github.io/Classes/SDWebImageOptionsProcessor.html#/c:objc(cs)SDWebImageOptionsProcessor(cm)optionsProcessorWithBlock:) (which introduced in SDWebImage v5.1.0)

**Comment by seanperez29** [comment]
> Duplicated to #2837 . There are already 5 issues about the same thing.
> 
> If you need, I can update a FAQ for this. But remember, this is a trade-off to disable the force decode feature. It will impact your frame rate, with less memory usage (but it's still under control)
> 
> ### For single image request
> If you want to disable the force decode feature for individual image request, use `SDImageCacheAvoidDecodeImage`:
> 
> ```objc
> [sd_setImageWithURL:url1 placeholderImage:nil options:SDImageCacheAvoidDecodeImage];
> ```
> 
> ### For central control
> If you want to have a global control for this, use Options Processor for this option.
> 
> ```objc
>  SDWebImageManager.sharedManager.optionsProcessor = [SDWebImageOptionsProcessor optionsProcessorWithBlock:^SDWebImageOptionsResult * _Nullable(NSURL * _Nullable url, SDWebImageOptions options, SDWebImageContext * _Nullable context) {
>      // Global disable force decode feature
>      options |= SDWebImageAvoidDecodeImage;
>  
>      return [[SDWebImageOptionsResult alloc] initWithOptions:options context:context];
>  }];
> [sd_setImageWithURL:url1];
> ```

How is the "For Central Control" option done in Swift? I have attempted to emulate many different ways and just receive errors. Thanks!
