### ISSUE TITLE
How to modify http headers when http url redirect occurs?

### ISSUE THREAD

**Issue by alexykuan** [SDWebImage/SDWebImage#2841]
### New Issue Checklist

* [ yes] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ yes] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ yes] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 12.0
 SDWebImage Version      | 5.0.0
 Integration Method      | cocoapods
 Xcode Version           |  Xcode 11 
 Repro rate              | all the time (100%)

### Issue Description and Steps

Url may redirect to another url and then I have to modify http headers of redirecting. 
eg.  Request with ip and then direct to another host, In case of that, I have to change the `host` http header filed to new host value to support the request. Any solution exist with my case?

**Comment by dreampiggy** [comment]
Using URLSessionDelegate 's method [URLSession:task:willPerformHTTPRedirection:newRequest:completionHandler:](https://developer.apple.com/documentation/foundation/nsurlsessiontaskdelegate/1411626-urlsession?language=objc)

See [wiki here](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-download-operation-40) about how to use custom DownloaderOperation and override the method you need.

By default from Apple's documentation, HTTP 302 redirect is always performed.

**Comment by alexykuan** [comment]
> Using URLSessionDelegate 's method [URLSession:task:willPerformHTTPRedirection:newRequest:completionHandler:](https://developer.apple.com/documentation/foundation/nsurlsessiontaskdelegate/1411626-urlsession?language=objc)
> 
> See [wiki here](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-download-operation-40) about how to use custom DownloaderOperation and override the method you need.
> 
> By default from Apple's documentation, HTTP 302 redirect is always performed.

I didn't see that method `setOperationClass` in class `SDWebImageDownloader` with SDWebImage Version 5.0.0
