### ISSUE TITLE
iOS High Memory Usage / Memory Leaks

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [SDWebImage/SDWebImage#2842]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found one
https://github.com/SDWebImage/SDWebImage/issues/2759
but it does not helped

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13.1
 SDWebImage Version      | 5.1.0
 SDWebImageWebPCoder Version      | 0.2.3
 Integration Method      | automaticly (RN > 0.60, React-Native-Fast-Image)
 Xcode Version           | Xcode 11
 Repro rate              | all the time (100%)
 Repro with our demo prj | Problem was found inside React-Native-Fast-Image which uses your libary

### Issue Description and Steps

When using React-Native-Fast-Image which uses for iPhone SDWebImage, we are displaying around 200 Images. This works very fine when they are PNG (around 400 Ram). But when we switch to webp, it jumps up to 1,9 GB Ram. In Simulator it stops there, and dont go any further (max cap?). When using on a real device ... well it just crashes due to too high memory usage.
Our Workaround at the moment is using PNG, which isnt that good.
The Images arent that big (512x512) but it happens also to thumbnails (128x128).

If there are big mistakes I made please let me now.

Best greets.

**Comment by dreampiggy** [comment]
Maybe it's better to switch the issue to the WebP Coder repo https://github.com/SDWebImage/SDWebImageWebPCoder

But anyway, can you provide a demo to trigger this issue ? So that it's easy to find the reason.

**Comment by dreampiggy** [comment]
I remember, the React-Native-Fast-Image integrate the `SDAnimatedImageView` for backing image rendering. And the WebP does not suppoort by Apple's hardware-accelerated codec, we have to use the WebP Software decoding, which may be slow and performance-costing. Maybe this is the main reason of this.

But a demo can help to find the performance decline point, and maybe we can try to optimize this.

**Comment by dreampiggy** [comment]
@NilsBaumgartner1994 And, did you try https://github.com/SDWebImage/SDWebImageWebPCoder/releases/tag/0.2.4 ? I saw you use the v0.2.3 version. The new version fix one WebP render issue.

**Comment by NilsBaumgartner1994** [comment]
Oh nice for the Information. I will try it out today. Yeah i posted it to SDWebImage, but also wanted to inform you about this issue.
If I dont reply here the error might be fixed.

**Comment by NilsBaumgartner1994** [comment]
Well no: Im testing right now with iPhone 11 Pro Max
in React Native. By Using PNG I the Memory is at: 430MB and with the latest version 0.2.4 the Memory jumps up to 1.74GB.

**Comment by dreampiggy** [comment]
Should be solved by https://github.com/SDWebImage/SDWebImageWebPCoder/issues/29
