### ISSUE TITLE
List of loading images show disorders, other data showed normal cell

### ISSUE THREAD

**Issue by haijiaoliuhao91** [SDWebImage/SDWebImage#2843]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          |  ios 
 Platform Version        | 12.4
 SDWebImage Version    |  5.1.1
 Integration Method      | cocoapods / manually
 Xcode Version           | Xcode 10
 Repro rate              | all the time (100%) 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

List using sd_setImageWithURL loading images show disorders, other data showed normal cell

**Comment by kinarobin** [comment]
Could you describe the issue in more detail ? Or could you provide a demo with this issue ?

**Comment by haijiaoliuhao91** [comment]
when i use the 'sd_setImageWithURL:(nullable NSURL *)url placeholderImage:(nullable UIImage *)placeholder '  method to set image in the collecionView, i found some cell display image disorders, but then  scroll the collectionView the image display normal. the problem only happens in 5.X SDWebImage

**Comment by kinarobin** [comment]
How about upload a demo with this issue?
