### ISSUE TITLE
Feature Request: Suppoerts HEIF Animated Image (heic sequence) introduced on iOS 13

### ISSUE THREAD

**Issue by dreampiggy** [SDWebImage/SDWebImage#2844]
### Feature Request

From iOS 13/macOS 10.15, Image/IO supports the HEIF standard of animation.

See standard here: https://nokiatech.github.io/heif/technical.html

See new API for us which can implements the animation of HEIF:

https://developer.apple.com/documentation/imageio/image_i_o_constants?changes=latest_minor&language=objc

+ [kCGImagePropertyHEICSLoopCount](https://developer.apple.com/documentation/imageio/kcgimagepropertyheicsloopcount?changes=latest_minor&language=objc)
+ [kCGImagePropertyHEICSDelayTime](https://developer.apple.com/documentation/imageio/kcgimagepropertyheicsdelaytime?changes=latest_minor&language=objc)
+ [kCGImagePropertyHEICSUnclampedDelayTime](https://developer.apple.com/documentation/imageio/kcgimagepropertyheicsunclampeddelaytime?changes=latest_minor&language=objc)

This can be implements with single line of code changes, if we can merge that #2678

**Comment by dreampiggy** [comment]
This is one demo HEIF animated image, which can be rendered animated on iOS 13 Safari.

**Comment by adityapatadia** [comment]
> This is one demo HEIF animated image, which can be rendered animated on iOS 13 Safari.
> https://nokiatech.github.io/heif/content/image_sequences/starfield_animation.heic

This does not work on iOS 13 safari. It asks to download the image.

**Comment by dreampiggy** [comment]
@adityapatadia This URL use the `application/octet-steam`. You can just save this into your personal image host and reply the content type `image/heif` instead. It will render as normal.

Or, you can just download and using iOS's preview to lookup it.

**Comment by adityapatadia** [comment]
https://nokiatech.github.io/heif/content/images/ski_jump_1440x960.heic this image responds with correct image type but still can't be rendered in iOS 13.

**Comment by dreampiggy** [comment]
@adityapatadia I've already implements all the code, but this need the pending refactory MR #2846 been merged.

**Comment by dreampiggy** [comment]
> this image responds with correct image type but still can't be rendered in iOS 13.

This can render on iOS 13. What environment are you using ? Image/IO (SDWebImage's built-in coder) can successfully decode this. And it's already one of our demo image.

Run our demo to see the result (clone the repo, run`pod install` and build)

**Comment by adityapatadia** [comment]
Oh, I am talking about iOS 13 Safari.

**Comment by adityapatadia** [comment]
> This is one demo HEIF animated image, which can be rendered animated on iOS 13 Safari.
> https://nokiatech.github.io/heif/content/image_sequences/starfield_animation.heic

You mentioned Safari here so I was testing on that one. Can you render any HEIF image in Safari browser itself?

**Comment by dreampiggy** [comment]
> Can you render any HEIF image in Safari browser itself?

I test again. Safarai (WebKit) can not render HEIF image. But iOS's QLPreviewController can. Which means, the native SDK can render it. Only the Web Broswer can not... 😕 

As a native SDK, since iOS itself can render the HEIF image, so we can support this as well.

**Comment by adityapatadia** [comment]
Yeah, natively it can decode it. Is there any support for fetching HEIF image from web and render it in native app? I mean does the HTTP request has any specific headers which indicates that HEIF is supported?

**Comment by dreampiggy** [comment]
> Is there any support for fetching HEIF image from web and render it in native app?
SDWebImage supports it (with iOS 11+). But only with the static HEIF image. 
If your deployment target is below iOS 11+, you can try [SDWebImageHEIFCoder](https://github.com/SDWebImage/SDWebImageHEIFCoder),which use open-source libheif codec but not Apple's ImageIO.

> I mean does the HTTP request has any specific headers which indicates that HEIF is supported?
Seems the Safari/Chrome does not support HEIF from the scratch, not anything related to server. See: https://caniuse.com/#search=heif

But, if oneday, Safari/Chrome supports the HEIF, maybe you can tell the server you need this format. You can do this by using the same approach like WebP with HTTP Header `Accept: image/heif` (maybe, I guess)

**Comment by adityapatadia** [comment]
It would be great if native libraries added that Accept header. You know, servers could serve image in HEIF format if client says it supports it.

**Comment by dreampiggy** [comment]
@adityapatadia You means, SDWebImage should provide the default HTTP header  ? Current value is `image/*,*/*;q=0.8`.

But...One issue (from my point of view). SDWebImage's support image format is configurable by user. Actually I don't know what the end-developer will choose the format. So we always recommaned the end-developer, to change the default HTTP header...(If they use the `SDWebImageWebPCoder`, they can add `image/webp` into the `Accept` header filed)

**Comment by adityapatadia** [comment]
Okay, understood. Thanks for your quick responses.

**Comment by dreampiggy** [comment]
@adityapatadia I'll add this HTTP header filed configration issue in the [Wiki](https://github.com/SDWebImage/SDWebImage/wiki/How-to-use). Previously this only point out how to config `each individual image request's header`, but we already have one API to change `the default http header applied to all request`.

**Comment by adityapatadia** [comment]
@dreampiggy, could you add the instructions to the wiki?

**Comment by dreampiggy** [comment]
@adityapatadia What kind of instructions of wiki do you need ?

For the custom HTTP request headers, there are already one:
https://github.com/SDWebImage/SDWebImage/wiki/How-to-use#use-request-modifier-50

For the guide how to add coders and coder usage, there are already one:

https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#coder-usage

**Comment by adityapatadia** [comment]
I am talking about wiki for accept header with image/heif value just the way accept header with image/webp is done. If that is added, developers will know that the value can be provided and servers which support it might serve heif image to those users.

**Comment by dreampiggy** [comment]
Maybe I can update one, in the `How-to-use#use-request-modifier-50` page ?

**Comment by dreampiggy** [comment]
@adityapatadia Sorry for delay. I've already add the wiki page about this configuration. See [Wiki - Coder Accept MIME Type](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#coder-accept-mime-type). There are also some changes in wiki which provide a external link to this chapter.

[SDWebImageWebPCoder](https://github.com/SDWebImage/SDWebImageWebPCoder) repo also update readme about the HTTP Accept header modification.

**Comment by dreampiggy** [comment]
Safari and WebKit is adopting adding support for HEIC and HEIC Sequence. See their bugreport: https://bugs.webkit.org/show_bug.cgi?id=197384
See code already merged into WebKit master repo: https://github.com/WebKit/webkit/commit/33f1bc5be369f346c25322ffa47e8c80e4a0629b

Maybe this will be available on iOS 13.x or 14 Safari :)

**Comment by adityapatadia** [comment]
I think the support is only for sequences. It's not clear to me whether the still images are supported.
