### ISSUE TITLE
"CGContextRelease" if in a subthread，Probability triggered crash

### ISSUE THREAD

**Issue by iamlion** [SDWebImage/SDWebImage#2845]
Hi，

I found one possible BUG for iOS system.

If the “CGContextRelease” operation is executed in a sub-thread, there will be a chance of crashing anywhere with touch screen. I want to confirm whether “SDWebImage” is safe in this respect.

```
// test code
- (void)viewWillAppear:(BOOL)animated
{
     [super viewWillAppear:animated];

     dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
           UIGraphicsBeginImageContext(CGSizeMake(200, 200));
           CGContextRef bitmapContextRef = UIGraphicsGetCurrentContext();
           CGContextRelease(bitmapContextRef);
      });
}

// then touch anywhere of screen and have chance to crash
```

**Comment by dreampiggy** [comment]
There already been bug report in Apple's radar about this of iOS 13+. And the `UIImage.drawRect` get effected as well. But this is not related to SDWebImage :)

CGContext method, is documented to be **Thread-Safe**. And for each `UIGraphicsGetCurrentContext `, it will create a **Per-thread-per-context** instance, If it does not, it's Apple's bug and they need to fix it.

![image](https://user-images.githubusercontent.com/6919743/65210217-06475600-dacd-11e9-9df1-047c7c9a4fb2.png)

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/65210452-da78a000-dacd-11e9-8669-d3418bfda190.png)

**Comment by iamlion** [comment]
Thank you very much, I got it.

Our customers found that the application crashed and i can not inexplicable explain, I was so depressed. :(

**Comment by iamlion** [comment]
原来你是个中国人，没仔细留意你的信息😢
