### ISSUE TITLE
NSURLErrorDomain error 406 before it even contacts the server

### ISSUE THREAD

**Issue by mclark4386** [SDWebImage/SDWebImage#285]
I have written a WS and one of the things it provides is avatars(uploading and servering). The only problem is that any time I try to access one with SDWebImage (UIButton+SDWebImage) I get the above error in my completion handler. Complete error is: (Error Domain=NSURLErrorDomain Code=406 "The operation couldn’t be completed. (NSURLErrorDomain error 406.)" ) 
The weird thing about it is that the server isn't ever getting touched (put logging in to verify this)! Any ideas what could be causing this and how to fix it? 

PS If I NSLog the URL and then copy and paste it into a browser it works perfectly, so it's something with SDWebImage or iOS.

**Comment by zapjonny** [comment]
We are seeing the same problem now.

**Comment by zapjonny** [comment]
This website describes a workaround: http://uiroshan.github.io/2015/01/25/sdwebimage-nsurlerrordomain-code-equals-406/

The deal is to call this code before .sd_setImage etc:

```
SDWebImageDownloader.shared().setValue("text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", forHTTPHeaderField: "Accept")
```

Can't tell for sure, but this looks like a bug in SDWebImage? It's kind of weird, because the same code would work for one domain/path, but not another...

**Comment by bpoplauschi** [comment]
It depends on how the server was set-up. I don't think this is a problem with SDWebImage. Why would you suspect that?

**Comment by zapjonny** [comment]
I suspected that too.

But downloading using curl or browsers work. If I change the accept parameter like that (I think Chrome uses that) it works. I don't know where the problem comes from.

**Comment by zapjonny** [comment]
And oh by the way, the first call would render a 406 error, then subsequent calls always -1001 or similar. It's like it caches the error (??) on first attempt after booting app, and does not retry actual network calls from there.

**Comment by bpoplauschi** [comment]
We have an array of failed URLs so we don't keep retrying URLs that failed.
