### ISSUE TITLE
The mobile phone cpu is very high when displaying this picture.

### ISSUE THREAD

**Issue by YotrolZ** [SDWebImage/SDWebImage#2851]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          | ios
 Platform Version       | 13.0
 SDWebImage Version    |  5.1.1
 Integration Method      | manually
 Xcode Version           |  Xcode 11 
 Repro rate              |  all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

The mobile phone cpu is very high when displaying this [picture.](https://i.loli.net/2019/09/24/rX2RkVWeGKIuJvc.jpg)

**Comment by Saberwhy** [comment]
[[UIImage alloc] initWithData:data scale:scale] This method has high CPU utilization

**Comment by dreampiggy** [comment]
> [[UIImage alloc] initWithData:data scale:scale] This method has high CPU utilization

This is UIKit's method and does not related to SDWebImage, actually.

I test this image locally on our demo, it show up just normally without high CPU usage.

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/69945954-9bcb8100-1525-11ea-8929-205659f8ab96.png)
