### ISSUE TITLE
Image are not showing

### ISSUE THREAD

**Issue by mronline** [SDWebImage/SDWebImage#2858]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13.1
 SDWebImage Version      | 5.2.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11
 Repro rate              |
 Repro with our demo prj |
 Demo project link       |

### Issue Description and Steps

It used to work properly. Suddenly, it stopped working. 
It works fine when I try another url. Pictures are housed at Digital Ocean Spaces. (S3 - Public Image)
I can display images with Imageview. But I can't show the pictures with SDWebImage.

When I look at the xCode console, the following error records appear:

```
TLS Client Certificates encountered error
Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://sdwebimage.fra1.digitaloceanspaces.com/killian-pham.jpg, NSErrorFailingURLKey=https://sdwebimage.fra1.digitaloceanspaces.com/killian-pham.jpg, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <79DEDC46-125D-4FF5-8A36-BEB2512AE2C9>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask
Task <5F2F716B-B12A-43F6-AEC0-19434BCD7DE6>.<6> HTTP load failed, 0/0 bytes (error code: -999 [1:89])
```

Sample Image Url:
https://sdwebimage.fra1.digitaloceanspaces.com/killian-pham.jpg

Tryed Another Url Schema:
https://fra1.digitaloceanspaces.com/sdwebimage/killian-pham.jpg

Info.plist:

```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

**Comment by dreampiggy** [comment]
Are you using TLS v1.0 or v1.1 ?  It's formally deprecated in iOS 13 and no longer supported. Try TLS v2.0 above to use.

This nerwork issue actually does nothing with SDWebImage, you can find some common URLSeesion issue in Apple forum.

**Comment by mronline** [comment]
Currently the problem is solved. I don't know how we solved it. I didn't do anything :)
