### ISSUE TITLE
iOS13 Warnings / Compatibility 

### ISSUE THREAD

**Issue by JulzPolz** [SDWebImage/SDWebImage#2859]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13
 SDWebImage Version      | All
 Integration Method      | All
 Xcode Version           | Xcode 11
 Repro rate              | all the time (100%)
 Repro with our demo prj | Yes
 Demo project link       | N.A

### Issue Description and Steps

Warnings are being thrown for iOS13 including...

- `'UIActivityIndicatorViewStyleWhite' is deprecated: first deprecated in iOS 13.0`
- `'CC_MD5' is deprecated: first deprecated in iOS 13.0 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger).`
- `'frameInterval' is deprecated: first deprecated in iOS 10.0 - preferredFramesPerSecond`
- `Implicit conversion loses integer precision: 'UIActivityIndicatorViewStyle' (aka 'enum UIActivityIndicatorViewStyle') to 'int'`

<img width="301" alt="Screenshot 2019-10-01 at 16 21 48" src="https://user-images.githubusercontent.com/153706/65976903-d1da7f00-e468-11e9-804e-0f143d33ca60.png">

**Comment by dreampiggy** [comment]
Known issue. And this does not effect any of usage.

All of the warnings can not been solved by code changes, like that MD5 (we use MD5 for calculate the filename,  this can not been changed, like forever)

If perferred, I'll around the clang diagnostic to ignore those warnings.

**Comment by dreampiggy** [comment]
Did you set deployment target version to iOS 13+ ? This sounds reasonable.
But actually, most of our customer deployment targets is around iOS 9.0~iOS 11.0, so there are less reply from the history. Because that `frameInterval` is already deprecated in iOS 10, but there are no workaround instead of ignore it. (We can not use `preferredFramesPerSecond`, which will double the GIF play rate, because we base on real world time, not your screen refresh time)

**Comment by JulzPolz** [comment]
I think that’s a good idea. I guess if it’s a known warning, which is not possible to remove, then it should be surpressed. It is better that way because it means developers can continue using the kit and see there own new warnings as they write code much easier with a blank warnings list.

**Comment by JulzPolz** [comment]
> Did you set deployment target version to iOS 13+ ? This sounds reasonable.
> But actually, most of our customer deployment targets is around iOS 9.0~iOS 11.0, so there are less reply from the history. Because that `frameInterval` is already deprecated in iOS 10, but there are no workaround instead of ignore it. (We can not use `preferredFramesPerSecond`, which will double the GIF play rate, because we base on real world time, not your screen refresh time)

Fair enough. My only point was to get it to a state where warnings are removed one way or another. It just makes life easier for developers who can build and sport warnings fast with an empty list of warnings.
