### ISSUE TITLE
iOS 8 Crash

### ISSUE THREAD

**Issue by lycan1c** [SDWebImage/SDWebImage#2862]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS
 Platform Version        | 8.0
 SDWebImage Version      |  >= 5.2.0
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 11 
 Repro rate              | all the time (100%) 
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps

dyld: Symbol not found: _kCGImagePropertyAPNGDelayTime
  Referenced from: /private/var/mobile/Containers/Bundle/Application/FCCF8DA5-4B83-4566-9239-8F9CDFFD5B7C/czb.app/Frameworks/SDWebImage.framework/SDWebImage
  Expected in: /System/Library/Frameworks/ImageIO.framework/ImageIO
 in /private/var/mobile/Containers/Bundle/Application/FCCF8DA5-4B83-4566-9239-8F9CDFFD5B7C/czb.app/Frameworks/SDWebImage.framework/SDWebImage

**Comment by dreampiggy** [comment]
Is this related to that #2846 

This code changes: kCGImagePropertyAPNGUnclampedDelayTime ?

**Comment by dreampiggy** [comment]
Maybe a revert quick fix is needed.

**Comment by dreampiggy** [comment]
Should be solved. Please upgrade to [v5.2.3 version](https://github.com/SDWebImage/SDWebImage/releases/tag/5.2.3)
