### ISSUE TITLE
UIImage.scale is not cached properly

### ISSUE THREAD

**Issue by maxchuquimia** [SDWebImage/SDWebImage#2864]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios (I assume it affects all platforms)
 Platform Version        | 13.0 (as above)
 SDWebImage Version      | 5.2.3
 Integration Method      | swift package manage
 Xcode Version           | Xcode 11
 Repro rate              | all the time (100%)
 Repro with our demo prj | did not test
 Demo project link       | see snippets below

### Issue Description and Steps

I created an `SDImageTransformer` that affects the `.scale` of a `UIImage`

```swift
class ScaleFactorImageTransformer: NSObject, SDImageTransformer {

    let scale: CGFloat

    init(scale: CGFloat) {
        self.scale = scale
        super.init()
    }

    var transformerKey: String {
        "ScaleFactorImageTransformer(\(scale))"
    }

    func transformedImage(with image: UIImage, forKey key: String) -> UIImage? {
        if let ciImage = image.ciImage {
            return UIImage(ciImage: ciImage, scale: scale, orientation: image.imageOrientation)
        }
        if let cgImage = image.cgImage {
            return UIImage(cgImage: cgImage, scale: scale, orientation: image.imageOrientation)
        }
        return nil
    }
}
```

I am using an iPhone 11 Pro. The first time `SDWebImageManager.loadImage` is called, the returned image has the applied scaled correctly. However on subsequent runs (presumably when the image is loaded from the cache) the scale of the image is 1.0. The code I am using is (in it's simplest form) :

```swift
let url = URL(string: "https://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/jpeg444.jpg")!

let transformer = ScaleFactorImageTransformer(scale: UIScreen.main.scale)

let context: [SDWebImageContextOption: Any]? = [SDWebImageContextOption.imageTransformer: transformer]
SDWebImageManager.shared.loadImage(with: url, options: [], context: context, progress: nil) {  (image, _, error, cacheType, _, _) in
    if let image = image {
        print("Scale:", image.scale)
    }
}
```

On first run, the console says `Scale: 3.0`. On subsequent runs, it says `Scale: 1.0`. The size of the image incorrectly increases in image views on subsequent runs.

This seems to be related to the closed issue [#1356](https://github.com/SDWebImage/SDWebImage/issues/1356)

**Comment by kinarobin** [comment]
Maybe  you should change the code to :
```ruby
init(scale: CGFloat) {
    super.init()
    self.scale = scale
}
```

**Comment by dreampiggy** [comment]
I'll investigate this issue later.

But actually, for your use case (custom image scale factor), you don't need transformer at all. You can just use the `[.imageScaleFactor: 3]` as context option.

See documentation here: https://sdwebimage.github.io/Constants.html#/c:@SDWebImageContextImageScaleFactor

**Comment by dreampiggy** [comment]
Know the issue. If you modify `scale factor` and store the transformed image into disk cache , then retrive from disk cache again. (Not memory cache, memory cache works) The scale factor is loss.

The issue is : `Image Scale Factor` can be been encoded into JPEG/PNG format. This is a extention from Apple, not related to JPEG/PNG format. This is also why you have `+[UIImage imageWithData:scale:]` two arguments, but not only `data` arg.

Since we only store the image data to cache, not any metadata related to it (such as filename, etc), so the scale factor your appied is lost.

Currentlly I have no good idea to fix it from the strtch, but I think it's trival. Because you can always use `.imageScaleFactor` option for this, this logic should not related to image transformer (which forcus on Image Digital Progressing, like scale, rotation, filter)

**Comment by dreampiggy** [comment]
Maybe the main part is that:

**Image Scale Factor** is a user-provided value, not the image itself's property. So you can not expected it to been encoded correctlly. Instead, always pass the correct scale factor value you want, and we'll provided the correct scale factor image as well.

**Comment by maxchuquimia** [comment]
Understood, thank you - didn't know about the `.imageScaleFactor`, that sorts things out well enough :)

**Comment by dreampiggy** [comment]
From v5.4.0, we can cache the imageScale now. But this need some manual steps (not by default, which may override other's cache).

You can touch the `image.sd_extendedObject` with your `@(UIImage.scale)` (convert it to NSNumber), then use that instead.

But still, I don't think scale is a property which related to image itself, it more like a runtime state, which is configurated by user.
