### ISSUE TITLE
install SDWebImage3.x doesn't work

### ISSUE THREAD

**Issue by evil001** [SDWebImage/SDWebImage#288]
install SDWebImage3.x doesn't work and it says 
ndefined symbols for architecture i386:
  "_xmlGetCharEncodingName", referenced from:
      -[ASIWebPageRequest encodingName] in ASIWebPageRequest.o
  "_xmlInitParser", referenced from:
      -[ASIWebPageRequest parseAsHTML] in ASIWebPageRequest.o
  "_htmlReadFile", referenced from:
      -[ASIWebPageRequest parseAsHTML] in ASIWebPageRequest.o
  "_htmlReadMemory", referenced from:
      -[ASIWebPageRequest parseAsHTML] in ASIWebPageRequest.o
  "_xmlFreeDoc", referenced from:
      -[ASIWebPageRequest parseAsHTML] in ASIWebPageRequest.o
      -[ASIWebPageRequest finishedFetchingExternalResources:] in ASIWebPageRequest.o
  "_xmlSaveToFd", referenced from:
      -[ASIWebPageRequest finishedFetchingExternalResources:] in ASIWebPageRequest.o
  "_xmlSaveDoc", referenced from:
      -[ASIWebPageRequest finishedFetchingExternalResources:] in ASIWebPageRequest.o
  "_xmlSaveClose", referenced from:
      -[ASIWebPageRequest finishedFetchingExternalResources:] in ASIWebPageRequest.o
  "_xmlBufferCreate", referenced from:
      -[ASIWebPageRequest finishedFetchingExternalResources:] in ASIWebPageRequest.o
  "_xmlSaveToBuffer", referenced from:
      -[ASIWebPageRequest finishedFetchingExternalResources:] in ASIWebPageRequest.o
  "_xmlBufferFree", referenced from:
      -[ASIWebPageRequest finishedFetchingExternalResources:] in ASIWebPageRequest.o
  "_xmlCleanupParser", referenced from:
      -[ASIWebPageRequest finishedFetchingExternalResources:] in ASIWebPageRequest.o
  "_xmlXPathNewContext", referenced from:
      -[ASIWebPageRequest readResourceURLs] in ASIWebPageRequest.o
      -[ASIWebPageRequest updateResourceURLs] in ASIWebPageRequest.o
  "_xmlXPathEvalExpression", referenced from:
      -[ASIWebPageRequest readResourceURLs] in ASIWebPageRequest.o
      -[ASIWebPageRequest updateResourceURLs] in ASIWebPageRequest.o
  "_xmlXPathFreeContext", referenced from:
      -[ASIWebPageRequest readResourceURLs] in ASIWebPageRequest.o
      -[ASIWebPageRequest updateResourceURLs] in ASIWebPageRequest.o
  "_xmlNodeGetContent", referenced from:
      -[ASIWebPageRequest readResourceURLs] in ASIWebPageRequest.o
      -[ASIWebPageRequest updateResourceURLs] in ASIWebPageRequest.o
  "_xmlGetNoNsProp", referenced from:
      -[ASIWebPageRequest readResourceURLs] in ASIWebPageRequest.o
  "_xmlXPathFreeObject", referenced from:
      -[ASIWebPageRequest readResourceURLs] in ASIWebPageRequest.o
      -[ASIWebPageRequest updateResourceURLs] in ASIWebPageRequest.o
  "_xmlNodeSetContent", referenced from:
      -[ASIWebPageRequest updateResourceURLs] in ASIWebPageRequest.o
  "_xmlFree", referenced from:
      -[ASIWebPageRequest readResourceURLs] in ASIWebPageRequest.o
      -[ASIWebPageRequest updateResourceURLs] in ASIWebPageRequest.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can help me?

**Comment by hemangshah** [comment]
+1

**Comment by mythodeia** [comment]
the error messages are from an old ASIHTTPRequest library
