### ISSUE TITLE
Image with dynamic height

### ISSUE THREAD

**Issue by nicatguliyev** [SDWebImage/SDWebImage#2883]
Hi, I have tableview with imageview in cell. I load images from url with sdwebimage. But image height is not dynamic. How to change imageview height according to image height dimension

**Comment by dreampiggy** [comment]
Setup your cell layout frame, during the completion handler, with the image size (from your use case)

**Comment by hiteshborse12** [comment]
@nicatguliyev  you got any solution?

@nicatguliyev @dreampiggy  after image download cell.setNeedsLayout(), cell.layoutIfNeeded() not working. let me know how to update height constaint after image download .

**Comment by dreampiggy** [comment]
> @nicatguliyev you got any solution?
> 
> @nicatguliyev @dreampiggy after image download cell.setNeedsLayout(), cell.layoutIfNeeded() not working. let me know how to update height constaint after image download .

You can use any UIKit layout code. For example, use Self-Sizing cell, which make you easy to dynamic changing layout. You need trigger Autolayout update after completion block call back.

Or, for non Self-Sizing cell, use estimatedRowHeight and update the actually height when finished loading. However this may not works well like Self-Sizing cell
