### ISSUE TITLE
The operation couldn't be completed. ( SDWebImageErrorDomain error 2002.)

### ISSUE THREAD

**Issue by niralishaha25** [SDWebImage/SDWebImage#2884]
Platform Name           : ios 
 Platform Version        : iOS 13.1.3
 SDWebImage Version      :  5.2.3
 Integration Method     : cocoapods
 Xcode Version          : Xcode 11.1
 Repro rate             : all the time (100%) for few users

<img width="349" alt="Screen Shot 2019-11-05 at 2 05 27 PM" src="https://user-images.githubusercontent.com/25455993/68191343-663e8100-ffd5-11e9-8c76-4ed6a3459ac5.png">

**Comment by dreampiggy** [comment]
This is a notable behavior change in 5.1.0. The error code is that you cancel the image request.

```
    SDWebImageErrorCancelled = 2002, // The image loading operation is cancelled before finished, during either async disk cache query, or waiting before actual network request. For actual network request error, check `NSURLErrorDomain` error domain and code.
```

See more: https://github.com/SDWebImage/SDWebImage/releases/tag/5.1.0

**Comment by dreampiggy** [comment]
If you don't care that user cancel logic, just filter this error code, or you can just filter the `SDWebImageErrorDomain`. Those error codes are mostlly something about your internal usage error, you should not provide a visual UI to end-user.

**Comment by hatjs880328s** [comment]
Use one Imageview instance download more than one image at the same time.....
