### ISSUE TITLE
获取图片下载耗时

### ISSUE THREAD

**Issue by mingios** [SDWebImage/SDWebImage#2891]
怎么能获取一个图片url的下载耗时，比如总时长，DNS解析时长等

**Comment by dreampiggy** [comment]
SDWebImage's default downloader, using NSURLSession. So it's simple.

1. Use NSURLProtocol to create a proxy, and monitor the download speed, DNS speed, etcs.
2. Use [NSURLSessionTaskMetrics](https://developer.apple.com/documentation/foundation/urlsessiontaskmetrics), which is a better API with many details information from URLSession.

**Comment by dreampiggy** [comment]
If you just care about download total time, it's much more simpler, you can use the notification sent by SDWebImage.
+ Start: https://sdwebimage.github.io/Constants.html#/c:@SDWebImageDownloadStartNotification
+ Stop: https://sdwebimage.github.io/Constants.html#/c:@SDWebImageDownloadStopNotification
+ Finished: https://sdwebimage.github.io/Constants.html#/c:@SDWebImageDownloadFinishNotification

**Comment by mingios** [comment]
好的 谢谢
