### ISSUE TITLE
UIImage width and height 0 with sd_setImage(with: URL)

### ISSUE THREAD

**Issue by freddieb** [SDWebImage/SDWebImage#2896]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13.1.3
 SDWebImage Version      | 5.3.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.2.1
 Repro rate              | all the time (100%)

### Issue Description and Steps

The image.size property of all images have size.height=0 and size.width=0. However, cgImage.width has size greater than 0. Also, all images must have some width and height as they are being displayed correctly within the UIImageView.

```swift
profileImageView.sd_setImage(with: URL(string: user.profileImageUrl)) { [weak self] (image, err, cachType, url) in 
            guard let image = image else { return }
            
            let imageSize = image.size
            let height = imageSize.height
            let width = imageSize.width
            
            print("cgImage width: \(image.cgImage?.width)")
            print("image width: \(width)")
            print("image height: \(height)")
}
```

**Comment by dreampiggy** [comment]
If the `UIImage.size` is (0, 0), it should always been marked as failed and report an Error:

https://github.com/SDWebImage/SDWebImage/blob/5.3.1/SDWebImage/Core/SDWebImageDownloaderOperation.m#L466

This `SDWebImageError.badImageData` error.

Can you provide me the demo to re-produce this issue ? Or something URL can trigger this issue. Sounds really strange that one `UIImage` is `CGImage based`, but have different size (0) compared to CGImage's size.

**Comment by freddieb** [comment]
Thanks for the fast reply!

I created an example project to demo the bug, however the bug isn't occurring in the demo despite SDWebImage being used in the exact same way as the project in which it is occurring (as far as I can see).

Are there any other steps you'd suggest I try so that I can debug the issue?

**Comment by freddieb** [comment]
Interestingly, even when instantiating `UIImage` with `UIImage(named: )` and an image from the asset catalog, the size of the `UIImage` instance is `(0,0)`. This makes it unlikely that the issue is due to `SDWebImage`. 

Still very puzzling though.

**Comment by dreampiggy** [comment]
I guess this related to something about debugger issue ? Xcode issue ? Or are you using the vector format image ?

iOS 13 introduced with symbol image, which may not have a intrinsicContentSize (0,0). Because it can scale at anysize.

But SDWebImage Core repo does not load that image, and if it's downloaded by network, I can ensure a `SDWebImageError.badImageData` will report to the user to mark it as failed

**Comment by freddieb** [comment]
Found the issue, it was due to configuration elsewhere. Thanks for the assistance.

**Comment by dreampiggy** [comment]
> Found the issue, it was due to configuration elsewhere. Thanks for the assistance. 

What’s the configuration cause this ? The coders manager register ? Or HTTP header ?

**Comment by freddieb** [comment]
It was a UIImage issue rather than an image with SDWebImage. We had a UIImage extension that was overriding the image size property. 🤦‍♂️

**Comment by dreampiggy** [comment]
> It was a UIImage issue rather than an image with SDWebImage. We had a UIImage extension that was overriding the image size property. 🤦‍♂️

This extention sound crazy...What does that used for ? (Actually, the better idea is to create a new UIImage with same underlaying CGImage, which can be shared across different UIImage instance, no overhead for RAM)
