### ISSUE TITLE
UIButton gif don't show

### ISSUE THREAD

**Issue by relaxfinger** [SDWebImage/SDWebImage#2905]
## Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.2
 SDWebImage Version      | 5.1.1
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 11.2.1
 Repro rate              | all the time (100%)
 Repro with our demo prj | no
 Demo project link       | https://github.com/relaxfinger/SDWebImageDemo.git

### Issue Description and Steps
UIBotton gif on UITableviewCell fails to display after UITableView scrolls

[self.button  sd_setImageWithURL:[NSURL URLWithString:@"https://images.ypcang.com/1575890250112.png"] forState:UIControlStateNormal placeholderImage:YPCImagePlaceHolder];

![Screen Recording 2019-12-10 at 15 16 35](https://user-images.githubusercontent.com/2360840/70505738-b32cee80-1b63-11ea-927d-0f1cc7815e01.gif)

**Comment by dreampiggy** [comment]
Seems you remove the `SDImageGIFCoder` from the coders manager ? This will cause this behavior.

See mroe : https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#gif-coder

**Comment by dreampiggy** [comment]
If you want to ensure only `SDAnimatedImageView` does not using the old UIKit Animated Image (UIAnimatedImage), you can using the options processor to do a filter like this:

```
        SDWebImageManager.shared.optionsProcessor = SDWebImageOptionsProcessor { url, options, context in
            var context = context ?? [:]
            if let _ = context[.animatedImageClass] as? SDAnimatedImageProtocol {
                options.insert(.decodeFirstFrameOnly)
            }
            return SDWebImageOptionsResult(options: options, context: context)
        }
```

**Comment by relaxfinger** [comment]
Thanks very much!  SDWebImage version is 5.1.1, there is not  SDWebImageCodersManager.  gif on button can dislay first, it disappeared after table view scrolled, and  when I  touch down in the button, then move out the button, gif appeard again.

**Comment by dreampiggy** [comment]
> Thanks very much! [[SDImageCodersManager sharedManager] addCoder:[SDImageGIFCoder sharedCoder]]; add this in appdelegate, but the problem as before. gif on button can dislay first, it disappeared after table view scrolled, and when I touch down in the button, then move out, gif appear again.

This is the default behavior of `UIImageView startAnimating` (called, UIKit native animated image).

When then CALayer disable the Core Animation Transaction (`CATransaction.end()`, actually). All the animation will be stopped.

For example, when push/pop the Navigation between two ViewControllers, when you scroll and entering the UITrackingRunLoopMode. The animation will be removed and display the `UIImageView.image` static image only.

These are no good ways to solve this from SDK side. Instead, you can try to use `SDAnimatedImageView` + `UILabel` to re-create your UIButton. `SDAnimatedImageView` does not use Core Animation to drive the animated image, it always rendering the animation even you scroll the list, go into the navigation from different view controllers. Which may solve your problem.

**Comment by relaxfinger** [comment]
thanks very much!
