### ISSUE TITLE
Can not show webp image in iOS12 or lower 

### ISSUE THREAD

**Issue by wanght** [SDWebImage/SDWebImage#2906]
Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        |  12, 11, 10
 SDWebImage Version      | 5.2.3 - 5.4.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11 / Xcode 10

### Issue Description and Steps

the SDWebImageWebPCoder is 0.2.3 - 0.2.5,  in iOS 12.x or lower version, can not show webp image, but the strange thing: when I debug app to those devices using xcode(11/10), it can show webp correctly. and close debug, start-up app directly, it cannot show webp again.
btw, when I use 5.1.0 and webpcoder 0.2.3, everything is fine.

**Comment by dreampiggy** [comment]
Can our demo reproduce this issue ? Use the SDWebImage repo's demo to have a try ?

```
cd SDWebImage
pod install
open SDWebImage.xcworkspace
```

**Comment by dreampiggy** [comment]
Using iPhone Simulator running iOS 12 (without debugger, follows what you says `and close debug, start-up app directly, it cannot show webp again.`), can not reproduce this issue.

Is this issue only re-producable on iOS 12 real device ? (I don't have one, so could you please use our demo and run iOS 12 real device to have a check ?)

**Comment by wanght** [comment]
I tried demo project, it works on 11.x device fine, I can't find the reason, the image display code has no change for a long term, the only changes on my project is I changed BITCODE compile to non-BITECODE

**Comment by dreampiggy** [comment]
>  the only changes on my project is I changed BITCODE compile to non-BITECODE

Does this means, there are something in-compatible issue of libwebp with Bitcode ? I can have a try later.

**Comment by wanght** [comment]
Maybe with non-bitcode, because I used BITCODE compile before, and everything works fine. But recently I use a sxxt library that can't compile with bitcode. so I change my project to non-bitcode mode

**Comment by wanght** [comment]
fixed at 5.4.2, thx

**Comment by wanght** [comment]
Sorry for mistakes, tried on iOS13 is fine, but on iOS12 or lower, it still not fixed yet.

**Comment by dreampiggy** [comment]
Still a strange issue, that I can not reproduce in local environment on iOS 12.

Did you have conditional firmware check code to add the `SDImageWebPCoder` like this ?

```objective-c
if (@available(iOS 13, *)) {
    [SDImageCodersManager.sharedManager addCoder:SDImageWebPCoder.sharedCoder];
}
```

**Comment by wanght** [comment]
其实没有做任何版本的检查，之前在所有iOS平台都是没有问题的，后来因为加了一个不支持bitcode模式的三方库，被迫整个工程都采用非bitcode编译，之后就只有iOS13才能显示webp了，显示相关代码一直都没有动过

**Comment by wanght** [comment]
I upgrade to 5.6.1 and SDWebImageWebPCoder to 0.5.0, tested on SE with iOS 11.2.5, problem fixed, thx!

**Comment by qipei** [comment]
on iOS 12.x  webp image uttype get nil,  imageFormat get -1

- (UIImage *)decodedImageWithData:(NSData *)data options:(nullable SDImageCoderOptions *)options  {
.........
CFStringRef uttype = CGImageSourceGetType(source);
    SDImageFormat imageFormat = [NSData sd_imageFormatFromUTType:uttype];

**Comment by dreampiggy** [comment]
> on iOS 12.x  webp image uttype get nil,  imageFormat get -1
> 
> 
> 
> - (UIImage *)decodedImageWithData:(NSData *)data options:(nullable SDImageCoderOptions *)options  {
> 
> .........
> 
> CFStringRef uttype = CGImageSourceGetType(source);
> 
>     SDImageFormat imageFormat = [NSData sd_imageFormatFromUTType:uttype];

ImageIO does not support WebP before iOS 13, use SDWebImageWebPCoder instead.

The readme and code comment alreay shows you the answer.
