### ISSUE TITLE
Crashed at -[SDMemoryCache commonInit]  on iOS 10.x

### ISSUE THREAD

**Issue by kunwang** [SDWebImage/SDWebImage#2908]
### New Issue Checklist

* [V] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [V] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [V] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found #2881, but that issue does not have enough information. 

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.x
 SDWebImage Version      | 5.4.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10
 Repro rate              |  sometimes 1%
 Repro with our demo prj | no
 Demo project link       | no

### Issue Description and Steps
   Crashed at -[SDMemoryCache commonInit] + 178 on iOS 10.x.
   
<img width="634" alt="fabric" src="https://user-images.githubusercontent.com/5682749/71001023-5c04bc00-2117-11ea-97e3-cca5e3a9b8f8.png">

**Comment by dreampiggy** [comment]
The stack trace seem get lost. Need the full stack trace to invesitigate this issue.

I test it on iOS 10 device seems have no issue, is this a OOM ?

**Comment by kunwang** [comment]
> @kunwang The stack trace seem get lost. Need the full stack trace to invesitigate this issue.
> 
> I test it on iOS 10 device seems have no issue, is this a OOM ?

hi，follow is stack trace detail.
<img width="669" alt="屏幕快照 2019-12-24 下午4 24 51" src="https://user-images.githubusercontent.com/5682749/71403225-0c1f7b00-266a-11ea-8d75-1ffaa35216bd.png">

**Comment by dreampiggy** [comment]
The KVO subclass can not be created ?
Did you use the two-level dynamic framework, which both contains the same SDWebImage code ? This is one case I know that will cause KVO crash...

See more: https://satanwoo.github.io/2017/09/11/KVO-CRASH/

Or, does anything that will cause this strange issue ?

**Comment by kunwang** [comment]
不装了，用中文，之前是好的没有crash，自从更新到 5.2.3 这个版本，就开始crash，然后升级到5.4.0还是crash, 而且只有 ios 10 crash， 没有使用 two-level dynamic framework.  crash 代码如下：
```
_ = SDWebImageManager.shared.imageCache.queryImage(forKey: urlString, options: [], context: nil, completion: { (image, _, _) in
                    if image != nil {
                        self.setImageWithUrlByFadingIn2(url)
                    } else {
                        self.gifMarker?.isHidden = false
                        self.gifLabel?.isHidden = false
                        self.gifActivityIndicator?.isHidden = true
                        completion?()
                    }
                })
```
