### ISSUE TITLE
custom `MyWebImageDownloaderOperation ` is not triggering method for handling Authentication Challenge

### ISSUE THREAD

**Issue by pandey786** [SDWebImage/SDWebImage#2909]
### Issue Description and Steps

I tried this:

```
class MyWebImageDownloaderOperation: SDWebImageDownloaderOperation {
    override func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
        completionHandler(URLSession.AuthChallengeDisposition.useCredential, URLCredential(trust: challenge.protectionSpace.serverTrust!))
    }
}
```
And in AppDelegate
```

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        SDWebImageDownloader.shared().setOperationClass(MyWebImageDownloaderOperation.self)
        return true
}
```
But didReceive method does not call when I use:
`
imageView.sd_setImage(with: imageUrl, placeholderImage: nil, options: SDWebImageOptions.refreshCached, completed: nil)`

**Comment by kinarobin** [comment]
I don't know what SDWebImage version you had used.

In SDWebImage 5.x version, you should like this:
```ruby
[SDWebImageDownloader sharedDownloader].config.operationClass = MyWebImageDownloaderOperation.class;
```
I wish this code can help you!

**Comment by pandey786** [comment]
@kinarobin 
I upgraded to SDWebImage 5.x version, still facing same issue.

Setting up custom operation class - 
`ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
`

This is my Custom Operation class - 

```
@objc public class CustomSDWebImageDownloaderOperation: SDWebImageDownloaderOperation {
    @objc public override func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
        print(challenge)
        print(completionHandler)
    }
}
```

inside `SDWebImageDownloader` i am seeing that my custom class is being assigned to dataOperation,
Still method in custom class not being called, instead, method in `SDWebImageDownloaderOperation` is called.

**Comment by kinarobin** [comment]
I test in Demo project.  It's OK.  You can have a try!

<img width="1566" alt="截屏2019-12-19下午5 36 30" src="https://user-images.githubusercontent.com/29303030/71162391-1adeea00-2286-11ea-83b2-aaf3cdcd0f26.png">

**Comment by dreampiggy** [comment]
@pandey786 Does this issue caused by Objective-C/Swift interoperability ?

For example, could you please, set a debugger point in `method in SDWebImageDownloaderOperation is called.`. Then, type these in lldb debugger window:

```
po SDWebImageDownloader.sharedDownloader.config.operationClass;
```

See whether this operation class is your own `CustomSDWebImageDownloaderOperation` class

**Comment by pandey786** [comment]
Yes, the issues was with Objc/Swift Interoperability.

There is a class and protocol both with the same name `SDWebImageDownloaderOperation `

**Comment by dreampiggy** [comment]
@pandey786 But, the `SDWebImageDownloaderOperation` class conforms to `SDWebImageDownloaderOperationProtocol`. So if you override the method, it should be called ?

Or, does this caused by that `override` keyword ?

**Comment by akshay-kochhar** [comment]
@dreampiggy I am not getting the handler to the downloader operation. Not really sure what's wrong

**Comment by mollywoodnini** [comment]
Took me quite a while to find that.
You have to override the method with `task: URLSessionTask` in it:

```
override func urlSession(_ session: URLSession, task: URLSessionTask, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
    // do your thing
}
```
