### ISSUE TITLE
Insecure Storage: HTTP Response Cache Leak

### ISSUE THREAD

**Issue by gopalchinnadurai** [SDWebImage/SDWebImage#2912]
We have used **SDWebImage 4.4.7** pod file as per our need. Some VAPT points are mentioned in below picture. Kindly help us asap.

**Issue Summary:**
On line 146 of **SDWebImageDownloader.m**, the method createNewSessionWithConfiguration: () performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.The identified method performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.

**Issue Screenshot:**
<img width="503" alt="Screenshot 2019-12-24 at 9 47 33 AM" src="https://user-images.githubusercontent.com/55129685/71393524-ef1b8580-2632-11ea-94d5-ecc30a4b068f.png">

**Comment by dreampiggy** [comment]
Your VAPT report is not smart at all. It does override `URLSession:dataTask:willCacheResponse:completionHandler:` method. See code by yourself.



The `SDWebImageDownloadOperation` handle the completionHandler as well, no leak (In 4.0.0, it leaks , but already been fixed 2 or 3 years agon).

**Comment by dreampiggy** [comment]
And the SDWebImage only, hit this method, when you pass `SDWebImageRefreshCached`, because by default we don't use NSURLCache with `NSURLRequestReloadIgnoringLocalCacheData`.

The HTTP URL response is used to calculate the Cache validation, so it should not call the completion with `nil` but a valid `NSCachedURLResponse`

**Comment by gopalchinnadurai** [comment]
Thanks for ur Support @dreampiggy

**Comment by dreampiggy** [comment]
@gopalchinnadurai Can this VAPT report be generated automatically ? So that this can be a static analysis tool for help for code quality.
