### ISSUE TITLE
SDWebImage图片缓存临界点问题

### ISSUE THREAD

**Issue by ZhangKejun** [SDWebImage/SDWebImage#2913]
场景：
在SD默认的缓存失效后，客户端处于弱网的情况下拉取图片失败；图片显示默认图

问题：
请问SD是否有一种缓存策略，永远不清理近一段时间（比如3天）的图片资源，只清理这段时间以外的资源；这样可以确保我经常使用的图片资源永远不会被清理。

**Comment by dreampiggy** [comment]
I guess you just need `SDImageCacheConfigExpireTypeAccessDate`.

Which use the access date, not the modification date or created date. If the same cache file hit in recent days, it won't been cleared.
