### ISSUE TITLE
How to add Coders with SPM installation?

### ISSUE THREAD

**Issue by kunalverma25** [SDWebImage/SDWebImage#2914]
### New Issue Checklist

* [x ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13
 SDWebImage Version      | Latest
 Integration Method      | SPM
 Xcode Version           | 11
 Repro rate              | all the time (100%) 

### Issue Description and Steps

I have integrated SDWebimage via SPM.
But I am unable to add WebPCoder as it does not have Package support.

Is there any specific steps involved to add Coders if SDWebImage is added through SPM?
Or Coders can be added manually? As there seems to be no info regarding that.

**Comment by kunalverma25** [comment]
@dreampiggy Any options?

**Comment by dreampiggy** [comment]
Not supported yet. Depends : https://github.com/SDWebImage/libwebp-Xcode/pull/3

**Comment by dreampiggy** [comment]
@kunalverma25 Try to use [v0.3.0](https://github.com/SDWebImage/SDWebImageWebPCoder/releases/tag/0.3.0), which support SwiftPM. (The dependency libwebp use the v1.1.0-rc2+)

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/71506194-e210c780-28ba-11ea-882a-5f5ba438b535.png)
