### ISSUE TITLE
crash version 4.3.3

### ISSUE THREAD

**Issue by NickNameWolf** [SDWebImage/SDWebImage#2920]
### New Issue Checklist

- [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
- [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
- [ x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

i found a similar issue , however that issue has closed. And no answer.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |iOS 
 Platform Version        | iOS 10.3.3
 SDWebImage Version      | 4.3.3
 Integration Method      | cocoapods 
 Xcode Version           |  Xcode 11 
 Repro rate              | a liitle

### Issue Description and Steps
i got crash from APPStore of my app. here is the crash log
`1	CoreFoundation0x181646fe0___exceptionPreprocess + 124
2	libobjc.A.dylib0x1800a8538_objc_exception_throw + 56
3	CoreFoundation0x181646f28-[NSException initWithCoder:] + 0

5	libsystem_platform.dylib0x18070530c__sigtramp + 36
6	libsystem_pthread.dylib0x18070b264_pthread_kill + 112
7	libsystem_c.dylib0x1805b59c4_abort + 140
8	libsystem_malloc.dylib0x1806869e8_nanozone_default_reader + 0
9	libsystem_malloc.dylib0x180687c54__nano_malloc_check_clear + 412
10	libsystem_malloc.dylib0x180686c38_nano_malloc + 44
11	libsystem_malloc.dylib0x180675664_malloc_zone_malloc + 172
12	CoreFoundation0x18151d044__CFRuntimeCreateInstance + 336
13	CoreFoundation0x1816063d8___CFStringCreateImmutableFunnel3 + 1948
14	CoreFoundation0x18151e684_CFStringCreateWithBytes + 44
15	CoreFoundation0x181551604_CreateStringFromFileSystemRepresentationByAddingPercentEscapes + 680
16	CoreFoundation0x18161b980__CFURLCreateWithFileSystemRepresentation + 244
19	CoreServicesInternal0x197e18348_URLEnumeratorGetNextURL
20	Foundation0x1820af680-[NSURLDirectoryEnumerator nextObject] + 64
21	CoreFoundation0x18154e610-[NSEnumerator countByEnumeratingWithState:objects:count:] + 60
50	[SDImageCache deleteOldFilesWithCompletionBlock:]_block_invoke (SDImageCache.m:641)`

this crash is very hard to reproduce.  only happen on release environment . i have no idea to resolve this crash . somebody can help me ?

**Comment by YasinTian** [comment]
你的程序有后台任务吗

**Comment by kinarobin** [comment]
Maybe this can help you ：

[https://mp.weixin.qq.com/s/5iq7gmNfiQvfL-sMs7pF_A](https://mp.weixin.qq.com/s/5iq7gmNfiQvfL-sMs7pF_A)

**Comment by NickNameWolf** [comment]
> Maybe this can help you ：
> 
> https://mp.weixin.qq.com/s/5iq7gmNfiQvfL-sMs7pF_A

i had read it . uh , maybe my crash is that case
