### ISSUE TITLE
SDImageCache value for shouldQueryMemoryOnly by options

### ISSUE THREAD

**Issue by 394771176** [SDWebImage/SDWebImage#2925]
#bug in the file SDImageCache,
the method - (nullable NSOperation *)queryCacheOperationForKey:(nullable NSString *)key options:(SDImageCacheOptions)options done:(nullable SDCacheQueryCompletedBlock)doneBlock 

BOOL shouldQueryMemoryOnly = (image && !(options & SDImageCacheQueryDataWhenInMemory));

this line code, has return value for shouldQueryMemoryOnly is not we expect

I think it will be right for BOOL shouldQueryMemoryOnly = (image && (options & SDImageCacheQueryDataWhenInMemory)); 

need delete the '!' in !(options & SDImageCacheQueryDataWhenInMemory).

I want you to make sure for this, and give me a reply,  best wishes for you!

**Comment by 394771176** [comment]
#bug

**Comment by dreampiggy** [comment]
No. This is designed behavior.

If you pass `SDImageCacheQueryDataWhenInMemory`, which means, even we hit the memory cache, we must query disk again. So it's not `shouldQueryMemoryOnly`

The explaination for these 3 combintation mask can be found here:

https://github.com/SDWebImage/SDWebImage/pull/2255#issuecomment-373099564

**Comment by dreampiggy** [comment]
@394771176 If you still find some usage issue, please reopen this.

Currently, since this issue is a designed behavior, I'll close it now.

**Comment by 394771176** [comment]
thanks, I have got it, It's really a question of my understanding.

but, SDWebImageQueryDataWhenInMemory or SDImageCacheQueryDataWhenInMemory doesn't mean what it looks like，
so the enum name maybe not suit.

**Comment by 394771176** [comment]
@dreampiggy

**Comment by dreampiggy** [comment]
Image in memory, does not means image data in memory.

This is the current design concept. If need change, for example, keep image data in memory as well, you need to fire feature request, or proposal to describe your use case, and the use case should be valuable to break the old behavior.
