### ISSUE TITLE
SDWebImage with 5.2 snapshot: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by athreus** [SDWebImage/SDWebImage#2926]
Mac os: 10.15
XCode: 11.3
swift: 5.2 from january 6th (https://swift.org/download/#snapshots)
SDWebImage: 5.4.2

To reproduce:

Create a new iOS project and import the library by using: File->swift packages-Add depedency

Compile:
```
Undefined symbols for architecture x86_64:
  "___isOSVersionAtLeast", referenced from:
      ___71-[SDImageCache storeImage:imageData:forKey:toMemory:toDisk:completion:]_block_invoke in SDWebImage.o
      -[SDImageCache diskImageForKey:data:options:context:] in SDWebImage.o
      ___44+[SDImageCoderHelper colorSpaceGetDeviceRGB]_block_invoke in SDWebImage.o
      +[SDImageHEICCoder initialize] in SDWebImage.o
      +[SDWebImageActivityIndicator(Conveniences) largeIndicator] in SDWebImage.o
      +[SDWebImageActivityIndicator(Conveniences) mediumIndicator] in SDWebImage.o
      -[UIImage(Metadata) sd_imageFormat] in SDWebImage.o
      ...
ld: symbol(s) not found for architecture x86_64
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any idea ? 
Thanks

**Comment by dreampiggy** [comment]
You use thr binary framework compiled with Xcode 11, but your local environment use Xcode 10 for linking. That's the short answer.

Xcode 10 and Xcode 11 built binary is not compatible (source code compatible). If you still don't upgrade to Xcode 11, make sure to compile all the binary with same Xcode version.

Note the deadline of Xcode 11 switch for App Store is Apirl. SDWebImage we will bumped to Xcode 11 minimum requirement at the same time with Apple.

**Comment by dreampiggy** [comment]
If you already use the Xcode version, make sure to clean your build cache data (~/Library/Developer/Xcode/DerrivedData) and recompile.

**Comment by athreus** [comment]
Thanks a lot!
