### ISSUE TITLE
[v 5.5.1] sd_setImage with context compile time error

### ISSUE THREAD

**Issue by ifs-mahmoudargui** [SDWebImage/SDWebImage#2932]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | macos
 Platform Version        | 10.14.6
 SDWebImage Version      | 5.5.1
 Integration Method      | cocoapods
 Xcode Version           | 11.1 (11A1027)
 Repro rate              | 100%

### Issue Description and Steps

Hello,
When I try to set an Image from an URL using the following method:
`  sd_setImage(with: url,
                                                 placeholderImage: nil,
                                                 options: nil,
                                                 context: [.imageThumbnailPixelSize : thumbnailSize])`
                                               
A compile error occurs: `Type 'AnyHashable' has no member 'imageThumbnailPixelSize'`
could you please Help me out on this ?

**Comment by dreampiggy** [comment]
Actually works ? Could you please try to remove your pod cache, and check your Swift version ?

![image](https://user-images.githubusercontent.com/6919743/72767711-e6b56b00-3c2f-11ea-9e5c-8c608ee29942.png)

Or, you can just download this sample project and compared with your local project.

**Comment by dreampiggy** [comment]
[SwiftMacDemo.zip](https://github.com/SDWebImage/SDWebImage/files/4088754/SwiftMacDemo.zip)

**Comment by dreampiggy** [comment]
> options: nil
What's this syntax ? The `options` is a non-optional `OptionSet`, you should pass `[]`...

**Comment by ifs-mahmoudargui** [comment]
I tried : 
```
pod cache clean --all
pod install --repo-update
```
and a clean / Build my project with swift version set as 4.0 / 4.2 and 5
I also removed the `options` arg as it is irrelevant in my use case.
The compile time error remains .

**Comment by dreampiggy** [comment]
> Actually works ? Could you please try to remove your pod cache, or could you please check your Swift version ? The API should generated as `AnyHashable<SDWebImageContextOption: Any>`
> 
> ![image](https://user-images.githubusercontent.com/6919743/72767711-e6b56b00-3c2f-11ea-9e5c-8c608ee29942.png)
> 
> Or, you can just download this sample project and compared with your local project.

This example project build result ?

**Comment by dreampiggy** [comment]
> @ifs-mahmoudargui  [SwiftMacDemo.zip](https://github.com/SDWebImage/SDWebImage/files/4088754/SwiftMacDemo.zip)
> 

This one...

**Comment by ifs-mahmoudargui** [comment]
Yes I actually tried all the steps mentioned above, the demo project build fails with the following error :
<img width="922" alt="Screenshot 2020-01-21 at 14 36 44" src="https://user-images.githubusercontent.com/57709142/72809735-85f05780-3c5c-11ea-9a62-211639aeb012.png">
I even deleted the derived data and did a clean pod install ....

**Comment by dreampiggy** [comment]
I guess this is something issue reated to the toolchain including CocoaPoda and Xcode. Check again:

1. Use `sudo xcode-select -r` to reset your toolchain to /Application/Xcode.app, must use Xcode 10 or 11 above.
2. Uninstall CocoaPods and reinstall, must use CocoaPods 1.5.x+, or latest 1.8.2
3. If this still can not works, try build SDWebImage with xcframework, you can just clone this repo, open SDWebImage.xcodeproj, click SDWebImage XCFramework and Hit run. It will produce a xcframework, drag it to your demo. See manual install in wiki page.
