### ISSUE TITLE
SSL Pinning (TrustKit)

### ISSUE THREAD

**Issue by guidev** [SDWebImage/SDWebImage#2935]
Hello,
is there any way to do add a custom SSL pinning logic? 

For instance, using TrustKit? 
Maybe providing a way to run custom code on the following delegate method?

```
- (void)URLSession:(NSURLSession *)session 
              task:(NSURLSessionTask *)task 
didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge 
 completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler
```

For the time being, I just forked the repo and basically just replaced the code on the previous method, but I'm looking for a better way to do it?

**Comment by dreampiggy** [comment]
Use the custom subclass of SDWebImageDownloaderOpertaion, see wiki https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-download-operation-40

**Comment by guidev** [comment]
Great! Thanks!
