### ISSUE TITLE
Cannot load image and got error

### ISSUE THREAD

**Issue by lpy0809** [SDWebImage/SDWebImage#2939]
I use SDWebImage and cell.Food.sd_setImage(with: URL(string: foodImage[indexPath.row])) to display the images and foodImage array contains the URL. I run it and got another errors below. I have no idea how to fix it and I can't found any errors about that. Does anyone know how to fix it? thanks.

Here is the error: 
Task < D58DD2B3-88A0-4673-BF27-A7AC5A65F3B4>.<3> finished with error - code: -999
...
Task <340CEBFF-ADE8-4C07-851D-0BD1F0159F20>.<8> finished with error - code: -999
Failed to get TCPIOConnection in addInputHandler
Task <5C16CD7B-2234-4BB6-BE2A-0D71ECD35658>.<12> finished with error - code: -999
[] nw_endpoint_flow_attach_protocols_block_invoke [4.1 107.20.173.119:443 in_progress socket-flow(satisfied)] Failed to attach application protocol CFNetworkConnection

**Comment by dreampiggy** [comment]
Seems something related to the network condition ?

Can you reproduce this issue using our demo ? Juse clone and `pod install`, then open to run.

If our example can not reproduce this issue, maybe this is something related to source code configuration ? Or Xcode project configuration ? (like that [NSAppTransportSecurity](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity?language=objc))

**Comment by frankusu** [comment]
are you using use_frameworks! in podfile? Try removing it, or replace with use_modular_headers!
