### ISSUE TITLE
Library not loaded / iOS 13.3.1

### ISSUE THREAD

**Issue by JeromedC34** [SDWebImage/SDWebImage#2940]
### New Issue Checklist

* [ x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13.3.1
 SDWebImage Version      | 5.5.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.3.1
 Repro rate              | all the time (100%)
 Repro with our demo prj | I found one demo project but couldn't compile
 Demo project link       | easy to reproduce (see below)

### Issue Description and Steps

Create a new project / XCode (Single View App)
Close the project in XCode
In terminal:
    pod init
    vi Podfile
    add "pod 'SDWebImage', '~> 5.0'"
    pod install
Open the workspace in XCode
Add "import SDWebImage" in ViewController.swift
Run in simulator (iOS 13.3) and works OK
Run on my iPhone 8 iOS 13.3.1 and gets the error below

dyld: Library not loaded: @rpath/SDWebImage.framework/SDWebImage
  Referenced from: /private/var/containers/Bundle/Application/25D8A34D-BD1E-4315-A979-E9CB3BCA4DE3/testSDWebImage.app/testSDWebImage
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/25D8A34D-BD1E-4315-A979-E9CB3BCA4DE3/testSDWebImage.app/Frameworks/SDWebImage.framework/SDWebImage: code signature invalid for '/private/var/containers/Bundle/Application/25D8A34D-BD1E-4315-A979-E9CB3BCA4DE3/testSDWebImage.app/Frameworks/SDWebImage.framework/SDWebImage'

	/private/var/containers/Bundle/Application/25D8A34D-BD1E-4315-A979-E9CB3BCA4DE3/testSDWebImage.app/Frameworks/SDWebImage.framework/SDWebImage: stat() failed with errno=25
	/private/var/containers/Bundle/Application/25D8A34D-BD1E-4315-A979-E9CB3BCA4DE3/testSDWebImage.app/Frameworks/SDWebImage.framework/SDWebImage: code signature invalid for '/private/var/containers/Bundle/Application/25D8A34D-BD1E-4315-A979-E9CB3BCA4DE3/testSDWebImage.app/Frameworks/SDWebImage.framework/SDWebImage'

	/private/var/containers/Bundle/Application/25D8A34D-BD1E-4315-A979-E9CB3BCA4DE3/testSDWebImage.app/Frameworks/SDWebImage.framework/SDWebImage: stat() failed with errno=1
	/private/var/containers/Bundle/Application/25D8A34D-BD1E-4315-A979-E9CB3BCA4DE3/testSDWebImage.app/Frameworks/SDWebImage.framework/SDWebImage: code signature invalid for '/private/var/containers/Bundle/Application/25D8A34D-BD1E-4315-A979-E9CB3BCA4DE3/testSDWebImage.app/Frameworks/SDWebImage.framework/SDWebImage'

	/private/var/containers/Bundle/Application/25D8A34D-BD1E-4315-A979-E9CB3BCA4DE3/testSDWebImage.app/Frameworks/SDWebImage.framework/SDWebImage: stat() failed with errno=1

**Comment by JeromedC34** [comment]
It seems to be an Apple problem linked to iOS 13.3.1 and free personnal Apple IDs.
You may check:
[https://github.com/Alamofire/Alamofire/issues/3051#issuecomment-580139830](url)
and
[https://stackoverflow.com/questions/60015309/running-ios-apps-causes-runtime-error-for-frameworks-code-signature-invalid](url)
I could fix the problem by using "use_modular_headers!" instead of "use_frameworks!" in my PodFile (not sure if this may lead to other problems).

**Comment by dreampiggy** [comment]
Code sign issue, not related to SDWebImage itself.

For workaround, don't use the dynamic framework, use `modular_heasers` or `static library` both are OK.
