### ISSUE TITLE
App Crash on SDWebImage: -[SDWebImageDownloaderOperation URLSession:task:didCompleteWithError:] + 572

### ISSUE THREAD

**Issue by BaluNaik** [SDWebImage/SDWebImage#2942]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.x and 13.x
 SDWebImage Version      | ~> 5.0
Integration Method      | cocoapods
 Xcode Version           |  Xcode 11
 Repro rate              | sometimes 
 Repro with our demo prj | No
 Demo project link       | -

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

<img width="826" alt="Screen Shot 2020-02-10 at 6 06 25 PM" src="https://user-images.githubusercontent.com/17030110/74157002-eb6aaf00-4c30-11ea-904f-88455ad1c592.png">
<img width="1610" alt="Screen Shot 2020-02-10 at 6 06 03 PM" src="https://user-images.githubusercontent.com/17030110/74157012-f291bd00-4c30-11ea-961d-34eb48fb7bed.png">

**Comment by kinarobin** [comment]
OOM Issue!
