### ISSUE TITLE
Can SDWebImage load Lottie JSON File format animation in AnimationView?

### ISSUE THREAD

**Issue by liudiange** [SDWebImage/SDWebImage#2949]
i hope support json format image
 like lottie ,but lottie in collectionview is caton

**Comment by dreampiggy** [comment]
You can write your coder-plugin to support any format, even MP4 video. See Wiki:

+ https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-coder-420
+ https://github.com/SDWebImage/SDWebImage/wiki/Coder-Plugin-List
+ https://github.com/SDWebImage/SDWebImageVideoCoder/releases

**Comment by liudiange** [comment]
for example :
i can use lottie like this

class HomeCollectionViewCell: UICollectionViewCell {

@IBOutlet weak var animationView: AnimationView!
var model: Model? {
    didSet{
        self.animationView.pause()
        
        let aniamtion = Animation.named("297944810352570808")
        self.animationView.animation = aniamtion
        self.animationView.animationSpeed = 1.0
        self.animationView.loopMode = .loop
        self.animationView.currentFrame = 10
        self.animationView.play()
        
    }
}

override func awakeFromNib() {
    super.awakeFromNib()

}
}
I can not decode json file to image,and god please help me
my Demo is this
https://github.com/liudiange/imageDemo1

**Comment by dreampiggy** [comment]
@liudiange 

And, I've already tell the way to do. You need a custom loader, which implements the logic to `Give a JSON NSData, convert it to a UIImage. If you can not convert it into UIImage, using the custom Animated Image Class`

I don't read Lottie-iOS's API, does this `Animation` is a subclass of `UIImage` ?

```
let animation = Animation.named("297944810352570808")
```

+ If not, you need a wrapper UIImage subclass. Learn it from [FLAnimatedImage plugin](https://github.com/SDWebImage/SDWebImageFLPlugin/blob/master/SDWebImageFLPlugin/Classes/FLAnimatedImageBridge/SDFLAnimatedImage.h), like this pseudocode:

```swift
open class LottieImage : UIImage, SDAnimatedImageProtocol {
    var animation: Animation
    // then all the protocol method you can just return the actual value using Lottie-iOS API
}
```

+ Next, you need to write your wrapper, to support the `sd_setImage` on your custom view, like this pseudocode

```swift
extension AnimationView {

    open func sd_setImage(with url: URL?) {
        self.sd_internalSetImage(with: url, options: [], context: [.animatedImageClass: LottieImage.Self])
    }
}
```

**Comment by liudiange** [comment]
Because I am a Rookie，so I will try it .thank you

**Comment by liudiange** [comment]
and  Animation is not subclass of UIImage, it is created by Lottie. I am a chinese and my english is poor. and you can open my demo and you can understand me.

**Comment by dreampiggy** [comment]
I create a chatroom using Gitter here: 
https://gitter.im/SDWebImage/community

Click to join and let's talk in Chinese about this. Maybe I think what you need is a simple wrapper of Lottie. But I think this is not what SDWebImage suitable to do.

**Comment by dreampiggy** [comment]
The Lottie support plugin get implemented via [SDWebImageLottiePlugin](https://github.com/SDWebImage/SDWebImageLottiePlugin).

This is the initial release state, you can have a try and provide feedback.

**Comment by liudiange** [comment]
ok

**Comment by dreampiggy** [comment]
@liudiange Please see the new comment in Gitter.im

I've update to provide a brand new solution for lottie animation, which rendre lottie animation into bitmap images (but not vector images), suitable for small icons and emoji and have a fast performance.

See: https://github.com/SDWebImage/SDWebImageLottieCoder

Which built on top of [rlottie](https://github.com/Samsung/rlottie)

**Comment by liudiange** [comment]
谢谢




| |
刘殿阁
|
|
邮箱：shaoyeliudiange@163.com
|

签名由 网易邮箱大师 定制

On 03/09/2020 10:08, DreamPiggy wrote:

@liudiange Please see the new comment in Gitter.im

I've update to provide a brand new solution for lottie animation, which rendre lottie animation into bitmap images (but not vector images), suitable for small icons and emoji and have a fast performance.

See: https://github.com/SDWebImage/SDWebImageLottieCoder

Which built on top of rlottie

**Comment by liudiange** [comment]
我为你的严谨精神和追求完美的态度和渊博的知识感到敬佩




| |
刘殿阁
|
|
邮箱：shaoyeliudiange@163.com
|

签名由 网易邮箱大师 定制

On 03/10/2020 12:51, shaoyeliudiange wrote:
谢谢




| |
刘殿阁
|
|
邮箱：shaoyeliudiange@163.com
|

签名由 网易邮箱大师 定制

On 03/09/2020 10:08, DreamPiggy wrote:

@liudiange Please see the new comment in Gitter.im

I've update to provide a brand new solution for lottie animation, which rendre lottie animation into bitmap images (but not vector images), suitable for small icons and emoji and have a fast performance.

See: https://github.com/SDWebImage/SDWebImageLottieCoder

Which built on top of rlottie

**Comment by dreampiggy** [comment]
@liudiange What's the current latest status of that Lottie Coder ? Can that new coder solve the performance issue ?

**Comment by liudiange** [comment]
我现在还没有时间尝试。目前天天在加班！周末我找一个时间试下




| |
刘殿阁
|
|
邮箱：shaoyeliudiange@163.com
|

签名由 网易邮箱大师 定制

On 03/11/2020 13:54, DreamPiggy wrote:

@liudiange What's the current latest status of that Lottie Coder ? Can that new coder solve the performance issue ?

**Comment by liudiange** [comment]
非常感谢，我试了 300k的一点都不卡，如丝柔般顺滑，非常感谢你 非常感谢你！我也不用tg的了 就用你的了 ！哈哈




| |
刘殿阁
|
|
邮箱：shaoyeliudiange@163.com
|

签名由 网易邮箱大师 定制

On 03/11/2020 13:57, shaoyeliudiange wrote:
我现在还没有时间尝试。目前天天在加班！周末我找一个时间试下




| |
刘殿阁
|
|
邮箱：shaoyeliudiange@163.com
|

签名由 网易邮箱大师 定制

On 03/11/2020 13:54, DreamPiggy wrote:

@liudiange What's the current latest status of that Lottie Coder ? Can that new coder solve the performance issue ?

**Comment by liudiange** [comment]
现在除了MJ. 我的心里又多了神。那就是你！再次感谢！




| |
刘殿阁
|
|
邮箱：shaoyeliudiange@163.com
|

签名由 网易邮箱大师 定制

On 03/16/2020 11:19, shaoyeliudiange wrote:

非常感谢，我试了 300k的一点都不卡，如丝柔般顺滑，非常感谢你 非常感谢你！我也不用tg的了 就用你的了 ！哈哈




| |
刘殿阁
|
|
邮箱：shaoyeliudiange@163.com
|

签名由 网易邮箱大师 定制

On 03/11/2020 13:57, shaoyeliudiange wrote:
我现在还没有时间尝试。目前天天在加班！周末我找一个时间试下




| |
刘殿阁
|
|
邮箱：shaoyeliudiange@163.com
|

签名由 网易邮箱大师 定制

On 03/11/2020 13:54, DreamPiggy wrote:

@liudiange What's the current latest status of that Lottie Coder ? Can that new coder solve the performance issue ?
