### ISSUE TITLE
how to display  json format image and let it have a animation

### ISSUE THREAD

**Issue by liudiange** [SDWebImage/SDWebImage#2950]
for example :
i can use lottie like this 

class HomeCollectionViewCell: UICollectionViewCell {

    
    @IBOutlet weak var animationView: AnimationView!
    var model: Model? {
        didSet{
            self.animationView.pause()
            
            let aniamtion = Animation.named("297944810352570808")
            self.animationView.animation = aniamtion
            self.animationView.animationSpeed = 1.0
            self.animationView.loopMode = .loop
            self.animationView.currentFrame = 10
            self.animationView.play()
            
        }
    }
    
    override func awakeFromNib() {
        super.awakeFromNib()
    
    }

}
I can not decode json file to image,and god please help me
my Demo is this
https://github.com/liudiange/imageDemo1

**Comment by dreampiggy** [comment]
Is this duplicated for #2949 ? Close one and use only one issue to report

**Comment by liudiange** [comment]
sorry，i update it

**Comment by dreampiggy** [comment]
And, I've already tell the way to do. You need a custom loader, which implements the logic to `Give a JSON NSData, convert it to a UIImage subclass`.

I don't read Lottie-iOS's API, does this 

```
let animation = Animation.named("297944810352570808")
```

+ The animation is a subclass of `UIImage` ? If not, you need a wrapper UIImage subclass. Learn it from [FLAnimatedImage plugin](https://github.com/SDWebImage/SDWebImageFLPlugin/blob/master/SDWebImageFLPlugin/Classes/FLAnimatedImageBridge/SDFLAnimatedImage.h)

pseudocode:

```swift
open class LottieImage : UIImage, SDAnimatedImageProtocol {
    var animation: Animation
    // then all the protocol method you can just return the actual value using Lottie-iOS API
}
```

+ Next, you need to write your wrapper, to support the `sd_setImage` on your custom view, like this pseudocode

```
extension AnimationView {

    open func sd_setImage(with url: URL?) {
        self.sd_internalSetImage(with: url, options: [], context: [.animatedImageClass: LottieImage.Self])
    }
}
```
