### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by iOSCountry** [SDWebImage/SDWebImage#2951]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          iOS
 Platform Version        13.3.1
 SDWebImage Version      5.5.2
 Integration Method      cocoapods
 Xcode Version           Xcode 11.3.1
 Repro rate              100%
    
UITableViewCell Load picture， When there are many pictures, swipe back and forth quickly and crash 

![image](https://user-images.githubusercontent.com/17453419/75578322-94713080-5a9e-11ea-8b65-bafa685d2413.png)

**Comment by dreampiggy** [comment]
Seems a OOM issue. Check your bitmap image pixel size (calculate that the concurernt load should not beyond your iPhone's RAM).

Or, check the tips how to limit the RAM usage in wiki:

+ https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#optimization-for-large-images
+ https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#thumbnail-decoding-550

**Comment by dreampiggy** [comment]
@iOSCountry SDWebImage [5.7.2](https://github.com/SDWebImage/SDWebImage/releases/tag/5.7.2) version released. I think this solve some OOM issue for large number of images using in `SDAnimatedImageView`.
