### ISSUE TITLE
Images are not cached?!

### ISSUE THREAD

**Issue by nastasiupta** [SDWebImage/SDWebImage#2960]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS 
 Platform Version        | 13.3
 SDWebImage Version      | 5.6.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.3.1
 Repro rate              | e.g. all the time (100%)

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

When the app starts, I set a security token for all the requests:
**SDWebImageDownloader.shared.setValue("something", forHTTPHeaderField: "Auth")**

After that, each time I have a an UIImageView I set the image with this...
`    func setupWith(URL: URL?, placeholderImage: UIImage? = nil, completion: ((UIImage?) -> Void)? = nil) {
        sd_setImage(with: URL, placeholderImage: placeholderImage) { (image, _, _, _) in
            completion?(image)
        }
    }`

The problem is that each time I dismiss the screen and open it again, the image is downloaded from server... but if I scroll the table view content, the images are displayed instant... only the first time is downloaded. :|...

**Comment by dreampiggy** [comment]
The HTTP header does not effect the cache policy, because we **Use NSURL.absoluteString by default with Cache Key**, not the **NSHTTPURLRequest which contains HTTP header**.

Can this be reproduced in our demo ? Provide a full reproducable demo can let us easy to investigate the issue.

**Comment by dreampiggy** [comment]
There are also many options effect the policy to download, including but not least:

+ `.fromLoaderOnly`: Always download and ignore cache
+ `.refreshCached`: Always download but callback completion only when new image is not equal to cached one (Suck...)


Also, you can try to set a breakpoint at `SDImageCache.queryImage` method, to see whether it query disk cache failed (If we query disk cache failed, we will do HTTP request). The disk cache may be cleared in some condition (like you setup the maxCacheAge, like you remove the default cache folder)

**Comment by dreampiggy** [comment]
@nastasiupta Any extra update ?

**Comment by nastasiupta** [comment]
@dreampiggy I don't use any option for download :-?.  As I understood, if no option is provided, it caches the image by default :-?

**Comment by dreampiggy** [comment]
Yes. It indeed cache the image into both Memory and Disk cache. With the default option.

**Comment by dreampiggy** [comment]
Is the URL changed during two sd_setImage call ?

**Comment by nastasiupta** [comment]
@dreampiggy  no, the URL string is not modified. This issue happens if I dismiss UITableViewController and present it again. During the UITableView cells dequeue, everything is fine ...

**Comment by dreampiggy** [comment]
Any little demo or psodcode can I try to find the issue ? I can not reproduce this strange behavior on SDWebImage's demo.

**Comment by dreampiggy** [comment]
Did you clean the memory cache during *Dismissing the UITableViewController* ? Sounds strange.

**Comment by nastasiupta** [comment]
@dreampiggy  no cleanup on dismissing :) 

code: 
`import Foundation
import SDWebImage

extension UIImageView {
    
    func setupWith(URL: URL?, placeholderImage: UIImage? = nil, completion: ((UIImage?) -> Void)? = nil) {
        sd_setImage(with: URL, placeholderImage: placeholderImage) { (image, _, _, _) in
            completion?(image)
        }
    }

}
    
`

**Comment by nastasiupta** [comment]
My issue is related to this: https://github.com/SDWebImage/SDWebImage/issues/2103

**Comment by bigNiuSanMao** [comment]
> @dreampiggy no cleanup on dismissing :)
> 
> code:
> 
> ```swift
> import Foundation
> import SDWebImage
> 
> extension UIImageView {
>     
>     func setupWith(URL: URL?, placeholderImage: UIImage? = nil, completion: ((UIImage?) -> Void)? = nil) {
>         sd_setImage(with: URL, placeholderImage: placeholderImage) { (image, _, _, _) in
>             completion?(image)
>         }
>     }
> 
> }
> ```

how dealt with this probloem finnaly?
