### ISSUE TITLE
SDImageCacheConfigExpireTypeAccessDate strange behavior

### ISSUE THREAD

**Issue by nicolasgoutaland** [SDWebImage/SDWebImage#2964]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Description and Steps
Hi,

Thanks again for your awesome library.
I'm using it for years and was trying to use the new cache option SDImageCacheConfigExpireTypeAccessDate introduced with https://github.com/SDWebImage/SDWebImage/pull/2357

When testing it on real device, cache doesn't seem to work as intended, since my images are still deleted, even when used.

After some research on Apple documentation, aout the [NSURLContentAccessDateKey](https://developer.apple.com/documentation/foundation/urlresourcekey/1408314-contentaccessdatekey) option.

I don't know how you understand it, but it seems it is the developer responsability to also set its value.

I've done some tests, and this parameters do not seems to be updated when opening a file through API.

What do you think about that ?

Regards,

**Comment by dreampiggy** [comment]
You mean, iOS System (Please provide your test enviornment again...) does not setup the accessDate ?

But, from the documentation, it should:

> Otherwise, the file system may set the contentAccessDateKey value to the current contentModificationDateKey value.

Can I reproduce this on some demo ?

**Comment by dreampiggy** [comment]
Does this happended only on APFS file system (iOS 11+) or HFS+ file system (iOS 11-)

**Comment by dreampiggy** [comment]
If the `NSURLContentAccessDateKey` does not work, maybe we need low-level POSIX API, to check the `mtime`, `atime`, etc

**Comment by nicolasgoutaland** [comment]
Hi,
thanks for your quick answer.
The problem was confirmed on HFS+ devices (several cases reported by users, all kind off OS versions), but don't assume it wasn't also on iOS 10 devices.
I've made some tests on simulator, device, playground, also mac os and it seems that this property isn't set by OS automatically.

My concern is that the documentation state that this property was readonly prior iOS 11, so I don't know if we can handle it on such devices

I've checked your methods, and atime seems the way to go http://kerolasa.github.io/filetimes.html, but need a test to validate it on real devices, and I've only iOS13+ device for now

**Comment by nicolasgoutaland** [comment]
Did just test on emulator, doesn't seems to work as magically as intended

```
#include <sys/stat.h>

- (void)testAccessTime {
    // Do any additional setup after loading the view.
    NSFileManager *fileManager = [NSFileManager defaultManager];
    NSString *documentsFolder  = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0];
    NSString *filePath = [documentsFolder stringByAppendingPathComponent:@"test.file"];

    // Create file
    [fileManager createFileAtPath:filePath contents:nil attributes:nil];

    NSLog(@"%@", [self lastAccessDate:filePath]);

    [NSThread sleepForTimeInterval:2];
    [NSData dataWithContentsOfFile:filePath];

    NSLog(@"%@", [self lastAccessDate:filePath]);

    // Delete file
    [fileManager removeItemAtPath:filePath error:nil];
}

- (NSDate *)lastAccessDate:(NSString *)filePath {
    // Extract file infos
    struct stat output;
    int ret = stat([filePath fileSystemRepresentation], &output);
    if (ret != 0) {
        return nil;
    }

    // Extract last access time
    return [NSDate dateWithTimeIntervalSince1970:output.st_atimespec.tv_sec];
}
```

**Comment by dreampiggy** [comment]
@nicolasgoutaland  Sorry for this late. I test this demo code and found the reason.

This API is totally deprecated: [NSFileManager createFileAtPath:contents:attributes:](https://developer.apple.com/documentation/foundation/nsfilemanager/1410695-createfileatpath?language=objc)

SD used to use that API (seems in 4.x version), but then replaced with the [NSData writeToFile:atomically:](https://developer.apple.com/documentation/foundation/nsdata/1408033-writetofile?language=objc)

See the different behavior between both. The NSFileManger will strip all the fil xattr, where the NSData one works for cases. Only one line code changes.

+ NSFileManager

<img width="1410" alt="截屏2020-04-04下午5 07 26" src="https://user-images.githubusercontent.com/6919743/78423175-2cae9680-7697-11ea-93f5-a63179b268a1.png">

+ NSData

<img width="1396" alt="截屏2020-04-04下午5 07 52" src="https://user-images.githubusercontent.com/6919743/78423169-26201f00-7697-11ea-918f-4af36e70e1ed.png">

So, for SDWebImage's network downloaded cache, the `.accessData` expire type should work as expected.

**Comment by dreampiggy** [comment]
If you still find issue related to this, you can fire extra information and let me know. SDWebImage 5.7.0 will release cuurently without reference to this issue.

**Comment by dreampiggy** [comment]
The `NSURLContentAccessDateKey` API works as expected as the POSIX API stat and atime. So I think they are works in the same way, just High level API wrapper.

**Comment by nicolasgoutaland** [comment]
Thanks for explanation, I will keep you in touch if I find an explanation to this problem.
Regards
