### ISSUE TITLE
Caching/offline does not work

### ISSUE THREAD

**Issue by coolcool1994** [SDWebImage/SDWebImage#2965]
When I loaded images using SDWebImageManager's loadImageWithURL, exit that photosViewController, turn wifi/cellular OFF, come back to photosViewController, all the photos would be loaded, with SDImageCacheTypeMemory returned.

But, when I exit that photosViewController the second time and come back, none of the photos are loaded with SDImageCacheTypeNone returned.

Or after I load the images with wifi/cellular, then quit the app by swiping from bottom, then do a cold start, photosViewController would not load any images with "Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline."".

The whole caching thing seems to be broken? I am trying to cache so it does not cost me money to fetch the same images over and over, but SDWebImage is not caching and not working to support offline mode after downloading the images when online.

I used Cocoapod to download the library, and am using iOS 13 real device to test.
- SDWebImage (5.4.0):
- SDWebImage/Core (= 5.4.0)
- SDWebImage/Core (5.4.0)

**Comment by coolcool1994** [comment]
I can provide more info. What's not enough info?

**Comment by dreampiggy** [comment]
Any reproducable demo ? Sounds really strange. Like #2960

**Comment by dreampiggy** [comment]
I'll check the SDWebImage's own demo again. You can do a check as well.

```
cd SDWebImage/
pod install
open SDWebImage.xcworkspace
Command + B
```

**Comment by coolcool1994** [comment]
im working on a real big project so I do not have a demo, but I will check SDWebImage's own demo right now

**Comment by dreampiggy** [comment]
> im working on a real big project so I do not have a demo

Just abstract your use case, provide the pseudocode, also with the customization detail (at least, what of `SDWebImageOptions/SDWebImageContext` and `SDWebImageCache/Download Config` you use).

**Comment by coolcool1994** [comment]
```SDImageCache *imageCache = [[SDImageCache alloc] initWithNamespace:@"thm" diskCacheDirectory: pathToGroupStorage];
        [imageCache.config setMaxDiskAge:-1];
self.webImageManager = [[SDWebImageManager alloc] initWithCache:imageCache loader:[SDWebImageDownloader sharedDownloader]];```

```
[self.webImageManager loadImageWithURL:[NSURL URLWithString: image_web_url] options:SDWebImageHighPriority progress:nil completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, SDImageCacheType cacheType, BOOL finished, NSURL * _Nullable imageURL) {
                if (finished && image) {
                    photoItem.image = image;
                    [weakSelf.collectionView reloadData];
                }
            }];```

**Comment by coolcool1994** [comment]
I am doing straight forward thing. I initialize SDWebImageManager with a SDImageCache with a custom diskCacheDirectory (since I want to use it across multiple extensions). And I load the image_urls. But the images are not cached in the library when I turn off wifi/cellular.

**Comment by dreampiggy** [comment]
Check whether you disk cache folder created successfuly.
The folder should name:

```
pathToGroupStorage/namespace
```

**Comment by dreampiggy** [comment]
We do not append any NSSearchPathForDirectoriesInDomains for your if you pass `diskCacheDirectory` non nil value.

So, check again, what's your `pathToGroupStorage` and `namespace` value in runtime is.

**Comment by dreampiggy** [comment]
In most cases, you don't need to use `diskCacheDirectory`, provide the namespace is enough. We will create this for you:

```
~/Caches/com.hackemist.SDWebImageCache/${namespace}
```

**Comment by coolcool1994** [comment]
I am downloading the image using SDWebImage in the Notification Service Extension and caching it so that when the user opens the app, the user doesn't have to redownload the image. This is good for the user (quick loading) and also for me (less cost for less GB downloaded from the server)

**Comment by coolcool1994** [comment]
I will check the other values now, but I want the SDWebImage cache to store images in the folder provided by App Group Capability so that the data can be accessed from both Notification Service Extension and the actual app itself.

**Comment by dreampiggy** [comment]
"in the folder provided by App Group Capability"

If SDWebImage can access to that directory, it will works. If not, full Disk Cache function will break.

I think it's issue on the case when you pass a wrong disk cache directory, or SDWebImage can not access (write access) to that directory.

In this cases, a Log from Fondation framework, or if you use the `NSFileManager` delegate will receive the error report.

**Comment by dreampiggy** [comment]
See: `SDImageCacheConfig.fileManager`

**Comment by dreampiggy** [comment]
You can also set a breakpoint here to debug:

https://github.com/SDWebImage/SDWebImage/blob/5.4.0/SDWebImage/Core/SDDiskCache.m#L90

If you use iPhone Simulator, you can copy that `fileURL` or `self.diskCachePath` into you Finder on Mac, acess and check whether the folder exists.

**Comment by coolcool1994** [comment]
that file path is broken  has file:///file:/

file:///file:/private/var/mobile/Containers/Shared/AppGroup/006894F7-5B12-4Y81-A365-EC19E45363A84/tom/tom/b0df51738caa9db6558864f174754a5b.jpeg

hmm

**Comment by coolcool1994** [comment]
po fileURL is like this
file:/private/var/mobile/Containers/Shared/AppGroup/006894F7-5B12-4Y81-A365-EC19E45363A84/tom/tom/b0df51738caa9db6558864f174754a5b.jpeg -- file:///

po [fileURL absoluteString]:
file:///file:/private/var/mobile/Containers/Shared/AppGroup/006894F7-5B12-4Y81-A365-EC19E45363A84/tom/tom/b0df51738caa9db6558864f174754a5b.jpeg

**Comment by dreampiggy** [comment]
Seems you pass a NSURL(fileURL)’s absoluteString into the arg.

SDImageCache’s `diskCacheDirectory` use file Path, not file URL

**Comment by coolcool1994** [comment]
Wow! Yeah. It is all working after I fixed it to path instead of absoluteString here:

from:
NSString *pathToGroupStorage = [[[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:@"group.name.from.project"] absoluteString];

to: 
NSString *pathToGroupStorage = [[[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:@"group.name.from.project"] path];

You are lightening fast and a SDWebImage genius! Thank you so very much!!

**Comment by dreampiggy** [comment]
You're welcome.

In the future (maybe 6.0.0) we will provide a full-trace log system for SDWebImage, which may help for this usage settings issues.

For now, just close this...
