### ISSUE TITLE
How to use 'WebImageVersionNumber' ?

### ISSUE THREAD

**Issue by iamlion** [SDWebImage/SDWebImage#2969]
How to use 'WebImageVersionNumber' ?

I have error:
'
Undefined symbols for architecture arm64:
  "_WebImageVersionNumber", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
'

**Comment by dreampiggy** [comment]
Seems...This version does not get defined. You should not reference to that symbol, and it get stripped automatically.

Did you want to use the Version for some binary compatible check ? If so, we can update to add this version in the future release, like 5.7.0

**Comment by iamlion** [comment]
> @iamlion Seems...This version symbol only exported, but not get defined. So it will cause link error.
> 
> You should not reference to that symbol, and it get stripped automatically.
> 
> Did you want to use the Version for some binary compatible check ? If so, we can update to add this version in the future release, like 5.7.0

YES，I need version to compatible check.

Many of our projects depend on SDWebImage and need to be compatible with the version

**Comment by dreampiggy** [comment]
We can added it to 5.7.0. However, for old version, there are no such a symbol.

Can you use the `feature` testing , like check some new SDWebImage classes using `NSClassFromString`, instead of using version check ? Or do we have something that actually break behavior during 5.0~5.7.0

**Comment by dreampiggy** [comment]
If you only use CocoaPods. You can use CocoaPods's `SDWebImageVersionNumber` symbol, this is generated by CocoaPods, which can give you the version.

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/78358033-15af6c00-75e5-11ea-9445-d0ca709c9d94.png)

**Comment by dreampiggy** [comment]
Solved by #2971, Carthage && SwiftPM can use the correct symbol from [5.7.0 version](https://github.com/SDWebImage/SDWebImage/releases/tag/5.7.0)
