### ISSUE TITLE
Incompatible Objective-C category definitions.

### ISSUE THREAD

**Issue by LXXuanCai** [SDWebImage/SDWebImage#2970]
ld: warning: Incompatible Objective-C category definitions. Some category metadata may be lost. '/Users/apple/Library/Developer/Xcode/DerivedData/XXXBuild/Products/Debug-iphoneos/SDWebImage/libSDWebImage.a(SDWebImageTransition.o)' and '/Users/apple/Desktop/XXX/Pods/UMCCommon/UTDID.framework/UTDID(UTDIDGTMBase64.o) built with different compilers

Installing SDWebImage 5.6.1 (was 5.6.0)
Installing UMCCommon 2.1.4 (was 2.1.1)
Installing UMCShare 6.9.8 (was 6.9.6)

**Comment by LXXuanCai** [comment]
how to solve this problem

**Comment by dreampiggy** [comment]
Seems you use a prebuilt framework (here UTDID.framework) which contains the Category to SDWebImage's class.

Could you please ask Umeng for help ? They can change the code to not cause conflict with SDWebImage itself.

**Comment by dreampiggy** [comment]
Chinese:

Prebuild的静态库的冲突导致的，对同一个类进行了同样的Category，运行时可能有问题，也可能没有问题。看起来这个UMCCommon是友盟公司提供的静态库，请咨询一下他们

**Comment by LXXuanCai** [comment]
SD使用了一个UIView的分类，里面起名我猜测是.x .y .witdh等，所以会和项目中其他同样起名的分类造成警告，应该不会有什么真实的影响，最后的结果是我放弃了友盟的安全组件。。。。

**Comment by LXXuanCai** [comment]
我不想在我的代码中看见警告

**Comment by dreampiggy** [comment]
> SD使用了一个UIView的分类，里面起名我猜测是.x .y .witdh等，所以会和项目中其他同样起名的分类造成警告，应该不会有什么真实的影响，最后的结果是我放弃了友盟的安全组件。。。。

不是的。

原因在于，UTDID.framework这里，使用了非同一个大版本的clang编译器，即非同一个版本的Xcode进行了编译，并且含有一个对同一个类进行Category，且Category Name相同的文件。

你需要咨询UMCCommon，他们需要重新编译一次即可。二进制上，Category Name不会造成问题，只有Selector同名才有问题

**Comment by LXXuanCai** [comment]
了解了

**Comment by vit008** [comment]
hi guys,
I have the same issue 
`ld: warning: Incompatible Objective-C category definitions. Some category metadata may be lost. '/Users/XXXX/Library/Developer/Xcode/DerivedData/IoApp-dxplamzoyxjpusfcibatpqdpqsmf/Build/Products/Debug-iphonesimulator/SDWebImage/SDWebImage.framework/SDWebImage(SDWebImageTransition.o)' and '/Users/XXXX/serve/tech/src/Source/IoApp/External/GRMustache/lib/libGRMustache7-iOS.a(GRMustacheKeyAccess.o) built with different compilers`


Can you help me to resolve this issue?
