### ISSUE TITLE
Caching transformedImage in originalImage's format Results In Wrong Encoding (e.g., lost alpha channel)

### ISSUE THREAD

**Issue by bdaz** [SDWebImage/SDWebImage#2975]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 13.4
 SDWebImage Version      | 5.7.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.4
 Repro rate              | 100%

### Issue Description and Steps

Issue: As of [this change](https://github.com/SDWebImage/SDWebImage/commit/46b0c4bae83103209431b2ec1eddae718a55d6df#diff-77921df0f8ea1cdae171e24d8060fe6bR345-R347), `SDWebImageManager` is caching  the transformed image in the downloadedImage's format. If the downloadedImage is a JPG, and the transformed image has an alpha channel (i.e., must be stored as a PNG), this leads to bugs where the alpha channel of the transformed image is lost when retrieved from the cache.

Expected Result:
The image format of the transformed image should be preserved when caching it.

Actual Result:
The image format of the transformed image is lost when it is cached. This results in the alpha channel getting lost if the downloadedImage is a JPG.

Regressions:
This was not an issue prior to 46b0c4bae83103209431b2ec1eddae718a55d6df.

**Comment by bdaz** [comment]
As a quick example, here's the transformed image that gets stored via `-[SDImageCache storeImage:imageData:forKey:toMemory:toDisk:completion:]:

![storeImage](https://user-images.githubusercontent.com/1771280/78706080-56e49c00-78c3-11ea-8b42-c7bc1ab35499.png)

And here's the image that gets retrieved from the cache via `-[SDImageCache diskImageForKey:data:options:context:]` with the same parameters:

![diskImage](https://user-images.githubusercontent.com/1771280/78706168-7e3b6900-78c3-11ea-960a-36c6af1279f1.png)

(Note the lack of an alpha channel in the second image)

**Comment by dreampiggy** [comment]
From the correct behavior, the transformed image should not inherit any information from the original one, even for the image format cames from. So this sounds not a designed behavior and should be fixed.

I'll fix it soon tomorrow, One question, So this bugfix applied for 5.7.1 patch version ? Or backward patch to old version like 4.6.2 ? There seems no huge changes during 5.4-> 5.7 and it's OK to upgrade,

**Comment by bdaz** [comment]
@dreampiggy That sounds correct to me, though I'm less familiar with the SDWebImage codebase than you are. 

In my own repo I've got a patch that avoids copying any attributes from originalImage to transformedImage, like you suggest, and unsurprisingly this restores the correct behavior as far as I can tell, though I'm not sure how to test it beyond my own use cases of image loading in my app. I'm happy to submit it as a pull-request if you'd like though.

**Comment by dreampiggy** [comment]
Fixed in 5.7.1 and released: https://github.com/SDWebImage/SDWebImage/releases/tag/5.7.1
