### ISSUE TITLE
SDImageTransformer  'UIColor+HexString.h' file not found

### ISSUE THREAD

**Issue by Akateason** [SDWebImage/SDWebImage#2978]
In  "SDImageTransformer.h" 
'UIColor+HexString.h' file not found

**Comment by Akateason** [comment]
thats a third part conflict question.

**Comment by dreampiggy** [comment]
If you install via Carthage/SwiftPM, the search path is correct and no other same file name header files will conflict.

If you install via CocoaPods, be sure to not **Hack SDWebImage**' search path (`HEADER_SEARCH_PATHS` xcconfig), or you have to solve this by yourself.
