### ISSUE TITLE
'UIColor+HexString.h' file not found

### ISSUE THREAD

**Issue by Gaozn** [SDWebImage/SDWebImage#2979]
swift
pod 'SDWebImage', '~> 5.0'

**Comment by dreampiggy** [comment]
See #2978.

We can not rename this file until SDWebImage 6.0.0. So, please use Carthage, or solve the header search path conflict by other bad-written CocoaPods framework. This is not SDWebImage's fault.

And SDWebImage 6.0.0 have two big goal to do, one is Swift Overlay Framework (Totally rename all current Objective-C exported API), one is the Separate of two component `SDWebImage` and `SDImage` (for image decoding/encoding related component). The schedule aim to be 2020 August...

**Comment by Gaozn** [comment]
谢谢你，我刚刚也已经找到了原因：（另一个库存在同名的文件）。

**Comment by dreampiggy** [comment]
The framework who make `UIColor+HexString.h` public in Podspec, or use the hack with `s.pod_target_xcconfig = {'HEADER_SEARCH_PATH' => 'xxxx'}` to point to their own folder, will cause the issue.

This is a bad design from other framework, not SDWebImage. SDWebImage use this header as *Private Header*, which is not designed to effect others.
