### ISSUE TITLE
UICollectionView Compositional Layout + Diffable Datasource Support

### ISSUE THREAD

**Issue by akun1** [SDWebImage/SDWebImage#2984]
### New Issue Checklist

* [x ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 13.0+
 SDWebImage Version      | Latest as of 4/15/2020
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 11
 Repro rate              | all the time (100%)
 Repro with our demo prj | Unsure
 Demo project link       | Unable to provide

### Issue Description and Steps

**Explanation:**

We have a UICollectionView using compositional layout + diffable data source. Each cell has an imageView inside and some labels. 

When loading the image view, we use sd_setImage() to set the image URL. When we do this with a standard index collection view, everything works.

However, when we use sd_setImage() with compositional layout, images will load in random cells and flicker when cells go in and out of view.

**Steps to Repro**

1. Create UICollectionView with compo layout + diffable data source. Make layout similar to App Store's layout.

2. Load image URLs into first row of cells (they should have image views inside of them). Use sd_setImage func.

3. When you run them and the images load, you'll see multiple cells in different rows and sections load images that are not supposed to be there.

4. Make sure all cells have same class, but different layouts.

**Comment by dreampiggy** [comment]
> Create UICollectionView with compo layout + diffable data source. Make layout similar to App Store's layout.

...Can we have a little example for this ? You don't need to create an App, use mock data and mock server is OK, just construct the usage case is enough for debugging.

**Comment by dreampiggy** [comment]
See #3766 

Use `SDCallbackPolicySafeAsyncMainThread` as context option when you query image URL inside the Diffable method.
