### ISSUE TITLE
Memory growth problems caused by reading the same disk data at the same time

### ISSUE THREAD

**Issue by BackNotGod** [SDWebImage/SDWebImage#2994]
### New Issue Checklist

* [√] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [√ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [√] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        |  12.0 
 SDWebImage Version      | 5.0.0
 Integration Method      |cocoapods
 Xcode Version           | Xcode 11
 Repro rate              |  all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

```
    [self.image1 sd_setImageWithURL:[NSURL URLWithString:@"https://www.sinaimg.cn/dy/slidenews/5_img/2015_52/72543_1311880_734219.gif"]];
    [self.image2 sd_setImageWithURL:[NSURL URLWithString:@"https://www.sinaimg.cn/dy/slidenews/5_img/2015_52/72543_1311880_734219.gif"]];
    [self.image3 sd_setImageWithURL:[NSURL URLWithString:@"https://www.sinaimg.cn/dy/slidenews/5_img/2015_52/72543_1311880_734219.gif"]];

```
When I request the same large image at the same time, there is no problem if there is no disk cache, because they share a download operation.
However, when I read the same image data from disk at the same time, I get repeated decoding, causing memory to explode.
I wonder if it is possible to add a second check of the decoded data to 'SDImageCache.m' to confirm that the decoded data already exists in memory.

![image](https://user-images.githubusercontent.com/13093664/80338381-c29ca200-888e-11ea-9a0a-2f763fa57333.png)
I don't know if there are any other potential problems with this.

**Comment by dreampiggy** [comment]
This seems like a feature request:

You want the cache to use the same `Different Query in cache share the same disk access and decoding`.

Currently we only supports the Download (Different Query to download share same Network access).

**Comment by dreampiggy** [comment]
One question:

Why the next query to cache, does not hit memory cache ? There already code to store the image from disk cache into memory. So they should not hit this, until concurrent query.

![image](https://user-images.githubusercontent.com/6919743/80339039-63d82800-8890-11ea-9dd2-85a4744212a1.png)

**Comment by BackNotGod** [comment]
![image](https://user-images.githubusercontent.com/13093664/80339582-8e76b080-8891-11ea-89ff-20fa0168e0ab.png)
The image judged in the queue was read from outside the queue and may have been invalidated

**Comment by BackNotGod** [comment]
> ![image](https://user-images.githubusercontent.com/13093664/80339582-8e76b080-8891-11ea-89ff-20fa0168e0ab.png)
> The image judged in the queue was read from outside the queue and may have been invalidated.
> But at this point the decoded data does already exist in memory, so there will be repeated decoding

I can set the SDWebImageQueryDiskDataSync options to avoid memory problems, But the dispatch_sync synchronization operation slows down the program.  😅

**Comment by dreampiggy** [comment]
This need some implementation like DownloadToken, to support the `Different Query for same URL for disk cache, should share the actually Disk IO and Decoding process`.

Not a huge bug, but this need some implementation code, marked in v5.8.0 and future milestone.

**Comment by dreampiggy** [comment]
But, can't that `@autoreleasepool` works for reduce memory peak ?

The Disk Access and Decoding use the same `ioQueue` (A serial queue), so, in theory there should be only 1 disk access at the same time, and 1 decoding process. But seems the release timing of temp object (during decoding) does not works as expected ?

**Comment by BackNotGod** [comment]
> But, can't that `@autoreleasepool` works for reduce memory peak ?
> 
> 
> 
> The Disk Access and Decoding use the same `ioQueue` (A serial queue), so, in theory there should be only 1 disk access at the same time, and 1 decoding process. But seems the release timing of temp object (during decoding) does not works as expected ?

The key is that the image data corresponding to the same url will be decoded multiple times, resulting in a waste of memory。

Image judged in serial queue may be misjudged.

**Comment by BackNotGod** [comment]
> > But, can't that `@autoreleasepool` works for reduce memory peak ?
> > 
> > 
> > 
> > The Disk Access and Decoding use the same `ioQueue` (A serial queue), so, in theory there should be only 1 disk access at the same time, and 1 decoding process. But seems the release timing of temp object (during decoding) does not works as expected ?
> 
> The key is that the image data corresponding to the same url will be decoded multiple times, resulting in a waste of memory。
> 
> Image judged in serial queue may be misjudged.
> 
> 

I can provide test case results.😁

**Comment by BackNotGod** [comment]
The reading of the image data in the memory is in the main thread, but the judgment of whether the image is empty is in other threads of a serial queue, such judgment is inaccurate.
