### ISSUE TITLE
SDWebImage with Tableview after several times  load images not show

### ISSUE THREAD

**Issue by kingnight** [SDWebImage/SDWebImage#2995]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 12.4 / 11.1
 SDWebImage Version      | 5.6.1
 Integration Method      | cocoapods 
 Xcode Version           | e.g. Xcode 11 / Xcode 10
 Repro rate              | all the time (100%) 
 Repro with our demo prj |
 Demo project link       | 
### Issue Description and Steps

1. Description : SDWebImage with Tableview after several times load more images will not show on screen,  this only  happens on iOS13 below, for example, iOS11.1
When this happens,  I go through SDWebImage  network queue, found network no callback and no timeout

2. Console Output 
```
Task <CD813072-7AFE-46BC-8B83-CBA42DBD26DC>.<167> finished with error - code: -1001
TIC TCP Conn Failed [40:0x139a3b630]: 3:-9802 Err(-9802)
Task <A7BE6C76-A101-410C-B6AA-D0B1DD011032>.<166> HTTP load failed (error code: -1200 [3:-9802])
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
```
3. My App Setting
app plist setting
```
<key>NSAppTransportSecurity</key>
<dict>
<key>NSAllowsArbitraryLoads</key>
<true/>
</dict>
```
4. Image Server has checked  support  TLS 1.2 and  Certificate  support #1: RSA 2048 bits (SHA256withRSA)，I aslo check to use SDWebImageOptions.allowInvalidSSLCertificates  to download Images ,  the result are same 

Does anyone have a suggestion to give?

**Comment by dreampiggy** [comment]
Still have this issue ?

Check the kCFStreamErrorDomainSSL error code description. Or using Charles to debug the network response.

This sounds nothing to do with SD, because it looks like a common network request issue.

**Comment by kingnight** [comment]
hi dreampiggy,
Still have,   When Images do not show, Using Charles to monitor image downloading request,  sd_image  function call with specified URL, but  Charles not see  this request URL

**Comment by henryawang** [comment]
@kingnight Maybe you used the wrong URL. Please check your URL! The simple solution:you can change a URL to test

**Comment by dreampiggy** [comment]
Use `.retryFailed`. This error will be marked into black list if you don't provide.

Debug the **First Network Request** for your url.

**Comment by kingnight** [comment]
thanks, dreampigg,  I have tried  `.retryFailed`,  the result is the same , but the most confusing is on iOS13 and later, same code runs ok,  but on iOS11,iOS12, the problem happens, so maybe is not SDWebImage 's  problem, but I can't find why
