### ISSUE TITLE
Issues about SDWebImagePrefetcher

### ISSUE THREAD

**Issue by LivyNN** [SDWebImage/SDWebImage#2998]
After calling [[SDWebImagePrefetcher sharedImagePrefetcher] cancelPrefetching];
Prefetcher seems to be hung up forever。

So, I tried to read code in SDWebImagePrefetcher.m and find some question I don't understand.

The first question is:

I know NSOperation conforms to SDWebImageOperation protocol, but when I tried to catch SDAsyncBlockOperation like this, I still get some SDAsyncBlockOperations:

![image](https://user-images.githubusercontent.com/37862043/80691195-82455a00-8b02-11ea-9781-c0ab6cc0c0b3.png)

I find some discussion about this from this issue : https://github.com/SDWebImage/SDWebImage/pull/2645/files/ff3a3e827d2741721d1ac3307da91ce99113cba8

But in that commit , " [operation isKindOfClass:[SDAsyncBlockOperation class]] " was changed back to "[operation conformsToProtocol:@protocol(SDWebImageOperation)]",  So I think this problem may cause SDAsyncBlockOperation won't be cancelled after I cancel prefetching manually.

The second question is:
This [asyncOperation complete]  was called in operation's block but not prefetchOperation's block, and I tried to move it out. It solved my problem , the prefetcher still works after I cancel prefetching manually,  but I'm not sure about it's right or not.

![image](https://user-images.githubusercontent.com/37862043/80692769-ad30ad80-8b04-11ea-91a7-66c33b48dbe9.png)
 

Thank you

**Comment by dreampiggy** [comment]
> " [operation isKindOfClass:[SDAsyncBlockOperation class]] " was changed back to "[operation conformsToProtocol:@protocol(SDWebImageOperation)]", So I think this problem may cause SDAsyncBlockOperation won't be cancelled after I cancel prefetching manually.

This does not cause anything issue. Both of them response to `cancel` selector, and it's always `SDAsyncBlockOperation`, just dummy protect code.

What's the real problem is ? I can not reproduce your `hung up` when calling `[[SDWebImagePrefetcher sharedImagePrefetcher] cancelPrefetching];`

Can there be a reproducable demo to trigger the issue ?

**Comment by dreampiggy** [comment]
The `complete` must be called when manager download finished. Or the `SDWebImagePrefetcherDelegate` callback count number is wrong. Your changes mark the operation directlly finished when created, which does not implements the `maxConcurrentCount` and delegate feature correctly.

**Comment by dreampiggy** [comment]
Join here: https://gitter.im/

Describe your issue and question. Can be used in English or Chinese.

**Comment by dreampiggy** [comment]
Fixed in [v5.7.4](https://github.com/SDWebImage/SDWebImage/releases/tag/5.7.4)
