### ISSUE TITLE
Possible to cancel SDWebImageDownloader download?

### ISSUE THREAD

**Issue by JohnnyTseng** [SDWebImage/SDWebImage#300]
Hello, I'm facing an issue, 
when user navigates back to previous view controller,
I want to cancel SDWebImageDownloader's download if it is current downloading something.

I only see cancel method in SDWebImageManager, is it possible to add to SDWebImageDownloader too?

Thank you!

**Comment by wlegate** [comment]
Calling cancel on the SDWebImageOperation object doesn't cancel the operation
