### ISSUE TITLE
Value of type 'UIImageView' has no member 'sd_setShowActivityIndicatorView'

### ISSUE THREAD

**Issue by amitsanvedi** [SDWebImage/SDWebImage#3000]
I have update the library for latest Xcode version then getting following error :
Code : imageDocument.sd_setShowActivityIndicatorView(true) 
Error : Value of type 'UIImageView' has no member 'sd_setShowActivityIndicatorView'
Code : imageDocument.sd_setIndicatorStyle(.gray)
Error : Value of type 'UIImageView' has no member 'sd_setIndicatorStyle'

**Comment by dreampiggy** [comment]
There are non such an API in SD 5.x.

Maybe you should write

```swift
imagwView.sd_indicator = SDWebImageActivityIndicator.medium
```

Always check API documentation in https://sdwebimage.github.io/
