### ISSUE TITLE
App Crash on SDDiskCache: -[SDDiskCache setData:forKey:] + 92,Non-aligned pointer 0xXXX being freed

### ISSUE THREAD

**Issue by wangjianyou** [SDWebImage/SDWebImage#3007]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 95% is iOS 13，4% is iOS 10，1% is iOS 9
 SDWebImage Version      | 5.5.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11
 Repro rate              | 518 crashes ，affect 416 users
 Repro with our demo prj | NA
 Demo project link       | NA

### Issue Description and Steps

Recently we found some crashes, and the information of these crashes is ‘Non-aligned pointer 0x1260956a0 being freed (2)’

Crash Stack
Crashed: com.hackemist.SDImageCache
0 libsystem_kernel.dylib 0x193c6cef4 __pthread_kill + 8
1 libsystem_pthread.dylib 0x193b8dd1c pthread_kill + 196
2 libsystem_c.dylib 0x193b1da54 abort + 104
3 libsystem_malloc.dylib 0x193b7ef8c _malloc_put + 562
4 libsystem_malloc.dylib 0x193b7f218 malloc_zone_error + 104
5 libsystem_malloc.dylib 0x193b66a38 szone_free + 456
6 libsystem_malloc.dylib 0x193b6e924 nanov2_free + 144
7 libsystem_malloc.dylib 0x193b753c0 default_zone_free + 76
8 libsystem_malloc.dylib 0x193b72bfc malloc_zone_free + 176
9 CoreFoundation 0x193d9a440 CFAllocatorDeallocate + 92
10 CoreFoundation 0x193db0bbc __CFCharacterSetDeallocate + 168
11 CoreFoundation 0x193dfe9bc _CFRelease + 232
12 CoreFoundation 0x193db0bf4 __CFCharacterSetDeallocate + 224
13 CoreFoundation 0x193dfe9bc _CFRelease + 232
14 CoreFoundation 0x193eabd4c _CFStringContentsInCharacterSet + 180
15 CoreFoundation 0x193ec0e7c _CFCopyResolvedFormatStringWithConfiguration + 1628
16 CoreFoundation 0x193e20924 __CFStringAppendFormatCore + 9876
17 CoreFoundation 0x193e21b74 _CFStringCreateWithFormatAndArgumentsAux2 + 156
18 Foundation 0x19414482c -[NSString initWithFormat:] + 60
19 Foundation 0x19417ec2c -[NSFileManager _URLForReplacingItemAtURL:error:] + 976
20 Foundation 0x194259400 _NSCreateTemporaryFile_Protected + 740
21 Foundation 0x194259924 _NSWriteDataToFileWithExtendedAttributes + 272
**22 SDWebImage 0x109c0a80c -[SDDiskCache setData:forKey:] + 92 (SDDiskCache.m:92)
23 SDWebImage 0x109c0f9f0 -[SDImageCache _storeImageDataToDisk:forKey:] + 264 (SDImageCache.m:264)
24 SDWebImage 0x109c0f554 __71-[SDImageCache storeImage:imageData:forKey:toMemory:toDisk:completion:]_block_invoke + 201 (SDImageCache.m:201)**
25 libdispatch.dylib 0x193b27bb0 _dispatch_call_block_and_release + 32
26 libdispatch.dylib 0x193b2900c _dispatch_client_callout + 20
27 libdispatch.dylib 0x193b2f484 _dispatch_lane_serial_drain + 568
28 libdispatch.dylib 0x193b2feb0 _dispatch_lane_invoke + 368
29 libdispatch.dylib 0x193b38f20 _dispatch_workloop_worker_thread + 580
30 libsystem_pthread.dylib 0x193b8eaa0 _pthread_wqthread + 280
31 libsystem_pthread.dylib 0x193b94c78 start_wqthread + 8

Guess the reason is the image data to be saved in disk，messed up data. Resulting in memory misalignment.

I can't reproduce it when I compile it myself. So i can't provide a picture link.

Any insight in correcting these crashes would be greatly appreciated.

**Comment by aiquantong** [comment]
the same issues

**Comment by dreampiggy** [comment]
Seems some thread-safe problem ? I'll have a check later.

**Comment by atistank** [comment]
same issues on me, please help
