### ISSUE TITLE
Race Condition when using .forceTransition and loading and cancelling an operation

### ISSUE THREAD

**Issue by AndreasVerhoeven** [SDWebImage/SDWebImage#3011]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        |  13.3
 SDWebImage Version      | e5.7.2
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 11
 Repro rate              | e.g. all the time (100%)
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps

- when using the following sequence of steps:

```
let url = "...." // make sure this url is in the memory cache
imageView.sd_setImage(with: url, placeholderImage: nil, options: [.forceTransition])
imageView.sd_cancelCurrentImageLoad()
imageView.image = UIImage(named: "SomeOtherImage")
```

In the next runloop, the image from `url` is assigned to the image view, even tho we cancelled the load. 

This seems to be the culprit:
```
        [UIView transitionWithView:view duration:0 options:0 animations:^{
            // 0 duration to let UIKit render placeholder and prepares block
            if (transition.prepares) {
                transition.prepares(view, image, imageData, cacheType, imageURL);
            }
        } completion:^(BOOL finished) {
            [UIView transitionWithView:view duration:transition.duration options:transition.animationOptions animations:^{
                if (finalSetImageBlock && !transition.avoidAutoSetImage) {
                    finalSetImageBlock(image, imageData, cacheType, imageURL);
                }
                if (transition.animations) {
                    transition.animations(view, image);
                }
            } completion:transition.completion];
        }];
```
In the completionHandler, there is no check if the current load operation has been cancelled and thus if the setImage would overwrite another image.

We actually get this problem when using collectionview inserts, so this migt be related to #2984 . I'm happy to send a PR for this, just not 100% sure if this is easy, since it seems to touch a lot of stuff that's outside of the loading machinery.

**Comment by dreampiggy** [comment]
Your analysis sounds reasonable.

The transition there does not assume any cancel during load, it always use UIView.transiton to trigger the immediately UI render.

If you want to fix, maybe you need to check the cancelled status of loading (or whether current ImageView.image == input placeholder)

**Comment by AndreasVerhoeven** [comment]
Yeah, the delay is causing the issue. The same thing happens when one uses `SDWebImageDelayPlaceholder`. 

Checking if `imageView.image == input.placeholder` is not enough, because then this would still fail:

```
let placeholder = UIImage(named: "SomeOtherImage")
imageView.sd_setImage(with: url, placeholderImage: placeholder, options: [.forceTransition])
imageView.sd_cancelCurrentImageLoad()
imageView.image = placeholder
// image can still end up being url here if we use imageView.image == input.placeholder
```

The only viable way to me seems to check if the operation didn't get cancelled. There are a lot of places where things are fired off to be done in the next runloop cycle. Those all need to be fixed. 

In your opinion, what would be the best? Checking the operation everywhere? I guess we would need to add a `isCanceled` flag to `SDWebImageOperation` then

**Comment by dreampiggy** [comment]
> I guess we would need to add a isCanceled flag to SDWebImageOperation then.

If introduce a `isCancelled` property can solve this problem, you can add one into the protocol and update all the implementations.

Note, for some of custom loader, they need to update as well (some does not return a `NSOperation` actually, like the one in [FirebaseUI](https://github.com/firebase/FirebaseUI-iOS/blob/master/Storage/FirebaseStorageUI/FUIStorageImageLoader.m#L152), here is a custom NSObject class). This task I can have a fix after your PR is merged.

**Comment by AndreasVerhoeven** [comment]
Thinking about it, would it make sense to attach a uuid to the view when we start loading, and remove it when we cancel? That way, we can "simply" check if the uuid is still the same when changing the image.  Would require no changes to the operations.

In pseudocode:
```
func cancelLoadingOperation() {
  objc_removeAssocatedObject(self, &uuidKey, ...)
}

func loadImage( .... ) {
  let uuid = UUID()
  objc_setAssocatedObject(self, uuid, &uuidKey, ...)

  // example of delayed image setting:
  DispatchQueue.main.async {
     if objc_getAssociatedObject(self, &uuidKey) == uuid {
        self.image = loadedImage
     }
  }
}
```

**Comment by dreampiggy** [comment]
One View can load different urls.

Think UIButton. Each URL is associated with a `UIControlState`

**Comment by dreampiggy** [comment]
Still have this issue ?


I recheck this issue again, if you call `cancel` on the current loading URL, why not this line get triggered and ignore set image image by SDWebImage ? The callback from manager should contains `image = nil && errorCode == SDImageErrorCancelled`

![image](https://user-images.githubusercontent.com/6919743/86311372-d4b20c80-bc52-11ea-8ef3-6b75404b6a78.png)

**Comment by AndreasVerhoeven** [comment]
@dreampiggy Yes the issue is still there: The issue happens when you cancel after the image has been loaded. The default completion handler sets the image in the next runloop.

So:
 - start an image load
 - image loads, default completion handler is called
 - handler checks if the the load is cancelled, which it isn't
 - handler schedules setting the image in the next runloop cycle
 - before that next runloop cycle, we cancel the load
 - when the next runloop runs, the image will still be set, because there's no check in the scheduled update

**Comment by dreampiggy** [comment]
>  The default completion handler sets the image in the next runloop.

The completion handler from `SDWebImageManager` is just main queue, not possible in any other global queue. You can ignore that `dispatch_main_async_safe` call, useless.

I think this issue only because of the `[UIView transitionWithDuration:]`. The `setImage` process is triggered just in the same runloop as the completion of `SDWebImageManager`.

**Comment by dreampiggy** [comment]
Because, for UIKit. Transition means, previous state and current state. So it automatically schedule the rendering code in the closure into next runloop.

**Comment by AndreasVerhoeven** [comment]
If you look at the code:
```
     [UIView transitionWithView:view duration:0 options:0 animations:^{
            // 0 duration to let UIKit render placeholder and prepares block
            if (transition.prepares) {
                transition.prepares(view, image, imageData, cacheType, imageURL);
            }
        } completion:^(BOOL finished) {
                            // A CHECK SHOULD BE ADDED HERE TO SEE IF THE LOADING OPERATION OF THIS SPECIFIC IMAGE HASN'T BEEN CANCELLED. IF IT HAS, DON'T RUN THESE ANIMATIONS
            [UIView transitionWithView:view duration:transition.duration options:transition.animationOptions animations:^{

                if (finalSetImageBlock && !transition.avoidAutoSetImage) {
                    finalSetImageBlock(image, imageData, cacheType, imageURL);
                }
                if (transition.animations) {
                    transition.animations(view, image);
                }
            } completion:transition.completion];
        }];
```

The actual image is set in the completion handler of the first UIView animation, which is in the next runloop. In my opinion, this completion handler should first check if the operation isn't canceled, otherwise there's a data race.

**Comment by AndreasVerhoeven** [comment]
@dreampiggy we're on the same page here, I just posted my comment a few seconds after you posted yours :)

**Comment by dreampiggy** [comment]
User may also update some UI status during `transition.prepares`. So it should be checked as well as the actual `transition.animations` block.

**Comment by dreampiggy** [comment]
Can you try to fork and update the code based on this discussion to check if this solve the issue ? Maybe you can just fire PR now. :)

**Comment by AndreasVerhoeven** [comment]
I'll try to do it tonight! The biggest thing holding me back is that I'm a bit unsure how to get access to the correct operation and url, since there can be multiple operations per view?

**Comment by dreampiggy** [comment]
> I'll try to do it tonight! The biggest thing holding me back is that I'm a bit unsure how to get access to the correct operation and url, since there can be multiple operations per view?

Yes. in theory. No in practice.

Think of UIButton, you can load different image URL into different states. However, UIButton has never works well with `SDWebImageTransition` or something. Because it's hard to maintain the different state's animation.

Think of when you press highlited the button, it should immediatelly dismiss the previous animation, switch to new placeholder and loading animation for current URL; when press down, switch back.

I think you can just ignore that case and focus on single View State logic. UIButton is not designed to use with transition or animation.

**Comment by dreampiggy** [comment]
@AndreasVerhoeven Please have a try with [v5.8.4](https://github.com/SDWebImage/SDWebImage/releases/tag/5.8.4) version.

**Comment by AndreasVerhoeven** [comment]
@dreampiggy This seem to work great now! Thanks for fixing this, @kinarobin !
