### ISSUE TITLE
Memory leak issue with GIF image.

### ISSUE THREAD

**Issue by harryraturi** [SDWebImage/SDWebImage#3013]
### Issue Info
 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 13.3
 SDWebImage Version      | pod 'SDWebImage', '~> 5.0'
 Integration Method      | e.g. cocoa pod
 Xcode Version           | e.g. Xcode 11 

### Issue Description and Steps

Hi Concern,
I'm facing some memory issue whenever I'm downloading the '*.gif' image. Below is the sample line of code I'm using in my application also sharing the sample url for testing purpose.

Sample code:
[[SDWebImageManager sharedManager] loadImageWithURL:[NSURL URLWithString:@"https://www.google.co.in/logos/doodles/2020/stay-and-play-at-home-with-popular-past-google-doodles-hip-hop-2017-6753651837108774-law.gif"] options:0 progress:nil completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, SDImageCacheType cacheType, BOOL finished, NSURL * _Nullable imageURL) {
                                    
}];

Sample URL: 
https://www.google.co.in/logos/doodles/2020/stay-and-play-at-home-with-popular-past-google-doodles-hip-hop-2017-6753651837108774-law.gif

I'm waiting for you reply.

Thanks,
Harish.

**Comment by dreampiggy** [comment]
I don't see any **Memory Leak** from your example.

Provide your Instruments profile to show this ?

**Comment by dreampiggy** [comment]
Check [wiki](https://github.com/rs/SDWebImage/wiki/Common-Problems) again about the Large Animated Image optimization. We already supports many solution like [SDAnimatedImageView](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50)
