### ISSUE TITLE
Resize UIImageView with transition and placeholder

### ISSUE THREAD

**Issue by internalG** [SDWebImage/SDWebImage#3014]
The UIImageView has a fixed size placeholder to show different ratio images to download. I have applied the fadeTransition good. But I can't find the callback to change the size of UIImageView correctly. It seems it should be time between the new image replacing the placeholder, or just before the transition starts? TIA.

**Comment by dreampiggy** [comment]
Didn't you see that `prepareBlock` in SDWebImageTransition ?

**Comment by internalG** [comment]
OK, I'm trying it.

**Comment by internalG** [comment]
prepares block is only working for downloading. So I'm back to use completion block. The sequence may be wrong but hard to notice.

**Comment by dreampiggy** [comment]
> prepares block is only working for downloading

This is wrong. The `prepareBlock` is called whatever image from cache or network. Check you code again.

If you find this behavoir not work as expected, it's a bug and please try to describe this again, we will provide the fix.

**Comment by internalG** [comment]
OK. Current prepares block also makes me confused before checking detail code. The only prepares block is in transition class, and can be forced by SDWebImageForceTransition v4.x.
SDWebImageTransitionPreparesBlock prepares

The prepares block is never called if the user doesn't want transition for cached images. It could be more useful to move this block out of transition, so that all kinds of images get the prepare calls without transition dependency.

**Comment by dreampiggy** [comment]
> The prepares block is never called if the user doesn't want transition for cached images. It could be more useful to move this block out of transition, so that all kinds of images get the prepare calls without transition dependency.

For this propose, you'd better use the `setImageBlock` in `UIView+WebCache.h`.

Both of APIs designed for matching different user's use case and demand, so they re not always replacable.

**Comment by dreampiggy** [comment]
Currently there are no place to add a `Extra Prepare Block`, because:

1. If you need extra animation transition, go to use `SDWebImageTransition`
2. If you need highly custom set image process, go to use `setImageBlock`
3. If you need some post-set-image process, like trace or log, error handle, go to use `completionBlock`.

**Comment by dreampiggy** [comment]
And even for history compatiblity and hack, if:

4. If you need some post-set-image but sometimes need to set image yourself (hack code before 5.x's transformer, like image resize), you can use `SDWebImageAvoidSetImage` + `completionBlock` to set by yourself and do process.

**Comment by internalG** [comment]
Thanks. That's fine. Closed. Our discussion should help others too.
