### ISSUE TITLE
How to check if a larger size image is already cached?

### ISSUE THREAD

**Issue by ferologics** [SDWebImage/SDWebImage#3019]
### Problem statement

I'm working on a project where a same kind of an image has varying sizes.
I would like to know how to go about checking if a larger size image is already cached.

### Context

If there is a larger image, I would transform the image in to a smaller one (that would also be cached later). This transformed image would have a different cache key (because the transformer is appending its key). If a larger image is not available then I would modify the request url to contain the larger size (I'm using [imgix](https://www.imgix.com)). I can implement my own `SDWebImageCacheKeyFilter` to make sure that the keys are generated correctly for transformed images.

### Possible solution

The only possible way that I see is by putting the size in URL and checking per cache key across all possible sizes like so:
```swift
let sizes = 0 ... 375 // <- up to the max device width
for size in sizes {
    let url = URL(string: urlString + size)
    let cacheKey = SDWebImageManager.shared.cacheKey(for: url)
    let isCached = SDImageCache.shared.diskImageDataExists(withKey: cacheKey)
    print(isCached)
}
```
### Optimizations and overrides

I'm thinking about using the `SDWebImageOptions` and `SDWebImageContextOption` to achieve this:

1. Use the `fromCacheOnly` option when the larger image is cached. 
(Not sure if this makes much of a difference... ?)
2. Add a `SDImageTransformer` context option when a larger image is available.
3. Use the `SDWebImageCacheKeyFilter` to map the cache keys to their respective sizes.

Are there any other optimizations that I could do to shave off some time before image is displayed?

### Expectation

Ultimately I would want to retrieve the larger image from cache, then scale it down to the smaller width without the need to fetch a new image of a smaller size from the server. Ideally the smaller scaled images would then also be cached and ready for reuse on the next `sd_setImage`.

### Concerns

How expensive is it to check if the image data exists?
Have I missed any API that already achieves this?

**Comment by dreampiggy** [comment]
Hi.

Didn't you see SDWebImage 5.8.0's new feature ? The original cache from transformer. It does what you do. See: https://github.com/SDWebImage/SDWebImage/releases/tag/5.8.0

PR: #2992

Use `[.orignalStoreCacheType: SDImageCacheType.all.rawValue, .originalQueryCacheType: SDImageCacheType.all.rawValue]`

Previsoully this cause some discusssion and I never implments it.

**Comment by ferologics** [comment]
Okay, that's great. However it's more tricky than that. I'm not only trying to transform the larger image in to a smaller one. I'm also trying to fetch a smaller image.

I have two different `URL` strings that fetch the image at different width? Notice the `?w=` parameter.

1) of width `375`
`"https://images.imgix.net/6WkXnsvxgAiajyhBLLhrJu-thumbnailMedia-1584524188991.jpg?w=375&dpr=3&q=50"`
2) of width `150`
`"https://images.imgix.net/6WkXnsvxgAiajyhBLLhrJu-thumbnailMedia-1584524188991.jpg?w=150&dpr=3&q=50"`

In the case of the second URL the cache would miss for a larger image and it would fetch a smaller one. Secondly it would 

I read the source code of how the `SDWebImageCacheKeyFilter` and `SDImageTransformer` key generation interacts, and it looks like I wouldn't be able to cache the new image with the key that I would like to. I hoped that the cache key filter would override the transformer appended key, but this is not true.

My point is to cache the `150` width transformed image with the 2nd URL cache key format. Not with a format of `"https://images.imgix.net/6WkXnsvxgAiajyhBLLhrJu-thumbnailMedia-1584524188991.jpg?w=375&dpr=3&q=50"` followed by appended `-WidthTransformer(150)`. This lets me plug in a valid URL that fetches a smaller image if a larger one is not cached.

Plus, to find the larger image I would have to modify the URL and query the cache manually by appending the transformer key. I guess I should consider implementing my own abstraction for the purpose of maintaining a record of all cached image sizes for a specific URL.

**Comment by dreampiggy** [comment]
> I hoped that the cache key filter would override the transformer appended key, but this is not true.

Emm...This sounds that the transformer and cache key design focus on the root concept:

The original image and transformed image is happended on client, but not server via differnt URLs.

Can you try to drop the transformer, and implements the custom cache seriliazer logic by your own ? From the description from you, I found that seems current SD's design for customization does not provide the support for this.

If this feature is a common use case, we can add new APIs which focus on this use case ?

**Comment by ferologics** [comment]
I ended up using the image cache key filter and wrote my own logic to check for the largest cached width.

Everything seems to work as expected (transforming and caching), except when a smaller image is cached and I want to fetch a larger one. The result is that **the image set on the larger view is very low quality for the first time, but the second time it actually uses the correct image.**

I use the `refreshCached` and `fromLoaderOnly` options.

Is there anything else that I should do when I try to refresh a cached image? I read some documentation and came across:
```swift
/**
 A `UIImage` instance from `SDWebImageManager` when you specify `SDWebImageRefreshCached` and image cache hit.
 This can be a hint for image loader to load the image from network and refresh the image from remote location if needed. If the image from remote location does not change, you should call the completion with `SDWebImageErrorCacheNotModified` error. (UIImage)
 @note If you don't implement `SDWebImageRefreshCached` support, you do not need to care abot this context option.
 */
public static let loaderCachedImage: SDWebImageContextOption
```
Is this relevant?

**Comment by dreampiggy** [comment]
Hi.

After revisit your comments, I found a little confused about your **Designed Behavior** or feature request.

> The result is that the image set on the larger view is very low quality for the first time, but the second time it actually uses the correct image.

Does this what you want ? For example, I want to query the `w=300` URL, but a `w=150` image is already cached,  I want to get that 150px image, but still want to request the 300px image at the same time.

> If there is a larger image, I would transform the image in to a smaller one (that would also be cached later). This transformed image would have a different cache key (because the transformer is appending its key). If a larger image is not available then I would modify the request url to contain the larger size (I'm using imgix).

This feel strange for me. What about just query the large 300px image via `w=300` URL with 150px transformer, it it get cached it will return immediately.  If not cached, query the full 300 px and do transform on client side code, also, you can keep both 300px and 150px image into cache as well (See the both `storeCacheType` and `originalStoreCacheType` two options.)

The only difference between this and your behavior, is whether to request server:
1. `w=300` once + `w=150` once (what you want)
2. `w=300` once (what using the case I talk above)

**Comment by dreampiggy** [comment]
And, if you really want, you can just ignore the `SDWebImageManager`, use `SDImageCache` and `SDWebImageDownloader` to build your logic. We have the following features which sounds match the logic you want:

1. Cache to check whether original cache exists, whether transformed cache exist(use `SDTransformedKeyForKey`)
2. Download the original image, downloader does not apply any transformer, so it's safe.
3. Transformer can be used standalone, you can call the transformer after you query the full image.
4. Store the cache with your own designed cache key. Which have no relationship with any URL. You can custom any cache key.

You can try to write some pseudocode for your designed behavior to check which of features current SDWebImage lack of.

**Comment by ferologics** [comment]
Hey, so regarding this:

> Does this what you want ? For example, I want to query the w=300 URL, but a w=150 image is already cached, I want to get that 150px image, but still want to request the 300px image at the same time.

It doesn't, because it looks like there's a bug where sometimes it's not setting the 300px image, as if something failed inside SDWebImage, and I get a 150px low resolution image instead.

The logic is something like
```swift
if anImageIsCached { // 150px image is cached
  if cachedImageIsLarger { // false
    transformImageWidth(...) // scale image down
    setOriginCacheType(...) // set cache query and store type
  } else {
    // the cached image must be therefore be smaller (150px)
    options.insert(.refreshCached) // refresh the 150px image with the 300px
  }
}
```

My point is that when I set `refreshCached` and the image is fetched at 300px **it isn't replaced after it's downloaded, and it stays the 150px image**.

**Comment by ferologics** [comment]
Is there a way to force the manager to use the downloaded image?

**Comment by ferologics** [comment]
I had to manually delete the cached image to make it request the larger image. The `.refreshCached` option works sometimes, but not reliably.

**Comment by dreampiggy** [comment]
Don't use SDWebImageManager. Use SDWebImageDownloader directly.

If you really want to force download, use `.fromLoaderOnly`

**Comment by dreampiggy** [comment]
Have this issue (or feature request) been solved by yourself ?

**Comment by ferologics** [comment]
As I said, the SDWebImage `refreshCached` option is not working as intended. The smaller image that is used as a thumbnail while the larger image is fetched is not always refreshed for the larger image. Setting `fromLoaderOnly` or other overrides didn’t have an effect. What I had to do is literally remove the smaller image from the cache. That’s what solved my issue.

**Comment by dreampiggy** [comment]
> The smaller image that is used as a thumbnail while the larger image is fetched is not always refreshed for the larger image. Setting fromLoaderOnly or other overrides didn’t have an effect

Your description sounds like a bug. Not a feature.

Any detail demo, or PR is welcomed.
