### ISSUE TITLE
Performance lags on iPhone X and above

### ISSUE THREAD

**Issue by mrousavy** [SDWebImage/SDWebImage#3020]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | any (13.5)
 SDWebImage Version      | ?
 Integration Method      | cocoapods
 Xcode Version           | /
 Repro rate              | all the time (100%)
 Repro with our demo prj | no
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Disclaimer: I am using **React Native** with some shared-element navigation logic (like the app store app-of-the-day animation) and the [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image) library (which is a wrapper around **SDWebImage** on iOS).

When navigating from screen to screen with Image components, there are very noticeable performance lags/frame drops/micro stutters in the navigation animation. The issues only appear on newer iPhones, like the iPhone X, iPhone 11, iPhone 11 Pro and so on. On my iPhone 8 I don't see no stutters whatsoever.

There is an issue opened in the fast-image repository here: https://github.com/DylanVann/react-native-fast-image/issues/605, but since the repository has been silent for some time now I've been looking into this issue myself to see if it's the react-native wrapper's fault (`react-native-fast-image` library), or if it's caused by the SDWebImage component itself.

I've been testing this issue myself, but since I only have access to an iPhone 8 right now, I can't reproduce the bug.

Has anyone been able to reproduce this bug?

**Comment by dreampiggy** [comment]
iPhone X above use the new arm64e chip. But I doubt this issue have anything related to that, since that's a low-level changes.

Can you run some Profiler like Instruments, or some tools from React Native platform to see the problem ? Take a trace file to let us or react-native-fast-image author to analysis.
