### ISSUE TITLE
load some gif Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by Lee0820** [SDWebImage/SDWebImage#3021]
Platform Name           iOS
 Platform Version       13.4.1
 SDWebImage Version     5.8.0
 Xcode Version           Xcode 11.4

when i load some gif, number 10--20, memory 1.3G, how to slove this

**Comment by dreampiggy** [comment]
Use SDAnimatedImageView + SDAnimatedImage, but not UIImage based animation, which need load all frames into RAM.

See more: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50

**Comment by Lee0820** [comment]
I have no idea whether the format of the image is gif or png. You mean I should use all SDAnimatedImageView?

**Comment by dreampiggy** [comment]
Use SDAnimatedImageView have no sad effect.

If you do not want Animation at all, use `.decodeFirstFrameOnly` option.

You can do this in the options processor as well, which can let you filter some URLs to disable animated image, some to allows animated image. See wiki about usage.

**Comment by Lee0820** [comment]
I changed UIImageView to SDAnimatedImageView, but the memory is still very high.
SDAnimatedImageView *imageView = [SDAnimatedImageView new];
[imageView sd_setImageWithURL:url];

**Comment by dreampiggy** [comment]
Run on real device.

SDAnimatedImageView use a algorithm to detech the `Safe memory`, when you run on Simulator, you have 8GM of your Mac RAM, not what's real iPhone have.

See more in wiki again, or comments in code about `SDAnimatedImageView.maxBufferSize`.

And, if you share one URL into both SDAnimatedImageView and UIImageView, it will still load the UIImage animated image into memory. You can disable any animation on UIImageView using something like this:

```swift
SDWebImageManager.shared.optionsProcessor = SDWebImageOptionsProcessor() { url, options, context in
    var mutableOptions = options
    if let context = context, let _ = context[.animatedImageClass] {
        // Check `SDAnimatedImageView`
    } else {
        mutableOptions.insert(.decodeFirstFrameOnly)
    }
    return SDWebImageOptionsResult(options: mutableOptions, context: context)
}
```

Note: All of these performance tip already talked in the wiki.
