### ISSUE TITLE
Share cache with app extension

### ISSUE THREAD

**Issue by guidev** [SDWebImage/SDWebImage#3022]
Hello,

what would be the best way to share the disk cache with an app extension?

I usually use this method to access a shared folder: 

`FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.company.app")?.appendingPathComponent("file.txt")
`

I've read the documentation at https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-cache-50, however, it's still not clear to me what's the easiest way to just change the path for the default cache. 

Ideally, this new disk cache should be used by default by all SDWebImage (loader, prefetcher, etc...)

Thanks

**Comment by dreampiggy** [comment]
@guidev  The disk cache path is initialized during `init` method of `SDImageCache`, but not `SDImageCacheConfig`.

So in theory, you can not custom the shared cache path. And it should not do so.

I suggest you use the [SDImageCache.additionalCachePathBlock](https://sdwebimage.github.io/SDWebImage/Classes/SDImageCache.html#/c:objc(cs)SDImageCache(py)additionalCachePathBlock) this API. This is a block you can return the extra cache path. In this block you return that container group path.

Can this solve your problem ?
