### ISSUE TITLE
show issue in log 

### ISSUE THREAD

**Issue by dverdugo85** [SDWebImage/SDWebImage#3024]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 13.4 
 SDWebImage Version      | e.g. 5.5.2 
 Integration Method      | e.g. swift package
 Xcode Version           | e.g. Xcode 11.4.1
 Repro rate              | e.g. all the time (100%) 
 Repro with our demo prj | e.g. does it happen with our demo project? no
 Demo project link      I working in the apps

### Issue Description and Steps
when compile in simulator for iphone show this log....

 Class SDImageCacheConfig is implemented in both /Users/dverdugo/Library/Developer/CoreSimulator/Devices/B7E3961A-06EB-44C9-991E-983C3C602DFD/data/Containers/Bundle/Application/A7743FE5-BDF5-4A42-9054-A937878D2E59/Bimbask.app/Frameworks/SDWebImage.framework/SDWebImage (0x10b1fd9f8) and /Users/dverdugo/Library/Developer/CoreSimulator/Devices/B7E3961A-06EB-44C9-991E-983C3C602DFD/data/Containers/Bundle/Application/A7743FE5-BDF5-4A42-9054-A937878D2E59/Bimbask.app/Bimbask (0x1090d05b8). One of the two will be used. Which one is undefined.
objc[11634]: Class SDMemoryCache is implemented in both /Users/dverdugo/Library/Developer/CoreSimulator/Devices/B7E3961A-06EB-44C9-991E-983C3C602DFD/data/Containers/Bundle/Application/A7743FE5-BDF5-4A42-9054-A937878D2E59/Bimbask.app/Frameworks/SDWebImage.framework/SDWebImage (0x10b1fd958) and /Users/dverdugo/Library/Developer/CoreSimulator/Devices/B7E3961A-06EB-44C9-991E-983C3C602DFD/data/Containers/Bundle/Application/A7743FE5-BDF5-4A42-9054-A937878D2E59/Bimbask.app/Bimbask (0x1090d0bf8). One of the two will be used. Which one is undefined.

**Comment by dreampiggy** [comment]
You link SDWebImage into both Dynamic Framework and Static Library (which embed in your App executable).

If you use cocoapods, try pod deintegrate and re install, clean to solve this.

**Comment by dverdugo85** [comment]
That solved problem,  install from podfile, not swiftpackage! Regards!!
