### ISSUE TITLE
[Table view scroll lagging when using SDWebImage]

### ISSUE THREAD

**Issue by VietNamBookingApp** [SDWebImage/SDWebImage#3028]
Dear. admin

Table view scroll lagging when using SDWebImage

Can you help me?

Thanks Admin

**Comment by LivyNN** [comment]
Use SDWebImagePrefetcher to prefetch some forward image while scrolling.

**Comment by dreampiggy** [comment]
Show some demo code about this ?

If you load too much of Animated Image or Vector Images, you can opt-in with our wiki's FAQ: https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#optimization-for-large-images
