### ISSUE TITLE
SDAnimatedImage GIF Normalization

### ISSUE THREAD

**Issue by JordanMcCulloch** [SDWebImage/SDWebImage#3032]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 9.3+ 
 SDWebImage Version      | 5.8.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.5
 Language Version           | Swift 5.0

### Issue Description and Steps

- I am currently successfully extracting the GIF 'animatedImageData()' from SDAnimatedImage and saving it to my cloud service provider (Google Cloud Storage).

- Using 'sd_setImage()' on a SDAnimatedImageView successfully loads the saved GIF 'animatedImageData()' from the cloud storage URL and animates it correctly. 

In order to save space on the cloud provider, the client's phone, and to speed up the loading of the GIFs I would like to normalize the GIF before upload by both resizing the SDAnimatedImage GIF and compress its data by reducing its quality (similar to UIImage '.jpegData(compressionQuality:)' )

1) **Resize**: I have tried `.sd_resizedImage(with: <#T##CGSize#>, scaleMode: <#T##SDImageScaleMode#>)`on the SDAnimatedImage but this results in only the first frame of the GIF being saved, turning it into a static image. 

2) **Compression**: I have tried `sd_imageData(as: <#T##SDImageFormat#>, compressionQuality: <#T##Double#>) `on the SDAnimatedImage but this also results in only the first frame of the GIF being saved, turning it into a static image. 

==> What is the recommended way to resize and then compress a SDAnimatedImage to maintain the GIF frames so that it may animate in an SDAnimatedImageView? Thank you!

**Comment by dreampiggy** [comment]
Current the encoding system, does not know `SDAnimatedImage`, this is the problem.

Because it based on simple assumtation:

If you need GIF data, just grab `SDAnimatedImage.animatedImageData`.

So, it does not consider `SDAnimatedImage` can be re-encoding.

**Comment by dreampiggy** [comment]
For temp workaround, you can grab each of `SDAnimatedImage`'s frame, into the `UIImage animatedImages`, using the API we provide:

https://sdwebimage.github.io/SDWebImage/Classes/SDImageCoderHelper.html#/c:objc(cs)SDImageCoderHelper(cm)animatedImageWithFrames:

Then feed this `UIAnimatedImage` into the encoder and change the compression quality.

Sample code:

```objective-c
    SDAnimatedImage *animatedImage = nil;
    NSMutableArray<SDImageFrame *> *frames = [NSMutableArray array];
    for (size_t i = 0; i < animatedImage.animatedImageFrameCount; i++) {
        UIImage *image = [animatedImage animatedImageFrameAtIndex:i];
        NSTimeInterval duration = [animatedImage animatedImageDurationAtIndex:i];
        SDImageFrame *frame = [SDImageFrame frameWithImage:image duration:duration];
        [frames addObject:frame];
    }
    UIImage *uiAnimatedImage = [SDImageCoderHelper animatedImageWithFrames:frames];
    NSData *encodedGIFData = [uiAnimatedImage sd_imageDataAsFormat:SDImageFormatGIF compressionQuality:0.5];
```

**Comment by JordanMcCulloch** [comment]
Thank you so much! This solution also allows for the use of other coders like SDImageWebPCoder to convert the GIF's 'uiAnimatedImage' to WebP using (example in Swift):

`let encodedWebPData: Data = SDImageWebPCoder.shared.encodedData(with: uiAnimatedImage, format: .webP, options: [ SDImageCoderOption.encodeCompressionQuality: 0.5, SDImageCoderOption.encodeMaxPixelSize: normalizedSize])`

**Comment by dreampiggy** [comment]
The convenient API now supports encoding SDAnimatedImage, available in [v5.8.3](https://github.com/SDWebImage/SDWebImage/releases/tag/5.8.3)

**Comment by dreampiggy** [comment]
In v6.0.0, the new `SDAnimatedImageEncoder` protocol will take care of animated image. And the old `SDImageCoder`'s `encodedDataWithImage:` API will no longer supports animation.

**Comment by DanielZanchi** [comment]
@dreampiggy 
What is the faster way to convert a GIF data to webP data? 
I also would need to compress this data to a max size in KB.

**Comment by dreampiggy** [comment]
Currently there are no `Transcode` built-in way.

If you use pure SDWebImage, you need:

1. Load the GIF into full memory
```
```

**Comment by dreampiggy** [comment]
However, I think this will cause some memory peak because load all frames will consume more memory. This is safe for small GIF but not huge GIF (like 400+frames, each frame is 1000x1000)

For huge GIF transcode to WebP, we need to write transcode hand by hand or introduce the similiar API like Apple's ImageIO

```
CGImageAddImageFromSource(source, index, options)
````

**Comment by DanielZanchi** [comment]
@dreampiggy  Thanks for the reply. 
The GIFs I am using are not very big and don't have many frames. 
But the conversion I was already doing with the first method you posted is quite slow. I will try this second approach if you think it could be faster...

**Comment by dreampiggy** [comment]
> But the conversion I was already doing with the first method you posted is quite slow

Which cause the slow, the "encoding to WebP" or "decoding frames from GIF"

**Comment by dreampiggy** [comment]
And actually you can try the similar way, but I don't think there are huge differences on CPU performance (only RAM peak)

```
guard let provider = SDImageGIFCoder(data: GIFData) else {return}
let loopCount = provider.animatedImageLoopCount ?? 0

var frames: [SDImageFrame] = []
for (index) in provider.animatedImageFrameCount {
    let image = provider.animatedImageFrame(at: index)
    let duration = provider.animatedImageDuration(at: index)
    let frame = SDImageFrame(image: image, duration: duration)
    // feed frames
    frames.append(frame)
}
// output
let webpData = SDImageWebPCoder.shared.encodedData(with: frames, loopCount: loopCount, options: [.compressionQuality: 0])
```
