### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by xuepan12** [SDWebImage/SDWebImage#3034]
http://image2.njf2016.com/lhN_nmm3wEeknpAN09I_D1mdHpZl

加载这个图片    内存直接飙到任何机型 内存峰值  然后闪退

版本 5.几来着   忘了~

**Comment by dreampiggy** [comment]
See wiki:
https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#reduce-image-memory-usage-by-resolution-and-channel

For your case, you original image have more than 10000*10000 pixels, you can only use the thumbnail decoding, or pre-scale down the image pixel size in the server (not client) to do this.

**Comment by dreampiggy** [comment]
See the example in SDWebImage: 
https://github.com/SDWebImage/SDWebImage/blob/5.8.0/Examples/SDWebImage%20Demo/MasterViewController.m#L121
