### ISSUE TITLE
Why SD design muti cache and the sence

### ISSUE THREAD

**Issue by stackJolin** [SDWebImage/SDWebImage#3035]
Why SD design muti cache and the sence?

NSMutableArray<id<SDImageCache>> *_imageCaches;

**Comment by dreampiggy** [comment]
User request from #1702.
PR proposal: #2955 
You can see original feature request to learn background.

**Comment by dreampiggy** [comment]
For architecture design, there are already wiki in readme:

https://github.com/SDWebImage/SDWebImage/wiki/5.6-Code-Architecture-Analysis

**Comment by stackJolin** [comment]
> For architecture design, there are already wiki in readme:
> 
> https://github.com/SDWebImage/SDWebImage/wiki/5.6-Code-Architecture-Analysis

Thanks!
