### ISSUE TITLE
SDAnimatedImageView doesn't render in iOS 14 Beta 1

### ISSUE THREAD

**Issue by cyanzhong** [SDWebImage/SDWebImage#3040]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.0
 SDWebImage Version      | 5.8.1
 Integration Method      | CocoaPods
 Xcode Version           | 12.0 beta (12A6159)
 Repro rate              | 100%

### Issue Description and Steps

This doesn't render anything:

```objc
SDAnimatedImageView *imageView = [SDAnimatedImageView new];
imageView.image = [UIImage systemImageNamed:@"trash"];
imageView.backgroundColor = [UIColor redColor];
imageView.frame = CGRectMake(100, 100, 100, 100);
[self.view addSubview:imageView];
```

UIImageView works fine:

```objc
UIImageView *imageView = [UIImageView new];
imageView.image = [UIImage systemImageNamed:@"trash"];
imageView.backgroundColor = [UIColor redColor];
imageView.frame = CGRectMake(100, 100, 100, 100);
[self.view addSubview:imageView];
```

Building the repro code with Xcode 11 works fine as well.

The root cause might be `currentFrame` is nil, and `displayLayer:` doesn't do anything.

**Comment by dreampiggy** [comment]
@cyanzhong This effect only custom codec like WebP. For `SDAnimatedImageIOCoder` like GIF/APNG, it does not get effected.

This is not related to that `currentFrame` is nil. The `SDAnimatedImageView.image != nil`, however, UIKit does not render the CGImage.

![image](https://user-images.githubusercontent.com/6919743/85375658-35618b00-b569-11ea-865a-aea059a93be9.png)


Seems some hack from Apple UIKit team that break the `UIImage` subclass to work.

**Comment by dreampiggy** [comment]
Seems some break change to that `displayLayer:` delegate method.

on iOS 13: If we override this, UIKit will render the `UIImageView.image` itself before calling this method. So even if `self.currentFrame == nil`, the `UIImageView.image` get rendered.
on iOS 14: UIKit no longer render anything if you override that `displayLayer:` method. We can have a backup to render `layer.contents` for this case by ourself.

**Comment by dreampiggy** [comment]
Patch available: #

**Comment by lvyuqiang** [comment]
We also meet it ,  waiting for  apple fix it

**Comment by dreampiggy** [comment]
Release v5.9.2

**Comment by zzivkovi** [comment]
The way it works in iOS 14 is actually correct because this implementation doesn't call `[super displayLayer: layer];` in the method override.

Fix should be:
```Objective-C
- (void)displayLayer:(CALayer *)layer
{
    [super displayLayer: layer];

    UIImage *currentFrame = self.frame;
    ...
```

**Comment by y500** [comment]
mark

**Comment by pongponglau** [comment]
I am using the latest version 5.9.4. However, i still encounter the same error, no web image can be shown in SDAnimatedImageVIew in iOS 14. What can i do to fix this issue? Many thanks for your advice.
