### ISSUE TITLE
Feature: Supports WebP/Animated WebP nativally for iOS 14/macOS 11/tvOS 14/watchOS 7 without extra libwebp dependency

### ISSUE THREAD

**Issue by dreampiggy** [SDWebImage/SDWebImage#3041]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
### Issue Description and Steps

Image/IO in iOS 14/macOS 14/tvOS 11/watchOS 7 supports WebP (including Animated WebP) nativally. See full changelog: http://codeworkshop.net/objc-diff/sdkdiffs/ios/14.0/ImageIO.html

It's easy and right time to drop the libwebp for user who set minimun deployment target version to iOS 14+.

ImageIO use hardware-accelerated codec instead of that libwebp (which is written in C and run on CPU), is much faster than the current WebP codecs on iOS 13.

### Design

Introduce the new subclass for AWebP: `SDImageAWebPCoder`. The `SDImageWebPCoder` naming already been taken by another codec repo maintained by us. So this a new naming.

In the future (2 Years later ?), that [SDWebImageWebPCoder](https://github.com/SDWebImage/SDWebImageWebPCoder) repo may be deprecated.

Note: For Static WebP, you don't need to add `SDImageAWebPCoder`, the `SDImageIOCoder` already handle those cases.

### Usage

For iOS 14+ user, you can use avaiable check to use the native WebP support. For iOS 13-, use the fallback version of libwebp support.

```objective-c
if (@available(iOS 14, macOS 11, tvOS 14, watchOS 7, *)) {
    [SDImageCodersManager.sharedManager addCoder:SDImageAWebPCoder.sharedCoder];
} else {
    [SDImageCodersManager.sharedManager addCoder:SDImageWebPCoder.sharedCoder];
}
```

**Comment by caoping** [comment]
Great News

**Comment by dreampiggy** [comment]
Seems Apple's ImageIO framework already vendor the libwebp source code:

![image](https://user-images.githubusercontent.com/6919743/86229226-fe6f2300-bbc1-11ea-92d4-007c0f5fe164.png)

Mostly, if the hardware codec does not support VP9, it will use software codec.

**Comment by dreampiggy** [comment]
Bad news: confirms that current iOS 14 Beta, does not supports WebP Encoding.
