### ISSUE TITLE
Image view flickering after latest pod update

### ISSUE THREAD

**Issue by svwalekar** [SDWebImage/SDWebImage#3042]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | iOS 13.3
 SDWebImage Version      | SDWebImage (5.8.0)
 Integration Method      | cocoa pods
 Xcode Version           | Xcode 11.3.1 (11C505)
 Repro rate              | all the time (80%)
 Repro with our demo prj | NOT SURE

### Issue Description and Steps
Updated from SDWebImage (4.4.8) to SDWebImage (5.8.0)
Collection view cell containing image view always flickering after the update.

**Comment by kinarobin** [comment]
Have you ever used imageTransition?

Can you provide more information about using SDWebImage?

**Comment by svwalekar** [comment]
Never used image transition.
the flickering problem has started just after a recent pod update
utilizing the SDWebImage using the following function only. 

public extension UIImageView {
       
    func setImage(url:String, placeHolder: UIImage? = nil, completed: SDExternalCompletionBlock? = nil) {
        var strUrl : String? = url
        if url.contains(" ") {
            strUrl = url.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)
        }
        guard let urlString = strUrl,
            let imageUrl = URL(string: urlString) else {
                self.image = placeHolder
                return
        }
        
        if let img = SDImageCache.shared().imageFromDiskCache(forKey: keyNameFromURL(url: url)) {
            self.image = img
        }else {
            sd_setImage(with: imageUrl, placeholderImage: placeHolder, options: [SDWebImageOptions.queryDiskSync, .retryFailed]) { (image, error, cacheType, fileUrl) in
                if image != nil {
                    DispatchQueue.main.async {
                        self.image = image
                    }
                }
                
                completed?(image,error,cacheType,fileUrl)
                SDImageCache.shared().store(image, forKey: self.keyNameFromURL(url: fileUrl?.path ?? ""), toDisk: true, completion: {})
            }
        }
    }
}

**Comment by svwalekar** [comment]
``

**Comment by svwalekar** [comment]
mistakenly closed

**Comment by kinarobin** [comment]
@svwalekar  

After SD query or downloaded an image, the image will be automatically set to ImageView, So this code is unnecessary.  This is also the cause of flicker, which in next runloop to reset image.
```objc
if image != nil {
   DispatchQueue.main.async {
      self.image = image
   }
 }
```

From your code, I suggest you use `SDWebImageManager` to query or download images, and then process the custom logic in the callback block. Hope this helps :)

**Comment by dreampiggy** [comment]
`DispatchQueue.main.async`

This cause you setup the image into **next runloop**.
However, current runloop will apply `imageView.image = nil`.

So, as UIKit, the render engine will display the blank image view firstly, then replace with the final image, cause a `flash`.

For your case, you should use `sd_internalSetImage:setImageBlock` with that `setImageBlock` to set the image. Remember, don't use dispatch to jump to next runloop.

**Comment by svwalekar** [comment]
thank you guys for help

**Comment by svwalekar** [comment]
Removed this code ...still not working 

if image != nil {
   DispatchQueue.main.async {
      self.image = image
   }
 }

**Comment by soondl** [comment]
Flickering caused because when call sd_setImage with SDWebImageOptions.queryDiskSync,
image is setup into next runloop. I fixed it in https://github.com/SDWebImage/SDWebImage/pull/3327 
please take a look
