### ISSUE TITLE
Issue with URL Encoding 

### ISSUE THREAD

**Issue by racer1988** [SDWebImage/SDWebImage#3044]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | last
 SDWebImage Version      | 5.8.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11
 Repro rate              | all the time (100%)

### Issue Description and Steps

SDWebImage does not download encoded URLs like:

https://upload.wikimedia.org/wikipedia/commons/4/41/Bahnhof_Berlin_Friedrichstraße_-_Detailansicht.jpg

### expectation:

URLs are encoded automatically

**Comment by kinarobin** [comment]
Oh, Maybe you should like this:
```objc
NSString *string = @"https://upload.wikimedia.org/wikipedia/commons/4/41/Bahnhof_Berlin_Friedrichstraße_-_Detailansicht.jpg";
NSString *URLString = [string stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
```

**Comment by racer1988** [comment]
Yes of course I can encode it myself. 

But then if a URL contains already encoding I need to be sure I don’t re-encode it. 

All is good, but why not add this as a feature to avoid having to check for encoding each time outside the framework?

**Comment by dreampiggy** [comment]
Percent encoding is not idempotent. Which means, a URL encoded twice, is **Different** from the URL been encoded once. This is the problem.

As a framework, we don't know what the times you already encode the URL, so we can not assume anything and arbitery apply percent encoding.

See wiki: https://en.wikipedia.org/wiki/Percent-encoding, the case like that `%`

**Comment by racer1988** [comment]
Yes that was exactly my problem. 

Cause I also get URLs to open that I don’t know if they are encoded or not. 

Hence I solved it by creating a URL and encode if it fails. 

I wanted to suggest to do the same in the framework. To try to fetch images that are from unencoded url, to simplify use
