### ISSUE TITLE
Load big image crash

### ISSUE THREAD

**Issue by DkSuperMan** [SDWebImage/SDWebImage#3045]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 13.4.1
 SDWebImage Version      | e.g. 5.8.1
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 11.5
 Repro rate              | e.g. all the time (100%) 

### Issue Description and Steps
Load local image crash, the sample image url is:http://img.kailule.cn/sdwebimage_crash.jpg

[self.thumbImageView sd_setImageWithURL:fileURL]; The fileURL is local path.

Xcode Console log:Received memory pressure event 16 vm pressure 0 and print didReceiveMemoryWarning.

I guess because the image is very big. It need 1.8G memory on my simulator. So, it must crash on my iPhone11 device.

**Comment by dreampiggy** [comment]
Did you try to use the `.imageThumbnailPixelSize` to thumbnail decode the image ? Why would you always use full pixels ?

**Comment by dreampiggy** [comment]
Please see wiki before send some usage related issues...

https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#thumbnail-decoding-550

**Comment by DkSuperMan** [comment]
> Please see wiki before sending common usage related issues...There are already feature request or issues talked about this case.
> 
> https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#thumbnail-decoding-550

Thanks, before i use SDImageResizingTransformer to solve the problem.
It's my fault, I will close the issue. Thank you again.
