### ISSUE TITLE
Crash at unknown point 

### ISSUE THREAD

**Issue by MiteshiOS** [SDWebImage/SDWebImage#3049]
I have updated SDWebImage to latest version and found that it is crashing at unknown point. Attached screenshot of crash. Please check and let us know.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.15.5 
 SDWebImage Version      | 5.8.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.5
 Repro rate              | all the time (100%) 
 Repro with our demo prj | 
 Demo project link       | 
<img width="1384" alt="Screenshot 2020-07-08 at 2 13 23 PM" src="https://user-images.githubusercontent.com/17427703/86898718-b3579180-c126-11ea-9396-c1a1698bab68.png">

**Comment by dreampiggy** [comment]
repo rate : all the time (100%)?

Can you use debugger to see what's that inside `options` local variable, and what's your PNG image data ? (Provide the URL is OK)
