### ISSUE TITLE
How to change the cache directory of the sharedImageCache

### ISSUE THREAD

**Issue by Rotemy** [SDWebImage/SDWebImage#3050]
Hi all,

As iOS can spontaneously remove the cache folder it seems like a bad idea to save the cached images in the cache folder since the SDWebImage cache mechanism knows when and which image to remove.

This happens a lot to our users, where they suddenly need to redownload all the images in the app even if it an image they downloaded 5 minutes ago.

How can I change the location of the cache of the sharedImageCached? and how to migrate the current cache to the new folder?

**Comment by dreampiggy** [comment]
You can not do this currently.

You can migrate those files using the standard Foundation API via `FileManager`.

You can also migrate using the convenient API we provided [SDDiskCache.moveCacheDirectoryFrom:to:](https://sdwebimage.github.io/SDWebImage/Classes/SDDiskCache.html#/c:objc(cs)SDDiskCache(im)moveCacheDirectoryFromPath:toPath:).

**Comment by dreampiggy** [comment]
Same feature request as #3022

**Comment by Rotemy** [comment]
Thanks @dreampiggy 

So if I move the cache directory using `SDDiskCache.moveCacheDirectoryFrom(:to:).` how can I make sure that the next image will be cached in the new directory?

**Comment by dreampiggy** [comment]
Since currently you `CAN'T` change the shared cache's cache directory. You can not do this, without Swizzle the SDWebImage's own logic.

This need a feature request and implementation, which allows developer to specify the default cache's path.

However, what about, just don't use the `default` cache ? You can always change the SDWebImageManager.shared 's cache. For example:


```objecitive-c
NSString *myPath;
SDImageCache *myOwnCache = [[SDImageCache alloc] initWithNamespace:@"my" diskCacheDirectory:myPath];
SDWebImageManager.defaultImageCache = myOwnCache;
// From next, all the image query and storage happended to that `myOwnCache`
```

**Comment by Rotemy** [comment]
ok, cool! this can help. thanks.

**Comment by dreampiggy** [comment]
Need a feature request and implementation. Hopefully this does not cause any API break so we can ship with SDWebImage 5.x version. 

@SDWebImage/core Any MR proposal ?
