### ISSUE TITLE
Load the same GIF url using both SDAnimatedImageView and FLAnimatedImageView, FLA will fail.

### ISSUE THREAD

**Issue by gonghonglou** [SDWebImage/SDWebImage#3051]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 SDWebImage Version      | 5.8.3
 SDWebImageFLPlugin Version      | 0.4.0
 FLAnimatedImage Version      | 1.0.12

### Issue Description and Steps

First, load an image (gif url) with SDAnimatedImageView. Later, load the same gif url with FLAnimatedImageView, SD will fetch a SDAnimatedImage instance from memory cache (SDImageCache), FLAnimatedImageView cannot display normally. 
Because：
```objc
// FLAnimatedImageView+WebCache.m
FLAnimatedImage *animatedImage;
if ([image isKindOfClass:[SDFLAnimatedImage class]]) {
   animatedImage = ((SDFLAnimatedImage *)image).animatedImage;
}
if (animatedImage) {
   // FLAnimatedImage framework contains a bug that cause GIF been rotated if previous rendered image orientation is not Up. We have to call `setImage:` with non-nil image to reset the state. See `https://github.com/rs/SDWebImage/issues/2402`
   strongSelf.image = animatedImage.posterImage;
   strongSelf.animatedImage = animatedImage;
} else {
   strongSelf.image = image;
   strongSelf.animatedImage = nil;
}
```

Fetch the image directly from the disk cache is normal. And, first load with FLAnimatedImageView, then load with SDAnimatedImageView also is ok.

**Comment by dreampiggy** [comment]
Designed Behavior.

If you want to avoid this, have a try with [SDWebImageMatchAnimatedImageClass](https://sdwebimage.github.io/SDWebImage/Enums/SDWebImageOptions.html#/c:@E@SDWebImageOptions@SDWebImageMatchAnimatedImageClass)

And, it's not a good usage case to use `FLAnimatedImageView` && SDAnimatedImageView at the same time. FLAnimatedImage is used for 4.x backward compatible, not `A core feature we want to maintain`.

FLAnimatedImage will be removed support in 6.0.0

**Comment by gonghonglou** [comment]
Got it. And `SDWebImageMatchAnimatedImageClass` did work, thanks.
