### ISSUE TITLE
Image url is blacklisted

### ISSUE THREAD

**Issue by arslan311** [SDWebImage/SDWebImage#3059]
I am getting following error **"swift SDWebImageDomainerror - code: 1003"**,  and in console error message is **"Image url is blacklisted"**
I am using following code snippet: 

 ### func loadIMage(url: String, imageview: UIImageView) {
       
        SDWebImageManager.shared.loadImage(
            with: URL(string: url),
            options: .continueInBackground, // or .highPriority
            progress: nil,
            completed: { [weak self] (image, data, error, cacheType, finished, url) in
                guard self != nil else { return }
                if let err = error {
                    // Do something with the error
                    print(err.localizedDescription)
                    return
                }
                guard let img = image else {
                    // No image handle this error
                    return
                }
                imageview.image = img
                // Do something with image
            }
        )
    }
please help me

**Comment by dreampiggy** [comment]
See readme and wiki: https://sdwebimage.github.io/SDWebImage/Enums/SDWebImageOptions.html#/c:@E@SDWebImageOptions@SDWebImageRetryFailed

If you don't want the failed url (not 404, not client error, only about server 500) been blocked, you should use `.retryFailed`.

PS: This is one behavior I dislike. I think by default we should not apply this black list logic.
