### ISSUE TITLE
Secure code by using NSSecureCoding instead of NSCoding 

### ISSUE THREAD

**Issue by mmathewsTableau** [SDWebImage/SDWebImage#3060]
NSCoding does not verify the type of object upon deserialization and therefore is vulnerable to object substitution attacks. The code can protect itself from these attacks by using NSSecureCoding instead: https://developer.apple.com/documentation/foundation/nssecurecoding?language=objc

Various spots where NSCoding is used:
https://github.com/SDWebImage/SDWebImage/search?q=nscoding&unscoped_q=nscoding

**Comment by dreampiggy** [comment]
So, How can I determine your custom class ?

That `sd_extendedObject` is a property, which does not contains any `Class` information.

This may be a API break changes and need consideration again.

**Comment by mmathewsTableau** [comment]
Thanks for the explanation. That makes sense why you can't use NSSecureCoding there without breaking your API.

**Comment by dreampiggy** [comment]
Kept for 6.x feature request.
