### ISSUE TITLE
Request: Add lepton decompression support

### ISSUE THREAD

**Issue by StainlessStlRat** [SDWebImage/SDWebImage#3061]
It would amazing to yield these huge bandwidth savings using Lepton compression.

https://github.com/dropbox/lepton

**Comment by dreampiggy** [comment]
This looks like a JPEG Encoding tool or lib.

SDWebImage core only use Apple Image/IO framework for Image Decoding/Encoding. If you want any custom codec, just follow the toturial to create your own custom coder. We do not maintain such a custom codec (only if there are many strong requests from user, like that WebP).

See: https://github.com/SDWebImage/SDWebImage/wiki/Coder-Plugin-List
