### ISSUE TITLE
iPad上拍摄的图片加载时出现错误的旋转

### ISSUE THREAD

**Issue by SnowPuslar** [SDWebImage/SDWebImage#3062]
### New Issue Checklist

* [ √] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ √] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ √] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13.5
 SDWebImage Version      | 5.8.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11 
 Repro rate              | all the time (100%)
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps

使用场景是这样的：
1. 使用iPad在竖屏时拍摄一张图片，并上传到服务器
2. 使用 UIImageView+WebCache 中的 方法
` - (void)sd_setImageWithURL:(nullable NSURL *)url placeholderImage:(nullable UIImage *)placeholder options:(SDWebImageOptions)options completed:(nullable SDExternalCompletionBlock)completedBlock;`
去加载已经上传到服务器中的图片，其中 options 设置为  SDWebImageScaleDownLargeImages

现象：图片内容出现了不正确的向左旋转90°

可以确认：
1. 上传到服务器的图片是正常的，使用浏览器打开这张图片时显示是正常的
2. 在 SDImageIOAnimatedCoder 中的 
`+ (UIImage *)createFrameAtIndex:(NSUInteger)index source:(CGImageSourceRef)source scale:(CGFloat)scale preserveAspectRatio:(BOOL)preserveAspectRatio thumbnailSize:(CGSize)thumbnailSize options:(NSDictionary *)options;`
在该方法中可以看到，原本的图片信息中，`exifOrientation = kCGImagePropertyOrientationRight`
但是，被该方法下面的逻辑
```
if (thumbnailSize.width > 0 && thumbnailSize.height > 0) {
        if (preserveAspectRatio) {
            // kCGImageSourceCreateThumbnailWithTransform will apply EXIF transform as well, we should not apply twice
            exifOrientation = kCGImagePropertyOrientationUp;
        } else {
            // `CGImageSourceCreateThumbnailAtIndex` take only pixel dimension, if not `preserveAspectRatio`, we should manual scale to the target size
            CGImageRef scaledImageRef = [SDImageCoderHelper CGImageCreateScaled:imageRef size:thumbnailSize];
            CGImageRelease(imageRef);
            imageRef = scaledImageRef;
        }
    }
```
强制修改为 kCGImagePropertyOrientationUp
3. 将上面逻辑中的 `exifOrientation = kCGImagePropertyOrientationUp;`注释掉后，重新下载的图片恢复正常显示

**Comment by dreampiggy** [comment]
Sounds like Apple's Bug:

kCGImageSourceCreateThumbnailWithTransform: 

Whether the thumbnail should be rotated and scaled according to the orientation and pixel aspect ratio of the full image. The value of this key must be a CFBoolean value. The default value is kCFBooleanFalse.

**Comment by dreampiggy** [comment]
发一下你说的图片URL吧，经过@kinarobin 的测试，含有EXIF的图像，就算使用thumbnail decoding（SDWebImageScaleDownLargeImages本质上会转义为thumbnail decoding），也不会错误显示。那行代码是专门加的，不加会有问题。

示例URL：https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_2.jpg
你iOS设备上展示必须要和Chrome一致才是正确的

**Comment by dreampiggy** [comment]
@SnowPuslar Any news about this ?

**Comment by SnowPuslar** [comment]
https://msgimg.51vv.com/20/08/13/2ef41c1bef4a65d2f2e974866fa3facd.jpg
这是一张会有显示问题的图片

**Comment by SnowPuslar** [comment]
我用一个干净的工程（Controller中只含有两个UIImageView，通过SDWebImage 5.8.0去分别加载两张图片：[图片1](https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_2.jpg) 和 [图片2](https://msgimg.51vv.com/20/08/13/2ef41c1bef4a65d2f2e974866fa3facd.jpg)）可以简单的复现出显示上的BUG，Demo工程git地址：https://github.com/SnowPuslar/SDWebImageTestDeom.git

**Comment by dreampiggy** [comment]
确认是Bug。

出现条件是：当你的Thumbnail Pixel Size非常大，超过原图的大小，同时你的原图含有EXIF 旋转（非正常方向），即可导致imageOrientation丢失。

我测试的地方，都是用了手动自己写的Thumbnail Pixel Size，比原图小，所以没发现。

**Comment by dreampiggy** [comment]
需要修复，统一根据这个判断条件决定是否应用EXIF旋转：

`if (thumbnailSize.width == 0 || thumbnailSize.height == 0 || pixelWidth == 0 || pixelHeight == 0 || (pixelWidth <= thumbnailSize.width && pixelHeight <= thumbnailSize.height))`
