### ISSUE TITLE
Is there any way to make transition when image is loaded from disk?

### ISSUE THREAD

**Issue by 0x0c** [SDWebImage/SDWebImage#3063]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | any
 SDWebImage Version      | 5.8.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11
 Repro rate              | all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Hello, is there any way to make transition when image is loaded from disk?
Read image from disk takes time to show longer than read from memory, UIImageView shows placeholder image and no animation to show when the image is loaded from disk even if SDWebImageTransition is applied.

If there is no way to solve this issue, I'll send PR contains following changes.
https://github.com/0x0c/SDWebImage/commit/698cca3ee14abd54522dfbac2abf8992833ad2a7

**Comment by dreampiggy** [comment]
Exist API. Have a check at API docset before firing PR.

https://sdwebimage.github.io/SDWebImage/Enums/SDWebImageOptions.html#/c:@E@SDWebImageOptions@SDWebImageForceTransition

**Comment by 0x0c** [comment]
@dreampiggy Thank you!

**Comment by 0x0c** [comment]
@dreampiggy Thank you for your reply. I want to make transition when the image loaded from disk or network, not from memory.
I think `SDWebImageForceTransition` is apply transition memory and disk both.

**Comment by dreampiggy** [comment]
Sounds a new feature request 😅

**Comment by 0x0c** [comment]
OK, I send PR.

**Comment by dreampiggy** [comment]
Available in 5.9.0
