### ISSUE TITLE
Can I set a default SDWebImageContext with the Manager which will provide the default context for all operations?

### ISSUE THREAD

**Issue by CapnSpellcheck** [SDWebImage/SDWebImage#3064]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | None - API questions
 Platform Version        | None - API questions
 SDWebImage Version      | 5.7.4
 Integration Method      | cocoapods 
 Xcode Version           | None - API questions
 Repro rate              | None - API questions
 Repro with our demo prj | None - API questions
 Demo project link       | None - API questions

### Issue Description and Steps

I would like to make sure `SDWebImageContextOriginalStoreCacheType` is `SDImageCacheTypeDisk` for all use of SDWebImageManager. But I use multiple SDWebImage loading APIs, like the UIView category and the SDWebImageManager directly. And sometimes I provide explicit context dictionary.

I cannot find an API to set default context for the Manager and have the context merged with explicit context passed in for a specific call. (Explicit context settings would override default settings). Is this possible?

**Comment by dreampiggy** [comment]
The `SDWebImageContextCustomManager` does not supports recursive passthrough.

It will be removed from UIView+WebCache after we can determine the manager.

**Comment by CapnSpellcheck** [comment]
Thanks! I have used options processor. I think that is fine.
