### ISSUE TITLE
Transforming images to smaller size leaves bigger memory footprint

### ISSUE THREAD

**Issue by mralj** [SDWebImage/SDWebImage#3071]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13.6
 SDWebImage Version      | 5.7.0
 Integration Method      | cocoapods 
 Xcode Version           | 12
 Repro rate              | 100%

### Issue Description and Steps

Hello, firstly I apologize in advance if I am not understanding how SDWebImage works or if I  say smth. stupid 🙂
I have no iOS dev experience whatsoever, and I am actually using [DylanVann/react-native-fast-image](https://github.com/DylanVann/react-native-fast-image) which is  react-native "wrapper" for SDWebImage.

It's  _thin_ wrapper which inherits `SDAnimatedImageView` and in order to display image it calls `sd_setImageWithURL`. ([link on relevant code](https://github.com/DylanVann/react-native-fast-image/blob/master/ios/FastImage/FFFastImageView.m))

Here is what's troubling me, from server we are sending much larger pictures than we have  to render in mobile app. 

If I am not mistaken for each picture, allocated memory will be W x H * depth (which is probably 24).
So if I am sending from server pic which is 500 x 500, and displaying it on 100 x 100 "container", the allocated memory will still be 500 x 500 x 24 ?

If this is true, it would be best to resize image before caching it and passing it to `UIImageView`. 
I've  done this via `SDImageResizingTransformer`. 
But strangely (at least it is strange to me), memory footprint of the app actually went up, and images are visibly slower to load. 
I have done similar optimisation for Android using Glide's ` .apply(new RequestOptions().override(W, H))`, which, in my understanding, should work similarly too `SDImageResizingTransformer `. Results on Android where as expected, much smaller memory footprint, and images are rendered pretty fast :) 

Here are my code changes from [DylanVann/react-native-fast-image](https://github.com/DylanVann/react-native-fast-image/blob/master/ios/FastImage/FFFastImageView.m):

To `init` method I have added this line:

`self.transformer = [SDImageResizingTransformer transformerWithSize:CGSizeMake(100, 100) scaleMode:SDImageScaleModeFill];`

And I have added `context` to the `sd_setImageWithURL` as follows: ` context: @{SDWebImageContextImageTransformer: self.transformer}`

Clearly I am missing something, but not sure what. 
Could someone please help me out / point me in right direction 🙂?

**Comment by dreampiggy** [comment]
> So if I am sending from server pic which is 500 x 500, and displaying it on 100 x 100 "container", the allocated memory will still be 500 x 500 x 24 ?

YES.

> If this is true, it would be best to resize image before caching it and passing it to UIImageView. I've done this via SDImageResizingTransformer.

There are many ways to scale down the images pixel size. Once best solution is to use [Thumbnail Image Decoding](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#thumbnail-decoding-550). Which does not allocate 500 x 500 RAM, instead, directly allocate 100 x 100 RAM.

The `SDImageResizingTransformer` logic is: Firstly decode full image (500 x 500 RAM), then scale it down, need another 100 x 100 temp buffer. Finally release 500 x 500 RAM. This may cause a memory peak so it's not always good solution.

And, you should take aware of other code which may cache the full image as well. Each of call to `sd_setImageWithURL:` to your URL should use that transformer. Not single request, or there may cache the full image which need 500x500 RAM.

If you need central control, try with [Options Processor](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#options-processor-510), to apply global transformer based on context.


More tips at wiki: https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#optimization-for-large-images

**Comment by mralj** [comment]
Thank you very much for taking your time to explain this 🙂

I will be closing the issue since you've answered all questions I have ATM.
