### ISSUE TITLE
loadImage: returns nil data

### ISSUE THREAD

**Issue by guidev** [SDWebImage/SDWebImage#3082]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | > 12.0
 SDWebImage Version      | 5.9.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11
 Repro rate              | sometimes, haven't been able to reproduce

### Issue Description and Steps

We've noticed in our Firebase logs that sometimes `SDWebImageManager.shared.loadImage` returns an image but the data is nil. 

Unfortunately, we haven't been able to reproduce the issue ourselves but happens to quite a few users (it's out most occurring non-crashing issue on Firebase). Also, 88% of the time, the app is in background.

For our use case, we need the original data, we're using the following options: 
`[.queryMemoryData, .queryMemoryDataSync, .highPriority, .continueInBackground]
`
Our app only handles webp images using the SDImageWebPCoder.
 
`SDImageCodersManager.shared.addCoder(SDImageWebPCoder.shared)`

**Comment by dreampiggy** [comment]
`[.queryMemoryData, .queryMemoryDataSync]`

If the image is cached only in memory, not in disk (for example, your disk cache expire because of SDImageCacheConfig like diskCount, diskTime). Then this will return nil data.

Using  these combination of options does not means **If the disk data is nil, we return nothing and treat as cache miss**. What you want, is to directly call `SDImageCache` API for your use case, not `SDWebImageManager`.

**Comment by guidev** [comment]
> `[.queryMemoryData, .queryMemoryDataSync]`
> 
> If the image is cached only in memory, not in disk (for example, your disk cache expire because of `SDImageCacheConfig` like maxDiskAge, maxDiskSize). Then this will return nil data.

Why? If the image is in memory, why shouldn't I get the data also? Why does it need to be also in the disk cache?

**Comment by dreampiggy** [comment]
@guidev 
Yes. SDWebImage is a loading system focus on `Image`. Not `Image Data`.
So, we design as `Image != nil` as an success query. Not `Image != nil && Image Data != nil`.

If you always need Image Data (even Image object exist), you need low level API from own SDK. Like you talked here.

**Comment by dreampiggy** [comment]
But anyway, we can mark this as feature request. For example, your request like #2963

**Comment by guidev** [comment]
Ok, thanks.

I understand your point, however, I still feel it's counterintuitive that the completion block `SDWebImageManager.shared.loadImage` can return successfully an `UIImage`, but don't return the respective image `data`.

I also understand that fetching the image data from disk is expensive and should be avoided when not needed, but I think it would be great to add an options `SDWebImageAlwaysReturnsData`.

**Comment by dreampiggy** [comment]
> Ok, thanks.
> 
> I understand your point, however, I still feel it's counterintuitive that the completion block of `SDWebImageManager.shared.loadImage` can return successfully an `UIImage`, but doesn't return the respective image `data`.
> 
> I also understand that fetching the image data from disk is expensive and should be avoided when not needed, but I think it would be great to add an options `SDWebImageAlwaysReturnsData`.

This options already exists. See:

https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#behavior-about-asyncsync-control-for-cache
