### ISSUE TITLE
Performance issues in recent versions of SDWebImage

### ISSUE THREAD

**Issue by hansemannn** [SDWebImage/SDWebImage#3083]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.0
 SDWebImage Version      | 5.8.0+
 Integration Method      | Carthage
 Xcode Version           | Xcode 12
 Repro rate              | All the time (100%)
 Repro with our demo prj | (still validating)

### Issue Description and Steps

We noticed major performance hits since using SDWebImage 3.8.0+ on iOS 14. It seems like the image loading is blocking the UI thread, which dis not happen before. We still need to spend more time on the test cases and will update this issue accordingly then! Opening now already, so other users updating to iOS 14 can find it as well. Thanks!

**Comment by dreampiggy** [comment]
Any context, stacktrace, instruments profile result for this ? I can not get any useful information from your description to solve this performance issues...

**Comment by paulmesa** [comment]
We are experiencing a very similar issue and have pulled the following stack traces for memory that is allocated but never deallocated. We have a tableview with collection views whose cells all have downloaded images. The memory issues seemed to have started after updating `SDWebImage` for iOS14 and can be repro-ed by pushing any screen onto the stack and then popping it. Each time I do that, there are ~10 more allocations like below that fail to deallocate.
```   2 CoreGraphics CGBitmapContextCreateImage
   3 HoneyMobile +[SDImageCoderHelper CGImageCreateDecoded:orientation:] /Users/xx/workspace/apps/yy-ios/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:273
   4 HoneyMobile +[SDImageCoderHelper CGImageCreateDecoded:] /Users/xx/workspace/apps/yy-ios/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:229
   5 HoneyMobile +[SDImageCoderHelper decodedImageWithImage:] /Users/xx/workspace/apps/yy-ios/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:334
   6 HoneyMobile SDImageCacheDecodeImageData /Users/xx/workspace/apps/yy-ios/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCacheDefine.m:80
   7 HoneyMobile -[SDImageCache diskImageForKey:data:options:context:] /Users/xx/workspace/apps/yy-ios/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCache.m:418
   8 HoneyMobile __73-[SDImageCache queryCacheOperationForKey:options:context:cacheType:done:]_block_invoke /Users/xx/workspace/apps/yy-ios/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCache.m:536
   9 libdispatch.dylib _dispatch_call_block_and_release
```
and 
```
   2 CoreGraphics CGBitmapContextCreateImage
   3 HoneyMobile +[SDImageCoderHelper CGImageCreateDecoded:orientation:] /Users/xx/workspace/apps/yy-ios/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:273
   4 HoneyMobile +[SDImageCoderHelper CGImageCreateDecoded:] /Users/xx/workspace/apps/yy-ios/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:229
   5 HoneyMobile +[SDImageCoderHelper decodedImageWithImage:] /Users/xx/workspace/apps/yy-ios/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:334
   6 HoneyMobile SDImageLoaderDecodeImageData /Users/xx/workspace/apps/yy-ios/ios/Pods/SDWebImage/SDWebImage/Core/SDImageLoader.m:95
   7 HoneyMobile __70-[SDWebImageDownloaderOperation URLSession:task:didCompleteWithError:]_block_invoke.230 /Users/xx/workspace/apps/yy-ios/ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageDownloaderOperation.m:474
   8 Foundation __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
```

**Comment by dreampiggy** [comment]
If you have huge usage of loading large URL image. You can try to use `.avoidDecodeImage` options to avoid we re-draw image on the UI context.

This is used for small images which can increase the first time rendering time. But however, the cost is the RAM pressure. It's a balance between CPU and RAM.

See more in wiki: https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#optimization-for-large-images
