### ISSUE TITLE
Get response headers inside completion block of loadImage menthod

### ISSUE THREAD

**Issue by surajrautela** [SDWebImage/SDWebImage#3084]
### New Issue Checklist

* [ Yes] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ Yes] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ Yes] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info
Platform Name iOS
Platform Version iOS 12+
SDWebImage Version 5.0.0
Integration Method Carthage/cocoapods
Xcode Version 11

### Issue Description and Steps
I am using SDWebImage library My requirement is to get etag value from the response headers when the image is finished downloading . I am using the following function to download an image. How can I get the response headers inside the completion block
`func loadImage(with url: URL?, options: SDWebImageOptions = [], context: [SDWebImageContextOption : Any]?, progress progressBlock: SDImageLoaderProgressBlock?, completed completedBlock: @escaping SDInternalCompletionBlock) -> SDWebImageCombinedOperation?`
I am using SDWebImage library in swift. I read the documentation but couldn't find anything helpful

**Comment by dreampiggy** [comment]
See #2937. 

I also update the wiki about this common problem, read again and there are demo code.

[Wiki - Retrieve HTTP response/metrics from Top Level API](https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#retrieve-http-responsemetrics-from-top-level-api)
