### ISSUE TITLE
Xcode 12 SPM `IPHONEOS_DEPLOYMENT_TARGET` warning

### ISSUE THREAD

**Issue by diogot** [SDWebImage/SDWebImage#3085]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14
 SDWebImage Version      | 5.9.1
 Integration Method      | SPM
 Xcode Version           | Xcode 12
 Repro rate              | all the time (100%)

### Issue Description and Steps

Using SDWebImage in SPM on Xcode 12 GM produces this warning:

> The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

According to [this thread](https://forums.swift.org/t/minimum-ios-version-xcode-12-and-build-warnings/40224/3) the problem is that  [this](https://github.com/microsoft/plcrashreporter/blob/af3a0a1248adc690354de07e5e36e8bcc7314e72/Package.swift#L8) line is overriding Xcode settings forcing `IPHONEOS_DEPLOYMENT_TARGET` to an unsupported SDK version by Xcode 12.

The solution on the thread was remove the `platforms` section, because they support all platforms/versions this might be also applicable here.

**Comment by dreampiggy** [comment]
Designed behavior. SDWebImage 5.x version still need to support iOS 8+.

For iOS 9+ min deployment target version, we will schedule to release SDWebImage 6.0.

**Comment by diogot** [comment]
This issue will be addressed in version 6, so I think it shouldn't be closed by stale bot yet.
