### ISSUE TITLE
Cache query and Request modifiers running on main Thread synchronously

### ISSUE THREAD

**Issue by surajrautela** [SDWebImage/SDWebImage#3086]
### New Issue Checklist

* [Yes ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [yes] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [Yes ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Platform Name iOS
Platform Version iOS 12+
SDWebImage Version 5.0.0
Integration Method Carthage/cocoapods
Xcode Version 11

### Issue Description and Steps

```
// Set up request modifier
        let requestModifier = SDWebImageDownloaderRequestModifier { (request) -> URLRequest? in
            // Add auth token to request headers
            guard let token = fetchAuthorizationToken( cellIdentifier: cellIdentifier, columnInternalName: columnInternalName, domainUrl: domainUrl) else {
                let errorMessage = "No Token found against the URL for \(cellIdentifier) and \(columnInternalName)"
                let message = LoggingUtility.generateMessage(componentName: .listCanvas, projectName: .listShared, fileName: "\(ItemDisplayUtility.self)", loggingMessage: errorMessage)
                assertFailAndRecord("\(message)", identifier: "RxMq.wzVi", owner: "garo")
                return nil
            }
            var mutableRequest = request
            // Setting up request header
            mutableRequest.setValue(CellViewModelUtility.ImageDownloadAPIConstants.bearerHeaderParam + token, forHTTPHeaderField: CellViewModelUtility.ImageDownloadAPIConstants.authorizationParam)
            mutableRequest.cachePolicy = .useProtocolCachePolicy
            return mutableRequest
        }
```

This request Modifier requires access token that may take some time.
On analysing from instruments 
1. I observed that cache query is being run on main thread synchronously
2. Request modifier is getting called from main thread

Its affecting the scroll performance.

Is it the expected behaviour or am I missing something?

**Comment by dreampiggy** [comment]
Request modifier is getting called from main thread

Designed. Modifier does not supports any async operation.

**Comment by surajrautela** [comment]
@dreampiggy  do we enforce it to happen on the main thread ??

**Comment by dreampiggy** [comment]
**Request Modifier**, just like its name. It happended during request constructor step. You should not bind heavy logic on this.

This step is designed to called on your caller queue. For SDWebImage, it's called from `SDWebImageDownloader loadImageWithURL:`, which is called from `SDWebIamgeManager` cache miss callback, which is designed to be main queue.

This cause finally that request modifier happended on main queue.

If you think this behavior need change, this is new feature request and noticable behavior changes, need implementation and another minor version bump (v5.10.0).

**Comment by surajrautela** [comment]
@dreampiggy  I think if we move loadImageWithUrl on background queue , then request modifier will no longer be called on main queue. Thats a good enough workaround I guess

**Comment by dreampiggy** [comment]
> I think if we move loadImageWithUrl on background queu
This cause massive bad effect. Because this is open API (called from you, which means developers we framework can not control).

See code: https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDWebImageDownloader.m#L255

The problem is: The return value of that `loadImageWithURL:` function, need to set the NSURLRequest object. Which means, always sync. No async.

**Comment by dreampiggy** [comment]
Another solution is to change the framework itself call to the downloader into a global queue (not main queue). Which means code here:
https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDWebImageManager.m#L399

Trigger the downloader's download method from a global queue.

**Comment by surajrautela** [comment]
yeah doing that only

**Comment by dreampiggy** [comment]
This issue...We may not decide to change. The request modifier block is guranteeded to be called on the `caller queue`, not a global queue, because we need to return the fucntion with the final `NSURLRequest`, which is guranteeded to be the `caller queue`.
