### ISSUE TITLE
How to store the same image with different  keys for disk cache and in-memory cache

### ISSUE THREAD

**Issue by surajrautela** [SDWebImage/SDWebImage#3088]
* [Yes ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [yes] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [Yes ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Platform Name iOS
Platform Version iOS 12+
SDWebImage Version 5.0.0
Integration Method Carthage/cocoapods
Xcode Version 11

### Issue Description and Steps

we load the image using SDWebImageAPI 

```
SDWebImageManager.shared.loadImage(with: URL(string: url),
                                  options: [.scaleDownLargeImages,
                                            .fromLoaderOnly],
                                  context: imageContext,
                                  progress: nil,
                                  completed: { (image, data, _, _, _, _) -> Void in
                                        completion(image)
                                    return
                                  })
```

I read the code and what it does is this:
It creates a key using **url and imageContext** as I am sending thumbnailsize in image context
using this key , it stores the downloaded image in both disk cache and in-memory cache

What I would like to do is , store image data in disk cache using url as the key and store image  in in-memory cache using **url and imageContext** as key .

Is there a way to do it ?

**Comment by dreampiggy** [comment]
Currently you need to disable the automatically saving and call SDImageCache by yourself.

Using `.storeCacheType` (this is the image after transformed) and `.originalStoreCacheType` (this is the original image before transform), pass `.none` to disable the cache. And you call SDImageCache to store it to what you want.

**Comment by surajrautela** [comment]
Then I would have to mantain a separate IO queue for disk writes . The same way SDWebImage does its current disk writes . Right ?

**Comment by dreampiggy** [comment]
> Then I would have to mantain a separate IO queue for disk writes . The same way SDWebImage does its current disk writes . Right @dreampiggy 

Using SDImageCache API will always have a serial IO queue, see implementation in code.

You just need to ensure that the async write logic does not effect your other logic. For example, you can not implements the SDWebImageWaitStoreCache options.

**Comment by surajrautela** [comment]
got it
