### ISSUE TITLE
 context[SDWebImageContextCustomManager] is always be nil

### ISSUE THREAD

**Issue by LittleSeven20** [SDWebImage/SDWebImage#3090]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
1.
SDWebImageManager *manager = context[SDWebImageContextCustomManager];
        if (!manager) {
            manager = [SDWebImageManager sharedManager];
        } else {
            // remove this manager to avoid retain cycle (manger -> loader -> operation -> context -> manager)
            SDWebImageMutableContext *mutableContext = [context mutableCopy];
            mutableContext[SDWebImageContextCustomManager] = nil;
            context = [mutableContext copy];
        }
2.
SDWebImageManager *manager  =  [SDWebImageManager sharedManager];
 context[SDWebImageContextCustomManager] is always  nil . What is the difference between 1 and 2？

**Comment by dreampiggy** [comment]
What's your problem. I can not get any context.
