### ISSUE TITLE
SDAnimatedImageView播放gif后停在开头

### ISSUE THREAD

**Issue by qpc2015** [SDWebImage/SDWebImage#3091]
使用版本:SDWebImage (5.9.1)
使用SDAnimatedImageView加载gif图片,iOS14一下没问题,每次播放完停留在结尾,使用iOS14以上的设备显示完成后有的会停在开头. 目标想和iOS14一下一样
这是我的创建代码:
    self.gifImage = [SDAnimatedImageView new];
    self.gifImage.shouldCustomLoopCount = YES;
    self.gifImage.animationRepeatCount = 1;
    self.gifImage.clearBufferWhenStopped = YES;

  SDAnimatedImage *sdimage = [SDAnimatedImage imageNamed:@"switchOn.gif"];
  self.gifImage.image = sdimage;

**Comment by dreampiggy** [comment]
Give a demo URL ? Is that gif actual a GIF, not some other animated image format like WebP ?

**Comment by qpc2015** [comment]
图片资源使用的是gif格式的,iOS14效果如下http://cdn-test.diandingding.com/ios14bug.MP4, iOS 13显示正常如下http://cdn-test.diandingding.com/ios14bug.MP4

**Comment by qpc2015** [comment]
> 给出一个演示URL？该gif实际是GIF吗，不是WebP等其他动画图像格式吗？

**Comment by qpc2015** [comment]
这是其中的一个gif文件http://cdn-test.diandingding.com/switchOn.gif

**Comment by qpc2015** [comment]
> 给出一个演示URL？该gif实际是GIF吗，不是WebP等其他动画图像格式吗？

![switchOn](https://user-images.githubusercontent.com/13270757/94357728-e0846200-00cd-11eb-9e82-d12794e8b945.gif)

**Comment by dreampiggy** [comment]
Fix available in #3092. This is caused by a bug behavior (but have no really visible effect on iOS 13, only iOS 14)

**Comment by dreampiggy** [comment]
Try using that branch of SDWebImage to test on your project ?

```ruby
pod 'SDWebImage', :git => 'https://github.com/dreampiggy/SDWebImage.git', :branch => 'fix_animated_image_callback_when_stop'
```

**Comment by qpc2015** [comment]
> @qpc2015 Try using that branch of SDWebImage to test on your project ?
> 
> ```ruby
> pod 'SDWebImage', :git => 'https://github.com/dreampiggy/SDWebImage.git', :branch => 'fix_animated_image_callback_when_stop'
> ```

谢谢大神修复的分支,此分支已完全解决了我刚才提交的bug,感谢!

**Comment by iRILLLL** [comment]
the branch already deleted? how to install 5.9.2 @dreampiggy ? thank u

**Comment by dreampiggy** [comment]
I'll publish the 5.9.2 now.

**Comment by iRILLLL** [comment]
thank u very much @dreampiggy

**Comment by MengLiMing** [comment]
我更新SDWebImage到5.9.5 还是出现了楼主出现的问题
