### ISSUE TITLE
Error Domain=SDWebImageErrorDomain Code=1000 "Image url is nil" UserInfo={NSLocalizedDescription=Image url is nil}

### ISSUE THREAD

**Issue by HellosunDong** [SDWebImage/SDWebImage#3093]
Error Domain=SDWebImageErrorDomain Code=1000 "Image url is nil" UserInfo={NSLocalizedDescription=Image url is nil}

https://img-bss.csdnimg.cn/20208521755620_83795.jpg?imageMogr2/auto-orient/thumbnail/636x360!/format/jpg|watermark/1/image/aHR0cHM6Ly9pbWctYnNzLmNzZG5pbWcuY24vd1Z1ZS0wMy5wbmc=/dissolve/85/gravity/Center/dx/0/dy/0/

I encountered a problem
The picture link is valid and can be opened normally in the browser, but it cannot be opened in iOS. The  programming language is used oc.
Version number: SDWebImage (~> 5.0)

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/94505661-29f3bf00-023e-11eb-95e6-786e5279b420.png)

**Comment by SpeedGeeker** [comment]
怎么解决的呢
