### ISSUE TITLE
Could "imageFromDiskCacheForKey" get full GIF data?

### ISSUE THREAD

**Issue by maundytime** [SDWebImage/SDWebImage#3095]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.0.1
 SDWebImage Version      | 5.9.2/5.7.3
 Integration Method      | SPM
 Xcode Version           | 12.0.1 (12A7300)
 Repro rate              | all the time (100%)
 Repro with our demo prj | N/A
 Demo project link       | N/A

### Issue Description and Steps

Seems that "imageFromDiskCacheForKey" could not load GIF image data, instead it get a static GIF frame data. I try the newest SDWebImage and an old version, in both cases, "imageFromDiskCacheForKey" would not get full GIF data.

Wonder is it a designed behavior?

```
let key = "a gif url"
let imageView = SDAnimatedImageView()
imageView.sd_setImage(with: URL(string: key)) { (image, error, cacheType, url) in
    let imageReturn = image!.sd_imageData()!.count
    let fromView = self.imageView.image!.sd_imageData()!.count
    let fromCache = SDImageCache.shared.imageFromCache(forKey: self.key)!.sd_imageData()!.count
    let fromMemoryCache = SDImageCache.shared.imageFromMemoryCache(forKey: self.key)!.sd_imageData()!.count
    let fromDiskCache = SDImageCache.shared.imageFromDiskCache(forKey: self.key)!.sd_imageData()!.count
    let diskImageData = SDImageCache.shared.diskImageData(forKey: self.key)!.count
    print(imageReturn, fromView, fromCache, fromMemoryCache, fromDiskCache, diskImageData)
}
```

Version|imageReturn|fromView|fromCache|fromMemoryCache|fromDiskCache|diskImageData
---|---|---|---|---|---|---
5.9.2|1709081|1709081|1709081|1709081|**267355**|1709081
5.7.3|267355|267355|267355|267355|**267355**|1709081

**Comment by dreampiggy** [comment]
This is wrong usage :

```
SDImageCache.shared.imageFromCache(forKey: self.key)!.sd_imageData()
```

You may doing a `Decoding then Encoding` again.

Why not just use `imageDataFromDiskCache(for:)` and decode ? Such as using `SDAnimatedImage(data:)`

**Comment by maundytime** [comment]
Yea, you're right, no need to `Decoding then Encoding`, sorry for my bad code lol.

Actually I'm curious about the detail, let me describe as below:

If I query cache and specify animate image class to `SDAnimatedImage` in context option I'll get `SDAnimatedImage`.

But `imageFromDiskCache` returns `_UIAnimatedImage`, while others functions return `SDAnimatedImage`.

Why there is a difference in `imageFromDiskCache`?

**Comment by dreampiggy** [comment]
Because this is old API from 3.x...
Need another new API, like `imageFromDiskCache:optionis:context:`, right ?

**Comment by dreampiggy** [comment]
@maundytime There are already that API ? Read the documentation again and check that ?

![image](https://user-images.githubusercontent.com/6919743/95565461-d27dfc00-0a52-11eb-8ef8-fe528f90bdb3.png)

**Comment by maundytime** [comment]
Yes, the API with context options  is there already, the options could specify the animate image class. No need for new API.

Thank you for the info: `imageFromDiskCache` is API from 3.x, which is related to `SDAnimatedImage `. I got it. XD
