### ISSUE TITLE
高频使用动图会导致crash

### ISSUE THREAD

**Issue by xiaoxiaoyingqian** [SDWebImage/SDWebImage#3099]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 9.0~14.0
 SDWebImage Version      | 5.9.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12
 Repro rate              | sometimes
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps
之前提过这个问题[#3052](https://github.com/SDWebImage/SDWebImage/pull/3052),但后面一直依旧存在,如果全局高频使用gif,会导致概率性crash,我怀疑是gif在变换图片的过程中,一边在释放这个CFRelease(_imageSource),一边在使用,导致的两边都存在crash日志的发生

<img width="941" alt="60D4EAD0-17DD-4228-8B78-476E1904BCE8" src="https://user-images.githubusercontent.com/10387407/95536988-00494d80-0a1f-11eb-96c3-640b31b60d79.png">

**Comment by dreampiggy** [comment]
One `SDImageCoder` own one `CGImageSource`. So even if there are 2 `SDAnimatedImageView` which share single `SDAnimatedImage`, it will only contains single `CGImageSource` and only dealloc after all the `SDAnimatedImageView` stopped

**Comment by dreampiggy** [comment]
CGImageSource itself should be **Thread-Safe**. Or it's Apple's bug which need hack.
