### ISSUE TITLE
Image decode slow when run in tableview or collectionView

### ISSUE THREAD

**Issue by ChiShouWu** [SDWebImage/SDWebImage#3102]
### New Issue Checklist

* [V] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [V] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [V] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | os
 Platform Version        | 12.0 / 14.0
 SDWebImage Version      | 5.0.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12
 Repro rate              | all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Image decode slow when run in tableview or collectionView

My image is from my php server set on GCP compute engine.
And it is really slow when image loading.
And I check profile the problem is happening when decode image as [below](https://drive.google.com/file/d/1_7zVQ1dC9HMnhKGkIJOceWIUKUuUQTdk/view?usp=sharing)

**Comment by konstantin-tcherkashin** [comment]
I can confirm, it's just tens times slower on iOS14 than it used to be

**Comment by ChiShouWu** [comment]
@dreampiggy Can u help plz?

**Comment by dreampiggy** [comment]
Need more context and demo to reproduce this issue...
