### ISSUE TITLE
How to extend the GIF playback functionality?

### ISSUE THREAD

**Issue by ku8ar** [SDWebImage/SDWebImage#3105]
### New Issue Checklist

* [V] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [V] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [V] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | all
 Platform Version        | all
 SDWebImage Version      | all
 Integration Method      | cocoapods
 Xcode Version           | all
 Repro rate              | 
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps

This is not a bug, just a question about adding a new feature.
I am writing an application that plays GIFs like this:
1st frame, 2nd frame, 3d frame, 2nd frame, 1st frame, etc.

And now I was able to patch SDWebImage library by adding this code:
<img width="996" alt="Zrzut ekranu 2020-10-12 o 16 36 11" src="https://user-images.githubusercontent.com/16975059/95758701-18340200-0ca9-11eb-98d1-f5bc2e4b734b.png">

And the code works great.
But I thought it might be useful for community to have the option to play GIFs this way (there are many popular apps that use this style of playback: TikTok for example).

So I opened the project and decided to write an additional "bounce" option that will play GIFs this way.

But...

I have small experience with ObjectiveC. And I have no idea how to add this new "bounce" option.

So I have some questions:
Should I add a new SDWebImageOptions flag?
Or maybe I should create a new plugin (or even something else)?
And will such functionality be implemented in SDWebImage at all?

Thank you in advance for your response :)

**Comment by dreampiggy** [comment]
This is not suitable for `SDWebImageOptions`.

This is a function which works on `SDAnimatedImageView`. And also, `SDAnimatedImagePlayer`.

So the new property should be placed on these two classes.

**Comment by dreampiggy** [comment]
> And will such functionality be implemented in SDWebImage at all?

Yes. Sounds not so hacky logic, we can add a enum (better than BOOL because I asssume there may be new feature request like skipping frames)


```objective-c
typedef NS_ENUM(NSUInteger, SDAnimatedImagePlaybackMode) {
    SDAnimatedImagePlaybackModeNormal = 0
    SDAnimatedImagePlaybackModeBounce, // Playback to last frame and reverse again
}
```

**Comment by ku8ar** [comment]
Thank you for the quick reply!
Yes, this enum with 4 modes is more universal. I will try to write a PR soon :)

**Comment by TysonParks** [comment]
I second this feature request!
