### ISSUE TITLE
建议:SDWebImageOptions 加一种类型

### ISSUE THREAD

**Issue by puhahalx** [SDWebImage/SDWebImage#3109]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 14.0
 SDWebImage Version      | 5.9.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12 
 Repro rate              | all the time (100%) 
 Repro with our demo prj | yes
 Demo project link       | 

### Issue Description and Steps

sd_setImageWithURL:placeholderImage: 建议此方法在imageview已经加载出图片的时候 默认展位图为已经加载出来的本身的图片 而不是方法设置的placeholderImage. 
在uiview+webCache中 74-78
```
    if (!(options & SDWebImageDelayPlaceholder)) {
        dispatch_main_async_safe(^{
            [self sd_setImage:placeholder imageData:nil basedOnClassOrViaCustomSetImageBlock:setImageBlock cacheType:SDImageCacheTypeNone imageURL:url];
        });
    }
```
此代码是不管imageview之前是否已经加载成功 默认还是会把占位图显示上去,虽然从内存里读缓存图片数据很快,但是在一个场景中,就是app从后台切回到前台,并且请求刷新列表数据后,可以肉眼可见的看到所有图片都从代码设置的placeholderImage闪了一下,闪到缓存图片,此体验不太好,所以建议加一个类型,在imageview已经加载出图片的时候 默认展位图为本身的图片.
  目前我解决此问题的方法是
```
  [self.iconView sd_setImageWithURL:[NSURL URLWithString:model.icon] placeholderImage:self.iconView.image?self.iconView.image:[UIImage imageNamed:@"default"]];
```
手动判断自身是否已经存在图片,来防止闪动

**Comment by dreampiggy** [comment]
This is because of **Memory Cache been purged**. So you queried disk cache.
Disk cache query is async, so it will show the placeholder firstly then replace with final image.

If you don't want **Memory Cache been purged**. Try disable ?

```
// disable background clean
SDImageCache.shared.config.shouldRemoveExpiredDataWhenEnterBackground = false
// or enable weak cache
SDImageCache.shared.config.shouldUseWeakMemoryCache = true
```

**Comment by puhahalx** [comment]
shouldUseWeakMemoryCache这个属性默认就是true 这个没更改过. shouldRemoveExpiredDataWhenEnterBackground这个属性是清除磁盘数据吧?对内存数据的清除应该没啥联系吧,我设置这个属性好像并没有解决我提的这个问题.
  我写了一个demo,并且复现了我想表明的问题:
[sdImageDemo.zip](https://github.com/SDWebImage/SDWebImage/files/5438424/sdImageDemo.zip)
当我从后台切回到前台时,tableview进行reloaddata,可以明显看到imageview从默认的图片闪到加载好的图片,如下
https://s31.aconvert.com/convert/p3r68-cdx67/1x4x7-xhkko.gif
而且并不是所有图片,我对其中的关键帧进行了截图,是后面三张图片都是重新加载了,我打断点发现,后面三张是走的磁盘缓存,第一张是走的内存.我有点好奇这个缓存的机制是什么,不是应该图片加载好后 内存和磁盘都会存储么,为什么前后台切换过程中,内存中的缓存就被清理了么.麻烦您解答一下我的疑惑
![82b27321-c499-4c25-a8d1-d8567e755227](https://user-images.githubusercontent.com/28496967/97166305-ffa30c00-17bf-11eb-907d-8ad87a791478.jpg)

**Comment by puhahalx** [comment]
因为这个问题,所以我萌生了加一个类型的建议.对于已经加载好的图片,就不去显示占位图了,重新加载时而是将已经加载好的imageview的image作为占位图,然后再去查缓存替换图片
