### ISSUE TITLE
Thumbnail Decoding (5.5.0) documentation is incorrect for the defaultScaleDownLimitBytes

### ISSUE THREAD

**Issue by sgraesser17** [SDWebImage/SDWebImage#3111]
### New Issue Checklist

* [x ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.0
 SDWebImage Version      | 5.9.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11
 Repro rate              | all the time (100%)
 Repro with our demo prj | n/a
 Demo project link       | n/a

### Issue Description and Steps

The sample code for the defaultScaleDownLimitBytes in the Thumbnail Decoding (5.5.0) documentation is incorrect.
`SDImageCoderHelper.defaultScaleDownLimitBytes = 1000 * 1000 * 4 * 1024 * 1024; // (1000, 1000) pixels`
This calculates to ~ 4 TB which is obviously not what is intended.

The correct sample code should be:
`SDImageCoderHelper.defaultScaleDownLimitBytes = 1000 * 1000 * 4; // (1000, 1000) pixels`
This calculates to ~4 MB

As a check, the section mentions the default bytes limit is 60 MB, which is equivalent to (3966, 3966) pixels.
`3966 * 3966 * 4 = 60.002 MB`

**Comment by dreampiggy** [comment]
Yes. It should use the Bytes, not assuming as MB(1024 * 1024).
For 1000x1000 pixels it should be 4MB. For 3966x3966 it should be 60MB.

**Comment by dreampiggy** [comment]
> SDImageCoderHelper.defaultScaleDownLimitBytes = 1000 * 1000 * 4 * 1024 * 1024; // (1000, 1000) pixels

Where is this ? The wiki page or code comment ?

**Comment by sgraesser17** [comment]
The advanced usage wiki page in the [Thumbnail Decoding (5.5.0)](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50) section.

**Comment by dreampiggy** [comment]
Fixed.
