### ISSUE TITLE
The sample code for the imageThumbnailPixelSize documentation does not include pixel scale factor

### ISSUE THREAD

**Issue by sgraesser17** [SDWebImage/SDWebImage#3112]
### New Issue Checklist

* [ x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.0
 SDWebImage Version      | 5.9.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11
 Repro rate              | all the time (100%)
 Repro with our demo prj | n/a
 Demo project link       | n/a

### Issue Description and Steps

The sample code for the imageThumbnailPixelSize in the [Thumbnail Decoding (5.5.0)](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#thumbnail-decoding-550) documentation doesn't include the pixel scale factor to correctly calculate the image thumbnail size. The computed thumbnail size will be off by a factor of 2 or 3.
`CGSize thumbnailSize = CGSizeMake(200, 200); // Thumbnail will bounds to (200,200)`

The correct sample code should be:
`let scale = UIScreen.main.scale // Will be 2.0 on 6/7/8 and 3.0 on 6+/7+/8+ or later`
`let thumbnailSize = CGSize(width: 200*scale, height: 200*scale) // Thumbnail will bounds to (600, 600)`

As a check, the [sample code project](https://github.com/SDWebImage/SDWebImage/blob/master/Examples/SDWebImage%20Demo/MasterViewController.m) has a cell image of size (60, 40). The thumbnail size is set to (180, 120).

**Comment by dreampiggy** [comment]
Emm...This sample seems does not considerate the iPhone devices. Actually Mac can use this API as well.
But anyway, this is good for new user. I'll update with scale factor.

**Comment by dreampiggy** [comment]
Done.
