### ISSUE TITLE
'SDWebImage/SDWebImage.h' file not found

### ISSUE THREAD

**Issue by veena-experion** [SDWebImage/SDWebImage#3114]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        | 14.0
 SDWebImage Version      |  5.9.3 
 Integration Method      | cocoapods 
 Xcode Version           |  Xcode 12 
 

I am getting this error 'SDWebImage/SDWebImage.h' file not found' in my project running in xcode12.

**Comment by kinarobin** [comment]
![截屏2020-10-28 下午7 46 40](https://user-images.githubusercontent.com/29303030/97432045-4fb3d700-1956-11eb-9a01-eb9523067b3c.png)

**Comment by brennobemoura** [comment]
I am using SPM and I am having the same problem on Xcode 12.1 using the SDWebImage 5.9.4

**Comment by brennobemoura** [comment]
I fixed by removing and adding SDWebImage. After that, I cleaned the build folder
