### ISSUE TITLE
BUG: HEIC encoder does not respect frame duration timing when encoding HEIC sequences; defaults to 0.1sec

### ISSUE THREAD

**Issue by TysonParks** [SDWebImage/SDWebImage#3120]
### New Issue Checklist

* [👍 ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [👍 ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ 👍] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          | ios
 Platform Version        |13+
 SDWebImage Version     | 5.9.4
 Integration Method      |Swift Package
 Xcode Version           |Xcode 12.1
 Repro rate              |all the time (100%)
 Repro with our demo prj   |not sure
 Demo project link       |https://github.com/TysonParks/SDWebImageTestingApp

### Issue Description and Steps

The HEIC encoder appears to only encode HEIC sequences at 10fps (or with a 0.1sec frame duration). 

I mainly just write Swift so it's a little challenging to fully understand all the Obj-C code in this framework but... 
maybe this has to do with a (0.1sec) frameDuration limiter like at the bottom of the SDImageIOAnimatedCoder frameDurationAtIndex() method implementation? Perhaps the heic encoder is somehow always receiving a frameDuration value below the frameDuration's (0.011sec) threshold and bumping everything up to 0.1sec?

I wrote a simple testing app that shows how SDWebImage transcoding from GIFs and APNGs with different frame rates successfully maintains frame rates when converting to GIF or APNG, but always converts to HEIC sequences at 10fps.

Many thanks in advance!

https://github.com/TysonParks/SDWebImageTestingApp

**Comment by dreampiggy** [comment]
The `SDWebImageHEICCoder` use Apple's built-in Image/IO framework. And for APNG/GIF they share the similiar codebase...Maybe this is some bug because of Image/IO, I'll have a check.

**Comment by dreampiggy** [comment]
Found the reason:

For GIF/APHG, the `kCGImagePropertyGIFDelayTime/kCGImagePropertyAPNGDelayTime` will reset to 10ms (0.01s)
For HEIC, the `kCGImagePropertyHEICSDelayTime` will reset to 100ms (0.1s).

This is the root case.

If you really want to keep the original frame duration and FPS, I'll create a MR patch to change these into the `kCGImagePropertyHEICSUnclampedDelayTime`

**Comment by dreampiggy** [comment]
Try to de-compile the ImageIO.framework

**Comment by TysonParks** [comment]
Thanks for digging into this so quickly! 
Okay, I see it's on Apple's end.  :( 
Yes, I thought that the SD implementations for HEICCoder seemed to be the exact same as the GIF/APNG coders, corresponding to their matching keys, but I thought I might just be missing something when digging through the framework.

**Comment by TysonParks** [comment]
> Try to de-compile the ImageIO.framework

Is this possible?

**Comment by dreampiggy** [comment]
Does not found a good way to workaround this. I've fired radar to Apple :(

![image](https://user-images.githubusercontent.com/6919743/98097677-4da6c680-1ec8-11eb-8fff-7d85a3e2ba0b.png)

**Comment by dreampiggy** [comment]
If anyone want to check about this bug, use this demo:


![image](https://user-images.githubusercontent.com/6919743/98097649-3ff14100-1ec8-11eb-9736-2ba06cc5c757.png)
[ImageIOHEICSEncodeDecodeBug.zip](https://github.com/SDWebImage/SDWebImage/files/5487023/ImageIOHEICSEncodeDecodeBug.zip)

**Comment by dreampiggy** [comment]
@TysonParks For now, I suggest you to use the open-source libheif codec solution for HEIC encoding.

We provide a external coder plugin as well: https://github.com/SDWebImage/SDWebImageHEIFCoder

**Comment by TysonParks** [comment]
@dreampiggy Thanks for digging further into this! I will test the SDWebImageHEIFCoder today.

**Comment by wuliaososhunhun** [comment]
Heyy @dreampiggy wonder how can I encode the UIImage in sequence heic with https://github.com/SDWebImage/SDWebImageHEIFCoder this demo? Do we have some demo code for it?
From the test demo
 [[SDImageHEIFCoder sharedCoder] encodedDataWithImage:image format:SDImageFormatHEIC options:@{SDImageCoderEncodeMaxPixelSize : @(CGSizeMake(100, 100))}];
It can not pass the delay duration? or am I missing anything? many thx

**Comment by dreampiggy** [comment]
`encodedDataWithFrames` API

**Comment by dreampiggy** [comment]
Note: All the API in any coders (like WebP, HEIF, AVIF) are the same. The most used repo is https://github.com/SDWebImage/SDWebImageWebPCoder which contains the example for animation encoding.

But some repo's readme is lack of maintainess.

I want to deprecate these dedicated repos and turn SDWebImage into monorepo in the future.

**Comment by wuliaososhunhun** [comment]
Thx @dreampiggy for the response! really appreciated. Since I just want encode, dont want to use the `SDWebImageView` to load the image. I only saw the `SDImageHEIFCoder` has the `encodedDataWithImage:format:option:` method :(  
Yeah i saw the encode in imageio loss the heic parameter when decode also. Do u suggest to take a look on the `libheif` instead? try to understand how can add the duration by using the `libheif`. 
Maybe another question, when we encode the file. the extension of the file for animated/sequence heic. shall we use `.heic` or `.heif`? many thx for the help!

**Comment by dreampiggy** [comment]
>  I only saw the SDImageHEIFCoder has the encodedDataWithImage:format:option: method :(

This HEIFCoder does not support the encoding animation API ?

**Comment by dreampiggy** [comment]
Wait for my support and new release of SDWebImageHEIFCoder

**Comment by dreampiggy** [comment]
> Do u suggest to take a look on the libheif instead? try to understand how can add the duration by using the libheif.

ImageIO does only support HEIC(HEIF with HEVC codec, means) static image encoding. Not animation encoding.

libheif, the open-source HEIF codec supports either static image and animation encoding. This is what `SDWebImageHEIFCoder` based on.

> Maybe another question, when we encode the file. the extension of the file for animated/sequence heic. shall we use .heic or .heif? many thx for the help!

File extension does not contains anything useful. Only when you open a image file on macOS QuickLook, the filename may help that App to detect the type. I suggest you use `.heic` on all Apple platforms, and `.heif` used for some other container (which may not be HEVC codec, HEIF can contains even JPEG/AV1 data, see more: https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format)

**Comment by wuliaososhunhun** [comment]
@dreampiggy thx for the info! today i learn!
I may miss something. wonder for the `libheif` if Apple imageio does not support animated sequence heic encode (mainly for encode/decode those heic (duration etc)  parameters). how could `libheif` make it works for encode? does it use something different way? 
For apple imageio heic if the encode can support compression level also? maybe because i tried on the sequence animation, the parameter is need go though :(

**Comment by dreampiggy** [comment]
> how could libheif make it works for encode? does it use something different way?

HEIF standard specify the Animation support. But this not Apple's care, so they don't.
libheif can use x265 or other codec and follow the standard to write the animation info HEIF container. Ask and check here https://github.com/strukturag/libheif

Apple don't support HEIF animation, does not means the Standard does not supoprt animation. These are two things.
(Like, Safari is a browser implementation which should follow W3C, but it can also not support some features)

**Comment by dreampiggy** [comment]
For Static HEIC animation on ImageIO, you can still use the `kCGImageDestinationLossyCompressionQuality` API

**Comment by wuliaososhunhun** [comment]
Got it. so the static heic the CompressionQuality will still work as expected, but the animated not. 
Ah yeahh i saw the SDwebImage has a HEICEncode, but it does not actually do anything.
Many thx for your quick response. wonder are u planning to implement the support of the sequence heic in this repo soon? 🙏🏻

**Comment by dreampiggy** [comment]
`Ah yeahh i saw the SDwebImage has a HEICEncode, but it does not actually do anything.` 

Why ? The above code does not work ?

We have unit test for this.

**Comment by dreampiggy** [comment]
![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/afb64957-c610-4854-9867-1f185759845a)

See: Tests/Tests/SDImageCoderTests.m/ `test13ThatHEICWorks`

**Comment by dreampiggy** [comment]
> wonder are u planning to implement the support of the sequence heic in this repo soon?

Not in this repo, but in https://github.com/SDWebImage/SDWebImageHEIFCoder/releases

**Comment by wuliaososhunhun** [comment]
ah yeah i mean the [HEIFCoder repo ](https://github.com/SDWebImage/SDWebImageHEIFCoder). sorry for the confusion!
so you will add some changes there to support the sequence with libheif right? 🙏🏻

**Comment by dreampiggy** [comment]
> ah yeah i mean the [HEIFCoder repo ](https://github.com/SDWebImage/SDWebImageHEIFCoder). sorry for the confusion! so you will add some changes there to support the sequence with libheif right? 🙏🏻

Recently, dependends on whether the API in libheif (the C API) is easy or hard.

**Comment by dreampiggy** [comment]
@wuliaososhunhun Bad news.

libheif does not support  encoding HEIC animation as well.

https://github.com/strukturag/libheif/issues/1142#issuecomment-1987778187

So, there are no easy tools available to convert the Animated image into HEICS

**Comment by wuliaososhunhun** [comment]
Ohhhhhh nooooooo :( 
 thx for the information! do you have any suggestion how could we pass that infomration? like hacky way to pass from the exif/usercomment?

**Comment by dreampiggy** [comment]
If the animation is really important for you and don't care much about the decode speed. Try Animated WebP or AVIF

**Comment by dreampiggy** [comment]
> like hacky way to pass from the exif/usercomment?

EXIF can store only metadata like short string information. Even you can encode the duration table into metadata, you can not encode the actual each frame bitmap image into EXIF. So it's useless

**Comment by wuliaososhunhun** [comment]
thx @dreampiggy we currently implement with webp. but since on iOS device we want to try something more apple friendly, heic seems like far more better performance on apple device than webp (size, speed), so thats why we try to encode in heic :(

**Comment by dreampiggy** [comment]
> If the animation is really important for you and don't care much about the decode speed. Try Animated WebP or AVIF
> 
> AWebP: https://github.com/SDWebImage/SDWebImageWebPcodr AVIF (AV1 Image Format, which can stored into HEIF container): [SDWebImageAVIFCoder](https://github.com/SDWebImage/SDWebImageAVIFCoder), remember to choose `dav1d` for animation decoding and `rav1e` for animation encoding, or it will be slowwwwww

For AVIF, Apple iOS 16 and iPhone 15 contains the hardware AV1 codec, so which means it's fast. And maybe support the AVIF animated image as well, you can have a test.

**Comment by wuliaososhunhun** [comment]
> > like hacky way to pass from the exif/usercomment?
> 
> EXIF can store only metadata like short string information. Even you can encode the duration table into metadata, you can not encode the actual each frame bitmap image into EXIF. So it's useless

exif/userComment it is a CFStringRef, but i wonder i can convert it in float (only if it can)? i know it sounds bit hacky haha
something like
```
            (__bridge NSString *)kCGImagePropertyExifDictionary: @{
                (__bridge NSString *)kCGImagePropertyExifUserComment: @"0.33",
            },
```

**Comment by dreampiggy** [comment]
>  more apple friendly
It's just a lying, actually.

If you really want to be `friendly`, choose the best format for the best hardware.

Apple contains HEVC and AV1 media decoder, and also JPEG hardware acceleration.

You should choose only 3 in them

**Comment by wuliaososhunhun** [comment]
> > If the animation is really important for you and don't care much about the decode speed. Try Animated WebP or AVIF
> > AWebP: https://github.com/SDWebImage/SDWebImageWebPcodr AVIF (AV1 Image Format, which can stored into HEIF container): [SDWebImageAVIFCoder](https://github.com/SDWebImage/SDWebImageAVIFCoder), remember to choose `dav1d` for animation decoding and `rav1e` for animation encoding, or it will be slowwwwww
> 
> For AVIF, Apple iOS 16 and iPhone 15 contains the hardware AV1 codec, so which means it's fast. And maybe support the AVIF animated image as well, you can have a test (which I currently not have one). But you can still use the software codec.
> 
> ![](https://camo.githubusercontent.com/305e51cdc76cbc98685744a509709b52386d890b4842af66b4355e0e72e987a6/68747470733a2f2f62333134383432342e736d75736863646e2e636f6d2f333134383432342f77702d636f6e74656e742f75706c6f6164732f323032332f30362f6950686f6e655f4156315f6465636f6465722e6a70673f6c6f7373793d322673747269703d3126776562703d31)

oh AVIF? I dont know this format. let me google it. basically we try to look for something support both static and animated format and better performance than webp. prefer to support iOS 13+

**Comment by wuliaososhunhun** [comment]
yeah basically we just had UIImage (by taking screenshots) then want to encode to NSData to be stored in disk. I can get each frame data by 
```
let frameCount = CGImageSourceGetCount(imageSource)

```
then loop the count, to get each image property right?
```
let option = CGImageSourceCopyPropertiesAtIndex(imageSource, i, nil)
```
so i can at least get some exif data? the app is not a metadata viewer. just download some resources and computed them to store cache in device

**Comment by VaslD** [comment]
Sorry for reviving an old thread.

I just found out that, to encode animated HEIC images using ImageIO.framework you have to use `"public.heics"` (that is `kSDUTTypeHEICS`) as the `type` parameter to `CGImageDestinationCreateWithData` (or `CGImageDestinationCreateWithURL`).

Both `SDImageHEICCoder` (`master`, as of now) and examples/demos in this issue thread tries to set `kCGImagePropertyHEICSDictionary` on a destination created using `"public.heic"` (that is `kSDUTTypeHEIC`, `AVFileTypeHEIC`, `UTType.heic`).

Well, it does say "HEICS"-dictionary, so setting it on an "HEIC" will never work. Which can be confirmed by calling `CGImageSourceCopyProperties()` on the result HEIC data/file (to retrieve the container/file-level property) and observe the returned dictionary having explicit `CanAnimate = 0;`. The loss of frame duration (on individual image properties) is merely a side effect of ImageIO discarding unused properties since the destination image will never animate.

A warning log from `CGImageDestinationAddImage()` would be nice but we all know Apple.

**Comment by dreampiggy** [comment]
Can `public.heics` solve the problem ?

**Comment by dreampiggy** [comment]
Will create a PR and fix the `SDImageHEICCoder`

But I think for user, I don't want to create a new `SDImageFormatHEICS`, which is really confusing.

For animated image, it should also support static image, like `GIF`, there are no `static GIF` concept for user's usage

**Comment by dreampiggy** [comment]
Seems iOS 18+ new feature.

The old firmware ImageIO does not support this.☹️

Should we create a new class called `SDImageHEICSCoder` ? Because it's `#avaialble (iOS 18)`

Or we can hide this compatibility details, just return nil for iOS 17- version

**Comment by VaslD** [comment]
> > Note: "public.heics" maps to UTType.heics, which is iOS 18+ API,
> 
> @VaslD Can `public.heics` solve the problem ?
> 
> I means, if I use `public.heics` on iOS 17, iOS 16, can the Apple's encoder encode the animated HEIC image ? Or this is iOS 18+ only new features (iOS 18 is still in beta)
> 
> If so, we can just update the HEIC coder to use that.

Yes, it's backward compatible. You can build with Xcode 15's SDKs and query `CGImageDestinationCopyTypeIdentifiers()` on older systems, `"public.heics"` should be in the returned array.

The problem is that animated HEIC is technically HEICS, meaning it should be tagged `"public.heics"` and bear `*.heics` extension. (So if you have something is both HEIC and animated but doesn't play in Safari or Preview, try renaming it to HEICS.)

It's like MP4, you can rename `*.mov`, `*.m4a`, `*.aac` and many files to MP4 and it plays in most players, but they're not technically the same thing.

**Comment by VaslD** [comment]
> Seems iOS 18+ new feature.
> 
> The old firmware ImageIO does not support this.☹️
> 
> Should we create a new class called `SDImageHEICSCoder` ? Because it's `#avaialble (iOS 18)`
> 
> Or we can hide this compatibility details, just return nil for iOS 17- version

I'm sure iOS 14 and iOS 17 (and macOS 14 just to be safe) returns `"public.heics"` as supported destinations. It's `UTType.heics` that's 18+ but ImageIO APIs take `String`s not `UTType`s.

**Comment by dreampiggy** [comment]
> I'm sure iOS 14 and iOS 17 (and macOS 14 just to be safe) return "public.heics" as supported destinations. It's UTType.heics that's 18+ but ImageIO APIs take Strings not UTTypes.

OK. I'll just update the `SDImageHEICCoder` without an extra `SDImageHEICSCoder`

By the way, have you test that is the encoding only supported on real device or simulator ? I think HEVC encoding may be slower than JPEG, and simulator may lack of some hardware acceleration

**Comment by dreampiggy** [comment]
Moved to feature request: https://github.com/SDWebImage/SDWebImage/issues/3726
