### ISSUE TITLE
how to set image sd_setimage in  url filter WebP format from .jpg url

### ISSUE THREAD

**Issue by JARNBOY** [SDWebImage/SDWebImage#3125]
my link (assume) ->  "http://cdn-img.namemyweb/filters:format(webp):quality(30)/numberimg.jpg?v=1&accept:image/webp,image&w=768".

when i use sd_setimage error throw this message "Operation cancelled by user during querying the cache" and some image like this "Downloaded image decode failed".

**Comment by dreampiggy** [comment]
I can not get the use case and context for your issue.

If you want to support WebP images below iOS 13, see wiki about How to add coders plugins: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#coder-accept-mime-type

If you want to do something like URL filter, use the API `requestModifier`: https://github.com/SDWebImage/SDWebImage/wiki/How-to-use#use-request-modifier-50

**Comment by hatjs880328s** [comment]
yep! maybe you download two or more than one image with one imageview instance......
