### ISSUE TITLE
Is it better to add context and option to `canRequestImageForURL`?

### ISSUE THREAD

**Issue by sainttail** [SDWebImage/SDWebImage#3127]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

Can I propose adding information about `SDWebImageContext` and maybe `SDWebImageOptions` to `SDWebImageLoader. canRequestImageForURL:`?

The reason I ask this because I happen to use `SDWebImageLinkPlugin` by adding it as an additional loader to default loader. Now the problem is because I use context to send `LPMetadata` (to let `SDWebImage` know that this request url is a link preview not image to `SDWebImage`) and because `SDWebImageLinkLoader` always return `YES` for `canRequestImageForURL`. Now all image is being load as link preview and I have no way to pass that information context to our custom link preview loader subclass.

The only way I can think of now is to maybe add some prefix to the url something like `linkhttps://...` and check for link prefix.

Is there any better way than this to support loading both image and link preview image with the same manager?

**Comment by sainttail** [comment]
Somehow I discover that I can pass `SDWebImageLoader` as a context and everything seem to work fine by now!

**Comment by dreampiggy** [comment]
emm... Current SDWebImage's architecture, the `URL` is the root source for loading. You can not a thing which outside of URL. (Kingfisher supports you load anything conforms to a protocol, but we 5.x can not break this API)

Instead, see there is one trick way, like https://github.com/SDWebImage/SDWebImagePhotosPlugin.

Which encode the PHAsset information into the URL, like 

```
photos://id123456
```

this is a valid URL form, but can used to decode and construct another PHAssets.

Another way, you can use Objective-C's Associated Object, to bind another object into the NSURL.

Note for Swift `URL` it's a struct, but can be toll free bridging to NSURL.

**Comment by dreampiggy** [comment]
@sainttail See #3129.

After this been merged, something like your mentioned `SDWebImageLinkPlugin` can be updated to use the new `options` and `context` arg to pass extra information, without having to hack to use Associated Object on `NSURL`

**Comment by sainttail** [comment]
Thanks @dreampiggy for fast response!

Even though, I found solution to my problem. But having ability to check url, context, and option provide more room to add logic around loader!

**Comment by dreampiggy** [comment]
Supported via #3129
