### ISSUE TITLE
error: can't allocate region

### ISSUE THREAD

**Issue by spirit-jsb** [SDWebImage/SDWebImage#3133]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

When I have a lot of large images loaded, I get this crash information

```
malloc: *** mach_vm_map(size=48775168) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 14.0.1
 SDWebImage Version      | e.g. 5.9.5
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 12.2
 Repro rate              | e.g. all the time (100%)
 Repro with our demo prj | e.g. no
 Demo project link       | e.g. no

### Issue Description and Steps

![Uploading 截屏2020-11-29 08.24.19.png…]()

**Comment by dreampiggy** [comment]
OOM issue. Need more context.

**Comment by spirit-jsb** [comment]
@dreampiggy i set maxMemoryCost & maxDiskSize, this problem does not appear in our new version of APP at present. I think it can be shut down temporarily. thx
