### ISSUE TITLE
关于线程安全的疑问

### ISSUE THREAD

**Issue by yFeii** [SDWebImage/SDWebImage#3135]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |ios
 Platform Version        | 14
 SDWebImage Version      | 5.8.0
 Integration Method      |  cocoapods 
 Xcode Version           | xcode12
 Repro rate              | sometimes

### Issue Description and Steps

![image](https://user-images.githubusercontent.com/24515770/100563110-96e80b80-32f8-11eb-9f03-28ac81680257.png)
这里能够保证对 “attach more callbacks“的线程安全问题，但是无法保证“addHandlersForProgress”时，此时“operation”由于session delegate(下载完成) 执行 copy callbacks 。导致虽然添加token到operation，但是无法触发回调，具体细节如下：
1. 两个imageview下载一个url图片（非同时）。
2. 当第一个任务开始下载->下载完成的某一刻(还未设置isFinish)，此时开始第二个imageview开始调用"downloadImageWithURL"
3. 此时复用(operation)。还未调用addHandlersForProgress(主线程)
4. 此时第一个任务下载完成:（session 线程）
    1. callCompletionBlocksWithError: 复制callback（session 线程），异步主线程回调（主线程）
    2. 重置任务状态。（session 线程，operation.completionBlock:operation线程）
5. 第二个任务addHandlersForProgress(主线程)
6. 由于@synchronized，保证上述4，5操作线程安全，但是如果5在4之后，会导致5的callback 不会触发。

复现：
![image](https://user-images.githubusercontent.com/24515770/100564263-7cfbf800-32fb-11eb-8b79-56d3539a2b81.png)

![image](https://user-images.githubusercontent.com/24515770/100564283-90a75e80-32fb-11eb-9c67-86a0e1cc73fe.png)

不知道这个case 是否存在？

**Comment by dreampiggy** [comment]
From logic this can happen. Because at that time I did not realize that there are somthing called `copy callbacks`
