### ISSUE TITLE
OSSpinLock is Deprecated

### ISSUE THREAD

**Issue by phoney** [SDWebImage/SDWebImage#3136]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 11.0
 SDWebImage Version      | 5.10.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.2
 Repro rate              | all the time (100%)
 Repro with our demo prj | didn't try
 Demo project link       | didn't try

### Issue Description and Steps

I'm seeing 108 deprecation warnings about OSSpinLock being deprecated in iOS 10.
This is new in SDWebImage version 5.10.0. I didn't see it in 5.9.5.

It seems like the code in SDInternalMacros.h is attempting to deal with this deprecation but I don't think it's doing it correctly. I think the code should use ```__IPHONE_OS_VERSION_MIN_REQUIRED``` or ```__IPHONE_OS_VERSION_MAX_ALLOWED``` to control the use of the spinlock. Using ```@available``` is a runtime check and what's needed is a compile time check.

My project iOS Deployment target is 11.0.
I have the following code in my Podfile so the iOS Deployment target in the Pods project for SDWebImage is also 11.0

```
# This prevents a bunch of warnings about ios Deployment target being too old
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('11.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
```

This is a sample of the warnings I'm seeing:

<img width="1055" alt="Screen Shot 2020-11-30 at 1 43 23 PM" src="https://user-images.githubusercontent.com/3106038/100650941-b855f100-3312-11eb-8160-a693c1ef1ac7.png">

**Comment by dreampiggy** [comment]
You change `SDWebImage`'s min deployment target.

This is not a designed behavior. So this is not our usage.

We use OSSpinLock only on iOS 9. Because our min deloyment target is iOS 9. See readme.

**Comment by phoney** [comment]
@dreampiggy 

> You change SDWebImage's min deployment target.
> 
> This is not a designed behavior. So this is not our issue or case to fix.
> 
> We use OSSpinLock only on iOS 9. Because our min deloyment target is iOS 9. See readme.

The readme says: iOS 9.0 or later. iOS 11 is later. Apple recommends that iOS apps support the current major iOS version and one version back; so iOS 14 and iOS 13. Many apps that use SDWebImage will be iOS 13 and later, only. Probably most apps are not using iOS 9 as a deployment target.

You say that OSSpinLock is only used on iOS 9 but the code is present in all versions of iOS, which is the cause of the warnings. It's only a matter of time before you raise the deployment target to 10. So you will need to fix this sooner or later.

The fix for this is simple. Just like for TARGET_OS_MACCATALYST #if __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_10_0 then only use os_unfair_lock_lock.

**Comment by dreampiggy** [comment]
Your reply is correct. But actualy you can submit a PR wth this comment firstly.

The things like you done (change a framework‘s deploymet target version) or anything like Xcode build settings, which is not on control of framework author. So this cause extra maintain or issue for author to debug with....


For this, if you can pick that, I'll merge in. Remember to check macOS/tvOS/watchOS deployment target as well. Ugly but may solve issue.

**Comment by phoney** [comment]
@dreampiggy I'll try to fix this within a few days. You should probably re-open this issue so other users will know about it.

**Comment by dreampiggy** [comment]
Wait for your PR.
