### ISSUE TITLE
sd_imageData() returns nil

### ISSUE THREAD

**Issue by guidev** [SDWebImage/SDWebImage#3139]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 14.3
 SDWebImage Version      | e.g. 5.10
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12
 Repro rate              | e.g. all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | https://github.com/gorillatech/NullImage

### Issue Description and Steps

I've encountered an unexpected behaviour.

I've always thought that sd_imageData() would always return the image's original data.

I've attached a sample project with the image in question, that surprisingly returns nil even calling  `sd_imageData(as: .JPEG)`

```

// THIS WORKS
let a = UIImage(named: "image_placeholder")?.sd_imageData(as: .PNG)
assert(a != nil)
assert(a!.count > 0)


// THIS DOESNT WORK
let b = UIImage(named: "image_placeholder")?.sd_imageData(as: .JPEG)
assert(b != nil)
assert(b!.count > 0)


// THIS DOESNT WORK
let c = UIImage(named: "image_placeholder")?.sd_imageData()
assert(c != nil)
assert(c!.count > 0)

```

**Comment by dreampiggy** [comment]
provide a demo and your SDWebImage version. This sounds not work as expected and we have Unit Test to verify this behavior.

**Comment by guidev** [comment]
Hi, here's a demo https://github.com/gorillatech/NullImage

**Comment by dreampiggy** [comment]
Found some strange behavior on iOS 14.

![image](https://user-images.githubusercontent.com/6919743/102576312-2c283400-4130-11eb-8493-956bcd219d3f.png)

This only effect JPEG format encoding, does not effect any other extra format (including PNG/TIFF/BMP, etc).

**Comment by dreampiggy** [comment]
Seems this issue only effect when you load UIImage from PDF or SVG image.

I change the input into another UIImage from normal JPEG/PNG, works well.

**Comment by dreampiggy** [comment]
If you want to avoid this, you can try to use the `Force Decode` of your original image from PDF. Then try encoding.

```swift
let pdfImage = UIImage(named: "image_placeholder")!
let decodedImage = UIImage.sd_decodedImage(with: pdfImage)
let jpegData = decodedImage.sd_imageData(as: .JPEG)
```

A little trick...
