### ISSUE TITLE
-[SDWebImageDownloaderOperation start] crash

### ISSUE THREAD

**Issue by GitForTSir** [SDWebImage/SDWebImage#3140]
CoreFoundation    0x180454878    __exceptionPreprocess +220
libobjc.A.dylib    0x1949aac50    objc_exception_throw +56
CoreAutoLayout    0x194c4a208    <redacted> (missing)
CoreAutoLayout    0x194c49edc    <redacted> (missing)
CoreAutoLayout    0x194c499b4    <redacted> (missing)
CoreAutoLayout    0x194c44f9c    <redacted> (missing)
UIKitCore    0x18334f260    -[UIView _wantsReapplicationOfAutoLayoutWithLayoutDirtyOnEntry:] +176
UIKitCore    0x18334fdf0    -[UIView(CALayerDelegate) layoutSublayersOfLayer:] +2596
QuartzCore    0x183865384    -[CALayer layoutSublayers] +304
QuartzCore    0x183865858    CA::Layer::layout_if_needed(CA::Transaction*) +520
QuartzCore    0x183879ff8    CA::Layer::layout_and_display_if_needed(CA::Transaction*) +140
QuartzCore    0x1837bfee0    CA::Context::commit_transaction(CA::Transaction*, double, double*) +412
QuartzCore    0x1837eb36c    CA::Transaction::commit() +728
QuartzCore    0x1837ec6fc    CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) +92
CoreFoundation    0x1803cf358    __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ +32
CoreFoundation    0x1803c95c4    __CFRunLoopDoObservers +572
CoreFoundation    0x1803c9b74    __CFRunLoopRun +1052
CoreFoundation    0x1803c921c    CFRunLoopRunSpecific +596
CoreFoundation    0x1803ca2fc    CFRunLoopRun +60
SDWebImage    0xd898    -[SDWebImageDownloaderOperation start] (malformed)
Foundation    0x1817a374c    __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ +20
Foundation    0x1817a31d4    __NSOQSchedule_f +180
libdispatch.dylib    0x180056fb8    _dispatch_block_async_invoke2 +144
libdispatch.dylib    0x180048db0    _dispatch_client_callout +16
libdispatch.dylib    0x18004c12c    _dispatch_continuation_pop +412
libdispatch.dylib    0x18004b854    _dispatch_async_redirect_invoke +588
libdispatch.dylib    0x18005993c    _dispatch_root_queue_drain +352
libdispatch.dylib    0x18005a120    _dispatch_worker_thread2 +112
libsystem_pthread.dylib    0x1c986c7c8    _pthread_wqthread +212
libsystem_pthread.dylib    0x1c987375c    start_wqthread +4

binaryImages:

MUMobile    B0DE8043-A526-3CA4-8162-2070DCDC794C    arm64    1
CoreFoundation    AF3F8E01-C130-3464-AD40-C5532D273483    arm64    0
libobjc.A.dylib    282FD01C-1437-349B-AE1A-2EFF32859670    arm64    0
CoreAutoLayout    42D414DD-F9B5-38AA-98FB-89FA71C952FA    arm64    0
UIKitCore    05147936-B875-3EF3-94DB-9C8869BB0E34    arm64    0
QuartzCore    DC2644E7-E5E4-3D83-9110-A5AE7E2C8B1F    arm64    0
SDWebImage    869D5CEC-8F6E-39AD-94F5-9D88FC973A0A    arm64    2
Foundation    5C24EE4A-3447-36BD-9910-6F4D9616D692    arm64    0
libdispatch.dylib    3277BF1E-B994-3609-9B30-E0186BBF3C25    arm64    0
libsystem_pthread.dylib    677A4A35-39F3-303E-8C65-3FA891A75CAF    arm64    0
libsystem_kernel.dylib    03A89B86-F947-3933-B6A1-EDB0C6A2055E    arm64    0
GraphicsServices    D365EFCF-659C-3292-B203-5692107EDD1D    arm64    0
libdyld.dylib    BA60CB9E-95C5-3646-BEED-D313E15586CF    arm64    0

**Comment by KittenYang** [comment]
maybe this pr will help u https://github.com/SDWebImage/SDWebImage/pull/3146
