### ISSUE TITLE
Completion isn't called when cancel performed async for the second app launch

### ISSUE THREAD

**Issue by anton-plebanovich** [SDWebImage/SDWebImage#3141]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14.3
 SDWebImage Version      | 5.9.4
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.3
 Repro rate              | all the time (100%)
 Repro with our demo prj | -
 Demo project link       | https://github.com/anton-plebanovich/SingleView/tree/52a19067cc0680587167b448e3682cc5a854a450

### Issue Description and Steps

Code:
```swift
        // Works well on the FIRST app launch only.
        // Clearing cache doesn't help.
        SDImageCache.shared.clear(with: .all) { [self] in
            
            print("set image")
            imageView.sd_setImage(with: url) { _, _, _, _ in
                print("completion")
            }
            
            DispatchQueue.main.async { [self] in
                print("cancel")
                imageView.sd_cancelCurrentImageLoad()
            }
        }
```

The first launch output:
```
set image
cancel
completion
```

The second launch output:
```
set image
cancel
```

Probably related to https://github.com/SDWebImage/SDWebImage/pull/2692/files
- Clone, install pods and run project https://github.com/anton-plebanovich/SingleView/tree/52a19067cc0680587167b448e3682cc5a854a450
- Launch app the first time -> completion called
- Launch app a second time -> completion isn't called

I can only guess it's related to not handled completion calls in `SDImageCachesManager`, e.g. line 291:
```swift
            if (operation.isCancelled) {
                // Cancelled
                return;
            }
```

**Comment by dreampiggy** [comment]
Trying the demo. The reproduce rate is not 100%. But the `completion` may not been print after trying more times.

**Comment by dreampiggy** [comment]
This timeline can cause the issue:

1. Cache Miss
2. Start Download (NSOperation does not run main method)
3. User Cancel
4. NSOperation Start main method (too late)
5. Download Success
6. Found no completion block (because it's been removed during 3)

**Comment by dreampiggy** [comment]
Trying debug using this code can fix the issue.

Need more testing and check:

![image](https://user-images.githubusercontent.com/6919743/103059397-f4156b00-45df-11eb-88be-e0fc059ecdc9.png)


PS: Actually, the current 5.x implementation which use `NSOperation + URLSessionTask` is really ugly and trick. Becausse URLSEssionTask itself has `cancel` state, NSOperation has `cancel` state. So this race condition can happended from theory, unless we remove that `SDWebImageDownloadOperation` class totally.

See Kingfisher: https://github.com/onevcat/Kingfisher/blob/master/Sources/Networking/SessionDelegate.swift

**Comment by dreampiggy** [comment]
@anton-plebanovich Have a try with #3142 patch to see whether this issue been solved.

Also, you can apply this patch in your real App project, not just that demo.

**Comment by anton-plebanovich** [comment]
@dreampiggy Wow! That was the fastest response I ever had for the open-source project 😄

The fix works for me. I'll try to use it for the app with error logs to see how it behave on a bigger scale. Thanks!

**Comment by dreampiggy** [comment]
@anton-plebanovich  Any progress about this ? Can this solve your issue in reeal project ?

**Comment by anton-plebanovich** [comment]
I wasn't able to reproduce hence closing this one. Thanks @dreampiggy !

**Comment by dreampiggy** [comment]
I'll merge #3142 and release another patch version. Maybe 5.10.1
