### ISSUE TITLE
Feature request: store transformed images in different cache

### ISSUE THREAD

**Issue by koenpunt** [SDWebImage/SDWebImage#3144]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | -
 Platform Version        | -
 SDWebImage Version      | 5.10.0
 Integration Method      | -
 Xcode Version           | -
 Repro rate              | -
 Repro with our demo prj | -
 Demo project link       | -

### Issue Description and Steps

To explain; I'm working on an image-heavy app, that has to be functional offline as well. To have images always available, we've configured the cache not to expire, but for some of our customers this is causing problems with their on-device storage. As a solution we would like to be able to clear thumbnails and other derived images, but keep the originals. 
If it would be possible to specify a different cache for the source than for the thumbnails, we could have 1 cache for all the originals which doesn't expire, and another cache for the thumbnails which does.

So for example, here I introduced a `SDWebImageContextOriginalImageCache` context option;

```objc
SDImageResizingTransformer *transformer = [SDImageResizingTransformer
                                           transformerWithSize:CGSizeMake(300, 300)
                                           scaleMode:SDImageScaleModeAspectFill];
SDWebImagePrefetcher *prefetcher = [[SDWebImagePrefetcher alloc] init];
prefetcher.context:@{
    SDWebImageContextOriginalImageCache: originalsCache,
    SDWebImageContextImageCache: thumbnailCache,
    SDWebImageContextImageTransformer: transformer,
    SDWebImageContextStoreCacheType: @(SDImageCacheTypeDisk),
    SDWebImageContextOriginalQueryCacheType: @(SDImageCacheTypeDisk),
    SDWebImageContextOriginalStoreCacheType: @(SDImageCacheTypeDisk)
};
[prefetcher prefetchURLs:@[...] progress:nil completed:^(NSUInteger noOfFinishedUrls, NSUInteger noOfSkippedUrls) {
    //
}];

```

Does this make sense? Or is there maybe another way how this can be achieved?

**Comment by dreampiggy** [comment]
Emmm...For your use case (Don't care the implementation detail):

> As a solution we would like to be able to clear thumbnails and other derived images, but keep the originals.

Your suggestion is that `I store the thumbnail and other transformed image variant into a different cache folder, then I just remove that folder`.

This sounds useful. However, why not `Just store them together, and I record a list of transformed image cache key ? Then I just iterate the list and remove them one by one`.

Separate the thumbnail and original image into different cache path may help, but not always a good solution.

Anyway, I'll mark this as a feature request and marked as 5.11.0 version milestone. You can find some other good solution as well and comment here.

**Comment by koenpunt** [comment]
I think it can have multiple solutions. Another option is to keep track of versions like you said, and then maybe even with different configuration values for `maxDiskAge` and `diskCacheExpireType`, so the transformed versions of an image can expire automatically as well, but on a different schedule.

**Comment by dreampiggy** [comment]
Will added in 5.11.0
