### ISSUE TITLE
SDWebImageDownloaderOperation 0x11890d7d0 went isFinished=YES without being started by the queue it is in

### ISSUE THREAD

**Issue by Paulhbf** [SDWebImage/SDWebImage#3145]
列表加载图片较多时就会崩溃

**Comment by Paulhbf** [comment]
SDWebImageDownloaderOperation

- (void)setFinished:(BOOL)finished {
    [self willChangeValueForKey:@"isFinished"];
    _finished = finished;
    [self didChangeValueForKey:@"isFinished"];
}
崩在方法：[self didChangeValueForKey:@"isFinished"];

**Comment by kinarobin** [comment]
@Paulhbf  Which SDWebImage version?

**Comment by Paulhbf** [comment]
5.10.1

**Comment by kinarobin** [comment]
Full call stacks, please.

**Comment by Paulhbf** [comment]
17610275689

**Comment by Paulhbf** [comment]
之前用5.9.2版本是不会崩溃的，现在升级到5.10.1就会经常崩溃

**Comment by Paulhbf** [comment]
![image](https://user-images.githubusercontent.com/41659621/103202856-872b0980-492e-11eb-89c9-4c4bac0ce033.png)

**Comment by Paulhbf** [comment]
![010 Thread Queue com apple main-thread (serial)](https://user-images.githubusercontent.com/41659621/103202932-c6f1f100-492e-11eb-8cdc-6db253b02cbe.png)

有的时候也会崩溃在这里
[self.downloadQueue addOperation:operation];

**Comment by dreampiggy** [comment]
Is this related to 5.10.1 changes #3142 ?

Is this assert from NSOperation @Paulhbf

**Comment by dreampiggy** [comment]
Try again with 5.10.0 (not 5.10.1) and test again ? @Paulhbf 

If so, I'll provide a fix soon and release 5.10.2

**Comment by Paulhbf** [comment]
5.10.0不会发生闪退的情况，也不会报这个错误了

**Comment by papac25** [comment]
how do i qboid

**Comment by papac25** [comment]
how to avoid

**Comment by dreampiggy** [comment]
@Paulhbf  @papac25  This issued been fixed in [v5.10.2](https://github.com/SDWebImage/SDWebImage/releases/tag/5.10.2). All current 5.10.1 users should update to that version instead.
