### ISSUE TITLE
Transformer options incorrectly interpreted as file extension

### ISSUE THREAD

**Issue by koenpunt** [SDWebImage/SDWebImage#3147]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | -
 SDWebImage Version      | 5.10.0 
 Integration Method      | -
 Xcode Version           | -
 Repro rate              | -
 Repro with our demo prj | -
 Demo project link       | -

### Issue Description and Steps

The cache key and path for transformed images can contain periods (`.`), and are incorrectly picked up as filename extension, as can be seen here:

![image](https://user-images.githubusercontent.com/351038/103209669-ec1d3a00-4903-11eb-992d-c8029a2b3b05.png)

This isn't necessarily an issue, since the filename is always produced in the same way, but I can imagine this could lead to unexpected results in the future.

The issue probably originates somewhere around these lines:

https://github.com/SDWebImage/SDWebImage/blob/f5fd53b2d23a60f52e8aaf206cbc0751f79a6a02/SDWebImage/Core/SDDiskCache.m#L313-L321

My suggestion would be to ignore the extension altogether.

**Comment by dreampiggy** [comment]
The dot of cache key, should be mapped into different encoded characters.

Because file extension is specialized keep for user's use case #2635 #3143

**Comment by dreampiggy** [comment]
Or standardlize the `transfomerKey`, don't use the CGFloat raw value, only keep the integer one, which is actually suitable for this cases. 

I can provide one PR to fix.
