### ISSUE TITLE
Remove deprecated unarchiveObjectWithData method

### ISSUE THREAD

**Issue by kyleclegg** [SDWebImage/SDWebImage#3148]
The method unarchiveObjectWithData is deprecated and deemed unsecure/less secure than unarchive*OfClass. Please remove the following instance of use:

SDImageCache.m

**Comment by dreampiggy** [comment]
Our min deployment target is iOS 9.

iOS 9 does not have new API. They have to be kept.

**Comment by dreampiggy** [comment]
Until SDWebImage 6.0, we have no any plan to bump min deployment target version.

**Comment by kyleclegg** [comment]
Thanks for staying on top of it. It's not a huge rush but our organization would welcome the improved security... whenever SDWebImage is ready to bump min supported version would be a great time to do it.
