### ISSUE TITLE
[UIResponder doesNotRecognizeSelector:] error only in release builds

### ISSUE THREAD

**Issue by ApostolisApo** [SDWebImage/SDWebImage#3150]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14.0
 SDWebImage Version      | 5.0.0 
 Integration Method      |  cocoapods 
 Xcode Version           | Xcode 12
 Repro rate              | all the time (100%)
 Repro with our demo prj | N/A
 Demo project link       | N/A

### Issue Description and Steps

I use the library only with this method: 
`sd_setImage(with: URL(string: "test_url")), placeholderImage: UIImage(named: "Test")){}
`
and while it works when in debug mode, as soon as I release the app on TestFlight it crashes the app. The crash log says this:
3   UIKitCore                     	0x1a3008dec -[UIResponder doesNotRecognizeSelector:] + 300 (UIResponder.m:626)

and points to the line where I call the method...

Any thoughts?

**Comment by dreampiggy** [comment]
Any reproducable demo about this ?

I don't find anything in SDK's codebase about this issue.

**Comment by ApostolisApo** [comment]
it's really strange because I cannot... I created a sample project with an identical Podfile and the library runs perfectly... What can it be?

**Comment by kinarobin** [comment]
@ApostolisApo  Maybe it is helpful with some crash stack.

**Comment by pratikstephen** [comment]
You probably have some code optimization in the release build that's causing this, and the optimization is not enabled for Debug builds.
I ran into something similar, and the optimized code was skipping a class instantiation leading to a similar crash only in release builds.
https://medium.com/thecodr/is-your-ios-app-crashing-only-when-you-upload-it-to-testflight-ef27d3cb3ecd
