### ISSUE TITLE
iOS 13加载图片报错 Error Domain=SDWebImageErrorDomain Code=1001 "Downloaded image decode failed"

### ISSUE THREAD

**Issue by karson711** [SDWebImage/SDWebImage#3151]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS
 Platform Version        |  13
 SDWebImage Version      | 5.10.1
 Integration Method      |  cocoapods
 Xcode Version           | Xcode 12.3
 Repro rate              |  all the time (100%) 

### Issue Description and Steps
imageUrl：https://bndgxl.oss-cn-shenzhen.aliyuncs.com/ariticle_icon/bnd007.png

[self.iconImageView sd_setImageWithURL:[NSURL URLWithString:safeString(listModel.icon)] placeholderImage:itemDefaultImage];

**Comment by dreampiggy** [comment]
Try the demo, work as expected. You can try to debug by yourself.

The URL will download a JPEG image. Not PNG. But SDWebImage does not use the file name to detect image format. It use the Data Magic Bytes. 

![image](https://user-images.githubusercontent.com/6919743/103847082-6efb7d00-50da-11eb-8eee-01417535c9d9.png)

**Comment by developeder** [comment]
This issue reproduced on **iOS 13** only and not on iOS 14!

**Comment by nikhilpatel7** [comment]
Can anyone explain what is wrong here? As I am facing same issue. Any help would be appreciated.

**Comment by ameue** [comment]
I ran into the same problem, but I think it is not the SDWebImage problem.
I tested it like this:
```
let data = try? Data(contentsOf: url)
let image = UIImage(data: data)
```
'url' can be opened on browsers and iOS 14 devices

data length is greater than 0, but image=nil

Maybe it's a problem with iOS

**Comment by SirJunqiuWu** [comment]
I have verified that the most likely reason is that the original image is in webp format, and someone manually changed the file format to jpg or png, causing damage to the original image resources. Under low system 14, decoding may fail and access may not be possible, but after iOS 14, the decoding ability of mobile phones is higher and it has not appeared. Secondly, it is also related to the phone's memory. But the fundamental reason is that the image format has been altered and damaged.
