### ISSUE TITLE
iOS 14.2 [NSNull CGSizeValue]: unrecognized selector sent to instance 0x1f6789ee0

### ISSUE THREAD

**Issue by Patrick2W** [SDWebImage/SDWebImage#3152]
0 CoreFoundation | ___exceptionPreprocess + 220
-- | --
1 libobjc.A.dylib | objc_exception_throw + 60
2 CoreFoundation | -[NSOrderedSet initWithSet:copyItems:]
3 CoreFoundation | ____forwarding___ + 1444
4 CoreFoundation | _CF_forwarding_prep_0 + 96
5 SDWebImage | -[SDImageIOAnimatedCoder decodedImageWithData:options:] + 220
6 SDWebImage | -[SDImageCodersManager decodedImageWithData:options:] + 344
7 SDWebImage | SDImageLoaderDecodeImageData + 1168
8 SDWebImage | __70-[SDWebImageDownloaderOperation URLSession:task:didCompleteWithError:]_block_invoke.230 + 208
9 Foundation | ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
10 Foundation | -[NSBlockOperation main] + 104
11 Foundation | ___NSOPERATION_IS_INVOKING_MAIN__ + 24
12 Foundation | -[NSOperation start] + 808
13 Foundation | ___NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
14 Foundation | ___NSOQSchedule_f + 184
15 libdispatch.dylib | __dispatch_block_async_invoke2 + 148
16 libdispatch.dylib | __dispatch_client_callout + 20
17 libdispatch.dylib | __dispatch_continuation_pop + 416
18 libdispatch.dylib | __dispatch_async_redirect_invoke + 592
19 libdispatch.dylib | __dispatch_root_queue_drain + 356
20 libdispatch.dylib | __dispatch_worker_thread2 + 116
21 libsystem_pthread.dylib | _pthread_wqthread + 216
22 libsystem_pthread.dylib | start_wqthread + 8

**Comment by kinarobin** [comment]
Which version for SD ?
  
But first you should make sure that `SDImageCoderDecodeThumbnailPixelSize` is not an NSNull object.

**Comment by Patrick2W** [comment]
I found the problem. It's because of other libraries. thank you
