### ISSUE TITLE
[Big Sur] Screen broken when executing .webp file

### ISSUE THREAD

**Issue by youngbokkim4469** [SDWebImage/SDWebImage#3154]
Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | macos 
 Platform Version        | 11.1 
 SDWebImage Version      | 5.10.0 
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 12.2 

### Issue Description and Steps

Screen broken when executing .webp file
MacOS 11.0 version or lower works normally.
[issue_file.zip](https://github.com/SDWebImage/SDWebImage/files/5800188/issue_file.zip)

**Comment by dreampiggy** [comment]
"Screen broken" what does this means ?

**Comment by youngbokkim4469** [comment]
Screen break video attaches to the screen.

https://user-images.githubusercontent.com/77316013/105654932-642a5000-5f02-11eb-82e1-c8913824dcf0.mov

**Comment by dreampiggy** [comment]
Sample WebP ?

And, provide your SDWebImage version, SDWebImageWebPCoder version(this is another WebP codec repo).
Or, are you use the built-in `SDImageAWebPCoder` from macOS 11.0 ?

**Comment by youngbokkim4469** [comment]
build os version : version 11.1 (Big Sur)
xcode : 12.2(12B45b)

Sample project podfile.lock 
PODS:
  - libwebp (1.1.0):
    - libwebp/demux (= 1.1.0)
    - libwebp/mux (= 1.1.0)
    - libwebp/webp (= 1.1.0)
  - libwebp/demux (1.1.0):
    - libwebp/webp
  - libwebp/mux (1.1.0):
    - libwebp/demux
  - libwebp/webp (1.1.0)
  - SDWebImage/Core (5.10.0)
  - SDWebImage/MapKit (5.10.0):
    - SDWebImage/Core
  - SDWebImageWebPCoder (0.7.0):
    - libwebp (~> 1.0)
    - SDWebImage/Core (~> 5.10)

sample Webp file attach:
[sample_webp.zip](https://github.com/SDWebImage/SDWebImage/files/5864590/sample_webp.zip)

**Comment by dreampiggy** [comment]
Seems your WebP images can not been correctly parsed by libwebp.

> ➜  Downloads webpmux -get frame 1 cheetabu_22.webp -o 1.webp
> Failed to create mux object from file cheetabu_22.webp.

Create another WebP images from the assets ? And try again

**Comment by dreampiggy** [comment]
Can you render this sample WebP correctly by using `SDImageAWebPCoder` ? Which is provided by Apple's engineer, they call libwebp as well.

**Comment by youngbokkim4469** [comment]
This is an issue that occurs only in specific files.
If you check the attached file in Chrome browser, it will be displayed normally.

And when the binary compiled from the same sample code is checked in macos (Catalina), it is normally exposed.

**Comment by dreampiggy** [comment]
Even Apple can not solve this :(

This is libwebp's bug or your cropt WebP image issues. Nothing can we do.

![Uploading image.png…]()

**Comment by dreampiggy** [comment]
Chrome's WebP rendering engine does not always means "Standard WebP rendering logic"... 😂

Chromium itself have something hack code to keep backward compatibility. But those code does not exist on their open-source codec libwebp.

https://developers.google.com/speed/webp/docs/riff_container
