### ISSUE TITLE
Why webp coder is alone repo, but not apng coder

### ISSUE THREAD

**Issue by stackJolin** [SDWebImage/SDWebImage#3158]
1. Why webp coder is alone repo, but not apng coder？
2. There are two coder about webp - awebp-coder and webp coder。Is there any problem?
3. Why need `SDAsyncBlockOperation` in `SDWebImagePrefetcher`?
Thanks!

@dreampiggy

**Comment by dreampiggy** [comment]
> Why webp coder is alone repo, but not apng coder？

Until iOS 14, WebP is not support with the built-in https://developer.apple.com/documentation/imageio framework. Which means we need another third-party library from Google: https://github.com/webmproject/libwebp to support WebP. Extra dependency cause binary size larger, which is not everyone want. So we move it into a plugin, you can just simply integrate and use it like most built-in coders.

**Comment by dreampiggy** [comment]
> There are two coder about webp - awebp-coder and webp coder。Is there any problem?
No problem. Said again, until iOS14, Apple iOS/macOS **can not** render WebP. So we introduce `SDWebImageAWebPCoder` for iOS 14+, use `SDWebImageWebPCoder` for iOS 13-.

See readme and changelog again, this can answer your question: https://github.com/SDWebImage/SDWebImage/releases/tag/5.9.0

**Comment by dreampiggy** [comment]
> Why need SDAsyncBlockOperation in SDWebImagePrefetcher?

For implmentation, read: https://github.com/SDWebImage/SDWebImage/wiki/5.6-Code-Architecture-Analysis

Which can answer most of your question. And since SDWebImage is open source, read source code is better.

**Comment by stackJolin** [comment]
Thanks!
