### ISSUE TITLE
SDWebImage returning many more frames than expected from GIF file.

### ISSUE THREAD

**Issue by LaChrome** [SDWebImage/SDWebImage#3159]
### New Issue Checklist

* [yes ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [yes ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [yes ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info
 Platform Name: iOS
 Platform Version: 14.3
 SDWebImage Version: 5.10.2
 Integration Method: cocoapods
 Xcode Version: 12.3
 Repro rate 100%

### Issue Description and Steps
Loading certain GIFs from local iOS photo albums using SDWebImage returns an unexpected number of frames for some GIFs. When using other methods / libraries to load the exact same GIF in the same way, I get the expected number of frames.

The attached GIF contains 35 frames, but when loaded with SDWebImage, it returns 291 frames (see attached file: SDWebImage_shows_291_frames.GIF)

If I take that same GIF file (SDWebImage_shows_291_frames.GIF) and load it into some other GIF editing app, and save it (SDWebImage_shows_35_frames.GIF), SDWebImage now returns the expected number of frames.

![SDWebImage_shows_291_frames](https://user-images.githubusercontent.com/7025214/105606277-6657a780-5d66-11eb-9e3c-14a54ad06bb9.GIF)
![SDWebImage_shows_35_frames](https://user-images.githubusercontent.com/7025214/105606281-6bb4f200-5d66-11eb-857a-9bcdf427ae72.GIF)

The file that works has some changes, such as GIF version from 89a to 87a and background color from 255 to 0, but I wouldn't have expected these to impact the SDWebImage load.

Here is how I'm loading the GIF file:

SDWebImageManager.shared.loadImage(with: selectedGifURL, options: [.retryFailed, .fromLoaderOnly], progress: nil) { [weak self] (image, _, error, _, _, _) in
                if let animImage = image, let frames = animImage.images {
                    self?.gifFrames = frames
                }
            }

I have tried various SDWebImage options, but it hasn't changed the outcome. This happens with a number of GIFs

I'm going to continue testing to see if I can identify the source of the issue, but I haven't had any luck yet.

Thanks,

Chris

**Comment by dreampiggy** [comment]
Designed behavior.

This is limit and suck of UIImage itself, not something we can workaround. Because it does not supports different duration for different frames.

Read here: https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDImageCoderHelper.h#L18-L26

If you really want the actual `frame count`, you can transform the `UIAnimatedImage` into `NSArray<SDImageFrames>` again. Use `SDImageCodersHelper`.

Or more simple, do not use `UIImageView`, use `SDAnimatedImageView` and `SDAnimatedImage`, which have a property called `frameCount` to query actual frame count.

**Comment by dreampiggy** [comment]
UIAnimatedImage.images.count != frame count.

You misunderstanding these two different things.

**Comment by dreampiggy** [comment]
You can use `sd_imageFrameCount` API from #3243 to grab the actual visible frame count when displaying. Support iOS && macOS
