### ISSUE TITLE
UIImageOrientation not supported

### ISSUE THREAD

**Issue by n13** [SDWebImage/SDWebImage#316]
SDWebImage library creates all images with orientation UP.

That doesn't work for images that have a different image orientation, as per the EXIF flag.

Apparently no one needs this except me...

It's trivial to do as far as loading is concerned. However, it gets tricky with the cache, as the cache assumes UP image orientation for images and I am not sure how to implement an orientation flag there.

**Comment by dreampiggy** [comment]
It seems that this code is out of date. `- [UIImage initWithData:]` now can correctlly handler the EXIF orientation tag. It's no need to create another UIImage instance again.

See the test for that: https://github.com/recurser/exif-orientation-examples

I'd suggest to remove this code to make ImageIO coder more clear and performent.

**Comment by n13** [comment]
That’s good news! I’m all for that.

**Comment by dreampiggy** [comment]
@n13 😅 It's surprised that you're still subscribe to this issue.
Here is the test result of 8 EXIF orientation tag. It shows all correct and `UIImage.imageOrientation` is set automatically.

Screenshot:

![image](https://user-images.githubusercontent.com/6919743/38537101-4a08287c-3cbf-11e8-838e-a64812ed9938.png)

![image](https://user-images.githubusercontent.com/6919743/38537105-502059c8-3cbf-11e8-9173-3e4b31023aea.png)

![image](https://user-images.githubusercontent.com/6919743/38537107-52c725d0-3cbf-11e8-97be-4564aac946bf.png)

**Comment by dreampiggy** [comment]
@n13 So maybe I'll change this in SD 5.x(5 years passed)...But, does anyone have a iOS 7 device to test if we can also change this extra calculation of EXIF orientation on iOS 7 so that maybe we can also merge this change into 4.x ? 😅

**Comment by dreampiggy** [comment]
However, this only works for the `data` initlaized method. If we use `CGImage` to create `UIImage`. The image orientation is lost. But since EXIF orientation tag is mostlly only availble on JPEG images. So it's OK now. Other image foramt like WebP EXIF orientation is a little hard to implement and most image tools does not correctlly process it, So we currentlly do not process as well in 5.x.

See this test:

![image](https://user-images.githubusercontent.com/6919743/38537430-33bc6068-3cc1-11e8-9476-59d46586b88d.png)

**Comment by dreampiggy** [comment]
@n13 So maybe I'll change this in SD 5.x(5 years passed since your PR)...But, does anyone have a iOS 7 device to test if we can also change this extra calculation of EXIF orientation on iOS 7 so that maybe we can also merge this change into 4.x ? 😅

**Comment by n13** [comment]
Since the removing of this code is just an optimization / removal of unneeded hack, I would suggest to keep doing it for any old version that SD still supports.

If you're sure it's not needed say in iOS 8 and up, but SD still supports iOS 6 and 7 too - then only remove it for iOS8 and up. That way things keep working in all versions supported by SD. 

I don't have access to a iOS 7 device. So I would just assume by default that the workaround is still needed there, until proven otherwise.

I didn't look up what versions are supported by SD, so please fill in the correct values up there.

I am a big fan of removal of unneeded workarounds! Keeping the code base clean is important. So thanks for bringing this up.

**Comment by bpoplauschi** [comment]
Guys, I see that the current master branch (releases 4.x) supports iOS7 and above, and also the incoming 5.x releases will drop iOS7 and require iOS8, so I think we should clean it up if we are sure about the fix.

**Comment by dreampiggy** [comment]
@bpoplauschi 😅I'll create a PR and merge this into 5.x. But howevver, whehter or not to change this should be checked later (To see if iOS 7 support this automatically EXIF orientation handle or not)

**Comment by n13** [comment]
Just assume iOS 7 still has the bug. IMO Not really worth anyone’s time and effort to check whether iOS 7 could be made more efficient. It is just a hack removal after all. 

But if you want to do it be my guest :)

Thanks for spotting this. Removal in 5.x sounds like a great solution.
