### ISSUE TITLE
crash on  -[SDWebImageDownloader downloadImageWithURL:options:context:progress:completed:]

### ISSUE THREAD

**Issue by replytoashish008** [SDWebImage/SDWebImage#3160]
### New Issue Checklist

> Crashed: com.apple.main-thread
0  Foundation                     0x1ab22cf9c __NSOQSchedule + 248
1  Foundation                     0x1ab22eb40 __addOperations + 904
2  SDWebImage                     0x10743747c -[SDWebImageDownloader downloadImageWithURL:options:context:progress:completed:] + 700
3  SDWebImage                     0x107439430 -[SDWebImageDownloader(SDImageLoader) requestImageWithURL:options:context:progress:completed:] + 268
4  SDWebImage                     0x107440df8 -[SDWebImageManager callDownloadProcessForOperation:url:options:context:cachedImage:cachedData:cacheType:progress:completed:] + 1120
5  SDWebImage                     0x107440184 __89-[SDWebImageManager callCacheProcessForOperation:url:options:context:progress:completed:]_block_invoke + 440
6  libdispatch.dylib              0x1aaaee134 _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x1aaaef5ac _dispatch_client_callout + 20
8  libdispatch.dylib              0x1aaafb7d4 _dispatch_main_queue_callback_4CF + 832
9  CoreFoundation                 0x1aadc88d4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
10 CoreFoundation                 0x1aadc358c __CFRunLoopRun + 1692
11 CoreFoundation                 0x1aadc2bc8 CFRunLoopRunSpecific + 480
12 GraphicsServices               0x1b51ab5cc GSEventRunModal + 164
13 UIKitCore                      0x1aef75744 UIApplicationMain + 1936
14 Mitron                         0x10490487c main + 18 (AppDelegate.swift:18)
15 libdyld.dylib                  0x1aac3f384 start + 4

`Crashed: NSOperationQueue 0x11ac74290 (QOS: USER_INTERACTIVE)
0  Foundation                     0x1a54cc2d4 __NSOQSchedule + 248
1  Foundation                     0x1a54cbfe0 +[__NSOperationInternalObserver _observeValueForKeyPath:ofObject:changeKind:oldValue:newValue:indexes:context:] + 1752
2  Foundation                     0x1a54a8628 NSKeyValueNotifyObserver + 132
3  Foundation                     0x1a54aaaf8 NSKeyValueDidChange + 324
4  Foundation                     0x1a54a7ef0 NSKeyValueDidChangeWithPerThreadPendingNotifications + 148
5  SDWebImage                     0x10510f3c4 -[SDWebImageDownloaderOperation done] + 32
6  SDWebImage                     0x105110d6c __70-[SDWebImageDownloaderOperation URLSession:task:didCompleteWithError:]_block_invoke.230 + 532
7  Foundation                     0x1a54cd2e8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
8  Foundation                     0x1a53ca098 -[NSBlockOperation main] + 100
9  Foundation                     0x1a54cf5a0 __NSOPERATION_IS_INVOKING_MAIN__ + 20
10 Foundation                     0x1a53c9d54 -[NSOperation start] + 784
11 Foundation                     0x1a54cff98 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
12 Foundation                     0x1a54cfa64 __NSOQSchedule_f + 180
13 libdispatch.dylib              0x1a3e35cb0 _dispatch_block_async_invoke2 + 104
14 libdispatch.dylib              0x1a3e53280 _dispatch_client_callout + 16
15 libdispatch.dylib              0x1a3e2bbf8 _dispatch_continuation_pop$VARIANT$armv81 + 404
16 libdispatch.dylib              0x1a3e2b360 _dispatch_async_redirect_invoke + 588
17 libdispatch.dylib              0x1a3e38450 _dispatch_root_queue_drain + 344
18 libdispatch.dylib              0x1a3e38bf0 _dispatch_worker_thread2 + 112
19 libsystem_pthread.dylib        0x1ed437568 _pthread_wqthread + 212
20 libsystem_pthread.dylib        0x1ed43a874 start_wqthread + 8`

`Crashed: com.apple.main-thread
0  Foundation                     0x1ab22cf9c __NSOQSchedule + 248
1  Foundation                     0x1ab22cc90 +[__NSOperationInternalObserver _observeValueForKeyPath:ofObject:changeKind:oldValue:newValue:indexes:context:] + 1836
2  Foundation                     0x1ab213800 NSKeyValueNotifyObserver + 136
3  Foundation                     0x1ab215924 NSKeyValueDidChange + 340
4  Foundation                     0x1ab2130c8 NSKeyValueDidChangeWithPerThreadPendingNotifications + 152
5  SDWebImage                     0x1051ef1c8 -[SDWebImageDownloaderOperation cancelInternal] + 288
6  SDWebImage                     0x1051ef078 -[SDWebImageDownloaderOperation cancel] + 40
7  SDWebImage                     0x1051ee3a8 -[SDWebImageDownloaderOperation cancel:] + 432
8  SDWebImage                     0x1051ed1ac -[SDWebImageDownloadToken cancel] + 144
9  SDWebImage                     0x1051f7138 -[SDWebImageCombinedOperation cancel] + 244
10 Mitron                         0x10283278c SearchUserTableViewCell.prepareForReuse() + 4313196428 (<compiler-generated>:4313196428)
11 Mitron                         0x102832808 @objc SearchUserTableViewCell.prepareForReuse() + 4313196552 (<compiler-generated>:4313196552)
12 UIKitCore                      0x1af15e07c -[UITableView _dequeueReusableViewOfType:withIdentifier:] + 216
13 Mitron                         0x1027104fc SearchUserViewController.tableView(_:cellForRowAt:) + 68 (SearchUserViewController.swift:68)
14 Mitron                         0x10271094c @objc SearchUserViewController.tableView(_:cellForRowAt:) + 4312009036 (<compiler-generated>:4312009036)
15 UIKitCore                      0x1af176e00 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 684
16 UIKitCore                      0x1af143f90 -[UITableView _updateVisibleCellsNow:] + 2468
17 UIKitCore                      0x1af1612a8 -[UITableView layoutSubviews] + 164
18 UIKitCore                      0x1af4472bc -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2160
19 QuartzCore                     0x1b1a9f978 -[CALayer layoutSublayers] + 292
20 QuartzCore                     0x1b1a9fdb8 CA::Layer::layout_if_needed(CA::Transaction*) + 472
21 QuartzCore                     0x1b1ab221c CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 144
22 QuartzCore                     0x1b19f6e10 CA::Context::commit_transaction(CA::Transaction*, double) + 304
23 QuartzCore                     0x1b1a218c4 CA::Transaction::commit() + 684
24 QuartzCore                     0x1b1a224b4 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 96
25 CoreFoundation                 0x1aadc811c __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
26 CoreFoundation                 0x1aadc2e4c __CFRunLoopDoObservers + 420
27 CoreFoundation                 0x1aadc32dc __CFRunLoopRun + 1004
28 CoreFoundation                 0x1aadc2bc8 CFRunLoopRunSpecific + 480
29 GraphicsServices               0x1b51ab5cc GSEventRunModal + 164
30 UIKitCore                      0x1aef75744 UIApplicationMain + 1936
31 Mitron                         0x1026b887c main + 18 (AppDelegate.swift:18)
32 libdyld.dylib                  0x1aac3f384 start + 4`

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name            ios
 Platform Version         13.7.0 (17H35) /  14.3.0 (18C66) / all
 SDWebImage Version      | e.g. 5.0.0 / 4.4.0
 Integration Method        cocoapods 
 Xcode Version           Version 12.3 (12C33)
 Repro rate              all the time (1-10%) 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link    https://apps.apple.com/us/app/mitron/id1528781076

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by dreampiggy** [comment]
Duplicated for #3162 and may has been fixed by #3155
