### ISSUE TITLE
SDAnimatedImageView 多个实例存在，加载不同动画问题

### ISSUE THREAD

**Issue by yuanyuntian** [SDWebImage/SDWebImage#3163]
Platform Name            ios
 Platform Version        14.0
 SDWebImage Version      5.0.0
 Integration Method     cocoapods
 Xcode Version           Xcode 12

加载Lottie json动画
1.    [[SDImageCodersManager sharedManager] addCoder:[SDImageLottieCoder sharedCoder]];
2.    [icon1 sd_setImageWithURL:[NSURL fileURLWithPath:@“1***”] placeholderImage:nil options:0 context:nil];
3. [icon2 sd_setImageWithURL:[NSURL fileURLWithPath:@“2***”] placeholderImage:nil options:0 context:nil];

从icon1加载动画开始切换到icon2开始动画，导致icon1中的json动画出现在icon2中，是不是底层缓存出问题了

**Comment by dreampiggy** [comment]
Seems Lottie itself's bug...LOTAnimatedImageView.

Move to https://github.com/SDWebImage/SDWebImageLottieCoder, or try use https://github.com/SDWebImage/SDWebImageLottiePlugin

**Comment by dreampiggy** [comment]
@yuanyuantian Fixed by [SDWebImageLottieCoder v0.2.0](https://github.com/SDWebImage/SDWebImageLottieCoder/releases/tag/0.2.0).
