### ISSUE TITLE
SIGILL_-[SDMemoryCache objectForKey:] crash

### ISSUE THREAD

**Issue by wulongwang** [SDWebImage/SDWebImage#3164]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        |  iPhone OS 14.1 (18A8395)
 SDWebImage Version      | 5.9.4

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

Trigger Thread:0
Code Type: arm64
OS Version: iPhone OS 14.1 (18A8395)
Hardware Model: iPhone8,2
Version: 12.8.5.4
Exception Type: SIGILL
Exception Codes: ILL_ILLTRP at 0x000000019c3ff328
Launch Time: 2021-01-26 05:17:57
Date/Time: 2021-01-26 05:17:59
ExtraInfo:{,FirstLaunch:0,FirstInstall:0}

Thread 0 name:  
Thread 0 Crashed:
0    ChatKit                          -[UIImage(IconAdditions) isContentDiscarded]	(in ChatKit)	0
1    libcache.dylib                   _cache_get	(in libcache.dylib)	372
2    CoreFoundation                   -[NSCache objectForKey:]	(in CoreFoundation)	148
3    xxxx                      -[SDMemoryCache objectForKey:]		(in xxxx)	(SDMemoryCache.m:95)	36
4    xxxx                      -[SDImageCache imageFromMemoryCacheForKey:]		

xxxx is App Name, don't care

**Comment by kinarobin** [comment]
@wulongwang The symbol `[UIImage(IconAdditions) isContentDiscarded]` not in SDWedImage, You should check your code.

**Comment by wulongwang** [comment]
> @wulongwang The symbol `[UIImage(IconAdditions) isContentDiscarded]` not in SDWedImage, You should check your **ChatKit** code.

@kinarobin YES I checked , I found the symbol **[UIImage(IconAdditions) isContentDiscarded]**  is iOS system symbol
I don't know this crash  related to SDMemoryCache cache

![124da94bd68750fc51569f119c13aa15](https://user-images.githubusercontent.com/3376097/106098059-562f3600-6173-11eb-875d-e02625e7fbde.jpg)

**Comment by dreampiggy** [comment]
You store an UIImage from ChatKit into `SDImageCache` ?

**Comment by wulongwang** [comment]
> ChatKit

@dreampiggy NO, we don't use **ChatKit**, image loaded from URL by SDWebImage, next use **[SDImageCache sharedImageCache] imageFromDiskCacheForKey:key]** get disk image

**Comment by kinarobin** [comment]
@wulongwang  Full crash stack, Thanks.

**Comment by dreampiggy** [comment]
`UIImage` is `NSDiscardableContent` ? NSCache seems supports purgable algorithm.

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/106146067-33bc0d80-61b1-11eb-9912-5edc2661c62d.png)

This `UIImage(IconAdditions) isContentDiscarded` is not Apple's system framework.

You add extension to let `UIImage` conforms to `NSDiscardableContent`...
