### ISSUE TITLE
Xcode 12: SDWebImageManager' has different definitions in different modules;

### ISSUE THREAD

**Issue by kyweng** [SDWebImage/SDWebImage#3165]
Hi,

May I know anyone can how to fix this issue?

**Comment by dreampiggy** [comment]
`SDWebImageManager` is only defined in `SDWebImage` module. Objective-C does not supports namespace.

If you use other third-party framework, check that module's source code to find which defined twice.

**Comment by kyweng** [comment]
> `SDWebImageManager` is only defined in `SDWebImage` module. Objective-C does not supports namespace.
> 
> If you use other third-party framework, check that module's source code to find which defined twice.

Hi,
Thanks for replying. I'm using pod install.

**Comment by dreampiggy** [comment]
Try clean the Xcode's Build data.

Or, you can just try switching to `Legacy Build System` ?

Sounds like CocoaPods's bug or Xcode's issue.

**Comment by kyweng** [comment]
> Try clean the Xcode's Build data.
> 
> Or, you can just try switching to `Legacy Build System` ?
> 
> Sounds like CocoaPods's bug or Xcode's issue.

This is not working. Between that, thanks for replying.

**Comment by kinarobin** [comment]
Could you show more **ERROR** message for this issue?

**Comment by kyweng** [comment]
> Could you show more **ERROR** message for this issue?

These are the error codes:
'SDImageCache' has different definitions in different modules; first difference is defined here found property name 'shouldDecompressImages'
https://drive.google.com/file/d/1T2Pp2eATpD6r71fYstyN3EDg7cEjein0/view?usp=sharing


'SDWebImageManager' has different definitions in different modules; first difference is defined here found property name 'id<SDWebImageManagerDelegate>'
https://drive.google.com/file/d/1gRvZhQb70vEcdynKOYdDwIDVwRsN4-Pb/view?usp=sharing

Besides that, my project is using Swift 5 but imported the SDWebImage (Objective-C) with pod install.

**Comment by dreampiggy** [comment]
Your project import two different code which defines `SDWebImageManager` twice.

One maybe not SDWebImage, some third-party lib copy SDWebImage's code, which resuilt in this issue.

Following the Xcode's hint to find which lib defined twice, remove it.

**Comment by alimumtaz** [comment]
I am also facing the exact issue. And it is working fine in xcode 11 but not in xcode 12.

**Comment by mandeepsangwan21** [comment]
I am also facing same issue, was it fixed?

**Comment by Azilla030** [comment]
I have also this issue, does someone fix this?
