### ISSUE TITLE
Help Wanted: How to load .imageThumbnailPixelSize first and then original res image?

### ISSUE THREAD

**Issue by JeunePadawan** [SDWebImage/SDWebImage#3166]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0
 SDWebImage Version      | 5.10.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12
 Repro rate              | all the time (100%)
 Repro with our demo prj | somewhat yes
 Demo project link       | none

### Issue Description and Steps

Hello, I would like some advice as to how to implement **SDWebImage** and **SDWebImagePhotosPlugin** in a collectionView on Swift 5. The main problem comes from the fact that when there are multiple images with very high resolutions like 4000x2000, it lags like insane. It's quite simple to replicate, I simply duplicated the simulator's original photos in the photos library about ~100 times. They all have very high resolutions so when I open the screen with the collectionView, it lags a lot. Therefore, as suggested in the documentation, I've been using the .imageThumbnailPixelSize option. However, the goal is that  when I click on a cell in my didSelectItemAt, it uploads the image from the cell to my server but the problem is that this image is that of the imageThumbnailPixelSize one, not the original image. Therefore, the image quality is pretty bad, especially when zoomed in. I've tried what was suggested for the "optimization for large images" in the "common problems" page, but I did not really see any change. So far the only way I got this to not lag like crazy was with .imageThumbnailPixelSize. I've got it set to be equivalent to let thumbnailSize = CGSize(width: 200 * scale, height: 200 * scale) and the scrolling/fetching of pictures if very decent, but as I said when uploading afterwards and viewing the image in the full size and zooming on it, it's very bad. I've tried upping it to 400 * scale, but then there's an impact on the fetching & scrolling speed. The way I currently have it is that there are tabs such as "recents", "favorites or "albums" and when you click on them, it shows the respective photos associated with the album. I'm a beginner so there's probably many things I'm doing wrong in this, but when I searched on google I could mostly only find 4-5 years old references for what I wanted to do so I figured maybe there's a way of doing it that I'm unaware of. Seriously though, this pod is really great and whatever happens with this post, I'll keep using it since it's amazing! Thanks a lot for everything, if this "issue" isn't permitted, feel free to delete. I didn't see many swift demos, especially for what I wanted so I'm giving it a try!

Here's how i do it currently : 

```
class DemoScaleDownTransformer : NSObject, SDImageTransformer {
    var transformerKey: String = "DemoScaleDownTransformer"
    func transformedImage(with image: UIImage, forKey key: String) -> UIImage? {
        /// scale down to the device scale factor
        let ratio = image.scale / UIScreen.main.scale
        if ratio > 1 {
            let newSize = CGSize(width: image.size.width / ratio, height: image.size.height / ratio)
            let newImage = image.sd_resizedImage(with: newSize, scaleMode: .fill)
            guard let cgImage = newImage?.cgImage else {
                return image
            }
            /// make the scale factor match the currernt device, both @3x, @2x, @1x share the same logic point size
            return UIImage(cgImage: cgImage, scale: UIScreen.main.scale, orientation: image.imageOrientation)
        } else {
            return image
        }
    }
}

    private var allPhotos: PHFetchResult<PHAsset>? = nil
    private var userCollections = PHFetchResult<PHAssetCollection>()
    var albumPhotoAssets = PHFetchResult<PHAsset>()
    let fetchCollectionsOptions = PHFetchOptions()

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        self.collectionView.reloadData()
    }
    
    override func viewDidLoad(){
        super.viewDidLoad()

//        Supports HTTP URL as well as Photos URL globally
        SDImageLoadersManager.shared.loaders = [SDWebImageDownloader.shared, SDImagePhotosLoader.shared]
//        Replace default manager's loader implementation
        SDWebImageManager.defaultImageLoader = SDImageLoadersManager.shared
        
        //MARK: Set Delegates
        self.scrollView.delegate = self
        self.collectionView.delegate = self
        self.collectionView.dataSource = self
        self.collectionView.allowsMultipleSelection = true
        
        //MARK: Register cells
        self.collectionView.register(UINib(nibName: "ItemCell", bundle: nil), forCellWithReuseIdentifier: "ItemCell")

        self.FetchRecents(UIButton())
    }
    
    @IBAction func FetchRecents(_ sender: UIButton) {
        getSpecificAlbum(type: .smartAlbum, subtype: .smartAlbumRecentlyAdded)
    }
    
    @IBAction func FetchFavoritesPhotos(_ sender: UIButton) {
        getSpecificAlbum(type: .smartAlbum, subtype: .smartAlbumFavorites)
    }

    @IBAction func FetchAlbumPhotos(_ sender: UIButton) {
        self.collectionView.reloadData()
    }
    
    func getSpecificAlbum(type: PHAssetCollectionType, subtype: PHAssetCollectionSubtype) {
        self.allPhotos = .none
        let fetchOptions = PHFetchOptions()
        fetchOptions.predicate = NSPredicate(format: "mediaType = %d", PHAssetMediaType.image.rawValue)
        fetchOptions.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: true)]
        
        let album = PHAssetCollection.fetchAssetCollections(with: type, subtype: subtype, options: nil)
            album.enumerateObjects { (collection, _, _) in
                let result = PHAsset.fetchAssets(in: collection, options: fetchOptions)
                self.allPhotos = result
            }
                self.collectionView.reloadData()
    }

    func getAllPhotos() {
        self.allPhotos = .none
        let fetchOptions = PHFetchOptions()
        fetchOptions.predicate = NSPredicate(format: "mediaType = %d", PHAssetMediaType.image.rawValue)
        fetchOptions.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: true)]
        
        DispatchQueue.global(qos: .background).async() {
            self.allPhotos = PHAsset.fetchAssets(with: fetchOptions)

            DispatchQueue.main.async() {
                self.collectionView.reloadData()
            }
        }
    }
}

extension ScreenViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
            let cellSize = (collectionView.bounds.width/3)-2
        return CGSize(width: cellSize, height: cellSize)
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let cell = collectionView.cellForItem(at: indexPath) as! ItemCell

        let s = itemCellSelect(image: cell.imageCell.image!, id: cell.id!)
        self.imagesSelected.append(s)
    }
    
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        return 1
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) -> UIEdgeInsets {
            
        return UIEdgeInsets.zero
    }

    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumInteritemSpacingForSectionAt section: Int) -> CGFloat {
        
        return 1
    }

    // This is the vertical spacing between the cells
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        
        return 2
    }
     
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "ItemCell", for: indexPath) as! ItemCell
        cell.imageCell.sd_imageTransition = SDWebImageTransition.fade

        let asset: PHAsset
        asset = self.allPhotos![indexPath.item]
        let photosURL = NSURL.sd_URL(with: asset) 
        
        let scale = UIScreen.main.scale // Will be 2.0 on 6/7/8 and 3.0 on 6+/7+/8+ or later
        let thumbnailSize = CGSize(width: 200 * scale, height: 200 * scale) // Thumbnail will bounds to (200,200) points
        let transformer = DemoScaleDownTransformer()
        let imageView = cell.imageCell
        
        imageView?.sd_setImage(with: photosURL as URL?, placeholderImage: nil, options: [.preloadAllFrames], context: [.imageScaleFactor : 3, .imageThumbnailPixelSize : thumbnailSize, .imageTransformer: transformer])
        cell.id = photosURL.absoluteString
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return allPhotos?.count ?? 0
    }
}

```

**Comment by dreampiggy** [comment]
From your question:

I don't think you have any reason to load **Full resolution image from Photos into `UIImage`.**

You just neeed full resolution image to upload to server, right ? Why not using Photos API itself: https://developer.apple.com/documentation/photokit/phimagemanager/1616957-requestimagedataforasset

This return back a `NSData`, not `UIImage`, suitable for uploading.

For Client side rendering thumbnail, it's OK to use SDWebImagePhotosLoader with a smaller thumbnail size.

**Comment by JeunePadawan** [comment]
@dreampiggy Unfortunately, that method is only available for ios 13+ and I'm on ios 11 :(

**Comment by JeunePadawan** [comment]
@dreampiggy Actually, isn't there a way in the completion handler to access the original, unmodified image? By that I mean the image without the .imageThumbnailPixelSize option. That way on my didSelectItemAt I could access the original quality image easily before uploading it instead of the resized one with the .imageThumbnailPixelSize option.

**Comment by dreampiggy** [comment]
NO...

You should understand what your current use case is.

Your use case is `I want to query the original image data, upload to server. But my client iOS App don't need to render the full resolution image, because it cause much more RAM, one single 4K image need 250MB+)`

So my suggestion is:

1. Use SDWebImagePhotosLoader's `SDWebImageContextPhotosRequestImageData` as well as `SDWebImageContextThumbnailPixelSize`, which will use the Apple's API to query original image data, then do thumbnail decoding with a smaller UIImage to render. You can grab the image data to upload, grab the UIImage to render on screen.

2. Or, you can just use Photos API to query image data, then call SDWebImage's decoding method to get thumbnail image. See `SDImageCodersManager` API or `UIImage+Multiformat` category API.

**Comment by dreampiggy** [comment]
```swift
// New API
let photosURL = asset.sd_URLRepresentation

imageView?.sd_setImage(with: photosURL, placeholderImage: nil, options: [.preloadAllFrames], context: [.imageScaleFactor : 3, .imageThumbnailPixelSize : thumbnailSize, .imageTransformer: transformer, .photosRequestImageData: true])
```

**Comment by JeunePadawan** [comment]
> ```swift
> // New API
> let photosURL = asset.sd_URLRepresentation
> 
> imageView?.sd_setImage(with: photosURL, placeholderImage: nil, options: [.preloadAllFrames], context: [.imageScaleFactor : 3, .imageThumbnailPixelSize : thumbnailSize, .imageTransformer: transformer, .photosRequestImageData: true]) { _, image, data, _, _ 
>     // image is thumbnail
>     renderImageToView(image)
>     // data is original data
>     uploadToServer(data)
> }
> ```

How can I access this though? I don't see anything where I can access a value of Data like you just did. I must be missing something here obviously, sorry for the hassle you're having because of me. Though I do think that this would solve my problem for sure.
![image](https://user-images.githubusercontent.com/60398892/106816269-22f11900-6643-11eb-8fce-4fdc4f8166ac.png)

**Comment by dreampiggy** [comment]
Using the `sd_internalSetImage` API instead to access `Image Data`. Which works the same like that.

**Comment by dreampiggy** [comment]
https://sdwebimage.github.io/SDWebImage/Categories/UIView%28WebCache%29.html#/c:objc(cs)UIView(im)sd_internalSetImageWithURL:placeholderImage:options:context:setImageBlock:progress:completed:

**Comment by JeunePadawan** [comment]
This worked great! Thanks for the help!
