### ISSUE TITLE
Get Url from UIImage?

### ISSUE THREAD

**Issue by HermanKayy** [SDWebImage/SDWebImage#3170]
Hello Is there a convenience to easily get the url from an image using SDWebImage?

**Comment by dreampiggy** [comment]
There is one `sd_imageURL` property on loaded UIImageView, see: https://sdwebimage.github.io/SDWebImage/Categories/UIView%28WebCache%29.html#/c:objc(cs)UIView(py)sd_imageURL

However, what you want seems the `I want to bind a UIImage with the loaded URL from SDWebImage` ? What this used for ?

**Comment by dreampiggy** [comment]
If you want this `binding` between loading URL and image, maybe you can have a try with `sd_extendedObject`. You can write the URL when loading completed (via SDWebImageLoader's delegate method, or sd_setImageWithURL callback).

Then read it when you need.

See: https://sdwebimage.github.io/SDWebImage/Categories/UIImage%28ExtendedCacheData%29.html#/c:objc(cs)UIImage(py)sd_extendedObject
