### ISSUE TITLE
Load Image Failed

### ISSUE THREAD

**Issue by kenny-alt** [SDWebImage/SDWebImage#3178]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Description and Steps

Error Domain=NSURLErrorDomain Code=-1005 "网络连接已中断。" UserInfo={NSLocalizedDescription=网络连接已中断。, NSErrorFailingURLStringKey=https://y.zdmimg.com/202007/22/5f17ff9d40eaf1380.png_d320.jpg, NSErrorFailingURLKey=https://y.zdmimg.com/202007/22/5f17ff9d40eaf1380.png_d320.jpg, _NSURLErrorRelatedURLSessionTaskErrorKey=	(
	"LocalDataTask <7B58CCBC-D1C6-490E-B7F8-88828472B5D6>.<3181>",
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <7B58CCBC-D1C6-490E-B7F8-88828472B5D6>.<3181>, NSUnderlyingError=0x283ecd4a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x284a66d00 [0x1f15b7a68]>{length = 16, capacity = 16, bytes = 0x100222b8ac110be40000000000000000}}}}

Accidentally, the image failed to load. From the log, it appears to be a network problem, but the device network is normal. The  Image URLs are accessible in Safari.

**Comment by iDevelopper** [comment]
Use English please!

**Comment by kenny-alt** [comment]
@iDevelopper OK
