### ISSUE TITLE
how to enable bitcode using cocoapods

### ISSUE THREAD

**Issue by zhonglaoban** [SDWebImage/SDWebImage#3179]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14.0
 SDWebImage Version      | 5.10.2
 Integration Method      | cocoapods 
 Xcode Version           |  Xcode 12.0
 Repro rate              | all the time (100%) 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

bitcode bundle could not be generated because 'SDWebImage.framework/SDWebImage' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file 'SDWebImage.framework/SDWebImage' for architecture arm64

**Comment by randarnold** [comment]
I don't believe that bitcode is supported in Xcode 14.
