### ISSUE TITLE
SDImageBlurTransformer doesn't work as intended ( doesn't apply blur to the downloaded image)

### ISSUE THREAD

**Issue by ForceGT** [SDWebImage/SDWebImage#3181]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          | IOS
 Platform Version        | IOS 14.4
 SDWebImage Version      | 5.10.4
SDWebImageSwiftUI Version | 1.5.0
 Integration Method      | e.g. Swift PM
 Xcode Version          | Xcode 12

### Issue Description and Steps

I tried using ```SDImageBlurTransformer``` but it doesn't seem to work 
I have put correct values for the blur radius even then it doesn't work as intended 

Here is my code 

```
func downloadImage(url: String, blurRadius: Double){
       
        let blurTransformer = SDImageBlurTransformer(radius: CGFloat(blurRadius))
        let downloader = SDWebImageDownloader.shared
        downloader.downloadImage(with: URL(string: url), options: [], context: [.imageTransformer: blurTransformer]) { (received, total, url) in
            DispatchQueue.main.async{
                self.downloadInProgress = true
                self.downloadProgressValue = Float(received) / Float(total)
            }

        } completed: { (image, data, err, finished) in
            
            DispatchQueue.main.async {
                if(err == nil){
                    if let image = image , finished{
                        //Finished successfully
                        self.downloadInProgress = false
                        self.saveToAlbum(photo: image, albumTitle: "WallPixel")
                    }
                }else{
                    self.downloadInProgress = false
                    self.downloadError = true
                    print(err?.localizedDescription)
                }
            }
            
        }
    }
```

**Comment by dreampiggy** [comment]
Downloader does not have the ability to produce `transformer`.

It's the task for Manager.

So, if you really don't want to use cache, you should write:

```
let manager = SDWebImageManager.shared
manager.loadImage(with: URL(string: url), options: [], context: [.imageTransformer: blurTransformer]) { (image, data, cacheType, url) in
    print(image)
    // transformed image here
}
```

I can update this in the Wiki pages about transformer.

**Comment by ForceGT** [comment]
So that method ```loadImage``` is similar to downloading image right?
Like it will save the image to cache temporarily and then apply the transformer and return the image

**Comment by dreampiggy** [comment]
Added in wiki: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#usage

**Comment by dreampiggy** [comment]
> So that method loadImage is similar to downloading image right?

If you want to avoid `store cache` process as well, pass `.storeCacheType : SDImageCacheType.None.rawValue` as well.


Image Loading including:
1. Query Cache
2. Download // You want
3. Do Transform // You want
4. Store Cache

**Comment by dreampiggy** [comment]
Or, you can just use transformer as a tool. It's not hard to use.

```swift
            DispatchQueue.main.global {
                let transformedImage = transformer.transformImage(with: image forKey: url)
            }
}
```
