### ISSUE TITLE
An image animate too fast!

### ISSUE THREAD

**Issue by YueLiXing** [SDWebImage/SDWebImage#3185]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / macos
 Platform Version        | e.g. 14.4 / 10.15.6
 SDWebImage Version      | e.g.5.10.4
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 12.4
 Repro rate              | e.g. all the time (100%) 

![4506c904d6cabd2f10d43e9f748fd181](https://user-images.githubusercontent.com/9456800/110110858-68436a80-7dea-11eb-8209-d8c7964aafa3.png)

这是一张 apng 的图，在电脑上的预览是正常的，但是用 SDAnimatedImageView 的方式来显示的时候，就执行速度非常快。和浏览器显示出来的也不一样
```
SDAnimatedImage * image = [SDAnimatedImage imageNamed:@"4506c904d6cabd2f10d43e9f748fd181.png"];
SDAnimatedImageView * imageView = [[SDAnimatedImageView alloc] init];
imageView.size = CGSizeMake(14, 14);
[self.view addSubview:imageView];
```

**Comment by dreampiggy** [comment]
Seems Apple's Bug, not something we can control.

The decoder is ImageIO (not third-party codec). ImageIO returns the third frame like this:

![image](https://user-images.githubusercontent.com/6919743/110270424-be89f680-8000-11eb-9e41-76f3e029aac9.png)

Which cause the un-expected visual effect.

You can reproduce the same issue on your iPhone's Photos Library.

Seems this works fine on macOS ?

**Comment by dreampiggy** [comment]
This does not works on my macOS as well. macOS Catalina 10.15.

Try to use the original animated assets to re-encode to APNG. Your APNG seems does not matches Apple's APNG implementation or APNG standard: https://wiki.mozilla.org/APNG_Specification

**Comment by YueLiXing** [comment]
use `SDWebImage OSX Demo` and `self.imageView3.image = [SDAnimatedImage imageNamed:@"4506c904d6cabd2f10d43e9f748fd181.png"];`

https://user-images.githubusercontent.com/9456800/110274936-00b83580-800b-11eb-89a2-727301990a77.mov

**Comment by dreampiggy** [comment]
> This is not SDWebImage's bug. It's Apple's bug.

I told the solution. You can workaround by re-create your APNG images using the standard APNG tools available online.
