### ISSUE TITLE
xcode 10.1 swift 4.2 install issue and -Use of undeclared identifier 'UIActivityIndicatorViewStyleLarge'

### ISSUE THREAD

**Issue by maverickchangithub** [SDWebImage/SDWebImage#3188]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.1 
 SDWebImage Version      | 5.10.4
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10
 Repro rate              | all the time (100%)
 Repro with our demo prj | not tested
 Demo project link       | only local

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

#### Here is my problem:

- install through pod "seems" ok , but cannot do `import SDWebImage` error says `No such module 'SDWebImage'`
- trying to build the project without import the module , it says 
```
Use of undeclared identifier 'UIActivityIndicatorViewStyleLarge'
```
on file `SDWebImageIndicator.m` line 141:
```
indicator.indicatorView.activityIndicatorViewStyle = UIActivityIndicatorViewStyleLarge;
```
and on line 156
```
indicator.indicatorView.activityIndicatorViewStyle = UIActivityIndicatorViewStyleMedium;
```

I know my machine is too old macOS High Sierra 10.13.6 , any chance this can be solved? Or what did I miss?

**Comment by dreampiggy** [comment]
Update to Xcode 11, no other solution.

**Comment by dreampiggy** [comment]
Or you can use the old version SDWebImage 4.x, see Readme there.

**Comment by maverickchangithub** [comment]
> Or you can use the old version SDWebImage update to 5.9.0.
> 
> See: https://github.com/SDWebImage/SDWebImage/releases/tag/5.10.0

Thank you , i will give it a try.
