### ISSUE TITLE
Downloaded image decode failed on webp images

### ISSUE THREAD

**Issue by DanielZanchi** [SDWebImage/SDWebImage#3189]
Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14.4
 SDWebImage Version      | 5.10.4
 Integration Method      |  cocoapods
 Xcode Version           | 12.4

### Issue Description and Steps

I am displaying **webp** images (500x500px, <300kb) in a collection view with a simple:

```
imageView.sd_setImage(with: imageURL) { (image, error, cacheType, url) in
                if let error = error {
                    print("error while getting image: \(error.localizedDescription) with \(url)")
                }
}
```

Every once in a while (1 image every 10) the decoding fails with this error: **"Downloaded image decode failed"**. If i relaunch the app the same image loads correctly and another one may fail.
I already try including the option _.retryFailed_ with no success as it retries if the downloads fails. Here the issue is with the decoding process.

**Comment by dreampiggy** [comment]
Check the setup steps to import the WebPCoder (another Pod, iOS 9+) or AWebPCoder (built-in, iOS 13+):

https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#coder-usage

**Comment by dreampiggy** [comment]
Or maybe you don't setup the MIME type for your image server. See: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#coder-accept-mime-type

**Comment by DanielZanchi** [comment]
I solved the issue by adding the webPCode. Thank you, you can close.
