### ISSUE TITLE
progressBlock will not action after ImageView been delloc and alloc again

### ISSUE THREAD

**Issue by whereAreTheGuGuda** [SDWebImage/SDWebImage#3193]
Info | Value
-- | --
Platform Name | ios
Platform Version | 14.0
SDWebImage Version | 5.10.2
Integration Method | cocoapods
Xcode Version | Xcode 12.0
Repro rate | all the time (100%)
Repro with our demo prj | e.g. does it happen with our demo project?
Demo project link | e.g. link to a demo project that highlights the issue

hi, In my project, an photoBrowser is used to load large images. When the user destroys the photoBrowser before the images are loaded, SDWebimage does not cancel the download. At this time, if I init a photoBrowser again and load the download progress bar of the images in progressblock, I cannot receive the progress of progressblock.
At present, it is very easy to reproduce in the weak network environment.
How can I fix it?

**Comment by dreampiggy** [comment]
It should be called. But may not be the 100% use case you want.

The processBlock is called only after the next bytes received. We don't trigger an initial progress valud.

Assume previouslly you dealloc the View, progress 50%. Next time you will not receive 50% at the beginning. Only after next URLSession callback, and the progress value is 60%.

**Comment by whereAreTheGuGuda** [comment]
Maybe it's because I'm in a weak network environment, which leads to the pictures not being updated. At present, I haven't found the specific reason. I'll confirm it when I have time
