### ISSUE TITLE
Load SVG Image from URL

### ISSUE THREAD

**Issue by Shrutimittal91** [SDWebImage/SDWebImage#3194]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info
Hi,

I tried searching to load the SVG image from URL but found a separate library to do so.  I can see the code related to SVG in the library. Can we use the existing SDWebImage library to load the SVG image from the URL? 
 I am using 'SDWebImage' 5.6'.
 Additionally will it support older versions also?

**Comment by kinarobin** [comment]
@Shrutimittal91 You can have a look in  [SDWebImageSVGKitPlugin](https://github.com/SDWebImage/SDWebImageSVGKitPlugin).

**Comment by Shrutimittal91** [comment]
@kinarobin i am trying to find a way so that i can avoid integrating a new library.  Main library do not support SVG?

**Comment by kinarobin** [comment]
> @kinarobin i am trying to find a way so that i can avoid integrating a new library. Main library do not support SVG?

YES

**Comment by Shrutimittal91** [comment]
@kinarobin There is no workaround that we can follow. I can see there is code related to SVG format in the library. If this library do not support that format then why that code is there?

**Comment by dreampiggy** [comment]
Or you can use https://github.com/SDWebImage/SDWebImageSVGcoder for iOS 13+. Which Apple provide CoreSVG for rendering.

**Comment by dreampiggy** [comment]
> I can see there is code related to SVG format in the library

This is just for convenience because we have two SVG codec (SVGKit or CoreSVG). So I move that into the SDWebImage Core.

But since you don't want to use SVGKit, and you have to support iOS 12-, we have no other solution. You can embed your own implementation by following the [Custom Coder](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-coder-420) steps.

**Comment by Shrutimittal91** [comment]
@dreampiggy by adding  SDWebImageSVGKitPlugin Do we get the SVG support for  below iOS 13.0 ?

**Comment by dreampiggy** [comment]
Yes. See README. Answered this common question.

**Comment by Shrutimittal91** [comment]
@dreampiggy I tried integrating SDWebImageSVGKitPlugin. But the issue is instead of taking the image background it is taking imageview background. Below i have attached the screenshots. Blue one is the original svg that i want to download image but instead it is taking my imageview background. 

<img width="328" alt="Screenshot 2021-03-26 at 3 42 10 PM" src="https://user-images.githubusercontent.com/8266611/112617753-6437c500-8e4b-11eb-97c5-f3c543517bcd.png">

<img width="322" alt="Screenshot 2021-03-26 at 3 54 23 PM" src="https://user-images.githubusercontent.com/8266611/112617886-8c272880-8e4b-11eb-8a0c-84d97ebfab3d.png">




I am using below code 
       
`let svgCoder = SDImageSVGKCoder.shared
        SDImageCodersManager.shared.addCoder(svgCoder)
        cellImage.sd_setImage(with: URL(string: info?.backgroundImage?.svg ?? ""))`

**Comment by wxwlcp** [comment]
svg could not be loaded

**Comment by wenjinfu321** [comment]
> svg could not be loaded

me too
