### ISSUE TITLE
Image cache cannot be cleared in macOS

### ISSUE THREAD

**Issue by qixin1106** [SDWebImage/SDWebImage#3199]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | macOS
 Platform Version        | 11.2.3 (20D91)
 SDWebImage Version      | 5.9.3
 Integration Method      | cocoapods 
 Xcode Version           | Xcode Version 12.4 (12D4e)
 Repro rate              | all the time (100%)
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps

I read the code and found that there is a problem here

### 1
```objc
#if SD_UIKIT || SD_MAC
- (void)applicationWillTerminate:(NSNotification *)notification {
    [self deleteOldFilesWithCompletionBlock:nil];
}
#endif
```
### 2
```objc
- (void)deleteOldFilesWithCompletionBlock:(nullable SDWebImageNoParamsBlock)completionBlock {
    dispatch_async(self.ioQueue, ^{
        [self.diskCache removeExpiredData];
        if (completionBlock) {
            dispatch_async(dispatch_get_main_queue(), ^{
                completionBlock();
            });
        }
    });
}
```
> In the “applicationWillTerminate” method, the “removeExpiredData” method did not work.
> I think in the applicationWillTerminate method, the operation must be performed synchronously.
> Maybe applicationWillTerminate is not the right time.
> Refer to the timing of cleaning files in iOS, you can use the applicationWillResignActive timing to clean up the file cache of macOS.

**Comment by wanhmr** [comment]
> I think in the applicationWillTerminate method, the operation must be performed synchronously.

I have tested for my iPhone6 in 13.6.1 and operations must be performed synchronously in the `applicationWillTerminate `method.

@dreampiggy

**Comment by dreampiggy** [comment]
Using sync version to clean disk cache will cause some IO laggy. I have no evidence that whether this will cause Springboard or some laggy from the end-user or not.

If you think this can works, we can just have a try.

**Comment by dreampiggy** [comment]
applicationWillResignActive seems too frequently for most cases. It's even been called when you pull down notification or phone call. So I just keep placing it into `willTerminate` + `didEnterBackground`
