### ISSUE TITLE
setImage from Data

### ISSUE THREAD

**Issue by DanielZanchi** [SDWebImage/SDWebImage#3200]
Is there a way to use
` _ImageView_.self.sd_setImage(with: URL)` 
**in this way:**
` _ImageView_.self.sd_setImage(with: Data)` 

Instead of passing a URL I would like to pass **Data**.
This because SDWebImage does a very good job with collectionViews and the scrolling is very smooth.
I now have Data retrieved from another service (without URL) and would like to use SDWebImage for the decoding of it and rendering it on the ImageView.

**Comment by dreampiggy** [comment]
You can use the `data://` type URL. Though this may cause some memory peak.

But actually, it's not a good idea to pass data. SDWebImage's loading system include both `Cache`, `Loader`, `Decoder`, `Transformer` and `UIRender`. Seems what you only want is the last 3 one.

You can directlly use the `SDImageCodersManager` with a global GCD queue, then set the decoded image.
