### ISSUE TITLE
Animated Image use Image/IO built in method to force decode question

### ISSUE THREAD

**Issue by KittenYang** [SDWebImage/SDWebImage#3201]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        |  13.0
 SDWebImage Version      5.x lastest
 Integration Method      | manually
 Xcode Version           | Xcode 11
 Repro rate              | all the time (100%)
 Repro with our demo prj | NO
 Demo project link       | 

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

我注意到现在动图解码的方案已经改成了 Image/IO 了，所以我尝试了一下

我尝试用下面的代码在异步线程 force decode 出 UIImage

```objc
- (UIImage *)imageIOWithData:(NSData *)data {
    
    CGImageRef imageRef;
    
    CGImageSourceRef source = CGImageSourceCreateWithData((__bridge CFDataRef)data,
                                                          (__bridge CFDictionaryRef)@{(NSString *)kCGImageSourceShouldCache: @(YES)});
    
    NSDictionary *options = nil;
    options = @{
        (__bridge NSString *)kCGImageSourceShouldCacheImmediately : @(YES),
        (__bridge NSString *)kCGImageSourceShouldCache : @(YES) // Always cache to reduce CPU usage
    };
    imageRef = CGImageSourceCreateImageAtIndex(source, 0, (__bridge CFDictionaryRef)[options copy]);
    
    
    UIImage *image = [[UIImage alloc] initWithCGImage:imageRef scale:[[UIScreen mainScreen] scale] orientation:UIImageOrientationUp];
    
    CGImageRelease(imageRef);
    
    
    return image;
}
```

按理说这个 UIImage 已经有数据了，但是在主线程赋值的时候
```objc
self.largeImageView.image = image
```
依然会发现有解码的操作。

主线程：
![截屏2021-04-02 下午1 48 20](https://user-images.githubusercontent.com/5517281/113385634-1414b180-93bb-11eb-887e-f87b616b04db.png)

Image/IO 异步线程：
![截屏2021-04-02 下午1 48 38](https://user-images.githubusercontent.com/5517281/113385641-1971fc00-93bb-11eb-8e57-9bb2c6aaf4b8.png)

kCGImageSourceShouldCache、kCGImageSourceShouldCacheImmediately 两个参数并没有起到缓存的作用！但是只在 13 系统下，14 主线程不会解码。

但是 iOS14 有其他 bug。看下图，出现了有两份内存：
![截屏2021-04-02 下午8 28 21](https://user-images.githubusercontent.com/5517281/113434474-9f219600-9413-11eb-98eb-d46f00a8693a.png)

一份是后台线程解码获取的数据并缓存，一份是 Core Animation 会拷贝一份之前解码缓存的数据用来显示到屏幕上。虽然主线程没有解码，但是主线程会调用 create_image_by_copying。
![截屏2021-04-02 下午8 24 49](https://user-images.githubusercontent.com/5517281/113434625-e445c800-9413-11eb-9ad2-29ff94efbf56.png)

可以看到主线程占了 35.3% 的时间，高速滑动时候还是会非常卡的。
<img width="454" alt="截屏2021-04-03 上午12 32 01" src="https://user-images.githubusercontent.com/5517281/113434694-03dcf080-9414-11eb-8080-0af17a048ec5.png">

因此结论是：

Force Decode 无论如何都不应该使用 `CGImageSourceCreateImageAtIndex`，`CGImageSourceCreateImageAtIndex` 只能用来替代 `[UIImage imageWithData:]` 解码，真要使用 Image IO 来 Force Decode 应该交给 `CGImageSourceCreateThumbnailAtIndex`. 该方法底层还会调用 `CGContextDrawImageWithOptions` 生成 CG raster data，可以直接用在主线程显示。

<img width="981" alt="截屏2021-04-03 下午1 47 13" src="https://user-images.githubusercontent.com/5517281/113470018-e09e5980-9484-11eb-825a-e1d5b23d3e21.png">

**Comment by dreampiggy** [comment]
Using Chinese:

从你的描述的意思，是需要使用`CGImageSourceCreateThumbnailAtIndex`，并不提供`kCGImageSourceThumbnailMaxPixelSize`，以达到同样的效果？

之所以使用`kCGImageSourceShouldCache`是因为动图解码如果大量分配内存，会造成高OOM，原始逻辑走了Lazy Decoding + `+[SDImageCoderHelper CGImageCreateDecoded]`（后置的一个CGContext绘制）来避免渲染时卡顿，造成了大量用户反馈OOM率偏高，于是改成了这样。

这部分Force Decode的东西是一直遗留过来的功能，本身计划做一个大重构。我先测试一下，使用`CGImageSourceCreateThumbnailAtIndex`是否能直接替代`+[SDImageCoderHelper CGImageCreateDecoded]`，如果可以的话，将Force Decode还是Lazy  Decode逻辑交由DecodingOptions控制（不在上层处理）

**Comment by dreampiggy** [comment]
Using Chinese:

从你的描述来看，是意思可以通过`CGImageSourceCreateThumbnailAtIndex`，options中不传入`kCGImageSourceThumbnailMaxPixelSize`来获得同样的Force Decode功能？

之前采取的方式是通过了`+[SDImageCoderHelper CGImageCreateDecoded]`，在原始ImageIO的Lazy Decoding之后，外置了一个流程绘制CGContext来触发解码，但是这个有很多的副作用（参考：[主流图片加载库所使用的预解码究竟干了什么](https://dreampiggy.com/2019/01/18/%E4%B8%BB%E6%B5%81%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD%E5%BA%93%E6%89%80%E4%BD%BF%E7%94%A8%E7%9A%84%E9%A2%84%E8%A7%A3%E7%A0%81%E7%A9%B6%E7%AB%9F%E5%B9%B2%E4%BA%86%E4%BB%80%E4%B9%88/)，并且与苹果在iOS 14所做的一系列优化背道而驰（这部分我后续会总结一个博客）

这样吧，这部分关于Force Decode的功能我本身就要做一些重构，后续这个不再会通过外置绘制来处理，而交由Decoding Options让Coders自行选择实现（因为除了ImageIO目前就没有解码器有Lazy Decoding的概念）。我在那里验证这个方案可行的话一并处理。

**Comment by KittenYang** [comment]
@dreampiggy  其实就是一个滑动流畅性和内存之间权衡的问题，想要滑动流畅的话那就得提前渲染（也就是说内存会高），想要避免高内存的话就是惰性解码。其实我发现 SD4.x 中的分块渲染 https://github.com/SDWebImage/SDWebImage/blob/d1c75d839709b3f91c82ecf7d3c7665272090456/SDWebImage/Core/SDImageCoderHelper.m#L349 可以很好解决这个问题，不知道为什么不用了？之前也开了讨论中 https://github.com/SDWebImage/SDWebImage/discussions/3192 给出了实验结果。

另外，CGImageSourceCreateThumbnailAtIndex 的最佳实践是设置 kCGImageSourceThumbnailMaxPixelSize（即使导出原尺寸也要设置），并且关闭 kCGImageSourceShouldCacheImmediately 和 kCGImageSourceShouldCache（因为反正已经自己维护了缓存，不需要缓存系统的解码）。

**Comment by dreampiggy** [comment]
> decodedAndScaledDownImageWithImage 可以很好解决这个问题，不知道为什么不用了？

这个工具方法使用了Tile Draw，即一次次按照块来绘制到完整的CGContext上，可以保持总内存峰值在 2x（主要内存分配是CGContext创建的1倍，CGImage自身的1倍，以及每次Tile的大小） 的Pixel Resolution内。

而Thumbnail Decoding是借助解码器自身的能力，比如ImageIO的CGImageSourceCreateThumbnailAtIndex，实现细节来决定的。按照你的Profile来看，它的内存峰值在 3x 的Pixel Resolution（主要内存分配是CGContext创建的1倍，CGImage自身的1倍，以及CGContextDrawImage的一倍+）

具体为什么当时要做这一改动，是因目前的`decodedAndScaledDownImageWithImage`实现不兼容动图，用户反馈在加载4K分辨率的的GIF的Crash，所以需要改成更通用的Thumbnail Decoding模式。

另外，目前的`decodedAndScaledDownImageWithImage`实现照抄于原始苹果实现，但是由于Tile Decoding分片和迭代次数较多，会造成很高的CPU开销（比如在限制内存为20MB时，4K的图像需要循环9次，8K需要36次）

**Comment by dreampiggy** [comment]
具体怎么样平衡和优化这里的老逻辑，我后续会思考和重构一下接口。这部分不应该交由SD上层处理，而是全部由解码器实现

**Comment by KittenYang** [comment]
@dreampiggy  `decodedAndScaledDownImageWithImage` 也可以兼容动态图吧，因为我看现在 SDAnimatedImage 的实现是一个动态 buffer，还是会去 force decode 动图里的每一帧，然后缓存，那么这个动图的 force decode 其实就是 N 个静态图的 force decode，完全可以复用。至于 CPU 的开销我一开始也担心过，但是特地测试了一下，发现和直接渲染大图没有区别，而且反而更快。你也可以亲自试验下。

**Comment by dreampiggy** [comment]
这就我说的，目前的接口和逻辑不匹配。

SDWebImage截止5.11，现在的`decodedAndScaledDownImageWithImage`或者`decodedImage`，是在解码器体系之外的，是SDImageCache/SDImageDownloader负责调用的，所以这是有问题的。换句话说，他不认识也没有办法参与到SDAnimatedImage里面。

我会考虑在下一个中版本5.12中，把decode或者scaleDown这部分，当作decodingOptions传给SDImageCoder，这样Coder就能利用这个信息，自行在返回的Image之前就触发解码。

老的架构设计错误，因为实际上除了ImageIO，所有第三方解码器都没有所谓的预解码，或者Lazy解码的机制。这是ImageIO独享的，应该是ImageIO Coder的内部实现细节，而不是通用逻辑。

**Comment by dreampiggy** [comment]
近期工作调动，暂时没有机会跟进了，当作未来的优化方案
