### ISSUE TITLE
Pod update downgrades to 5.10.4

### ISSUE THREAD

**Issue by wimbledon** [SDWebImage/SDWebImage#3203]
### Issue Description and Steps

When I ran `pod update`, it downgrades the WDWebImage pod from 5.11.0 to 5.10.4.
Is there something wrong with the podspec file?

![image](https://user-images.githubusercontent.com/3291853/113656236-682ed700-96d6-11eb-8f3a-728260ea526e.png)

**Comment by dreampiggy** [comment]
Re-run again. Because of the hotfix issue in #3195 , I re-push the Podspec trunk.

This may take update to 5 minutes for CocoaPods trunk to update

**Comment by dreampiggy** [comment]
Should be OK now.

![image](https://user-images.githubusercontent.com/6919743/113694131-f1a7ce80-9701-11eb-80d2-cd9889bba50f.png)
