### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by lbrndnr** [SDWebImage/SDWebImage#321]
SDWebImage doesn't take the GIF format in account. Additional frames are perpetually lost.
I've written a [small category](https://github.com/larcus94/LBGIFImage) that makes an UIImage out of GIF data. I'd totally add this to your lib by myself but I don't really have time in next couple weeks nor do I feel like breaking half of your code due to the fact that I don't really know SDWebImage too well.

I'd really love to see SDWebImage having GIF support as it may be useful for other folks here too. Looking forward to hearing from you,
Laurin

**Comment by chainone** [comment]
why is this issue closed? It is still the same as RaimundWege mentioned. Did I miss anything here?

**Comment by mythodeia** [comment]
@chainone continue [here](https://github.com/rs/SDWebImage/issues/945)

**Comment by josepaul28** [comment]
You can do something like this:

`
var placeholderImage: UIImage? = nil

//viewDidLoad
if let resourceUrl = NSBundle.mainBundle().URLForResource("loader-64px", withExtension: "gif") {
            if let path = resourceUrl.path where NSFileManager.defaultManager().fileExistsAtPath(path) {
                let placeholderImageView: UIImageView = UIImageView()
                placeholderImageView.sd_setImageWithURL(resourceUrl)
                if let arrayImages = placeholderImageView.image?.images where arrayImages.count > 0 {
                    self.placeholderImage = UIImage.animatedImageWithImages(arrayImages, duration: 0.2)
                }
            }
        }

//cellForItemAtIndexPath
cell.productImageView.sd_setImageWithURL(NSURL(string: image), placeholderImage: self.placeholderImage)
`
