### ISSUE TITLE
SDImageCacheConfig property shouldUseWeakMemoryCache not working

### ISSUE THREAD

**Issue by weiminghuaa** [SDWebImage/SDWebImage#3213]
When app re-enter foreground, or memory warning is triggered, weakCache can hold images which are held strongly by UIImageViews or other live instances can be recovered again, to avoid later re-query from disk cache or network. 

But when reload imageViews in cell, it will call ```sd_setImage```  and then these code  execute to set placeholder, and then 
the UIImage in UIImageView will clear. It cause weakCache clear to, and cell flashing because image need load from disk again.

```
dispatch_main_async_safe(^{
            [self sd_setImage:placeholder imageData:nil basedOnClassOrViaCustomSetImageBlock:setImageBlock cacheType:SDImageCacheTypeNone imageURL:url];
        });
```

Should do this in SDMemoryCache?

```
- (void)didReceiveMemoryWarning:(NSNotification *)notification {
    // Only remove cache, but keep weak cache
    [super removeAllObjects];
    for (id key in [self.weakCache keyEnumerator]) {
        id obj = [self.weakCache objectForKey:key];
        [super setObject:obj forKey:key];
    }
}

- (void)willEnterForeground:(NSNotification *)notification {
    for (id key in [self.weakCache keyEnumerator]) {
        id obj = [self.weakCache objectForKey:key];
        [super setObject:obj forKey:key];
    }
}
```

**Comment by dreampiggy** [comment]
Seems a design bug.

The placeholder will trigger `setImage:` and the `UIImage` may decrease the ref count to 0 and dealloc. So there're no proper timing to sync back the image in weak cache into the memory cache.

**Comment by dourgulf** [comment]
Using SDWebImageDelayPlaceholder option maybe avoid such case.
But SDWebImageDelayPlaceholder will make placeholder  image display only after network failed.
So, I try to add a new option to solve such problem:
https://github.com/SDWebImage/SDWebImage/pull/3214
It can work, but not the perfect solution.

**Comment by dreampiggy** [comment]
Works, but not a good solution.

A better idea may be: 

1. When memory warning (strong cache been purged), mark the flag `not synced`
2. When `not synced`, call `sd_setImage:`, it will not call `setImage:` before memory cache query callback; else continue to the normal steps
3. When memory cache hit the weak cache, sync back to strong cache and clear the flag `not synced`
4. Continue the normal steps

**Comment by dourgulf** [comment]
Yes, it is not a good solution.
Maybe a simple optimize will be work and good: when setting image URL, judge if current showing image is corresponding the setting URL, if so, don't do any change.

**Comment by dreampiggy** [comment]
Don't do any change will break the UICollectionView and UITableView reusing alogirhtm.

Still need to set again.

**Comment by dourgulf** [comment]
Oh, yes.

**Comment by dourgulf** [comment]
I don't understand why only after received memory warning will cause flashing.
I have dig into the code, every time reload data, no memory cache in fact, it will load the image from disk cache, but no flashing, only after received a memory warning once, it will flashing every time reloading data.

**Comment by dourgulf** [comment]
One strange problem, after received memory one time, the strong cache seams not work later
- (void)setObject:(id)obj forKey:(id)key cost:(NSUInteger)g {
    [super setObject:obj forKey:key cost:g];
    NSAssert([self objectForKey:key] != nil, @"not really cache??");
 It will assert failed every time.

**Comment by dourgulf** [comment]
https://stackoverflow.com/questions/27289360/nscache-objectforkey-always-return-nil-after-memory-warning-on-ios-8

**Comment by dreampiggy** [comment]
@dourgulf @weiminghuaa  Please have a check at #3239. I add a extra memory cache query to ensure `weak cache` feature works as expected.

However, due the extra query, so I change the config to disable weak cache by default. If you want to use that to avoid some imagView flashing back when memory warning or entering background, you can enable again.
