### ISSUE TITLE
Fatal crash report: Address Sanitiser detected: out-of-memory

### ISSUE THREAD

**Issue by ramanocs1145** [SDWebImage/SDWebImage#3216]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.4.2
 SDWebImage Version      | 5.10.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.4
 Repro rate              | all the time (100%)

### Issue Description and Steps

I'm getting **Fatal** crash issue like EXC_BAD_ACCESS UIInputWindowController --> dealloc > exceptionWithName:reason:userInfo: > name > reason > Attempted to dereference garbage pointer...

I have traced this crash issue by choosing Address sanitiser with Zombie Objects - I'm getting the crash report like below,
**Thread 18: Address Sanitiser detected: out-of-memory** in debug mode.

I understood this is cause memory issue but doesn't have an idea why it happening and what kind of reason behind this?

![SDWebImageCrashIssue](https://user-images.githubusercontent.com/25265355/115241991-10b15200-a13f-11eb-86b3-ddd236e1dbb0.png)

**Comment by dreampiggy** [comment]
Just OOM. Already show for you.
