### ISSUE TITLE
What is the best approach to load low quality image first followed by its original quality image?

### ISSUE THREAD

**Issue by DavidAmyot** [SDWebImage/SDWebImage#3222]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14.4
 SDWebImage Version      | latest
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.4
 Repro rate              | All the time
 Repro with our demo prj | No, not the same image size
 Demo project link       | nil

### Issue Description and Steps

Hello, I was wondering what would be the best approach to load low quality image first followed by its original quality image? 

I have access to both the low quality and high quality urls of an image and I would like to first load in the low quality and afterwards the high quality image. The reason for that is that many of my images have a big size of like 4000x2000 and even with the `.imageThumbnailPixelSize` context it's not fast enough, at all. However, from my understanding, the completion handler is ran on the main thread by default so would it really be a good idea to do another sd_setImage in there? This is what I currently do but it really is not efficient enough.

### Curent code

```
private func setPictureCell(url_List: [Pictures], indexPath: IndexPath, cell: ProfileShowroomCell, thumbnailSize: CGSize) {
    let currentCellView = cell.placeholderImage
    
    if url_List.count != 0 && indexPath.row < url_List.count {
        if let thumbnail = url_List[indexPath.row].thumbnail, let asset = url_List[indexPath.row].url {
            currentCellView?.sd_setImage(with: URL(string: thumbnail), placeholderImage: nil, options: [], context: nil, progress: nil, completed: { (thumbImage, thumbError, thumbCacheType, thumbUrl) in
                
                if thumbError != nil { // print("[ERROR] We have an error : \(error!)") 
            
                if let thumbImage = thumbImage {
                    currentCellView?.image = thumbImage

                    DispatchQueueService.background {
                        currentCellView?.sd_setImage(with: URL(string: asset), placeholderImage: nil, options: [.avoidAutoSetImage, .lowPriority], context: [.imageThumbnailPixelSize : thumbnailSize], progress: nil, completed: { (originalImage, originalError, originalCecheType, originalUrl) in
                            
                            if originalError != nil { // print("[ERROR] We have an error : \(error!)") }
                            
                            if let originalImage = originalImage {
                                currentCellView?.sd_imageTransition = .fade
                                currentCellView?.image = originalImage
                            }
                        })
                    } completion: {}
                }
            })
        } else {
            print("[ERROR] Could not find the asset.")
        }
    }
}
```

### Questions

1. Is it normal that my error prints (`if thumbError != nil {...}`) always go through when I start scrolling? I've also commented out the print because it's ran on the main thread and it was actually making the collection view less fluid.
2. I'm using a background queue to run the second sd_setImage, definitely not sure if I'm doing it right, hell I'm not too sure it's good procedure to run a background thread inside a main thread.
3. I also use the SDWebImagePhotosPlugin plugin and per the documentation, PhotoKit allows the use of a `PHImageRequestOptionsDeliveryModeOpportunistic` option where it will _return a degraded thumbnail image first and again with the full pixel image_. The fluidity of this process is exactly what I'm seeking, I would much rather have some kind of gradual "fade" just like with this option compared to the normal fade option with sdwebimage. Am I doing something wrong? 

Would it be hard to achieve what I just said in my last question? I really just want to load the thumbnail url image first and then gradually show the original quality image so that the transition is fluid and smooth. 

I'm really a beginner when it comes to coding so I'm open to any suggestion honestly!

Thank you very much for this amazing library!

**Comment by dreampiggy** [comment]
> load low quality image first followed by its original quality image

You can, use [transformer](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#image-transformer-50)


Transformer will download and store/query the full size image, then do transforming with Image Bitmap to scale down its size, and callback.

So, by using this, you can load the full size image its image data from network, but client size only shows the thumbnail size image. Next time you query the full size image, it already in the cache.

To do so, use `.originalStoreCacheType = .disk || .originalQueryCacheType == .disk`, or upgrade to SDWebImage 5.11.1, which by default set these context options. https://github.com/SDWebImage/SDWebImage/releases/tag/5.11.1

**Comment by DavidAmyot** [comment]
> > load low quality image first followed by its original quality image
> 
> You can, use [transformer](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#image-transformer-50)
> 
> Transformer will download and store/query the full size image, then do transforming with Image Bitmap to scale down its size, and callback.
> 
> So, by using this, you can load the full size image its image data from network, but client size only shows the thumbnail size image. Next time you query the full size image, it already in the cache.
> 
> To do so, use `.originalStoreCacheType = .disk || .originalQueryCacheType == .disk`, or upgrade to SDWebImage 5.11.1, which by default set these context options. https://github.com/SDWebImage/SDWebImage/releases/tag/5.11.1

But then how would I call the low quality image before the transformer resized it if in the completion handler it's already resized?

If I understand right and I'm using SDWebImage 5.11.1, I have it like so to use the transformer : 

```
private func setPictureCell(url_List: [Pictures], indexPath: IndexPath, cell: ProfileShowroomCell, thumbnailSize: CGSize) {
        let currentCellView = cell.placeholderImage
        let transformer = SDImageResizingTransformer(size: CGSize(width: 200, height: 200), scaleMode: .fill)
        
        if url_List.count != 0 && indexPath.row < url_List.count {
            if let asset = url_List[indexPath.row].url {
                currentCellView?.sd_setImage(with: URL(string: asset), placeholderImage: nil, options: [], context: [.imageTransformer: transformer], progress: nil, completed: { (image, error, cacheType, url) in

                        if error != nil { /* print("[ERROR] We have an error : \(error!)") */ }
                        
                        if let image = image { currentCellView?.image = image }
                })
            }
        }
    }
```

**Comment by dreampiggy** [comment]
> reinstall it and load the images for the first time

The first time you need to download the full size image data (1), then do full size image decoding (2), and store full size image data into disk cache (3). And in the meantime, do the transformed image decoding (4), store the transformed image and re-encode it into disk cache (5).

So this cause more time.

**Comment by DavidAmyot** [comment]
Ok I see. However, if I wanted to have fast loading even the first time how would I go at it? Not too sure how to chain the loading of low res and high res image 🤔 In the meantime the transformer is better than what I had before though. Thanks a lot for the help, really appreciate it!

**Comment by dreampiggy** [comment]
> if I wanted to have fast loading even the first time how would I go at it

Did you have something local cache image for backup ?

For example, using `additionalCachePathBlock` for your local image backup.

Or, try to use JPEG format, which increase the decoding speed. Or compress more quality for your high resolution image.

Actually, I think the time consuming is `Download`, not the `Decode` part. You can use the instruments to analyze the time.

**Comment by DavidAmyot** [comment]
Well when I load just the low quality urls it's extremely fast and the quality is fine when we look at the cells. What I mean is that if I were to first load the low quality urls, how would I "chain" the downloading of the high res images so that they're available for when we present a cell in fullscreen (without affecting the loading speed of the initial low res images)? Sorry for all the trouble!

**Comment by dreampiggy** [comment]
Seems you have two urls, one for low quality, one for high quality

**Comment by dreampiggy** [comment]
So, you don't need transformer feature at all.

**Comment by dreampiggy** [comment]
Instead, you can use `SDWebImagePrefetcher`, to prefetch the high quality url at the same time when loading low quality url.

**Comment by DavidAmyot** [comment]
>prefetch the high quality url at the same time

But how would I do it at the same time though? I'd call sd_setImage with the low res url and in the completion handler the prefetch? Sorry it's morning and I've never used the prefetcher!

**Comment by dreampiggy** [comment]
In paralles.

ImageView.sd_setImage(with: highResUrl)
SDWebImagePrefetcher.shared.prefetch(urls: [lowResUrl])
