### ISSUE TITLE
Can't get data from cache

### ISSUE THREAD

**Issue by StackHelp** [SDWebImage/SDWebImage#3225]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 14.4
 SDWebImage Version      | Latest
 Integration Method      |  cocoapods 
 Xcode Version           | Xcode 12.4
 Repro rate              |  all the time (100%)
 Repro with our demo prj | Not Tested
 Demo project link       | N/A

### Issue Description and Steps

I am loading animated images with `.webp` format using `imageView.sd_setImage(with: animatedURL, placeholderImage: nil, options: [.progressiveLoad])` and it worked as well So, obviously it cached it in disk but when I tried to fetch it using `SDImageCache.shared.imageFromDiskCache(forKey:  key)` or `SDImageCache.shared.diskImageData(forKey:  key)`, it gives me `nil` value. 

So, how do I get the cached image?

**Comment by dreampiggy** [comment]
You can calculate the cache key using `SDWebImageManager.shared.cacheKey(for: url)`, then feed it into the SDImageCache.


From the theory, this should work. If not, could you please provide a simple demo to let us invetigate ?

**Comment by dreampiggy** [comment]
If you want to query disk cache right in the `completionBlock`, remember by default the write cache is async.

If you want to wait for writing cache finished, use `.waitStoreCache` option. See: https://sdwebimage.github.io/SDWebImage/Enums/SDWebImageOptions.html#/c:@E@SDWebImageOptions@SDWebImageWaitStoreCache

**Comment by StackHelp** [comment]
@dreampiggy Let me test more cases with the scenario you provided and If I still have an issue, I will update you here only.

Thanks for your support
