### ISSUE TITLE
ImageView Cloudn't load image through SDWebImage with url : http://img001.seefm.com.cn/image/lntq1hybqpwk840ckc.jpg?x-oss-process=image/resize,m_mfit,h_320,w_320

### ISSUE THREAD

**Issue by SunshineTraveller** [SDWebImage/SDWebImage#3229]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS
 Platform Version        |  >11.0
 SDWebImage Version      |  5.8.3
 Integration Method      |  cocoapods 
 Xcode Version           | e.g. Xcode 12.3 

### Issue Description and Steps

ImageView Cloudn't load image through SDWebImage with url : http://img001.seefm.com.cn/image/lntq1hybqpwk840ckc.jpg?x-oss-process=image/resize,m_mfit,h_320,w_320

**Comment by kinarobin** [comment]
Use latest SDWebImage 5.11.1, It's OK.
![simulator_screenshot_B4D9E05F-6725-49FA-BC67-D8B4D79ABE90](https://user-images.githubusercontent.com/29303030/135198822-2fc949df-6b42-4ec4-b637-d4c13984289f.png)
