### ISSUE TITLE
The wrong memory cache was used。

### ISSUE THREAD

**Issue by lyp944** [SDWebImage/SDWebImage#3230]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14.5.1
 SDWebImage Version      | 5.11.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.5
 Repro rate              | all the time (100%)
 Repro with our demo prj | No
 Demo project link       | https://github.com/lyp944/SDWebImageMemoryCacheWrongDemo.git

### Issue Description and Steps

When the `SDAnimatedImageView` loads the animatedImage (eg WebP) and `UIImageView` later loads the same animatedImage, `UIImageView` will hit the `SDAnimatedImage` in the memory cache, At this point, `UIImageView` is showing a static image, the wrong cache was used.

当`SDAnimatedImageView`加载动图的时候（比如webp），之后`UIImageView`再加载这个动图时，`UIImageView`会命中内存缓存中的`SDAnimatedImage`，这时候`UIImageView`显示的是一个静态图片,使用了错误的缓存

**Comment by dreampiggy** [comment]
By design.

The issue is that you mixed using `SDAnimatedImageView` and `UIImageView` for the same image. And you want to `Show animation in both cases`.

However, it's wrong.

It can be achieved in theory by caching both two type of object. However think of what you get if you do so:

Assume the image resolution is 1000x1000. 100 frames.

1. A SDAnimatedImage which occupy 1 x 1000 x 1000 x 4 = 3.8MB
2. A UIAnimated image which occupy 100 x 1000 x 1000 x 4 = 381MB
3. Total 385MB

This will cause huge issue for memory.

**Comment by dreampiggy** [comment]
My suggestion is:

Know whether you need animation or not.

If you need animation, use `SDAnimatedImageView`, whatever you actually download a GIF or JPEG.
If you don't need animation, use `UIImageView`. So even if you download GIF, it can render firsrt frame and match your feature request.

If you don't know which to choose, use `SDAnimatedImageView`. Which is superset.

**Comment by lyp944** [comment]
> My suggestion is:
> 
> Know whether you need animation or not.
> 
> If you need animation, use `SDAnimatedImageView`, whatever you actually download a GIF or JPEG.
> If you don't need animation, use `UIImageView`. So even if you download GIF, it can render firsrt frame and match your feature request.
> 
> If you don't know which to choose, use `SDAnimatedImageView`. Which is superset.

Thanks for your answer!
I can understand what you're saying. In most cases, when the image can be a WebP or JPEG, I prefer the `SDAnimatedImageView` to display the image. 
But sometimes (display multiple images at the same time), I don't want to decode the same WebP multiple times (display image faster for next time), and I want to cache all the decoded image frames (now I'm using `UIImageView`).  Any good advice for this situation?

**Comment by lyp944** [comment]
> By design.
> 
> The issue is that you mixed using `SDAnimatedImageView` and `UIImageView` for the same image. And you want to `Show animation in both cases`.
> 
> However, it's wrong.
> 
> It can be achieved in theory by caching both two type of object. However think of what you get if you do so:
> 
> Assume the image resolution is 1000x1000. 100 frames.
> 
> 1. A SDAnimatedImage which occupy 1 x 1000 x 1000 x 4 = 3.8MB
> 2. A UIAnimated image which occupy 100 x 1000 x 1000 x 4 = 381MB
> 3. Total 385MB
> 
> This will cause huge issue for memory.

I understand your concern.
But in this case, updating the memory cache to the recently used image class would be easier to understand, wouldn't it?

Just like here:
```Objc
else if (options & SDImageCacheMatchAnimatedImageClass) {
            // Check image class matching
            Class animatedImageClass = image.class;
            Class desiredImageClass = context[SDWebImageContextAnimatedImageClass];
            if (desiredImageClass && ![animatedImageClass isSubclassOfClass:desiredImageClass]) {
                image = nil;
            }
 }
```

**Comment by dreampiggy** [comment]
> I don't want to decode the same WebP multiple times (display image faster for next time), and I want to cache all the decoded image frames (now I'm using UIImageView). Any suggestion for this situation?

Can be achieved in next minor version. This need a refactory to the current `SDAnimatedImagePlayer`.

The player now, keep the decoded form into the `player-level` cache, which is a `(index, frame)` hash map.

However, a better design is to share the different frame cache across the total framework. For example, whether you share this single player into multiple `SDAnimatedImage`, or display on multiple `SDAnimatedImageView`, they always decode the `same data, same frame index` once, whatever the object is.

**Comment by lyp944** [comment]
> However, a better design is to share the different frame cache across the total framework. For example, whether you share this single player into multiple `SDAnimatedImage`, or display on multiple `SDAnimatedImageView`, they always decode the `same data, same frame index` once, whatever the object is.

That's really a good idea!

It would be better to update the memory cache so that `UIImageView` can play the same animation after `SDAnimatedImageView` has already played it.(https://github.com/SDWebImage/SDWebImage/issues/3230#issuecomment-840446892)
