### ISSUE TITLE
unable to add http header values in sdwebimage swift

### ISSUE THREAD

**Issue by Saravanakumar22** [SDWebImage/SDWebImage#3233]
**swift version**: 5.4
**SDWebImage version**: 5.11.1 
 **XCode:** 12.4

 there is a method available for objective-c       
`        [manager setValue:@"" forHTTPHeaderField:@"key"]
`
but there is no method available for swift.
if anyone has done this before, if so please help

Thanks

**Comment by dreampiggy** [comment]
This API is on `SDWebImageDownloader`, not `SDWebImageManager`.

https://sdwebimage.github.io/SDWebImage/Classes/SDWebImageDownloader.html#/c:objc(cs)SDWebImageDownloader(im)setValue:forHTTPHeaderField:
