### ISSUE TITLE
.refreshCached ignores cached value

### ISSUE THREAD

**Issue by sndive** [SDWebImage/SDWebImage#3240]
### New Issue Checklist

* [x ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           ios 
 Platform Version        any
 SDWebImage Version      5.11.1 
 Integration Method       cocoapods 
 Xcode Version           Xcode 12.5
 Repro rate              100%
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

.refreshCached causes SDWebImageDownloaderIgnoreCachedResponse
this is NOT what the documentation for .refreshCached says:
.refreshCached documentation implies that cache is ignored only if the image in cache is stale
and that the standard NSURLCache mechanism is used then.
That is respecting Last-Modified and/or etag: headers

I'm not sure if SDWebImageDownloaderIgnoreCachedResponse needs a better (less scary) name
or the logic needs fixing. thanks

**Comment by dreampiggy** [comment]
> cache is ignored only if the image in cache is stale

Current implementation check whether `SDImageCache`'s UIImage is equal to `URLSession Cached Image Data and decoded image`

This is long-history issue, but seems no PR is here to fix that.

Solution:
1. Re-implementation HTTP standard E-Tag, Last-Modified, Cache-Control, anything related to HTTP Cache. Without URLSession.
2. Provide a better way to bridge to URLSession, keep the cache logic, but have a better check and ignore double cache issue.
