### ISSUE TITLE
UIView+WebCache crash

### ISSUE THREAD

**Issue by zhongTom** [SDWebImage/SDWebImage#3245]
![image](https://user-images.githubusercontent.com/20367203/120304108-0cfa1900-c302-11eb-87de-670877e72abc.png)
this crash happened since iOS 14.
Please help me to solve this bug,thans very much

**Comment by zhongTom** [comment]
Appears only in versions higher than iOS 14

**Comment by kinarobin** [comment]
@zhongTom Which SD version?

**Comment by LSJCoder** [comment]
I have the same problem in SD version5.11.1

**Comment by LSJCoder** [comment]
I think the problem is Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread

**Comment by zhongTom** [comment]
> @zhongTom哪个 SD 版本？

The version we are using is 5.10.4

**Comment by zhongTom** [comment]
> > @zhongTom哪个SD版本？
> 
> 我们使用的版本是5.10.4

This problem has appeared since the release of iOS14. We have updated version 5.9.5 and version 5.10.4, and the problem still exists

**Comment by zhongTom** [comment]
> @zhongTom哪个 SD 版本？

This problem has appeared since the release of iOS14. We have updated version 5.9.5 and version 5.10.4, and the problem still exists

**Comment by zhongTom** [comment]
> I think the problem is Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread

I think this is not the reason, the crash log has been shown, and the UI operation is performed on the main thread

**Comment by zhongTom** [comment]
After our analysis, we believe that this crash is caused by accessing the memory that has been released. This is another crash log：
![image](https://user-images.githubusercontent.com/20367203/127257564-0169824a-e9c4-474e-8560-1c9a4e565c22.png)
