### ISSUE TITLE
Help: memory issue about a strange picture!!!

### ISSUE THREAD

**Issue by yuman07** [SDWebImage/SDWebImage#3247]
### New Issue Checklist

*  I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
*  I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
*  I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 14.6
 SDWebImage Version      | e.g. 5.11
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 12
 Repro rate              | e.g. all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

服务端下发了一张图片，造成了很多低端机的OOM问题，经排查，发现很多「神奇」之处：
该图片URL:  http://liangcang-material.alicdn.com/prod/upload/7c8cdd03cdcf46fd871ee89428656c3a.jpg

1 该图片为jpg格式，大小为750*433，但是大小却有9MB
2 当使用SDWebImage(5.11)进行加载时，无论开启预解码与否，都会产生一个极大的内存峰值
3 如果把该图片下载到本地，用文件的方式加载，就不会有这个峰值。

如图：
![Snip20210611_2](https://user-images.githubusercontent.com/39876471/121629757-73bfc500-caae-11eb-90dd-d4d725531134.png)
![Snip20210611_5](https://user-images.githubusercontent.com/39876471/121629809-8f2ad000-caae-11eb-9e19-e0b597849ef5.png)

想请问：
 我理解预解码只是把系统自解码的时机提前，两者最终消耗的RAM应该是差不多的，但为何对于这张图片有如此大的差异？
 另外，对于这种「不太正常」的图片，能否在SDWebImage层就能抛出警告之类，让业务方可以自行处理，比如不去加载之类，这总比直接OOM好。

**Comment by iceXice** [comment]
[[SDImageCache sharedImageCache].memoryCache removeAllObjects]; 
这个可以清调内存里面的图片 ，但是治标不治本

**Comment by dreampiggy** [comment]
"极大的内存峰值"是由于CGImageContextDrawImage造成的，会有2倍Bitmap Pixel Buffer的开销。

这部分Apple原生处理会使用 边解码 边渲染的模式，只会有1倍Bitmap Pixel Buffer的开销；在支持的HEVC解码器的iPhone机型上和iOS 13+，还会使用GPU和CPU共享内存来更进一步减少开销。

这部分SD目前已经很久没有跟进苹果的优化了，如果着急，可以手动使用 `.avoidDecodeImage`暂时关闭提前预解码，使用官方的ImageIO的机制来处理

**Comment by dreampiggy** [comment]
对GPU和GPU共享内存，目前只有Private API能够调用，我们无法直接处理，有兴趣可以检查这个分支：
https://github.com/dreampiggy/SDWebImage/tree/iosruface_testing
