### ISSUE TITLE
crash after changing the height of UIImageView which loaded a gif from a URL

### ISSUE THREAD

**Issue by loveNoodles** [SDWebImage/SDWebImage#3248]
### New Issue Checklist
I have an UIImageView, which loaded a gif from a  URL.
After that I changed the the height of that imageView to **0.1** or a value less than **0.1**，then the app crashed.

The crash info is below:
#0	0x00000001a792e5ac in __exceptionPreprocess ()
#1	0x00000001bb9a842c in objc_exception_throw ()
#2	0x00000001a799d4cc in _CFThrowFormattedException ()
#3	0x00000001a799a9ec in -[__NSArrayM insertObject:atIndex:].cold.1 ()
#4	0x00000001a780f744 in -[__NSArrayM insertObject:atIndex:] ()
#5	0x00000001aa720ef4 in -[UIImageView _setImageViewContentsForAnimatedImage:] ()
#6	0x00000001aa7202a0 in -[UIImageView _setImageViewContents:] ()
#7	0x00000001aa721fe0 in -[UIImageView _updateState] ()
#8	0x00000001aa723798 in -[UIImageView _setViewGeometry:forMetric:] ()
#9	0x0000000102958528 in SearchResultView.updateBottomData() 
#10	0x0000000102955ce4 in SearchResultView.setupAfterLoadFinish() 
#11	0x00000001029553b4 in SearchResultView.showResultImplementation() 
#12	0x0000000102955c88 in ResultView.refreshSearchResult() 
#13	0x00000001029503b4 in ResultView.showSearchResultImp(with:) 

If I don't load the gif from the URL, then it's will be ok !
So I think it's a bug caused by SDWebImage.

### Issue Info
Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name                 | ios |
 Platform Version         | all |
 SDWebImage Version     | 5.0.2 |
 Integration Method       |cocoapods|
 Xcode Version           |Xcode 12.2|
 Repro rate             | all the time (100%)|

Thanks ahead.

**Comment by DomRiedweg** [comment]
Warning: checking for `0.1` doesn't solve the problem, use `0.2` or something similar as `0.10001` also crashes. 

We are facing such a crash on iOS 15.6 (xCode 13.4) for width or height. Triggered by `UIImageView.frame = bounds` during an animation.

**Comment by dreampiggy** [comment]
Please have a try with the latest v2.1 ?
