### ISSUE TITLE
FLAnimatedImageView's contents get nil when the view controller disappeared

### ISSUE THREAD

**Issue by Jonathan331** [SDWebImage/SDWebImage#3249]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14.0
 SDWebImage Version      | 5.1.1
 Integration Method      | manually
 Xcode Version           | Xcode 12
 Repro rate              | all the time (100%)
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps

I load a Gif into the FLAnimatedImageView that was added on the viewController, then the FLAnimatedImageView's content  disappeared when another viewController was pushed into the navigationController. And I also found that it happend only when the Gif had limited loopCount.

One of the GIF's causing the issue: https://wallet.95516.com/s/wl/icon/large/liuywqgl210623bjt.gif.

**Comment by zisulu** [comment]
I had met the same problem. I had opened an issue on FLAnimatedImage, but no one replied.
My solution can be used, but not including some special cases, such as using UIPopoverPresentationController, still can cause it to become nil, I can't figure out the reason...), you can modify my solution to suit your situation.
https://github.com/Flipboard/FLAnimatedImage/issues/248
