### ISSUE TITLE
Animated gifs loaded with progressiveLoad option do not animate

### ISSUE THREAD

**Issue by pixelmatrix** [SDWebImage/SDWebImage#3250]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14.5
 SDWebImage Version      | 5.11.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.5.1
 Repro rate              | 100%

### Issue Description and Steps

We use FLAnimatedImageView and SDWebImage + SDWebImage/FLPlugin to render animated gifs from Tenor in our app with `sd_setImage(url:placeholderImage:options:completionHandler:)` along with the `.progressiveLoad` option. It has been working smoothly up until very recently. We're now experiencing a strange issue where initially the GIFs load in as a static image and do not animate, even after waiting for several minutes for them to load. No error is returned in the completion block either. However, if you kill and restart the app the same images now display as animated.

After looking into it, the only relevant change I can see is that we updated SDWebImage from 5.10.x to 5.11.x, and indeed after downgrading back to 5.10.4 the GIFs display as animated once again. I also tried removing the `.progressiveLoad` option with 5.11.1 and that also resolved the issue.

Given that 5.11 made some changes to how progressive decoding works, it seems like that might have broken something, at least with FLAnimatedImage. For now we're going to downgrade, but I wanted to report the issue. Let me know if I can provide more info to debug.

**Comment by dreampiggy** [comment]
FLAnimatedImageView does not supports progressive animation.
Only `SDAnimatedImageView` do.

**Comment by pixelmatrix** [comment]
Ah, okay - good to know! I'll update our code to reflect that
