### ISSUE TITLE
Crash in SDAnimatedWebImageView when using progressiveLoad option

### ISSUE THREAD

**Issue by kevinfarst-earnin** [SDWebImage/SDWebImage#3254]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.x
 SDWebImage Version      | 5.11.1
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 12.5
 Repro rate              | 10%

### Issue Description and Steps

We have receive these two separate but likely related crashes in the past several versions of our app, after the introduction of the `SDAnimatedImageView` into one of our view controllers. This issue has persisted after upgrading from version 5.11.0 to 5.11.1

| Crashed: NSOperationQueue 0x107db70a0 (QOS: DEFAULT) | EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000c15ab2520
|------------------------|----------------------------------------|
| 0  libobjc.A.dylib               |0x1b2ccb020 objc_release + 16
| 1  ImageIO                       |0x19f2da374 IIOImageRead::updateData(__CFData const*, bool) + 132
| 2  ImageIO                       |0x19f20eae0 IIOImageSource::updateData(__CFData const*, bool) + 228
| 3  ImageIO                       |0x19f213c48 CGImageSourceUpdateData + 984
| 4  SDWebImage                    |0x10558a208 -[SDImageIOAnimatedCoder updateIncrementalData:finished:] + 411 (SDImageIOAnimatedCoder.m:411)
| 5  SDWebImage                    |0x10558cc40 SDImageLoaderDecodeProgressiveImageData + 174 (SDImageLoader.m:174)
| 6  SDWebImage                    |0x10559637c __68-[SDWebImageDownloaderOperation URLSession:dataTask:didReceiveData:]_block_invoke + 410 (SDWebImageDownloaderOperation.m:410)
| 7  Foundation                    |0x19efe0850 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
| 8  Foundation                    |0x19eecd740 -[NSBlockOperation main] + 104
| 9  Foundation                    |0x19efe2ca4 __NSOPERATION_IS_INVOKING_MAIN__ + 24
| 10 Foundation                    |0x19eecd3c8 -[NSOperation start] + 808
| 11 Foundation                    |0x19efe374c __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
| 12 Foundation                    |0x19efe31d4 __NSOQSchedule_f + 184
| 13 libdispatch.dylib             |0x19d893fb8 _dispatch_block_async_invoke2 + 148
| 14 libdispatch.dylib             |0x19d885db0 _dispatch_client_callout + 20
| 15 libdispatch.dylib             |0x19d88912c _dispatch_continuation_pop + 416
| 16 libdispatch.dylib             |0x19d888854 _dispatch_async_redirect_invoke + 592
| 17 libdispatch.dylib             |0x19d89693c _dispatch_root_queue_drain + 356
| 18 libdispatch.dylib             |0x19d897120 _dispatch_worker_thread2 + 116
| 19 libsystem_pthread.dylib       |0x1e97417d8 _pthread_wqthread + 216
| 20 libsystem_pthread.dylib       |0x1e974876c start_wqthread + 8

| Fatal Exception: NSRangeException | *** -[__NSFrozenArrayM objectAtIndexedSubscript:]: index 310 beyond bounds for empty array
|---------------------------------|----|
|0  CoreFoundation                |0x187832754 __exceptionPreprocess
|1  libobjc.A.dylib               |0x19c2f97a8 objc_exception_throw
|2  CoreFoundation                |0x1878a4a18 -[__NSCFString characterAtIndex:].cold.1
|3  CoreFoundation                |0x18772e080 -[__NSFrozenArrayM objectAtIndexedSubscript:]
|4  SDWebImage                    |0x1068ab234 -[SDImageIOAnimatedCoder animatedImageDurationAtIndex:] + 641 (SDImageIOAnimatedCoder.m:641)
|5  SDWebImage                    |0x106896ee0 -[SDAnimatedImage animatedImageDurationAtIndex:] + 274 (SDAnimatedImage.m:274)
|6  SDWebImage                    |0x106898690 -[SDAnimatedImagePlayer displayDidRefresh:] + 296 (SDAnimatedImagePlayer.m:296)
|7  SDWebImage                    |0x10689d09c -[SDDisplayLink displayLinkDidRefresh:] + 200 (SDDisplayLink.m:200)
|8  QuartzCore                    |0x18aa957b8 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long)
|9  QuartzCore                    |0x18ab747f4 display_timer_callback(__CFMachPort*, void*, long, void*)
|10 CoreFoundation                |0x187787a5c __CFMachPortPerform
|11 CoreFoundation                |0x1877ad274 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
|12 CoreFoundation                |0x1877ac5f4 __CFRunLoopDoSource1
|13 CoreFoundation                |0x1877a61d8 __CFRunLoopRun
|14 CoreFoundation                |0x1877a5360 CFRunLoopRunSpecific
|15 GraphicsServices              |0x19ede3734 GSEventRunModal
|16 UIKitCore                     |0x18a220584 -[UIApplication _run]
|17 UIKitCore                     |0x18a225df4 UIApplicationMain
|18 Activehours                   |0x104238ab8 main
|19 libdyld.dylib                 |0x187461cf8 start

**Comment by ACFancy** [comment]
@dreampiggy  I also have this problem. 
```objc
UIImage *image = [[UIImage alloc] initWithCGImage:imageRef scale:scale orientation:imageOrientation];
``` 
in SDAnimatedImagePlayer displayDidiRefresh method, execute in background thread may be lead to crash
Reference [this stackoverflow issue](https://stackoverflow.com/questions/37083378/ios-uiimage-initwithcgimagescaleorientation-crashes-on-a-background-thread)
