### ISSUE TITLE
UITableVIewCell inside UICollectionView cell images over lapping randomly 

### ISSUE THREAD

**Issue by vinod1988** [SDWebImage/SDWebImage#3268]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 14.0
 SDWebImage Version      | 5.0.0 
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 12 
 Repro rate              |  sometimes 90% / random
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by kinarobin** [comment]
@vinod1988 Please provide more info in this issues, Such as demo , reproduce code ....
