### ISSUE TITLE
Crashing issue with SDWebImageDownloaderOperation

### ISSUE THREAD

**Issue by mmdock** [SDWebImage/SDWebImage#3272]
* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found one:

Issue: 
https://github.com/SDWebImage/SDWebImage/pull/3167

The issue looks like it might be similar to the merged PR referenced above, the line that seems to be causing issues: https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDWebImageDownloaderOperation.m#L426

I didn't want to make a PR as I wasn't sure the importance of using .copy vs not using that

NSAllocateObject(): attempt to allocate object of class '_NSInlineData' failed

Fatal Exception: NSMallocException
0  CoreFoundation                 0x19438a708 __exceptionPreprocess
1  libobjc.A.dylib                0x1a8e947a8 objc_exception_throw
2  Foundation                     0x195714f64 NSDeallocateObject
3  Foundation                     0x1955f2cac -[_NSPlaceholderData initWithBytes:length:copy:deallocator:]
4  SDWebImage                     0x106829d50 -[SDWebImageDownloaderOperation URLSession:dataTask:didReceiveData:] + 391 (SDWebImageDownloaderOperation.m:391)
5  SDWebImage                     0x1068266b8 -[SDWebImageDownloader URLSession:dataTask:didReceiveData:] + 447 (SDWebImageDownloader.m:447)
6  FirebasePerformance            0x106052fc0 __InstrumentURLSessionDataTaskDidReceiveData_block_invoke + 122 (FPRNSURLSessionDelegateInstrument.m:122)
7  CFNetwork                      0x194b6ac10 _CFNetworkHTTPConnectionCacheSetLimit
8  libdispatch.dylib              0x193f75a84 _dispatch_call_block_and_release

**Comment by Qson8** [comment]
同样遇到了这个问题，版本5.11.1，是否可以回退到某个版本
