### ISSUE TITLE
GIF speed not right in devices with ProMotion refresh rates

### ISSUE THREAD

**Issue by adriana-elizondo** [SDWebImage/SDWebImage#3279]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 15.0
 SDWebImage Version      | 5.12.0
 Integration Method      | cocoa pods
 Xcode Version           | Xcode 13
 Repro rate              | 100%
 Repro with our demo prj | yes
 Demo project link       | n/a

### Issue Description and Steps

With the [ProMotion refresh rates ](https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro) in iPhone 13 Pro and iPad Pro the GIFs played using `SDAnimatedImageView` have the wrong refresh rate

Correct animation                    | Wrong animation                               |
-------------------------|-----------------------------------------------------------------------|
   
![correct_animation](https://user-images.githubusercontent.com/5721324/136060046-5f699e6b-9d74-4cc7-9883-b9090b2c2e2c.gif) |  ![fun_but_wrong_animation](https://user-images.githubusercontent.com/5721324/136060089-8711237b-2ae2-4930-a66e-b7ed2c7748aa.gif)

**Comment by kinarobin** [comment]
Close in #3280
