### ISSUE TITLE
crash   _platform_memmove ()

### ISSUE THREAD

**Issue by a130785** [SDWebImage/SDWebImage#3295]
用SDWebImage会莫名其妙的crash，切换成YYWebImage不会有这个问题

Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001f16f4aa8 in _platform_memmove ()
#1	0x00000001837ae8bc in PNGReadPlugin::copyImageBlockSetAPNG(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) ()
#2	0x00000001836c5f3c in PNGReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) ()
#3	0x0000000183678134 in IIO_Reader::CopyImageBlockSetProc(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) ()
#4	0x0000000183673ac8 in IIOImageProviderInfo::copyImageBlockSetWithOptions(CGImageProvider*, CGRect, CGSize, __CFDictionary const*) ()
#5	0x000000018367bc64 in IIOImageProviderInfo::CopyImageBlockSetWithOptions(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) ()
#6	0x000000018591769c in CA::Render::copy_image(CGImage*, CGColorSpace*, unsigned int, double, double) ()
#7	0x000000018596741c in CA::Render::prepare_image(CGImage*, CGColorSpace*, unsigned int, double) ()
#8	0x00000001858b0c90 in CA::Layer::prepare_commit(CA::Transaction*) ()
#9	0x00000001858c60bc in CA::Context::commit_transaction(CA::Transaction*, double, double*) ()
#10	0x00000001858cf174 in CA::Transaction::commit() ()
#11	0x00000001858b1210 in CA::Transaction::flush_as_runloop_observer(bool) ()
#12	0x0000000181b6f570 in __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ ()
#13	0x0000000181b3e854 in __CFRunLoopDoObservers ()
#14	0x0000000181b398ec in __CFRunLoopRun ()
#15	0x0000000181b4d3c8 in CFRunLoopRunSpecific ()
#16	0x000000019d35e38c in GSEventRunModal ()
#17	0x00000001844f30bc in -[UIApplication _run] ()
#18	0x0000000184270be8 in UIApplicationMain ()
#19	0x0000000104842be4 in main at main.m:15
#20	0x0000000112e49a24 in start ()

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name            | ios 
 Platform Version         |15.0/14.6
 SDWebImage Version      | 5.12.1
 Integration Method       | cocoapods 
 Xcode Version           | Xcode 13.0 
 Repro rate              | all the time (90%) 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

**Comment by shihaos** [comment]
> OOM ,已经解决了

是加锁解决的吗？
