### ISSUE TITLE
cell上加载webp格式的动图,reload之后会变成静态

### ISSUE THREAD

**Issue by bapidashu** [SDWebImage/SDWebImage#3296]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / macos / tvos / watchos
 Platform Version        | e.g. 12.0 / 10.14.0 / 12.0 / 5.0
 SDWebImage Version      | e.g. 5.0.0 / 4.4.0
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 11 / Xcode 10
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.
你好,我现在遇到一个问题,在UICollectionviewCell上通过sdwebimage加载的webp格式的动画图片,调用[uicollectionview reload],不更新数据源,并且如果imageview已经有图片不重新加载的情况下,已经在播放的webp格式的动图会卡在其中一帧,导致原本的动态图片变成了静态的图片
Hello, I am having a problem with [uicollectionView] on UICollectionviewCell Reload], does not update the data source, and if the ImageView already has an image and does not reload, the webP GIF that is already playing will get stuck in one of the frames, causing the original dynamic image to become a static image

**Comment by fengyunjue** [comment]
可能是你在下载图片后，在completed之后调用[uicollectionview reload]，然后collectionView:cellForItemAtIndexPath:方法又会去调用下载图片方法，出现死循环，导致你的webp图片卡顿。如果是这个问题，可以尝试下面的代码。
```
    [self.gifView sd_setImageWithURL:url placeholderImage:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL)  {
        if (cacheType == SDImageCacheTypeNone) {// 仅第一次下载时，调用reloadData
            [collectionView reloadData]
        }
    }];
```

**Comment by bapidashu** [comment]
> ionvi



> 可能是你在下载图片后，在completed之后调用[uicollectionview reload]，然后collectionView:cellForItemAtIndexPath:方法又会去调用下载图片方法，出现死循环，导致你的webp图片卡顿。如果是这个问题，可以尝试下面的代码。
> 
> ```
>     [self.gifView sd_setImageWithURL:url placeholderImage:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL)  {
>         if (cacheType == SDImageCacheTypeNone) {// 仅第一次下载时，调用reloadData
>             [collectionView reloadData]
>         }
>     }];
> ```

额,cell里面set数据源方法目前逻辑简单点来说是下面这样的
if (self.giftView.image == nil) {
    [self.gifView sd_setImageWithURL:url placeholderImage:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL)  {
    }];
}

我们这个业务情景是这样的:
collectionviewcell上有一张图片,加载的是一个十秒左右的webp动图,然后我们逻辑是如果这个控件有图片就不重新调用sd方法,但是cell上有其他数据需要更新的话,还是需要reload一下,实际测试就是reload 之后,虽然没有再去调用sd方法,但是imageview上面的webp动图却卡在了其中的一帧,变成了静态图显示了

现在的显示情况是(不考虑复用),我们现在有八个collectionviewcell,并列两排,每个cell上都显示相同的webp动图显示,并且在动图加载完以后reload,每次reload后大概有三个左右会卡在其中的一帧,其他的就不会卡

**Comment by JustToBeBetter** [comment]
解决了么

**Comment by timerrhythm** [comment]
我遇到的问题是，webp的刷新在reload之前，就会出现webp变成静态的情况。webp在cellForItemAtIndexPath的时候刷新就是可以

**Comment by bapidashu** [comment]
> 我遇到的问题是，webp的刷新在reload之前，就会出现webp变成静态的情况。webp在cellForItemAtIndexPath的时候刷新就是可以

应该是类似的情况

**Comment by JIabao1** [comment]
我也遇到了同样问题
1、iPhone 11Pro ，14.4系统，通过cell加载webp动图，cell滑动超出屏幕，再次显示该cell时，cell所持有的imageVIew不调用sd_setImageWithURL:方法，imageView显示的动图会卡在某一帧，点击imageView后，动画就正常了。

2、iPhone XR ，12.4系统，通过cell加载webp动图，cell滑动超出屏幕，再次显示该cell时，cell所持有的imageVIew不调用sd_setImageWithURL:方法，imageView不显示图片，点击imageView后，动画就正常了。

复现demo核心代码如下，cell只在创建时，设置webp动图。
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
   
    if (indexPath.row == 0) {
       **MyCell *cell  = [tableView dequeueReusableCellWithIdentifier:@"MyCell"];
        if (!cell) {
            cell = [[MyCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"MyCell"];
            cell.imageURL = @"https://p.upyun.com/demo/webp/webp/animated-gif-1.webp";
        }
        return cell;**
    }else {
        UITableViewCell *cell  = [tableView dequeueReusableCellWithIdentifier:@"cellID"];
        if (!cell) {
            cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"cellID"];
            cell.selectionStyle = UITableViewCellSelectionStyleNone;
            cell.backgroundColor = [UIColor clearColor];
            cell.contentView.backgroundColor = [UIColor clearColor];
            cell.layer.zPosition = 1;
            cell.textLabel.text = @"侧滑删除按钮偏移测试";
        }
        return cell;
    }
}

**Comment by JIabao1** [comment]
复现demo
[NewXcodeTest.zip](https://github.com/SDWebImage/SDWebImage/files/9196822/NewXcodeTest.zip)
1、iPhone 11Pro ，14.4系统
https://user-images.githubusercontent.com/9211599/181211444-4f361adb-b31b-4e3c-8320-badac86a594c.MP4

2、iPhone XR ，12.4系统 录屏
https://user-images.githubusercontent.com/9211599/181211555-df56d951-b207-41a0-96c6-2f11673ced19.MP4

**Comment by JIabao1** [comment]
https://stackoverflow.com/questions/36834341/uiimage-created-with-animatedimagewithimages-have-bugs
好像是苹果bug导致的。

**Comment by dreampiggy** [comment]
Did you try SDWebImge latest v5.13.2 version ?

**Comment by dreampiggy** [comment]
> [NewXcodeTest.zip](https://github.com/SDWebImage/SDWebImage/files/9196822/NewXcodeTest.zip) 

This demo is not available.

**Comment by JIabao1** [comment]
This one :
[NewXcodeTest.zip](https://github.com/SDWebImage/SDWebImage/files/9240950/NewXcodeTest.zip)

**Comment by LMzishimumu** [comment]
这个问题有办法解决么，我更新了最新的版本，也是一样的，如果cell滑出屏幕，再滑回来不重新调加载的方法，就不会动了。但是webp解包比较慢，我们又不想重复加载

**Comment by dreampiggy** [comment]
If you means `UIImageView` and `UIImage`, it's Apple's bug for UICollectionViewCell/UITableViewCell. Because it use CAKeyframeAnimation in implementation. 

Use `SDAnimatedImageView` and `SDAnimatedImage` instead. You can re-call `startAnimating` or `stopAnimating` if you custom the load point
