### ISSUE TITLE
Unable to decode this picture in iOS 14

### ISSUE THREAD

**Issue by 451222664** [SDWebImage/SDWebImage#3298]
### New Issue Checklist

* I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS / iPhone 12
 Platform Version        | iOS 14.3
 SDWebImage Version      | 5.11.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.5

### Issue Description and Steps

Unable to decode this picture

![RED_COLOR](https://user-images.githubusercontent.com/16403304/140468665-cdd6ac83-8fbd-4ae7-a324-d32dd1105f50.jpg)

some : Error Domain=SDWebImageErrorDomain Code=1001 "Downloaded image decode failed" UserInfo={NSLocalizedDescription=Downloaded image decode failed}

**Comment by 475288550** [comment]
I have the same problem as you. Have you solved it?

**Comment by 451222664** [comment]
> I have the same problem as you. Have you solved it?

I use SDWebImageWebPCoder solve this issue.

**Comment by 451222664** [comment]
Error Domain=SDWebImageErrorDomain Code=1001 "Downloaded image decode failed" UserInfo={NSLocalizedDescription=Downloaded image decode failed}

Quick Count  ( 1000 /1000 records )
iOS version
15.1：30.0%
14.8.1：19.2%
15.1.1：19.0%
14.7.1：5.6%
15.0.2：4.7%
