### ISSUE TITLE
i can't stop the GIF animation

### ISSUE THREAD

**Issue by BalajiAnandan15** [SDWebImage/SDWebImage#3307]
OBJECTIVE C: 
Need help to Stop animating the GIF animation on UIImageView, I used GIPHY POD for stickers & GIF.

**My Implementation:
in TableView Delegate: willDisplayCell**
[gifCell.ImageImageView setSd_imageIndicator:SDWebImageActivityIndicator.grayIndicator];
[gifCell.ImageImageView sd_setImageWithURL:[NSURL URLWithString:message.mediaMessage.fileURL] placeholderImage:nil];

in TableView Delegate: didEndDisplayingCell
I will set the Thumbimage of the GIF/Sticker when the cells aren't visible.

**Required Feature:
The requirement is:** On the visible index it needs to be played only once when it is **Received or Sent.**

So I need to stop the animation, but I can't do that.

**Followed this:** https://github.com/SDWebImage/SDWebImage/issues/2724
But none helped.

Tried with UIImageView.AnimationRepeatCount, it also didn't help. So someone help me to stop the animation and need to use the animation repeat count feature with this pod.

**Comment by iMostfa** [comment]
change your ImageImageView type to be `SDAnimatedImageView`, instead of `UIImageView`.
then calling `stopPlaying()` or `ImageImageView.player?.stopPlaying()` should work.

**Comment by dreampiggy** [comment]
GIF or WebP format data can control its own loop count. (0 means infinity)
If you want animated image view play once. You can also try setting the `animationRepeatCount` to 1 as well. Which force any `SDAnimatedImage` on this `SDAnimatedImageView` to only place once.

**Comment by dreampiggy** [comment]
Note:

UIImageView and `UIAnimatedImage` can not use that `animationRepeatCount`. This is Apple's API design. If you really want to use that, do like this:

```
// Not do this
// imageView.image = image;

// Do like this
imageView.animationRepeatCount = image.sd_imageLoopCount; // optional, you can force to 1 here
imageView.animationImages = image.images;
imageView.animationDuration = image.animationDuration
imageView.startAnimating();
```

See wiki for more info about `UIAnimatedImage vs SDAnimatedImage`: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50
