### ISSUE TITLE
use imageFromDiskCacheForKey make cache from SDFLAnimatedImage to _UIAnimatedImage

### ISSUE THREAD

**Issue by tangbl93** [SDWebImage/SDWebImage#3313]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 15.0
 SDWebImage Version      | e.g. 5.0.0 / 4.4.0
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | 13.1 (13A1030d)
 Repro rate              | 100%
 Repro with our demo prj | SDWebImageFLPlugin example project can repro
 Demo project link       | 

```
/// SDWebImageFLPlugin example modify
@interface SDViewController () {
    FLAnimatedImageView *animatedImageView;
}

@end

@implementation SDViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    
	// Do any additional setup after loading the view, typically from a nib.
    animatedImageView = [[FLAnimatedImageView alloc] initWithFrame:self.view.frame];
    animatedImageView.contentMode = UIViewContentModeScaleAspectFit;
    [self.view addSubview:animatedImageView];
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    NSString *url = @"https://raw.githubusercontent.com/liyong03/YLGIFImage/master/YLGIFImageDemo/YLGIFImageDemo/joy.gif";
    UIImage *image = [[SDImageCache sharedImageCache] imageFromDiskCacheForKey:url];
    
    [animatedImageView sd_setImageWithURL:[NSURL URLWithString:url]];
}

@end
```

### Issue Description and Steps

1. download SDWebImageFLPlugin example project, and modify `SDViewController` use avove code
2. After touch, the `obj` will from `SDFLAnimatedImage` become  `_UIAnimatedImage`, and app will crash due to memery issues

![image](https://user-images.githubusercontent.com/13956214/148156422-6673cbd6-7ecd-4a4c-b594-e94d7e44a6fc.png)

**Comment by dreampiggy** [comment]
Using the options arg `SDWebImageMatchAnimatedImageClass` with the API `imageFromCacheForKey:options:context:`
