### ISSUE TITLE
【优化】使用一个方法，加载GIF图时内存占用显著减少，效果却能保持完全一样~

### ISSUE THREAD

**Issue by Vesentanger** [SDWebImage/SDWebImage#3314]
在SDImageIOAnimatedCoder.m的+ (UIImage *)createFrameAtIndex:(NSUInteger)index source:(CGImageSourceRef)source scale:(CGFloat)scale preserveAspectRatio:(BOOL)preserveAspectRatio thumbnailSize:(CGSize)thumbnailSize options:(NSDictionary *)options方法最后，对image进行一次处理，不改变分辨率不改变显示效果，就能很好的降低内存使用：
#if SD_UIKIT || SD_WATCH
    UIImageOrientation imageOrientation = [SDImageCoderHelper imageOrientationFromEXIFOrientation:exifOrientation];
    UIImage *image = [[UIImage alloc] initWithCGImage:imageRef scale:scale orientation:imageOrientation];
#else
    UIImage *image = [[UIImage alloc] initWithCGImage:imageRef scale:scale orientation:exifOrientation];
#endif
    CGImageRelease(imageRef);
    
    UIGraphicsBeginImageContextWithOptions(image.size, NO, 1);
    [image drawInRect:CGRectMake(0, 0, image.size.width, image.size.height)];
    UIImage* scaledImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return scaledImage;

是什么原因呢？

**Comment by dreampiggy** [comment]
See: [https://dreampiggy.com/2019/01/18/%E4%B8%BB%E6%B5%81%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD%E5%BA%93%E6%89%80%E4%BD%BF%E7%94%A8%E7%9A%84%E9%A2%84%E8%A7%A3%E7%A0%81%E7%A9%B6%E7%AB%9F%E5%B9%B2%E4%BA%86%E4%BB%80%E4%B9%88/](主流图片加载库所使用的预解码究竟干了什么)

**Comment by tomsemi** [comment]
mark
