### ISSUE TITLE
Is there a plan to support libpag ?

### ISSUE THREAD

**Issue by shixiaoda** [SDWebImage/SDWebImage#3317]
libpag: https://github.com/Tencent/libpag

**Comment by dreampiggy** [comment]
No extra plan.

You can see wiki toturial to learn how to write a coder plugin: 
https://github.com/SDWebImage/SDWebImage/wiki/Coder-Plugin-List.

APIs available here, not hard to use: 
https://sdwebimage.github.io/SDWebImage/Protocols/SDImageCoder.html
