### ISSUE TITLE
bmp image With imageFromDiskCacheForKey can't load in iOS15.2 and later

### ISSUE THREAD

**Issue by JzwOnly** [SDWebImage/SDWebImage#3330]
test bmp url: `https://raw.githubusercontent.com/JzwOnly/unMec/main/001.bmp`
SDWebImage Version: 5.12.3
iPhone in iOS 14.8 is ok
when I update to iOS 15.3.1 this bmp url can't show but disk memory bmp image no error

**Comment by JzwOnly** [comment]
This is Demo for test 
[BMPTest.zip](https://github.com/SDWebImage/SDWebImage/files/8159223/BMPTest.zip)

1. `image = [[SDImageCache sharedImageCache] imageFromDiskCacheForKey:key];`
2. `NSString * filePath = [[SDImageCache sharedImageCache] cachePathForKey:key];
        image = [UIImage imageWithContentsOfFile:filePath];`
`1` don't work show image, but `2` is ok

**Comment by JzwOnly** [comment]
This is Demo Video

Uploading RPReplay_Final1646116004.MP4…

**Comment by JzwOnly** [comment]
This is Demo Video
https://user-images.githubusercontent.com/21191349/156117005-87bf5218-3c9e-4983-8a76-4663bf1a5c85.MP4

**Comment by JzwOnly** [comment]
> > This is Demo for test [BMPTest.zip](https://github.com/SDWebImage/SDWebImage/files/8159223/BMPTest.zip)
> > 
> > 1. `image = [[SDImageCache sharedImageCache] imageFromDiskCacheForKey:key];`
> > 2. `NSString * filePath = [[SDImageCache sharedImageCache] cachePathForKey:key]; image = [UIImage imageWithContentsOfFile:filePath];`
> >    `1` don't work show image, but `2` is ok
> 
> I test with you demo. `1` and `2` work perfect in iPhone 12 && iOS 15.3.1

Are you use Simulator or real machine？
I test this demo in real machine（IPhoneXS and iPad Pro） `1` not work, `2` is ok

**Comment by JzwOnly** [comment]
> This is Demo Video https://user-images.githubusercontent.com/21191349/156117005-87bf5218-3c9e-4983-8a76-4663bf1a5c85.MP4

@kinarobin This video demo was shot with an iPad Pro
use ImageData to create Image is not work such as `1`, but use filePath to create is ok.
I had to setup image with filePath in completeBlock  again to fix it.
have better solution?

**Comment by dreampiggy** [comment]
Seems this API cause failure:

```
[SDImageCoderHelper decodedImageWithImage:image]
```

**Comment by dreampiggy** [comment]
Seems bug. CGContext should convert the RGBX8888 to our BGRA8888, however it failed on iOS 15.3+

A quick hack is to check the fomat and use the input CGImage's bitmap info to create CGContext

**Comment by dreampiggy** [comment]
I'll check whether vImage can convert this CGImage, if ImageIO fails, may all the `UIImage+Transform` API like `sd_scaledImage` will faill on this CGImage as well.

**Comment by dreampiggy** [comment]
One small question: 

What's the meaning of `[DP]` and `[IP]` when print CGImage in debugger (seems via `image_copy_format_description`)

```
<CGImage 0x7fdf13f16d10> (DP)
	<<CGColorSpace 0x6000007ad2c0> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)>
		width = 1080, height = 1080, bpc = 8, bpp = 32, row bytes = 4320 
		kCGImageAlphaNoneSkipFirst | kCGImageByteOrder32Little  | kCGImagePixelFormatPacked 
		is mask? No, has masking color? No, has soft mask? No, has matte? No, should interpolate? Yes


// This one before PR #3332
<CGImage 0x7f8e2510abd0> (IP)
	<<CGColorSpace 0x60000049c420> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)>
		width = 1080, height = 1080, bpc = 8, bpp = 32, row bytes = 4320 
		kCGImageAlphaNoneSkipLast | 0 (default byte order)  | kCGImagePixelFormatPacked 
		is mask? No, has masking color? No, has soft mask? No, has matte? No, should interpolate? Yes		

// This one after PR #3332 
<CGImage 0x7fee621073a0> (DP)
	<<CGColorSpace 0x600002315620> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)>
		width = 1080, height = 1080, bpc = 8, bpp = 32, row bytes = 4320 
		kCGImageAlphaNoneSkipLast | 0 (default byte order)  | kCGImagePixelFormatPacked 
		is mask? No, has masking color? No, has soft mask? No, has matte? No, should interpolate? Yes
```

The previous SDWebImage decoded image seems always use `IP`, but after changes it will show `DP` and works great.

**Comment by dreampiggy** [comment]
Released [v5.12.4](https://github.com/SDWebImage/SDWebImage/releases/tag/5.12.4)

**Comment by dreampiggy** [comment]
One tip: For new user who don't want that `Force Decode`, you can disable that when initialize SDWebImage.

See: 

```objc
SDWebImageManager.sharedManager.optionsProcessor = [SDWebImageOptionsProcessor optionsProcessorWithBlock:^SDWebImageOptionsResult * _Nullable(NSURL * _Nullable url, SDWebImageOptions options, SDWebImageContext * _Nullable context) {
     // Disable Force Decoding in global, may reduce the frame rate
     options |= SDWebImageAvoidDecodeImage;
     return [[SDWebImageOptionsResult alloc] initWithOptions:options context:context];
}];
```

**Comment by dreampiggy** [comment]
Can anyone limit the effect iOS version for this bug ?

I have no extra iPhones, but tested with iPhone 15.2 simulator

I found the reproduce way:

If CGContext: BGRX8888,
input CGImage: RGBX8888
CGContextDrwaImage will always return blank

However, if CGContext is BGRA8888(alpha channel), everything works.

**Comment by dreampiggy** [comment]
> Can anyone limit the effect iOS version for this bug ?
> 
> I have no extra iPhones, but tested with iPhone 15.2 simulator
> 
> I found the reproduce way:
> 
> If CGContext: BGRX8888, input CGImage: RGBX8888 CGContextDrwaImage will always return black.
> 
> However, if CGContext is BGRA8888(alpha channel), everything works.

Check result:
+ iOS 14.8: works
+ iOS 15.0: fail
+ iOS 15.2: fail
+ iOS 15.3.1: fail

I assume this is a iOS 15+ only bug.

#eproduce Demo: https://github.com/dreampiggy/CGContextDrawImageBug
