### ISSUE TITLE
Blended color layer increased when I use SDWebImageContextOption.imageTransformer

### ISSUE THREAD

**Issue by duydph** [SDWebImage/SDWebImage#3335]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |   ios
 Platform Version        |  15.3.1
 SDWebImage Version      |  5.12.5
 Integration Method      |  cocoapods
 Xcode Version           |   Xcode 13

### Issue Description and Steps

Blended color layer increased when I use SDWebImageContextOption.imageTransformer

When I use:
<img width="708" alt="Screen Shot 2022-03-26 at 11 39 01" src="https://user-images.githubusercontent.com/7614524/160225388-c340f1e2-2fd8-4aab-b601-9aeacc71c17f.png">
Result:
<img width="344" alt="Screen Shot 2022-03-26 at 11 33 56" src="https://user-images.githubusercontent.com/7614524/160225393-5e373aa1-5e21-4b75-b41c-4609b61467fb.png">

But when i tried to use SDWebImageContextOption.imageTransformer:
<img width="679" alt="Screen Shot 2022-03-26 at 12 07 43" src="https://user-images.githubusercontent.com/7614524/160225615-273cf1df-acdc-4ca1-8090-52e75e03b87e.png">
Result:
<img width="344" alt="Screen Shot 2022-03-26 at 11 45 15" src="https://user-images.githubusercontent.com/7614524/160225398-e218c4bd-ca6a-4e74-9b92-a64f70269539.png">

Can anybody help me! I don't want to increase "Blended color layer". Give me what and how I can fix it?
Thanks

**Comment by dreampiggy** [comment]
This transformer has to re-draw that bitmap into CGContext, so, it must cause a `blended` color.

Another way to re-rasterize the image, or use CIFilter, but which has its own disadvantage on RAM usage

**Comment by duydph** [comment]
> This transformer has to re-draw that bitmap into CGContext, so, it must cause a `blended` color.
> 
> Another way to re-rasterize the image, or use CIFilter, but which has its own disadvantage on RAM usage

Thank you
