### ISSUE TITLE
The expectedSize in progress block always 0?

### ISSUE THREAD

**Issue by j2live** [SDWebImage/SDWebImage#334]
Why the expectedSize = 0 ?
Can not get the total size of the image in the progress block using

[imageView setImageWithURL:imgUrl
                               placeholderImage:nil
                                        options:SDWebImageProgressiveDownload
                                       progress:^(NSUInteger receivedSize, long long expectedSize){......}  completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType){......}

**Comment by elburro1887** [comment]
Im also seeing this issue on 3.7.2

First i thought it was because my web server was not outputting the "Content-Size" HTTP header, but even after adding that, it still outputs 0.

**Comment by pratik1311** [comment]
Hi

I am still facing the same issue. When I tried to download image I am always getting expected size 0.
Can any one please help me.

Thanks.

**Comment by KDTechniques** [comment]
I also had the same issue, in my case I was downloading a GIF, so I changed the URL and tried to download another GIF image and I got the total size. It's not a bug.

total size was -1 and 0 for: https://www.icegif.com/wp-content/uploads/2023/03/icegif-1393.gif
received total size for: https://cdn.pixabay.com/animation/2022/10/11/09/05/09-05-26-529_512.gif
