### ISSUE TITLE
Crash on iPad in -[SDWebImageDownloadToken initWithDownloadOperation:] + 534 with version 5.12.5

### ISSUE THREAD

**Issue by wang-yapu** [SDWebImage/SDWebImage#3341]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iPadOS
 Platform Version        | 12, 14, 15
 SDWebImage Version      | 5.12.5
 Integration Method      |  cocoapods 
 Xcode Version           | Xcode 12
 Repro rate              |  sometimes 
 Repro with our demo prj | no
 Demo project link       | no

### Issue Description and Steps
First of all, thank you for your great project! 

I can not repro this crash on my device ( iPad 6th generation, iOS 15.2), but this issue happened many times reminded by Firebase.

#### crash logs

```

已崩溃：com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000008


Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x26b84 objc_moveWeak + 208
1  CoreFoundation                 0x15e218 _CFXNotificationRegistrarAddObserver + 372
2  CoreFoundation                 0x15e038 CFXNotificationRegistrarAdd + 556
3  CoreFoundation                 0x82d88 _CFXNotificationRegisterObserver + 240
4  Foundation                     0x7ec0 -[NSNotificationCenter addObserver:selector:name:object:] + 432
5  Edu901iPhone                   0x1bbe6c0 -[SDWebImageDownloadToken initWithDownloadOperation:] + 534 (SDWebImageDownloader.m:534)
6  Edu901iPhone                   0x1bbcbd0 -[SDWebImageDownloader downloadImageWithURL:options:context:progress:completed:] + 255 (SDWebImageDownloader.m:255)
7  Edu901iPhone                   0x1bbebc0 -[SDWebImageDownloader(SDImageLoader) requestImageWithURL:options:context:progress:completed:] + 609 (SDWebImageDownloader.m:609)
8  Edu901iPhone                   0x1bc691c -[SDWebImageManager callDownloadProcessForOperation:url:options:context:cachedImage:cachedData:cacheType:progress:completed:] + 397 (SDWebImageManager.m:397)
9  Edu901iPhone                   0x1bc5dec __89-[SDWebImageManager callCacheProcessForOperation:url:options:context:progress:completed:]_block_invoke + 289 (SDWebImageManager.m:289)
10 libdispatch.dylib              0x2a84 _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x481c _dispatch_client_callout + 20
12 libdispatch.dylib              0x12c70 _dispatch_main_queue_callback_4CF + 884
13 CoreFoundation                 0xa3340 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
14 CoreFoundation                 0x9d218 __CFRunLoopRun + 2524
15 CoreFoundation                 0x9c308 CFRunLoopRunSpecific + 600
16 GraphicsServices               0x3734 GSEventRunModal + 164
17 UIKitCore                      0xbca75c -[UIApplication _run] + 1072
18 UIKitCore                      0xbcffcc UIApplicationMain + 168
19 Edu901iPhone                   0x4cc7f4 main + 16 (main.m:16)
20 libdyld.dylib                  0x1cf8 start + 4

```

### What did I do recently 

I upgraded SDWebImage from 5.0.6 to 5.12.5 in the last version, the crash rate raised 2 times.

### Other issues
Firebase shows other crashes also, I don't know if I should post a new Issue or just paste it here, if you think I should post a new issue, please let me know.

```
已崩溃：com.hackemist.SDImageCache
SIGSEGV 0x00000000000003d0

SDImageIOAnimatedCoder.m line 193
+[SDImageIOAnimatedCoder createFrameAtIndex:source:scale:preserveAspectRatio:thumbnailSize:options:]
```

```
已崩溃：com.hackemist.SDImageCache
SIGSEGV 0x0000000000000018

SDGraphicsImageRenderer.m line 228
-[SDGraphicsImageRenderer imageWithActions:]
```

If you need more information, let me know and I will post them ASAP. 

Thanks a lot.

**Comment by ssm-heecheon** [comment]
I have got exactly the same report, crashed with iPhone 6s Plus (iOS 15.5)

**Comment by codeflying** [comment]
I have got exactly the same issue on SDWebImage 5.12.6

**Comment by aplusm** [comment]
The exact same bugs occurs on version 5.14.2

**Comment by kakaku-yamaguchi-shota** [comment]
Me too. I have the exact same bug with version 5.14.2.

After rolling back to version 5.13.4, which was used before the upgrade, it was temporarily resolved.

**Comment by mmdock** [comment]
seeing this crash, sdwebimage version 5.17.0, integrated with SPM, xcode 14.2, line SDWebImageDownloader.m:524

**Comment by dreampiggy** [comment]
I guess the notification center related code already changed: 
https://github.com/SDWebImage/SDWebImage/pull/3619

**Comment by dreampiggy** [comment]
duplicated for #3610
