### ISSUE TITLE
SDImageCache should not call beginBackgroundTaskWithExpirationHandler in applicationDidEnterBackground

### ISSUE THREAD

**Issue by jerrydudu** [SDWebImage/SDWebImage#3343]
In the document of Apple about the [beginBackgroundTaskWithExpirationHandler](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtaskwithexpiratio)

It say that "If you call this method shortly before your app is due to be suspended, there’s a chance that the system might suspend your app before that task assertion is granted. For example, don’t call this method at the very end of your [applicationDidEnterBackground:](doc://com.apple.documentation/documentation/uikit/uiapplicationdelegate/1622997-applicationdidenterbackground?language=occ) method and expect your app to continue running"

SDWebImage Call this When UIApplicationDidEnterBackgroundNotification was posted, I think it may not a good time, because the AppDelegate may call applicationDidEnterBackground earlier.

I think it will be a risk that will terminate the app for cumulativeBackgroundTaskAssertionTimeoutExitCount.

**Comment by dreampiggy** [comment]
This seems a old feature from SD v3.0

You can disable the defaults on using `shouldRemoveExpiredDataWhenTerminate`

**Comment by jerrydudu** [comment]
> This seems a old feature from SD v3.0
> 
> You can disable the defaults on using SDImageCacheConfig's `shouldRemoveExpiredDataWhenTerminate = NO`

Thank you, get it.
