### ISSUE TITLE
macOS build Xcode 14.0

### ISSUE THREAD

**Issue by mariohahn** [SDWebImage/SDWebImage#3352]
Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name.                            |   macOS
 Platform Version                         |    12.4
 SDWebImage Version   |   5.12.5
 Integration Method    |   SPM
 Xcode Version        |    14.0 Beta 1
 Repro rate         |     100%

<img width="1349" alt="Bildschirmfoto 2022-06-07 um 17 13 33" src="https://user-images.githubusercontent.com/915933/172416740-7ac513de-3124-4f49-8490-b7c4138ea5cd.png">

**Comment by dreampiggy** [comment]
Fixed in [5.12.6](https://github.com/rs/SDWebImage/releases/tag/5.12.6)
