### ISSUE TITLE
SDMemoryCache  dealloc崩溃

### ISSUE THREAD

**Issue by Enter133** [SDWebImage/SDWebImage#3371]
![image](https://user-images.githubusercontent.com/107378371/179146016-516e3312-7e50-422a-a7c9-4a010f885029.png)

![image](https://user-images.githubusercontent.com/107378371/179145913-61d59abc-7a18-4b5e-9805-168640d4721d.png)

**Comment by dreampiggy** [comment]
Check your code firstly.

Seems you use objc_associatedObject to bind a `SDImageCache` to `UIImage`, which cause the recursive deallocating.

Because SDMemoryCache is a NSCache, which may keep a strong references -> UIImage
UIImage -> SDImageCache -> SDMemoryCahe

**Comment by vlightvDev** [comment]
> 

I had the same problemt,there were a lot of crashes
That's how I use it
![A8F816D5-C2AC-4338-BB61-B744CBBE5F57](https://user-images.githubusercontent.com/112917010/197100186-cfb10757-6f1a-4c05-8ed4-c20caf4881ac.png)

I found that SDImageCache binds the context to the image
![E07A466A-A6FC-4FE9-9D9E-6EA9F28C25E8](https://user-images.githubusercontent.com/112917010/197100377-cb170e0e-fa67-4d92-b101-81f7dc2fa52f.png)

**Comment by dreampiggy** [comment]
Your code cause the recursive retain and so it leaks memory for the memory cache object.

A fix can be either applys from SDK (SD) which beed breaking APIs. Because currently we don't know which context is only decoding related, which is not.

 or user site (Use completion block to remove the sd_decodingOptions)

**Comment by dreampiggy** [comment]
This custom cache as context option issue should be fixed in [v5.13.5](https://github.com/rs/SDWebImage/releases/tag/5.13.5)
