### ISSUE TITLE
5.13.1版本[SDImageIOAnimatedCoder createFrameAtIndex:source:scale:preserveAspectRatio:thumbnailSize:options:]崩溃

### ISSUE THREAD

**Issue by fangYaLei110** [SDWebImage/SDWebImage#3375]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           ios
 Platform Version        | 15.5
 SDWebImage Version      | 5.13.1 
 Integration Method      | cocoapods
 Xcode Version           | Xcode 13.3
 Repro rate              | all the time (100%)
 Repro with our demo prj | 

### Issue Description and Steps

gif图片持续播放，大约播放到100个就会出现崩溃(https://cdnpw.chinaesport.com/cms/companion/15976543568178637234440461235.gif)这个是我播放的gif地址，使用方法如下：

![image](https://user-images.githubusercontent.com/49603818/179759322-699f411a-150d-444b-a4ee-468ea8b8fdf0.png)
![image](https://user-images.githubusercontent.com/49603818/179759757-70922e2a-bf11-450f-ad86-2581ca0c6ea7.png)
![image](https://user-images.githubusercontent.com/49603818/179759873-26d75f6e-f8e2-482f-b9cb-24bbf3d2ffca.png)
![image](https://user-images.githubusercontent.com/49603818/179759937-ab4633c2-7a85-473a-86d9-9c67f5e33d19.png)

以上方法，间隔0.2s播放一次gif动画，大约2-15分钟之内一定会出现崩溃现象。

bugly崩溃堆栈如下：
![image](https://user-images.githubusercontent.com/49603818/179765209-1b303218-a1e2-47a6-9e60-f9523bf4e423.png)
![image](https://user-images.githubusercontent.com/49603818/179765958-9d3294f2-b055-4c50-a224-da683695dd98.png)

**Comment by fork4jm** [comment]
#3273
