### ISSUE TITLE
iOS SDWebImage Crash on SDGraphicsGetImageFromCurrentImageContext iOS 15

### ISSUE THREAD

**Issue by jigneshD11** [SDWebImage/SDWebImage#3376]
Platform Name           iOS
 Platform Version        iOS 15+
 SDWebImage Version     
 Integration Method   cocoapods
 Xcode Version           13
 Repro rate              25 events

0 libsystem_platform.dylib __platform_memmove
1 CoreFoundation _CFDataGetBytes
2 ImageIO _CGImageGetImageSource
3 UIKitCore -[_UIImageCGImageContent initWithCGImage:scale:]
4 UIKitCore -[UIImage initWithCGImage:scale:orientation:]
5 __hidden
6 __hidden
7 __hidden
8 __hidden
9 Foundation _NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK
10 Foundation -[NSBlockOperation main]
11 Foundation _NSOPERATION_IS_INVOKING_MAIN
12 Foundation -[NSOperation start]
13 Foundation _NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION
14 Foundation ___NSOQSchedule_f
15 libdispatch.dylib __dispatch_block_async_invoke2
16 libdispatch.dylib __dispatch_client_callout
17 libdispatch.dylib __dispatch_continuation_pop
18 libdispatch.dylib __dispatch_async_redirect_invoke
19 libdispatch.dylib __dispatch_root_queue_drain
20 libdispatch.dylib __dispatch_worker_thread2
21 libsystem_pthread.dylib __pthread_wqthread

**Comment by dreampiggy** [comment]
You stacktrace does not match your issue title :(

And I guess, this here shows `CGImageGetImageSource`, maybe this related to issue #3273, please check that instead.
