### ISSUE TITLE
doesn't work if file name contains arabic words or empty spaces

### ISSUE THREAD

**Issue by aparandiy** [SDWebImage/SDWebImage#3394]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS
 Platform Version        | 15.4
 SDWebImage Version      | 5.13.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 13.3.1
 Repro rate              |  all the time (100%) 

### Issue Description and Steps

The library returns an error "Image url is nil" when I am trying to download a valid url string.
Here is my code:

let imgStr = "https://salalem-enterprise.s3-eu-central-1.amazonaws.com/client/سلالم/learning-activities/competition/1635233936352-lg.png"
imgView.sd_setImage(with: URL(string: imgStr)) { image, error, type, url in
       if let error = error {
             print("error - \(error.localizedDescription)") // -> Image url is nil
       }
 }

**Comment by dreampiggy** [comment]
You need URL encode. This is standard way of NSURL processing.
