### ISSUE TITLE
SDWebImage 5.13.2 disk cache larger than expect

### ISSUE THREAD

**Issue by heistings** [SDWebImage/SDWebImage#3395]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 15.2
 SDWebImage Version      | 5.13.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 13.2.1
 Repro rate              | all the time (100%) 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

I just made a very simple demo to called the `-loadImageWithURL:options:progress:completed:` method. If run the project twice, the data size in the completion block will change.

e.g Directly download https://pic.616pic.com/ys_img/00/51/32/sEA4z1yxN3.jpg it is 14KB. But in the disk the file is 34KB. If you check the data size in the completion block, it seems 14KB 1st, and 34KB 2rd.

**Comment by dreampiggy** [comment]
Known issue.

May be fixed later (v5.13.3 has more important crash fix which need to release first)

**Comment by dreampiggy** [comment]
I think this https://github.com/SDWebImage/SDWebImage/pull/3428/files solve your issue.

Read the test case code, I think it explain your demo code

**Comment by dreampiggy** [comment]
> it seems 14KB 1st, and 34KB 2rd.

You seems use the thumbnail or transformer.

The `14KB` is original downloaded data size
The `34KB` is re-encoded data size for your thumbnail

Note in 5.14.0, the data params is nil. Because now we have 2 kind of data (Thumbnail Image's data, and Original Full Size data). To avoid misunderstanding, we just remove it totally.
