### ISSUE TITLE
iOS 16 PDF Decoding Issue

### ISSUE THREAD

**Issue by kemalturk** [SDWebImage/SDWebImage#3396]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |ios|
 Platform Version        |16.0|
 SDWebImage Version     |5.13.2|
 Integration Method      |SPM|
 Xcode Version           |Xcode 14|

### Issue Description and Steps

On the iOS 16 i am getting Downloaded image decode failed with PDF images. 
I have discovered this after iOS 16 upgrade on my phone today.
And i had to change my all pdf images to png on the server.

Error Domain=SDWebImageErrorDomain Code=1001 "Downloaded image decode failed" UserInfo={NSLocalizedDescription=Downloaded image decode failed}

**Comment by pbowden** [comment]
I am encountering the same issue (version 5.13.2 as well).

**Comment by dreampiggy** [comment]
Is there anything behavior changes from Apple ?

The PDF thumbnail is using ImageIO's `CGImageSourceCreateThumbnailAtIndex` to decode.

**Comment by dreampiggy** [comment]
Seems iOS 16, ImageIO can no longer decode PDF. SAD NEWS

![image](https://user-images.githubusercontent.com/6919743/190994487-1da78e2d-57fd-4c19-ae3d-0095da424c02.png)


You can test with simple demo by your hand as well.

Need fire radar to Apple, because their documentation says:

> If the image source is a PDF, this function creates a 72 dpi image of the PDF page specified by the index that you pass. You must, however, pass an options dictionary that contains either the [kCGImageSourceCreateThumbnailFromImageIfAbsent](https://developer.apple.com/documentation/imageio/kcgimagesourcecreatethumbnailfromimageifabsent?language=objc) or [kCGImageSourceCreateThumbnailFromImageAlways](https://developer.apple.com/documentation/imageio/kcgimagesourcecreatethumbnailfromimagealways?language=objc) keys, with the value of the key set to true.

https://developer.apple.com/documentation/imageio/1465099-cgimagesourcecreatethumbnailatin?language=objc#

**Comment by dreampiggy** [comment]
Demo is here: 
[ImageIODecodePDFIssue.zip](https://github.com/SDWebImage/SDWebImage/files/9597963/ImageIODecodePDFIssue.zip)


A quick workaround, you can use that [SDWebImagePDFCoder](https://github.com/SDWebImage/SDWebImagePDFCoder), which use PDFKit instead of ImageIO to decode.

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/190995777-31252c06-9917-4ab7-b508-241e5a102ee2.png)

FB11543333

**Comment by kemalturk** [comment]
@dreampiggy Thanks for the informations. That's enough for me. Im closing the issue. But we need to update the Readme.

**Comment by dreampiggy** [comment]
I'll pin this issue and see whether Apple solve this in iOS 16.1 beta

**Comment by dreampiggy** [comment]
If this still need workaround, I can provide a fallback on SDImageCoder to use PDFKit to draw PDF, copy the code from [SDWebImagePDFCoder](https://github.com/SDWebImage/SDWebImagePDFCoder)

Ugly, but, still a workaround :(

**Comment by dreampiggy** [comment]
Oh, I think that the #3370 already fix this issue by providing more context to ImageIO
