### ISSUE TITLE
SDAnimatedImageView can't load normal photo

### ISSUE THREAD

**Issue by ice0github** [SDWebImage/SDWebImage#3397]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | macOS
 Platform Version        | 12.5
 SDWebImage Version      | 5.13.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 14
 Repro rate              | all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Here is 2 photo: 
gif1.gif /  jpg2.jpg

Step1. set "gif1.gif" to SDAnimatedImageView (via sd_setImageWithURL:)
Step2. set "jpg2.jpg" to SDAnimatedImageView  (via sd_setImageWithURL:)
Step3. the "jpg2.jpg"  doesn't display at image view

------------
I try remove this code in [SDAnimatedImagePlayer initWithProvider:]
`
if (animatedImageFrameCount <= 1) {
            return nil;
}
`
It work...

**Comment by dreampiggy** [comment]
The second set should be a UIImage, which just call super setImage. So it should render as static image. 

Need to check again, can this be reproducable in macOS demo ?

**Comment by ice0github** [comment]
@dreampiggy 
demo and video here:
https://github.com/ice0github/GIFBugDemo.git

**Comment by dreampiggy** [comment]
Sounds like this is macOS/AppKit related bug ? Does not applied to iOS/UIKit ?

**Comment by dreampiggy** [comment]
Any better solution ?

Currently our subclass SDAnimatedImageView can only show normal image logic, but not the `NSBitmapImageView` which can be animated GIF , does not match super behavior actually 😂

Because we handle CALayer by ourselves. I want to find out the public API to call to fallback NSImageView's default behavior, but didn't find one.
