### ISSUE TITLE
302 Redirect not working with

### ISSUE THREAD

**Issue by shatodj** [SDWebImage/SDWebImage#3398]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 15, 16
 SDWebImage Version      | e.g. 5.12.5
 Integration Method      | e.g. SPM
 Xcode Version           | e.g. Xcode 13, 14
 Repro rate              | e.g. all the time (100%) 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

It looks like SDWebInage is not able to handle 302 redirect image links. Example image:
https://media-we-cdn.oriflame.com/-/media/WE/Promotions/09/02/10/16764606_2.ashx?u=0101010000&imageFormat=JPEG&ib=%23ffffff&q=33&w=1200

Request Response:
```http
HTTP/1.1 302 Found
Cache-Control: private
Content-Type: text/html; charset=utf-8
Date: Fri, 16 Sep 2022 07:36:35 GMT
Location: https://media-we-cdn.oriflame.com/contentImage?externalMediaId=e1642b8f-ce3b-4ab0-9adf-a269d1ee0703&u=0101010000&imageFormat=JPEG&ib=%23ffffff&q=33&w=1200
Server: Microsoft-IIS/10.0
Set-Cookie: f5avraaaaaaaaaaaaaaaa_session_=GAHDLNEABJIMJBEEGIGFHBKJNGGDBAAGAOHKHNAHFKNOMHPHMHAKIOEIJLMMPCGJLNODNFMNJHKJKHMCGCMALNGDDCBIFNEJJPOKHDEECAMBILCDKONOHHKEEKGLDMGE; HttpOnly; secure;
Set-Cookie: TSb51d2775027=08afc1cc77ab2000380834e3663130b0c3a26e3b3a5c9a709a04945850bb319aa1a1f21032e400f808a24de643113000b409a3f2404aac48a9a1177b9f620c242ed4c5a5f547473fd90ab241964d208d2a3856e30a0f8725f42ae0945c8ae33b; Path=/; Secure
Strict-Transport-Security: max-age=16070400; includeSubDomains
Vary: Accept-Encoding
Content-Length: 291

<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://media-we-cdn.oriflame.com/contentImage?externalMediaId=e1642b8f-ce3b-4ab0-9adf-a269d1ee0703&amp;u=0101010000&amp;imageFormat=JPEG&amp;ib=%23ffffff&amp;q=33&amp;w=1200">here</a>.</h2>
</body></html>
```

Swift code inside UIImageView extension:
```swift
sd_setImage(with: url) { image, error, _, _ in
            guard let image = image else {
                os_log_app("Image loading error '\(url)' ending with error: \(String(describing: error)). Using fallback image.", type: .error)
                errorCallback?()
                return
            }
            self.image = image
        }
```

SDWebImnage Error Description:
```
Error Domain=SDWebImageErrorDomain Code=2002 "Operation cancelled by user during querying the cache" UserInfo={NSLocalizedDescription=Operation cancelled by user during querying the cache}
```

Similar issues of this problem describe situations that should be already fixed.

**Comment by dreampiggy** [comment]
Is this becaues of the URLSession delegate method https://developer.apple.com/documentation/foundation/nsurldownloaddelegate/1412181-download

You can try using the demo and update the code in `SDWebImageDownloader` to see whether this is triggered.

**Comment by dreampiggy** [comment]
Tested worked in unit test. Close

**Comment by HappyIosDeveloper** [comment]
I have this problem with SVG urls & SDImageSVGNativeCoder.

**Comment by dreampiggy** [comment]
> I have this problem with SVG urls & SDImageSVGNativeCoder.

Provide the demo ?

And, use any other User-Agent (not Chrome) to test, whether the server side HTTP redirect based on User-Agent.

SDWebImage use a fake User-Agent, maybe related to this
