### ISSUE TITLE
EXC_BAD_INSTRUCTION - APP crashes while images loading

### ISSUE THREAD

**Issue by hell77** [SDWebImage/SDWebImage#3400]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 16
 SDWebImage Version      | 5.13.2 (master)
 Integration Method      | PM
 Xcode Version           | e.g. Xcode 14
 Repro rate              | all the time (100%) 
 Repro with our demo prj |
 Demo project link       | 

### Issue Description and Steps

RunTime Error  in file _SDWebImageManager_:  **Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)**

Implementation code:
```swift
List(0..<30)
{
    WebImage(url: URL(string: imageUrl), options: [.progressiveLoad, .delayPlaceholder], isAnimating: .constant(true))
        .retryOnAppear(true)
        .resizable()
        .placeholder(Image(systemName: "wifi.exclamationmark")
            .resizable())
        .indicator(.progress)
        .transition(.flipFromLeft)
        .scaledToFit()
        .onTapGesture
    {
        self.currentImage = "http://wiu.ks-api.com/Content/\(item.body!)"
        withAnimation
        {
            isFullScreenMode.toggle()
        }
    }
        .zIndex(1)
        .padding(.horizontal, -20)
}
```

Code where an error occurred:

```swift
- (BOOL)isCancelled {
    BOOL isCancelled = NO;
    SD_LOCK(_cancelledLock);
    isCancelled = _cancelled;
    SD_UNLOCK(_cancelledLock);
    return isCancelled;
}
```

**Comment by dreampiggy** [comment]
Seems bug intoduced from #3393

Hi. [Alex](https://github.com/SDWebImage/SDWebImage/pull/3393), seems the basic block `return` does not release the lock and cause crash.

![image](https://user-images.githubusercontent.com/6919743/190947799-363b204f-715f-4a5e-922d-bca4320b94a8.png)

I'll provide a quick fix in v5.13.3

**Comment by hell77** [comment]
Hi, 
perhaps it will be more informative and useful

<img width="1440" alt="Screenshot 2022-09-19 в 10 52 50" src="https://user-images.githubusercontent.com/7412110/190982624-c4bc03ca-0c88-4dcd-9e94-f1781e3628c3.png">

**Comment by dreampiggy** [comment]
@hell77 Your screenshot seems that `_cancelledLock` does not get correct init using `os_unfair_lock_init` and seems to be a null pointer.

What's the call stack trace of this ? Or can any demo reproduce the crash.

**Comment by dreampiggy** [comment]
To solve this issue quickly, I deceide to rollback the https://github.com/SDWebImage/SDWebImage/pull/3393

**Comment by hell77** [comment]
Recorded video from the screen.

Nesting: NavigationView -> ScrollReader -> List -> WebImage

The error occurs when scrolling through the list.
If you do not scroll the list immediately, but wait, then everything is OK

https://user-images.githubusercontent.com/7412110/190994104-0512565c-7c0e-4aac-acc6-97659caafacc.mp4
