### ISSUE TITLE
SDWebImage causing crash in iOS 16.

### ISSUE THREAD

**Issue by AmanShekhar14** [SDWebImage/SDWebImage#3406]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          | iOS (iPhone 12 Device)
 Platform Version        | 16.0
 SDWebImage Version      | 5.13.3
 Integration Method      | cocoapods
 Xcode Version           | xCode 14
 Repro rate              | 100%

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

stack trace is coming empty. However, we are putting the screenshots, it will be easier to see the hierarchy. 
<img width="1726" alt="Screenshot 2022-09-21 at 13 29 55" src="https://user-images.githubusercontent.com/102651387/191448853-47e18063-0f00-492f-9250-dcc24b6297cd.png">
<img width="692" alt="Screenshot 2022-09-21 at 13 24 23" src="https://user-images.githubusercontent.com/102651387/191449015-cac24abf-ac9c-44cb-ab8b-4f80f1ace177.png">
<img width="1490" alt="Screenshot 2022-09-21 at 13 25 21" src="https://user-images.githubusercontent.com/102651387/191449022-7d55b618-885e-448f-87d7-b21b38f8fbb3.png">
<img width="1484" alt="Screenshot 2022-09-21 at 13 25 57" src="https://user-images.githubusercontent.com/102651387/191449030-503f25c1-d32f-4489-827e-6af870ad3cdd.png">

Steps: 
Going to the view which have integrated SDWebImage, and going back and forth on the two view. It causes crash, after 1-2 screen transition.

**Comment by dreampiggy** [comment]
This is [SDWebImageSwiftUI](https://github.com/SDWebImage/SDWebImageSwiftUI/issues), should be fixed in v2.1.1
