### ISSUE TITLE
加载图频内存泄漏暴涨

### ISSUE THREAD

**Issue by CCSH** [SDWebImage/SDWebImage#3413]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 16.0
 SDWebImage Version      | e.g. 5.13.4
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 14 
 Repro rate              | e.g. all the time (100%) 
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps
Memory surge

- (void)storeImage:(nullable UIImage *)image
         imageData:(nullable NSData *)imageData
            forKey:(nullable NSString *)key
          toMemory:(BOOL)toMemory
            toDisk:(BOOL)toDisk
        completion:(nullable SDWebImageNoParamsBlock)completionBlock

<img width="910" alt="image" src="https://user-images.githubusercontent.com/16768967/195020031-b8157e37-fb39-4de8-a641-0903fe8a5fb1.png">

**Comment by nevsee** [comment]
@dreampiggy 能否可以提供一个设置缩略图百分比的option，我想在不知道图片尺寸的情况下始终使用 CGImageSourceCreateThumbnailAtIndex 创建图片，这样可以有效缓解内存开销

![企业微信截图_9bb28677-a42c-485d-9b93-0533573770be](https://user-images.githubusercontent.com/42122949/195283091-c7b3cd17-6d54-41a0-a1e9-e2a40ec7ff6b.png)

![企业微信截图_64a6835f-3f1f-42ce-97ba-71d7295a373f](https://user-images.githubusercontent.com/42122949/195283126-c7b5436d-78b1-4e74-9097-fefc11054c05.png)

**Comment by nevsee** [comment]
@dreampiggy 一个500KB gif图片内存对比

使用CGImageSourceCreateThumbnailAtIndex
![企业微信截图_f3d0a8e4-134f-4844-9b65-28de7532f48c](https://user-images.githubusercontent.com/42122949/195284265-6feb93b8-7d09-4616-9030-cf0eac48924e.png)

使用CGImageSourceCreateImageAtIndex
![企业微信截图_d23a667e-622d-44c1-8026-f7e51d5f208d](https://user-images.githubusercontent.com/42122949/195284439-4cf4bc98-bb7d-4730-9f25-000440ff2e49.png)

**Comment by dreampiggy** [comment]
This RAM usage in your call trace, is `Image Encoding`, but not just `Image Decoding`

**Comment by dreampiggy** [comment]
For your feature request.

The current `thumbnailPixelSize`, why I name it `Pixel`, because this options can be used for two cases:

1. Bitmap Image (GIF/JPEG), create a smaller thumbnail image instead
2. Vector Image (SVG/PDF), create the fixed size provided by you, which does not has such as `intrinsic size`

If we introduce the `thumbnailRatio`, which should only applies to the Bitmap Image, but not vector, because it actually has no **origin size** at all.

**Comment by nevsee** [comment]
@dreampiggy - -，其实我已经设置了thumbnailPixelSize = 3072，但是绝大多数图片（gif/jpeg）尺寸是不大于`thumbnailPixelSize`，我这边gif图片比较多导致内存高，如果设置`thumbnailPixelSize `比较小又导致图片模糊，至于vector图片，实属罕见。

**Comment by nevsee** [comment]
I try

**Comment by dreampiggy** [comment]
Should be solved in 5.14.0.

If you want force-decode, Pass `.decodeUseLazyDecoding = NO` to context option `.imageDecodeOptions`
if you don't, and prefer lazy-decode, Pass `.decodeUseLazyDecoding = YES` to context option `.imageDecodeOptions`
