### ISSUE TITLE
设置GIF动画循环次数无效呢，这个应该怎么设置呢

### ISSUE THREAD

**Issue by Marcello168** [SDWebImage/SDWebImage#3414]
[cell.imageView sd_setImageWithURL:LYUrl(image) completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
                [image setSd_imageLoopCount:1];

            }];

            cell.imageView.image.sd_imageLoopCount = 1;

**Comment by dreampiggy** [comment]
When using UIImageView for animation, you should update `sd_imageLoopCount` before it set to `UIImageView`.

Or you just do something by your own hand using https://developer.apple.com/documentation/uikit/uiimageview/1621070-animationrepeatcount, like

```swift
completionBlock { _, _, _, in
    cell.imageView.animationRepeatCount = 100
}
```

When using `SDAnimatedImageView` (recommend), you can just use the property `customLoopCount`

```
let imageView = SDAnimatedImageView()
imageView.customLoopCount = 100
```

**Comment by dreampiggy** [comment]
Or you can directlly call `sd_internalSetImage()`, by providing the custom `setImageBlock`, update the logic for you like:

```
setImageBlock { image in
    if image.count > 0 {
        imageView.image = nil
        imageView.animationImages = image.images
        imageView.animationRepeatCount = 100
    } else {
        imageView.image = image
        imageView.animationImages = nil
        imageView.animationRepeatCount = 0
    }
}
```
