### ISSUE TITLE
Github slack integration

### ISSUE THREAD

**Issue by alrocha** [SDWebImage/SDWebImage#3435]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

Trying to get notified for new releases automatically.

### Issue Description and Steps

Hi folks!

I am trying to subscribe to releases within Slack / Github app bot but looks like is not installed, when I run the subscribe command in Slack I get:
![image](https://user-images.githubusercontent.com/8307263/201102281-2ab89cfc-df8c-44ea-917f-93bd5baa5898.png)

The same would apply for the SwiftUI repo https://github.com/SDWebImage/SDWebImageSwiftUI

Could you please install it in the repo? you just need to run it from the following link:  https://github.com/apps/slack/installations/new

Thanks a lot in advance!

**Comment by dreampiggy** [comment]
It's OK. We used to use slack for internal communication of maintainers. But it's no longer maintained.

Is this Slack for GitHub requires additional information of SDWebImage's maintainer or some other information ?

**Comment by dreampiggy** [comment]
I think it's linked ?

![image](https://user-images.githubusercontent.com/6919743/204727713-ff24d8c3-9b5b-424f-8a79-0195b0b2c4f4.png)

**Comment by alrocha** [comment]
Amazing it works! thanks for the support!
