### ISSUE TITLE
最新版SDK5.14.0报错[SDWebImageDownloaderOperation start]

### ISSUE THREAD

**Issue by xiaowangqinghui** [SDWebImage/SDWebImage#3438]
-[NSArray initWithArray:range:copyItems:]: range {0, 1} extends beyond bounds for empty array

CoreFoundation
___exceptionPreprocess + 220

3
CoreFoundation
-[NSArray initWithArray:range:copyItems:] + 680
4
SDWebImage
-[SDWebImageDownloaderOperation start] + 1648
5
Foundation
___NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24

14
libsystem_pthread.dylib
_start_wqthread + 8
<img width="785" alt="image" src="https://user-images.githubusercontent.com/15713276/201248650-80c06775-6989-4a06-b933-7e7ad5d9bf08.png">

**Comment by xiaowangqinghui** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/15713276/201249233-b6839f7f-cb17-4a79-b091-8eb3cfe2c5c2.png">

**Comment by dreampiggy** [comment]
Should be fixed in [5.14.1](https://github.com/SDWebImage/SDWebImage/releases/tag/5.14.1)
