### ISSUE TITLE
iOS 14 runtime crash: dyld: Symbol not found: _CGImageGetImageSource

### ISSUE THREAD

**Issue by chwo** [SDWebImage/SDWebImage#3441]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.8.1
 SDWebImage Version      | **5.14 and 5.14.1**
 Integration Method      | SPM
 Xcode Version           | Xcode 14.1 (14B47b)
 Repro rate              | all the time (100%)
 Repro with our demo prj | ?
 Demo project link       | -

### Issue Description and Steps

After updating the SDWebImage package from version `5.13.5` to version `5.14.1` the app crashes on startup when running on a iOS 14 (14.8.1) device. On iOS 15 and iOS 16 it still runs fine. This crash occurs only since version `5.14.x`.

```
dyld: Symbol not found: _CGImageGetImageSource
  Referenced from: /private/var/containers/Bundle/Application/F9F33737-E56A-4998-BBB8-394D0DB8B071/AppName.app/AppName
  Expected in: /System/Library/Frameworks/ImageIO.framework/ImageIO

dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

**Comment by dreampiggy** [comment]
This call has `if (@available(iOS 15, tvOS 15, *))` check. Are you sure it's used ?

And I think this check exists only in Debug mode, not Relase mdoe.

**Comment by dreampiggy** [comment]
> This call has `if (@available(iOS 15, tvOS 15, *))` check. Are you sure it's used ?
> 
> And I think this check exists only in Debug mode, not Release mdoe.

I can have a check at the Debug build binary. To see whether this symbol references is strong. If is, I can change it into calling `dlsym` instead

**Comment by ilya-free** [comment]
I have got the similar problem. When i had sended my release build to the appstoreconnect i received this issue from apple:

> **ITMS-90338: Non-public API usage** - The app references non-public symbols in Frameworks/SDWebImage.framework/SDWebImage: _CGImageGetImageSource. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

how fix it i dont know now

**Comment by ilya-free** [comment]
i decrease version number to 5.13.4 and appstoreconnect have passed my build
i hope it will be useful for somebody

**Comment by luinily** [comment]
It seems you're already on it (thanks!) but just in case, I have the same problem with my project (I'm using SDWebImageSwiftUI, and when SDWebImage it uses went from 5.13.5 to 5.14.1 my app started crashing on iOS 14 in the enterprise build I use for internal testing (it would work fine on 14 in debug mode from Xcode).

The error from the crash log is:
```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, symbol '_CGImageGetImageSource' not found, expected in '/System/Library/Frameworks/ImageIO.framework/ImageIO', needed by '/private/var/containers/Bundle/Application/[...]'
```

**Comment by dreampiggy** [comment]
Please use [5.14.2](https://github.com/SDWebImage/SDWebImage/releases/tag/5.14.2)

**Comment by chwo** [comment]
@dreampiggy I can conform that it works again on iOS 14 devices with version `5.14.2`. Thank you for providing a fix this fast 👍
