### ISSUE TITLE
5.14.0 ITMS-90338: Non-public API usage - _CGImageGetImageSource

### ISSUE THREAD

**Issue by shimastripe** [SDWebImage/SDWebImage#3442]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 14.0-16.x
 SDWebImage Version      | e.g. 5.14.0 / 5.14.1
 Integration Method      | e.g. SwiftPM
 Xcode Version           | e.g. Xcode 14.1 (14B47b)
 Repro rate              | e.g. all the time (100%)
 Repro with our demo prj | Uploading to AppStoreConnect is always failed.
 Demo project link       | nothing

### Issue Description and Steps

My app is updated SDWebImage. Then appstoreconnect rejected the new binary. Because this binary uses private api.

> ITMS-90338: Non-public API usage - The app references non-public symbols in MYAPP: _CGImageGetImageSource. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by dreampiggy** [comment]
This SPI is only used in DEBUG mode for assertion. Check your build log and settings

**Comment by shimastripe** [comment]
Thank you for your quick reply! Yes, I use DEBUG build binary for Testflight. However I don't think SwiftPM can make Release Configuration only for specific packages... Could I use any workaround?

**Comment by dreampiggy** [comment]
This assertion is used for SDWebImage maintainer (me...) to know whether Apple change their ImageIO/CoreGraphics assumation.

Actually you can remove that assertion, but this may cause, for example, once iOS 17 Apple change their ImageIO implementation again which effects SDWebImage, I have no way to find it out, unless some user fire new GitHub issues about the thread safe crash. :(

Or, I can change that macro and assertion only avaiable when using in SDWebImage's demo or test project, like 

```
// in SDWebImageDemo.ViewController.m
#define SD_CHECK_CGIMAGE_RETAIN_SOURCE 1
#include <SDWebImage/SDWebImage.h>
```

**Comment by dreampiggy** [comment]
Please use [5.14.2](https://github.com/SDWebImage/SDWebImage/releases/tag/5.14.2)

**Comment by shimastripe** [comment]
@dreampiggy I'll check it! Thank you.

**Comment by ravkooashishraval** [comment]
Rejected the new binary. Because this binary uses private api.

ITMS-90338: Non-public API usage - The app references non-public symbols in _CGImageGetImageSource. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by AraceliPM** [comment]
Hi!! @dreampiggy Can you pease help me to update SDWebImage -> 5.14.2 over SDWebImageWebPCode? I have the same issue sinse on SDWebImageWebPCode uses actually SDWebImage (5.13.5)

**Comment by ravkooashishraval** [comment]
Issue was resolve...after creating static framework....and added in app folder...
