### ISSUE TITLE
SDWebImageDownloaderOperation存在大量崩溃问题（5.13.3）

### ISSUE THREAD

**Issue by xiaowangqinghui** [SDWebImage/SDWebImage#3446]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/15713276/202943916-3721b8ca-76dd-494f-82d9-0a89c1ed6167.png">

版本是5.13.3  之前更新到最新版本又出现别的崩溃问题 就回退到了5.13.3，然后又出现这个崩溃

**Comment by dreampiggy** [comment]
This stack trace does not show the line count. Update your dSYM to re-symbolicate.

**Comment by xiaowangqinghui** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/15713276/203236432-c0a3f9ac-6f43-4e4c-b789-b247b09d550a.png">今天又看到另一个错误

**Comment by dreampiggy** [comment]
> <img alt="image" width="895" src="https://user-images.githubusercontent.com/15713276/203236432-c0a3f9ac-6f43-4e4c-b789-b247b09d550a.png">今天又看到另一个错误

OOM issue. Because of `memmove`

**Comment by dreampiggy** [comment]
> <img alt="image" width="846" src="https://user-images.githubusercontent.com/15713276/202943916-3721b8ca-76dd-494f-82d9-0a89c1ed6167.png">
> 
> 版本是5.13.3 之前更新到最新版本又出现别的崩溃问题 就回退到了5.13.3，然后又出现这个崩溃

Provide this stack trace's line number ? Seems you can update dSYM to re-symbolicate (Your 2nd screenshot shows the actual line number, but the 1st one does not)

**Comment by xiaowangqinghui** [comment]
> > <img alt="image" width="895" src="https://user-images.githubusercontent.com/15713276/203236432-c0a3f9ac-6f43-4e4c-b789-b247b09d550a.png">今天又看到另一个错误
> 
> OOM issue. Because of `memmove`

What？什么意思，因为你移除了？

**Comment by dreampiggy** [comment]
> > > <img alt="image" width="895" src="https://user-images.githubusercontent.com/15713276/203236432-c0a3f9ac-6f43-4e4c-b789-b247b09d550a.png">今天又看到另一个错误
> > 
> > 
> > OOM issue. Because of `memmove`
> 
> What？什么意思，因为你移除了？

I means:

1. Provide your first crash report's `Line Number`. That `+74` is not line number. It's address offset because you don't symbolicate correctly.
2. The second crash report is becaseu of `OOM` (out of memory), which may related to your App's issue, not always the SDK side. There are some tips to lower the RAM usage, check: https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#optimization-for-large-images
