### ISSUE TITLE
Should the second parameter of the `CGImageSourceCreateWithData` method be `NULL` in line 404?

### ISSUE THREAD

**Issue by JustLoveBen** [SDWebImage/SDWebImage#3453]
### New Issue Checklist
 I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
 I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
 I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Description
https://github.com/SDWebImage/SDWebImage/blob/430ef4d73ca268d8efcefad08d3ac020af91c750/SDWebImage/Core/SDImageIOAnimatedCoder.m#L404

should the second parameter of the `CGImageSourceCreateWithData` method be `NULL` in line 404?

**Comment by dreampiggy** [comment]
Any issue ? This is documented API, see its description: https://developer.apple.com/documentation/imageio/1465073-cgimagesourcecreatewithdata

**Comment by JustLoveBen** [comment]
Sorry, I probably didn't express clearly.

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/18016109/205823303-d120dcbf-13c6-47b7-9a15-ccfa9c6df4e3.png">
The comments in line 403, reads `Try again without UTType hint, the call site from user may provide the wrong UTType`.  
So, the kCGImageSourceTypeIdentifierHint key should not be contained in `CGImageSourceCreateWithData `'s `options` param. 
Is that so?

**Comment by dreampiggy** [comment]
@JustLoveBen   Oh, this is a bug. The creatingOptions here in this line should be NULL.

PR is welcomed ! (For you)

**Comment by dreampiggy** [comment]
Seems this bug did not get into merged in 5.15.0. I'll create one :)

**Comment by dreampiggy** [comment]
Fixed in [5.15.1](https://github.com/SDWebImage/SDWebImage/releases/tag/5.15.1)
