### ISSUE TITLE
+[SDImageIOAnimatedCoder createFrameAtIndex:source:scale:preserveAspectRatio:thumbnailSize:lazyDecode:options:] crash 

### ISSUE THREAD

**Issue by SYLuffy** [SDWebImage/SDWebImage#3458]
### New Issue Checklist
 
+[SDImageIOAnimatedCoder createFrameAtIndex:source:scale:preserveAspectRatio:thumbnailSize:lazyDecode:options:] crash 

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        | 12.0 ～ 16.2
 SDWebImage Version      | 5.14.1
 Integration Method      |  cocoapods 
 Xcode Version           |  Xcode 14.2
 
### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

![image](https://user-images.githubusercontent.com/11451051/208838502-3b91244d-1455-4202-b10e-64fa683afa84.png)

**Comment by dreampiggy** [comment]
Need more information.

Does this related to 5.14's changes for that #3425 ?

**Comment by dreampiggy** [comment]
Please re-check with the latest v5.14.3 version. Which may reduce the JPEG/HEIF RAM usage by using Apple's YUV420 optimization
