### ISSUE TITLE
5.14.3 not found in CocoaPods

### ISSUE THREAD

**Issue by iamDiNGo** [SDWebImage/SDWebImage#3463]
Hello. Not found [5.14.3] in CocoaPods.

**Comment by dreampiggy** [comment]
> ➜  sdwebImage git:(master) pod trunk info SDWebImage
SDWebImage
    - Versions:
      - 2.4 (2014-05-19 21:38:21 UTC)
      - 2.5 (2014-05-19 21:39:04 UTC)
      - 2.6 (2014-05-19 21:41:09 UTC)
      - 2.7 (2014-05-19 21:44:13 UTC)
      - 2.7.4 (2014-05-19 21:48:44 UTC)
      - 3.0 (2014-05-19 21:45:15 UTC)
      - 3.1 (2014-05-19 21:46:01 UTC)
      - 3.2 (2014-05-19 21:48:48 UTC)
      - 3.3 (2014-05-19 21:52:34 UTC)
      - 3.4 (2014-05-19 21:54:25 UTC)
      - 3.5 (2014-05-19 21:56:42 UTC)
      - 3.5.1 (2014-05-19 21:59:21 UTC)
      - 3.5.2 (2014-05-19 22:00:46 UTC)
      - 3.5.3 (2014-05-19 22:04:17 UTC)
      - 3.5.4 (2014-05-19 22:04:17 UTC)
      - 3.6 (2014-05-19 22:05:17 UTC)
      - 3.7.0 (2014-07-15 06:56:43 UTC)
      - 3.7.1 (2014-07-23 05:22:28 UTC)
      - 3.7.2 (2015-03-17 15:52:03 UTC)
      - 3.7.3 (2015-07-13 20:19:49 UTC)
      - 3.7.4 (2016-01-08 15:46:45 UTC)
      - 3.7.5 (2016-01-21 14:50:01 UTC)
      - 3.7.6 (2016-05-08 17:45:31 UTC)
      - 3.8.0 (2016-06-06 18:28:30 UTC)
      - 3.8.1 (2016-06-07 09:11:28 UTC)
      - 3.8.2 (2016-09-05 17:20:38 UTC)
      - 3.8.3 (2019-06-05 05:23:55 UTC)
      - 4.0.0 (2017-01-28 18:24:23 UTC)
      - 4.0.0-beta (2016-10-05 09:31:19 UTC)
      - 4.0.0-beta2 (2016-10-06 14:28:34 UTC)
      - 4.1.0 (2017-07-31 13:53:37 UTC)
      - 4.1.1 (2017-10-06 19:05:48 UTC)
      - 4.1.2 (2017-10-09 06:46:48 UTC)
      - 4.2.0 (2017-10-30 16:31:43 UTC)
      - 4.2.1 (2017-10-31 20:01:06 UTC)
      - 4.2.2 (2017-11-07 07:28:03 UTC)
      - 4.2.3 (2018-01-03 03:24:04 UTC)
      - 4.3.0 (2018-02-01 03:39:21 UTC)
      - 4.3.1 (2018-02-25 15:06:25 UTC)
      - 4.3.2 (2018-02-28 04:13:20 UTC)
      - 4.3.3 (2018-03-12 15:17:42 UTC)
      - 4.4.0 (2018-05-31 10:01:51 UTC)
      - 4.4.1 (2018-06-07 15:24:26 UTC)
      - 4.4.2 (2018-07-18 16:04:16 UTC)
      - 4.4.3 (2018-12-05 10:43:31 UTC)
      - 4.4.4 (2019-01-26 08:47:36 UTC)
      - 4.4.5 (2019-01-31 10:42:21 UTC)
      - 4.4.6 (2019-02-26 10:42:58 UTC)
      - 4.4.7 (2019-06-05 12:48:21 UTC)
      - 4.4.8 (2019-12-27 06:47:58 UTC)
      - 5.0.0 (2019-04-02 14:06:31 UTC)
      - 5.0.0-beta (2018-07-17 08:21:01 UTC)
      - 5.0.0-beta2 (2018-07-31 15:13:54 UTC)
      - 5.0.0-beta3 (2018-08-30 10:38:23 UTC)
      - 5.0.0-beta4 (2019-01-26 10:35:20 UTC)
      - 5.0.0-beta5 (2019-01-31 11:14:44 UTC)
      - 5.0.0-beta6 (2019-03-15 07:52:07 UTC)
      - 5.0.1 (2019-04-11 14:08:08 UTC)
      - 5.0.2 (2019-04-25 14:19:19 UTC)
      - 5.0.3 (2019-05-16 11:39:56 UTC)
      - 5.0.4 (2019-05-29 12:33:06 UTC)
      - 5.0.5 (2019-06-03 12:47:16 UTC)
      - 5.0.6 (2019-06-05 13:01:45 UTC)
      - 5.1.0 (2019-08-03 11:07:24 UTC)
      - 5.10.0 (2020-11-22 10:32:18 UTC)
      - 5.10.1 (2020-12-25 08:49:28 UTC)
      - 5.10.2 (2020-12-29 03:46:11 UTC)
      - 5.10.3 (2021-01-24 10:35:37 UTC)
      - 5.10.4 (2021-02-02 10:01:05 UTC)
      - 5.1.1 (2019-09-04 16:08:23 UTC)
      - 5.11.0 (2021-04-01 13:21:58 UTC)
      - 5.11.1 (2021-04-23 12:46:41 UTC)
      - 5.12.0 (2021-09-30 09:52:26 UTC)
      - 5.12.1 (2021-10-15 11:05:52 UTC)
      - 5.12.2 (2021-12-31 09:26:23 UTC)
      - 5.12.3 (2022-01-27 13:54:18 UTC)
      - 5.12.4 (2022-03-08 07:34:04 UTC)
      - 5.12.5 (2022-03-16 08:08:56 UTC)
      - 5.12.6 (2022-06-12 10:43:56 UTC)
      - 5.13.0 (2022-06-26 18:56:59 UTC)
      - 5.13.1 (2022-07-16 11:59:37 UTC)
      - 5.13.2 (2022-07-23 15:11:00 UTC)
      - 5.13.3 (2022-09-19 10:42:11 UTC)
      - 5.13.4 (2022-09-26 12:59:32 UTC)
      - 5.13.5 (2022-10-29 12:36:23 UTC)
      - 5.14.0 (2022-11-08 14:55:21 UTC)
      - 5.14.1 (2022-11-11 07:37:43 UTC)
      - 5.14.2 (2022-11-14 10:52:10 UTC)
      - 5.14.3 (2022-12-27 12:04:42 UTC)

**Comment by iamDiNGo** [comment]
<img width="565" alt="Снимок экрана 2022-12-29 в 17 23 08" src="https://user-images.githubusercontent.com/4320750/209917594-4115c67c-ec77-428c-9a1e-a3e8c868a183.png">

**Comment by dreampiggy** [comment]
did you `pod update` ? or `pod repo update` ?

It's shown on the trunk

**Comment by dreampiggy** [comment]
https://github.com/CocoaPods/Specs/blob/master/Specs/1/1/7/SDWebImage/5.14.3/SDWebImage.podspec.json

It's here. If you can not use the CDN version of CocoaPods trunk, use the git source. If you don't understand what's this means, see: https://blog.cocoapods.org/CocoaPods-1.8.0-beta/

**Comment by iamDiNGo** [comment]
pod repo update helped. Thanks
