### ISSUE TITLE
sd_setImage doesn't call completed callback

### ISSUE THREAD

**Issue by gngrwzrd** [SDWebImage/SDWebImage#3464]
### New Issue Checklist

* [ x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 16.0
 SDWebImage Version      | 5.14.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 14
 Repro rate              |all the time
 Repro with our demo prj | haven' t tried
 Demo project link       | haven't tried

### Issue Description and Steps

I just upgraded from an old version (3.something) to 5.14.3 and noticed this issue. 

From swift calling sd_setImage with only a URL and completedBlock doesn't call the completed callback.

````
sd_setImage(with: url) { image, error, cacheType, imageURL in
    //not called
}
````

BUT, calling the method with more parameters will call completion block. 

````
sd_setImage(with: url, placeholderImage: nil) { image, error, cacheType, imageURL in
    //called
}
````

**Comment by gngrwzrd** [comment]
Nevermind!

**Comment by dreampiggy** [comment]
Is this reproduable ?
I think the first API is actually calling the second API with placeholerImage = nil, isn't it ?
