### ISSUE TITLE
在5.14.0开始出现两个imageView加载同一个url，可能导致第二个ImageView没有展示图片

### ISSUE THREAD

**Issue by fangandyuan** [SDWebImage/SDWebImage#3475]
测试代码

```
import UIKit
import SDWebImage
class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let image = UIImage(named: "test111")
        
        saveImage(currentImage: image!, persent: 1.0, imageName: "test111")
    }
    
    private func saveImage(currentImage: UIImage, persent: CGFloat, imageName: String){
        if let imageData = currentImage.jpegData(compressionQuality: persent) as NSData? {
                let fullPath = NSHomeDirectory().appending("/Documents/").appending(imageName)
                imageData.write(toFile: fullPath, atomically: true)
                print("fullPath=\(fullPath)")
                addImageViews(fullPath:fullPath)
            }
        }
    
    func newImageView() -> UIImageView {
        let imageView = SDAnimatedImageView()
        imageView.contentMode = .scaleAspectFit
        imageView.backgroundColor = .yellow
        imageView.translatesAutoresizingMaskIntoConstraints = false
        imageView.isUserInteractionEnabled = true
        imageView.sd_imageIndicator = SDWebImageActivityIndicator.gray
        imageView.sd_imageIndicator?.startAnimatingIndicator()
        return imageView
    }

    var i = 1
    var j = 1
    func addImageViews(fullPath: String) {
        DispatchQueue.main.async {
            let imageView = self.newImageView()
            self.view.addSubview(imageView)
            imageView.frame = CGRect(x: 50 + self.j * 22, y: 60 + 22 * self.i, width: 20, height: 20)
            let url = URL(fileURLWithPath: fullPath)
            imageView.sd_setImage(with: url) {image, error, cacheType, url in
                print("+++++++++++\(String(describing: image))")
                imageView.image = image
            }
            self.i += 1
            if self.i < 30 {
                self.addImageViews(fullPath:fullPath)
            } else if self.j < 4 {
                self.i = 1
                self.j += 1
                self.addImageViews(fullPath:fullPath)
            }
        }
    }
}
```

发现问题可能出在
```
for (SDWebImageDownloaderOperationToken *token in tokens)
{
}
```
可能在解码这段时间内，tokens数组增加了新的token，但是新来的token不会被创建Operation。
之前的版本出现的概率较低，是因为之前版本都是先生成图片，再获取completed数组，去执行

**Comment by dreampiggy** [comment]
> 新来的token不会被创建Operation
应该不是这个问题，就算我临时将所有访问`self.callbackTokens`改成`@synchronized`而不是临时拷贝一份拷贝，依然能复现这个问题

问题应该发生在Manager Level，而不是Cache/Download Level

**Comment by dreampiggy** [comment]
是不是和这里有关？5.14.0为了修复多个不同thumbnail size的请求对同一个url，改成了token模式，加锁加的是`self.callbackTokens`，即属性上

而之前是加锁加到`self`上

在Downloader这里有一个锁会锁Operation，属于跨对象的逻辑锁

![image](https://user-images.githubusercontent.com/6919743/216026987-d9803275-044e-4aa4-a49c-8e11967bf338.png)

**Comment by dreampiggy** [comment]
不需要加开关，Bug应该直接修复

**Comment by dreampiggy** [comment]
我重新review一下5.13.x到5.14.x的Diff，发现一个问题

## 5.13.x

之前的设计下，不同的addHandler加进来的block，都会统一在URLSessionTask的回调线程解码得到Image后，dispatch到main queue然后callback，参考：
https://github.com/SDWebImage/SDWebImage/blob/5.13.5/SDWebImage/Core/SDWebImageDownloaderOperation.m#L606-L616

这里写法很有意思，等到真正main queue执行时，会就地读一次“当前的callbackBlock，也就是说获取的callbackBlock时机是在main queue上。


## 5.14.x
而5.14之后，因为不同的callbackBlocks不再用同样的Image了（离谱吧，一个URL会callback出不同的UIImage，因为有thumbnail decoding传入的size差异），此时获取callbackBlock是在“URLSessionTask”线程中获取的

这个获取时机产生了差异。@fangandyuan  你那里的测试代码是不断dispatch_async到main queue然后添加新的callbackBlocks，因此在URLSessionTask这里判定肯定会有遗漏的情况（当main queue在添加callback，URLSessionTask已经进行到解码的代码行时，此时提前for-in循环获取的callbackBlocks就会漏掉现在正在添加的那个）

**Comment by dreampiggy** [comment]
我思考一下怎么改，主要问题是整个设计语义产生了差异，我始终觉得之前写法也有问题，因为它只解决了main queue添加的callbackBlock

假如我在自己创建的一个dispatch queue 1线程中进行addHandler操作，此时也有类似的原子操作问题。

合理的做法可能是：对`SDWebImageDownloaderOperation` 加一个`isCallbacking` 或者类似的标记，指的是此时我们已经锁定最终需要回调的callbacks数组了，此时后续新加的对同一个URL的请求，严格不能复用这个`SDWebImageDownloaderOperation`，需要重新创建一个新的URLSessionTask并进行网络请求。

这也是符合实践预期的，就跟排队上车，虽然都是“同一趟路线”（同一个URL），但是一旦发车之后，下一批乘客就不能再次上车，需要发到下一趟车（就算URL完全一样，也得重新去请求网络）

**Comment by dreampiggy** [comment]
另外，5.13.5也能复现这个问题，它从源头就没有解决这个原子性问题。只是复现概率（丢失的callback）少了而已

![image](https://user-images.githubusercontent.com/6919743/216567419-0278b33f-1e34-4c5d-bc77-1d28007e4a90.png)


我打算按照上面的说法，通过新的状态来判定是否应该复用DownloadOperation，在你这种代码发生时，可能会进行多次网络请求，但是不会丢失任何callback

**Comment by dreampiggy** [comment]
关于5.14.0的“为什么复现概率/丢失概率增加”，发现问题发生在NSOperation.addDependency

这个方法比用iOS13+的`[NSOperationQueue addBarrierBlock:]`，实际最终调度执行的要“慢”，导致了更多主线程async的callback被提交，进而丢失

直接在5.14.0，换用`[NSOperationQueue addBarrierBlock:]`，也能达到类似5.13.5的效果（虽然这没有从本质上避免问题）

打算丢弃NSOperation

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/216586754-802b45fd-b228-4065-be39-6452f1df6a30.png)

测试方案可行，不会丢任何Callback

**Comment by dreampiggy** [comment]
测试直接在`didCompleteWithError:`时发车，对于你这个fileURL因为下载太快了（可以认为接近一个dispatch_async的耗时），会导致最终创建了74个DownloadOperation和URLSessionTask，总共116次请求


如果是正常的网络请求，这部分并不会有这么搞的重新请求概率。

**Comment by dreampiggy** [comment]
Fixed in [5.15.1](https://github.com/SDWebImage/SDWebImage/releases/tag/5.15.1)
