### ISSUE TITLE
iOS 12.5.6  iPhone 6   在5.14.0 版本必现Crash   SDWebImageDownloaderOperation.m  614行                       dispatch_barrier_async(self.coderQueue.underlyingQueue, ^{

### ISSUE THREAD

**Issue by HeXiuLian** [SDWebImage/SDWebImage#3476]
![crash](https://user-images.githubusercontent.com/29196558/216221093-8e788ed5-b545-4e4f-8fe7-d0406b8195f7.jpg)

**Comment by dreampiggy** [comment]
https://github.com/SDWebImage/SDWebImage/issues/3433
重复Issue，升级至5.14.1以上
