### ISSUE TITLE
Completed Block not called

### ISSUE THREAD

**Issue by Hackmodford** [SDWebImage/SDWebImage#348]
It seems if there is an image already in the cache then the completed block for [self.imageView setImageWithURL:....]; is never called.

---

The first time this is called it works. But If I call the method again and it has already determined that there is no image to download the completed block is never called.

Here's some of my code

```
UIActivityIndicatorView *activityIndicator = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
            activityIndicator.center = self.customImageView.center;
            activityIndicator.hidesWhenStopped = YES;

            [activityIndicator startAnimating];
            [self.customImageView addSubview:activityIndicator];

            [self.customImageView setImageWithURL:[NSURL URLWithString:[NSString stringWithFormat:@"http://%@/%@.jpg",[[NSUserDefaults standardUserDefaults] stringForKey:@"imagePath"],[selectedItem.persistentID stringValue]]] placeholderImage:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType) {

                [activityIndicator removeFromSuperview];

            }];
```

The second time this method is called for an image that doesn't load (because it doesn't exist) the activity indicator doesn't get removed...

**Comment by chadkouse** [comment]
@Hackmodford Can you reopen this - it still seems like a bug to me

**Comment by mythodeia** [comment]
@EpicDraws @chadkouse
 i have tried it with the demo project and the completion block always fires. The only option set is the ```SDWebImageProgressiveDownload``` Can you reproduce it with the example source code?

**Comment by chadkouse** [comment]
In my case it's not firing for failed downloads.  I am not sure about images successfully retrieved from cache.  I will try the example source.

**Comment by mythodeia** [comment]
@chadkouse i added to the sample project a failedURL (404 image) and on the 1st view the image did not load. When i tapped on the cell to enter the details view the completion block fired just fine.
