### ISSUE TITLE
SDAnimatedImage gif animation speed much faster than original gif on iPhone 13 Pro Max

### ISSUE THREAD

**Issue by msimonetta1** [SDWebImage/SDWebImage#3491]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 16.0
 SDWebImage Version    |  5.11.1
 Integration Method  |    cocoapods
 Xcode Version        |   Xcode 14.1
 Repro rate          |    All the time on certain iPhone 13 Pro Max devices
 Repro with our demo prj | not sure
 Demo project link       | Demo Video of fast gif playback: https://imgur.com/a/Eu5dGmZ - video of original gif speed: https://imgur.com/a/GhqSdDe

### Issue Description and Steps

Its been reported that gif playback on iPhone 13 Pro Max's is much faster than the playback of the orignal gif file. Playback on other iOS devices works as expected. Implementation is very straightforward:

let animatedImage = SDAnimatedImage(named: "share-step.gif")
stepsImageView.setImage(animatedImage, animated: true)

https://user-images.githubusercontent.com/87341357/218089535-b1564129-5861-4aba-abd8-de9cffb639ff.mov
![ig-story-share-step-2-gif](https://user-images.githubusercontent.com/87341357/218089605-89819bfa-05dc-41b0-a55d-0db3e9b3a255.gif)

**Comment by dreampiggy** [comment]
Need iPhone Pro Motion series to debug.

Since SDWebImage is open-source, you can also use debugger to test, check code in `SDDisplayLink` and `SDAnimatedImagePlayer` logic of timing

**Comment by dreampiggy** [comment]
And, provide you sample animated image URL (uploaded here or privately send me email if it's sensitive)

**Comment by dreampiggy** [comment]
I guess this logic effect the result :

```
    duration = self.displayLink.targetTimestamp - CACurrentMediaTime();
    if (duration <= 0) {
        duration = kSDDisplayLinkInterval;
    }
```

When current display link render time finished, the duration will less than 0, but the `duration <= 0` will revert back that into `kSDDisplayLinkInterval` (which is 1/60 second)

This is not correct in my mind.

**Comment by dreampiggy** [comment]
Try with this fork branch and report your test result, I can not reproduce with an iPhone 13 Pro Max and [this sample gif url](https://raw.githubusercontent.com/liyong03/YLGIFImage/master/YLGIFImageDemo/YLGIFImageDemo/joy.gif)

https://github.com/dreampiggy/SDWebImage/tree/temp/try_fix_promotion

**Comment by csaq5507** [comment]
Experiencing the same issue with animated WebP. 
React-native app using react-native-fast-image.
react-native-fast-images use SDWebImage as I found in the .podspec:
```
...
s.dependency 'SDWebImage', '~> 5.11.1'
s.dependency 'SDWebImageWebPCoder', '~> 0.8.4'
...
```

Example image to test: 
[https://api.clava-sports.com/images/Dn9uR6KzTaEPJEG8tBZfyisqwObMp7op-wkQMIWGeSU.webp](https://api.clava-sports.com/images/Dn9uR6KzTaEPJEG8tBZfyisqwObMp7op-wkQMIWGeSU.webp)
Playback time: approx. 10 sec
Playback time on iPhone 13 Pro: < 5 sec

**Comment by dreampiggy** [comment]
> Try with this fork branch and report your test result, I can not reproduce with an iPhone 13 Pro Max and [this sample gif url](https://raw.githubusercontent.com/liyong03/YLGIFImage/master/YLGIFImageDemo/YLGIFImageDemo/joy.gif)
> 
> https://github.com/dreampiggy/SDWebImage/tree/temp/try_fix_promotion

@csaq5507 Please test this branch and report your test result

**Comment by msimonetta1** [comment]
@dreampiggy I've tested with the branch you provided and it is now working as expected. Tyvm

**Comment by dreampiggy** [comment]
So let's  ship it

**Comment by dreampiggy** [comment]
[5.15.3](https://github.com/SDWebImage/SDWebImage/releases/tag/5.15.3) released.
