### ISSUE TITLE
N identical requests, and the requested picture is illegal, there will be N*N failed callbacks, expect only N callbacks.

### ISSUE THREAD

**Issue by flypigrmvb** [SDWebImage/SDWebImage#3493]
N identical requests, and the requested picture is illegal, there will be N*N failed callbacks, expect only N callbacks.

Demo related code

`xxx` is the exception image URL

```
        [self.imgView sd_setImageWithURL:[NSURL URLWithString:@"xxx"] placeholderImage:nil completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
            NSLog(@"completed 1 end");
        }];

[self.imgView2 sd_setImageWithURL:[NSURL URLWithString:@"xxx"] completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
            NSLog(@"completed 2 end");
        }];
```

SDK internal code
```
[self callCompletionBlocksWithError:[NSError errorWithDomain:SDWebImageErrorDomain code:SDWebImageErrorBadImageData userInfo:@{NSLocalizedDescriptionKey : description}]];

- (void)callCompletionBlocksWithError:(nullable NSError *)error {
    [self callCompletionBlocksWithImage:nil imageData:nil error:error finished:YES];
}

- (void)callCompletionBlocksWithImage:(nullable UIImage *)image
                           imageData:(nullable NSData *)imageData
                               error:(nullable NSError *)error
                            finished:(BOOL)finished {
    NSArray<SDWebImageDownloaderOperationToken *> *tokens;
    @synchronized (self) {
        tokens = [self.callbackTokens copy];
    }
    for (SDWebImageDownloaderOperationToken *token in tokens) {
        SDWebImageDownloaderCompletedBlock completedBlock = token.completedBlock;
        if (completedBlock) {
            dispatch_main_async_safe(^{
                completedBlock(image, imageData, error, finished);
            });
        }
    }
}
```

**Comment by dreampiggy** [comment]
Provide the issue template

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / macos / tvos / watchos
 Platform Version        | e.g. 12.0 / 10.14.0 / 12.0 / 5.0
 SDWebImage Version      | e.g. 5.0.0 / 4.4.0
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 11 / Xcode 10
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

**Comment by dreampiggy** [comment]
@flypigrmvb 如果你用英文表达不清楚，用中文说明

提供一下Issue对应的SDWebImage版本号，以及你说明的复现Demo

**Comment by dreampiggy** [comment]
是说这一行在解码失败时，会导致重复回调？应该是callCompletionBlockWithToken吗？
<img width="1160" alt="截屏2023-02-18 17 22 47" src="https://user-images.githubusercontent.com/6919743/219852620-50f1c632-e146-4eed-852b-e348669dd8d7.png">

**Comment by flypigrmvb** [comment]
@dreampiggy 是的，这一行代码是在for循环中的，callCompletionBlocksWithImage方法内部也有个for循环，所以存在N*N次回调的问题。

**Comment by dreampiggy** [comment]
5.15.0版本重构导致的问题，已提PR，发5.15.3版本：
https://github.com/SDWebImage/SDWebImage/pull/3497

**Comment by flypigrmvb** [comment]
@dreampiggy 好的

**Comment by dreampiggy** [comment]
已添加单元测试防止此类愚蠢问题再次出现：`test31ThatMultipleRequestForSameURLFailedCallback`

**Comment by dreampiggy** [comment]
[5.15.3](https://github.com/SDWebImage/SDWebImage/releases/tag/5.15.3) released.
