### ISSUE TITLE
CGImageSourceCopyPropertiesAtIndex  Leak

### ISSUE THREAD

**Issue by TelenLiu** [SDWebImage/SDWebImage#3494]
in SDImageIOAnimatedCoder.m

CGImageSourceCopyPropertiesAtIndex，should be CFRelease

**Comment by dreampiggy** [comment]
Provide your leak detection result or code line ?

I check all these 3 and does not contains leak at all. 

Note the `__bridge_transfer` will transfer the reference count into ObjectiveC's NSDictionary, so it should not use `CFRelease`

**Comment by dreampiggy** [comment]
<img width="324" alt="截屏2023-02-18 17 17 32" src="https://user-images.githubusercontent.com/6919743/219852385-85fb9111-eb44-4808-8124-3872e88fdffb.png">

**Comment by TelenLiu** [comment]
Thank you for your reply. You are right, but my understanding of [ __bridge_transfer ] is wrong.
