### ISSUE TITLE
5.13.4 Crash: -[NSFileManager fileSystemRepresentationWithPath:]

### ISSUE THREAD

**Issue by leminhcse** [SDWebImage/SDWebImage#3504]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | iPadOS 14.7.1
 SDWebImage Version      | 5.13.4
 Integration Method      | cocoapods
 Xcode Version           | Xcode 14
 Repro rate              | only once
 Repro with our demo prj | couldn't reproduce
 Demo project link       | couldn't reproduce

### Issue Description and Steps

We are using pod and they are using SDWebImage, we noticed a crash when we updated SDWebImage (5.13.4), it looks related to some thread issue, Crashlytics nor Xcode could give us more information.

<img width="1291" alt="Screen Shot 2023-03-02 at 18 07 22" src="https://user-images.githubusercontent.com/45330126/222411643-edeeb2b6-2e65-489b-8c49-946462c8f05e.png">

**Comment by dreampiggy** [comment]
Seems duplicated for #crash filemana

Is this a NSException ? `reason: '*** -[NSFileManager fileSystemRepresentationWithPath:]: nil or empty path argument'`

**Comment by dreampiggy** [comment]
Where did you feed the nil key or nil path to SDWebImage ? I think there assert in debug mode



But if this is on release mode, seems will cause runtime exception

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/222653165-0f591bd5-2ef2-4385-8bbd-cc5fb7ded864.png)

We can add an extra guard here

**Comment by leminhcse** [comment]
> Where did you feed the nil key or nil path to SDWebImage ? I think there assert in debug mode
> 
> ![image](https://user-images.githubusercontent.com/6919743/222653319-7790aa73-9902-4586-b0e5-6d95a16911fe.png)
> 
> But if this is on release mode, seems will cause runtime exception

Hi @dreampiggy, This crash happen on release mode, not debug mode. I tried to reproduce but can't.

**Comment by dreampiggy** [comment]
> Crashlytics nor Xcode could give us more information.

And, your symbolication looks wrong. Try to re-symbolicate use your ipa dSYM, which will show exact the line of code for SDWebImage. Current I can only guess `where SDWebImage call that fileSystemRepresentation`， however actually there a re no direct call (some Objc call may be inlined)

**Comment by felipecastrosales** [comment]
how this is fixed? I'm passing for this problem

**Comment by dreampiggy** [comment]
Closed by #3690 in 5.19.1
