### ISSUE TITLE
SDImageWebPCoder's downsampling consumes a relatively large amount of memory

### ISSUE THREAD

**Issue by JaminZhou** [SDWebImage/SDWebImage#3508]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | iOS 16
 SDWebImage Version      | 5.15.0
 Integration Method      | SPM
 Xcode Version           | Xcode 14.2
 Repro rate              | all the time (100%) 
 Repro with our demo prj | TBD
 Demo project link       | TBD

### Issue Description and Steps
I have found a bug in the downscaling function of SDWebImage. It keeps allocating new memory and currently the memory is not released. This is particularly noticeable when downsampling animated WebP images, as there are many downscaled frames.

Behavior:
![image](https://user-images.githubusercontent.com/9011374/223067319-ec84172d-b289-44f8-89ef-54e17be5d212.png)

After attempting to fix:
![image](https://user-images.githubusercontent.com/9011374/223067341-f7773540-b1b2-480c-b1c7-194038fecd71.png)

Code for attempted fix:
![image](https://user-images.githubusercontent.com/9011374/223067366-803d81e4-021d-46b5-9e30-2b5e348faec6.png)

PS: The code for the attempted fix is not particularly rigorous and needs further refinement.

The problematic code is located within the `+ (CGImageRef)CGImageCreateScaled:(CGImageRef)cgImage size:(CGSize)size` method of the `SDImageCoderHelper` class.

**Comment by dreampiggy** [comment]
This is not leak. It just allocate memory and free when decode donw.

**Comment by dreampiggy** [comment]
And, you first change is wrong. This function is following `Create Rule`, which means

**if the return value is not null, then the caller must call `CFRelease` on it**. So, if we don't call `CFRetain` to make the CGImage + 2 retain count, after the caller call `CFRelease`, the origin input CGImage will dealloc !

```
// caller
CGImageRef inputCGImage; // obtain from other way, current retain count 1
CGImageRef newScaledCGImage = CGImageCreateScaled(inputCGImage); // if we directlly return self, this may still be retain count 1
if (newScaledCGImage) {
    printf("scaled size: %d %d", CGImageGetWidth(newScaledCGImage), CGImageGetHeight(newScaledCGImage));
    CFRelease(newScaledCGImage); // this is designed to dealloc newScaledCGImage, but not inputCGImage
    double originWidth = CGImageGetWidth(inputCGImage); // Crash here!
}
```

**Comment by dreampiggy** [comment]
Is the left one your changes ? How do vImage not allocating new memory buffer but create a new `scaled` one ?

**Comment by JaminZhou** [comment]
> Is the left one your changes ? How do vImage not allocating new memory buffer but create a new `scaled` one ?

Yes, the changes on the left-hand side are mine. Currently, this modification can solve the problem, but I have not done much research on it. Because during the investigation of the memory issue, I found that this section of code was causing it, so I made some attempt to fix it without being too rigorous.

**Comment by dreampiggy** [comment]
Maybe you can create a partial PR

and let me to invesigate the root case following your steps. Use instruments to find the real problem.

**Comment by dreampiggy** [comment]
And, a Demo for better reproduce is recommanded.

Current SDWebImage Demo can not reproduce your "Leak" issue, actually. Maybe you need to create one for me, like using WebP thumbnail animated decoding.

**Comment by JaminZhou** [comment]
In the SDWebImage demo project, I was able to reproduce the issue, and I will post the reproducible code tomorrow and submit a pull request for easier viewing of the changes. 

Currently, the issue can cause significant memory usage when not modified, but there have been no observed memory leaks at this time.

**Comment by dreampiggy** [comment]
I guess is not leak. It just break Apple's optimization about `lazy decoding`, if you can not understand what that means, check: https://dreampiggy.com/2022/11/07/%E6%8E%A2%E7%A7%98%E8%B6%8A%E6%9D%A5%E8%B6%8A%E5%A4%8D%E6%9D%82%E7%9A%84ImageIO%E6%A1%86%E6%9E%B6/

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/223618091-daff8ac2-bb5e-42d0-98de-0d1af523ec0b.png)

**Comment by dreampiggy** [comment]
vm_map可以做到两个Task（表现为两个进程）共享一份VM Memeory，只要没有write造成写冲突让Darwin Kernel触发拷贝。Xcode的这个内存面板显示的Owner和实际的不太一样，建议以Instruments 为准，它显示的是Task纬度（不是Process这种上层概念）

参考：https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/KernelProgramming/vm/vm.html

**Comment by dreampiggy** [comment]
你可以这样验证对比，你试试将这里代码改成：

```objective-c
- (nullable CGImageRef)sd_drawnWebpImageWithCanvas:(CGContextRef)canvas iterator:(WebPIterator)iter colorSpace:(nonnull CGColorSpaceRef)colorSpaceRef scaledSize:(CGSize)scaledSize CF_RETURNS_RETAINED {
    CGImageRef imageRef = [self sd_createWebpImageWithData:iter.fragment colorSpace:colorSpaceRef scaledSize:scaledSize]; // WARN <----- Modify here to output thumbnail
    if (!imageRef) {
        return nil;
    }
    
    size_t canvasWidth = CGBitmapContextGetWidth(canvas);
    size_t canvasHeight = CGBitmapContextGetHeight(canvas);
    CGFloat tmpX = iter.x_offset;
    CGFloat tmpY = canvasHeight - iter.height - iter.y_offset;
    CGRect imageRect = CGRectMake(tmpX, tmpY, iter.width, iter.height);
    
    BOOL shouldBlend = iter.blend_method == WEBP_MUX_BLEND;
    
    // If not blend, cover the target image rect. (firstly clear then draw)
    if (!shouldBlend) {
        CGContextClearRect(canvas, imageRect);
    }
    CGContextDrawImage(canvas, imageRect, imageRef);
    CGImageRef newImageRef = CGBitmapContextCreateImage(canvas);
    
    CGImageRelease(imageRef);

    if (iter.dispose_method == WEBP_MUX_DISPOSE_BACKGROUND) {
        CGContextClearRect(canvas, imageRect);
    }
    
    // WARN: <----- SKIP scale down
    
    return newImageRef;
}
```

不管渲染的动图是不是正常，只看内存占用

**Comment by dreampiggy** [comment]
<img width="1624" alt="截屏2023-03-08 12 46 45" src="https://user-images.githubusercontent.com/6919743/223622155-b7a3a28d-3aec-4cbb-80b2-8047ba7f027e.png">
[SDWebPThumbnailAnimation.trace.zip](https://github.com/SDWebImage/SDWebImage/files/10917303/SDWebPThumbnailAnimation.trace.zip)

和我猜想的一致，没有Leak，只是提前拷贝到CA RenderServer进程罢了，可以看这个trace


你如果不想要这个行为，可以加开关，目前有一个SDImageCoderDecodeUseLazyDecoding，我可以给WebPCoder支持上（注意，SDImageAWebPCoder本身有这个支持能力）

本质就是一个CPU和内存的平衡，因为动图渲染如果使用lazy decoding，会有大量动图短时间内必须在主线程解码。可能造成卡顿。默认行为推荐之所以设置为LazyDecoding 为False，因为提前分配内存拷贝，可以减缓CPU压力，在动图场景更适合，毕竟本身如果SDAnimatedImage工作正常，是能检测到内存压力并清除甄缓存的（但是有用户反馈有Bug不够及时）

**Comment by JaminZhou** [comment]
我检查了之前临时修复的代码，其实有些问题（会兜底跳过 scale down）。目前观察的现象：SDImageWebPCoder 比 SDImageAWebPCoder 处理 scale down 上会花费更多的内存。
以下是 500-500 的 webp scale down 到 480-480 的对比（总共 6 张动图）

SDImageWebPCoder
![image](https://user-images.githubusercontent.com/9011374/223621919-cb92a280-0863-454e-9b91-709ea0ff92aa.png)

SDImageAWebPCoder
![image](https://user-images.githubusercontent.com/9011374/223622127-8a844f6d-ae45-4c74-9988-ae02fc4393b8.png)

PS：此处我添加了一行 hard code代码，使得会走到同样的 scale down 处理
![image](https://user-images.githubusercontent.com/9011374/223622326-39ca1acb-02df-4434-b08c-04d6937f1a83.png)

关于内存泄漏问题，可能是我们业务代码的bug，而非SDK。

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/223622701-f20f35ed-ac75-4a9b-844a-da58bd5962bc.png)

**Comment by dreampiggy** [comment]
我先加开关吧，给WebPCoder支持SDImageCoderDecodeUseLazyDecoding是吧

**Comment by dreampiggy** [comment]
@JaminZhou 有什么思路吗？让libwebp自己产出bitmap buffer时就缩放，不要我后置分配新画布内存

**Comment by dreampiggy** [comment]
我好像懂了，是不是我`CGContextClearRect`用错了大小，应该要用scale以后的大小清理画布

**Comment by dreampiggy** [comment]
想到一个思路，不触发额外的Bitmap Buffer（vImage）分配

利用`CGContextScaleCTM`，我在Decode一帧之后，先SaveState，Scale Down，然后PopState

这样利用CGContext本身的Buffer池，避免一倍的额外中间消耗

**Comment by dreampiggy** [comment]
仔细想想，SDWebImageCore这里的CreateScaled也可以用`kvImageNoAllocate`优化

现在无论如何，如果要Create一个更小的Image，必须分配内存。但是原CGImage转为vImageBuffer这一过程不需要额外的内存开销。

所以合理的改法应该是，sourceBuffer用`kvImageNoAllocate`，destBuffer就地allocate，vImageScale_ARGB8888用`kvImageNoAllocate`

**Comment by dreampiggy** [comment]
@JaminZhou Please review and check:

Core: #3509
WebPCoder: https://github.com/SDWebImage/SDWebImageWebPCoder/pull/73

**Comment by JaminZhou** [comment]
> 



> @JaminZhou Please review and check:
> 
> Core: #3509 WebPCoder: [SDWebImage/SDWebImageWebPCoder#73](https://github.com/SDWebImage/SDWebImageWebPCoder/pull/73)

@dreampiggy  In the demo I reproduced, the issue was resolved by using the new SDWebImageWebPCoder.

**Comment by dreampiggy** [comment]
@JaminZhou Your first issue is about the ImageIO built-in WebP coder? (Which means the `SDImageAWebPCoder`, only works on iOS 14+ only)
![image](https://user-images.githubusercontent.com/6919743/223910682-5ec7a988-fcc9-4bc6-bf5b-9d088776c046.png)

Here it only use the `CGImageCreateScaled` when you request thumbnail but not keep aspect ratio (This is really rare and not default behavior), are you sure you're using this one ?

I used to talk about the issue on [SDImageWebPCoder](https://github.com/SDWebImage/SDWebImageWebPCoder), a custom coder built on top of open-source libwebp, which supports iOS 8+

**Comment by JaminZhou** [comment]
@dreampiggy Only hardcode in the demo for the convenience of testing and comparing the effects. It has not been used in actual production environment. Also, I found that SDImageAWebPCoder has more CPU usage when downsampling compared to SDImageWebPCoder. Is this a known issue?

**Comment by dreampiggy** [comment]
I said again, the usage of RAM for downsampling, is not always Xcode's memory graph shows.

You should clearify the `VM Alloc` and `Malloc`. VM Alloc will share memory buffer acorss process, which means, if I have a image which need 400MB (10240x10240 pixels)

# VM Alloc
Your App: 100MB (for other things)
CoreAnimation Render Process: 500MB (100MB + 400MB)

# Malloc
Your App: 500MB (100MB + 400MB)
CoreAnimation Render Process: 100MB

They both occupy 500MB, has no differences actually visiable to user.

**Comment by dreampiggy** [comment]
`SDImageAWebPCoder` use the `CGBitmapContext` and draw on it, which will transparently use `VM Alloc` because Core Graphics API assume you're rendering it on screen.

`SDImageWebPCoder` does not use canvas for most cases, it may use `Malloc` from libwebp for static WebP (For Animated WebP, it use `CGBitmapContext` and has similiar report)

**Comment by dreampiggy** [comment]
For more information, you can contact me privately, I've sent your email
