### ISSUE TITLE
How to remove cache for specific image?

### ISSUE THREAD

**Issue by hungwei0331** [SDWebImage/SDWebImage#3510]
I had an issue about cache from SDWebImage 5.9.5,

I would like to set a image url, and backend could change it dynamically in the future.

since  I had used `imageView.sd_setImage(with: url, placeholderImage: placeholderImage, options: .refreshCached)`

even tried clear cache before` imageView.sd_setImage`

for example 

```
SDImageCache.shared.clearMemory()
SDImageCache.shared.removeImage(forKey: url, cacheType: .all)

SDWebImageManager.shared.imageCache.removeImage(forKey: url, cacheType: .all)
SDWebImageManager.shared.imageCache.clear(with: .all) 
```
but still could not get the latest image, only show the image which get by first time download,

appreciate if there any suggestion or help, thank you.

**Comment by dreampiggy** [comment]
The disk cache remove is async function, you need to put your `sd_setImage` code into the async callback.

Or, if you don't care about **Blocking current thread** (maybe main thread), you can use the sync version API:

```swift
SDImageCache.shared.removeImageFromMemory(for: key)
SDImageCache.shared.removeImageFromDisk(for: key)
```

**Comment by hungwei0331** [comment]
thank you @dreampiggy, 
I had tried from you all suggestion,
even test it with async sync syntax as well, but it still could not clear the cache,
does there an other way to implement it, sorry for bother you 

`            SDImageCache.shared.removeImage(forKey: url) {
                SDImageCache.shared.removeImageFromDisk(forKey: url)
                SDImageCache.shared.removeImageFromMemory(forKey: url)
                imageView.sd_setImage(with: url, placeholderImage: nil, options: options, completed: completionHandler)
                }
            }
`

**Comment by dreampiggy** [comment]
Maybe I misunderstand your request.

Is this the similar feature request like https://github.com/SDWebImage/SDWebImage/issues/2904 ?

**Comment by dreampiggy** [comment]
Actually, can URLSessionTask itself download your URL cause wrong cache ? Since it's nothing magic and open sourced. You can have a test again to check whether it's your server side issue (For example, are you return the HTTP E-tag or something correctly)
