### ISSUE TITLE
SDWebImage playback GIFs too fast on watchOS

### ISSUE THREAD

**Issue by vincentneo** [SDWebImage/SDWebImage#3511]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | watchos
 Platform Version        | 9.1
 SDWebImage Version      | 5.15.2 (working fine) / 5.15.5 (problematic)
 Integration Method      | SPM
 Xcode Version           | Xcode 14.2
 Repro rate              | all the time (100%) 
 Repro with our demo prj | unsure
 Demo project link       | https://github.com/vincentneo/SDWebImageSpeedIssue

### Issue Description and Steps

I am using `SDWebImage` with `SDWebImageSwiftUI`, but I am inclined to believe that it doesn't matter, as things work fine if downgraded to 5.15.2.

Basically, the issue is with the fact that 5.15.5 plays the GIF at a speed that's way too fast, while 5.15.2 plays it at the right speed. 
I have not tested the releases in between the 2 versions mentioned, because I believe it has something to do with the fix introduced for #3377. 

Below are 2 examples of what I am seeing. You may also view the demo repository, which includes 2 branches, aptly named according to the respective SDWebImage versions.

![sdwebimage5 15 2](https://user-images.githubusercontent.com/23420208/227169330-a205c761-ec31-4eaa-a6de-e9ab4bc21f2d.gif)
![sdwebimage5 15 5](https://user-images.githubusercontent.com/23420208/227169339-5c0ad9fa-b95b-4f0e-8030-9d1e49ddf4a5.gif)

For your reference, this is the GIF shown in the above examples:
![example actual gif](https://media.tenor.com/oTeBa4EVepMAAAAM/business-cat-working.gif)

**Comment by vincentneo** [comment]
Note that I when preparing the demo GIFs above, I accidentally enabled the loop option. As a result, the looping is just a side effect of the preparation. Just focus on the speed of playback.

**Comment by dreampiggy** [comment]
Need some time to test. The silly solution is to revert back the changes specified to watchOS in `SDDisplayLink`
