### ISSUE TITLE
How to Solve the Memory Explosion Problem of Multiple GIFs?

### ISSUE THREAD

**Issue by HanX1ao** [SDWebImage/SDWebImage#3515]
Crashed: com.apple.main-thread
0  libsystem_platform.dylib       0x91c _platform_memmove + 76
1  ImageIO                        0x1e9634 GIFBufferInfo::GIFBufferInfo(unsigned char*, bool, unsigned int, unsigned int, unsigned int) + 108
2  ImageIO                        0x1fb464 std::__1::__shared_ptr_emplace<GIFBufferInfo, std::__1::allocator<GIFBufferInfo> >::__shared_ptr_emplace<unsigned char*&, bool, unsigned int&, unsigned int&, unsigned int>(std::__1::allocator<GIFBufferInfo>, unsigned char*&, bool&&, unsigned int&, unsigned int&, unsigned int&&) + 76
3  ImageIO                        0x1fb3e4 std::__1::shared_ptr<GIFBufferInfo> std::__1::allocate_shared<GIFBufferInfo, std::__1::allocator<GIFBufferInfo>, unsigned char*&, bool, unsigned int&, unsigned int&, unsigned int, void>(std::__1::allocator<GIFBufferInfo> const&, unsigned char*&, bool&&, unsigned int&, unsigned int&, unsigned int&&) + 88
4  ImageIO                        0x1facd4 GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 800
5  ImageIO                        0x1a8a0 IIO_Reader::CopyImageBlockSetProc(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 280
6  ImageIO                        0x16370 IIOImageProviderInfo::copyImageBlockSetWithOptions(CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 744
7  ImageIO                        0x1e480 IIOImageProviderInfo::CopyImageBlockSetWithOptions(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 836
8  QuartzCore                     0xa4200 CA::Render::copy_image(CGImage*, CGColorSpace*, unsigned int, double, double) + 2944
9  QuartzCore                     0xe935c CA::Render::prepare_image(CGImage*, CGColorSpace*, unsigned int, double) + 24
10 QuartzCore                     0x112cc -[CAKeyframeAnimation CA_prepareRenderValue] + 64

**Comment by dreampiggy** [comment]
Seems you're using UIAnimatedImage (See that CAKeyframeAnimation), which will load all frames into memory, it's not safe for huge frame GIF images.

Try with SDAnimatedImage instead ? https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50

**Comment by HanX1ao** [comment]
you mean if I use that can solve?
```swift
let imageView = SDAnimatedImageView()
imageView.sd_setImage(with: imageURL)
```

**Comment by dreampiggy** [comment]
> Atually, it doesn't solve my problem

Can you provide you demo ? Actually, SDAnimatedImageView or FLAnimatedImageView, from the core design part (using a frame buffer cache and window to decode frame just in time) is the same

So it should works as the similiar performance.

**Comment by HanX1ao** [comment]
> > Atually, it doesn't solve my problem
> 
> Can you provide you demo ? Actually, SDAnimatedImageView or FLAnimatedImageView, from the core design part (using a frame buffer cache and window to decode frame just in time) is the same
> 
> So it should works as the similiar performance.

[SDAnimatedImageViewDemo.zip](https://github.com/SDWebImage/SDWebImage/files/11295301/SDAnimatedImageViewDemo.zip)
You should use Your iPhone to debug, not simulator

**Comment by HanX1ao** [comment]
@dreampiggy Do you think so?

**Comment by dreampiggy** [comment]
Possible relative to #https://github.com/SDWebImage/SDWebImage/issues/3449 and https://github.com/SDWebImage/SDWebImage/pull/3445

**Comment by dreampiggy** [comment]
There are two PR will solve your issue. Let me explain

1. A bug that cause your demo (query multiple same URL at the same time), which will cause un-wanted decode in parallels, because we `can not communicate with each other's image query pipeline`. So, When  multiple query happened, during the memory cache miss, then we will try to decode. Here we switch the GCD queue (and maybe next runloop), but the first decode and memory written may be already succssed. We can do an extra memory cache query to avoid this :)

**Comment by dreampiggy** [comment]
2. Use a global shared buffer pool for the same `URL` image
Previouslly, if you have 20 imageView, which will create 20 imagePlayer, and create 20 `NSMutableDictionary` to store each frame index's `UIImage`.

This design is not as good as we want. :(

Because if the URL is same (let assume one GIF contains 100 frames), even with 20 imageViews, we actually need to store `100` UIImage, right ? But here we need `20 * 100` UIImage because of the history design.

A new design was to introduce a `per-URL` frame cache, don't reply on what numbers of imageView it references. This can solve your common usage case if you load same URL image into different imageViews.

**Comment by HanX1ao** [comment]
> ### 2. Use a global shared buffer pool for the same `URL` image
> Previouslly, if you have 20 imageView, which will create 20 imagePlayer, and create 20 `NSMutableDictionary` to store each frame index's `UIImage`.
> 
> This design is not as good as we want. :(
> 
> Because if the URL is same (let assume one GIF contains 100 frames), even with 20 imageViews, we actually need to store `100` UIImage, right ? But here we need `20 * 100` UIImage because of the history design.
> 
> A new design was to introduce a `per-URL` frame cache, don't reply on what numbers of imageView it references. This can solve your common usage case if you load same URL image into different imageViews.
> 
> The second PR is in-draft. I'll reply after May 4th. @HanX1ao You can also contact me via WeChat if you're using Chinese
> 
>  SDAnimatedImageViewDemo.mov

我把我的联系方式发到你的126邮箱了，期待回复。

**Comment by dreampiggy** [comment]
@HanX1ao  Did not get the email, resend again ? :)

And, you can directly use #3524 branch (mostly finished) for SDWebImage to test in your production App to see the performance diff.

**Comment by HanX1ao** [comment]
> @HanX1ao Did not get the email, resend again ? :)
> 
> And, you can directly use #3524 branch (mostly finished) for SDWebImage to test in your production App to see the performance diff.

send again

**Comment by HanX1ao** [comment]
> @HanX1ao Did not get the email, resend again ? :)
> 
> And, you can directly use #3524 branch (mostly finished) for SDWebImage to test in your production App to see the performance diff.

I tried your changes and found that whether it's multiple URLs or a single URL, there will be high CPU usage causing the playback speed to become very slow, which feels a bit poor, but the crash issue has been resolved.

**Comment by dreampiggy** [comment]
Test 5.16.0 and report more issue or re-open this:

https://github.com/SDWebImage/SDWebImage/releases/tag/5.16.0
