### ISSUE TITLE
SDBundlePreferredScales/SDImageScaleFactors - A function declaration without a prototype is deprecated in all versions of C

### ISSUE THREAD

**Issue by JulzPolz** [SDWebImage/SDWebImage#3518]
### New Issue Checklist

* [-] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [-] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [-] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 16
 SDWebImage Version      | 5.15.5
 Integration Method      | manually
 Xcode Version           | 14.3
 Repro rate              | all the time (100%)
 Repro with our demo prj | yes
 Demo project link       | n/a

### Issue Description and Steps

Warning at compile time against the latest iOS16. Both references to `SDBundlePreferredScales` and `SDImageScaleFactors` yield the same error: `A function declaration without a prototype is deprecated in all versions of C`. They are the only warnings on the project, so would be good to resolve/suppress them.

<img width="1406" alt="Screenshot 2023-04-20 at 14 03 38" src="https://user-images.githubusercontent.com/153706/233374673-f7995d49-1bc1-4807-b054-28c1a3ac58f9.png">
<img width="1364" alt="Screenshot 2023-04-20 at 14 03 29" src="https://user-images.githubusercontent.com/153706/233374667-3370f791-2555-4f82-a76b-4c4430f74200.png">
<img width="261" alt="Screenshot 2023-04-20 at 14 03 24" src="https://user-images.githubusercontent.com/153706/233374658-fa4780af-4603-46f2-88f7-482af1f95fcc.png">

**Comment by dreampiggy** [comment]
Added `void` in param will fix this
