### ISSUE TITLE
GIF load crash?

### ISSUE THREAD

**Issue by a7340103** [SDWebImage/SDWebImage#3529]
### New Issue Checklist

* [✅] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [✅] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [✅] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           iOS
 Platform Version        16+
 SDWebImage Version      5.15.5

### Issue Description and Steps

![image](https://user-images.githubusercontent.com/15100013/236614639-3038883b-d5dd-4c11-b891-484366fd94e5.png)

**Comment by dreampiggy** [comment]
I don't think this issue is related to SDWebImage, maybe fire radar to Apple firstly.
