### ISSUE TITLE
Getting a NSInvalidArgumentException on SDWebImageDownloaderOperation.m line 59 

### ISSUE THREAD

**Issue by pnicholls** [SDWebImage/SDWebImage#354]
I am using SDWebImage to load images in tableview cells:

``` objective-c
[cell.profileImageView setImageWithURL:user.profileUrlSquare placeholderImage:[UIImage imageNamed:@"profile-placeholder.gif"] options:SDWebImageRefreshCached];
```

I keep hitting this error with the app crashing:

``` objective-c
Exception Type: NSInvalidArgumentException
Reason: -[__NSMallocBlock__ appendData:]: unrecognized selector sent to instance 0x1eb3d000

__59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke
```

Any ideas?

Cheers

**Comment by kostassite** [comment]
Still having this issue with 21656fad68084e682a18eb638077989351a7cb52

**Comment by maximkhatskevich** [comment]
@rs this might be an issue again. iOS 8.4, SDWebImage 3.7.3.

I'm getting crashes with message like this: "malloc: *** error for object 0x17cd03320: Freeing unallocated pointer *** set a breakpoint in malloc_error_break to debug" when using "[[SDImageCache sharedImageCache] storeImage:forKey:];" for image preloading. See screenshot attached. Any suggested are very welcome!

<img width="1013" alt="screen shot 2015-07-29 at 04 51 25" src="https://cloud.githubusercontent.com/assets/2624646/8949607/8bcea4e6-35ad-11e5-81a5-13ac97d193ba.png">
