### ISSUE TITLE
dyld: Symbol not found: _kCGImagePropertyHEICSDelayTime

### ISSUE THREAD

**Issue by cikichen** [SDWebImage/SDWebImage#3555]
### New Issue Checklist

dyld: Symbol not found: _kCGImagePropertyHEICSDelayTime
  Referenced from: /private/var/containers/Bundle/Application/EB5336A2-A843-424A-B77C-51CD6CDE3334/xxx.app/Frameworks/SDWebImage.framework/SDWebImage (which was built for iOS 13.0)
  Expected in: /System/Library/Frameworks/ImageIO.framework/ImageIO
 in /private/var/containers/Bundle/Application/EB5336A2-A843-424A-B77C-51CD6CDE3334/xxx.app/Frameworks/SDWebImage.framework/SDWebImage
(lldb) 
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name         | ios
 Platform Version       | 12.5.6
 SDWebImage Version    |  5.16.0
 Integration Method      |cocoapods
 Xcode Version           |xcode 14.3.1
 Repro rate              |all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by dreampiggy** [comment]
I don't think you can use HEIF coder in iOS 12.5.6.

**Comment by dreampiggy** [comment]
If you still believe this is issue of SDWebImage (not your usage level issue), please re-open and provide more information or re-production demo
