### ISSUE TITLE
Usage of NSURLCreationDateKey need Privacy Manifest (xcprivacy)

### ISSUE THREAD

**Issue by erikkerber** [SDWebImage/SDWebImage#3574]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Description and Steps

New privacy requirements coming in iOS 15/Fall 2023 restrict the usage of certain APIs that may be used for fingerprinting. The list of APIs and allowed reasons can be found in the [Privacy Manifest Files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc) documentation.

SDWebImage uses one of those APIs [for cache invalidation](https://github.com/SDWebImage/SDWebImage/blob/bc4d0c7c62364616c29f23d13ed4f047f5ecb870/SDWebImage/Core/SDDiskCache.m#L156):

- `NSURLCreationDateKey`

Any app that uses this API must provide a reason, and cache invalidation is unfortunately not an accepted use:

> DDA9.1
> Declare this reason to display file timestamps to the person using the device.
> 
> Information accessed for this reason, or any derived information, may not be sent off-device.
> 
> C617.1
> Declare this reason to access the timestamps of files inside the app container, app group container, or the app’s CloudKit container.
> 
> 3B52.1
> Declare this reason to access the timestamps of files or directories that the user specifically granted access to, such as using a document picker view controller.

If I'm interpreting everything correctly, a new time-based mechanism is needed or apps using SDWebImage will be rejected.

**Comment by dreampiggy** [comment]
See #3550

**Comment by dreampiggy** [comment]
And actually, even if SDWebImage don't provide one, as an App developer, you can declare that xcprivacy by your own as well

**Comment by erikkerber** [comment]
The new page released alongside Xcode 15 Beta 5, and I think this detail was lost a bit in translation with my post:

> Your app or third-party SDK must declare one or more approved reasons that accurately reflect your use of each of these APIs and the data derived from their use. You may use these APIs and the data derived from their use for the declared reasons only. These declared reasons must be consistent with your app’s functionality as presented to users, and you may not use the APIs or derived data for tracking.

I admit I glossed over that this is an approved reason as I wrote this last night 🥴 

> C617.1
> Declare this reason to access the timestamps of files inside the app container, app group container, or the app’s CloudKit container.

Which is what would apply to SDWebImage's use of `NSURLCreationDateKey`. I'll close this out as nothing above the linked ticket then.

**Comment by wlxo0401** [comment]
@dreampiggy 
If the library developer doesn't provide PrivacyInfo, should the app developer create PrivacyInfo files in the app project and analyze and add the library's code??

Does xcprivacy not have to belong to library files??

**Comment by dreampiggy** [comment]
YES.
YES.
