### ISSUE TITLE
A non-loading gif ends up in some other image cache

### ISSUE THREAD

**Issue by larkox** [SDWebImage/SDWebImage#3580]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 16.5.1
 SDWebImage Version      | 5.17.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 14.3.1
 Repro rate              | I have a setup that reproduces 90% of the time, but it is hard to get that setup
 Repro with our demo prj | Haven't tried
 Demo project link       | Haven't got one

### Issue Description and Steps

We have an app done in React Native, and we are using FastImage to load images. This uses in the background SDWebImage for iOS almost directly. Here is the relevant code from FastImage: https://github.com/DylanVann/react-native-fast-image/blob/main/ios/FastImage/FFFastImageView.m

The issue we are facing seems similar to this one: https://github.com/SDWebImage/SDWebImage/issues/2383
But any of the solutions there does not seem to be working for me.

In my scenario, a few images are loaded at the same time. But one particular gif (in my setup is always [this gif](https://media3.giphy.com/media/3o6gDWzmAzrpi5DQU8/200w.gif), but this has been reported with other non-gif images (but potentially large)), oftentimes doesn't load the first time. Instead of that, one of the other images shows that gif.

I don't know the architecture of SDWebImage, so not sure if what I am going to say is accurate, but my guess is that somehow, the "image finished loading" event is being listened by the wrong image, setting the cache to the wrong image, and letting the original image "waiting forever".

Just sanity check, I have checked that the values passed to `sd_setImageWithURL` are the correct ones and the completion handler is being called with the correct  `imageURL` (`source.url === imageUrl`). Also, I have checked that sd_setImageWithURL is called for the gif, but the completion handler is never called for it when this happens.

**Comment by dreampiggy** [comment]
I guess this maybe some race condition.

Can you have a test with the latest version (5.18.3) ? There are some related changes about this during 5.17.0->5.18.3

**Comment by larkox** [comment]
@dreampiggy We recently updated to 5.18.2. I will keep my eyes peeled to see if we receive any other report of this, and close this ticket accordingly. We received a report not long ago, but I think it might be that the cache got "polluted" before the update, and they only noticed after the update. Nevertheless, that makes me wary about marking the issue as fixed on our side :sweat_smile:

**Comment by larkox** [comment]
I closed the issue on my side, so I will close it here too. If we hear more reports, I may reopen it :sweat_smile: 

Thank you very much for the work on the library! :tada:
