### ISSUE TITLE
Release RAM 

### ISSUE THREAD

**Issue by tanlucvo** [SDWebImage/SDWebImage#3584]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

When sd_setImageWithURL many time on UIImageView ram not release, use with `context:@{SDWebImageContextStoreCacheType: @(SDImageCacheTypeDisk)}`. It only release when i set option is `SDWebImageFromLoaderOnly` but can't load from cache from disk. How to load image cache from disk and release RAM when `removefromsupview` or `sd_setImageWithURL` again ?

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          |IOS
 SDWebImage Version  |   latest

**Comment by dreampiggy** [comment]
...
https://github.com/SDWebImage/SDWebImageWebPCoder/issues/80#issuecomment-1680730633

Just call `[SDImageCache.sharedCache removeCacheFromMemoryForKey:[SDWebImageManager.sharedManager cacheKeyForURL:url]]`

**Comment by tanlucvo** [comment]
oh my bad, I'm missing it. Thank you
