### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException

### ISSUE THREAD

**Issue by mmdock** [SDWebImage/SDWebImage#3585]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        |  14-16
 SDWebImage Version      | 5.17.0
 Integration Method      | SPM
 Xcode Version           | Xcode 14.2
 Repro rate              | NA
 Repro with our demo prj | NA
 Demo project link       | NA

<img width="294" alt="Screenshot 2023-08-18 at 11 31 40 AM" src="https://github.com/SDWebImage/SDWebImage/assets/2423465/d2d33edb-a291-4ac4-ab8b-e23e122f8d27">

### Issue Description and Steps

Do not know how to reproduce, it is a crash i am seeing in my Crashlytics.
Fatal Exception: NSInternalInconsistencyException
Invalid parameter not satisfying: imageData

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x9cb4 __exceptionPreprocess
1  libobjc.A.dylib                0x183d0 objc_exception_throw
2  Foundation                     0x4e1688 -[NSMutableDictionary(NSMutableDictionary) initWithContentsOfFile:]
3  Her                            0xa83a70 SDImageLoaderDecodeProgressiveImageData + 98 (SDImageLoader.m:98)
4  Her                            0xa8bd6c __68-[SDWebImageDownloaderOperation URLSession:dataTask:didReceiveData:]_block_invoke + 485 (SDWebImageDownloaderOperation.m:485)
5  Foundation                     0xa6ef4 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
6  Foundation                     0x7b000 -[NSBlockOperation main]
7  Foundation                     0x7af90 __NSOPERATION_IS_INVOKING_MAIN__
8  Foundation                     0x3c4b8 -[NSOperation start]
9  Foundation                     0x3c1ec __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
10 Foundation                     0x4187c __NSOQSchedule_f
11 libdispatch.dylib              0x12fc4 _dispatch_block_async_invoke2
12 libdispatch.dylib              0x3eac _dispatch_client_callout
13 libdispatch.dylib              0x7330 _dispatch_continuation_pop
14 libdispatch.dylib              0x6998 _dispatch_async_redirect_invoke
15 libdispatch.dylib              0x15944 _dispatch_root_queue_drain
16 libdispatch.dylib              0x16158 _dispatch_worker_thread2
17 libsystem_pthread.dylib        0xda0 _pthread_wqthread
18 libsystem_pthread.dylib        0xb7c start_wqthread

**Comment by dreampiggy** [comment]
This is a assert. The `imageData` arg should not be nil.

Provide your SDWebImage version ? @mmdock

**Comment by dreampiggy** [comment]
Maybe it's a old version bug...Seems need to make this property access become `Atomic`

**Comment by dreampiggy** [comment]
@mmdock Can you check your SDWebImage version again ?

This `__68-[SDWebImageDownloaderOperation URLSession:dataTask:didReceiveData:]_block_invoke + 485 (SDWebImageDownloaderOperation.m:485)`

The file line number does not match the thread function call, maybe it's not 5.17.0 ?
