### ISSUE TITLE
Crashed: com.hackemist.SDWebImageDownloader.downloadQueue (QOS: UNSPECIFIED)

### ISSUE THREAD

**Issue by mmdock** [SDWebImage/SDWebImage#3586]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14-16
 SDWebImage Version      | 5.17.0
 Integration Method      | SPM
 Xcode Version           | Xcode 14.2
 Repro rate              | NA
 Repro with our demo prj | NA
 Demo project link       | NA

### Issue Description and Steps

stack trace: 
[com.dattch.dattch_issue_dc5651c7030de33db25b32e89bdc95e5_crash_session_a61db7e7a93140bb992cc9f1b3111314_DNE_8_v2_stacktrace.txt](https://github.com/SDWebImage/SDWebImage/files/12383163/com.dattch.dattch_issue_dc5651c7030de33db25b32e89bdc95e5_crash_session_a61db7e7a93140bb992cc9f1b3111314_DNE_8_v2_stacktrace.txt)

crash on: SDWebImageDownloaderOperation.m:230

**Comment by BaluNaik** [comment]
Same issue for us.

**Comment by BaluNaik** [comment]
@dreampiggy  @bpoplauschi.

**Comment by dreampiggy** [comment]
Don't you think this is Apple's bug ?

And, it's already reported, like https://github.com/SDWebImage/SDWebImage/issues/3610

**Comment by dreampiggy** [comment]
And actually, see your stacktrace.

it's not cause crash by SDWebImage, it's caused by `FirebasePerformance` function
