### ISSUE TITLE
缓存读取问题（已解决）

### ISSUE THREAD

**Issue by kangbingbing** [SDWebImage/SDWebImage#3588]
**最新版5.17.0版本**
首先shouldCacheImagesInMemory 使用内存缓存是默认开启的，我在使用过程中，已经在内存缓存中的数据，再次刷新页面，可能会出现错乱的bug。bug复现如下图gif。

上方图片本身是红色，下方是键盘，一旦发送一个文本刷新后两张图片的image会调换，禁用内存缓存后，问题不在复现。`[SDImageCacheConfig defaultCacheConfig].shouldCacheImagesInMemory = NO;`
**所以猜测应该是从内存中读取数据时有问题。**

![20230824-145940](https://github.com/SDWebImage/SDWebImage/assets/15312953/68ed70b0-8f2c-422d-bed2-4c886e991317)

**Comment by dreampiggy** [comment]
Provide a demo, I think this is your business logic error.

The only differences between (in default options) memory cache and disk cache is:

1. Memory cache query is *Sync*
2. Disk cache query is *Async*

So maybe your logic cause error when hitting *Sync* query.

You can do a test again, by using the options `SDWebImageQueryDiskData | SDWebImageQueryDiskDataSync` with the disabled memory cache  (via `context[SDWebImageQueryCacheType] = @(SDImageCacheTypeDisk)`), which should also contains issues.

**Comment by dreampiggy** [comment]
See usage: https://sdwebimage.github.io/documentation/sdwebimage/
See wiki: https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#behavior-about-asyncsync-control-for-cache

**Comment by kangbingbing** [comment]
> See usage: https://sdwebimage.github.io/documentation/sdwebimage/ See wiki: https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#behavior-about-asyncsync-control-for-cache
感谢，使用了SDWebImageQueryMemoryData ，解决问题。
