### ISSUE TITLE
SDWebImageManager.shared.loadImage is causing excessive memory usage.

### ISSUE THREAD

**Issue by HanX1ao** [SDWebImage/SDWebImage#3611]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        |  16
 SDWebImage Version      |  5.18.0
 Integration Method      |  spm
 Xcode Version           |  Xcode 15
 Repro rate              |  all the time (100%)

### Issue Description and Steps

```swift
// method 1
SDWebImageManager.shared.loadImage(
    with: url,
    options: [],
    context: nil,
    progress: nil
)

// method 2
sd_setImage(
    with: url,
    placeholderImage: nil,
    options: [],
    context: nil,
    progress: nil
)
```
The two methods mentioned above, when given the same parameters, result in significantly higher memory consumption for Method 1 if a GIF image is being loaded. What could be the reason for this?

**Comment by dreampiggy** [comment]
The second one when operate on `SDAnimatedImageView`, it will pass additional context `SDWebImageContextAnimatedImageClass : SDAnimatedImage.class`

So, the loaded `UIImage` or `SDAnimatedImage` has different RAM occupy.

Just the simple question when you look at the source code :)
