### ISSUE TITLE
memory may overflow when using SDAnimatedImage.sd_imageDataAsFormat:SDImageFormatGIF

### ISSUE THREAD

**Issue by jiasongs** [SDWebImage/SDWebImage#3616]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name      | iOS
 Platform Version      | 13.0
 SDWebImage Version  | 5.18.2
 Integration Method   | cocoapods
 Xcode Version  | Xcode 15.0
 Repro rate    | all the time
 Repro with our demo prj | demo
 Demo project link  | [SDWebImageDemo.zip](https://github.com/SDWebImage/SDWebImage/files/12839876/SDWebImageDemo.zip)

### Issue Description and Steps

As shown in the demo, when using sd_imageDataAsFormat to convert to SDImageFormatGIF, there will be a lag phenomenon, and it is likely to cause memory overflow. It stands to reason that the image itself loads pictures in gif format, and then converting to SDImageFormatGIF should not cause this situation.

**Comment by dreampiggy** [comment]
`SDAnimatedImage` was not designed as orignally to do `Transcoding` from GIF to APNG/AWebP...Because it actually retain the original image data (via `image.sd_imageData`) or `SDAnimatedImage.imageData`

I think you can just use that instead, and call ImageIO by your hand ?

If you really think SDWebImage can help for some common simple utils, maybe `SDAnimatedImage` need to override that `sd_imageAsFormat:` API and provide its own implementation

**Comment by dreampiggy** [comment]
A question ? If the input SDAnimatedImage `animatedImageFormat` is equal to the transcoding format (input GIF, output GIF), why not just call 

```swift
let data = animatedImage.sd_imageData
//
let data = animatedImage.sd_imageData(as: GIF)
```

**Comment by dreampiggy** [comment]
A simple naive solution is that, if:

+ ouput.format == input.format
+ compressionQuality == 1

Then it will always return the internal data, instead of do actual transcoding

**Comment by dreampiggy** [comment]
Should be closed by #3617, test that instead.

**Comment by jiasongs** [comment]
> 应该由 [#3617 ](https://github.com/SDWebImage/SDWebImage/pull/3617)关闭，改为测试它。

Thanks, I think (https://github.com/SDWebImage/SDWebImage/pull/3617/commits/4acf569171ba762b4d5a9cbf64487fb3493489b5) can solve this problem. What I don’t understand is that using sd_imageDataAsFormat:.GIF will cause the memory to be too large, but this picture is only 6.5M

**Comment by dreampiggy** [comment]
> but this picture is only 6.5M

I think you don't understand how bitmap image (compared to vector image) occupy memory.

RAM = frame count * bytes per frame
+ bytes per frame = bytes per pixel * pixel count
+ bytes per pixel = 4 (for RGBA8888) or 8 (for RGBA16161616, HDR image)

This image: https://raw.githubusercontent.com/liyong03/YLGIFImage/master/YLGIFImageDemo/YLGIFImageDemo/joy.gif, is 2.1MB, but if you load full frames into memory, will occupy 800MB+ (120 frames, 7MB per frame)

**Comment by dreampiggy** [comment]
There is known limitation that `SDImageCoder` API `encodedImageWithFrames:` is not suitable for large frame images. Because it use `NSArray`

A better API design (which break API) should be :

```
let encoder = SDImageCoder(encodeFormat: .gif, options: nil)
let animatedImage: SDAnimatedImage
let frameCount = animatedImage.animatedFrameCount
for index in frameCount {
    let frame = animatedImage.animatedImage(at: index)!
    ehcoder.addImage(frame)
}
let data = encoder.encode(options: nil)
```

**Comment by jiasongs** [comment]
> RAM = frame count * bytes per frame

Thanks, I understand

**Comment by dreampiggy** [comment]
@jiasongs So it's time to merge that #3617 ? Any extra question ?

**Comment by jiasongs** [comment]
> @jiasongs那么是时候合并 [#3617 ](https://github.com/SDWebImage/SDWebImage/pull/3617)了？ 还有其他问题吗？

No problem

**Comment by dreampiggy** [comment]
Use 5.18.3 version instead.
