### ISSUE TITLE
SDWebImage randomly not showing in UITableViewCell

### ISSUE THREAD

**Issue by cromanelli** [SDWebImage/SDWebImage#363]
Hello I have a script that downloads an image and dynamically sets the UITableView height after it finishes the download, but some images randomly do not show , the curious think is that when i change back and forth the tab the images suddenly appear . in the options argument i am passing SDWebImageRetryFailed.

Any idea would be more than welcome , thanks. 

``` Objective-C
-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    item = [news objectAtIndex:[indexPath row]];
    cell = [tableView dequeueReusableCellWithIdentifier:@"FrontPageNewsCell"];
    [[cell newsTitle] setText:[item title]];
    [[cell newsVideo] setAlpha:0.0];
    if ([item newsImageURL]){
        descFrame = [[cell newsBody] frame]; 
        [[cell newsImage] setImageWithURL:[item newsImageURL] placeholderImage:[UIImage imageNamed:@"placeholderImage.png"] options:SDWebImageRetryFailed  completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType){
            if (image) {
                CGRect newsImageFrame = [[cell newsImage] frame];
                float downImageWidth = image.size.width;
                float downImageHeight = image.size.height;
                float newsImageWidth = 304.00; //imageViewSize.size.width;
                if (downImageWidth > newsImageWidth) {
                    float scaleFactor = newsImageWidth / downImageWidth;
                    newWidth = downImageWidth * scaleFactor;
                    newHeight = downImageHeight * scaleFactor;
                } else {
                    newWidth = downImageWidth;
                    newHeight = downImageHeight;
                }   
                newFrame = CGRectMake(newsImageFrame.origin.x, newsImageFrame.origin.y, newWidth, newHeight);
                [[cell newsImage] setFrame:newFrame]; //asigno el nuevo frame a la imagen . 
                float newOriginY = newFrame.origin.y + newFrame.size.height + 10.00;
                descFrame = CGRectMake(cell.newsBody.frame.origin.x,
                                       newOriginY,
                                       304.00,
                                       cell.newsBody.frame.size.height);
                blockHeight = newHeight;
            }
            NSLog(@"image %@ cached ? %u", image ,cacheType);
            if (error) {
                NSLog(@"Error: %@",error);
            }
        }];
```

**Comment by gujinku** [comment]
Have encountered similar issue.  The image cannot be shown in UITableViewCell. I tried to scroll the table view to trigger the dequeuing of UITableViewCell, but it still cannot show. 

I opened other views, the images' downloading is normal.

**Comment by Tbwas** [comment]
I encountered the same issue, how to fix it

**Comment by mythodeia** [comment]
@Tbwas which version of the library are you using? have you tried in the demo project? can you provide a sample project?

**Comment by Tbwas** [comment]
@mythodeia Sorry, I don't know the specific version. The last time update library is 6 June 2016. Is it a SDWebImage’s bug?

**Comment by mythodeia** [comment]
@Tbwas can you try with the latest version and report back or try the dataset that produces the issue with our demo project (use latest version) and report back

**Comment by Tbwas** [comment]
ok, I will try it. I found the reason. The first image downloading request is finished yet the `connectionDidFinishLoading` method doesn't execute completely, and then the second image downloading request start executing because of the UICollectionViewCell reuse mechanism，so the first request is cancelled but the image is downloaded completely and cached. However, the first request callback nil to the second cell rather than the first cell, and the second cell's operation is marked cancel state.

**Comment by Tbwas** [comment]
@mythodeia ok, I will try it. I found the reason. The first image downloading request is finished yet the connectionDidFinishLoading method doesn't execute completely, and then the second image downloading request start executing because of the UICollectionViewCell reuse mechanism，so the first request is cancelled but the image is downloaded completely and cached. However, the first request callback nil to the second cell rather than the first cell, and the second cell's operation is marked cancel state.

**Comment by mythodeia** [comment]
@Tbwas try with the latest version. i think we made some fixes regarding this.

**Comment by Tbwas** [comment]
@mythodeia ok, thanks.

**Comment by Berkat0789** [comment]
Hey is you are still having issues with this I found a way to fix it..you need to use the SD_set image call with options and set the SdWebimageOptions Accordingly. Here is what I did. I am user Firebase Also if that helps you in any way.. 

  itemImage.sd_setImage(with: URL(string: passedItem.itemImage), placeholderImage: #imageLiteral(resourceName: "Watch_Item"), options: [SDWebImageOptions.progressiveDownload, SDWebImageOptions.continueInBackground]) { (image, error, CatahType, url) in
            self.itemImage.image = image (this is obviously the image you want to set)
        }
