### ISSUE TITLE
remove cache images with url whatever the context

### ISSUE THREAD

**Issue by farfromrefug** [SDWebImage/SDWebImage#3630]
In my app i have an image i use in many different places with different transformers.
It works great and all image+transformers are cache correctly

Now in some cases i can change that "source" image, so i need to clear the cache for all those image+transformers.
I understand how the image cache key is created and so what i would like is "clear all cache images where key starts with the image URL. Right now this is not possible.
Do you think it would be possible to add?
It should be quite easy on the memory cache since i could loop overs the dictionary key and remove all those that "start with".
It is trickier with the disk cache, do you see a way to do that?

I think it would be a nice feature to add and not only for me

**Comment by dreampiggy** [comment]
NSCache does not contains "loop the key" API, actually.


It's not a hash map

**Comment by dreampiggy** [comment]
The biggest problem is that, the cache key is hashing. So even SDK itself can not get back the url from the disk filename or anything.

The relationship between transformed image and full size image, is from the caller (you)...Which only the samw URL will makes the transformer and cache logic works...

Maybe need to rethink the usage. For example, why not create a universal wrapper or use options processor, to manage and control the transformer in global ?


The context options is designed to use for individual request, but also can be central controlled...

**Comment by dreampiggy** [comment]
Like, you write a wrapper or use global control like:

```
let optionsProcessor = { url, options, context in
    if all_of_transoformed_image_for_this_url_need_to_be_cleared(url) {
        let transformedKey = SDWebImageManager.shared.cacheKey(for: url)
        // remove the related cache
        SDImageCache.shared.removeCache(for: transformedKey)
    }
    return SDWebImageOptionsResult(options, context)
}
```

**Comment by farfromrefug** [comment]
@dreampiggy sorry but i dont think i understand if i use your `optionsProcessor` then `transformedKey` does not include the context and so it will only remove the "original" image. Any transform applied to it (in context) will remain the cache wont it?
I think i missed something

**Comment by farfromrefug** [comment]
@dreampiggy yes I use it through context. I see I can get the cache key by passing the context. The issue is that I have like 100 images to remove for which at the time i dont have all the contexts.
Here is a ![screenshot](https://imgpile.com/i/GRTaDg) for context (android but same on iOS)
As you can see there is a collection view which  has around 100 items. If I Change the source image I need to update them all.
For now I clear all sdwebimage cache, no easy way around it. 
I might think about storing a map of all cached images and then use that to clear based only on url

**Comment by dreampiggy** [comment]
Seems like you need to build a manager of transformers, on the top of SDWebImage's manager...

You need to record all the URL which use transformer, and the transformer's key. You may even use the power feature called `image.sd_extendedObject`

This extended object will store into the Disk cache via Apple's xattr(https://en.wikipedia.org/wiki/Extended_file_attributes), so can be easily retrive. 

You can store the metadata like URL or transformer key to that xattr of Image Data. So, even next launching time, you load the image from disk, your transformer manager can know which transform to remove or clean, by loop though the disk data.

This even does not rely on the cache filename

**Comment by farfromrefug** [comment]
@dreampiggy awesome thanks a lot for taking the time to answer! I will dig into that

**Comment by dreampiggy** [comment]
Are you really want to use these different transformer and store their variant into cache ?

If you don't care about cache, the problem will be much more simple. You can always store one full data, and each time (when showing rendering your detail view), do Image Transform on the RAM (using the API from Apple, or ours like `UIImage+Transform.h`)

**Comment by farfromrefug** [comment]
@dreampiggy yes I can but one of my transforms (mayrix color transform ) is actually pretty expensive so yes I need the cache
