### ISSUE TITLE
[Question][API Design] Is it ok to use `sd_internalSetImageWithURL` in my project? 

### ISSUE THREAD

**Issue by Alatip** [SDWebImage/SDWebImage#3633]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | any
 SDWebImage Version      | 5.13.4
 Integration Method      | spm
 Xcode Version           | Xcode 15.0.1
 Repro rate              | all the time (100%)
 Repro with our demo prj | -
 Demo project link       | -

### Issue Description and Steps

Can I use the `UIImage+sd_internalSetImageWithURL` method in my project? The completion block's name is `SDInternalCompletionBlock`. But the API is open and visible from my project (that integrates SDWebImage via SPM). Can I assume the API will stay as is or it could be broken at any moment?

I need the `data` parameter so I can solve my problem. That's why I want to use the internalSet function.

**Comment by dreampiggy** [comment]
The API has exists for 3 years. It still treated as public API and the only break time is v6.0.0

**Comment by dreampiggy** [comment]
> I need the data parameter so I can solve my problem. That's why I want to use the internalSet function.

Maybe or may not. If you want "Do decode in the completion block", pay attention your decoding will block main queue. Because the completion block is always called at main queue.

If you want to dispatch to async, this will break UIKit's render lifecycle, because the setImage does not happended on the same Runloop.

1. Set image to placeholder1
2. Load image from memory cache
3. Decode data in async global queue (!!!!!!) -> Switch to next runloop
4. Set the decoded image 

This cause a refresh and render flashing.

**Comment by dreampiggy** [comment]
If the case I talked above is your issue. Please, use Custom Coder instead for this.

https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-coder-420

**Comment by Alatip** [comment]
We have some custom optimisations over a network layer, so I need to get `data.count` and send the value into our framework. I don't do decoding or other things.

**Comment by dreampiggy** [comment]
https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#behavior-about-asyncsync-control-for-cache

**Comment by Alatip** [comment]
> The API has exists for 3 years. It still treated as public API and the only break time is v6.0.0

Is there a timeline or schedule for v6.0.0, so we can plan ahead and estimate when to expect a possible API breakage?

**Comment by Alatip** [comment]
@dreampiggy thank you for a quick response!

**Comment by dreampiggy** [comment]
> > The API has exists for 3 years. It still treated as public API and the only break time is v6.0.0
> 
> Is there a timeline or schedule for v6.0.0, so we can plan ahead and estimate when to expect a possible API breakage?

Seems no real timeline. Because the biggest blocking PR https://github.com/SDWebImage/SDWebImage/issues/2980 no body was doing...
