### ISSUE TITLE
iOS17.0.1 go background and go foreground, SDAnimatedImageView not display the image.

### ISSUE THREAD

**Issue by longjianjiang** [SDWebImage/SDWebImage#3635]
## demo code

```
    NSString *imgName = @"test@3x";
    NSString *imgType = @"webp";
    NSString *path = [[NSBundle mainBundle] pathForResource:imgName ofType:imgType];
    NSURL *imgUrl = [NSURL fileURLWithPath:path];

    [self.imageView sd_setImageWithURL:imgUrl
                      placeholderImage:nil
                               options:SDWebImageProgressiveLoad | SDWebImageScaleDownLargeImages
                               context:@{SDWebImageContextImageForceDecodePolicy: @(SDImageForceDecodePolicyNever)}
    ];
    self.imageView.shouldCustomLoopCount = YES;
    self.imageView.animationRepeatCount = 1;
```

**Github does not allow uploading webp images**

## procedure

first webp image display normally.
![Screenshot 2023-11-13 at 5 17 52 PM](https://github.com/SDWebImage/SDWebImage/assets/15277239/b059a642-2859-4f1e-8805-f533bfed8053)

when app go background and go foreground, imageView not display the image correctly。
![Screenshot 2023-11-13 at 5 18 16 PM](https://github.com/SDWebImage/SDWebImage/assets/15277239/46f82710-1313-491d-aca3-095d4ec17d4f)

**Comment by dreampiggy** [comment]
Does this works well on iOS 16 or below ?

**Comment by dreampiggy** [comment]
> Github does not allow uploading webp images

Zip the webp and upload

**Comment by dreampiggy** [comment]
SDAnimatedImageView has a logic to `Automatic stop when view removed from window, or enter in background`, and `restart when view added into window, or enter foreground`

I think this cause issues..

**Comment by dreampiggy** [comment]
![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/b03563d5-4a1e-4089-8c95-7c4d3ba9acd1)
![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/681188f0-c852-4d19-ab6a-47f9c12e99e1)

**Comment by dreampiggy** [comment]
Is that the webp data (which needed by SDAnimatedImage to render animation) been removed when entering the background ?

**Comment by longjianjiang** [comment]
> Does this works well on iOS 16 or below ?

yes.

---

> Did you push or pop the image view to cause the sd_setImageWithURL: been re-called, durint the background/foreground changes?

no, `sd_setImageWithURL: ` at viewDidLoad.

---

[test@3x.webp.zip](https://github.com/SDWebImage/SDWebImage/files/13335258/test%403x.webp.zip)

**Comment by longjianjiang** [comment]
```
- (void)applicationDidEnterBackground:(NSNotification *)notification {
 return;
}
```
i try do nothing at enter background, but not working.

**Comment by dreampiggy** [comment]
Need a iOS 17 device and demo code to reproduce the problem.

I guess iOS 17 change UIKit render lifecycle, like that `enter in the background` will trigger a `didMoveToWindow:nil`, which is not the previous behavior.

**Comment by dreampiggy** [comment]
@longjianjiang Please zip the demo and upload for me to investigate...Currently I have no idea about this issues, maybe Apple's UIKit changes which break SDAnimatedImageView

**Comment by dreampiggy** [comment]
@longjianjiang  Zip your Xcode project and upload that to me. More easy to reproduce

**Comment by dreampiggy** [comment]
You means, using the SDWebImage's itself's demo ?

**Comment by longjianjiang** [comment]
> You means, using the SDWebImage's itself's demo ?

yes.

**Comment by dreampiggy** [comment]
Can reproduce the behavior.


Seems the `currentFrame` is correct, even when resume from background:

![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/62780887-692e-4f70-a8df-77a1b50132a3)

---

**Comment by dreampiggy** [comment]
Before entering the background (last visiable status)

```
(lldb) po [[0x103e150a0 currentFrame] CGImage];
<CGImage 0x108405760> (DP)
	<<CGColorSpace 0x600002618240> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)>
		width = 108, height = 108, bpc = 8, bpp = 32, row bytes = 448 
		kCGImageAlphaPremultipliedLast | 0 (default byte order)  | kCGImagePixelFormatPacked 
		is mask? No, has masking color? No, has soft mask? No, has matte? No, should interpolate? Yes

(lldb) po [[0x103e150a0 layer] contents];
<CGImage 0x108405760> (DP)
	<<CGColorSpace 0x600002618240> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)>
		width = 108, height = 108, bpc = 8, bpp = 32, row bytes = 448 
		kCGImageAlphaPremultipliedLast | 0 (default byte order)  | kCGImagePixelFormatPacked 
		is mask? No, has masking color? No, has soft mask? No, has matte? No, should interpolate? Yes
```

They're matched.

---

**Comment by dreampiggy** [comment]
Seems some magic things happened when UIImageView entering the background.

The underlying `CALayer.contents` been modified by someone outside of our framework (like UIKit internal)

Which replace the CGImage with another one, and cause the render failed. Because actually SDAnimatedImage relys on the CALayer.contents to display the current frame

**Comment by dreampiggy** [comment]
### Let's set a `-[CALayer setContents:]` break point to see who did this

**Comment by dreampiggy** [comment]
I have no good idea to fix this @longjianjiang 

I don't even know why UIKit assume UIImageView always need `self.image.CGImage` to re-render

A possible way it's to reset the CALayer.contents status when `become foreground`, after UIKit change this. ?

Or a stupid better solution:

`We override the UIImageView.image property totally`, which means, we provide the both `getter` of `image` and `setter` of `image`

Previouslly we only override the setter method. But seems UIKit still stupid enough to touch the getter one, we may hack to return a temp UIImage which created from `self.currentFrame.CGImage`

**Comment by dreampiggy** [comment]
Another is to override `[UIImageView traitCollectionDidChange:]`

The implementation should be easy:

```objc
- (void)traitCollectionDidChange:() {
    [super traitCollectionDidChange]; // Trigger some modify of CALayer.contents, which out-of-sync
    [self setNeedsDisplay]; // This trigger the new call to `CALayerDelegate - (void)displayLayer:(CALayer *)layer`, and refresh the `CALayer.contents` by ourselves
}
```

**Comment by dreampiggy** [comment]
@longjianjiang override the`traitCollectionDidChange` can temp solve the problem. Did you have any real demo to test whether this cause more problems ?

**Comment by dreampiggy** [comment]
Found a more interesting behavior.

When entering the background in iOS 17 and iOS 17 use Dark mode. The traitCollection actually receive `Light -> Dark` Changes

I don't know why, seems not the desired behavior. The Dark mode is always `ON`, I don't change that

![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/e284324e-d9d4-41fe-b9f4-d087c158974f)
