### ISSUE TITLE
UIImageView sd_cancelCurrentImageLoad Not working

### ISSUE THREAD

**Issue by cjwl0106** [SDWebImage/SDWebImage#3646]
![Xnip2023-11-30_15-31-08](https://github.com/SDWebImage/SDWebImage/assets/5037850/8a4fc775-ba37-4cb5-ba67-abb8e9891a26)

Have you forgotten sd_latestOperationKey

**Comment by dreampiggy** [comment]
No. This is wrong.

The `UIImageView.sd_setImage` use `nil` for operation key, which is correct.

The `UIImageView.sd_setHighlitedImage` use a custom operation key, so that category use non `nil` to cancel

**Comment by dreampiggy** [comment]
If you're misunderstanding by the API naming

We can rename `UIImageView.sd_cancelCurrentImageLoad` into

`UIImageView.sd_cancelImageLoad`

**Comment by cjwl0106** [comment]
![Xnip2023-12-01_17-03-47](https://github.com/SDWebImage/SDWebImage/assets/5037850/ffdf1d42-35a3-4f55-8621-7866514e375c)
We changed the cacheKey using the cacheKeyFilter, and when using the latest version of SDWebImage, sd_cancelCurrentImageLoad is no longer working.

**Comment by dreampiggy** [comment]
I don't think, cache key has any related information with `operation key`

They're totally different thing.

Any demo about your issue ? Provide me a re-producable demo to investigate

**Comment by DIVEINBLUE** [comment]
'sd_cancelCurrentImageLoad' call 'sd_cancelImageLoadOperationWithKey:' with nil param witch means it will do nothing. It 
does not seam to be a normal behavior.
<img width="540" alt="image" src="https://github.com/SDWebImage/SDWebImage/assets/20055520/158ce442-522f-4d97-8832-8a5db8bb6127">
<img width="769" alt="image" src="https://github.com/SDWebImage/SDWebImage/assets/20055520/4ae6103e-d027-46fc-9126-5df11fb3e977">

**Comment by dreampiggy** [comment]
This API seems get effected by the changes. I'll provide a better correct changes (Your PR looks not correct, actually, change the API naming)

**Comment by dreampiggy** [comment]
@DIVEINBLUE Please test using the branch in #3653 

To see whether that matches your wanted behavior.

And, to avoid future misunderstanding like this, I decide to remove the `sd_cancelLatestImageLoad` on UIView super class. (Only keep that `sd_cancelLatestImageLoad` on UIImageView sub class)

**Comment by dreampiggy** [comment]
> @cjwl0106 @DIVEINBLUE Please test using the branch in #3653
> 
> To see whether that matches your wanted behavior.
> 
> And, to avoid future misunderstanding like this, I decide to remove the `sd_cancelLatestImageLoad` on UIView super class. (Only keep that `sd_cancelLatestImageLoad` on UIImageView sub class)

Because, for arbitery UIView (like, for example, MyView)

I can not understand whether it's stateful or non-stateful. If `MyView` is a container, which can show two picture at the same time, then that `sd_cancelCurrentImageLoad` can not explain anything.

**Because the two image is loading at the same time, there are no `current image` in theory***.

**Comment by DIVEINBLUE** [comment]
Get it.

**Comment by dreampiggy** [comment]
In v6.0, the `sd_internalSetImage` API may change to something like this one (using Swift API):

```swift
public struct ImageLoadRequest {
   var resource: ImageResource // A protocol, URL conforms to this protocol, also, PHImageRequest conforms to this protocol
   var loadOperationKey: String? // optional, defaults to `NSStringFromClass(self.class)
   var options: ImageLoadOptions // current `options` and `context` into one enum with associated object
   var placeholderImage: UIImage
}

public func internalSetImage(with: ImageLoadRequest, setImageBlock: ()->(), progress: () ->(), completed: () -> ());
```

See more in https://github.com/SDWebImage/SDWebImage/issues/2980

**Comment by dreampiggy** [comment]
Is this issue serious for you ? I can provide a backport patch for 5.18 and 5.17. Without that deprecation

**Comment by DIVEINBLUE** [comment]
Not very serious for me.

**Comment by dreampiggy** [comment]
Decide to release both 5.18.8 patch and 5.19.0

5.18.8 does not introduce the new API and deprecation

**Comment by dreampiggy** [comment]
@DIVEINBLUE @cjwl0106   5.18.8 released with this fix.

**Comment by DIVEINBLUE** [comment]
Ok, 5.18.8 works well.
