### ISSUE TITLE
Is Privacy Manifest well recognized??

### ISSUE THREAD

**Issue by wlxo0401** [SDWebImage/SDWebImage#3652]
Xcode : 15.1
SDWebImage: 5.18.7
Using SPM

I checked that Privacy Manifest was added and checked Privacy Report in Archive, but I can't see anything corresponding to SDWebImage. Is it just me?

**Comment by dreampiggy** [comment]
SDWebImage's privacy is just that NSURLCreationDateKey, and it's not needed to get any effect on your App (now)

So, by excepted. Don't consider too much.
