### ISSUE TITLE
how to add PrivacyInfo.xcprivacy of sdwebimage?

### ISSUE THREAD

**Issue by zziazm** [SDWebImage/SDWebImage#3655]
Xcode 15.1
sdwebimage 5.18.0

I saw the  PrivacyInfo.xcprivacy file of sdwebimage  already in the repository.
I add pod 'SDWebImage' in pod file and run pod install in my project. But I didn't find the  PrivacyInfo.xcprivacy file of sdwebimage  in my project.
I have created my own PrivacyInfo.xcprivacy in my project， how can I add  PrivacyInfo.xcprivacy file of sdwebimage to my project?

**Comment by dreampiggy** [comment]
It's using resource bundle. It's CocoaPods feature.

For static ar archive, it will create `SDWebImage.bundle/PrivacyInfo.xcprivacy`
For framework, it will create `SDWebImage.framework/Resources/PrivacyInfo.xcprivacy`

**Comment by dreampiggy** [comment]
Well...If this question is a FAQ

I can add more about this on README.

For most cases, it just works, guranteeded by CocoaPods

**Comment by zziazm** [comment]
I pod sdwebimage 5.18.8 and I can see the PrivacyInfo.xcprivacy file，thanks
