### ISSUE TITLE
why iOS17 index-color PNG not support in release

### ISSUE THREAD

**Issue by Leon-OS** [SDWebImage/SDWebImage#3658]
https://github.com/SDWebImage/SDWebImage/blob/fd010e54231331fc19338f81c6d072cd9ace2825/SDWebImage/Core/SDImageIOAnimatedCoder.m#L241

SDImageIOPNGPluginBuggyNeedWorkaround only debug  effect。

**Comment by dreampiggy** [comment]
Seems bug introduced in the final PR

**Comment by dreampiggy** [comment]
Fixed in 5.18.9
