### ISSUE TITLE
SDImageIOAnimatedCoder.m:241:17: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]

### ISSUE THREAD

**Issue by dominicmarmionswrve** [SDWebImage/SDWebImage#3663]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 17
 SDWebImage Version      |  5.18.9
 Integration Method      | cocoapods
 Xcode Version           | Xcode 15
 Repro rate              | all the time if GCC_TREAT_WARNINGS_AS_ERRORS=YES
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

The following compile error occurs when `GCC_TREAT_WARNINGS_AS_ERRORS` is set to YES in podfile

```
❌  /Users/distiller/dev/myproject/Pods/SDWebImage/SDWebImage/Core/SDImageIOAnimatedCoder.m:241:17: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]

SD_LOG("Detected the current OS's ImageIO PNG Decoder is buggy on indexed color PNG. Perform workaround solution...");
```

**Comment by dreampiggy** [comment]
I don't set `GCC_TREAT_WARNINGS_AS_ERRORS` in CocoaPods or SPM or Carthage.

You override SDWebImage's build settings and cause this.

---

Maybe fixed later.
