### ISSUE TITLE
The issue of playing the same animated image link simultaneously on SDAnimatedImageView and UIImageView is as follows:

### ISSUE THREAD

**Issue by pepsikirk** [SDWebImage/SDWebImage#3667]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name         | iOS
 Platform Version      | 17.2.1
 SDWebImage Version      | 5.18.10
 Integration Method      | cocoapods
 Xcode Version           | Xcode14.3.1
 Repro rate              | 100%
 Repro with our demo prj | YES

### Issue Description and Steps

For example, when a network animated image is downloaded and decoded into SDAnimatedImage for SDAnimatedImageView, it can play normally and is cached by SDMemoryCache. Subsequently, the same URL is downloaded into a UIImageView, and it retrieves the cached image from SDMemoryCache, which is an SDAnimatedImage. However, UIImageView is unable to display the SDAnimatedImage, resulting in the final display of a static image. How can this issue be resolved?

**Comment by dreampiggy** [comment]
By designed issue.

The `SDAnimatedImage` and `_UIAnimatedImage` is not compatible.

If you use normal UIImageView to display GIF, which is indeed a bad idea. You can disable this by using the options override.

```
if context[.animatedImageClass] != SDAnimatedImgae.class {
    context.options |= .decodeFirstFrameOnly
}
```

**Comment by pepsikirk** [comment]
> By designed issue.
> 
> The `SDAnimatedImage` and `_UIAnimatedImage` is not compatible.
> 
> If you use normal UIImageView to display GIF, which is indeed a bad idea. You can disable this by using the options override.
> 
> ```
> if context[.animatedImageClass] != SDAnimatedImgae.class {
>     context.options |= .decodeFirstFrameOnly
> }
> ```

This is indeed not a good idea, but we do have such a business scenario, mainly occurring when displaying network avatars. 
I noticed that the solution you provided is to use a static image display, while my expectation is to enable UIImageView to play the animated image dynamically, rather than just displaying the first frame. 
Currently, does SDWebImage not support this scenario?

**Comment by dreampiggy** [comment]
UIImageView is from Apple's UIKit, we can not change it's behavior or hook them

`_UIAnimatedImage` is the only API to make the `UIImageView` play animation. And, it's use CoreAnimation layer animation to replace each frame.

It can not supports to dynamic replacement himself.

Read more about why we introduce `SDAnimatedImageView/SDAnimatedImage` and subclass `UIImageView/UIImage`
https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50

**Comment by dreampiggy** [comment]
I guess your question is:

> Since SDAnimatedImage here contains a frame buffer pool, when I create another `UIImage` for the same image (means, the Data), can we steal the frame from it ?

Maybe, but this cause huge complicated.

> If I really really has two image view, one is `UIImageView`, another is `SDAnimatedImage`, and want both of them showing the animation GIF, how can I do ?

Well, you can. Using the option `SDWebImageMatchImageClass`. See why I introduce that option

**Comment by dreampiggy** [comment]
Oh, seems that `SDWebImageMatchAnimatedImageClass` does not solve this case. It will only ensure:

1. Cached image is `UIImage`, but consumer is `SDAnimatedImageView`. Will assume `cache miss` and re-decoding

I guess your case seems to be:

1. Cached image is `SDAnimatedImage`, but consumer is `UIImageView`

**Comment by pepsikirk** [comment]
> Oh, seems that `SDWebImageMatchAnimatedImageClass` does not solve this case. It will only ensure:
> 
> 1. Cached image is `UIImage`, but consumer is `SDAnimatedImageView`. Will assume `cache miss` and re-decoding
> 
> I guess your case seems to be:
> 
> 1. Cached image is `SDAnimatedImage`, but consumer is `UIImageView`


I understand, but the cost of replacing all UIImageViews that could potentially display animated images with SDAnimatedImageView in our application is somewhat high. Therefore, my current solution involves hooking the cacheKeyForURL:context: method and setting the key through SDWebImageContextAnimatedImageClass for identification. However, this approach is not quite elegant, and it also results in storing three identical copies of the data on the disk. So, I am still in the process of finding a better solution.

**Comment by dreampiggy** [comment]
Need changes about how image stored and queried. A better design is to store both, with a modified key. Or using a more hackey way


A more hackey way can be like. UIImage instance use associated object to retain the SDAnimatedImage, or the reversed.

**Comment by dreampiggy** [comment]
The original design of `SDAnimatedImage` because I don't think people still preferrs to use `_UIAnimatedImage`, which has high ritaio from the design to cause OOM (which retain a `NSArray<UIImage *> *` in memory, bad thing)

**Comment by pepsikirk** [comment]
Thank you, I already know what to do.
