### ISSUE TITLE
Set UIImageView.sd_imageTransition, new image request cannot cancel the animation of the previous request

### ISSUE THREAD

**Issue by Mervin1024** [SDWebImage/SDWebImage#3674]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | iOS 10+
 SDWebImage Version      | 5.18.11
 Integration Method      | cocoapods
 Xcode Version           | Xcode 14
 Repro rate              |  all the time (100%) 
 Repro with our demo prj | yes
 Demo project link       | https://github.com/Mervin1024/SDWebImageIssueDemo

### Issue Description and Steps

Set UIImageView.sd_imageTransition, set image_1, and set the already in memory image_2 during the process of displaying transition animation after the request is completed. At this time, the image will display image_2 and then return to image_1. The reason is that the animation of the previous request cannot be canceled when setting image_2.

**Comment by dreampiggy** [comment]
By design currently.

Because `animation` can not been `per-request state`, correct ?

It's a global shared state on `UIView`, not `SDWebImage's request`

**Comment by dreampiggy** [comment]
It's about the state management issue.

For complicated use case, do not use that `sd_imageTransition`. Do transition by your own, using the API:

`setImageBlock`
`completedBlock`

instead

**Comment by dreampiggy** [comment]
Maybe I misunderstand your question ?

You're talk about issue on `Single State View`, (means, UIImageView.image only), not like `UIButton.setImageForState: highlighted, UIButton.setImageForseState: touchUpInside)

I think there are already check for animation during cancel ? What cause the problem

```
            if (!view.sd_latestOperationKey || ![originalOperationKey isEqualToString:view.sd_latestOperationKey]) {
                return;
            }
```

**Comment by Mervin1024** [comment]
> Maybe I misunderstand your question ?
> 
> You're talk about issue on `Single State View`, (means, UIImageView.image only), not like `UIButton.setImageForState: highlighted, UIButton.setImageForseState: touchUpInside)
> 
> I think there are already check for animation during cancel ? What cause the problem ?
> 
> ![image](https://private-user-images.githubusercontent.com/6919743/305843903-e37dd3a5-c90f-44eb-a4e6-19a0ba870a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjc0ODcsIm5iZiI6MTcwODMyNzE4NywicGF0aCI6Ii82OTE5NzQzLzMwNTg0MzkwMy1lMzdkZDNhNS1jOTBmLTQ0ZWItYTRlNi0xOWEwYmE4NzBhMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMDcxOTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDBhOGJmM2Q1MDQzNjJhYWRkM2ViMWFmNmI3YTM3OTU3YmU2MDBlMDE1NjhlNWE0MDM0MTRiNWU0NDI4ZjUyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H1QA2d0biiHupRjak5WtbmsRSKfNXc1uOf4-Z4z8n18)

After passing the check, set a new image after the animation starts executing. At this point, the animation did not terminate, resulting in it eventually reverting back to the previous image. I provided a very simple demo that can be replicated

**Comment by Mervin1024** [comment]
![20240219170400](https://github.com/SDWebImage/SDWebImage/assets/12757274/fb2b1cd1-24e7-4119-ac83-bfda1fd4bf26)
I tried to add `[view.layer removeAllAnimations]` here, but it didn't work. I can confirm that the animation has not yet ended when image_2 is set, and that this line of code has been executed. But in the end, UIImageView was still set to image_1 at the end of the animation time

**Comment by dreampiggy** [comment]
I don't think this is issue on SDWebImage. You're doing something complicated transition (which means, you touch `self.image` inside the animation or prepares block)

For this case, do transition by your own. It's just as simple as it.

Or you can use `SDWebImageManager` to load image and do transition. Do not use that `View Category`

> Demo

I can not find your reproduce demo.  Did you upload it ?

**Comment by Mervin1024** [comment]
> I don't think this is issue on SDWebImage. You're doing something complicated transition (which means, you touch `self.image` inside the animation or prepares block)
> 
> For this case, do transition by your own. It's just the thing you should handle for states.
> 
> Or you can use `SDWebImageManager` to load image and do transition. Do not use that `View Category`
> 
> > Demo
> 
> I can not find your reproduce demo. Did you upload it ?

Demo：https://github.com/Mervin1024/SDWebImageIssueDemo

In fact, the scenario I described is only the simplest necessary scenario, not my actual usage scenario.

I found that this bug appears in the online environment. In `UICollectionView`, the current page has no interaction and has received two `reloadData` operations (callback from different requests). Two CollectionCells exchanged between two reloads (cellA：imgA_URL, cellB：imgB_URL ---**reload**---> cellA：imgB_URL, cellB：imgA_URL). The timing of the second reload happened to be during the process of the cell displaying the downloaded images in animated form after the first reload. Then the phenomenon was that one cell ultimately displayed the wrong image.

Imagine that SDWebImageManager has already downloaded imgA and imgB internally, and cellA is displaying imgA in animated form. At this point, due to reloadData, cellA needs to display imgB. And imgB has already been downloaded, so there is no need to go through a transition and trigger the set method directly. Because the previous transition animation continued to execute, it changed back to imgA.

This should be a relatively simple and common usage scenario, with a high reproducibility rate

**Comment by dreampiggy** [comment]
Just write code to call `UIAnimation transition` by your own. As Image Loading framework (not UI Animatino framework), that API is provided just for old user who use the simplest case (using cell inside UITableView/UICollectionView, which always cancel previous request and load the new one), not about this complicated case

**Comment by dreampiggy** [comment]
我提供一个简单方案，以及一个终极解决方案，不过后者涉及到API Break，可能6.0会ship：

###简单方案：

新增参数`SDWebImageWatiTransition`，逻辑是：如果设置了transition，则会在`+[UIView transitionWithView:]`的`completion`后，才回调你的completedBlock，也就是你想要“触发下一个transition动画”的那个时机。

这样就压根不会出现你现在做的，并行两个SetImage的状态（你现在是，在transition进行中还没结束，因为completedBlock立即回掉了，所以出发了新的SetImage状态，UI状态错乱了）


###终极方案

现有的SetImageBlock是同步的，不支持“异步”，定制性比较差，会继续修改

```
typedef void(^SDSetImageBlock)(UIImage * _Nullable image, NSData * _Nullable imageData, SDImageCacheType cacheType, NSURL * _Nullable imageURL);
```

=>

```
typedef void(^SDSetImageBlock)(UIImage * _Nullable image, NSData * _Nullable imageData, SDImageCacheType cacheType, NSURL * _Nullable imageURL, (void(^BOOL)completionHandler);
```

你可以利用SetImageBlock来做复杂动画，并且当且仅当，你调用一次`completionHandler`时，我们才会回调completedBlock（即`SDInternalCompletionBlock`），整个加载动画变成了异步的，用户可掌控的

当然，这break了已有的API，因此只能在6.0提供

**Comment by dreampiggy** [comment]
![20240224-165336](https://github.com/SDWebImage/SDWebImage/assets/6919743/7c82237e-c0df-42f3-9bea-c250da6fc408)

```
- (void)setFirstImageWithFade {
//    [self.testView1 sd_cancelCurrentImageLoad];
    self.testView1.sd_imageTransition = [SDWebImageTransition fadeTransitionWithDuration:5];
    [self.testView1 sd_setImageWithURL:[[NSBundle mainBundle] URLForResource:@"image1" withExtension:@"JPG"] placeholderImage:nil options:SDWebImageWaitTransition completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
        NSLog(@"set image 1 complete: cacheType - %@", @(cacheType));
        /// 设置第二张图片，但是已经在内存所以不带动画
        [self setSecondImageWithoutFade];
    }];
}

- (void)setSecondImageWithoutFade {
    [self.testView1 sd_setImageWithURL:[[NSBundle mainBundle] URLForResource:@"image2" withExtension:@"png"] placeholderImage:nil options:SDWebImageWaitTransition completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
        NSLog(@"set image 2 complete: cacheType - %@", @(cacheType));
    }];
}
```

**Comment by Mervin1024** [comment]
> 我提供一个简单方案，以及一个终极解决方案，不过后者涉及到API Break，可能6.0会ship：
> 
> ### 简单方案
> 新增参数`SDWebImageWatiTransition`，逻辑是：如果设置了transition，则会在`+[UIView transitionWithDuration:]`的`completion`后，才回调你的completedBlock，也就是你想要“触发下一个transition动画”的那个时机。
> 
> 这样就压根不会出现你现在做的，并行两个SetImage的状态（你现在是，在transition进行中还没结束时，由于completedBlock回调了，而触发新的SetImage，提交了新的transition，UI状态错乱了）
> 
> ### 终极方案
> 现有的SetImageBlock是同步的，不支持“异步”，定制性比较差，你可能无法实现复杂的定制动画（尤其是多个状态切换）
> 
> ```
> typedef void(^SDSetImageBlock)(UIImage * _Nullable image, NSData * _Nullable imageData, SDImageCacheType cacheType, NSURL * _Nullable imageURL);
> ```
> 
> =>
> 
> ```
> typedef void(^SDSetImageBlock)(UIImage * _Nullable image, NSData * _Nullable imageData, SDImageCacheType cacheType, NSURL * _Nullable imageURL, void (^)(void)completionHandler);
> ```
> 
> 你可以利用SetImageBlock来做复杂动画，并且当且仅当，你调用一次`completionHandler`时，我们才会回调completedBlock（即`SDInternalCompletionBlock`），整个加载动画变成了异步的，用户可掌控的
> 
> 当然，这break了已有的API，因此只能在6.0提供
> 
> 还有一个其他方案，提供"可取消的transition"，这个依赖iOS 10+ API，因此只在SD 6.0考虑(届时最低部署版本会提升至iOS 12)

嗯，提供可取消的 transition 应该是一个合理的解决方案。

因为 demo 里在 completeBlock 中调用 setImage 只是为了稳定触发这个时机（transition 已开启但未结束时接收到新的 setImage），并不代表实际的使用场景，问题不是出在 completeBlock 的调用时机上。

实际出现这个问题的场景是在 UICollectionView 短时间内频繁触发 reload 的情况下，同屏同数据下同类 cell 也会自行出现交换位置加载数据的行为，每一次 cell 重新加载都会使得 cell 取消上一次请求加载新的请求。
如果第二次 reload 如果刚好落在第一次 reload 之后，cell 正在展示 transition 的期间（_如果第一次网络图片加载完成需要 100ms，transition 展示需要 250ms。那么这个时机就是 第二次 reload 位于第一次加载之后的 100ms 到 350 ms 之间_），就会出现图片先展示最终的图片后切换回第一次 reload 的图片（最终图片在第一次 reload 已经先一步下载完成，所以第二次会直接从缓存中读取）。

UICollectionView 短时间内频繁刷新是由于这个页面有很多接口一起提供数据，回调有先后，每次都会调用 reloadData 刷新全部。我能想到的最可靠的修改方式，就是每次 cell 重新加载请求时都先取消“可能存在的上一次的 transition”。

我这边暂时取消掉了对 sd_imageTransition 的使用，改用在 complete 中直接对 ImageView.layer 使用渐现 CAAnimation 的方式了。
期待 6.0 的发布🍷

**Comment by dreampiggy** [comment]
从最早设计transition就是不可取消的，UIKIT在iOS 10之前也没有接口，只有CoreAnimation层面，所以本身这个就只提供简单transition，不是和复杂场景，复杂场景你不要用任何UIKit的接口，自己用cache manager downloader这些独立工具组合，封装自己的逻辑

**Comment by mlch911** [comment]
想问一个最简单的场景。
在TableView的cell里，使用有transition动画的加载图片。
当一个cell刚刚下载完图片，在动画中，此时cell被拿去复用，加载另外一张图片，但可能出现前一张图的动画没结束，最终显示的图片还是会显示前一张图。
这种情况应该怎么解决？

**Comment by Mervin1024** [comment]
> 想问一个最简单的场景。 在TableView的cell里，使用有transition动画的加载图片。 当一个cell刚刚下载完图片，在动画中，此时cell被拿去复用，加载另外一张图片，但可能出现前一张图的动画没结束，最终显示的图片还是会显示前一张图。 这种情况应该怎么解决？
> 
> 我看[YYWebImage里的代码](https://github.com/ibireme/YYWebImage/blob/093193c67bfa2409af93e618a48e3208d63106a5/YYWebImage/Categories/UIImageView%2BYYWebImage.m#L162)，这个动画是用的CATransition，加在layer上，然后加载其它图的时候，一定会移除这个CATransition。 这样我感觉应该更好吧。不会出现前面说的问题。

我提这个 issue 的出现场景和你是相同的。
我的解决方式是不使用 `SDWebImageTransition`，封装了一层 API，在 `completeBlock` 中给 View.layer 添加 CATransition 动画。
```
- (void)sd_setImageAnimateWithURL:(NSURL *)url
                 placeholderImage:(UIImage *)placeholder
                          options:(SDWebImageOptions)options
                        completed:(SDExternalCompletionBlock)completedBlock {
    weakifyself;
    [self sd_setImageWithURL:url
            placeholderImage:placeholder
                     options:options
                    progress:nil
                   completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL){
        strongifyself;
        if (self.superview && image && !error) {
            if(cacheType == SDImageCacheTypeNone){
                CATransition *transition = [CATransition animation];
                transition.type = kCATransitionFade;
                transition.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseInEaseOut];
                transition.duration = [UIView animationDuration];
                [self.layer addAnimation:transition forKey:nil];
            }
        }
        if (completedBlock) completedBlock(image, error, cacheType, imageURL);
    }];
}

```
`[UIView transitionWithView:]` API 无法被取消，但是 `CATransition` 可以。
