### ISSUE TITLE
部分jpg图片链接无法显示的问题，channelPicUrlImgView.sd_setImage(with: URL(string: model?.channelPicUrl ?? ""), placeholderImage: UIImage(named: "placeholder.png")) 

### ISSUE THREAD

**Issue by sunjianios** [SDWebImage/SDWebImage#3675]
xcode 15.2
Kingfisher (7.9.1)

可以显示的图片：https://lechangecloud.oss-cn-hangzhou.aliyuncs.com/lechange/snappic/9F0EB79PAJ546FD_img/Alarm/44/6394760186c44509b19e25f4a729f691.jpg?Expires=1709099268&OSSAccessKeyId=LTAIP4igXeEjYBoG&Signature=h1A789p%2Bu%2FX%2BuMYjnbgAwKpylSA%3D"

无法显示的图片："channelPicUrl":"https://lechangecloud.oss-cn-hangzhou.aliyuncs.com/lechange/snappic/9F0EB79PAJ546FD_img/Alarm/51/06ea173ded834dc19a30c77eda5f76c1.jpg?Expires=1709099272&OSSAccessKeyId=LTAIP4igXeEjYBoG&Signature=6J3YtLqaFblHO0e9BbdTnhPeBNI%3D"

补充：
mac浏览器加载上述两个地址，会先后两张图片，第二张图片使用预览也无法打开，查看简介发现可能是图片缺少：尺寸、色彩空间、颜色描述文件这几个元素。

![图片](https://github.com/SDWebImage/SDWebImage/assets/6253316/0f6d3424-c063-4191-93f0-adc985dd462f)

请教各位大神代码层面有啥解决的方案吗？

**Comment by sunjianios** [comment]
The problem with some JPG image links not being displayed, channelPicUrlImgView. sd_setImage (with: URL (string: model?. channelPicUrl??), placeholderImage: UIImage (named: "placeholder. png")

Xcode 15.2

Kingfisher (7.9.1)


Images that can be displayed: https://lechangecloud.oss-cn-hangzhou.aliyuncs.com/lechange/snappic/9F0EB79PAJ546FD_img/Alarm/44/6394760186c44509b19e25f4a729f691.jpg?Expires=1709099268&OSSAccessKeyId=LTAIP4igXeEjYBoG&Signature=h1A789p%2Bu%2FX%2BuMYjnbgAwKpylSA%3D “


Image that cannot be displayed: "channelPicUrl":“ https://lechangecloud.oss-cn-hangzhou.aliyuncs.com/lechange/snappic/9F0EB79PAJ546FD_img/Alarm/51/06ea173ded834dc19a30c77eda5f76c1.jpg?Expires=1709099272&OSSAccessKeyId=LTAIP4igXeEjYBoG&Signature=6J3YtLqaFblHO0e9BbdTnhPeBNI%3D “


Supplement:

When the Mac browser loads the above two addresses, there will be two images in sequence, and the second image cannot be opened using preview. Upon reviewing the introduction, it was found that the image may be missing elements such as size, color space, and color description file. 

![图片](https://github.com/SDWebImage/SDWebImage/assets/6253316/f2943805-df7c-49ea-9a74-e3aea1c59d0a)

 May I ask if there are any solutions at the code level for the experts?

**Comment by dreampiggy** [comment]
Emm...Is this Apple's OS bug or SDWebImage issue ?

**Comment by sunjianios** [comment]
SDWebImage and Kingfisher have the same issue. 😂， https://github.com/onevcat/Kingfisher/issues/2213

**Comment by sunjianios** [comment]
[归档.zip](https://github.com/SDWebImage/SDWebImage/files/14383235/default.zip)

**Comment by sunjianios** [comment]
Both Safari and Chome cannot display this image on iPhone (06ea173ded834dc19a30c77eda5f76c1)

**Comment by dreampiggy** [comment]
So, this is that image's format issue. End

**Comment by sunjianios** [comment]
thanks

**Comment by sunjianios** [comment]
But Chrome and Firefox on the Mac can display it, but even if you save the image as, it cannot be displayed
