### ISSUE TITLE
iOS17 privacy policy

### ISSUE THREAD

**Issue by KKakadiyaKashyap** [SDWebImage/SDWebImage#3685]
Apple required App Privacy manifests until 2025. So GoogleSignIn-iOS SDK that contains an app privacy manifest must be signed.
I would like to know when you adopt this change.

**Comment by dreampiggy** [comment]
It's already bundled. Check changelog and readme again ?
https://github.com/SDWebImage/SDWebImage?tab=readme-ov-file#data-collection-practices

**Comment by parvez-keeptruckin** [comment]
@dreampiggy The upgrade for `SDWebImage` also covered `SDWebImageSwiftUI` for privacy manifest ?

**Comment by dreampiggy** [comment]
Only `SDWebImage` need privacy manifest. Other repos do not need, it does not access any disk data.
