### ISSUE TITLE
issue with `SDImageCache.sharedImageCache`

### ISSUE THREAD

**Issue by farfromrefug** [SDWebImage/SDWebImage#3687]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | macos
 Platform Version        | 17.2
 SDWebImage Version      | 5.19.0
 Integration Method      | cocoapods
 Xcode Version           | e.g. Xcode 14
 Repro rate              | e.g. all the time (100%) 

### Issue Description and Steps

I have an issue with `SDImageCache.removeImageForKeyCacheTypeCompletion` when used in conjonction with transformers
Here is my use case (i use Javascript code here, just see it as pseudo code. I use Nativescript which directly calls the native method)
* set image :
```js
if (transformers.length > 0) {
                    context.setValueForKey(SDImagePipelineTransformer.transformerWithTransformers(transformers), SDWebImageContextImageTransformer);
                }
                this.mCacheKey = SDWebImageManager.sharedManager.cacheKeyForURLContext(uri, context);
                this.nativeImageViewProtected.sd_setImageWithURLPlaceholderImageOptionsContextProgressCompleted(uri, this.placeholderImage, options, context, this.onLoadProgress, this.handleImageLoaded);
``` 
* update the source  image on disk
* remove from cache
```js
SDImageCache.sharedImageCache.removeImageForKeyCacheTypeCompletion(this.mCacheKey, SDImageCacheType.All, onCompletion);
```
* once done set the image again when the same code as above.

That process works perfectly fine when there is no transform. But when there is a transform ` SDWebImageManager.sharedManager.cacheKeyForURLContext(uri, context)` does not seem the return the correct key because it is the image without transform which is removed from cache and not the image "with" transform.
To be even clearer i see that  `SDWebImage`  caches 2 images where there is a transform: the source image and the image transformed. I would expect `SDWebImageManager.sharedManager.cacheKeyForURLContext(uri, context)` to return the key for the transformed image (which it kind of look like as i see the transform "keys" in the returned string).
But when i use that key to remove from cache i see that the "source cache image" is removed (from disk) but not the "transformed image".
Do you have any idea?
On that note in my case uri is a local file. Why is the "source image" cached again on disk while it is just a "copy" of the image pointed by uri? Seems unecessary and thus uses unecessary space.

Thanks

**Comment by dreampiggy** [comment]
The `SDImageCache` current design, only care about keys you passed. Not about the `context` param with the transformer.

Your code seems correct using `SDWebImageManager.sharedManager.cacheKeyForURLContext(uri, context)` to firstlly get the transformed key (if your `context` contains a `SDImageTransformer` associated)

Any demo ?

**Comment by dreampiggy** [comment]
Since SDWebImage is open-soruced. If you try to read the implementation, you can understand this more easily:

```objective-c
- (nullable NSString *)cacheKeyForURL:(nullable NSURL *)url context:(nullable SDWebImageContext *)context {
    if (!url) {
        return @"";
    }
    
    NSString *key;
    // Cache Key Filter
    id<SDWebImageCacheKeyFilter> cacheKeyFilter = self.cacheKeyFilter;
    if (context[SDWebImageContextCacheKeyFilter]) {
        cacheKeyFilter = context[SDWebImageContextCacheKeyFilter];
    }
    if (cacheKeyFilter) {
        key = [cacheKeyFilter cacheKeyForURL:url];
    } else {
        key = url.absoluteString;
    }
    
    // Thumbnail Key Appending
    NSValue *thumbnailSizeValue = context[SDWebImageContextImageThumbnailPixelSize];
    if (thumbnailSizeValue != nil) {
        CGSize thumbnailSize = CGSizeZero;
#if SD_MAC
        thumbnailSize = thumbnailSizeValue.sizeValue;
#else
        thumbnailSize = thumbnailSizeValue.CGSizeValue;
#endif
        BOOL preserveAspectRatio = YES;
        NSNumber *preserveAspectRatioValue = context[SDWebImageContextImagePreserveAspectRatio];
        if (preserveAspectRatioValue != nil) {
            preserveAspectRatio = preserveAspectRatioValue.boolValue;
        }
        key = SDThumbnailedKeyForKey(key, thumbnailSize, preserveAspectRatio);
    }
    
    // Transformer Key Appending
    id<SDImageTransformer> transformer = self.transformer;
    if (context[SDWebImageContextImageTransformer]) {
        transformer = context[SDWebImageContextImageTransformer];
        if ([transformer isEqual:NSNull.null]) {
            transformer = nil;
        }
    }
    if (transformer) {
        key = SDTransformedKeyForKey(key, transformer.transformerKey);
    }
    
    return key;
}
```

**Comment by farfromrefug** [comment]
@dreampiggy thanks for the detailed explanation and thank for for pointing to the related code.

I see that i get the correct cache key, the one for the transformed image. My issue is that when i use it to remove from cache it is not the transformed image which is removed but the original one.
I will try to debug this with SDWebImage source code.
i also want to look at not caching original image when it is a local image already (no point).

I also saw that transformed image using `sd_resizedImageWithSize` ends up being bigger in size that the original image. I am thinking this might be due to JPEG compression

As for an example, i am mostly working without Nativescript right now. So i have a full app https://github.com/Akylas/OSS-DocumentScanner showing this but it is not straight forward to run and debug

**Comment by dreampiggy** [comment]
> My issue is that when i use it to remove from cache it is not the transformed image which is removed but the original one.

Maybe...A history `hack` exists. You should not pass the `context` arg to `SDImageCache. removeImageForKeyCacheTypeCompletion`...Try passing a nil context ?

**Comment by dreampiggy** [comment]
> i also want to look at not caching original image when it is a local image already (no point).

If you don't want to cache the full size original image. Use context params: `SDWebImageContextOriginalStoreCacheType`. The value for this is `SDImageCacheTypeNone.rawValue`

**Comment by dreampiggy** [comment]
> I also saw that transformed image using sd_resizedImageWithSize ends up being bigger in size that the original image. I am thinking this might be due to JPEG compression

What about this ? Do you means the `compressed JPEG data size`, or the ouput transformed UIImage.size ?

**Comment by farfromrefug** [comment]
> > I also saw that transformed image using sd_resizedImageWithSize ends up being bigger in size that the original image. I am thinking this might be due to JPEG compression
> 
> Which is larger ? Do you means the `compressed JPEG data size`, or the ouput transformed UIImage.size ?
My source image is 2.3Mb in JPEG. I transform the image by scale it down to 0.8 its size. The cached image for transformed image is 4.3Mb

**Comment by dreampiggy** [comment]
> > > I also saw that transformed image using sd_resizedImageWithSize ends up being bigger in size that the original image. I am thinking this might be due to JPEG compression
> 
> Which is larger ? Do you means the `compressed JPEG data size`, or the ouput transformed UIImage.size ? My source image is 2.3Mb in JPEG. I transform the image by scale it down to 0.8 its size. The cached image for transformed image is 4.3Mb

I guess maybe the JPEG encoding compress quality issue. You can use `UIImageJPEGRepresentation` and set the lowest compression quality to see.

This is not SDWebImage's issue. Just about the compressed data size. And it's all based on Apple's JPEG encoding API (actually the ImageIO framework on iOS)

**Comment by farfromrefug** [comment]
> > > > I also saw that transformed image using sd_resizedImageWithSize ends up being bigger in size that the original image. I am thinking this might be due to JPEG compression
> > 
> > 
> > Which is larger ? Do you means the `compressed JPEG data size`, or the ouput transformed UIImage.size ? My source image is 2.3Mb in JPEG. I transform the image by scale it down to 0.8 its size. The cached image for transformed image is 4.3Mb
> 
> I guess maybe the JPEG encoding compress quality issue. You can use `UIImageJPEGRepresentation` and set the lowest compression quality to see.
> 
> This is not SDWebImage's issue. Just about the compressed data size. And it's all based on Apple's JPEG encoding API (actually the ImageIO framework on iOS)

I agree. I dont see SDWebImage using `UIImageJPEGRepresentation`  when writing JPEG cache images to disk. How does SDWebImage chooses the compress quality? I followed the code [here](https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDImageIOCoder.m#L347) but dont compress quality parameter.
The 2.3Mb image i am talking about is written using `UIImageJPEGRepresentation` with compress quality of 80

**Comment by dreampiggy** [comment]
> I tried passing nil context to SDWebImageManager.sharedManager.cacheKeyForURLContext but then if i remove from cached and try to set image again with sd_setImageWithURLPlaceholderImageOptionsContextProgressCompleted the image is not cached anymore, nor updated

Actually... I think you can do more simple. Consider your use case

If you don't want to cache the full size image at all, nor query the full size image, just pass these two context:

```
context[SDWebImageContextOriginalQueryCacheType] = @(SDImageCacheTypeNone)
context[SDWebImageContextOriginalStoreCacheType] = @(SDImageCacheTypeNone)
```

If you want to opt-in and manual to manage (include, query, store, remove) the each indivial cached image and data. You'd better use the directlly low level API like `SDWebImageDownloader + SDImageCache`, not that manager

**Comment by dreampiggy** [comment]
> How does SDWebImage chooses the compress quality

We don't know your previous `JPEG encoding compression quality`, so we don't. It will fallback to use 1.0 (the largest size)

If you want to opt-in, still, pass the context params:

```
NSDictionary *encodingOptions = @{SDImageCoderEncodingCompressionQuality : @(0.8)};
context[SDWebImageContextImageEncodingOptions] = encodingOptions;
````

SDWebImage is designed to be customizable...

**Comment by dreampiggy** [comment]
The context params are huge...

And from 5.10, we even supports to pass that `SDImageCoderOptions` (another Dictionary) into the `SDWebImageContextImageDecodeOptions` and `SDWebImageContextImageEncodeOptions`...Things become more and more complicated

**Comment by dreampiggy** [comment]
Maybe....We can introduce something like `Preset context``

Which means, a collection of pre-defined context options for different common use case.

Like your case:

### Preset: Small non-animated Images in List

```
queryCacheType = all
storeCacheType = all
originalQueryCacheType = none
originalStoreCacheType = none
encode[compressionQuality] = 0.5

```

### Preset: Large animated images in List

```
queryCacheType = all
storeCacheType = all
originalQueryCacheType = disk
originalStoreCacheType = disk
scaleLimitBytes: 1024 * 1024
decodePolicy: never
```

**Comment by farfromrefug** [comment]
> Maybe....We can introduce something like `Preset context`
> 
> Which means, a collection of pre-defined context options for different common use case.
> 
> Like your case:
> ### Preset: Small non-animated Images in List
> 
> ```
> queryCacheType = all
> storeCacheType = all
> originalQueryCacheType = none
> originalStoreCacheType = none
> encode[compressionQuality] = 0.5
> decodePolicy: automatic
> ```
> 
> ### Preset: Large animated images in List
> 
> ```
> queryCacheType = all
> storeCacheType = all
> originalQueryCacheType = disk
> originalStoreCacheType = disk
> scaleLimitBytes: 10 * 1024 * 1024
> decodePolicy: never
> ```
If you think it is good for more people yes maybe. I personally dont mind having to create my own preset.
BTW tested with :
```
originalQueryCacheType = none
originalStoreCacheType = none
encode[compressionQuality] = 0.8
```
My cache image not being updated is fixed!  Just want to mention their must be a bug still somewhere where when using the transform cache key, it is the original image which is removed.

Now about cache image size. I found the issue. Even though the cached image is named `.jpg` it is stored as a PNG image. Which is why the size is bigger. Will investigate

**Comment by dreampiggy** [comment]
> Even though the cached image is named .jpg it is stored as a PNG image.

Still, we have no context about `what encoding format you need`. Use `url file extension` is a good way to support

But currently, it just use a stupid check: If the `UIImage` has alpha channel, use PNG, else use JPEG.

```
// Check image's associated image format, may return .undefined
            SDImageFormat format = image.sd_imageFormat;
            if (format == SDImageFormatUndefined) {
                // If image is animated, use GIF (APNG may be better, but has bugs before macOS 10.14)
                if (image.sd_imageFrameCount > 1) {
                    format = SDImageFormatGIF;
                } else {
                    // If we do not have any data to detect image format, check whether it contains alpha channel to use PNG or JPEG format
                    format = [SDImageCoderHelper CGImageContainsAlpha:image.CGImage] ? SDImageFormatPNG : SDImageFormatJPEG;
                }
            }
```

**Comment by dreampiggy** [comment]
I think even your url suffix end with `.jpg`, the data is not a JPEG or is there something bug cause this ? You can set a breakpoint here to see why this `CGImageContainsAlpha:` return true for your thumbnail image

Is this the `sd_resizedImageWithImage` create a alpha channel ?

**Comment by farfromrefug** [comment]
@dreampiggy yes i saw that. But my source image is .jpg with no alpha. Why is it picking up an alpha channel...
I will investigate. Might be one of my transformers

**Comment by dreampiggy** [comment]
Guess the transformer lose that `UIImage.sd_imageFormat` information, and created a new alpha image.

**Comment by farfromrefug** [comment]
@dreampiggy yes i get that let me try a few things to pinpoint the error. I am using quite a lot of transformers

**Comment by dreampiggy** [comment]
![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/718fd0e8-8db7-4c70-a548-da0b6be021e8)


Can you add this line in SDWebImageManager.m ?

**Comment by farfromrefug** [comment]
> ![image](https://private-user-images.githubusercontent.com/6919743/315956254-718fd0e8-8db7-4c70-a548-da0b6be021e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTk4ODEsIm5iZiI6MTcxMTA5OTU4MSwicGF0aCI6Ii82OTE5NzQzLzMxNTk1NjI1NC03MThmZDBlOC04ZGI3LTRjNzAtYTU0OC1kYTBiNmJlMDIxZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMDkyNjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmFkNDczNjA5MTljYmU5MzNhNWQwMzM0Yjk5MDlmOTFjYmVmYjA0ZGIwM2NkNDcxZTM4MjQxZGM1NjEzY2Y1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BToV8URbnE2zSFPHhMZ0JYtg4TUDm7TzSnRbHGd1yuw)
> 
> Can you add this line `SDImageCopyAssociatedObject(cacheImage, transformedImage);` in SDWebImageManager.m ?
> 
> means, after the line with `transformedImage.sd_isTransformed = YES`
> 
> Means, each transformer don't need to care about the UIImage medata information. We keep this from the full size original image.

That fixed it!

**Comment by dreampiggy** [comment]
But actually...Maybe only some of metadata need to keep. Because the transformed UIImage is generated by you. Maybe not all of these information should be kept.

```
// Image Metadata
target.sd_isIncremental = source.sd_isIncremental;
target.sd_isTransformed = source.sd_isTransformed;
target.sd_decodeOptions = source.sd_decodeOptions;
target.sd_imageLoopCount = source.sd_imageLoopCount;
target.sd_imageFormat = source.sd_imageFormat;
// Force Decode
target.sd_isDecoded = source.sd_isDecoded;
// Extended Cache Data
target.sd_extendedObject = source.sd_extendedObject;
```

Anyway, I'll provide a PR for this

**Comment by farfromrefug** [comment]
@dreampiggy awesome! Thanks a lot for the great support. Really love that library!

**Comment by dreampiggy** [comment]
> My cache image not being updated is fixed! Just want to mention their must be a bug still somewhere where when using the transform cache key, it is the original image which is removed.

What about this issue ? Is SDWebImage issue or your usage issue ? Do we need something fix ?

**Comment by farfromrefug** [comment]
> > My cache image not being updated is fixed! Just want to mention their must be a bug still somewhere where when using the transform cache key, it is the original image which is removed.
> 
> What about this issue ? Is SDWebImage issue or your usage issue ? Do we need something fix ?

I would say yes we need a fix. I can investigate this. It feels like the wrong image is removed from cache (original instead of  transform) when you use the transform cache key

**Comment by dreampiggy** [comment]
I check the code in `SDImageCache.removeImageForKey`, it seems has no extra calculation.

Is this actually `remove the full cached data` ? I means, maybe another bug

Like: We `store the full image data` into `the transformed cache key`

So, if you provide the `transformed cache key`, it looks like `remove the full image data`, but it not the root case.

## Tip

A tip, you can change this line to make the cache to keep the original file name instead of MD5 hash of filename, in `SDDiskCache.m`

![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/47d6d518-5379-45dc-baab-13ac68e3967c)

**Comment by farfromrefug** [comment]
> I check the code in `SDImageCache.removeImageForKey`, it seems has no changes/calculation from your `input key params`
> 
> Is this actually `remove the full cached data` ? I means, maybe another bug internally
> 
> Like:
> 
>     1. We somehow `store the full image data` into `the transformed cache key`
> 
>     2. So, if you provide the `transformed cache key`, it looks like `remove the full image data`, but it not the root case.
> 
>     3. And the filename in iPhone sandbox use the MD5 of key, which make it hard to debug
> 
> 
> ## Tip
> 
> A tip, you can change this line to make the cache to keep the original file name instead of MD5 hash of filename, in `SDDiskCache.m`

Awesome trick will test that!

**Comment by dreampiggy** [comment]
This logic (means, directly use the full image data without network, and then do transformer) is designed by me.

It's magic in somehow, but ueseful to save bandwidth. For example, we have a full big image, and have 5 different CIfilter (a transformer which do some image process), we don't need to download 5 times, just use one original UIImage and generate 5 transformed UIImage with their data.

**Comment by farfromrefug** [comment]
> This logic (means, directly use the full image data without network, and then do transformer) is designed by me.
> 
> It's magic in somehow, but ueseful to save bandwidth. For example, we have a full big image, and have 5 different CIfilter (a transformer which do some image process), we don't need to download 5 times, just use one original UIImage and generate 5 transformed UIImage with their data.

I really like it! Now that i got my head well around it, i am golden.
Great work!
