### ISSUE TITLE
App Rejected due to ITMS-91065: Missing signature in SDWebImage

### ISSUE THREAD

**Issue by YagnikBavishi04** [SDWebImage/SDWebImage#3709]
ITMS-91065: Missing signature - Your app includes “Frameworks/SDWebImage.framework/SDWebImage”, which includes SDWebImage, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit: https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks.

We have used -  https://github.com/SDWebImage/SDWebImage/releases/tag/5.18.12 version in our code.

Can you please look into why our app is rejected due to a Missing signature in SDWebImage.

**Comment by dreampiggy** [comment]
You use CocoaPods ? I don't think this the SDK issue, seems a `Package Manager` issue

**Comment by dreampiggy** [comment]
If you sign the framework by yourself, maybe this can be solved.

**Comment by dreampiggy** [comment]
I guess this related to https://github.com/SDWebImage/SDWebImage/blob/master/Scripts/create-xcframework.sh

**Comment by YagnikBavishi04** [comment]
We are using SDWebImage SDK using Carthage with XCFramework.

**Comment by dreampiggy** [comment]
> We are using SDWebImage SDK using Carthage with XCFramework.

Seems known issue.

You can codesign yourself for the built XCFramework

###

And I'll remove the Carthage support later, we will build XCFramework myself and release on GitHub release pages.

The Carthage's pipeline design is wrong. It requires SDK client (you) to codesign, which is un-avoidable to cause the suply chain attacking.

**Comment by Jimmylxue** [comment]
codesign --timestamp -v --sign "Your Certifacate Name" "${SRCROOT}/build/SDWebImage.xcframework"

what is SRCROOT
my project no this path

<img width="326" alt="image" src="https://github.com/user-attachments/assets/1be69b75-f732-4dd0-934d-f35d95ac1ba2">

**Comment by dreampiggy** [comment]
SRCROOT is the directory contains "SDWebImage.xcodeproj"

Actually you don't need sign yourself, just download the XCFramework from the release page and use it (from recent 5.19.x version)
