### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by laxman-iroid** [SDWebImage/SDWebImage#3713]
I am getting memory issue when loading 15 to 20 images

    class func downloadAndBlurImageWith(from stringURL: String, imageView: UIImageView, placeHolderImage: String? = nil) {
        let imageUrl = URL(string: stringURL)
        // Load the image using SDWebImage
        imageView.sd_setImage(with: imageUrl, placeholderImage: UIImage(named: placeHolderImage ?? "place_holder_image.png")) { [self] (image, error, _, _) in
            guard  let image = image else {
                return
            }
            let blurredImage = image.sd_blurredImage(withRadius: 30.0) // Adjust the radius as needed
            imageView.image = blurredImage
        }
    }
    
            Utility.downloadAndBlurImageWith(from:cpa.pinimage ?? "", imageView: storeImageView, placeHolderImage: "User_profile_image")

**Comment by dreampiggy** [comment]
Don't write code like this. You will block main queue and does not use any cache


Use transformer instead: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#image-transformer-50
