### ISSUE TITLE
After upgrading to the old version, the local webp object cannot be obtained through the SDAnimatedImage method imageNamed:

### ISSUE THREAD

**Issue by duxinfeng** [SDWebImage/SDWebImage#3714]
SDWebImage upgraded from 5.10.4 to 5.19.2 (SDWebImageWebPCoder 0.8.5 -> 0.14.6), now using [SDAnimatedImage imageNamed:imageName] returns nil

The following methods will not work either
```
  NSURL *staticWebPURL = [[NSBundle mainBundle] URLForResource:@"TestColorspaceStatic" withExtension:@"webp"];
  NSData *webpData = [NSData dataWithContentsOfURL:staticWebPURL];
  SDAnimatedImage *image = [SDAnimatedImage imageWithData:webpData];
```

this is okay
    `UIImage *image = [[SDImageWebPCoder sharedCoder] decodedImageWithData:webpData options:nil];`

**Comment by dreampiggy** [comment]
You can just debug to see what happened. May because you don't register WebPCoder to coders manager.

PR and fix is welcomed

**Comment by dreampiggy** [comment]
Can not reproduce, I think this is your integration or usage issue ?

![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/ca410c81-b364-4781-9c39-6dd595e9b5f8)

Close for now, feel free to re-open if you believe this is SDK issue
