### ISSUE TITLE
Calling the base url in each request

### ISSUE THREAD

**Issue by yahyatabba** [SDWebImage/SDWebImage#3722]
Hello,

I want to ask if the library calling the base URL for each request?

for example if we have this URL:
"https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"

Dose the library call "https://www.google.com/" before the request?

Thank you

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          ios
 Platform Version       17
 SDWebImage Version     5.0.0
 Integration Method     cocoapods
 Xcode Version           | e.g. Xcode 15
 Repro rate             sometimes

**Comment by dreampiggy** [comment]
NO.

Anything about the network can check Apple's documentation about "NSURLSession"
