### ISSUE TITLE
iOS 18/macOS 15 Beta breaks the HEICS animated encoding and cause test16ThatHEICAnimatedWorks failed

### ISSUE THREAD

**Issue by Kyle-Ye** [SDWebImage/SDWebImage#3732]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | macOS
 Platform Version        | 15.0 Beta 3
 SDWebImage Version      | latest / cba8ec966758e0193f9cc3d231dd4e7ef8dfcfb8
 Integration Method      | cocoapods
 Xcode Version           | Xcode 16 Beta 3
 Repro rate              | all the time (100%)
 Repro with our demo prj | test case
 Demo project link       | https://github.com/SDWebImage/SDWebImage/blob/cba8ec966758e0193f9cc3d231dd4e7ef8dfcfb8/Tests/Tests/SDImageCoderTests.m#L237-L249

### Issue Description and Steps

@dreampiggy have encountered the issue only on CI with "(Fig) signalled err=-15474". And he suspects we should be able to reproduce it using a VM macOS.

I can reproduce this issue on a non-VM macOS locally with a similar error message.

File the issue to track the information publicly.

```
NSDictionary *properties = (__bridge_transfer NSDictionary *)CGImageSourceCopyPropertiesAtIndex(source, index, (__bridge CFDictionaryRef)@{kSDCGImageSourceSkipMetadata : @(YES)});
```

```
(Fig) signalled err=-16990
initialize:772: *** CMPhotoDecompressionContainerGetImageGeometryForIndexWithOptions  err = kCMPhotoError_InvalidParameter [-16990]
```

**Comment by Kyle-Ye** [comment]
Reverse Engineering Hacking:

## Step 1: CMPhotoDecompressionContainerGetImageGeometryForIndexWithOptions

The second error message indicated a function named "CMPhotoDecompressionContainerGetImageGeometryForIndexWithOptions".

And the symbol can be found on `/System/Library/PrivateFrameworks/CMPhoto.framework`.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/3f76b065-495c-4d6b-9cfc-df7da6ae37ab">

It will then call into `0x2294b2f4c` with the following register status.

```
(lldb) reg read x0 x1 x2 x3 x4 x5 x6
      x0 = 0x000000012b1085a0 = initial x0 = <CMPhotoDecompressionContainer 0x12b1085a0 [0x1ecb52218]>
      x1 = 0x0000000000000001 = initial x1
      x2 = 0xffffffffffffffff = -1
      x3 = 0x0000000000000000 = initial x2
      x4 = 0x000000016fdfb268 = sp+0x8 -> -1
      x5 = 0x0000000000000000
      x6 = 0x0000000000000000
```

## Step 2: The unnamed symbol 0x2294b2f4c

The logic is we do `cmp x1, [x0+0x248]`. The result is equal so we will fall into the logic of `FigSignalErrorAt` with `w0 = #0xffffbda2 = -16990`

It will then print the "Fig" error log `(Fig) signalled err=-16990`

And then call `HEIFReadPlugin::initialize` to get the second error log

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/4ae032f7-3120-43b1-a832-048909c452c4">

**Comment by Kyle-Ye** [comment]
Update:

I can reproduce "(Fig) signalled err=-15474" on iOS 18 Beta 3 on Simulator when running `test16ThatHEICAnimatedWorks `.

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/a5afa963-989f-4c7a-8e31-b44a37a98973">

**Comment by dreampiggy** [comment]
This need a Radar ID and report to Apple.

**Comment by dreampiggy** [comment]
@VaslD Is this issue been fixed in iOS 18 Beta 5?

Demo:
[HEICSEncodingDemo.zip](https://github.com/user-attachments/files/16520962/HEICSEncodingDemo.zip)


# iOS 18 Beta 5
![iOS 18 Beta5](https://github.com/user-attachments/assets/c3d9869a-8f0e-4b22-8e60-5668868146e6)

# iOS 17
![iOS 17](https://github.com/user-attachments/assets/51141889-a46d-4127-a4ce-aaa4b6316e29)
