### ISSUE TITLE
App Rejection Due to ITMS-91065: Missing Signature in SDWebImage within Custom Framework

### ISSUE THREAD

**Issue by niravparmar231** [SDWebImage/SDWebImage#3733]
I have a custom framework that includes SDWebImage, which is imported through package dependencies (version 5.19.5). I use this custom framework in one of my projects. However, when I uploaded the app to the App Store, it was rejected with the following message:

ITMS-91065: Missing Signature - Your app includes “Frameworks/CustomFramework.framework/CustomFramework”, which includes SDWebImage, an SDK identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK to get an updated version with a signature. For details about verifying the code signature for a third-party SDK, visit: Apple Documentation.

I am confused about how to sign the SDK when it is imported through package dependencies and used in a custom framework.

**Comment by dreampiggy** [comment]
Why not use the signed XCFramework which downloaded from release page ?https://github.com/SDWebImage/SDWebImage/releases

Or you can sign with your certifacte, recursively by yourself.
