### ISSUE TITLE
SDWebImage didn't added AWebPCoder by default, which cause `.webp` bundled images don't animate

### ISSUE THREAD

**Issue by xmollv** [SDWebImage/SDWebImage#3739]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |ios
 Platform Version        | 17.6.1
 SDWebImage Version      | 5.19.6
 Integration Method      | SPM
 Xcode Version           | 15.4
 Repro rate              | 100%
 Repro with our demo prj | n/a
 Demo project link       | n/a

### Issue Description and Steps

`.webp` images that are bundled with the application don't seem to automatically play. If they do come from the network (aka loading them via `SDAnimatedImageView.sd_setImage(with:placeholderImage:options:completed:)`, they do animate as expected.

Is there a way to load local files that are bundled with the app and make them play? We do have `.gif` images that are bundled with the app and those play just fine, it's just the `.webp` ones that don't play. They load, but they look as if they were a static jpg/png, they don't animate.

To load them, I'm doing the following:

```swift
let imageView = SDAnimatedImageView()
if let url = Bundle.main.url(forResource: "example", withExtension: "webp") {
  imageView.image = SDAnimatedImage(contentsOfFile: url.path)
}
addSubview(imageView)
```

If the `example.webp` was an `example.gif`, it does play. But it doesn't if it's a `.webp`.

**Comment by dreampiggy** [comment]
It should be animated.

Unless you have something configuration issue.

Check SDWebImage's own demo, we have `TestImageAnimated.webp`

**Comment by xmollv** [comment]
> It should be animated.
> 
> Unless you have some configuration issue, like:
> 
> 1. Your webp file is not animated
> 2. You don't register either `SDImageAWebPCoder` , nor `SDImageWebPCoder` (this is plugin lib, https://github.com/SDWebImage/SDWebImageWebPCoder). Read: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-coder-420
> 3. Your bundled file was modified by Xcode, when you use Assets.car but not `Copy file into ipa bundle`
> 
> Check SDWebImage's own demo, we have `TestImageAnimated.webp`


1. The file is animated (happens with any `.webp` file I try). I always end up converting them to `.gif` when I need to bundle them to sort the issue.
2. The part that I don't understand is why `.webp` files play just fine if they come from the network, but they don't if they're bundled from the app. I haven't added any extra coders, I'm using SDWebImage 'vanilla', yet the `.webp` images from the network play just fine. What am I missing?
3. It could definitely be this, I'll dig around a bit!

Thanks for the reply!

**Comment by dreampiggy** [comment]
Provided your example.

Can not reproduce on our Unit Test. So there are must be something **no code related** thing break the usage.

**Comment by dreampiggy** [comment]
`imageView.image = SDAnimatedImage(contentsOfFile: url.path)`

Seems you use the wrong API ? Why not have a try with `(data:)` API

**Comment by xmollv** [comment]
> Provided your example (including your usage Demo code, and your .webp file)
> 
> Can not reproduce on our Unit Test. So there are must be something **no code related** thing break the usage.

@dreampiggy Here's the `.webp` I was testing with (had to `.zip` it because GH doesn't support `.webp`s!:

[wrongDirection.webp.zip](https://github.com/user-attachments/files/16579075/wrongDirection.webp.zip)

Here's my class that acts as a wrapper:

```swift
open class DumpsImageView: UIView {
  
  // MARK: Properties
  private let imageView = SDAnimatedImageView()
  
  public override var contentMode: UIView.ContentMode {
    get { imageView.contentMode }
    set { imageView.contentMode = newValue }
  }
  
  // MARK: Init
  public required init(contentMode: UIImageView.ContentMode = .scaleAspectFill) {
    super.init(frame: .zero)
    translatesAutoresizingMaskIntoConstraints = false
    imageView.contentMode = contentMode
    imageView.isUserInteractionEnabled = true
    addSubview(imageView)
    imageView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
  }
  
  @available(*, unavailable)
  required public init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
  
  // MARK: Public methods
  public func load(localURL: URL) {
    self.imageView.image = SDAnimatedImage(contentsOfFile: localURL.path)
  }
}
```

And the usage:

```swift
let imageView = DumpsImageView()
if let url = Bundle.main.url(forResource: "wrongDirection", withExtension: "webp") {
  imageView.load(localURL: url)
}
addSubview(imageView)
```

**Comment by xmollv** [comment]
> My local test result: ![image](https://private-user-images.githubusercontent.com/6919743/356975929-e592c75c-2543-4f7c-b863-2b0aabc8ae21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTA4NDUsIm5iZiI6MTcyMzQ1MDU0NSwicGF0aCI6Ii82OTE5NzQzLzM1Njk3NTkyOS1lNTkyYzc1Yy0yNTQzLTRmN2MtYjg2My0yYjBhYWJjOGFlMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMDgxNTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDUzMjk4ZWRiOGI5MTFkNTUwZmRmZTFjMjdkZjBkNzM0YWY4Yjg1MTRiZjg4NTgzODQ1M2M2YmIwMTUwMDUxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aSnscjKWDKVEJGZedKqAnmJEuWcVof5OC1xbI2gaook)

Loading the data seems correct (I see the image on-screen). The issue is that it doesn't play, it loads as if it was a static image!

> `imageView.image = SDAnimatedImage(contentsOfFile: url.path)`
> 
> Seems you use the wrong API ? Can you have a try with `(data:)` API again

I'll give it a try!

**Comment by dreampiggy** [comment]
Works on our Demo as well

So I still think it's your integrating issue or configuration issue.

![image](https://github.com/user-attachments/assets/f71b5dc7-c031-47c1-a7e0-c7fcbb82b604)

**Comment by dreampiggy** [comment]
Is that the generated Swift API wrong ? The signature should be this. It should not fallback to call UIKit's parent class's API

`public init?(contentsOfFile path: String)`
![image](https://github.com/user-attachments/assets/21318348-733f-4fad-b022-53afce00c50e)

**Comment by xmollv** [comment]
> `imageView.image = SDAnimatedImage(contentsOfFile: url.path)`
> 
> Seems you use the wrong API ? Can you have a try with `(data:)` API again

I've just tried with `SDAnimatedImage(data: data)` and I've got the same results. Loading the data like this:

```swift
if let url = Bundle.main.url(forResource: "wrongDirection", withExtension: "webp"), let data = try? Data(contentsOf: url) {
  imageView.image = SDAnimatedImage(data: data)
}
```

It loads the image, but again, it doesn't play.

**Comment by dreampiggy** [comment]
Can not explain why your envrionment does not play.

Create a full Xcode project demo, not just sample code, zip the archive and send to me for debugging.

**Comment by dreampiggy** [comment]
> let imageView = DumpsImageView()

This code does not work. You don't override `init(frame:)`. But provided a API ` public required init(contentMode: UIImageView.ContentMode = .scaleAspectFill)`

Try to use this API instead ?

**Comment by dreampiggy** [comment]
@xmollv Your own issue.

Simply run the debugger and it will shows the reason.

You create a `UIImageView` but don't added it into subview layer tree. The setter `imageView.image = xxx` will result no-op

![image](https://github.com/user-attachments/assets/1463604d-efd1-4961-bfea-9bfb502c870c)

**Comment by xmollv** [comment]
> Can not explain why your environment does not play.
> 
> Create a full Xcode project demo, not just sample code, zip the archive and send to me for debugging.
> 
> There must be something special usage or configuration which cause the issue. Which your example code snippet does not show

There you go: 
[TestWEBP.zip](https://github.com/user-attachments/files/16596550/TestWEBP.zip)




> > let imageView = DumpsImageView()
> 
> This code does not work. You don't override `init(frame:)`. But provided a API ` public required init(contentMode: UIImageView.ContentMode = .scaleAspectFill)`
> 
> Try to use this API instead ?

That code does work. The `init` has a default value for the `contentMode`, which means it doesn't need to be specified at the call site.

> Even I copy your Swift code and integrate into SDWebImage's demo, it works.
> 
> Full code:
> 
> ```objc
> #import "DetailViewController.h"
> #import <SDWebImage/SDWebImage.h>
> #import "SDWebImage_iOS_Demo-Swift.h"
> 
> @interface DetailViewController ()
> 
> @property (strong, nonatomic) IBOutlet UIImageView *imageView;
> 
> @end
> 
> @implementation DetailViewController
> 
> - (void)configureView {
> //    SDAnimatedImage *image = [SDAnimatedImage imageWithContentsOfFile:fileURL.path];
> //    assert(image);
>     DumpsImageView *imageView = [[DumpsImageView alloc] initWithContentMode:UIViewContentModeScaleAspectFit];
>     [self.view addSubview:imageView];
> //    self.imageView.image = image;
> //    if (!self.imageView.sd_imageIndicator) {
> //        self.imageView.sd_imageIndicator = SDWebImageProgressIndicator.defaultIndicator;
> //    }
> //    [self.imageView sd_setImageWithURL:self.imageURL
> //                      placeholderImage:nil
> //                               options:SDWebImageProgressiveLoad | SDWebImageScaleDownLargeImages
> //                               context:@{SDWebImageContextImageForceDecodePolicy: @(SDImageForceDecodePolicyNever)}
> //    ];
> //    self.imageView.shouldCustomLoopCount = YES;
> //    self.imageView.animationRepeatCount = 0;
> }
> 
> - (void)viewDidLayoutSubviews {
>     [super viewDidLayoutSubviews];
>     DumpsImageView *imageView = self.view.subviews[1];
>     imageView.frame = self.view.bounds;
>     NSURL *fileURL = [NSBundle.mainBundle URLForResource:@"wrongDirection.webp" withExtension:nil];
>     assert(fileURL);
>     [imageView loadWithLocalURL:fileURL];
> }
> 
> - (void)viewDidLoad {
>     [super viewDidLoad];
>     [self configureView];
> }
> 
> @end
> ```

Can you try the demo I'm attaching? Maybe it's an issue with the bridge between Objective-C and Swift? I've only tried it on Swift.

**Comment by dreampiggy** [comment]
You don't register `AWebPCoder`

That's the reason

**Comment by dreampiggy** [comment]
I think this issue can become

> Why SDWebImage don't register `Animated WebP Coder` by default ?

**Comment by xmollv** [comment]
> I think this issue can become
> 
> > Why SDWebImage don't register `Animated WebP Coder` by default ?
> 
> Answer: History reason. ImageIO supports animated WebP from iOS 13, and still [buggy](https://github.com/SDWebImage/SDWebImage/issues/3558).
> 
> Actually I don't want to ship something buggy to user (even it's Apple's bug)
> 
> But if you really want, we can added this coder by default, or update the README with some explanation about **Default coders** (Default format we support)

If the default implementation from Apple is known to be buggy, IMO we should have the SDWebImage one on by default and allow people to opt out of it maybe? I'll look into adding the `AWebPCoder` on my end to see if it works (no idea where to do that, need to check the docs!).

**Comment by dreampiggy** [comment]
Seems there are some documentation hidden in wiki pages.

https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#awebp-coder

But new user didn't notice this.

> The default coders manager does not contains AWebP coder, you can add this by yourself:

**Comment by xmollv** [comment]
> Seems there are some documentation hidden in wiki pages.
> 
> https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#awebp-coder
> 
> But new user didn't notice this.
> 
> > The default coders manager does not contains AWebP coder, you can add this by yourself:
> 
> The documentation can be highlighted on README again (current it's linked in the `SDWebImageAWebPCoder`), see my screenshot.
> 
> ![image](https://private-user-images.githubusercontent.com/6919743/357337913-e2560837-3077-4092-b0da-65e269e27cae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mzg3MzksIm5iZiI6MTcyMzUzODQzOSwicGF0aCI6Ii82OTE5NzQzLzM1NzMzNzkxMy1lMjU2MDgzNy0zMDc3LTQwOTItYjBkYS02NWUyNjllMjdjYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDg0MDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2JiNGU5OTc2ZGVhOTI0Yzk1YjRhNTlhYTIzMjNmNjk0YTFmZTU2NWY3OWM4YjRmZmFlZjEwZGUwZjFhZGE3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N0QEEcGeuOdQMkB-0D-1oSJh1_ag1LuCnCv1yF7ZoRQ)

Yeah, with that it worked. I just included `SDImageCodersManager.shared.addCoder(SDImageAWebPCoder.shared)` on the sample project and the animation works as expected now! 🎉

**Comment by dreampiggy** [comment]
> IMO we should have the SDWebImage one on by default and allow people to opt out of it maybe?

Maybe. But **Changing a default value** which will effect current other SDWebImage user. If you really want, we have to release another minor version like SDWebImage 5.20.0

And also, there are another `SDImageHEICCoder` which should be added to default coder list, if you run on iOS 12+

**Comment by dreampiggy** [comment]
Sounds acceptable if we added `All Apple's built-in format coders` into default coder.

But this it's a behavior changes, I'll mark this into SDWebImage next minor.

**Comment by dreampiggy** [comment]
> .webp images that are bundled with the application don't seem to automatically play. If they do come from the network (aka loading them via SDAnimatedImageView.sd_setImage(with:placeholderImage:options:completed:), they do animate as expected.

But again, this can not explain the original issue you faced. Does your `network load logic` append the AWebP coder ? (via `SDWebImageContext`, there are a option called .imageCoder)

Or maybe you use some third party lib which wrap SDWebImage as its implementation, added the AWebP coder secretly

**Comment by dreampiggy** [comment]
I check your previous demo (without AWebPCoder reigsterd). Using `sd_setImage(with: url) with HTTP request still not animates
![image](https://github.com/user-attachments/assets/26a3f2dd-7bc4-4d90-8414-682fcc5188d7)

> If they do come from the network (aka loading them via SDAnimatedImageView.sd_setImage(with:placeholderImage:options:completed:), they do animate as expected.
So this is wrong as well. Our network loading logic seems use the same logic as file loading logic (and `:data` API is the same)

**Comment by dreampiggy** [comment]
Updated the README to make this more user-friendly for new user, see:

![image](https://github.com/user-attachments/assets/06850bfb-8544-46b6-9acf-b4f578b0529c)

**Comment by xmollv** [comment]
> I check your previous demo (without AWebPCoder reigsterd). Using `sd_setImage(with: url)` with HTTP request still not animates. Whether you use `SDAnimatedImage(data:)` API from bundle path or load from our loading system use `sd_setImage(with:)` API, it should has the same behavior.
> 
> ![image](https://private-user-images.githubusercontent.com/6919743/357346563-26a3f2dd-7bc4-4d90-8414-682fcc5188d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDgyMTIsIm5iZiI6MTcyMzU0NzkxMiwicGF0aCI6Ii82OTE5NzQzLzM1NzM0NjU2My0yNmEzZjJkZC03YmM0LTRkOTAtODQxNC02ODJmY2M1MTg4ZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMTExODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjFlMzQzNjBhNWNkY2RiZGFkZDUxZWM3NTliNDA0ZTUyMmY4YzY3NjNlZTI1YjQ2YmM3NjhiMGQ1MTc2ZDllNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nu0OCyZ24kwE4tz90MJhe7d96Bssbozq6qX4XXVxCCk)
> 
> > If they do come from the network (aka loading them via SDAnimatedImageView.sd_setImage(with:placeholderImage:options:completed:), they do animate as expected.
> 
> So this is description is also not correct. Check your App's code, search for `SDImageAWebPCoder` and `SDImageWebPCoder`. Your team's coworker may have written some logic for this.

Yeah now I'm doubting myself, maybe the `webp` images never actually worked and we didn't notice? Anyway, with the addition of the `SDImageAWebPCoder`, it all seems to work as expected now. Feel free to close this issue and thank you so much!
