### ISSUE TITLE
used SDWebImage to load the following image link, I found that some **thumbnail** JPEG image was rotated on iOS, but normal in the browser

### ISSUE THREAD

**Issue by lyon888** [SDWebImage/SDWebImage#3742]
### New Issue Checklist

* [✅ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [✅ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ✅] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        | all
 SDWebImage Version      | 5.19.2
 Integration Method      |  cocoapods 
 Xcode Version           |  Xcode 15.3 
 Repro rate              | all the time (100%)
 Repro with our demo prj | yes
 Demo project link       | 

### Issue Description and Steps

When I used SDWebImage to load the following image link, I found that the image was rotated on iOS, but normal in the browser, and not normal in safari. This makes me wonder if there is something wrong with SDWebImage's handling of Exif information. 
 
Image links: https://img4.yishouapp.com/obs/goods/img/model/2024/8/17/4663f8cda2f9ffb1255f0d7d14c9a1e6.jpg 
 
Steps: 
 
1. Use SDWebImage to load the linked image. 
2. View images on different platforms (iOS device, browser, Safari).

**Comment by dreampiggy** [comment]
Does you override the URLSession's redirect delegate method ?: https://developer.apple.com/documentation/foundation/nsurlsessiontaskdelegate/1411626-urlsession

 Why can't that redirect happens ?(If your image server return 304 status code ?)

You need debug the source code to check

**Comment by lyon888** [comment]
现在有个现象，使用SD加载下列图片，在5.9.1版本是正常显示的，5.19.1版本是旋转显示的，版本之间是否有什么变化导致这个问题产生？ 或者说我需要如何调整SD的配置才能让其正常显示
https://img4.yishouapp.com/obs/goods/img/model/2024/8/17/4663f8cda2f9ffb1255f0d7d14c9a1e6.jpg

**Comment by dreampiggy** [comment]
Is this `kCGImageSourceSkipMetadata` cause the issue ?

**Comment by dreampiggy** [comment]
See: https://github.com/SDWebImage/SDWebImage/issues/3594


从结果来看，无论设置不设置kCGImageSourceSkipMetadata，没有办法兼容所有的JFIF的图的方向正确

这是Apple ImageIO的Bug

**Comment by dreampiggy** [comment]
看起来只有使用Thumbnail Decoding会触发这个ImageIO的Bug

你用原图Decoding不会

自己开关`SDWebImageContextImageThumbnailPixelSize`测试一下

**Comment by dreampiggy** [comment]
Use 5.19.7 and retry
