### ISSUE TITLE
SDWebImageContextImageThumbnailPixelSize produce  VM: CG raster data

### ISSUE THREAD

**Issue by hutiancong** [SDWebImage/SDWebImage#3753]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name         | iOS
 SDWebImage Version   |   5.19.7
 Integration Method   |  cocoapods
 Xcode Version         | 15.3
 Repro rate            |100%
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

Use SDWebImageContextImageThumbnailPixelSize produce  VM: CG raster data 

![image](https://github.com/user-attachments/assets/4257547b-bbe2-4fd8-9c27-bf88cddcaed3)

![image](https://github.com/user-attachments/assets/6d55bd7d-8cb7-454a-8b10-1cbef8756b07)

without SDWebImageContextImageThumbnailPixelSize has no  VM: CG raster data 
![image](https://github.com/user-attachments/assets/836d875a-03f9-4a8c-a2a1-42da8ed06fa4)

![image](https://github.com/user-attachments/assets/4cbb2016-b026-424d-b11b-fd0795f52081)

when i use  SDWebImageContextImageThumbnailPixelSize,  will  produce  VM: CG raster data

**Comment by dreampiggy** [comment]
By design.

JPEG/PNG Thumbnail decoding it's driven by ImageIO's public API `CGImageSourceCreateThumbnailImageAtIndex`

Which use Core Graphics to draw a smaller one in internal implementation (because I disassemble it)

**Comment by dreampiggy** [comment]
I don't understand your question actually ? What's the wrong with this ? It's allocated by Core Graphics on their VM region

**Comment by hutiaoncong** [comment]
I discover image use SDWebImageContextImageThumbnailPixelSize,  the memory is large than full image, IOSurface +  VM: CG raster data, so image memory optimize can not use SDWebImageContextImageThumbnailPixelSize？

**Comment by hutiaoncong** [comment]
According to the data from the instrument, using SDWebImageContextImageThumbnailPixelSize consumes more memory

**Comment by dreampiggy** [comment]
Use thumbnail decoding will disable the `lazy decode`, lazy means, decode just when image rendering on the screen (via `CALayer`)

But actually, thumbnail you can choose the smaller size than the full lazy decoding. For example

1. Image Full size 2000x2000, 16MB in RAM
2. Lazy decode will occupy 16MB when the image is on the screen (if you don't use custom force decode policy)
3. Since iPhone resolution is smaller than 2000x2000, you don't need 2000x2000 and provided 1000x1000 thumbnail, so 4MB in RAM

So in general, I don't think it has issue to do more complicated control for this.

**Comment by dreampiggy** [comment]
>  the memory is large than full image, IOSurface + VM:

No, you don't consider the cross-process RAM. UIKit and Apple's team optimize for large image via lazy decoding. The image's memory usage can be optimized using the YUV420 subsample, on JPEG and HEIF.

However, thumbnail one does not have this optimization. But you actually don't **Load the same pixel resolution when comparing the full size image and thumbnail one**, correct ?

If you don't understand what I say, check out my blog: https://dreampiggy.com/2022/11/07/%E6%8E%A2%E7%A7%98%E8%B6%8A%E6%9D%A5%E8%B6%8A%E5%A4%8D%E6%9D%82%E7%9A%84ImageIO%E6%A1%86%E6%9E%B6/

**Comment by hutiancong** [comment]
> > the memory is large than full image, IOSurface + VM:
> 
> Not actually. UIKit and Apple's team optimize for large image via lazy decoding. The image's memory usage can be optimized using the YUV420 subsample, on JPEG and HEIF.
> 
> IOSurface is used to share texture (means, Image buffer) from VRAM (GPU) and RAM (CPU), it's work better on M series chips because it has universal memory architecture.
> 
> However, thumbnail one does not have this optimization. But you actually don't **Load the same pixel resolution when comparing the full size image and thumbnail one**, correct ?
> 
> If you don't understand what I say, check out my blog: https://dreampiggy.com/2022/11/07/%E6%8E%A2%E7%A7%98%E8%B6%8A%E6%9D%A5%E8%B6%8A%E5%A4%8D%E6%9D%82%E7%9A%84ImageIO%E6%A1%86%E6%9E%B6/



我看了您的博客。 文章中有一段话提到了 “如果直接使用ImageIO接口，需要注意，调用CGImageSourceCreateImageAtIndex返回的是惰性解码的占位CGImage，而CGImageSourceCreateThumbnailAtIndex返回的是解码后的CGImage（也就根源上无法利用IOSurface优化）”， 这个就是您说的惰性解码的吧，如果使用了CGImageSourceCreateThumbnailAtIndex，就无法使用惰性解码。我测试的数据是使用CGImageSourceCreateThumbnailAtIndex之后，部分页面的内存反而会变大，因为产生了VM: CG raster data，如果 不使用的CGImageSourceCreateThumbnailAtIndex优化的话，没有VM: CG raster data，
