### ISSUE TITLE
Detected the current OS's ImageIO PNG Decoder is buggy on indexed color PNG. Perform workaround solution...

### ISSUE THREAD

**Issue by xygkevin** [SDWebImage/SDWebImage#3755]
iOS18.0   iPhone15PM

Detected the current OS's ImageIO PNG Decoder is buggy on indexed color PNG. Perform workaround solution...
NSBundle file:///System/Library/PrivateFrameworks/MetalTools.framework/ principal class is nil because all fallbacks have failed
verify_image_parameters: invalid image bits/component: 8 bits/pixel 8 alpha info = kCGImageAlphaNone
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
imagePNG_error_break:384: *** ERROR: imagePNG_error_break
Warning! [0x103fa3000] Decoding incomplete with error code 18,446,744,073,709,551,615. This is expected if the image has not been fully downloaded.
[0x103fa3000] Decoding: c0 0x2620140 0x3548 0x11111100 0x0 86,642
[0x103fa3000] Options: 1x18,446,744,073,709,551,615 [ffffffff,ffffffff] 54060
Warning! [0x103fa3000] Decoding incomplete with error code 18,446,744,073,709,551,615. This is expected if the image has not been fully downloaded.
[0x103fa3000] Decoding: c0 0x2620140 0x3548 0x11111100 0x0 69,234
[0x103fa3000] Options: 1x18,446,744,073,709,551,615 [ffffffff,ffffffff] 54060

**Comment by dreampiggy** [comment]
Just ignore, it's incremental loading of PNG with EXIF will show this logging. It use os_log and don't print to user's stdoutput (for Mac command line tool)
