### ISSUE TITLE
Xcode 16/ iOS18 Compatibility check 

### ISSUE THREAD

**Issue by pavm035** [SDWebImage/SDWebImage#3758]
Hi,

This is just general query to confirm the official SDWebImage SDK version that's compatible with Xcode 16/iOS18

Current version we are using: 5.19.1

**Comment by dreampiggy** [comment]
Just use the latest version: https://github.com/SDWebImage/SDWebImage/releases/tag/5.19.7

Or, if you're really care about the minimum version, try https://github.com/SDWebImage/SDWebImage/releases/tag/5.19.5
