### ISSUE TITLE
列表加载大量的webP动图会内存特别高

### ISSUE THREAD

**Issue by YanPeixue** [SDWebImage/SDWebImage#3774]
如果直接使用全局的        SDImageCache.shared.config.shouldCacheImagesInMemory = false
会有什么影响？ 或者您有什么建议？

**Comment by dreampiggy** [comment]
Animated WebP不使用这个SDImageCache做缓存，它是每个SDAnimatedImagePlayer（持有by SDAnimatedImageView）自己有缓存

目前5.0不支持全局控制，你必须每个SDAnimatedImageView自己控制合理的maxBufferSize，虽然很不好用

**Comment by YanPeixue** [comment]
好的 感谢回复。

**Comment by dreampiggy** [comment]
maxBufferSize是每个Player自己动态计算的，但实际情况下由于是异步线程（没有stop the world），计算是有偏差的，可能会导致超出maxBufferSize限制，甚至OOM

目前这套设计不是很好，从源头来说，应该是集中管控而不是per-image-view的管控内存

临时workaround方案是你自己使用animatedImageTransformer或者thumbnailPixelSize，控制原图动图最大帧数或者最大尺寸，尽量控制内存在一个合理的区间。以及，不要用空间换时间，设置`SDWebImageContextUseLazyDecoding = YES`，这种lazy的CGImage在系统RAM不足时，会被自动回收，然后呈现白屏（需要重新渲染和解码），至少不会崩溃
