### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by romaincointepas** [SDWebImage/SDWebImage#410]
Official Google WebP doc :
https://developers.google.com/speed/webp/

And also :
http://www.ioncannon.net/programming/1483/using-webp-to-reduce-native-ios-app-size/

**Comment by arthankamal** [comment]
Add **"User Header Search Paths"** in **"SDWebImage"** target which is in **"Pods"** project. 

**$(SRCROOT)/libwebp/src** with **recursive**

![screen shot 2016-01-27 at 11 00 45 pm](https://cloud.githubusercontent.com/assets/10445166/12621808/52fba9fe-c548-11e5-80de-4cd5a28284de.png)
