### ISSUE TITLE
Application gets stuck while scrolling speedily in UITableView for the first time

### ISSUE THREAD

**Issue by bharatdodeja** [SDWebImage/SDWebImage#425]
I have list of 500-600 records in a UITableView and when I scroll speedily up and down for the first time, application gets stuck and I can not do anything. I have to kill the app. If I provide nil as URL and use placeholders instead, it works fine.

I am running the app in iPad 2 having iOS version 5.1.1. Unable to replicate the same in simulator

**Comment by ndethore** [comment]
@agiokas had the same issue a while ago ... are you using the image you downloaded from `downloadImageWithURL:options:progress:completed:`'s completed block ? If so, make sure you dispatch to the main queue before using using the image ;)

**Comment by sakshijoshi** [comment]
solution for getting stuck tableview while scrolling .If you are using image from url then use it
 [cell.imgView setImageWithURL:[NSURL URLWithString:[NSString stringWithFormat:@"%@",[dict objectForKey:@"profile_pic"]]] placeholderImage:[UIImage imageNamed:@"profile.png"]];

**Comment by sanjay-explode** [comment]
https://stackdev.space/questions/application-crashes-while-scrolling-through-the-tableview behold the answer here
