### ISSUE TITLE
Exception: +[UIImage sd_imageWithData:]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by skrul** [SDWebImage/SDWebImage#428]
I encountered this problem after upgrading to 3.3.  When trying to read a cached image off disk using something like:

UIImage *cachedImage = [[SDImageCache sharedImageCache] imageFromDiskCacheForKey:cacheKey];

This unrecognized selector exception is raised (in the [SDImageCache diskImageForKey:] frame).

This may have something to do with the fact that we use SDImageCache directly (rather than the UIImageView category methods).

Any thoughts?

**Comment by TechbirdsYogendra** [comment]
I have the Same Problem.

**Comment by mythodeia** [comment]
@TechbirdsYogendra please follow the installation documentation step by step. 
Make sure all the files are in place or use cocoapods to save some time
