### ISSUE TITLE
No libwebp in Vendors dir 

### ISSUE THREAD

**Issue by MaciejGad** [SDWebImage/SDWebImage#447]
After downloading repository in zip, I tried to compile examples, and I've got this error:

```
clang: error: no such file or directory: '/Users/bazyl/Desktop/SDWebImage-master/Vendors/libwebp/src/dec/webp.c'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

beacuse there isn't libwebp in Vendors dir. It will be nice to have working examples out of the box after download zip, but also it can be mention in README.md in section Installation to manually download libwebp and place in Vendors dictionary

**Comment by sekmo** [comment]
git clone --recursive https://github.com/rs/SDWebImage.git

**Comment by bpoplauschi** [comment]
Great @sekmo

**Comment by pathfinder1989** [comment]
@bpoplauschi  when pod install  error:

Installing libwebp (0.5.0)

[!] Error installing libwebp
[!] /usr/bin/git clone https://chromium.googlesource.com/webm/libwebp /var/folders/0c/rt1dny3d64qfrncb1yq22_rc0000gn/T/d20161103-3177-11xvrzp --template= --single-branch --depth 1 --branch v0.5.0

Cloning into '/var/folders/0c/rt1dny3d64qfrncb1yq22_rc0000gn/T/d20161103-3177-11xvrzp'...
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

**Comment by buvtopcc** [comment]
cd SDWebImage/SDWebImage Dir and run 'git submodule update --init --recursive', It's correctly clone  libwebp and worked for me.
