### ISSUE TITLE
SDWebImageDownloader: <__NSArrayM: 0x208a6e90> was mutated while being enumerated.

### ISSUE THREAD

**Issue by getaaron** [SDWebImage/SDWebImage#470]
Using SDWebImage 3.3 via CocoaPods, the app sometimes crashes with the error `<__NSArrayM: 0x208a6e90> was mutated while being enumerated.`.

Line 248 in SDWebImageDownloaderOperation calls         `self.progressBlock(self.imageData.length, self.expectedSize);`.  This calls SDWebImageDownloader.m, which crashes on [line 129](https://github.com/rs/SDWebImage/blob/3.3/SDWebImage/SDWebImageDownloader.m#L129).

It also happens occasionally on [line 144](https://github.com/rs/SDWebImage/blob/3.3/SDWebImage/SDWebImageDownloader.m#L144), called by line 292 in SDWebImageDownloaderOperation.

**Comment by MaximillionMai** [comment]
This bug still repros.  We should call "copy" inside the "dispatch_sync" block.  I will send a PR.

**Comment by MaximillionMai** [comment]
actually, this is already fixed in 3.7.2 in the inlined code instead of callbacksForURL: function.
