### ISSUE TITLE
- (void)setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options progress:(SDWebImageDownloaderProgressBlock)progressBlock completed:(SDWebImageCompletedBlock)completedBlock

### ISSUE THREAD

**Issue by ghost** [SDWebImage/SDWebImage#489]
When I load a non-image URL, the program will crash, the site is a fake picture address.

crash here!
for (NSDictionary *callbacks in callbacksForURL)
{
SDWebImageDownloaderProgressBlock callback = callbacks[kProgressCallbackKey];
if (callback) callback(receivedSize, expectedSize);
}

**Comment by Oneginpanda** [comment]
I‘ve got the same crash here.
