### ISSUE TITLE
Crash -[NSConcreteMutableData initWithCapacity:]: absurd capacity: 2148905797, maximum size: 2147483648 bytes'

### ISSUE THREAD

**Issue by cherpake** [SDWebImage/SDWebImage#503]
Hi,
I'm using your framework, and some of my users experience this crash,
when capacity changes but it's always more than 2GB.

Application Specific Information:
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSConcreteMutableData initWithCapacity:]: absurd capacity: 2148905797, maximum size: 2147483648 bytes'

Last Exception Backtrace:
0   CoreFoundation                      0x316ba3e7 **exceptionPreprocess + 163
1   libobjc.A.dylib                     0x393b5963 _objc_exception_throw + 31
2   CoreFoundation                      0x316ba307 +[NSException raise:format:] + 107
3   Foundation                          0x31f35f35 -[NSConcreteMutableData initWithCapacity:] + 109
4   App                             0x001d6989 -[SDWebImageDownloaderOperation connection:didReceiveResponse:] + 269
5   Foundation                          0x31ff6915 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke_0 + 17
6   Foundation                          0x31f36769 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 201
7   Foundation                          0x31f36685 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 61
8   Foundation                          0x31f3874b _NSURLConnectionDidReceiveResponse + 83
9   CFNetwork                           0x31397d2d ___delegate_didReceiveResponse_block_invoke_0 + 45
10  CFNetwork                           0x31396d33 ___withDelegateAsync_block_invoke_0 + 55
11  CFNetwork                           0x313bf013 ___performAsync_block_invoke_068 + 19
12  CoreFoundation                      0x31600acd _CFArrayApplyFunction + 177
13  CFNetwork                           0x313bf473 RunloopBlockContext::perform() + 75
14  CFNetwork                           0x31323461 MultiplexerSource::perform() + 189
15  CoreFoundation                      0x3168f8f7 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 15
16  CoreFoundation                      0x3168f15d __CFRunLoopDoSources0 + 213
17  CoreFoundation                      0x3168df2f __CFRunLoopRun + 647
18  CoreFoundation                      0x3160123d _CFRunLoopRunSpecific + 357
19  CoreFoundation                      0x3165fc4b _CFRunLoopRun + 99
20  App                             0x001d64c7 -[SDWebImageDownloaderOperation start] + 439
21  Foundation                          0x31fc0fe7 __block_global_6 + 103
22  libdispatch.dylib                   0x397cf793 _dispatch_call_block_and_release + 11
23  libdispatch.dylib                   0x397d3657 _dispatch_root_queue_drain + 279
24  libdispatch.dylib                   0x397d37d9 _dispatch_worker_thread2 + 93
25  libsystem_c.dylib                   0x397f77f1 _pthread_wqthread + 361
26  libsystem_c.dylib                   0x397f7684 _start_wqthread + 8

**Comment by yupliang** [comment]
@cherpake hi , I meet the same crash issue , how could you solve the problem , please help me .

**Comment by cherpake** [comment]
Wow this was long time ago... I think that by mistake I was trying to load a movie instead of image, or something like this. If I remember correctly adding additional check before loading images helped (size wise).

**Comment by yupliang** [comment]
thank you guys.
