### ISSUE TITLE
How can I add a fade in effect?

### ISSUE THREAD

**Issue by Ricardo1980** [SDWebImage/SDWebImage#533]
Hello!
How can I add a fade in effect when the image is retrieved?
BTW, the sample project does not work, it seems 
# import "webp/decode.h"

is missing in 
UIImage+WebP.h
and vender/libwebp folder is empty.
I donwloaded the project as a ZIP file right now.
Thanks.

**Comment by Nagarjun123** [comment]
It worked thanks @asuralyc

**Comment by Nagarjun123** [comment]
How to change white fadein background for this? Currently fadein is white i want it black or grey?
