### ISSUE TITLE
The issue  "'webp/decode.h' file not found" is still exist

### ISSUE THREAD

**Issue by MeganZhou** [SDWebImage/SDWebImage#544]
I not sure whether I forked the wrong version (But I think the master brach is the correct one, am  I?) or the issues is still exist. or it is just exist in SDWebImageDemo project.

Very appreciate to your help, thank you very much.

I found libwebp folder in my vender folder is empty, Is there a possible that I need download libwebp by myself?

**Comment by shiyingyan** [comment]
step: 
1、 cd into your SDWebImage directory.
2、git submodule init.
3、git submodule update.
