### ISSUE TITLE
-[UIImageView setImageWithURL:placeholderImage:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by obaidjawad** [SDWebImage/SDWebImage#622]
This issue still exits, even after adding the flag -Objc

However it is very strange in one of my project it works smooth but at the same time I have added this to my another project and it crash with the log
-[UIImageView setImageWithURL:placeholderImage:]: unrecognized selector sent to instance

I don't know whats going on.

**Comment by SamKun28** [comment]
I was having the same problem, I solved it by adding libSDWebImage+WebP.a in Build Phases Link Binary With Libraries,me too
