### ISSUE TITLE
[UIImageView setImageWithURL:placeholderImage:]: unrecognized selector sent to instance 0x962daf0

### ISSUE THREAD

**Issue by yinyinliushang** [SDWebImage/SDWebImage#636]
My code:
-(UITableViewCell _)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    id coursewareRow=[courseArray objectAtIndex:indexPath.row+everyPageCount_([self.pageBtnItem.title integerValue]-1)];
    CoursewareCell *coursewareCell=[tableView dequeueReusableCellWithIdentifier:@"PlayCoursewareCell"];
    if(!coursewareCell)
        coursewareCell=[[CoursewareCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"PlayCoursewareCell"];
[coursewareCell.imageView setImageWithURL:[NSURL URLWithString:@"http://www.floraphotographs.com/showrandomios.php?color=blue&session=1"]
                   placeholderImage:[UIImage imageNamed:@"home.png"]];
return coursewareCell;
}
The error is:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIImageView setImageWithURL:placeholderImage:]: unrecognized selector sent to instance 0x962daf0'

**Comment by alirezaLG** [comment]
That damn issue just killed whole my time !!
But finally it solved, just follwo this instruction:
https://github.com/Alamofire/Alamofire#embedded-framework
