### ISSUE TITLE
Broken image 

### ISSUE THREAD

**Issue by phamquy** [SDWebImage/SDWebImage#654]
I set image for my UIImageView using following code

``` Objective-C
[self.thumbnailImageView
     setImageWithURL:imageThumbnailURL
     placeholderImage:[UIImage imageNamed:iMPlaceHolderImage]
     options:SDWebImageRetryFailed
     completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType) {
        dispatch_async(dispatch_get_main_queue(), ^{
            [wself.thumbnailImage setContentMode:(UIViewContentModeScaleAspectFit)];
        });
     }];
```

Sometime i got broken image like this:
http://stackoverflow.com/questions/21978006/incomplete-image-with-sdwebimage

**Comment by amarcadet** [comment]
Hi, 

I'm facing the same issue with version `3.7.1`. It's really hard to reproduce so I'm not able to give you a sample code :disappointed: .

It's clearly related to the quality of the network as it appears more often on Edge or Low Latency network.

Thanks for your help
