### ISSUE TITLE
Why _downloadQueue.maxConcurrentOperationCount = 2?

### ISSUE THREAD

**Issue by operatordevelopment** [SDWebImage/SDWebImage#680]
Wondering if you can give some background on why you chose to set _downloadQueue.maxConcurrentOperationCount = 2?
From my limited experience with NSOperationQueue, I would have expected you to leave it set to the default, NSOperationQueueDefaultMaxConcurrentOperationCount, since the NSOperationQueue class documentation says it adjusts based on system conditions.
But I know you've got a lot of experience with this sort of thing and SDWebImage is a rather mature product.  So this is not a challenge but a request for more information.  :-)
Thanks!
Del

**Comment by mmjuns** [comment]
Hi, I am not sure if my SDWebImage is not the latest version or not. However, I met a strange case. The default value of _downloadQueue.maxConcurrentOperationCount is 2 in my app. I found that I can only get two images downloaded and displayed in my tableview even I have more than 2 cells in the current view and call the download function more than 2 times. Also, even I refresh the view, still only 2 images shown. I have to kill the app and re run it. Then I will get 2 more images downloaded and displayed. Basically, I believe this means the downloader only download 2 images each time. But based on the app doc, _downloadQueue.maxConcurrentOperationCount should only define the max concurrentoperation number, not the queue size. Is this a bug in the previous version of the SDWebImage???

**Comment by mythodeia** [comment]
@mmjuns not its not a but. the number show the max concurrent operations at any given time. check the sample code. it words just fine. i think there is an issue with your project.
