### ISSUE TITLE
should not add url to failedURLs when timeout, cancel and so on.

### ISSUE THREAD

**Issue by Whirlwind** [SDWebImage/SDWebImage#707]
I found I often fail to show image because of some season, but it will not display forever.

I debug it, and I found I got a `NSURLErrorTimedOut`, and there is a code like this:

```
                    if (error.code != NSURLErrorNotConnectedToInternet)
                    {
                        @synchronized(self.failedURLs)
                        {
                            [self.failedURLs addObject:url];
                        }
                    }
```

I think I should not add the url to failedURLs if I got a timeout. I think I can retry download to be OK, because the url is ok, and the network is bad. 

I think that `NSURLErrorCancelled`, `NSURLErrorTimedOut`, `NSURLErrorNotConnectedToInternet` should be retry.

**Comment by erango** [comment]
On iOS > 6, the error codes that don't make it to shouldBeFailedURLAlliOSVersion can still make it to shouldBeFailedURLiOS7 and ruin things still, since the code checks either of them to be YES.

**Comment by bpoplauschi** [comment]
@erango check #1297, it should fix the issue you are describing. Please note this is only merged into master and not yet included in any release.

**Comment by erango** [comment]
@bpoplauschi thanks!
