### ISSUE TITLE
Set custom header for every HttpRequest

### ISSUE THREAD

**Issue by yorkwang** [SDWebImage/SDWebImage#729]
As I know, SDWebImage's http header can be modified as below:

SDWebImageDownloader *manager = [SDWebImageManager sharedManager].imageDownloader;
    if (coverRefer.length > 0) {
        [manager setValue:coverRefer forHTTPHeaderField:@"Referer"];
    }

In my application, I have a tableView with 3 different http referers. How can I custom header for every HttpRequest?

**Comment by lehelmedves** [comment]
Hello,

Actually, this does not solve the problem of not being able with the above code, to set a different header for each call. How should this be handled?

**Comment by dreampiggy** [comment]
@lehelmedves See the #2020. The comments here show the solution.

For 4.x, you can only use `headersFilter` property in `SDWebImageDownloader`. You can use a switch case to decide which url should be appending the addtional headers.

For 5.x, you should use `requestModifier`. It has one context option named `SDWebImageContextDownloadRequestModifier` to allow you to specify request modifier for each of image request. So you can directlly set the header during `sd_setImageWithURL:`

**Comment by lehelmedves** [comment]
@dreampiggy thank you so much for your help!
