### ISSUE TITLE
iOS 8 - failing to build app

### ISSUE THREAD

**Issue by voronianski** [SDWebImage/SDWebImage#736]
On build with XCode 6 I have such errors in `SDWebImageDownloaderOperation.m` -
`Use of undeclared identifier '_executing'`, `Use of undeclared identifier '_finished'`

```
46        _cancelBlock = [cancelBlock copy];
47        _executing = NO;
48        _finished = NO;
```

**Comment by avaiyakirtib** [comment]
@synthesize executing = _executing;
@synthesize finished = _finished;

solved my problem , camel case is not working still after renaming
