### ISSUE TITLE
How can I download and cache image without assigning it to imageView?

### ISSUE THREAD

**Issue by bizibizi** [SDWebImage/SDWebImage#749]
I will assign it to imageView later with URL

**Comment by sndive** [comment]
is SDWebImageManager.downloadWithURL thread safe or I'm supposed to call that off the main thread only?

**Comment by dreampiggy** [comment]
@sndive  Thread-Safe and can be called from global queue.

**Comment by sndive** [comment]
perfect, even less work for me than given that the resulting uiimage is typically fed into uikit and like
