### ISSUE TITLE
unable to run example project of sdwebimage

### ISSUE THREAD

**Issue by shujataliz** [SDWebImage/SDWebImage#756]
i am getting build failed due to this error.

clang: error: no such file or directory: '/Users/msarimsiddiqui/Downloads/SDWebImage-master/Vendors/libwebp/src/utils/random.c'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

i had download zip from github and libwebp folder is empty i assumed that supporting files fir this sdk is missing please reply fast
![screen shot 2014-06-13 at 12 58 39 pm](https://cloud.githubusercontent.com/assets/2575406/3267670/9ce1f056-f2d0-11e3-814a-f0517163f626.png)

**Comment by qingmarch** [comment]
I have tried `git clone --recursive https://github.com/rs/SDWebImage.git` for several times, but still not work
