### ISSUE TITLE
Delegate method not called

### ISSUE THREAD

**Issue by ivanvassilev** [SDWebImage/SDWebImage#762]
Delegate method is not called in collectionview controller.
- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:   (UIImage *)image withURL:(NSURL *)imageURL

SDWebImageManagerDelegate is set in header
"[SDWebImageManager sharedManager].delegate = self" is set in viewDidLoad

software used:
- SDWebImage-3.6.framework 
- Xcode 5.1.1

**Comment by Davomere** [comment]
@ivanvassilev Hey! I have the same issue, can you share with me how you resolved this issue? Thanks
