### ISSUE TITLE
Image not loaded on first call (eg. first table view cell).

### ISSUE THREAD

**Issue by heresamit** [SDWebImage/SDWebImage#802]
I am using version 3.6 through cocoapods.

I make this call inside cellForRowAtIndexPath

`[cell.coverImage setImageWithURL:[NSURL URLWithString:[AppDelegate.properties[indexPath.row] pictureURLs][0]]];`

The URL for all indexPaths is the same.

The image doesn't load in the first cell until I scroll down till it is off the screen and then scroll back to it i.e. till cellForRowAtIndexPath is not called with the path 0 - 0 again.

If I use a completion block here, that block is also not called.

I am using a similar call elsewhere (with a scrollview) and there too, the image doesn't get loaded first, when I visit it again (and the setImageWithURL method is called again), it appears correctly.

**Comment by sara-shokry** [comment]
i also have same issue
