### ISSUE TITLE
crash use sd_setImageWithURL

### ISSUE THREAD

**Issue by onceMu** [SDWebImage/SDWebImage#862]
when i use sd_setImageWithURL load image  crashed,
while use deprecated method setImageWithURL it's ok.
the code is 
[imageView sd_setImageWithURL:[imageItem getDefaultImageURL]
                     placeholderImage:nil
                              options:SDWebImageProgressiveDownload
                            completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                                if (image) {
                                    imageView.image = image;
                                }
                            }];

the error is     sd_setImageWithURL:placeholderImage:options:completed:]: unrecognized selector sent to instance 0x166f9de0

while i use setImageWithURL it's ok

**Comment by pclion** [comment]
I also have this problem,how to reslove it?

**Comment by mythodeia** [comment]
@pclion please see the installation documentation for this library. Use cocoapods to make your life easier

**Comment by sebyddd** [comment]
In my case, I managed to solve this by removing and adding back Foundation.framework and ImageIO.framework from the Pods target. Everything working good now.

**Comment by satheeshiOS** [comment]
I have solved this problem by adding the library files into the Build phase in the tag "Link Binary With Libraries" after adding the library using cocoapods. :+1:

**Comment by yeison** [comment]
I solved the problem by adding $(inherited) to the 'Other Linker Flags' field

**Comment by mythodeia** [comment]
discussed [here](https://github.com/rs/SDWebImage/issues/1080) as well
:+1:

**Comment by red010182** [comment]
I was installed by CocoaPod and had the problem too!  Solve this by adding ImageIO.framework & SDWebImage.framework in project setting.

**Comment by alirezaLG** [comment]
That damn issue just killed whole my time !!
But finally it solved, just follwo this instruction:
https://github.com/Alamofire/Alamofire#embedded-framework

**Comment by lpeancovschi** [comment]
I just integrated 3rd party libraries via cocoapods and got this nasty error. Fixed it by _adding -framework_ to _Other Linker Flags_

**Comment by toka756** [comment]
In my case,   I have to add "SDWebImage.framework" to ["Build Phrases" → "Link Binary With Libraries"] after cocoa pod installation.
