### ISSUE TITLE
Assign different SDImageCache to SDWebImageManager?

### ISSUE THREAD

**Issue by ghost** [SDWebImage/SDWebImage#877]
I wish I could create multiple instances of SDWebImageManager and assign different cache to each, but this is not possible at the moment because the imageCache property in SDWebImageManager is readonly. Is there any reason for this property to be readonly? Can we make it writable, so that client code has the flexibility to inject another cache?

**Comment by onmyway133** [comment]
@bpoplauschi sometimes we have requirements to have different caches in a project. So having ability to change imageCache of SDWebImageManager is on demand. Since SDWebImage is abusing Singleton all over its code base, I don't know override property accessor will do any harm :|

**Comment by bpoplauschi** [comment]
Feel free to work on a solution to this on your fork. If it works for us, we will include it by a PR.

**Comment by onmyway133** [comment]
@bpoplauschi I have different `SDWebImageManager` with different `SDImageCache`, and it works for me so far. Thanks

**Comment by bpoplauschi** [comment]
Great
