### ISSUE TITLE
-[__NSArrayM getBytes:length:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by hamin** [SDWebImage/SDWebImage#882]
Just got that crash on [SDWebImage startOperation]. Assuming its here https://github.com/rs/SDWebImage/blob/c8df858f7516f5a43b917e6344c8fc4b5bf5300c/SDWebImage/NSData%2BImageContentType.m#L13

The exception makes sense, not sure why an NSArray is being passed instead of NSData?

**Comment by codefei** [comment]
@bpoplauschi I got crashed too, my version of SDWebImage is 3.7.5.
-[__NSMallocBlock__ getBytes:length:]: unrecognized selector sent to instance 0x157eced0

It seems that the parameter type of data may be not `NSData` type, here is call stack:
`[NSData(ImageContentType) sd_contentTypeForImageData:]
[UIImage(MultiFormat) sd_imageWithData:]
 [SDWebImageDownloaderOperation connectionDidFinishLoading:]`
