### ISSUE TITLE
[UIImageView sd_setImageWithURL:placeholderImage:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by eliomartinezb** [SDWebImage/SDWebImage#885]
I'm using SDWebImage for about 2 years now, with the newer version that I made the .framework file myself (maybe that's whats wrong). 
I get this error while running
[UIImageView sd_setImageWithURL:placeholderImage:]: unrecognized selector sent to instance.

But when i use [UIImageView setImageWithURL:placeholderImage:] works perfectly, only with a warning telling me its deprecated but still works.

**Comment by Senkada** [comment]
I have even tried all the methods. But still having the same issue... Can you please tell me the solution

**Comment by irineul** [comment]
I'm having the same problem too, tried all methods and still getting the error.

**Comment by Senkada** [comment]
@irineul I have added all the files of SDWebImage folder into project. Its working now. Try this method.

**Comment by driventokill** [comment]
I had the problem and found it's because I set the `OTHER_LDFLAGS`(aka `Other Linker Flags` in build settings) before using cocoapods. So after switched to latest cocoapods which already support swift, you should change the `OTHER_LDFLAGS` to `$(inherited)`.

**Comment by anabusy** [comment]
hello ,
I am using sdwebimage for more than 1.5 years for all my applications.. 
now I have upload new update and apple is requiring arm64 support .. 
i have installed the last sdwebimage 3.7.1 by cocoapods but the application is crashing all the time...
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIImageView sd_setImageWithURL:placeholderImage:]: unrecognized selector sent to instance 0x7fa8c3018240'


is the last version is working?

please help ,I have to know what to do with?

**Comment by anabusy** [comment]
thanks i found the problem ... it was build active architecture only. to yes .


:) 
thanks

**Comment by rsardek** [comment]
As pointed here above, attaching libSDWebImage.a did the trick. Thanks.

**Comment by orikidoz** [comment]
Hi 
I'm having the same issue.
Tried all above fixes nothing works.

![screen shot 2016-02-28 at 11 33 14 am](https://cloud.githubusercontent.com/assets/15074268/13378427/361bce10-de0f-11e5-866b-8d93912db5f5.png)

Thanks,
Ori

**Comment by bhavik-iottive** [comment]
you need to add a libSDWebimage.a framework in linked framework and libraries section.
its worked for me.

**Comment by hntoosi** [comment]
> I had the problem and found it's because I set the `OTHER_LDFLAGS`(aka `Other Linker Flags` in build settings) before using cocoapods. So after switched to latest cocoapods which already support swift, you should change the `OTHER_LDFLAGS` to `$(inherited)`.

this is solved my problem. thanks
