### ISSUE TITLE
Duplicate symbol

### ISSUE THREAD

**Issue by fredbjor** [SDWebImage/SDWebImage#89]
i followed the description of adding the lib to my project, but i get the following error when i try to build it:

ld: duplicate symbol _SDWebImageDownloadStartNotification in /Users/fredrik/Library/Developer/Xcode/DerivedData/OETC12-fpgsfoeiadrbqdgtfjxwfwmlfczb/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDWebImageDownloader.o) and /Users/fredrik/Library/Developer/Xcode/DerivedData/OETC12-fpgsfoeiadrbqdgtfjxwfwmlfczb/Build/Intermediates/OETC12.build/Debug-iphonesimulator/OETC12.build/Objects-normal/i386/SDWebImageDownloader.o for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

any suggestions?

**Comment by ashishmankar** [comment]
If you are not adding MapKit framework delete following files from the SDWebImage

MKAnnotationView+WebCache.h
MKAnnotationView+WebCache.m
