### ISSUE TITLE
Problem while compile using objective c++ complier

### ISSUE THREAD

**Issue by ThangavelMca** [SDWebImage/SDWebImage#909]
My app have many c++ files. So i want to change my complier sources as Objective C++. 

My C++ code compile fine. But SDWebImage code not compile. Showing error. How to fix this issue. 

Please help to fix this issue.

**Comment by CheneyZJ** [comment]
Hi,@bpoplauschi,now i am facing the same problem and I imported  <CoreFoundation/CFNumber.h> as you said, but it seems not work for me.Here is the error:
![47f4ba83-be70-4a4e-b4ff-8b8fe6941248](https://cloud.githubusercontent.com/assets/5838170/7830495/61800d00-0480-11e5-94ab-ed979153e026.png)
in the method of - (void)connection:(NSURLConnection *)connection didReceiveData:(NSData *)data .
Please help fix this issue.thanks very much.
