### ISSUE TITLE
Crash When call [SDWebImageCombinedOperation cancel] after fix #809

### ISSUE THREAD

**Issue by zhongchao-han** [SDWebImage/SDWebImage#948]
It not alway crash,please look crash log below.

Exception Type:  EXC_BAD_ACCESS (SIGABRT)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00000000
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                  0x2b544e3a **exceptionPreprocess + 122
1   libobjc.A.dylib                 0x38bf2c86 objc_exception_throw + 34
2   CoreFoundation                  0x2b544d80 +[NSException raise:format:] + 108
3   QWeiboSDK4iOSDemo               0x00606b44 UmengSignalHandler + 132
4   libsystem_platform.dylib        0x392b286e _sigtramp + 30
5   libobjc.A.dylib                 0x38bf5d2c realizeClass(objc_class_) + 216
6   libobjc.A.dylib                 0x38bf5d2c realizeClass(objc_class_) + 216
7   libobjc.A.dylib                 0x38bf8ff8 lookUpImpOrForward + 152
8   libobjc.A.dylib                 0x38bf8f52 _class_lookupMethodAndLoadCache3 + 30
9   libobjc.A.dylib                 0x38bff1d4 _objc_msgSend_uncached + 20
10  QWeiboSDK4iOSDemo               0x0002d51e -[SDWebImageDownloaderOperation .cxx_destruct](SDWebImageDownloaderOperation.m:34)
11  libobjc.A.dylib                 0x38bf1d9c object_cxxDestructFromClass(objc_object_, objc_class_) + 112
12  libobjc.A.dylib                 0x38bfb5f2 objc_destructInstance + 30
13  libobjc.A.dylib                 0x38bfb616 object_dispose + 10
14  Foundation                      0x2c1a518a -[NSOperation dealloc] + 86
15  libobjc.A.dylib                 0x38c0cd5a objc_object::sidetable_release(bool) + 162
16  QWeiboSDK4iOSDemo               0x003b59d4 __destroy_helper_block_144 (SDWebImageManager.m:0)
17  libsystem_blocks.dylib          0x3918dadc _Block_release + 212
18  QWeiboSDK4iOSDemo               0x003b68fc -[SDWebImageCombinedOperation cancel](SDWebImageManager.m:324)
19  QWeiboSDK4iOSDemo               0x0025fc7e -[UIView(WebCacheOperation) sd_cancelImageLoadOperationWithKey:](UIView+WebCacheOperation.m:44)
20  QWeiboSDK4iOSDemo               0x00336ae2 -[UIImageView(WebCache) sd_cancelCurrentImageLoad](UIImageView+WebCache.m:123)
21  QWeiboSDK4iOSDemo               0x00334a6e -[UIImageView(WebCache) sd_setImageWithURL:placeholderImage:options:progress:completed:](UIImageView+WebCache.m:42)
22  QWeiboSDK4iOSDemo               0x0033463c -[UIImageView(WebCache) sd_setImageWithURL:](UIImageView+WebCache.m:18)
23  QWeiboSDK4iOSDemo               0x002afe04 -[KSHomeCell lazyLoad](KSHomeCell.m:104)
24  QWeiboSDK4iOSDemo               0x002c926e -[KSHomeViewController lazyLoadVisiableCells](KSHomeViewController.m:717)
25  QWeiboSDK4iOSDemo               0x002c63f4 -[KSHomeViewController scrollViewWillBeginDragging:](KSHomeViewController.m:490)
26  UIKit                           0x2eb723b2 -[UIScrollView _updatePanGesture] + 274
27  UIKit                           0x2eb5fad6 _UIGestureRecognizerSendActions + 290
28  UIKit                           0x2ea0e4c4 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 664
29  UIKit                           0x2ee20716 ___UIGestureRecognizerUpdate_block_invoke661 + 42
30  UIKit                           0x2e9d7efc _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 212
31  UIKit                           0x2e9d5dda _UIGestureRecognizerUpdate + 2922
32  UIKit                           0x2ea0c8bc -[UIWindow _sendGesturesForEvent:] + 780
33  UIKit                           0x2ea0c198 -[UIWindow sendEvent:] + 520
34  UIKit                           0x2e9e2a38 -[UIApplication sendEvent:] + 192
35  UIKit                           0x2ec56144 _UIApplicationHandleEventFromQueueEvent + 13884
36  UIKit                           0x2e9e148c _UIApplicationHandleEventQueue + 1292
37  CoreFoundation                  0x2b50b58a __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 10
38  CoreFoundation                  0x2b50a99a __CFRunLoopDoSources0 + 214
39  CoreFoundation                  0x2b509000 __CFRunLoopRun + 768
40  CoreFoundation                  0x2b45761c CFRunLoopRunSpecific + 472
41  CoreFoundation                  0x2b45742e CFRunLoopRunInMode + 102
42  GraphicsServices                0x328050a4 GSEventRunModal + 132
43  UIKit                           0x2ea41804 UIApplicationMain + 1436
44  QWeiboSDK4iOSDemo               0x00043362 main (main.m:16)
45  libdyld.dylib                   0x39172aaa tlv_initializer + 2

**Comment by timkoma** [comment]
I'm using 3.7.1 and I'm still getting crash.
@zhongchao-han can I see you fix ?
