### ISSUE TITLE
Domain=NSURLErrorDomain Code=-1100 "The operation couldn’t be completed

### ISSUE THREAD

**Issue by hungbv** [SDWebImage/SDWebImage#986]
While downloading image, I lost my connection. Then, I reconnect to Internet and re-download the image again. however, I can't download this image anymore, each time I tried to download the image, I got error status: "Domain=NSURLErrorDomain Code=-1100 "The operation couldn’t be completed. (NSURLErrorDomain error -1100.)". please help me !

**Comment by f33chobits** [comment]
I got this error on this image:
http://img4.imgtn.bdimg.com/it/u=2496578486,2607734154&fm=21&gp=0.jpg
and add the retry option still not working. But it can be displayed in the web browser. Is there something wrong with that image file?

**Comment by mythodeia** [comment]
@f33chobits using your image i get:
```403 "The operation couldn’t be completed. (NSURLErrorDomain error 403.)```
according to wiki:
```
A web server may return a 403 Forbidden HTTP status code in response to a 
request from a client for a web page or resource to indicate that the server 
can be reached and understood the request, but refuses to take any further action.
```

**Comment by f33chobits** [comment]
Request from a different country might have been blocked. Bad thing.
Never mind. We have changed another image file and it seems working now.
Thanks.

**Comment by mythodeia** [comment]
:+1:

**Comment by hungbv** [comment]
When I tried to download image with Japanese words in download url like this "名称未設定-4.png", error happened: "Error Domain=NSURLErrorDomain Code=500 "The operation couldn’t be completed. (NSURLErrorDomain error 500.)". It works well when I change url with no Japanese words in the URL. How can I download image with Japanese word in my url? please help me, thanks

**Comment by mythodeia** [comment]
@hungbv i think this is unrelated with the current closed issue.
maybe [this](https://github.com/rs/SDWebImage/issues/1126) can help you

**Comment by hungbv** [comment]
@mythodeia I'll try it, thank you :)

**Comment by donly** [comment]
Yes, I have found this issue and fixed.
By adding a header field `User-Agent` with the value of `Mozilla/5.0 (iPod; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1`, which same as to the Safari Browser's, everything works well again

**Comment by lvXiaoPeng** [comment]
I just received error code -1100 when I tried to request image from "http://ww4.sinaimg.cn/thumbnail/b89e3f89gw1fa24q3eszgj20go09d0up.jpg##http://ww1.sinaimg.cn/thumbnail/b89e3f89gw1fa24q2w8thj20go06aq3q.jpg",It's OK in browser to see the image.I have tried SDWebImageRetryFailed operation and it doesn't work.Please help me ,thanks!
