### ISSUE TITLE
SDWebImageDownloaderOperation not thread-safe when cancelling during finish loading

### ISSUE THREAD

**Issue by newacct** [SDWebImage/SDWebImage#990]
Consider the following sequence of events:
1. An SDWebImageDownloaderOperation, which uses its own worker thread for delegate methods, gets called with connectionDidFinishLoading: (on its worker thread) when the download finishes
2. Inside -[SDWebImageDownloaderOperation connectionDidFinishLoading:], it first sets self.thread to nil inside a synchronized(self) block, then it leaves the synchronized block
3. Suppose then that someone cancels the operation on the main thread. Although the body of -[SDWebImageDownloaderOperation cancel] also has a synchronized(self) block, the other synchronized(self) has already exited, so this can run
4. -[SDWebImageDownloaderOperation cancel] sees that self.thread is nil, so it executes [self cancelInternal] synchronously (on the main thread), rather than asynchronously performing cancelInternalAndStop on the worker thread like it would if self.thread were still non-nil
5. -[SDWebImageDownloaderOperation cancelInternal] calls [self reset], and -[SDWebImageDownloaderOperation reset] sets self.imageData to nil
6. At the same time that (5) above is executing, -[SDWebImageDownloaderOperation connectionDidFinishLoading:] is still running on the worker thread, during which it reads self.imageData
7. imageData is a non-atomic property, and reading and writing to it concurrently on multiple threads is unsafe (For example, the property can be set to nil and the object deallocated on one thread after it has been read on another thread and before it could be retained.)

**Comment by mythodeia** [comment]
@newacct 
can you check if this recent pull request fixes any issues for you?
https://github.com/rs/SDWebImage/pull/1031

**Comment by newacct** [comment]
@mythodeia I don't think so. That change doesn't touch SDWebImageDownloaderOperation.

**Comment by mythodeia** [comment]
it made some changes in the SDWebImageOperation and how it cancels sub operations fixing a race condition, making thread-safe! 
It also made a small change when calling the ``` [self.imageDownloader downloadImageWithURL ... ``` which basically inits in return the SDWebImageDownloaderOperation.
Thats why i asked if that pull request in its entirety fixed the cancelling issues for you

**Comment by newacct** [comment]
@mythodeia This is an internal design issue in SDWebImageDownloaderOperation, which occurs even when assuming that the SDWebImageDownloaderOperation API is used 100% correctly by outside code. So fixing bugs in other code will not help.

**Comment by timkoma** [comment]
At least it correctly sets cancelBlock id <SDWebImageOperation> subOperation

**Comment by timkoma** [comment]
see also my comment in https://github.com/rs/SDWebImage/issues/910

**Comment by timkoma** [comment]
FYI: 
same problem with self.thread in
- (void)connection:(NSURLConnection *)connection didFailWithError:(NSError *)error {

**Comment by timkoma** [comment]
I have possible fix, but I haven't time to test it carefuly. Anyway you can inspire at least.
Here is a commit
https://github.com/timkoma/SDWebImage/commit/8d8b27cc2639f6deb85e0c0bd91432b943ee2df5

**Comment by timkoma** [comment]
@newacct please review my PR

**Comment by newacct** [comment]
@timkoma So basically, it fixes it by not setting self.thread to nil in the beginning of connectionDidFinishLoading?

**Comment by timkoma** [comment]
@newacct No, more things needs to be changed, see may comments in PR https://github.com/rs/SDWebImage/pull/1044

**Comment by bpoplauschi** [comment]
Let's close this issue, see if it happens again with 4.0.0 (4.0.0-beta is available for download, 4.0.0 official release is on its way).
